"""Archive main-text conventions and unresolved source statements separately."""
import json
from save_inventory import ROOT,PID

def main():
    aux=[]
    def add(n,s,ps,note,deps=()):aux.append(dict(local_id='A'+str(n),statement_original=s,evidence=[dict(page=p,location='Original main-text context A'+str(n)) for p in ps],scope_note=note,depends_on=list(deps)))
    add(1,r'''Here, $\epsilon_i$'s are assumed to be centered error independent of $X$''',[4],'Noise convention carried from the regression setup. The main text does not explicitly state independence across observations or independent test sampling.')
    add(2,r'''where $\beta_1$ is the smoothness index of the univariate component and $\beta_2$ is the smoothness index of the bivariate components of $f_0$.''',[8],'Original interpretation of the two smoothness indices used in theorem rates. Assumption2.3 uses a generic beta.',['D4'])
    add(3,r'''Here $f^\star=\phi_1^\star+\phi_2^\star$ is (approximately) the best approximator of $f_0$ in terms of $L_2(P_X)$ norm among the class of neural networks, i.e.
\[
\|f^\star-f_0\|_{L_2(P_X)}\le\inf_{\phi_1\in\mathcal F^1_{NN},\phi_2\in\mathcal F^2_{NN}}\|f_0-\phi_1-\phi_2\|_{L_2(P_X)}+\tau_n
\]
for some small tolerance $\tau_n$ to be specified later.''',[8],'Original aggregate approximate minimizer. It is not the componentwise sparse approximant sum(3.4); theorem2.9 defines rho_n and V_n in its own statement.',['D1','D6'])
    add(4,r'''In this section, we establish the minimax lower bound for estimating the non-parametric 2-way interaction model (2.2), when the dimension of the covariate $d=d(n)\to\infty,d=o(n)$ and satisfies Assumption 2.6.''',[12],'Explicit Section2.3 context for2.12, despite omission of2.6 in its theorem body.',['D1','D9'])
    add(5,r'''In this section, we present our analysis for the fixed design model, where we assume $X_i$'s to be fixed.''',[14],'Section3.1 context for3.2/3.5; the theorem bodies still cite random-density Assumption2.1. This tension is retained rather than repairing the hypotheses.')
    add(6,r'''Once we have $\widehat S_1,\widehat S_2$, then we solve the unpenalized least square problem only on the active set based on the second half of the data (Step 4 of Algorithm 1) to obtain the final estimate.''',[17],'Original second-half refit convention omitted from the explicit sum in Eq3.17.',['D23'])
    add(7,r'''Suppose $V(W,L)$ denotes the largest VC- dimension of a ReLU network with $W$ parameters and $L$ layers. There exist constants $c_1,c_2>0$ such that
\[
c_1WL\log(WL)\le V(W,L)\le c_2WL\log WL.
\]''',[10],'Original Lemma2.8, a cited lemma rather than an inventoried theorem. Records intended activation and VC terminology without importing its proof or asserting this is a definition of pseudo-dimension.',['D5'])
    add(8,r'''Since our problem is highly non-convex in terms of the weights of the neural network, it is not immediately clear whether such an algorithm will converge to global minima. To avoid such issues, we work with a neural network that minimizes empirical risk in our article. Understanding the properties of the gradient descent-based estimator is left open for future research.''',[10],'Original exact ERM/global optimization convention; no computational guarantee inferred.',['D8'])
    add(9,r'''The constants $c_1,c_2$ will be mentioned explicitly in the proof.''',[17],'Algorithm1 threshold constants are deferred to appendix proof; not recovered from outside scope.',['D23'])
    add(10,r'''As $\sigma(\cdot)$ is ReLU, we have the identity $\sigma(x)-\sigma(-x)=x$.''',[20],'Main-text proof explicitly identifies the intended activation. This is notation context, not a proof-only dependency on a separate theorem.',['D5'])
    bindings={
'T2.7':'Original depth-dependent structured classes(2.4)–(2.5), two-way mean model, beta1/beta2 smoothness, and Section2.1 setup including Assumptions2.1,2.2,2.6. N_i L_i are chosen inline and C1,C2,C3 have the printed independence scope. Infimum repeats phi2 while integrand has phi1; retain as unresolved source binding. E integrates X; Euclidean absolute square, binomial coefficients, floors and growth notation are ambient.',
'T2.9':'Original clipped global ERM(2.3), instantiated with revised constant-depth classes(2.7)–(2.8). Assumptions2.1–2.3 and2.6 are explicit. S_n is the training sample; X is the test/design argument. Rho_n^2 and V_n are defined with their bounds inline, not extra theorems or sparse component errors. Conditional expectation and Op require the data-law conventions recorded as unresolved where unstated.',
'T2.12':'Two-way mean class with generic Sigma(beta,L), interpreted through2.3 and the beta1/beta2 convention in Remark2.5. Assumptions2.1–2.3 explicit; Section2.3 explicitly also fixes growing d=o(n) satisfying2.6. Minimax risk M has an expectation; estimator/data measurability and design-law supremum conventions are not specified. Printed lower c versus final C is retained.',
'T3.2':'Sparse model and component smoothness; explicit Assumptions2.1–2.3,3.1 and component bound3.6. Penalized global estimator3.5 uses empirical L2 norms and truncated component network classes. Rho component errors use3.8; lambda choices and V formulas are defined in the continuation on15. Fixed-design context coexists with density Assumption2.1. No RSC is assumed.',
'T3.5':'Inherit precisely the hypotheses and penalty choices of3.2 plus full Assumption3.4 RSC, including its cone slack and approximant sum3.4. Do not import3.2 conclusion as a hypothesis. Phi-hat in prose and f-hat in bound refer to the estimator3.5 but are not silently rewritten.',
'T3.8':'Section3 sparse setup and its standing3.1 growth condition, plus inherited identifiability/boundedness convention2.2; random-design distribution under2.1 is explicit in Section3.2. The theorem explicitly requires the RSC event to hold with high probability and3.7 signal strength, and uses Algorithm1 final refit and penalty choices inherited through3.5/3.2. It does not explicitly inherit every conclusion of3.5 or prove RSC from a density upper bound. The log-factor qualifier and architecture tuning ambiguity remain.',
'T3.9':'Sparse model3.1 defines F_sp including component smoothness, S1,S2 and sparsities. Assumptions2.2,2.1 are explicit; the standing Section3 growth assumption3.1 is retained as section context, not inserted in original text. No RSC or neural-network estimator is required to state this infimum over arbitrary estimators. Preserve expectation-free population-norm display, max operations and log(d^2/s2) term.'}
    refs=[]
    def ref(n,target,kind,note):refs.append(dict(claim_id=PID+'/T'+n,target=target,reference_kind=kind,note=note))
    ref('2.7','Section2.1 setup and Assumption2.6','section_convention','Dense growth is adopted before the theorem;2.1 and2.2 describe its model and design. The proof on23 confirms the use of2.6 but is not substituted for the statement.')
    ref('2.9','Revised classes(2.7)–(2.8)','definition_reference','Same notation F_NN^1,F_NN^2 changes architecture on10; retain this version for2.9.')
    ref('2.12','Section2.3 introductory paragraph','section_convention','Explicitly adds d growing,o(n), and2.6 outside the theorem body.')
    ref('3.5','Theorem3.2 hypotheses and penalty definitions','assumption_reference','Includes2.1–2.3,3.1,3.6 and3.7 choices, not its slow-rate conclusion.')
    ref('3.8','Algorithm1 and Section3.2','definition_reference','Includes data split, thresholded active sets and second-half unpenalized refit; preserve missing threshold constants and sample-normalization convention.')
    ref('3.8','Theorem3.5 penalty parameters','definition_reference','Resolve lambda to3.7; this citation does not itself import the complete3.5 theorem as a hypothesis.')
    for n in ['3.8','3.9']:ref(n,'Section3 standing Assumption3.1','section_convention','Section3 introduces this growth assumption before splitting into fixed design, random design and lower-bound subsections. Its omission in the later theorem body is recorded; no theorem text is expanded.')
    for n,a in [('2.9','A.1'),('2.12','A.2'),('3.2','A.3'),('3.5','A.3'),('3.8','A.4'),('3.9','A.5')]:ref(n,'Appendix '+a,'proof_only','Appendix body is outside scope and not read or imported as a statement dependency.')
    issues=[]
    def issue(key,ps,note):issues.append(dict(issue_id=key,evidence=[dict(page=p,location='Source issue '+key) for p in ps],note=note))
    issue('registered-version',[1,23],'Registered arXiv2302.05851v1 marked12Feb2023,46pages; not asserted identical to the2024 published text. Main text ends before references on23, clipped645; Appendix A starts26 and is excluded. Seven Theorems retained.')
    issue('theorem-2.7-bound-variables',[9],'Infimum repeats phi_2 for both classes while integrand contains phi_1. Preserve it; correcting the first index requires a separate normalized statement. Slash-form exponents n^{1/2(2beta1+1)} and n^{1/2(beta2+1)} are retained without changing precedence.')
    issue('smoothness-definition',[5,8,12],'Assumption2.3 gives generic beta and L, with floor(beta) derivatives and exponent beta-floor(beta), including zero at integer beta. It does not specify all lower derivative bounds, norm conventions, uniform component constants or separate Sigma notation; Sigma is identified by reference on12. Beta1/beta2 convention is in Remark2.5. Do not silently use a different standard Holder ball.')
    issue('network-architecture',[6,7,10,13],'Class F_NN definition does not explicitly fix activation, exact versus at-most architecture counts, bias counting or integer rounding. ReLU appears in Lemma2.8 and main proof20. Structured aggregate classes(2.4)–(2.5), revised constant-depth classes(2.7)–(2.8), and component classes(3.2)–(3.3) are distinct. Taking L=1 in LlogL is not a literal derivation of positive constant depth.')
    issue('sampling-and-norms',[4,10,14,17,19],'Centered errors independent of X are stated, but independence across observations and independent test X are not explicit. Fixed-design3.2/3.5 still cite a density assumption. Population norm versus empirical norm must stay distinct;3.9 has no expectation over training data or probability qualifier.')
    issue('centering-bounds',[5,14],'Identifiability uses Lebesgue marginals, not P_X-centering or conditional expectations. Assumption2.2 bounds the sum f0;3.6 separately bounds individual components and truncates networks. Joint density upper bound does not imply coordinate independence or a uniform positive lower bound.')
    issue('optimizer-selection',[7,10,14,18],'Argmin definitions omit existence, uniqueness and measurable selection; no weight compactness is imposed. Exact global ERM is not guaranteed to be found by gradient descent. Output clipping for2.3 differs from individual-component clipping in Section3.')
    issue('lower-bound-labels',[12,19],'Theorem2.12 uses c in the bound and C in the final sentence. Both minimax displays put X~P_X beneath a supremum without a law family;3.9 omits sampling expectation altogether. Retain both original displays rather than identifying their risks.')
    issue('sparse-indexing',[13,15,18,19],'S2 is defined as a subset of[d]×[d], but later formulas require distinct ordered pairs k<l. Eq3.4 uses active approximants only, whereas RSC3.9 references inactive approximants without defining their zero extension. Empty sparsity sets and0*log(d/0) conventions are unstated.')
    issue('approximation-witness',[13,15,16],'Original component approximant passage mixes jk and kl indices and attributes existence to2.9. It specifies approximation bounds rather than an exact argmin, although subsequent prose calls it best approximator. RSC quantifies any decomposed function without expressly restricting component classes.')
    issue('penalty-and-curvature',[14,15,16],'Both complete radicands contain their log(d)/n terms;3.2 retains linear lambda and half lambda squared terms. RSC has approximation slack and squared-penalty slack. Constants C3,C4 and kappa uniformity are not fully quantified. Theorem3.5 changes phi-hat in prose to f-hat in its formula.')
    issue('sample-split-algorithm',[17,18],'Algorithm1 splits odd n explicitly, fits on D1 and by preceding prose refits on D2. Its empirical norms and sum_i/n retain full-sample notation; no index range/normalization change is printed. Threshold constants are deferred to appendix proof, which remains outside scope.')
    issue('signal-strength',[18],'Assumption3.7 bounds unsquared component L2 norms by rn; its display is a square root. Following prose calls rn precisely the Corollary3.6 rate, which is a squared-error rate. Preserve the distinction; do not square the signal hypothesis or remove the radical.')
    issue('random-design-rate',[17,18],'Theorem3.8 assumes RSC with high probability; it does not derive RSC from Assumption2.1. It gives an Op expression only upto log-factors, with no exponent. Lambda refers to3.5, but network width choices for the claimed optimized rate are not explicitly repeated. Do not strengthen this into a fully specified tuned rate.')
    issue('scope-of-standing-growth',[9,12,13,14,18,19],'Assumption2.6 is adopted before2.7 and expressly repeated in Section2.3 before2.12. Section3 adopts3.1 before its three subsections. Retain these section conventions separately from explicit theorem hypotheses; later3.8/3.9 do not repeat3.1. This census records the paper’s stated section scope without asserting minimal necessary hypotheses.')
    data=dict(paper_id=PID,unranked_auxiliary_passages=aux,statement_local_bindings=bindings,source_claim_references=refs,source_issues=issues,unresolved_external_prerequisites=[dict(target='Algorithm1 threshold constants c1,c2',source='Main-text page17 defers exact choices to the proof in Appendix A.4.',status='outside_scope_unresolved')],ambient_prerequisites=['Finite-dimensional Euclidean spaces, indexed sums, binomial coefficients, floors, Lebesgue integrals and marginalization, probability densities, expectations and conditional expectations.','Supremum norm, empirical L2 seminorm and population L2 norm; norm2 in Section3.2 is interpreted using its explicit population-loss paragraph, without adding a training expectation to3.9.','Asymptotic sequences in n,d,s1,s2 and architecture sizes; Op, o(1), comparison symbols and logarithmic factors. Constants uniform in d only where expressly stated.','Holder smoothness as printed; finite ReLU networks and scalar clipping, architecture constants and measurable selection of empirical minimizers remain incompletely specified.','Minimax infima over estimators, signal strength, global penalized empirical risk and sample splitting. No computational, proof-correctness or mathlib-availability verdict is implied.'],validation_limits='Source census preserves complete main-text statements and their original assumptions, dependencies and ambiguities. Structural validation cannot prove the theorems, choose unstated constants or resolve unspecified sampling, norm, architecture and optimizer conventions. Appendix bodies are excluded.')
    (ROOT/'ambient-prerequisites.json').write_text(json.dumps(data,indent=2,ensure_ascii=False)+'\n')
if __name__=='__main__':main()
