"""Preserve source conventions and unresolved wording without repairing either theorem."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];PID=ROOT.name
aux=[]
def add(aid,text,pages,loc,meaning):
    aux.append(dict(auxiliary_id=aid,statement_original=text.strip(),evidence=[dict(page=p,location=loc) for p in pages],resolution=meaning))
add('A1',r'''We write the squared $L_2(Q)$ norm of a function as $\|g\|_Q^2=\int g(z)^2\,dQ(z)$. The sup-norm is denoted by $\|f\|_\infty=\sup_{z\in\mathcal Z}|f(z)|$. For a matrix $A$ we let $\|A\|$ and $\|A\|_2$ denote the operator/spectral and Frobenius norms, respectively, and let $\lambda_{\min}(A)$ and $\lambda_{\max}(A)$ denote the minimum and maximum eigenvalues of $A$, respectively. We write $a_n\lesssim b_n$ if $a_n\leq Cb_n$ for $C$ a positive constant independent of $n$, and $a_n\asymp b_n$ if $a_n\leq Cb_n$ and $b_n\leq Ca_n$ (i.e., if $a_n\lesssim b_n$ and $b_n\lesssim a_n$). We write $a_n\sim b_n$ to mean that $a_n$ and $b_n$ are proportional, i.e., $a_n=Cb_n$ for some $C$. We also use $a\vee b=\max(a,b)$ and $a\wedge b=\min(a,b)$.''',[4],'Section 2 — norms, comparison symbols and extrema','The matrix norm without a subscript is spectral, while the subscript 2 is Frobenius. The theorem’s tilde means proportionality, not ratio tending to one. All fixed-factor comparisons are distinct from little-o. Maximum notation is explicit, but its precedence inside the rate exponent is not parenthesized fully.')
add('A2',r'''We use the shorthand $\mathbb P_n(f)=\mathbb P_n\{f(Z)\}=\frac1n\sum_{i=1}^nf(Z_i)$ to write sample averages, and similarly $\mathbb U_n(f)=\mathbb U_n\{f(Z_1,Z_2)\}=\frac1{n(n-1)}\sum_{i\ne j}f(Z_i,Z_j)$ for the U-statistic measure.''',[4],'Section 2 — empirical and U-statistic measures','The second-order average runs over ordered distinct pairs. Its kernel need not be symmetrized separately. The averaging sample has n>=2 for this expression; the independent nuisance training sample is D^n from Definition 2.')
add('A3',r'''Let $Y^a$ denote the counterfactual outcome that would have been observed under treatment level $A=a$. Then, under the assumptions of consistency (i.e., $Y=Y^a$ if $A=a$), positivity (i.e., $\epsilon\leq\mathbb P(A=1\mid X)\leq1-\epsilon$ with probability one, for some $\epsilon>0$), and no unmeasured confounding (i.e., $A\perp\!\!\!\perp Y^a\mid X$), the quantity $\tau(x)$ also equals the conditional average treatment effect (CATE)
\[
\mathbb E(Y^1-Y^0\mid X=x).
\]''',[2],'Section 1 — causal interpretation of the regression contrast','These assumptions identify the observed regression contrast with a counterfactual effect. They are not silently added to the definition of the observed-data statistical target or to the lower-bound model. Theorem 2 separately states propensity overlap.')
add('A4',r'''Note again that, as with other higher-order estimators, the estimator (3) depends on an initial estimate of the covariate distribution $F$ (near $x_0$), through $\widehat\Omega$. Importantly, we do not take this estimator $\widehat F$ to be the empirical distribution, in general, since then our optimal choices of the tuning parameter $k$ would yield $\widehat\Omega$ non-invertible; this occurs with higher-order estimators of pathwise differentiable functionals as well [Mukherjee et al., 2017].''',[18],'Remark 8 — restriction on the covariate distribution estimator','Definition 2 is a procedure conditional on suitable nuisance inputs; substituting the empirical covariate distribution is not justified by the theorem. No alternative density estimator or spectral regularization is constructed in this census.')
add('A5',r'''Similarly for $\widehat Q\theta$ we have
\[
\mathbb E\{\rho_h(X_1)K_h(X_1)\widehat\varphi_{a2}(Z_1,Z_2)K_h(X_2)\rho_h(X_2)^{\mathsf T}\theta\mid D^n\}\tag{9}
\]
\[
=-\int\rho(v_1)\{\pi^*(v_1)-\widehat\pi^*(v_1)\}\widehat\Pi_b(\pi^*\tau_h^*)(v_1)\,dF^*(v_1)
\]''',[20],'Section 4.2 — displayed Q correction used in the bias calculation','The expectation ends in rho_h(X_2)^T, whereas Definition 2’s Q-hat correction ends in rho_h(X_1)^T. This source excerpt records the discrepancy; the bias proof is not used to replace the actual estimator or add proof-only graph edges.')
add('A6',r'''where we use the change of variable $v=\frac12+\frac{x-x_0}h$ and again define for any function $g:\mathbb R^d\mapsto\mathbb R$ its corresponding stretched version as $g^*(v)=g(x_0+h(v-1/2))$. To ease notation it is left implicit that any integral over $v$ is only over $\{v:\|v-1/2\|\leq1/2\}$.''',[19,20],'Section 4.2 — stretched functions and local integration convention','Theorem 2’s F-star norms use unstarred nuisance names, although the calculations evaluate their stretched versions. This passage specifies the intended variable change and local integration domain. It does not specify a measure normalization, and the Euclidean-ball domain differs from the explicit cube in the estimated Gram integral.')
add('A7',r'''For simplicity, the lower bound result in Theorem 1 is given for a large model in which the covariate density is only bounded. However, as discussed in detail later in Section 4 and Remark 11, for the stated rate to be attainable more conditions on the covariate density are required. In Section B.8 of the Appendix, we give a particular submodel of $\mathcal P$ under which upper and lower bounds on the minimax rate match up to constants; it will be important in future work to further elucidate the role of the covariate density in CATE estimation.''',[5],'Remark 2 — model limitation on attainability','The upper bound is not a matching uniform guarantee over every distribution in the broad lower-bound model. The source’s appendix submodel is explicitly not inspected or reconstructed.')
add('A8',r'''Crucially, Condition 4 allows the CATE $\tau(x)$ to have its own smoothness $\gamma$, which is necessarily at least the regression smoothness $\beta$, but can also be much larger, as described in the Introduction.''',[5],'Section 3 — smoothness ordering stated in surrounding prose','The surrounding text treats gamma>=beta as its intended smoothness regime, repeated on page 14. Neither theorem lists it as a separate numbered hypothesis. With only the displayed condition on the control regression, this ordering is not automatically a logical consequence, so the original theorem statements remain unchanged.')
add('A9',r'''Let $s\equiv(\alpha+\beta)/2$.''',[5],'Theorem 1 — average nuisance smoothness','Theorem 2 retains this average-smoothness abbreviation without rebinding s. It is distinct from the generic s in the Hölder approximation property (6).')
add('A10',r'''Specifically, the result of Theorem 2 can also be written as
\[
\mathbb E_P|\widehat\tau(x_0)-\tau_P(x_0)|\lesssim n^{-1/\left(1+\frac d{2\gamma}+\frac d{4s}\vee\left(1+\frac d{2\gamma}\right)\right)}+R_{3,n},\tag{15}
\]
for the third-order error term
\[
R_{3,n}=\|(d\widehat F^*/dF^*)-1\|_\infty\|\widehat\pi-\pi\|_{F^*}(\|\widehat\mu_0-\mu_0\|_{F^*}+h^\gamma),
\]
so that Condition 1 simply requires this third-order term to be of smaller order than the first minimax optimal rate in (15)''',[25],'Remark 11 — third-order distribution-estimation remainder','The product form explains the density-estimation condition, but the theorem uses a fixed-factor less-than comparison rather than an explicit little-o. The same unparenthesized maximum appears in its rate denominator; its original grouping is retained.')
issues=[]
def issue(key,text,pages):issues.append(dict(issue_id=key,description=text,evidence=[dict(page=p,location='Inspected main-text source convention') for p in pages],resolution_status='source_preserved'))
issue('S1','The strict floor in the Hölder definition is the largest integer strictly smaller than s, so at an integer s it equals s-1. This convention also fixes the degree and dimension of the Legendre basis; the usual floor at integers is not substituted.',[4,15])
issue('S2','The lower-bound model bounds the covariate density only from above. It does not explicitly require positivity near x_0 or treatment overlap. Conditional regression versions can then be unidentified at some points. Theorem 2 adds overlap and matrix conditions; these are not transferred to Theorem 1.',[4,5,24])
issue('S3','The text calls gamma necessarily at least beta and later repeats gamma>=beta, but the two theorem statements do not separately list this ordering. The displayed lower-bound model constrains mu_0 and tau independently. The intended regime in the prose is recorded without inventing an extra original hypothesis.',[5,14,24])
issue('S4','The vector norm is defined as Euclidean, so the kernel and localized-basis indicators select a ball. Later prose describes stretching a cube, and the estimated Gram integral explicitly runs over [0,1]^d. A later convention restricts v integrals to a Euclidean ball inside that cube. These differing domains are retained, not silently reconciled by using a sup norm.',[4,15,16,17,18,20])
issue('S5','F-star is written dF(x_0+h(v-1/2)) and called a local distribution, with no explicit normalization. For an ordinary bounded density, the literal restricted pushforward has mass of order h^d, while the change-of-variable formulas with K_h and the assumed eigenvalue scales suggest a rescaled interpretation. No missing h^-d factor or conditional-probability normalization is inserted.',[16,18,19,20,24])
issue('S6','Definition 2’s Q-hat U-statistic term ends in rho_h(X_1)^T, but equation (9) in the bias calculation uses rho_h(X_2)^T. These are different kernels. The definition and theorem reference retain the printed estimator; the discrepancy is documented separately.',[16,20])
issue('S7','The first-order treatment correction is A(A-pi-hat), not (A-pi-hat)^2. The first-order outcome correction uses the control regression mu_0, not the marginal regression eta. Familiar R-learner formulas are not substituted for these specific source formulas.',[4,16])
issue('S8','The main text displays Omega-hat explicitly and uses Omega in the coordinate formula for the F-star-weighted linear projection. It does not separately display Omega=integral bb^T dF-star. Identifying Omega as the population Gram matrix is a source-backed interpretation of that projection formula, not a verbatim extra definition.',[16,18,20])
issue('S9','The norm of dF-hat-star/dF-star is said to be bounded above and below away from zero. A lower bound on this sup norm does not imply a pointwise lower bound on the density ratio. The theorem’s literal condition is retained, without strengthening it to mutual domination.',[22,24])
issue('S10','Condition 1 and equation (15) print 1+d/(2gamma)+d/(4s) vee (1+d/(2gamma)) without parentheses identifying the two arguments of the maximum. Interpreting only d/(4s) versus 1+d/(2gamma) as the maximum makes the expression agree with the piecewise rates; taking the entire preceding sum as one operand does not. Both the ambiguous formula and the unambiguous piecewise conclusion are preserved.',[24,25])
issue('S11','Condition 1 divides by the product of nuisance-error norms, which can be zero. No zero-denominator convention is given. The product remainder in Remark 11 supplies an interpretation but is not substituted for the theorem’s original fraction.',[24,25])
issue('S12','Condition 1 uses a fixed-factor less-than comparison. Remark 11 describes the third-order remainder as smaller order, which is stronger if read as little-o. The comparison symbols retain their explicit Section 2 meanings.',[4,24,25])
issue('S13','The nuisance estimators are trained on D^n independently of the sample used by U_n, and the empirical and U-statistic terms use the common evaluation sample. The source gives no cross-fitting or ensemble averaging rule and does not state a separate training-size asymptotic. No such procedure is added.',[4,16,18])
issue('S14','Remark 8 expressly says that an ordinary empirical covariate distribution need not make Omega-hat invertible at the chosen k. The high-level theorem does not construct nuisance estimators satisfying every condition. The census records its required inputs, rather than claiming an unconditional ready-to-run estimator.',[18,24,25])
issue('S15','The estimator uses inverse Q-hat and inverse Omega-hat with no finite-sample singularity fallback. Condition C contains an inverse-error bound, implicitly requiring that inverse to exist; density-ratio norm bounds alone do not specify an estimator regularization rule.',[16,24])
issue('S16','Theorem 2 states boundedness conditions on random nuisance quantities without explicitly saying whether they hold surely, with high probability, or conditionally. Its conclusion is an expectation bound. No high-probability-only condition or unmentioned tail/uniform-integrability condition is supplied.',[24])
issue('S17','F-star norm expressions in the theorem use unstarred nuisance functions, whereas the main-text calculation defines stretched versions g-star(v)=g(x_0+h(v-1/2)). This suppressed composition and the h-dependent measure must be kept visible for subsequent formalization.',[18,19,20,24])
issue('S18','The polynomial basis has total-degree dimension choose(d+strict-floor(gamma),strict-floor(gamma)), not the full tensor-product dimension (strict-floor(gamma)+1)^d. The correction basis has a separate increasing dimension k. The two bases and their population matrices are not merged.',[15,16])
issue('S19','The tuning notation tilde is defined as proportionality, while k is a basis dimension and must be an integer. The source does not specify integer rounding. The strict low-smoothness branch and otherwise branch include the elbow equality exactly as printed.',[4,23,24])
issue('S20','The lower bound has an infimum over estimators and supremum over the broad model. The upper bound lacks that supremum and adds distribution-estimation and regularity assumptions. Remark 2 explicitly limits matching to a more restricted submodel whose appendix details are excluded.',[5,24])
issue('S21','The observed regression contrast is defined without counterfactual variables. Consistency, positivity and no unmeasured confounding identify it as a causal effect in the introduction; these are not all automatically statistical prerequisites of the lower bound.',[2,4,5])
issue('S22','Remark 1 discusses replacing control-regression smoothness by marginal-regression smoothness and changing s to min(alpha,s), but the actual results for that model are in Appendix A. This alternative model is not substituted into the two inventoried main-text Theorems.',[5])
issue('S23','Theorem 2’s reference to condition (6) is the displayed Hölder approximation property, not Proposition 6. Main-text propositions used in the proof are not additional inventoried Theorems or automatically imported assumptions. Remark 10 repeatedly calls A-C Condition 2, and Proposition 6 refers to its own assumptions; these reference defects do not change the theorem’s explicit list.',[18,22,24])
resolution={
 'shared':'The source uses blackboard P for the true observed-data law and generic P when indexing models. X lies in [0,1]^d, A is binary, and the statistical target is tau=mu_1-mu_0 at an interior x_0. Smoothness orders are positive in the usual Hölder interpretation, radii are fixed independently of n, and the strict-floor convention is explicit. A1 resolves norms and comparison symbols, A2 empirical/U-statistic normalizations, A3 the optional causal interpretation, and A9 the average smoothness abbreviation.',
 '1':'D1 supplies iid sampling and the covariate density f. D2 supplies the propensity and treatment-specific regressions, D3 the pointwise target and mean absolute error, and D4 the exact smoothness class. The statement itself defines the model, s=(alpha+beta)/2, both rate branches and the sufficiently-large-n qualifier. It does not require the proposed estimator, independently trained nuisance inputs, approximation basis, positivity or the upper-bound density-estimation conditions. Its generic estimator is any measurable sample-based estimator of the pointwise target; no appendix lower-bound construction is required for the statement.',
 '2':'D5 supplies K_h, the strict-floor Legendre degree, total-degree dimension q and affine localization; D6 supplies the separate k-dimensional correction basis. D7 gives the independently trained nuisance estimates and Omega-hat, and D8 the full estimator with all four correction functions and both empirical terms. D9 supplies population Q and R. D10 supplies F-star, D11 the population projection and implicit Gram matrix Omega, and D12 the explicitly referenced approximation property (6). The theorem itself gives all A-C and numbered regularity conditions, both tuning regimes and the two rates. The average s is A9; the norms and ordered-pair average are A1-A2. The density ratio presupposes absolute continuity, but the source’s lower bound on its sup norm is not strengthened to pointwise domination. No proof-only proposition, appendix sufficient condition or modified estimator is inserted. Ambiguous measure normalization, maximum grouping, integration domains and the X_1/X_2 correction mismatch remain explicit source issues.'
}
(ROOT/'ambient-conventions.json').write_text(json.dumps(dict(paper_id=PID,auxiliary_passages=aux,unresolved_source_conventions=issues,standard_ambient_resolution=resolution),indent=2,ensure_ascii=False)+'\n')
print('Saved',len(aux),'auxiliary passages and',len(issues),'source-convention notes.')
