"""Preserve original p/e-variable definitions and convex-order construction passages."""
import json
from save_inventory import ROOT,PID,STATEMENTS
interfaces=[];members={}
def add(n,term,s,pages,deps,symbols,boundary,heading,kind='definition',context=None,context_page=None,phrases=None):
    lid=f'D{n}'
    m=dict(paper_id=PID,local_id=lid,local_label=heading,source_heading=heading,source_kind=kind,statement_original=s,relation='exact',depends_on=[f'D{i}' for i in deps],evidence=[dict(page=p,location=heading) for p in pages],highlight_symbols=symbols,highlight_phrases=phrases or [])
    kw=dict(paper_id=PID,local_id=lid,source_text=term,label=term[0].upper()+term[1:],kind='term')
    if term not in s:
        assert context and term in context,(lid,term)
        m['naming_context']=[dict(context_id=lid+'/name',text=context,evidence=[dict(page=context_page or pages[0],location='Original naming context')])];kw['context_id']=lid+'/name'
    members[lid]=m
    interfaces.append(dict(interface_id=PID+'/'+lid,rank_group='all',name=kw['label'],lean_role='definition',type_shape=boundary,semantic_boundary=boundary,members=[m],source_keywords=[kw],central_claim_uses=[],dependencies=[],theorem_explanations={}))
add(1,'pivotal',r'''A random variable $X$ is pivotal for $\mathcal P$ if $X$ has the same distribution under all $P\in\mathcal P$.''',[2],[],[], 'Common law under every null distribution, not merely common expectation. Exact e-variables need not be pivotal.','Terminology 1 — Pivotal random variable',phrases=['pivotal'])
add(2,'e-variable',r'''A nonnegative random variable $X$ is a e-variable for $\mathcal P$ if $\mathbb E^P[X]\le1$ for all $P\in\mathcal P$. An e-variable $X$ for $\mathcal P$ is exact if $\mathbb E^P[X]=1$ for all $P\in\mathcal P$. We say $X$ is nontrivial for $\mathcal Q$ if $\mathbb E^Q[X]>1$ for all $Q\in\mathcal Q$. An e-variable $X$ for $\mathcal P$ is said to have nontrivial e-power against $\mathcal Q$ if for each $Q\in\mathcal Q$, $\mathbb E^Q[\log X]>0$.''',[2],[],[r'\mathbb E^P[X]\le1',r'\mathbb E^P[X]=1',r'\mathbb E^Q[\log X]>0'],'Preserve four separate notions: null validity, exactness, expectation nontriviality, and pointwise positive log e-power. Uniform infimum-positive e-power in T6.7 is strictly stronger.','Terminology 2 — E-variable, exactness and power',phrases=['e-variable','nontrivial e-power'])
add(3,'p-variable',r'''A nonnegative random variable $X$ is a p-variable for $\mathcal P$ if $P(X\le\alpha)\le\alpha$ for all $\alpha\in(0,1)$ and $P\in\mathcal P$, and a p-variable $X$ is exact if $P(X\le\alpha)=\alpha$ for all $\alpha\in(0,1)$ and $P\in\mathcal P$. A p-variable $X$ for $\mathcal P$ is nontrivial (or has nontrivial power) against $\mathcal Q$ if, for each $Q\in\mathcal Q$, $Q(X\le\alpha)\ge\alpha$ for all $\alpha\in(0,1)$ with strict inequality for some $\alpha\in(0,1)$. Without loss of generality, p-variables can be restricted to $[0,1]$ by truncation, without changing their properties.''',[2,3],[],[r'P(X\le\alpha)\le\alpha',r'Q(X\le\alpha)\ge\alpha'],'Validity and exactness under every null; under each alternative all thresholds have at least nominal rejection probability and some threshold has strict improvement. The improving threshold may depend on Q.','Terminology 3 — P-variable, exactness and power',phrases=['p-variable'])
add(4,'convex hull and span',r'''For a finite set $A$ of random variables or probability measures on the same space, we define $\operatorname{Conv}A$ and $\operatorname{Span}A$ in the usual sense of convex hull and span.''',[5],[],[r'\operatorname{Conv}A',r'\operatorname{Span}A'],'Ordinary finite convex hull and linear span. Do not insert closures into finite-hypothesis results or identify span with convex hull; signed linear combinations are relevant in the later closure formulation.','Notation 2 — Convex hull and span')
add(5,'convex order',r'''For $\mu,\nu\in\mathcal M(\mathbb R^d)$, we denote by $\mu\preceq_{\mathrm{cx}}\nu$ if $\int\phi\,d\mu\le\int\phi\,d\nu$ for every convex function $\phi$, in which case we say $\mu$ is smaller than $\nu$ in convex order. If $\mu,\nu$ are probability measures and $X\stackrel{\mathrm{law}}\sim\mu$, $Y\stackrel{\mathrm{law}}\sim\nu$, we sometimes abuse notation and write $X\preceq_{\mathrm{cx}}Y$ instead of $\mu\preceq_{\mathrm{cx}}\nu$.''',[5],[],[r'\mu\preceq_{\mathrm{cx}}\nu'],'Convex-integral order on finite first-moment measures, also applied to subprobabilities. Affine test functions entail equal mass and first moment where defined; this is not ordinary setwise measure order.','Notation 3 — Convex order')
add(6,'usual order',r'''We write $\mu\le\nu$ if $\mu(A)\le\nu(A)$ for every Borel set $A$.''',[5],[],[r'\mu\le\nu'],'Ordinary setwise order used in monotonicity of the split measures mu_x; distinct from convex order.','Notation 3 — Usual order of measures',context=r'''The class of measures $\{\mu_x\}_{x\ge0}$ from Proposition 4.3 is monotone (in the usual order), i.e., for all $x\le y$, $\mu_x\le\mu_y$.''',context_page=13)
add(7,'barycenter',r'''All measures we consider will be finite and have a finite first moment, i.e., $\int|x|\mu(dx)<\infty$. For a Polish space $\mathcal X$, we let $\mathcal M(\mathcal X)$ be the set of all finite measures on $\mathcal X$ and $\Pi(\mathcal X)$ be the set of probability measures on $\mathcal X$. For $\mu\in\mathcal M(\mathbb R^d)$, we denote its barycenter by $\operatorname{bary}(\mu):=\int_{\mathbb R^d}x\mu(dx)/\mu(\mathbb R^d)$.''',[5],[],[r'\operatorname{bary}(\mu)'],'Normalized barycenter of a finite measure, not an unnormalized first moment. The zero-measure case is not specified in this printed definition; record that when SHINE splits an empty component.','Notation 2 — Finite measures and barycenter')
add(8,'positive diagonal',r'''Bold symbols such as $\mathbf x$ and $\boldsymbol\alpha$ will typically denote vectors. Write $\mathbf1_d=(1,\ldots,1)\in\mathbb R^d$, $\mathbf0_d=(0,\ldots,0)\in\mathbb R^d$, $\mathcal I_d=\{\mathbf x\in\mathbb R^d\mid x_1=\cdots=x_d\}=\mathbb R\mathbf1_d$, and $\mathcal I_d^+=\{\mathbf x\in\mathbb R^d\mid x_1=\cdots=x_d\ge0\}=\mathbb R_+\mathbf1_d$. When the dimension $d$ is clear, we may omit the subscript $d$ and write $\mathbf1,\mathbf0,\mathcal I,\mathcal I^+$ instead. We let $U_1$ denote the Lebesgue measure on $[0,1]$. Denote the Euclidean norm by $\|\cdot\|$.''',[5],[],[r'\mathcal I_d^+',r'\mathbf1_d'],'The positive diagonal includes zero. Vector diagonal measures and scalar first-coordinate martingales must remain distinct. U1 is the unit-interval uniform probability measure.','Notation 4 — Positive diagonal',context=r'''the positive diagonal $\mathcal I_L^+\not\subseteq\mathbb H_x$;''',context_page=13)
add(9,'maximal element',r'''The relation $\preceq_{\mathrm{cx}}$ is a partial order on $\Pi(\mathbb R^d)$. Given a subset $\mathcal N\subseteq\Pi(\mathbb R^d)$, we say $\mu$ is a (Pareto) maximal element in $\mathcal N$ if there exists no $\nu\in\mathcal N$ such that $\nu\ne\mu$ and $\mu\preceq_{\mathrm{cx}}\nu$; we say $\mu$ is the maximum element in $\mathcal N$ if $\nu\preceq_{\mathrm{cx}}\mu$ for each $\nu\in\mathcal N$.''',[6],[5],[r'\mu\preceq_{\mathrm{cx}}\nu',r'\nu\preceq_{\mathrm{cx}}\mu'],'Maximal means undominated; maximum means dominates every element. SHINE only guarantees maximality unless a maximum exists.','Section 2 — Maximal and maximum elements',phrases=['maximal element','maximum element'])
add(10,'simultaneous transport plans and maps',r'''For $d\ge1$ and two $\mathbb R^d$-valued measures $\boldsymbol\mu,\boldsymbol\nu$ on Polish spaces $\mathcal X,\mathcal Y$ (denoted by $\boldsymbol\mu\in\mathcal M(\mathcal X)^d$ and $\boldsymbol\nu\in\mathcal M(\mathcal Y)^d$) such that $\boldsymbol\mu(\mathcal X)=\boldsymbol\nu(\mathcal Y)$, let $\mathcal K(\boldsymbol\mu,\boldsymbol\nu)$ and $\mathcal T(\boldsymbol\mu,\boldsymbol\nu)$ denote the set of all simultaneous transport plans and maps from $\boldsymbol\mu$ to $\boldsymbol\nu$ respectively, i.e., $\mathcal K(\boldsymbol\mu,\boldsymbol\nu)$ is the set of all stochastic kernels $\kappa$ such that
\[
\kappa_\#\boldsymbol\mu(\cdot):=\int_{\mathcal X}\kappa(x;\cdot)\boldsymbol\mu(dx)=\boldsymbol\nu(\cdot),
\]
and
\[
\mathcal T(\boldsymbol\mu,\boldsymbol\nu)=\{T:\mathcal X\to\mathcal Y\mid\boldsymbol\mu\circ T^{-1}=\boldsymbol\nu\}.
\]''',[6],[],[r'\mathcal T(\boldsymbol\mu,\boldsymbol\nu)',r'\kappa_\#\boldsymbol\mu'],'A single kernel or map transports every coordinate measure to its corresponding target. Do not replace it by independently chosen maps for each null distribution.','Section 2 — Simultaneous transport')
add(11,'jointly atomless',r'''Consider a tuple of probability measures $\boldsymbol\mu=(\mu_1,\ldots,\mu_d)$ on a Polish space $\mathcal X$. We say that $\boldsymbol\mu$ is jointly atomless if there exists $\mu\gg\sum_{i=1}^d\mu_i$ and a random variable $\xi$ such that under $\mu$, $\xi$ is atomless and independent of $(d\mu_1/d\mu,\ldots,d\mu_d/d\mu)$.''',[6],[],[r'\xi',r'(d\mu_1/d\mu,\ldots,d\mu_d/d\mu)'],'Definition 2.2 requires an atomless auxiliary random variable independent of the density-ratio vector under a dominating measure. Individual atomlessness of each law does not suffice. In (JA), apply it to the combined null/alternative tuple.','Definition 2.2 — Joint atomlessness',phrases=['jointly atomless'])
add(12,'absolutely continuous',r'''\[P_1,\ldots,P_L\ll Q.\]
(AC)''',[9],[],[r'P_1,\ldots,P_L\ll Q'],'Absolute continuity in the null-to-alternative direction only. Not mutual equivalence and not a joint-atomlessness requirement. Theorem 4.9 imposes this only for its two-observation refinement.','Assumption (AC)',kind='assumption',context=r'''For $P,Q\in\mathcal M(\mathcal X)$ we write $P\ll Q$ if $P$ is absolutely continuous with respect to $Q$ (sometimes we say $Q$ dominates $P$), and $P\approx Q$ if $P\ll Q\ll P$.''',context_page=5,phrases=['(AC)'])
add(13,'Radon–Nikodym derivatives',r'''In this section, we let
\[
\gamma:=\left(\frac{dP_1}{dQ},\ldots,\frac{dP_L}{dQ}\right)\bigg|_Q.
\]
(4)
In particular, $\gamma$ is a probability measure on $\mathbb R_+^L$ with mean $\mathbf1$.''',[11],[12],[r'\gamma',r'\frac{dP_1}{dQ}'],'Law under Q of the L-dimensional null-to-alternative density vector. It has mean one in each coordinate; it is not the density vector itself or the law under a null P.','Section 4 — Density-ratio law (4)',context='For infinite $\\mathcal X$, such a direct construction exploiting orthogonality is no longer possible because the Radon–Nikodym derivatives do not live in a Hilbert space.',context_page=11)
add(14,'e-power',r'''The e-power of an e-variable $X$ can be measured by $\mathbb E^Q[\log X]$, which has long been a popular criterion; see for example Kelly (1956); Breiman (1961); Bell and Cover (1988); Shafer et al. (2011); Grünwald, de Heide and Koolen (2024); Waudby-Smith and Ramdas (2024). It has been recently called the e-power of $X$ (Vovk and Wang (2024)), a term we continue to use for simplicity. In this section, we will fix $\mathcal P=\{P_1,\ldots,P_L\}$ and $\mathcal Q=\{Q\}$. Our goal is to solve
\[
\max\quad\mathbb E^Q[\log X],\qquad\text{s.t.}\quad X:X\text{ is a pivotal exact e-variable}.
\]
(3)''',[11],[1,2],[r'\mathbb E^Q[\log X]'],'Optimization over exact pivotal e-variables for a fixed simple alternative. Do not replace by maximizing ordinary expectation, or remove pivotality because another e-value construction does so.','Section 4 — E-power maximization (3)')
add(15,'convex order',r'''In other words, let $\gamma$ be the law of $(dP_1/dQ,\ldots,dP_L/dQ)$ under $Q$ and introduce the set $\mathcal M_\gamma$ of probability measures supported on $\mathcal I_L^+$ that is smaller than $\gamma$ in convex order, and our goal is to
\[
\max\quad\mu\text{ in }\preceq_{\mathrm{cx}},\qquad\text{s.t.}\quad\mu\in\mathcal M_\gamma.
\]
(8)''',[13],[5,8,13],[r'\mathcal M_\gamma',r'\mathcal I_L^+'],'Feasible diagonal-supported probability measures below gamma in convex order. This is the general-L set, not the earlier one-dimensional illustration on all of R.','Section 4.1 — Diagonal convex-order feasible set (8)')
add(16,'hyperplane',r'''$\gamma$ from (4) does not give positive mass to any hyperplane in $\mathbb R^L$.
(N)
That is, for every half-space $\mathbb H\subseteq\mathbb R^L$, $\gamma(\partial\mathbb H)=0$.''',[13],[13],[r'\gamma(\partial\mathbb H)=0'],'No mass on any affine hyperplane; stronger than atomlessness. Theorem 5.3 adds N only for the convergence/maximality clause; preserve that scope.','Assumption (N)',kind='assumption',phrases=['(N)','hyperplane'])
add(17,'separating hyperplane',r'''Let $\gamma$ be a probability measure on $\mathbb R_+^L$ with mean $\mathbf1$. Consider $x\ge0$. There exists a closed half-space $\mathbb H_x$ of $\mathbb R^L$ and a measure $\mu_x$ supported on $\mathbb H_x$, such that
(i) the positive diagonal $\mathcal I_L^+\not\subseteq\mathbb H_x$;
(ii) $-\mathbf1\in\mathbb H_x$;
(iii) $x\mathbf1\in\partial\mathbb H_x=\mathbb H_x\cap\mathbb H_x^c$, where $\mathbb H_x^c$ is the closed complement of $\mathbb H_x$;
(iv) the measure $\mu_{\mathbb H_x^c}:=\gamma-\mu_x$ is supported on $\mathbb H_x^c$, and the barycenters of $\mu_x$ and $\mu_{\mathbb H_x^c}$ both lie on $\mathcal I^+$.
In this case, we call $\partial\mathbb H_x$ a separating hyperplane at $x$. Moreover, if (N) holds, there exists a unique measure $\mu_x$ satisfying the above conditions, in which case it also holds that $\mu_x=\gamma|_{\mathbb H_x}$ and $\mu_{\mathbb H_x^c}=\gamma|_{\mathbb H_x^c}$.''',[13],[7,8],[r'\mu_x',r'\mathbb H_x',r'\partial\mathbb H_x'],'Complete source specification in Proposition 4.3, including exceptional closed-complement notation. N gives unique split measures, not necessarily a unique half-space. Do not impose N on the existence portion or equate usual order with convex order.','Proposition 4.3 — Separating hyperplane and split measures',kind='source_passage')
add(18,'E-power maximization',r'''As a consequence of Proposition 2.3, the optimization problem (3) is equivalent to finding
\[
\max\quad\mathbb E^G\left[-\log\frac{dF}{dG}\right],\qquad\text{s.t.}\quad F,G\in\Pi(\mathbb R):\left(\frac{dF}{dG},\ldots,\frac{dF}{dG}\right)\bigg|_G\preceq_{\mathrm{cx}}\left(\frac{dP_1}{dQ},\ldots,\frac{dP_L}{dQ}\right)\bigg|_Q.
\]
(7)''',[12],[5,13],[r'\mathbb E^G',r'\frac{dF}{dG}'],'Likelihood-ratio-law optimization corresponding to (3); the actual objective and constraint need convex order and gamma, not a fresh assumption of a proof proposition. Values at zero density and infinite log objective are not explicitly settled by the main text.','Section 4.1 — Transformed optimization (7)',context='E-power maximization and convex order.',context_page=11)
add(19,'iid data points',r'''Suppose that instead of one data point, we observe $n$ iid data points $Z_1,\ldots,Z_n$ in the space $\mathcal X$ from the experiment. The e-variable is built based on the $n$ data points together instead of a single data point. In other words, given $\mathcal P=\{P_1,\ldots,P_L\}$ and $\mathcal Q=\{Q\}$, we build an e-variable for $\mathcal P^n:=\{P_1^n,\ldots,P_L^n\}$ that is pivotal, exact, and has nontrivial e-power against $\mathcal Q^n:=\{Q^n\}$.''',[14],[],[r'\mathcal P^n:=\{P_1^n,\ldots,P_L^n\}',r'Q^n'],'Product experiment: one population distribution is used for all iid draws. The null consists of pure products P_i^n, not all mixed products or the product of a mixture. Theorem 4.9 concerns product-measure span separation only; the surrounding e-value motivation does not add JA or e-variable premises.','Section 4.4 — Multiple-observation experiment')
add(20,'SHINE construction',r'''Start with $\mu^{(0)}=\delta_{\mathbf1}$, $x_1^{(0)}=1$, and $\mu_1^{(0)}=\gamma$ from (4). At step $s\ge0$, we are given $\mu^{(s)}$, $\{x_k^{(s)}\}_{1\le k\le2^s}$, and $\{\mu_k^{(s)}\}_{1\le k\le2^s}$. For each $k$, we apply Proposition 4.3 to the sub-probability measure $\mu_k^{(s)}$ at the point $x_k^{(s)}$. This yields a unique decomposition of $\mu_k^{(s)}$ into two measures, each having a barycenter on $\mathcal I^+$. Denote them by $\mu_{2k-1}^{(s+1)}$ and $\mu_{2k}^{(s+1)}$. For $1\le k\le2^{s+1}$, define $x_k^{(s+1)}=\operatorname{bary}(\mu_k^{(s+1)})$. Finally, let $\mu^{(s+1)}$ be the probability measure having mass $\mu_k^{(s+1)}(\mathbb R^L)$ on $x_k^{(s+1)}$ for every $k$, i.e.,
\[
\mu^{(s+1)}:=\sum_{k=1}^{2^{s+1}}\mu_k^{(s+1)}(\mathbb R^L)\delta_{x_k^{(s+1)}}.
\]
(11)
The output of the SHINE construction at step $s$ is the measure $\mu^{(s)}$.''',[20],[7,8,13,17],[r'\mu^{(s+1)}',r'\mu_k^{(s)}'],'Recursive split-at-barycenter construction. Source alternates scalar first-coordinate and vector barycenter notation. Uniqueness without N and zero-mass children are not fully specified; preserve the printed algorithm rather than inventing a tie-break or empty-child rule.','Section 5.1 — SHINE construction (11)')
add(21,'SHINE martingale',r'''Define $\{X_s\}$ as the coupling of the first coordinate of $\{\mu^{(s)}\}$ such that $X_0=1$ and at each $s\ge0$, for $j=2k-1,2k$,
\[
\mathbb P[X_{s+1}=x_j^{(s+1)}\mid X_s=x_k^{(s)}]=\frac{\mu_j^{(s+1)}(\mathbb R^L)}{\mu_{2k-1}^{(s+1)}(\mathbb R^L)+\mu_{2k}^{(s+1)}(\mathbb R^L)}.
\]
(12)
By construction,
\[
x_{2k-1}^{(s+1)}\mu_{2k-1}^{(s+1)}(\mathbb R^L)+x_{2k}^{(s+1)}\mu_{2k}^{(s+1)}(\mathbb R^L)=x_k^{(s)}\mu_k^{(s)}(\mathbb R^L)=x_k^{(s)}(\mu_{2k-1}^{(s+1)}(\mathbb R^L)+\mu_{2k}^{(s+1)}(\mathbb R^L)).
\]
It can thus be checked by direct calculation that $\mathbb E[X_{s+1}\mid X_s=x_k^{(s)}]=x_k^{(s)}$, meaning that $\{X_s\}$ forms a nonnegative martingale, and hence converges a.s. to some $X_\infty$ by the martingale convergence theorem. We call $\{X_s\}$ the SHINE martingale (associated with $\gamma$). Denote by $\mu$ the law of $X_\infty\mathbf1=(X_\infty,\ldots,X_\infty)$.''',[20],[20],[r'X_s',r'X_\infty',r'\mathbb E[X_{s+1}\mid X_s=x_k^{(s)}]'],'Scalar first-coordinate martingale coupled along the split tree; its reciprocal corresponds to the e-variable. EP_k uses minus log X_k. The theorem wording about almost-sure convergence of measures is interpreted via this coupling, not silently rewritten.','Section 5.1 — SHINE martingale (12)')
add(22,'common reference measure',r'''Assume that there exists a common reference measure $R\in\Pi(\mathcal X)$ such that $P\ll R$ for $P\in\mathcal P$ and $Q\ll R$ for $Q\in\mathcal Q$.''',[25],[],[r'R\in\Pi(\mathcal X)',r'P\ll R',r'Q\ll R'],'One probability measure dominates every null and alternative law. This differs from AC, which makes the single alternative dominate all nulls.','Theorem 6.7 — Common dominating measure',kind='theorem_excerpt')
add(23,'total variation distance',STATEMENTS[-1][STATEMENTS[-1].index('There exists'):],[25],[2,4],[r'\overline{\overline{\operatorname{Span}}\mathcal P+\overline{\operatorname{Conv}}\mathcal Q}',r'\inf_{Q\in\mathcal Q}\mathbb E^Q[\log X]>0'],'Original uniform-e-power and closed-set separation passage. Both inner closed span/closed convex hull and the outer closure of their sum are printed. Under tightness, the further criterion is disjointness of the two individually closed sets. The paper names total variation and tightness but gives no explicit defining formula here.','Theorem 6.7 — Uniform e-power and total-variation separation',kind='theorem_excerpt')
def main():
    (ROOT/'source-passages.json').write_text(json.dumps(dict(paper_id=PID,members=list(members.values())),indent=2,ensure_ascii=False)+'\n')
    (ROOT/'interface-extraction.json').write_text(json.dumps(dict(paper_id=PID,interfaces=interfaces),indent=2,ensure_ascii=False)+'\n')
if __name__=='__main__':main()
