"""Archive original context and unresolved source scope separately from quotations."""
import json
from save_inventory import ROOT,PID

def main():
    aux=[]
    def add(n,s,pages,note,deps=()):aux.append(dict(local_id='A'+str(n),statement_original=s,evidence=[dict(page=p,location='Original main-text context A'+str(n)) for p in pages],scope_note=note,depends_on=list(deps)))
    add(1,r'''Consider a universe of distributions $\Pi$ on a sample space $(\mathcal X,\mathcal F)$, where $\mathcal X$ is a Polish space. The data are generated according to some $P\in\Pi$. Let $\mathcal P$ and $\mathcal Q$ be disjoint subsets of $\Pi$. When we say we are testing $\mathcal P$, we mean that we are testing the null hypothesis $P\in\mathcal P$. When we say we are testing $\mathcal P$ against $\mathcal Q$, we mean additionally that the alternative hypothesis is $P\in\mathcal Q$.''',[1],'Ambient testing space and disjoint hypothesis sets; Euclidean space is additionally required in Theorem 4.9.')
    add(2,r'''We fix $\mathcal P=\{P_1,\ldots,P_L\}$ and $\mathcal Q=\{Q\}$ in $\Pi(\mathcal X)$ and will assume that
\[
(\mathcal P,\mathcal Q)\text{ is jointly atomless},
\]
(JA)
unless otherwise stated.''',[9],'JA refers to the combined tuple in Definition 2.2. Later composite-alternative statements replace the singleton Q by the finite alternative tuple. Explicit exceptions in Theorems 4.9, 6.1, 6.2 and 6.7 retain their own scope.',['D11'])
    add(3,r'''We say “a probability measure $\mu$ is supported on a set $A$” if $\mu(A)=1$. This does not imply that $A$ is closed or $A=\operatorname{supp}\mu$. The product measure is denoted by $P\otimes Q$.''',[5],'Support on the diagonal or convex boundary means full measure, not equality to the closed topological support. Pure product powers in T4.9 use ordinary product measures.')
    add(4,r'''For $P,Q\in\mathcal M(\mathcal X)$ we write $P\ll Q$ if $P$ is absolutely continuous with respect to $Q$ (sometimes we say $Q$ dominates $P$), and $P\approx Q$ if $P\ll Q\ll P$.''',[5],'Distinguish one-way AC, mutual equivalence, and common domination in T6.7.')
    add(5,r'''A coupling $(X,Y)$ on $\mathbb R^d\times\mathbb R^d$ is called a martingale coupling if $\mathbb E[Y\mid X]=X$. Given $\mu,\nu\in\Pi(\mathbb R^d)$, a martingale transport (plan) from $\mu$ to $\nu$ is a martingale coupling $(X,Y)$ such that $X\stackrel{\mathrm{law}}\sim\mu$ and $Y\stackrel{\mathrm{law}}\sim\nu$.''',[6],'Context for the SHINE coupling. Strassen’s theorem is an externally named proof tool, not an additional stored Theorem environment.')
    add(6,r'''The only place we used our assumption (N) is on the uniqueness of the measure $\mu_x$ in Proposition 4.3. When there is no uniqueness, the condition (b) in Theorem 4.4 needs to be replaced by the existence of a monotone selection of measures $\{\mu_x\}_{x\ge0}$, each of them satisfying the conditions in Proposition 4.3.''',[13],'Remark 4.6 describes the atom-containing extension. It does not license removing N from the printed theorem or treating an arbitrary selection as monotone.',['D16','D17'])
    add(7,r'''We keep the same setting as in Section 4.2 and assume (N), with the exception that $L=2$.''',[14],'Preceding Section 4.3 scope for Theorem 4.7. L counts null distributions, not the dimension of the observation space.',['D16'])
    add(8,r'''In this paper when we mention “dimension” we typically refer to the dimension of the null, but not the dimension of the underlying space $\mathcal X$.''',[14],'Footnote 5. T4.9 separately requires Euclidean observation space; do not conflate its dimension with L.')
    add(9,r'''When we apply the construction in practice, we need to stop at finitely many steps, so we will not always obtain an exactly maximal element. Later in Section 5.3, we show that the e-power from the $k$-th step in SHINE converges exponentially to the optimal value produced by SHINE, with a rate that can be made explicit given mild moment conditions.''',[21],'Finite iteration is not necessarily maximal. The limiting SHINE value need not be a global maximum in a setting with incomparable maximal measures.',['D9','D20','D21'])
    add(10,r'''With the presence of atoms, the decomposition given by Proposition 4.3 is not necessarily unique when applied to our construction. The degree of freedom of each $\mu_x$ is the measure on the hyperplane $\partial\mathbb H_x$. To describe a well-defined construction, we need to specify $\mu_x|_{\partial\mathbb H_x}$ uniquely for each $x$. Analyzing the maximality of the output remains a technical task, which we do not discuss in this paper.''',[21],'The main text explicitly leaves the atomic selection and its maximality unresolved. Do not invent a selection rule or promote finite empirical simulations to the N theorem.',['D16','D17','D20'])
    add(11,r'''Since $(P_1,\ldots,P_L,Q)$ is jointly atomless, we may apply Proposition 2.4 to find a simultaneous transport map $Y\in\mathcal T((P_1,\ldots,P_L,Q),(F,\ldots,F,G))$ such that for each $x\in\mathcal X$,
\[
\frac{dF}{dG}(Y(x))\times\mathbf1=h\left(\frac{dP_1}{dQ}(x),\ldots,\frac{dP_L}{dQ}(x)\right).
\]
This leads to
\[
(X(x))^{-1}\times\mathbf1=h\left(\frac{dP_1}{dQ}(x),\ldots,\frac{dP_L}{dQ}(x)\right),\quad x\in\mathcal X.
\]''',[21],'Source link between the SHINE scalar coordinate and the reciprocal e-variable. The recovery proof does not add a transport-map premise to T5.5, which states a convergence rate for the SHINE martingale.',['D10','D11','D13'])
    add(12,r'''Note that here we do not require that $\mathcal P$ and $\mathcal Q$ are finite, but only the existence of a reference measure $R$ dominating $\mathcal P\cup\mathcal Q$.''',[25],'Remark 6.3 supplies common domination for the infinite-family reading of T6.2(c)–(d), absent from that theorem’s last sentence. The additional uniform-separation issue is recorded, not repaired.')
    add(13,r'''A third classical yet fundamental related work is Kraft’s theorem (Kraft (1955, Theorem 5)), which states that if there is a $\sigma$-finite reference measure $R$ that dominates every distribution in $\mathcal P\cup\mathcal Q$, then for each $\varepsilon>0$ there exists a $[0,1]$-valued random variable $X$ with
\[
\inf_{Q\in\mathcal Q}\mathbb E^Q[X]\ge\varepsilon+\sup_{P\in\mathcal P}\mathbb E^P[X]
\]
(1)
if and only if the total variation distance $d_{\mathrm{TV}}(\operatorname{Conv}\mathcal P,\operatorname{Conv}\mathcal Q)\ge\varepsilon$.''',[4],'An externally cited theorem quoted in introductory prose, not a local Theorem environment. Its positive uniform separation is stronger than mere disjointness of noncompact sets or pointwise expectation improvement.')
    add(14,r'''Note that we have put a stronger assumption on the e-variable $X$ ($\inf_{Q\in\mathcal Q}\mathbb E^Q[\log X]>0$) than having nontrivial e-power against $\mathcal Q$ (for all $Q\in\mathcal Q$, $\mathbb E^Q[\log X]>0$).''',[25],'Author explicitly distinguishes uniform from pointwise positive log e-power. Pivotality in the infinite case remains a conjecture in Section 6.2.',['D2','D23'])
    issues=[]
    def issue(i,pages,note):issues.append(dict(issue_id=i,evidence=[dict(page=p,location='Source scope or notation issue') for p in pages],note=note))
    issue('exactness-pivotality-power',[2,3,9,24,25],'Exact p-variables are pivotal because their null law is uniform. Exact e-variables merely have expectation one. Pointwise expectation nontriviality, positive log e-power and a uniform positive infimum are separate definitions; preserve each theorem clause.')
    issue('ja-exceptions',[9,15,24,25],'T3.1 and T3.4 use JA but not AC. T4.9 is a Euclidean product-measure separation result with no JA premise. T6.1(c)–(e) and T6.2(c)–(d) explicitly dispense with JA. T6.7 assumes common domination, not JA; its pivotal strengthening is Conjecture 6.8.')
    issue('ac-direction-and-refinement',[9,11,15,25],'AC means P_i≪Q, not Q≪P_i. It is needed to define gamma, and in T4.9 only the additional k≤2 refinement imposes AC and linear independence. Common dominating R in T6.7 is a different condition.')
    issue('maximal-versus-maximum',[6,13,20,21],'T4.4 and T4.7 concern a maximum dominating all feasible measures. Under N, T5.3 guarantees only a maximal limit; if a maximum exists the construction converges to it. Finite SHINE outputs need not be maximal.')
    issue('closed-complement',[13],'Proposition 4.3 explicitly calls H_x^c the closed complement, so it overlaps H_x on the hyperplane. Do not substitute the ordinary open set complement defined in general notation. Under N the overlap has zero gamma mass.')
    issue('split-measure-uniqueness',[13,20,21],'N makes the split measure unique, while uniqueness of the half-space is separately asserted for strictly positive density. The algorithm prints a unique decomposition before T5.3’s N clause; the later atomic discussion explicitly requires a selection that the paper does not specify.')
    issue('zero-mass-barycenters',[5,13,20],'The barycenter formula divides by total mass. Splitting may produce zero-mass children, and the transition formula divides by parent mass. The main text does not specify empty-child values or transitions on null states. No arbitrary conventions have been inserted.')
    issue('scalar-vector-coupling',[20,22],'Equation (11) alternates x_k as a vector barycenter and as a scalar first coordinate. Equation (12) is the scalar SHINE martingale. T5.3 says measures converge almost surely; the preceding coupling supplies the a.s. random-variable interpretation. Preserve the printed wording and record the distinction.')
    issue('shine-rate-assumption-scope',[20,22],'T5.5 says same conditions as T5.3, whose conclusion has an additional N branch. The rate statement’s preceding convergent-construction context uses that branch. Preserve this contextual reading separately; do not pretend T5.5 explicitly repeats N.')
    issue('distinct-moment-indices',[22],'T5.5 requires a finite (2+epsilon)-moment for some density coordinate j and a finite inverse-square moment for some possibly different j-prime. It does not require every coordinate or one common index to satisfy both.')
    issue('reciprocal-and-log-domain',[11,12,21,22],'The e-variable is a likelihood ratio dG/dF, whereas the SHINE coordinate corresponds to dF/dG and EP_k uses minus log. Main-text formulas do not explicitly settle all zero-density/infinite-objective conventions; AC alone is not mutual equivalence. Preserve directions and do not silently impose equivalence.')
    issue('infinite-hull-separation',[4,24,25],'The final T6.2 clause removes finiteness and JA without stating common domination, which Remark 6.3 then supplies. The remark invokes Kraft’s uniform positive TV separation from pointwise expectation improvement and from disjoint convex hulls. Those implications are not justified for arbitrary infinite families by the printed hypotheses. Preserve the unclosed formula and flag the quantifier/topology issue rather than claiming a repaired theorem or proof certification.')
    issue('nested-total-variation-closures',[25],'T6.7 prints separately closed span and convex hull inside an additional outer closure of their sum. Only the tight-Q clause replaces this by disjointness of the individually closed sets. Total variation and tightness are named but not explicitly defined in the main text.')
    issue('products-and-dimensions',[14,15],'P^k is the finite family of pure product laws P_i^k, not all mixed products and not powers of convex mixtures. L is the null-family size; the Euclidean sample-space restriction in T4.9 is separate from L=2 in T4.7.')
    refs=[dict(from_claim_id=PID+'/T4.4',to_source_label='Proposition 4.3',reference_kind='definition_reference',scope='Import the split-measure specification mu_x, not proof lemmas.'),dict(from_claim_id=PID+'/T4.7',to_source_label='Proposition 4.3',reference_kind='definition_reference',scope='Split mu_x with L=2 enters the distribution formula.'),dict(from_claim_id=PID+'/T5.3',to_source_label='Section 5.1 and Proposition 4.3',reference_kind='definition_reference',scope='Recursive SHINE construction and its canonical first-coordinate coupling.'),dict(from_claim_id=PID+'/T5.5',to_source_label='Theorem 5.3',reference_kind='assumption_reference',scope='JA, AC and the N convergence branch. Do not import a global-maximum-existence condition.'),dict(from_claim_id=PID+'/T5.5',to_source_label='Lemma 5.6 and Appendix D',reference_kind='proof_only',scope='Rate proof and Wasserstein bound; no appendix body read and no new statement dependency.'),dict(from_claim_id=PID+'/T6.2',to_source_label='Kraft’s theorem (1), Remark 6.3 and Proposition A.2',reference_kind='proof_only',scope='Proof motivation is not a replacement theorem statement. Infinite-family domination and separation limitations recorded. Appendix body excluded.')]
    bindings={
'T3.1':'Finite null P_1,...,P_L and simple alternative Q; JA is the combined tuple condition. Exact p and the three different e/pivotal existence clauses keep separate quantifiers. Atomless laws in (d) are local conditions. Span is ordinary finite linear span. No AC requirement.',
'T3.4':'Finite null and simple alternative, JA; nontrivial p/e-variable definitions are D2–D3. The hull is ordinary finite Conv. No exactness, pivotality or AC is added from adjacent results.',
'T4.2':'Finite null/simple Q, JA and AC. Maximize (3) with pivotal exact feasible variables. F,G are probability measures on R and one map Y simultaneously transports each null to F and Q to G. The displayed ratio direction dG/dF is preserved.',
'T4.4':'Assumption N for the gamma of (4); M_gamma and I^+ from (8) and notation. The unique maximum dominates every feasible measure in convex order. Split mu_x comes from Prop4.3; its monotonicity uses setwise order. Gamma’s registered density-law origin uses AC, but no JA premise is imported for this measure-order characterization.',
'T4.7':'Preceding Section4.3 fixes L=2. N, JA, AC; convex Gamma⊆R² and gamma(boundary Gamma)=1 are theorem-local conditions. The diagonal maximum has distribution mu([0,x]²)=mu_x(R²). Distinct probability F,G with repeated dF/dG law mu attain (7).',
'T4.9':'Euclidean observation space, distinct finite P_i and Q outside that family. Some finite k separates Q^k from Span(P^k). Only the moreover branch assumes AC and linear independence to get k=1 or2. No JA, p/e-variable constraint or density-law gamma is imported.',
'T5.3':'JA,AC for SHINE(11) and coupling(12); every step increases in convex order, strictly if the measures differ. N is added for a maximal limit in M_gamma. Existence of a maximum is an additional conditional conclusion branch, not a standing premise. Preserve a.s. measure wording with its coupling explanation.',
'T5.5':'Conditions referenced from T5.3, with N in the convergent-construction reading. E_Q[(dP_j/dQ)^(2+epsilon)]<infinity for some j; E_Q[(dP_j-prime/dQ)^(-2)]<infinity for possibly different j-prime. X_k is the scalar SHINE martingale, EP_k=E_Q[-log X_k]. EP_infinity is printed with unsubscripted expectation. Constants r∈(0,1),C>0 do not depend on k. No global maximum premise.',
'T6.1':'Finite null and finite alternative under JA. Exact-p, pivotal exact bounded e with positive log-power, exact nontrivial e, and common-pivotal-law separation are alternative equivalent clauses. Span(P)∩Conv(Q)=empty is the last clause. The (c)–(e) equivalence removes JA.',
'T6.2':'Finite null and finite alternative, JA for full equivalence. Nonexact p and e conditions compare ordinary convex hulls. The final (c)–(d) clause removes JA and finiteness; Remark6.3 supplies domination and raises an unresolved uniform-separation issue. No closure bars inserted.',
'T6.7':'Arbitrary disjoint null/alternative families on the ambient Polish space, dominated by one probability R. Exact bounded e-variable with uniform inf_Q E_Q[log X]>0. Closed span and closed hull have an outer closure around their sum; 0 must lie outside it. With tight Q, the further criterion is disjointness of the individually closed sets. No JA or pivotality; TV, tightness and signed-measure span are ambient notions.'}
    out=dict(paper_id=PID,status='extracted',unranked_auxiliary_passages=aux,source_issues=issues,source_claim_references=refs,statement_local_bindings=bindings,ambient_prerequisites=['Polish measurable spaces, probability measures and pushforward laws, atomlessness, Radon–Nikodym derivatives and conditional expectations. Finite first moments are the source’s Euclidean measure convention.','Finite linear spans and convex hulls of measures; in T6.7, signed-measure linear span and total-variation closures. The main text names total variation distance and tightness without giving explicit definitions.','Euclidean convex sets, closed half-spaces and boundaries, ordinary measure restriction, product measures, finite-dimensional linear independence, Dirac measures, nonnegative martingale convergence and logarithms. Conditions bound within theorem statements remain local and are not invented definitions.'],extraction_policy='All eleven main-text Theorems, complete statements and source-local definitions. Preserve equivalent-clause scopes and unresolved source limitations. Appendix bodies, library search and proof certification excluded.')
    (ROOT/'ambient-prerequisites.json').write_text(json.dumps(out,indent=2,ensure_ascii=False)+'\n')
if __name__=='__main__':main()
