"""Preserve source conventions and ambiguities without altering the seven statements."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];PID=ROOT.name
aux=[]
def add(aid,text,pages,loc,meaning):
    aux.append(dict(auxiliary_id=aid,statement_original=text.strip(),evidence=[dict(page=p,location=loc) for p in pages],resolution=meaning))
add('A1',r'''Here and throughout $F^{-1}$ denotes the quantile function corresponding to a cdf $F$, $F^{-1}(u)=\inf\{x\in\mathbb R:F(x)\geq u\}$, for $u\in(0,1)$.''',[8],'Section 3 — generalized inverse convention','The ranks and their estimators use this left generalized inverse, not a classical inverse requiring strict monotonicity. Endpoint values at 0 and 1 are not specified; they do not change the Lebesgue quantile integrals but matter for pointwise compositions.')
add('A2',r'''We utilize the optimal mass transport map
\[
H_{X,\omega}(u)=F_X^{-1}(F_\omega(u))-u,\qquad u\geq0,\tag{10}
\]
see, e.g., Ambrosio, Gigli and Savaré (2008), to assign a measure of centrality to an element $\omega\in\Omega$ with respect to $P$. When $F_\omega$ is continuous, by a change of variable, the integral
\[
\int H_{X,\omega}(u)dF_\omega(u)=\int_0^1\{F_X^{-1}(u)-F_\omega^{-1}(u)\}du\tag{11}
\]
provides a summary measure of the mass transfer when transporting $F_\omega$ to $F_X$.''',[8],'Section 3 — motivation of the signed quantile integral','This is a signed displacement, not an absolute transport cost. The continuity qualification belongs to the displayed change of variables; the rank is subsequently defined directly by the quantile integral. No extra rank theorem assumption is inferred from this motivation, and endpoint evaluation of the composition is not silently totalized.')
add('A3',r'''Let $\mathcal P_{(\Omega,d)}$ denote the class of all Borel probability measures on $(\Omega,d)$ that are uniquely determined by the measure of all open balls or equivalently by the set of distance profiles, that is, for $Q_1,Q_2\in\mathcal P_{(\Omega,d)}$, $Q_1=Q_2$ if and only if $F^{Q_1}_\omega(u)=F^{Q_2}_\omega(u)$ for all $\omega\in\Omega$ and $u\geq0$. In fact $\mathcal P_{(\Omega,d)}$ corresponds to the set of all Borel probability measures on $(\Omega,d)$ when the metric $d$ is such that $d^\theta$ is of strong negative type (9) for some $\theta>0$ (see Proposition 1). If $w_\omega(u)>0$ for any $\omega\in\Omega$ and for any $u\geq0$, then $D^w_{XY}=0$ implies that $F^X_\omega(u)=F^Y_\omega(u)$ for almost any $u\geq0$ and for any $\omega$ in the union of the supports of $P_1$ and $P_2$. Hence, if $\Omega$ is contained in the union of the supports of $P_1$ and $P_2$, then $D^w_{XY}(P_1,P_2)=0$ implies that $P_1=P_2$ whenever $P_1,P_2\in\mathcal P_{(\Omega,d)}$.''',[16],'Section 6.1 — identification discussion after (26)','These extra positivity, identifying-class and support-coverage conditions concern identification of zero population discrepancy. Theorem 6.2 instead assumes a positive discrepancy sequence explicitly. This paragraph does not silently add strong negative type or full-support assumptions to all two-sample theorems; its stated claims are preserved as context, not independently certified.')
add('A4',r'''Suppose that $\overline\Gamma_L(\cdot)$ is continuous and strictly increasing at $\overline q_\alpha$ and $n,m\to\infty$ such that $\frac n{n+m}-c=O((n+m)^{-1/2})$ and $\frac m{n+m}-(1-c)=O((n+m)^{-1/2})$. Then under Assumptions 1, 4, 5 and 6, $|\widehat q_\alpha-\overline q_\alpha|=o_{\mathbb P}(1)$, i.e., $\widehat q_\alpha$ converges to a deterministic limit also for the case where $P_1\ne P_2$.''',[18],'Section 6.2 — main-text mixture-quantile assertion preceding Theorem 6.3','This contextual assertion explains the mixture quantile used in the last clause of Theorem 6.3. It is not itself an additional labeled Theorem. The two balance conditions are retained even though one follows from the other.')
issues=[]
def issue(key,text,pages):issues.append(dict(issue_id=key,description=text,evidence=[dict(page=p,location='Inspected main-text source convention') for p in pages],resolution_status='source_preserved'))
issue('S1','The first strong-negative-type formulation quantifies over all measurable h, omitting a mean-zero and integrability restriction. It is not equivalent as printed to (9): for a point-mass P the zero diagonal kernel makes the quadratic form zero for every h, contradicting its equality-only-if-h=0 clause. Both formulations are transcribed literally.',[8])
issue('S2','Section 3 discusses strong negative type for a powered distance d^theta, but Theorem 4.1(d) invokes the metric space (Omega,d) itself. A property of an arbitrary other power is not substituted for the theorem hypothesis; Proposition 1 is a distinct result type and is not added to the Theorem inventory.',[8,11])
issue('S3','Assumption 2 asks for a continuous density and a strictly positive infimum over its support. With the usual global continuity and support conventions, this is problematic at the boundary of a bounded nonnegative distance distribution. The source may intend continuity on the interior, but this is not specified and is not repaired.',[7,12])
issue('S4','Assumption 3 takes the infimum outside each individual median’s epsilon ball. If there were two distinct medians, choosing epsilon below their distance would make the rank gap zero. Its prose describes separated multiple medians, which does not agree with the formula. The census retains the formula instead of changing it to separation from the entire median set.',[14])
issue('S5','Theorem 4.1(c) writes R_gamma(s)(u) and R_gamma(t)(u), although (12) defines scalar ranks with no u argument. This extra argument is preserved in the theorem and recorded separately.',[9,11])
issue('S6','Equation (22) indexes profiles by omega but writes d(x,X) and d(x,Y), leaving x unbound in that sentence. The intended anchor interpretation is clear from (8) and Assumption 5, but the original equation is retained.',[14,17])
issue('S7','The permutation split gives Y_Pi_j the second entry V_Pi_j(2), overlapping the first group, instead of the expected V_Pi_j(n+2). Its literal formula conflicts with the accompanying claim of splitting into two groups of sizes n and m. No corrected algorithm is silently substituted.',[16])
issue('S8','Assumption 4 does not require nonnegative weights. Theorem 6.1 nevertheless uses sqrt(w_x(u)w_x(v)) and a chi-square-series law. Negative or sign-changing weights create a mismatch between the statistic and that representation; the positivity imposed for identification after (26) is not explicitly repeated in Assumption 4. The missing condition is flagged, not inserted.',[15,16,17])
issue('S9','Theorem 6.1 calls lambda_j^x the eigenvalues of a covariance surface without explicitly specifying the associated operator space or integration measure. The literal averaged pointwise eigenvalue series is preserved; no alternative covariance operator or spectral formula is inferred from a proof.',[17])
issue('S10','The source calls H_nm contiguous alternatives but defines only D=a_nm tending to zero with nm/(n+m)*a_nm tending to infinity. This is not by itself a statement of Le Cam contiguity, and the source term is not expanded into that stronger probabilistic claim.',[17,18])
issue('S11','The notation P_Hnm does not state whether power is evaluated along an arbitrary chosen pair sequence or uniformly over the composite set. The source also uses a null-law critical value under alternatives without specifying a particular null P there. No minimax, supremum or uniformity convention is supplied by the census.',[16,17,18])
issue('S12','Section 3 assumes total boundedness and separability, while Theorem 4.1 restates only separability. Total boundedness makes the rank quantile integrals finite. Extending that theorem to arbitrary unbounded separable spaces would need an integrability convention, which the local statement does not supply.',[7,9,11])
issue('S13','The notation F-hat_Xi denotes a leave-one-out CDF in the empirical rank formula, whereas F-hat_omega is the full-sample empirical CDF. When omega is an observation these roles coincide symbolically but differ in denominator; the two source conventions remain separate.',[11,12])
issue('S14','Assumption 2 explicitly asks for continuous densities; Assumption 5 asks for absolutely continuous profiles and densities but does not explicitly demand density continuity. Both have anchorwise positive lower bounds and uniform upper bounds. They are not merged into a stronger common condition.',[12,17])
issue('S15','Theorem 5.1 states weak convergence of the indexed process without naming a function-space topology. The preceding discussion calls the ball-indicator class P-Donsker, suggesting the usual empirical-process interpretation; this is interpretation, not extra original theorem wording.',[12])
issue('S16','The generalized inverse is defined on (0,1), while the map F_X inverse composed with F_omega can reach 0 or 1. Endpoint conventions are not provided. Endpoint values do not affect the rank’s Lebesgue integral, but the pointwise map is not automatically defined everywhere.',[8,9])
issue('S17','The text permits any strictly monotone invertible map from R to [0,1] after using expit with range (0,1). A decreasing transform reverses the ranking and closed-endpoint bijectivity differs from the logistic map. All theorem interpretations retain the actual expit definition, not the unrestricted prose generalization.',[9,11])
issue('S18','Total boundedness does not imply compactness. Theorem 5.3 explicitly assumes a nonempty population median set; no existence theorem or arbitrary selection rule is added. The empirical set retains all sample maximizers, and its leave-one-out rank needs n>=2.',[7,9,12,14])
issue('S19','Theorem 6.3 writes Gamma-hat_m,n rather than Gamma-hat_nm from (27). The first conclusion is pointwise at continuity points, not uniform in t. Its final power clause does not repeat K tending to infinity although the earlier permutation clauses do; this omission and the source sequence of clauses are preserved.',[16,18])
issue('S20','The two root-total-size sample-balance bounds in Theorem 6.3 are algebraically redundant, but both are retained. The mixture definition initially allows c in [0,1]; Assumption 6 restricts the theorem regime to c in (0,1).', [17,18])
issue('S21','The permutation statistic is defined by evaluating the same statistic functional on each permuted sample. No separate rule says to freeze data-adaptive weights fitted to the original group labels. The census preserves the functional definition without inventing a shortcut or an implementation.',[15,16])
issue('S22','The three critical values have different reference laws: q_alpha uses the null law, q-hat_alpha the permutation empirical CDF, and q-bar_alpha the mixture limit. The mixture quantile restricts the infimum to t>=0, while the other two do not. These definitions and their continuity hypotheses remain distinct.',[16,17,18])
resolution={
 'shared':'The standing model is a totally bounded separable metric space with Borel object laws, distinct from the underlying probability measure. Standard real integration, covariance, Gaussian distributions, indicator functions, generalized inverse quantiles, covering numbers and stochastic O/o notation retain their ordinary meanings. A1 fixes the generalized inverse. Theorems concern source statements, not independently proved conclusions; the omitted support, integrability, spectral and finite-sample conventions are listed explicitly.',
 '4.1':'D1-D6 resolve the random-object model, distance profiles, strong negative type, scalar logistic transport ranks, median set and transport mode. The isometry h, pushforward P_h, curve gamma and pair of laws are bound in the statement. Part (d) uses the metric d itself. Part (c)’s extra u on scalar ranks and the broader separable-only wording remain source issues.',
 '5.1':'D7 is the full-sample empirical CDF; D10 and D11 are exactly Assumptions 1 and 2; D12 is the ball-indicator class defining the displayed covariance. The Gaussian process is bound in the statement, with MSBM-font G transcribed as mathbb G. The source’s P-Donsker context suggests a uniform empirical-process topology, but that topology is not written into the original theorem.',
 '5.2':'D4 and D8 give population and estimated ranks, using A1 for inverses and D2 for the random-anchor profile with an independent object copy. D10/D11 supply the entropy and density assumptions. The bound is a root-n uniform stochastic order over Omega, not a central limit theorem. D7’s full-sample anchor term and D8’s leave-one-out random term remain distinguished.',
 '5.3':'D5 is the population argmax over the support, D9 the finite-sample argmax, D13 the two-sided Hausdorff metric. D10/D11/D14 are Assumptions 1-3. Nonemptiness is explicit. The source’s pointwise-median rank separation is retained despite its incompatible multimedian prose.',
 '6.1':'D15 supplies the two-sample model and common null law. D17/D16 supply the weighted statistic and four empirical profiles. D10/D18/D19/D20 are Assumptions 1,4,5,6, with (25) in D18’s source context. The theorem binds L, its independent normal sequence, V and V-prime, pointwise covariance and eigenvalues (also archived as D23 for subsequent references). Weights are the supplied function family constrained by D18; no rank/median condition or Assumption 2 is imported.',
 '6.2':'The same four assumptions apply. D22 specifies the discrepancy sequence using D21 and D15; D28 specifies strict-exceedance power using the null critical value D24 based on D23. The theorem does not require equality of laws to be characterized by zero discrepancy, so the additional positivity/strong-negative-type/support discussion in A3 is not an extra hypothesis. Probability over the composite alternative remains a source convention.',
 '6.3':'D25 defines permutations, their independent randomness, the empirical CDF and estimated quantile. D23 identifies the null CDF; its quantile q_alpha is inf{t:Gamma_L(t)>=1-alpha}, as preserved in D24, without importing the alternative-power object D28 as a hypothesis of the null clauses. D26 supplies the mixture law, limiting CDF and nonnegative-domain mixture quantile; D27/D22 give alternative power. All clauses use Assumptions 1,4,5,6, with the extra rate and continuity requirements local to their clauses. The m,n subscript and permutation split mismatch are preserved. The source does not specify uniform assumptions along every changing pair of laws or restate K’s limit in the last clause.'
}
def main():
    (ROOT/'ambient-conventions.json').write_text(json.dumps(dict(paper_id=PID,auxiliary_passages=aux,unresolved_source_conventions=issues,standard_ambient_resolution=resolution),indent=2,ensure_ascii=False)+'\n')
    print('Saved',len(aux),'auxiliary passages and',len(issues),'source-convention notes.')


if __name__ == "__main__":
    main()
