"""Archive main-text conventions, auxiliary definitions and unresolved source limitations."""
import json
from save_inventory import ROOT,PID

def main():
    aux=[]
    def add(n,s,ps,note,deps=()):aux.append(dict(local_id='A'+str(n),statement_original=s,evidence=[dict(page=p,location='Original main-text context A'+str(n)) for p in ps],scope_note=note,depends_on=list(deps)))
    add(1,r'''Throughout the paper, we assume that $L$ and $B$ are positive constants not depending on the sample size $n$.''',[2],'Standing fixed-bound convention for the bounded and Lipschitz classes.',['D3','D4','D5'])
    add(2,r'''Our rate results often involve various constants which are generically denoted by $c$ or $C$. These constants never depend on the sample size $n$ but they often depend on various other parameters involved in the problem (such as the dimension $d$, Lipschitz constant $L$, uniform bound $B$, number of facets of the polytopal domain $\Omega$, etc.). We have tried to indicate the dependence of the constant explicity using notation such as $C_{d,B,L}$. We have not attempted to explicitly specify the dependence of these constants on these parameters. Please note that the value of these constants may change from occurrence to occurrence.''',[8],'Original Section1.3 constant convention; explicit theorem statements take precedence over a stronger inferred uniformity.')
    add(3,r'''Here (and in the rest of the paper), when we say that a specific set $S$ is a “polytope”, we assume that the number of facets or extreme points of $S$ is bounded by a constant not depending on the sample size $n$.''',[4],'General polytope terminology;3.1 strengthens to a dimensional facet bound, while14 uses a dimensional slab-count bound.',['D14'])
    add(4,r'''The minimax rate for a function class $\mathcal F$ in the above setting is:
\[
\mathfrak R_n^{\mathrm{random}}(\mathcal F):=\inf_{\breve f_n}\sup_{f_0\in\mathcal F}\mathbb E_{f_0}\ell_{\mathbb P}^2(\breve f_n,f_0)
\]''',[3],'Original comparison quantity. No inventoried theorem requires minimax risk to be supplied as an input; Section2 statements carrying it are Propositions.',['D9','D10'])
    add(5,r'''The supremum risk of an estimator $\breve f$ on a function class $\mathcal F$ is defined as
\[
R_n(\breve f_n,\mathcal F):=\sup_{f\in\mathcal F}\mathbb E_f\ell_{\mathbb P}^2(\breve f_n,f).
\]''',[4],'Original supremum-risk abbreviation; theorem displays expand the supremum.',['D9','D10'])
    add(6,r'''Here $N_{[\,]}(\epsilon,\mathcal F,\ell_{\mathbb P})$ denotes the $\epsilon$-bracketing number of $\mathcal F$ under the $\ell_{\mathbb P}$ metric which is defined as the smallest number of $\epsilon$-brackets:
\[
[\underline f,\bar f]:=\{g:\underline f(x)\le g(x)\le\bar f(x)\text{ for all }x\}\qquad\text{with }\ell_{\mathbb P}(\underline f,\bar f)\le\epsilon
\]
needed to cover $\mathcal F$. The logarithm of $N_{[\,]}(\epsilon,\mathcal F,\ell_{\mathbb P})$ denotes the $\epsilon$-bracketing entropy of $\mathcal F$.''',[4],'Original full bracket definition specialized to the probability L2 metric. In4.5 the metric is explicitly replaced by Lebesgue Lp on a union of simplices; do not infer a random-design assumption for that deterministic theorem. Bracket endpoints need not be members of the target class.',['D9','D20'])
    add(7,r'''\[
t_f(\mathcal F):=\operatorname*{argmax}_{t\ge0}H_f(t,\mathcal F)\tag{31}
\]
with
\[
H_f(t,\mathcal F):=\mathbb E\left[\sup_{g\in\mathcal F:\ell_{\mathbb P_n}(f,g)\le t}\frac1n\sum_{i=1}^n\xi_i(g(X_i)-f(X_i))\,\middle|\,X_1,\ldots,X_n\right]-\frac{t^2}2.\tag{32}
\]
Here $t_f(\mathcal F)$ is random as it depends on the random design points $X_1,\ldots,X_n$. Note that (30) applies to the loss $\ell_{\mathbb P_n}$ and not to $\ell_{\mathbb P}$.''',[14],'Original random-design conditional counterpart of4.1; it appears in proof explanations and is not substituted into the fixed-design theorem.',['D8','D11','D23','D24'])
    add(8,r'''Here we work with the same setting as in Subsection 2.2 (in particular, note that $\Omega$ is polytopal of the form (14)).''',[11],'Explicit standing setting for all of3.2, supplying polytopal domain, grid and Gaussian model to3.3–3.6.',['D1','D14','D15'])
    add(9,r'''The metric employed is the $L_p$ metric on a bunch of simplices. This result is stated for arbitrary $p\in[1,\infty)$ although we only use it for $p=2$. Lemma 4.2 is proved by applying this theorem to the simplices given in Lemma 3.2.''',[17],'Original4.5 metric context; Lebesgue integral in42 is on allOmega, but43 uses the union. The application to Lemma3.2 is proof-only and imposes no special quadratic-approximation center in4.5.',['D17','D20','D21'])
    add(10,r'''In particular, this assumption implies that $\Omega$ has diameter at most $2$ and also volume at most $1$.''',[2],'Original consequence stated after3. The volume-at-most1 assertion does not follow from containment in the Euclidean unit ball in general dimensions (already dimension1 has volume2). Preserve the source statement without adding volume<=1 as a domain hypothesis.',['D7'])
    add(11,r'''From an examination of our proofs, it should be clear that all our random design results would continue to work under the more general assumption that $\mathbb P$ has a density on $\Omega$ that is bounded from above and below by positive constants. With this assumption, our bounds will involve additional multiplicative constants depending on the density constants.''',[22],'Original discussion generalization, not the original uniform-law theorem3.1. Unbounded Gaussian design and non-Gaussian errors are left for future work in22–23.',['D8'])
    bindings={
    'T3.1':'Gaussian convex regression1; uniform random design and population squared L2 loss4; expectation over all observations. Normalized domain3. First branch is bounded-Lipschitz class with B>=L or Lipschitz-only class, lower constant sigma L and threshold N_(d,sigma/L). Second branch requires dimensional facet bound and uses bounded-only class, sigma B and N_(d,sigma/B). Its piecewise-affine witness, Gaussian supremum, entropy bounds and Theorem4.1 are proof-only, not hypotheses.',
    'T3.3':'Section3.2 explicitly imports Section2.2: Gaussian model, regular small-delta grid, normalized slab polytope and dimensional F bound. F^frakturL is empirical distance at most frakturL to all affine functions; the estimator is unrestricted convex LSE. Empirical squared risk. Preserve all three dimension cases and constants/threshold; frakturL is not Lipschitz L.',
    'T3.4':'Same fixed-design setup as3.3. Supremum runs over simultaneous L-bounded L-Lipschitz convex functions, whereas estimator ranges over all convex functions. Positive sigma,L; n>=C_(d,sigma/L). Neither3.6 nor the selected Lemma3.2 function is required to state this supremum bound.',
    'T3.5':'Same fixed-design setup. C_(k,h) is defined by a grid partition into k convex regions each cut by at most h slabs, with affine restriction of f. It does not require full-region disjointness or impose normalized-domain inradius on each region. Preserve d<=3, d=4 and d>=5 rates; k,h are counts although theorem writes only >=1. Uniformity of C_d in h is retained as stated.',
    'T3.6':'Same fixed-design setup and unrestricted convex LSE with empirical risk. The true function is specifically the tilde f_k referred to in Lemma3.2, whose full main-text statement is archived. Keep n>=N_d and 1<=k<=min(sqrt(n)*sigma^(-d/4),c_d*n), including the sigma dependence. The existential lemma does not uniquely select this function; appendix construction is outside scope.',
    'T4.1':'Own fixed deterministic design in arbitrary convex body X, not necessarily a lattice or normalized Omega. The class F is convex as a set of functions; its individual functions need not be convex. Gaussian noises and f inF are inline hypotheses. Generic LSE2 and empirical loss8, H_f expected localized Gaussian supremum minus t²/2, t_f its maximizing radius. Both probability/expectation bounds and inequalities28–29 belong to the statement. Measurable minimizer existence/closedness is not stated for an arbitrary convex class.',
    'T4.5':'Deterministic entropy theorem for a convex domain inside the unit ball, Gamma-bounded convex center, and Gamma-bounded convex functions within unnormalized Lebesgue Lp distance t on allOmega. Simplices have disjoint interiors and center affine on each; their union need not equalOmega. Brackets use Lp on the union, for1<=p<infinity. No random design, Gaussian noise, normalized inradius3, lattice, or Lemma3.2 approximation is imposed. Printed log(Gamma/epsilon) bound is retained despite a large-epsilon endpoint concern.',
    'T4.11':'Deterministic covering entropy under the discrete normalized Lp metric51,1<=p<infinity from preceding prose, grid15 with n=cardinality and small delta16, normalized slab polytope14 and3, dimensional F. No Gaussian response/model, continuous population loss, affine approximant, or bracketing condition is required. Preserve [c_(d,p) log(1/delta)]^F (t/epsilon)^(d/2) for every positive epsilon,t.'}
    refs=[]
    def ref(n,target,kind,note):refs.append(dict(claim_id=PID+'/T'+n,target=target,reference_kind=kind,note=note))
    ref('3.1','(3) and classes on2','assumption_and_definition_reference','Use the separate branch-specific class and domain requirements.')
    for n in ['3.3','3.4','3.5','3.6']:ref(n,'Section2.2 imported by Section3.2','standing_assumption','Polytopal grid model is explicit preceding context, not repeated within each original statement.')
    ref('3.6','Lemma3.2','definition_reference','Theorem explicitly names the function supplied by this main-text lemma; archive its full statement including continuation on11.')
    ref('3.5','(14) within C_(k,h)','definition_reference','Only the slab representation format is used for cells; global normalized domain hypotheses do not transfer to each cell.')
    ref('4.1','(2) and empirical loss(8)','definition_reference','Generic convex class and own fixed design are bound inline; do not import random-design or lattice conditions.')
    ref('4.5','(42), Lp on simplex union','definition_reference','Retain distinct norm domains for defining the local class and bracketing restrictions.')
    ref('4.11','(3),(14),(15),(16),(51)','definition_reference','Full deterministic domain and grid conventions, including1<=p<infinity in preceding prose.')
    for n in ['3.1','3.3','3.4','3.5','3.6']:ref(n,'Theorem4.1 and entropy/approximation proof lemmas','proof_only','These prove rate bounds; only3.6 explicitly needs Lemma3.2 to identify its true function.')
    for n in ['3.1','3.3','3.4','3.5','3.6','4.5','4.11']:ref(n,'Appendix proofs','proof_only','Main text points to appendices; no appendix body read or imported.')
    issues=[]
    def issue(key,ps,note):issues.append(dict(issue_id=key,evidence=[dict(page=p,location='Source issue '+key) for p in ps],note=note))
    issue('registered-source',[1,24],'Registered arXiv2006.02044v2,67pages,stamp3Sep2024. Main text ends24; appendix begins25. Preserve this registered version and its eight theorem environments, not an abstract or replaced published source.')
    issue('notation-fidelity',[2,6,11],'Fraktur L in9/3.3 differs from Lipschitz L; fraktur B_d denotes the Euclidean unit ball. Population law and empirical measure are blackboard P and P_n; classes and grid are calligraphic. PDF plain text conflates these fonts; checked rendered pages and font metadata.')
    issue('noise-and-selection',[1,2,13],'Model1 gives iid Gaussian errors without explicitly stating independence from random design. This is a usual model convention needed for conditional Gaussian calculations. LSE2 chooses any minimizer; generic existence, measurable selection and off-design uniqueness are not guaranteed by that notation.')
    issue('generic-convex-class',[13],'Theorem4.1 assumes a convex class F, not necessarily a class of convex functions. It does not explicitly impose closedness of evaluation vectors. For the open convex family of constant functions c in(0,1), minimizers can fail when the sample mean is outside this interval. Preserve source wording and record missing attainment/closure conditions; do not assert theorem truth from transcription checks.')
    issue('normalized-body-volume',[2,3],'Containment in the Euclidean unit ball does not imply volume<=1 as stated after3. Retain the actual domain condition without adding the claimed volume consequence as a hypothesis. Theorem4.5 explicitly needs only containment, and4.1 binds an arbitrary convex body.')
    issue('slabs-and-facets',[4,9,10,11],'F in14 counts slabs, while3.1 explicitly bounds facets. They are not the same literal count. Constants may depend on dimension and the stated complexity bounds; do not replace a fixed-dimensional slab condition with an unrestricted growing-polytope sequence.')
    issue('grid-and-cells',[9,12,19],'n equals the number of grid points inOmega; delta is small enough for16 and n>=2. C_(k,h) partitions grid intersections, not necessarily every point ofOmega. Referring to slab format14 for cells does not require each cell to contain a dimensional ball. Integer k,h and cell endpoint assignment conventions remain implicit.')
    issue('affine-distance',[6,11],'F^frakturL bounds the unsquared empirical distance to all affine functions. It is design-dependent and allows unbounded affine trends. Do not substitute a Lipschitz bound, uniform bound, or a squared-distance threshold. The supremum class and the unrestricted estimator class are different.')
    issue('lemma-function-choice',[10,11,12],'Lemma3.2 provides existence of a convex tilde f_k with at most C_d*k simplex pieces and approximation properties; it does not uniquely define a function. Theorem3.6 calls it the function from that lemma. Preserve the reference and existential properties; no unique constructor or all-witness assertion is supplied from the excluded appendix. Small-k meaning of(1-C_d*k^(-1/d))*Omega is also retained without correction.')
    issue('h-uniformity',[12,18],'Theorem3.5 says C_d depends on d alone for every k,h>=1 and writes(log n)^h. The proof-sketch bounds47–48 have powers(cd log n)^h, potentially hiding h-dependent factors if h varies. Preserve the printed theorem and flag the stated constant scope rather than silently importing h-dependence.')
    issue('bracketing-scale',[17],'Theorem4.5 states the bound for every0<epsilon<Gamma with log(Gamma/epsilon)^(d+1). For fixed t large enough to include constants -Gamma and Gamma onOmega=[-1,1] and one simplex equalOmega, their Lp distance exceedsGamma, so the bracketing entropy stays at least log2 as epsilon approachesGamma, whereas the printed RHS tends to0. A restricted epsilon range or a log convention may be intended, but none is specified in the main-text constants convention. Preserve43 and record this endpoint issue without correcting it.')
    issue('metric-distinctions',[3,4,6,17,19],'Population squared L2, empirical squared L2, unnormalized Lebesgue Lp and normalized discrete Lp are distinct. Full-function empirical distances are pseudometrics until quotienting evaluation vectors. Covering entropy uses closed balls; bracket endpoints are pointwise ordered functions with metric width. Centers/quotient conventions are implicit; finite-dimensional metric facts are ambient, not theorem-truth checks.')
    issue('theorem4.11-scope',[19,20],'The p range1<=p<infinity and small-delta grid convention precede4.11 rather than appearing in its first sentence. Keep this context without rewriting the original. Constant c_(d,p) occurs inside an F-th power, unlike4.5 where k appears linearly. No response noise belongs to this entropy theorem.')
    issue('discussion-not-extension',[22,23],'The discussion proposes bounded-density random design with changed constants, unbounded designs, non-Gaussian errors and modified interior loss. These are not replacement hypotheses or new inventoried Theorems; Gaussian errors and original losses remain the census scope.')
    data=dict(paper_id=PID,unranked_auxiliary_passages=aux,statement_local_bindings=bindings,source_claim_references=refs,source_issues=issues,unresolved_external_prerequisites=[dict(reference='Lemma3.2 function selection in Theorem3.6',reason='The main-text lemma gives existence and properties; a unique particular construction would require excluded appendix material. Retain an existentially chosen witness and flag the unresolved selection semantics.')],ambient_prerequisites=['Euclidean spaces, real-valued convex and affine functions, Lipschitz and absolute uniform bounds, full-dimensional compact convex bodies, unit balls, polytopes, facets, slabs and affinely independent simplices.','Gaussian iid regression errors, observation laws and expectation, empirical probability measures, Lebesgue integration, squared losses and Lp (pseudo)metrics, pointwise ordered brackets and covering numbers.','Finite grid cardinalities, integer dimensions/piece counts, natural sample size, supremum and infimum over classes, argmin and argmax selections, logarithms, powers, positive thresholds and dimension-dependent constants.','Measurability and existence of stochastic suprema and LSE selections remain ambient requirements; no proof-correctness or mathlib-availability claim is made.'],validation_limits='Source fidelity and independent structural validation cover the main text only. They do not certify proofs, correct possible source errors, or resolve appendix-only constructions.')
    (ROOT/'ambient-prerequisites.json').write_text(json.dumps(data,indent=2,ensure_ascii=False)+'\n')
if __name__=='__main__':main()
