"""Derive and validate this paper's census from its reviewed inventory and local graph."""
import copy
import json
import subprocess
import sys
from pathlib import Path
from extract_interfaces import ROOT,PID,interfaces,members,edges,main as save_passages

SKILL=Path('skills/statistical-paper-census/scripts')
sys.path.insert(0,str(SKILL))
from canonical_dependencies import canonical_dependencies
from census_metrics import derive_metrics
from publication_contract import attach_inventory

DIRECT={
 '3.3':{
  'D10':'Assumption 2 in the first sentence imposes conditional exchangeability on the arbitrary score family.',
  'D11':'Assumption 3 rules out ties in both the arbitrary-score assertion and its AdaDetect specialization.',
  'D7':'The empirical p-values are explicitly those of (10), with strict calibration-score comparisons.',
  'D12':'The conclusion states PRDS on H0, with the increasing-set conditional-probability definition in Section 3.2.',
  'D9':'The particular AdaDetect assertion explicitly assumes raw-measurement exchangeability through Assumption 1.',
  'D5':'The particular assertion requires the fitted score to satisfy permutation condition (8).',
  'D6':'The p-values generated by AdaDetect use the evaluated scores (9); this is specific to the final sentence, not a restriction on the first arbitrary score family.'},
 '3.4':{
  'D10':'The opening sentence imposes Assumption 2 on the arbitrary scores.',
  'D11':'Assumption 3 imposes the no-ties condition, also used in the final AdaDetect specialization.',
  'D7':'The statement applies BH to empirical p-values defined by (10).',
  'D3':'R-alpha is explicitly the BH rejection set at level alpha.',
  'D2':'The left side of (11) is FDR(P,R-alpha), the expectation of FDP from (2).',
  'D9':'The final AdaDetect specialization explicitly imposes Assumption 1.',
  'D8':'The last sentence sets R-alpha equal to the complete AdaDetect procedure.'},
 '3.6':{
  'D10':'The opening setting reference to Theorem 3.4 imports its arbitrary-score Assumption 2.',
  'D11':'The setting reference to Theorem 3.4 imports Assumption 3, also explicit in the last sentence.',
  'D7':'The input vector p is explicitly the empirical p-value family (10).',
  'D3':'The procedure is BH with the data-dependent level alpha*m/G(p).',
  'D2':'The conclusion (14) bounds FDR(P,R), as defined in (2).',
  'D13':'The expectation on the right of (14) is under D_i, explicitly referenced as (13).',
  'D9':'The final AdaDetect specialization explicitly assumes Assumption 1.',
  'D8':'The last sentence replaces R by AdaDetect at the same data-dependent level.'},
 '4.1':{
  'D14':'The opening hypothesis is Assumption 4, requiring independence of all observations.',
  'D15':'The opening hypothesis also requires Assumption 5, specifying positive marginal densities relative to nu.',
  'D17':'The score r is explicitly the ratio (18) used in the displayed threshold rejection set.',
  'D18':'The comparison requires mFDR(R)=alpha and mFDR(R-prime)<=alpha; Section 4.2 supplies the mFDR passage with an unresolved printed index ambiguity.'},
 '5.1':{
  'D14':'The setting of Theorem 4.1 includes Assumption 4 on independent observations; its optimality conclusion is not imported.',
  'D15':'The setting of Theorem 4.1 includes Assumption 5 on positive marginal densities.',
  'D8':'Part (ii) explicitly identifies the rejection set as AdaDetect with score hat-g.',
  'D16':'The error term Delta explicitly uses gamma from (17), the mixed-sample alternative proportion.',
  'D21':'The hypotheses and both conclusions use R0 and R1 from the risk definitions (25), with different signs for null and alternative errors.',
  'D22':'The error terms in (28) contain V(G), the finite VC dimension specified immediately before (26).',
  'D23':'Hat-g in parts (i) and (ii) is the empirical constrained minimizer in (26), using epsilon0 from (28).',
  'D24':'The first sentence explicitly references the population optimizer (27) and assumes its null-risk constraint holds with equality.'},
 '5.4':{
  'D14':'Assumption 4 is an explicit hypothesis of the probability bound.',
  'D15':'Assumption 5 is an explicit hypothesis of the probability bound.',
  'D8':'AdaDetect at alpha-prime uses the estimated score, as fixed in the preceding paragraph.',
  'D19':'The event and comparison set use oracle AdaDetect, defined in Definition 4.2 and realized with g-star in the preceding paragraph.',
  'D20':'The final oracle p-values use g-star, whose oracle form (19) is fixed at the start of Section 5.2.',
  'D25':'The theorem explicitly requires continuity and strict decrease of the tail (33), and uses it to define the final oracle p-values.',
  'D26':'Alpha-prime contains zeta-r(eta), explicitly referenced as (34).',
  'D27':'The bound contains P(hat-eta>eta), explicitly referenced as the discrepancy (35).',
  'D3':'The final assertion replaces oracle AdaDetect by BH applied to the explicitly given oracle p-values.'}
}

def main():
    save_passages()
    inv=json.loads((ROOT/'theorem-inventory.json').read_text())
    data=copy.deepcopy(inv)
    data['schema_version']='statistical-ranked-interfaces-v4'
    data['scope'].update(paper_count=1,
        source_policy='Pinned arXiv:2208.06685v3. All six main-text Theorems and relevant source passages reviewed against the PDF; appendices excluded.',
        normalization_policy='Preserve printed wording, formulas, labels and source inconsistencies; expand macros and normalize line wrapping and typographic emphasis only.',
        semantic_ranking_policy='All six inventoried Theorems retained; direct demand counted once per theorem and interface, independently of proof use.',
        build_order_policy='Derive from the acyclic same-paper dependency graph; arbitrary score conditions remain distinct from the adaptive score construction and independent-density model.')
    data['interfaces']=copy.deepcopy(interfaces)
    claims={c['claim_id']:c for c in data['claims']}
    for c in data['claims']:
        number=c['claim_id'].split('/T')[-1]
        direct=DIRECT[number]
        c['depends_on']=list(direct)
        for x in data['interfaces']:
            used=[m['local_id'] for m in x['members'] if m['local_id'] in direct]
            if used:
                x['central_claim_uses'].append(dict(use_id=c['claim_id']+'-'+x['interface_id'].split('/')[-1],
                    paper_id=PID,claim_id=c['claim_id'],use_kind='statement_dependency',reason=' '.join(direct[lid] for lid in used),evidence=c['evidence']))
    derived=canonical_dependencies(data)
    for x in data['interfaces']:x['dependencies']=derived[x['interface_id']]
    derive_metrics(data)
    for x in data['interfaces']:
        for r in x['related_theorems']:
            cid=r['claim_id'];path=r['via_local_ids'];number=cid.split('/T')[-1]
            sentences=[DIRECT[number][path[0]]]
            evidence=list(claims[cid]['evidence'])
            for lid in path:
                evidence.extend(e for e in members[lid]['evidence'] if e not in evidence)
            for a,b in zip(path,path[1:]):sentences.append(edges[a][b])
            x['theorem_explanations'][cid]=dict(paper_id=PID,via_local_ids=path,text=' '.join(sentences),evidence=evidence)
        for m in x['members']:
            own=m['statement_original']+' '+m['local_label']
            linked=own+' '+' '.join(claims[r['claim_id']]['statement_original'] for r in x['related_theorems'])
            selectors=m['highlight_symbols']+m['highlight_phrases']
            assert any(s in own for s in selectors),(m['local_id'],'no source highlight')
            assert all(s in linked for s in selectors),(m['local_id'],'unmatched selectors',[s for s in selectors if s not in linked])
    attach_inventory(data,ROOT/'theorem-inventory.json',ROOT/'ranked-interfaces.json')
    (ROOT/'unfinalized-census.json').write_text(json.dumps(data,indent=2,ensure_ascii=False)+'\n')
    subprocess.run([sys.executable,str(SKILL/'finalize_census.py'),str(ROOT/'unfinalized-census.json'),str(ROOT/'ranked-interfaces.json'),'--inventory',str(ROOT/'theorem-inventory.json')],check=True)
    subprocess.run([sys.executable,str(SKILL/'validate_census.py'),str(ROOT/'ranked-interfaces.json')],check=True)
    print('All source highlight selectors matched. Census finalized and independently validated; final source-audit record remains.')

if __name__=='__main__':main()
