"""Preserve source definitions and conditions, including distinct reused matrix symbols."""
import json
from save_inventory import ROOT,PID,STATEMENTS,NU,G,SIGMA,AUX,NULL
interfaces=[];members={}
def add(n,term,s,pages,deps,symbols,boundary,heading,kind='definition',context=None,context_page=None,phrases=None):
    lid=f'D{n}'
    m=dict(paper_id=PID,local_id=lid,local_label=heading,source_heading=heading,source_kind=kind,statement_original=s,relation='exact',depends_on=[f'D{i}' for i in deps],evidence=[dict(page=p,location=heading) for p in pages],highlight_symbols=symbols,highlight_phrases=phrases or [])
    kw=dict(paper_id=PID,local_id=lid,source_text=term,label=term[0].upper()+term[1:],kind='term')
    if term not in s:
        assert context and term in context,(lid,term)
        m['naming_context']=[dict(context_id=lid+'/name',text=context,evidence=[dict(page=context_page or pages[0],location='Original naming context')])];kw['context_id']=lid+'/name'
    members[lid]=m
    interfaces.append(dict(interface_id=PID+'/'+lid,rank_group='all',name=kw['label'],lean_role='definition',type_shape=boundary,semantic_boundary=boundary,members=[m],source_keywords=[kw],central_claim_uses=[],dependencies=[],theorem_explanations={}))
add(1,'two-sample mean testing problem',r'''Suppose that for $m=1,2$, $\mathbf x_{mi}$, $i=1,\ldots,n_m$ is a random sample from a $p$-dimensional population with mean $\boldsymbol\mu_m$ and covariance matrix $\mathbf\Sigma$, which is assumed to be finite and positive definite.

Consider the two-sample mean testing problem:
\[
H_0:\boldsymbol\mu_1=\boldsymbol\mu_2\quad\text{versus}\quad H_1:\boldsymbol\mu_1\ne\boldsymbol\mu_2.
\]''',[3,4],[],[r'H_0',r'H_1',r'\mathbf\Sigma'],'Two sample populations with different possible means and the same finite positive-definite covariance. Do not substitute the unequal-covariance extension mentioned as future work.','Section 2 — Two-sample model and hypotheses',kind='assumption')
add(2,'pooled sample covariance matrix',r'''Let $\bar{\mathbf x}_m=n_m^{-1}\sum_{i=1}^{n_m}\mathbf x_{mi}$ be the sample mean of the $m$th sample, and
\[
\mathbf S=(s_{hk})_{h,k=1,\ldots,p}=(n_1+n_2-2)^{-1}\sum_{m=1}^2\sum_{i=1}^{n_m}(\mathbf x_{mi}-\bar{\mathbf x}_m)(\mathbf x_{mi}-\bar{\mathbf x}_m)^T,
\]
be the pooled sample covariance matrix and $\mathbf x_{mi}=(x_{mi1},\ldots,x_{mip})^T$.''',[3],[1],[r'\bar{\mathbf x}_m',r'\mathbf S'],'Pooled covariance with denominator n1+n2−2 and separately centered groups. Sample means and covariance use the same observations as the statistic.','Section 2 — Pooled sample covariance')
add(3,'correlation matrix',r'''Decompose the covariance matrix $\mathbf\Sigma=\mathbf D^{1/2}\mathbf R\mathbf D^{1/2}$, where $\mathbf D$ is the diagonal matrix from the diagonal elements of $\mathbf\Sigma$, and $\mathbf R$ is the correlation matrix. The natural estimator of $\mathbf D$ is $\operatorname{diag}(\mathbf S)$, which is the diagonal matrix consisting of the diagonal elements of the pooled sample covariance matrix $\mathbf S$. Therefore, we focus on modeling $\mathbf R^{-1}$ instead of $\mathbf\Sigma^{-1}$.''',[4],[1],[r'\mathbf\Sigma=\mathbf D^{1/2}\mathbf R\mathbf D^{1/2}',r'\mathbf R^{-1}'],'Population correlation versus precision decomposition. D is the marginal variance diagonal, unrelated to D0 and D1 in Theorem 2.2.','Section 2.1 — Covariance decomposition')
add(4,'symmetric matrix bases',r'''Let us consider the structure of $\mathbf R^{-1}$, which can be written as a linear combination of symmetric matrix bases $\mathbf A_1,\ldots,\mathbf A_K$ as follows:
\[
\mathbf R^{-1}=\theta_1\mathbf A_1+\cdots+\theta_K\mathbf A_K.
\]
(3)''',[4],[3],[r'\mathbf A_1',r'\mathbf R^{-1}=\theta_1\mathbf A_1'],'Exact finite linear structure in known symmetric matrix bases. The true active set is assumed included; K is finite as clarified in the Discussion. No positive-definiteness constraint on fitted coefficients is supplied here.','Section 2.1 — Linear inverse-correlation model (3)')
add(5,'sample correlation matrix',r'''Let $\widehat{\mathbf R}$ denote the sample correlation matrix, that is, $\widehat{\mathbf R}=[\operatorname{diag}(\mathbf S)]^{-1/2}\mathbf S[\operatorname{diag}(\mathbf S)]^{-1/2}$.''',[5],[2],[r'\widehat{\mathbf R}'],'Diagonal normalization of the pooled covariance. Inverse square roots of sample diagonal entries require positivity; no deterministic guarantee is stated for the permitted discrete observations.','Section 2.1 — Sample correlation matrix')
add(6,'quadratic loss',r'''Next, we propose an estimation procedure for $\boldsymbol\theta=(\theta_1,\ldots,\theta_K)^T$.

To estimate $\boldsymbol\theta$, we aim to minimize the quadratic loss given by
\[
\min_{\boldsymbol\theta}\operatorname{tr}[\widehat{\mathbf R}(\theta_1\mathbf A_1+\cdots+\theta_K\mathbf A_K)-\mathbf I_p]^2.
\]
(4)
Here, $\operatorname{tr}(\cdot)$ refers to the trace of a matrix. Denote $\mathbf B$ to be a $K\times K$ matrix, with $(k,l)$-element given by $p^{-1}\operatorname{tr}(\widehat{\mathbf R}\mathbf A_k\widehat{\mathbf R}\mathbf A_l)$, and $\mathbf b$ to be a $K\times1$ vector, with the $k$th element being $p^{-1}\operatorname{tr}(\widehat{\mathbf R}\mathbf A_k)$. The minimizer of (4) is $\widehat{\boldsymbol\theta}=\mathbf B^{-1}\mathbf b$.''',[5],[4,5],[r'\widehat{\boldsymbol\theta}=\mathbf B^{-1}\mathbf b',r'\widehat\theta_k'],'Unpenalized coefficient estimator. Preserve trace of the matrix residual squared; do not replace it by a Frobenius norm of a nonsymmetric residual. This B is sample-based, distinct from the B redefined in Theorem 2.2. Invertibility and coefficient identifiability are implicit.','Section 2.1 — Quadratic loss estimator (4)')
add(7,'high dimension',r'''Denote $y_{n-2}=p/(n-2)$, and assume $y=\lim_{n\to\infty}y_{n-2}$ exists and is finite.''',[5],[],[r'y_{n-2}=p/(n-2)',r'y=\lim_{n\to\infty}y_{n-2}'],'Finite aspect-ratio limit, with n=n1+n2 and p,n tending to infinity in the proof context. The printed statement allows y=1 although Theorem 2.2 contains (1−y)^{-2}; no exclusion is added.','Section 2.1 — Dimension-to-sample ratio',kind='assumption',context=r'''Bai and Saranadasa (1996) studied the asymptotical behavior of the Hotelling $T^2$ test and concluded that it has no power when $p/n$ approaches to 1 due to effect of high dimension.''',context_page=4)
add(8,'independent and identically distributed',STATEMENTS[0][:STATEMENTS[0].index(' Then it follows')],[5],[1],[r'\mathbf x^{(m)}=\mathbf\Sigma^{1/2}\mathbf w+\boldsymbol\mu_m',r'E(w_j^4)=\kappa'],'Linear transform of independent identically distributed standardized coordinates with a common fourth moment. Normality is not assumed and independence of transformed coordinates is not asserted.','Theorem 2.1 — Population representation and fourth moment',kind='theorem_excerpt')
add(9,'bounded',r'''Under the conditions of Theorem 2.1 and $p^{-1}\operatorname{tr}(\mathbf R\mathbf A_i\mathbf R\mathbf A_j)$ are bounded for $i,j=1,\ldots,K$, for any constants $(\pi_1,\ldots,\pi_K)$, we have''',[5],[4],[r'p^{-1}\operatorname{tr}(\mathbf R\mathbf A_i\mathbf R\mathbf A_j)'],'Normalized trace-product boundedness imposed by Theorem 2.2. Its mention of Theorem 2.1 is an inherited assumption reference, resolved separately at theorem level, not a recursive definition of the trace condition.','Theorem 2.2 — Trace-product condition',kind='theorem_excerpt')
add(10,'asymptotical joint normality',r'''$\mathbf B=\{p^{-1}\operatorname{tr}(\mathbf R\mathbf A_k\mathbf R\mathbf A_\ell)+y_{n-2}p^{-2}\operatorname{tr}(\mathbf R\mathbf A_k)\operatorname{tr}(\mathbf R\mathbf A_\ell)\}_{k,\ell=1}^K$''',[6],[4,7],[r'\mathbf B',r'y_{n-2}p^{-2}'],'Population trace matrix in the coefficient CLT, including the aspect-ratio rank-one term. This is a different object from the sample matrix B in (4); keep separate local identity.','Theorem 2.2 — Population matrix B',kind='theorem_excerpt',context=r'''Furthermore, Theorem 2.2 establishes the asymptotical joint normality of $\boldsymbol\theta$, and its proof is presented in the Supplementary Material due to limited space.''',context_page=5)
add(11,'matrix',r'''$\mathbf D_0$ being the $p\times p$-dimensional matrix with the $(i,j)$ element being $u_{ij}$ as follows: $u_{ij}=2(\mathbf e_i^T\mathbf R\mathbf e_j)^3+\beta_w\mathbf e_i^T\mathbf R\mathbf e_j\sum_{\ell=1}^p(\mathbf e_\ell^T\mathbf R^{1/2}\mathbf e_i)^2(\mathbf e_\ell^T\mathbf R^{1/2}\mathbf e_j)^2$, $\mathbf e_k$ being the $k$-column of the $p\times p$ identity matrix and $\beta_w=\kappa-3$.

'''+G,[6],[3,8],[r'\mathbf D_0',r'g(i,j,\beta_w,\mathbf R)',r'\beta_w=\kappa-3'],'Fourth-moment kernel g and matrix D0 as defined in the same theorem. D0 is not A0 from the null normalizer. Dependence on D8 supplies the defined kappa parameter, not a Gaussian specialization.','Theorem 2.2 — Fourth-moment matrix and kernel',kind='theorem_excerpt')
add(12,'symmetric matrix bases',r'''$\mathbf D_1=\eta_1\mathbf A_1+\cdots+\eta_K\mathbf A_K$, $(\eta_1,\ldots,\eta_K)=(\pi_1,\ldots,\pi_K)\mathbf B^{-1}$''',[6],[4,10],[r'\mathbf D_1',r'(\eta_1,\ldots,\eta_K)'],'Contrast-weighted combination of the basis matrices, using the population B of Theorem 2.2. D1 is not the diagonal variance matrix D from Section 2.1.','Theorem 2.2 — Contrast matrix D1',kind='theorem_excerpt',context=r'''Let us consider the structure of $\mathbf R^{-1}$, which can be written as a linear combination of symmetric matrix bases $\mathbf A_1,\ldots,\mathbf A_K$ as follows:''',context_page=4)
add(13,'asymptotical joint normality',NU+'\n'+SIGMA,[5,6],[7,11,12],[r'\nu',r'\sigma^2',r'\frac{1+2y}{1-y}'],'Complete centering nu and scale sigma² of Theorem 2.2. Retain all eleven centering terms and all eight additive variance terms, including distinct tr[(RD1)^2] and tr(RD1)^2 placements. Nonzero scale and y≠1 are not explicitly required by the printed hypotheses.','Theorem 2.2 — Centering and variance',kind='theorem_excerpt',context=r'''Furthermore, Theorem 2.2 establishes the asymptotical joint normality of $\boldsymbol\theta$, and its proof is presented in the Supplementary Material due to limited space.''',context_page=5)
add(14,'precision matrix',r'''Given $\widehat{\boldsymbol\theta}$, a natural estimate of $\mathbf R^{-1}$ using the linear structure in (3) as $\widehat{\mathbf R}_L^{-1}=\widehat\theta_1\mathbf A_1+\cdots+\widehat\theta_K\mathbf A_K$. Consequently, the estimate of the population precision matrix $\mathbf\Omega=\mathbf\Sigma^{-1}$ is given by
\[
\widehat{\mathbf\Omega}=[\operatorname{diag}(\mathbf S)]^{-1/2}\widehat{\mathbf R}_L^{-1}[\operatorname{diag}(\mathbf S)]^{-1/2},
\]
(6)
where $\mathbf S$ is the pooled sample covariance matrix.''',[7],[2,4,6],[r'\widehat{\mathbf R}_L^{-1}',r'\widehat{\mathbf\Omega}'],'Precision estimate from the fitted inverse correlation and sample marginal scales. The source reuses theta-hat for raw, bias-corrected and penalized fits; the formal tests retain the raw shrinkage c inherited from Theorems 2.1–2.2. The scope conflict is recorded, not resolved by substituting a regularized estimator.','Section 2.1 — Precision estimator (6)')
add(15,'test statistic',r'''By substituting $\mathbf W$ with $\widehat{\mathbf\Omega}$ in (2), we obtain the test statistic as follows:
\[
T_n=(\bar{\mathbf x}_1-\bar{\mathbf x}_2)^T\widehat{\mathbf\Omega}(\bar{\mathbf x}_1-\bar{\mathbf x}_2).
\]
(7)''',[7],[2,14],[r'T_n',r'\widehat{\mathbf\Omega}'],'Equation (7) lacks the n multiplier present in (2). Keep T_n as defined and n T_n in theorem normalizations; do not silently identify T and T_n.','Section 2.2 — Test statistic (7)')
add(16,'matrix',NULL+r'''
respectively, where $\mathbf e_k$ is the $k$-column of the identity matrix $\mathbf I_p$ and $\mathbf A_0$ is a $p\times p$ matrix with $(h,\ell)$-element being $a_{h,\ell}=2(\mathbf e_h^T\mathbf R\mathbf e_\ell)^3$.''',[7],[3],[r'\sigma_0^2',r'\mu_0',r'\mathbf A_0'],'Population null centering and variance with elementwise cubic A0. Keep the two trace-correction terms; this is not D0, and the formulas here contain no beta_w term.','Theorem 2.3 — Null mean and variance',kind='theorem_excerpt')
add(17,'estimates',r'''The estimates $\widehat\sigma_0^2$ and $\widehat\mu_0$ are obtained by replacing $\mathbf R$ with $\widetilde{\mathbf R}=\{\operatorname{diag}[\widehat{\mathbf R}_L]\}^{-1/2}\widehat{\mathbf R}_L\{\operatorname{diag}[\widehat{\mathbf R}_L]\}^{-1/2}$ in $\sigma_0^2$ and $\mu_0$.''',[7],[14,16],[r'\widetilde{\mathbf R}',r'\widehat\mu_0',r'\widehat\sigma_0^2'],'Plug-in null normalizers use the inverse of the fitted precision basis combination, then re-normalize its diagonal. This is not the sample correlation Rhat. Inverse/positive diagonal existence is implicit and recorded as a source issue.','Theorem 2.3 — Plug-in null normalizers',kind='theorem_excerpt')
add(18,'alternative hypothesis',r'''Under the conditions of Theorem 2.3 and under the alternative hypothesis $H_1:\boldsymbol\mu_1\ne\boldsymbol\mu_2$, it follows that'''+ '\n\n'+r'''where $c=(1+y)^{-1}$, $\delta_n=\boldsymbol\mu_d^T\mathbf\Sigma^{-1}\boldsymbol\mu_d$ with $\boldsymbol\mu_d=\boldsymbol\mu_1-\boldsymbol\mu_2$.''',[8],[1,7],[r'\delta_n',r'\boldsymbol\mu_d',r'c=(1+y)^{-1}'],'Signal delta_n is a population Mahalanobis squared mean difference. T2.4 replaces H0 by H1 when importing T2.3 conditions; it does not require both hypotheses. Local-alternative restrictions later used for comparison are not inserted into this full statement.','Theorem 2.4 — Alternative and signal',kind='theorem_excerpt')
add(19,'bounded spectral norm',r'''Although Theorems 2.3–2.4 in this paper require the bounded spectral norm of the population correlation matrix, the restrictions may be relaxed following the proof of Theorems 2.2–2.3 in Zheng et al. (2019), which removes the bounded spectral norm restriction. Because the proof of the central limit theorem under the bounded spectral norm is very different from the proof of the central limit theorem under the unbounded spectral norm, we place the proof under the unbounded spectral norm in future work.''',[22],[3],[], 'The Discussion explicitly identifies this as a requirement of T2.3–T2.4 even though their printed statements do not spell it out. Retain the condition as source context without rewriting those statements or treating the claimed future relaxation as proved.','Section 4 — Stated scope of Theorems 2.3–2.4',kind='condition',phrases=['bounded spectral norm'])
def main():
    (ROOT/'source-passages.json').write_text(json.dumps(dict(paper_id=PID,members=list(members.values())),indent=2,ensure_ascii=False)+'\n')
    (ROOT/'interface-extraction.json').write_text(json.dumps(dict(paper_id=PID,interfaces=interfaces),indent=2,ensure_ascii=False)+'\n')
if __name__=='__main__':main()
