"""Keep source caveats and mathematical context separate from original theorem quotations."""
import json
from save_inventory import ROOT,PID
def main():
    aux=[]
    def add(n,s,pages,note,deps=()):aux.append(dict(local_id='A'+str(n),statement_original=s,evidence=[dict(page=p,location='Original main-text context A'+str(n)) for p in pages],scope_note=note,depends_on=list(deps)))
    add(1,r'''To enhance the power of the Hotelling $T^2$ type test, we propose a new test statistic $T$, given by
\[
T=n(\bar{\mathbf x}_1-\bar{\mathbf x}_2)^T\mathbf W(\bar{\mathbf x}_1-\bar{\mathbf x}_2),
\]
(2)
where the weight matrix $\mathbf W$ is properly chosen and $n=n_1+n_2$.''',[4],'Generic weighted statistic T contains n. Equation (7) defines T_n without n, and the theorems normalize nT_n; preserve the difference.',['D2'])
    add(2,r'''This theorem shows that if $y>0$, the estimator $\widehat\theta_k$ is not a consistent estimate of $\theta_k$. However, $[(n+p-2)/(n-2)]\widehat\theta_k$ is a consistent estimate. Therefore, we utilize $[(n+p-2)/(n-2)]\widehat\theta_k$ as our final estimate of $\theta_k$.''',[5],'Post-Theorem-2.1 bias correction, not the raw coefficient estimator of the theorem. The later tests retain shrinkage c, so the paper does not consistently distinguish the final corrected estimator from the raw one.',['D6','D7'])
    add(3,r'''The regularization method for estimating $\boldsymbol\theta$ is to minimize the following penalized quadratic loss:
\[
\widehat{\boldsymbol\theta}=\min_{\boldsymbol\theta}\{\operatorname{tr}\widehat{\mathbf R}(\theta_1\mathbf A_1+\cdots+\theta_K\mathbf A_K)-\mathbf I_p\}^2+\sum_{k=1}^Kp_\lambda(|\theta_k|),
\]
(5)
where $p_\lambda(\cdot)$ is a penalty function with a tuning parameter $\lambda$, which can be selected by a data-driven method such as the high-dimensional Bayesian information criterion (HBIC), as proposed by (Wang, Kim and Li (2013)). Commonly used penalty functions can be found in Fan et al. (2020). In our numerical study, we focus on the SCAD penalty (Fan and Li (2001)) and the MCP penalty (Zhang (2010)). The tuning parameter $\lambda$ is selected by using the HBIC.''',[7],'Original min rather than argmin and trace/bracket placement preserved. Penalties and HBIC are named, not defined, in the main text. No theorem proves a selection rate or extends the raw-estimator CLT to arbitrary penalized fits.',['D4','D5'])
    add(4,r'''For the purpose of power comparison, let us simplify the expression of $Q(\delta_n,\sigma_0\mid\alpha)$. Following Bai and Saranadasa (1996), it is assumed that $\delta_n=o(1)$ and $\lim_{n\to\infty}n_1/n\to\gamma\in(0,1)$.''',[8],'Additional local-signal and sample-allocation restrictions for Section 2.3 comparison. Retain the double limit/arrow wording; do not add these to the complete Theorem 2.4 quotation.',['D18'])
    add(5,r'''To ensure the first term in (9) dominates the second term in (9), it is assumed that
\[
p^{-2}\operatorname{tr}(\mathbf R^2)=o(1),\quad\text{and}\quad p^{-2}\sum_{h=1}^p\mathbf e_h^T\mathbf R^2\mathbf e_h\mathbf e_h^T\mathbf R^{-1}\mathbf e_h=o(1).
\]
(10)''',[8],'Trace conditions only for the simplified power comparison, not silently imported into the full theorem normalizers.',['D3'])
    add(6,r'''In the development of the theoretical properties of the testing method, it is assumed that the set of true basis matrices of the precision matrix is included in the candidate set of the basis matrices.''',[22],'Explicit exact-model scope. Numerical performance with a misspecified candidate set is not a proved robustness theorem.',['D4'])
    add(7,r'''In this paper, it is assumed that the number of active basis matrices of the precision matrix is finite, although the number of basis matrices in the candidate set is allowed to diverge because we can use the regularization method to select the active basis matrices. It would be of particular interest to consider the possibility of allowing $K\to\infty$ in order to encompass a more extensive class of precision matrices in future research.''',[22],'Finite active K in the theory; growing candidate sets and numerical selection do not supply a growing-active-dimension CLT.',['D4'])
    add(8,r'''Although Theorems 2.3–2.4 in this paper require the bounded spectral norm of the population correlation matrix, the restrictions may be relaxed following the proof of Theorems 2.2–2.3 in Zheng et al. (2019), which removes the bounded spectral norm restriction.''',[22],'Main-text author clarification of theorem scope is also indexed as D19. The cited relaxation is future work here, not an additional inventoried theorem.',['D19'])
    add(9,r'''Assume that for any $\mathbf a$ satisfying $\|\mathbf a\|=1$, $\sqrt n\mathbf a^T\mathbf\Sigma^{-1/2}(\bar{\mathbf x}_1-\bar{\mathbf x}_2)$ asymptotically follows a normal distribution $N(\sqrt n\mathbf a^T\boldsymbol\mu_d,(n/n_1+n/n_2))$, where $\boldsymbol\mu_d=\boldsymbol\mu_1-\boldsymbol\mu_2$.''',[4],'Motivating directional approximation for choosing W, not a separate numbered theorem. The displayed mean omits the whitening factor present in the random variable; preserve and flag instead of rewriting it.',['D1','D2'])
    add(10,r'''Then the proof of Theorem 2.1 is completed.''',[12],'The proof calculation concludes with an o_p(1) error, while the theorem states almost sure convergence. This source discrepancy is not repaired in the inventory.')
    issues=[]
    def issue(i,pages,note):issues.append(dict(issue_id=i,evidence=[dict(page=p,location='Source scope or notation issue') for p in pages],note=note))
    issue('sample-versus-population-b',[5,6],'The symbol B first denotes p^-1 tr(Rhat A_k Rhat A_l), then denotes the population trace matrix plus the y correction in Theorem 2.2. Local entries D6 and D10 preserve distinct meanings.')
    issue('coefficient-estimator-overloading',[5,7,12],'Theta-hat is the unpenalized B^-1 b estimator in T2.1–T2.2. The text calls its bias correction the final estimate, then reuses theta-hat for penalized estimation. T2.3 retains shrinkage c and its proof uses the raw asymptotic coefficient behavior. No unconditional extension to penalized/corrected fits is asserted by this census.')
    issue('inverse-existence',[5,6,7],'The source uses sample and population B inverses, inverse sample diagonal square roots, and inverse/diagonal normalization of Rhat_L without explicit nondegeneracy, eigenvalue bounds or fitted positive-definiteness guarantees. Known symmetric bases alone do not guarantee these operations are defined.')
    issue('unit-aspect-ratio',[5,6],'The preceding assumption only requires a finite y=p/(n-2) limit; Theorem 2.2 contains (1−y)^-2, singular at y=1. Retain the formula and record the missing explicit exclusion rather than replacing its denominator.')
    issue('zero-contrast-scale',[5,6],'Theorem 2.2 quantifies over any constants pi_1,...,pi_K, including the zero contrast, but normalizes by sigma^-1. No sigma>0 or variance nondegeneracy is explicitly stated. Preserve the quantifier and flag this limitation.')
    issue('trace-power-placement',[5,6,7],'The quadratic loss and variance contain trace/matrix powers whose placement matters. In particular Theorem 2.2 prints both tr[(RD1)^2] and tr(RD1)^2. Equation (5) additionally prints min rather than argmin and a trace/scalar-minus-identity expression. All are retained without repair.')
    issue('almost-sure-versus-proof',[5,11,12],'Theorem 2.1 states almost sure convergence, whereas the displayed proof establishes an o_p(1) expansion. The census preserves the theorem assertion and does not claim proof verification.')
    issue('test-statistic-scaling',[4,7],'Equation (2) contains n; (7) omits it despite the substitution description. T_n is retained without n, and theorem normalizations use nT_n exactly as printed.')
    issue('null-and-alternative-inheritance',[7,8],'Theorem 2.4 invokes T2.3 conditions while explicitly replacing H0 by H1. It does not assume both. The condition inheritance does not import T2.2 contrast-specific conclusion, nu or sigma into the null/alternative tests.')
    issue('later-spectral-condition',[7,8,22],'The Discussion explicitly says T2.3–T2.4 require bounded population-correlation spectral norm, although their printed statements do not spell it out. Record that as a separate source condition D19; do not rewrite the quoted statements.')
    issue('local-alternative-scope',[8,22],'The full T2.4 prints H1 without a local-signal rate. Delta_n=o(1), sample proportion and trace conditions are introduced later for simplified power comparisons; the Discussion calls the alternative local. Preserve both the printed theorem and this scope ambiguity.')
    issue('finite-active-bases',[4,22],'Known exact basis representation and finite active K are part of the theory. Growing candidate sets and selection in simulations do not establish a theorem for an arbitrary growing active K or model misspecification.')
    issue('directional-whitening',[4],'The motivating normal approximation whitens the sample-mean difference but prints an unwhitened mean vector in its Gaussian mean. This is archived as source context, not used to alter theorem statements.')
    refs=[dict(from_claim_id=PID+'/T2.2',to_source_label='Theorem 2.1',reference_kind='assumption_reference',scope='Inherit the population model, fourth moment, finite aspect ratio and underlying exact linear estimator setting.'),dict(from_claim_id=PID+'/T2.3',to_source_label='Theorem 2.2',reference_kind='assumption_reference',scope='Inherit assumptions, not the arbitrary contrast, coefficient-CLT centering nu or scale sigma.'),dict(from_claim_id=PID+'/T2.4',to_source_label='Theorem 2.3',reference_kind='assumption_reference',scope='Retain common assumptions and population normalizers; replace H0 by H1, and use population c rather than c-hat.'),dict(from_claim_id=PID+'/T2.1',to_source_label='Lemma 2.5',reference_kind='proof_only',scope='Trace convergence lemma is used in the proof; not a statement dependency.'),dict(from_claim_id=PID+'/T2.2',to_source_label='Supplementary Material',reference_kind='proof_only',scope='Proof is deferred, but the entire theorem and all of its auxiliary formulas are printed in the main text. No supplement body read.')]
    bindings={
'T2.1':'D1–D6 give the common-covariance samples, pooled S, R and D decomposition, known symmetric linear inverse-correlation model, sample correlation and unpenalized estimator. D7 supplies y_n−2 and finite y. D8 is the printed standardized iid-coordinate fourth-moment model. K is finite in the theory per A6–A7. No regularized estimator is substituted; a.s. wording is preserved despite proof o_p notation.',
'T2.2':'Inherits T2.1 assumptions and adds D9 trace boundedness. The coefficient estimator remains D6. D10 is the new population B; D12 builds D1 from its inverse and the arbitrary contrast pi. D11 supplies beta_w, D0 and g; D13 gives the complete nu and sigma². D and D0/D1, sample/population B and trace powers remain distinct. Zero contrast, y=1 and invertibility issues remain explicit.',
'T2.3':'Inherits the T2.2 assumptions, including trace boundedness and the exact coefficient model, but not its contrast-specific conclusion. D14–D15 form the fitted precision and T_n. D16 supplies population mu0, sigma0² and A0; D17 supplies plug-in Rtilde and estimated normalizers; c-hat=1/(1+p/(n−2)) is local. D19 records the later explicit bounded-spectral-norm condition. H0 is the null; raw-versus-corrected/penalized fit scope remains flagged.',
'T2.4':'Inherits the common T2.3 assumptions with H1 replacing H0. D15 is T_n, D16 its population null mean/variance, D18 supplies population c and Mahalanobis delta_n. The full power formula uses Phi and Phi(−z_alpha)=alpha; no estimated normalizer occurs in the printed limit. D19 retains the Discussion spectral requirement. Additional Section 2.3 local-signal and trace conditions A4–A5 are not silently inserted into the statement.'}
    out=dict(paper_id=PID,status='extracted',unranked_auxiliary_passages=aux,source_issues=issues,source_claim_references=refs,statement_local_bindings=bindings,ambient_prerequisites=['Euclidean vectors, symmetric positive-definite covariance matrices, diagonal extraction and square roots, trace, standard coordinate columns e_k, normal distribution and its CDF, convergence in distribution and almost surely.','n=n1+n2; n−2 pooled degrees of freedom; p,n→infinity and finite active K are retained with the main-text context. No invertibility or nondegeneracy repair is inferred.'],extraction_policy='All four main-text Theorems with complete original statements. Definitions and context preserve reused notation and unresolved scope. No supplementary body, mathlib audit or proof certification.')
    (ROOT/'ambient-prerequisites.json').write_text(json.dumps(out,indent=2,ensure_ascii=False)+'\n')
if __name__=='__main__':main()
