"""Preserve source conventions separately from the four original theorem statements."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];PID=ROOT.name
aux=[]
def add(aid,text,pages,loc,meaning):
    aux.append(dict(auxiliary_id=aid,statement_original=text.strip(),evidence=[dict(page=p,location=loc) for p in pages],resolution=meaning))
add('A1',r'''For any integer $d\geq1$, we write $[d]=\{1,\ldots,d\}$, and denote by $\mathbf I_d$ the $d\times d$ identity matrix. We denote by $I(\cdot)$ the indicator function. For a vector $\mathbf h=(h_1,\ldots,h_d)^\top$, we write $|\mathbf h|_0=\sum_{j=1}^dI(h_j\ne0)$ and $|\mathbf h|_\infty=\max_{j\in[d]}|h_j|$ for its $L^0$-norm and $L^\infty$-norm, respectively. For a countable set $S$, we use $\#S$ or $|S|$ to denote its cardinality.''',[3],'Notation — finite indices, norms and cardinality','These resolve [p], the fixed-coordinate [s] indexing, support cardinality and identity matrices. The zero counting function is called a norm by the source, without changing it to a genuine norm.')
add('A2',r'''For two sequences of positive numbers $\{a_p\}_{p\geq1}$ and $\{c_p\}_{p\geq1}$, we write $a_p\lesssim c_p$ or $c_p\gtrsim a_p$ if $\limsup_{p\to\infty}a_p/c_p<\infty$, and write $a_p\asymp c_p$ if and only if $a_p\lesssim c_p$ and $c_p\lesssim a_p$ hold simultaneously. We also write $a_p\ll c_p$ or $c_p\gg a_p$ if $\limsup_{p\to\infty}a_p/c_p=0$.''',[3],'Notation — asymptotic comparisons','Theorems 1-4 use positive-sequence comparisons. In particular 1>>gamma means gamma tends to zero, and the intermediate regime in Theorem 1 is comparability, not equality or asymptotic ratio one.')
add('A3',r'''where $\mathcal I=\{(i,j):1\leq i\ne j\leq p\}$ for directed networks, and $\mathcal I=\{(i,j):1\leq i<j\leq p\}$ for undirected networks.''',[4],'After equation (2.1) — admissible edge index set','The beta-model is undirected and uses each upper-triangular edge once. This also shows why the script-I membership chain printed in Theorem 1 is not a well-typed parameter restriction.')
add('A4',r'''For any $\pi>0$, a release mechanism (i.e. a conditional probability distribution) $Q$ satisfies $\pi$-edge differential privacy if
\[
\sup_{\mathbf X,\mathbf Y\in\mathcal X:\,\delta(\mathbf X,\mathbf Y)=1}\ \sup_{\mathbf Z\in\mathcal X:\,Q(\mathbf Z\mid\mathbf X)>0}\frac{Q(\mathbf Z\mid\mathbf Y)}{Q(\mathbf Z\mid\mathbf X)}\leq e^\pi.\tag{2.2}
\]''',[4],'Definition 1 — Edge differential privacy','Privacy is background context for the jittering restrictions. The four Theorems are estimator results under a specified noise mechanism; they do not quantify over arbitrary privacy kernels. Here X is the finite adjacency space and delta counts differing admissible edges as in (2.1). The denominator-positive restriction is retained literally.')
add('A5',r'''\[
\pi=\log\left\{1+\frac{1-\alpha-\beta}{\min(\alpha,\beta)}\right\}.
\]''',[5],'Remark 1 — jittering privacy parameter','This gives the exact privacy calibration for the kernel under the interior restrictions used by the theorems. The zero-noise endpoints discussed in remarks require limiting conventions and are not members of M(gamma;C_1).')
add('A6',r'''Put $N=(p-1)(p-2)$.''',[9],'Section 3.3.2 — sample-size abbreviation','N is the number of ordered pairs of nodes avoiding a selected node, twice |H_ell|. It is not the number of network edges p(p-1)/2.')
add('A7',r'''In the sequel, we always assume that the privacy level $\pi\to0$ together with the number of nodes $p\to\infty$.''',[10],'Section 4 — standing bootstrap-section convention','Theorems 2/3 have gamma tending to zero explicitly, consistent with this standing convention and pi comparable to gamma. Theorem 1 also allows a fixed gamma in part (a); this later convention does not apply retroactively.')
add('A8',r'''Write $\widehat{\boldsymbol\theta}=(\widehat\theta_1,\ldots,\widehat\theta_p)^\top$ where $\widehat\theta_\ell$ is the proposed moment-based estimator given in (3.8) based on the sanitized data $\mathbf Z$.''',[12],'Immediately before Theorem 3 — estimator vector','This identifies the original estimator in Theorem 3, not the twice-jittered estimator or a fitted parameter vector under a bootstrap law.')
add('A9',r'''Note that
\[
\mathbb P(X_{i,j}=0)=\frac{\mathbb E\{\varphi_{(i,j),0}^\dagger\}}{(1-2\delta)(1-\alpha-\beta)}\quad\text{and}\quad\mathbb P(X_{i,j}=1)=\frac{\mathbb E\{\varphi_{(i,j),1}^\dagger\}}{(1-2\delta)(1-\alpha-\beta)}.
\]''',[11],'Section 4.1 — bootstrap population law','The printed expectation identities refer to the original graph probabilities, so the expectations used in mu-dagger and nu-dagger are population expectations over both noise stages. They are not conditional expectations given the realized sanitized graph.')
add('A10',r'''The sparse β-model (6.1) can be reformulated as the standard β-model (3.1) with
\[
|\boldsymbol\theta|_\infty\begin{cases}
\sim\left|\dfrac{\omega_1}2-\omega_2\right|\log p,&\text{if }\omega_1\ne2\omega_2,\\
=o(\log p),&\text{if }\omega_1=2\omega_2.
\end{cases}
\]''',[17],'After equation (6.2) — displayed sparse-parameter norm claim','This display neglects the inactive coordinates theta_ell=xi/2 when omega_1>0. For instance omega_1=2omega_2>0 and s=o(p) leave inactive coordinates of logarithmic magnitude. It is recorded as a source inconsistency, not imposed as an extra assumption on Theorem 4.')
issues=[]
def issue(key,text,pages):issues.append(dict(issue_id=key,description=text,evidence=[dict(page=p,location='Inspected main-text source convention') for p in pages],resolution_status='source_preserved'))
issue('S1','Theorem 1 prints (alpha,beta) in script I in M(gamma;C_1). Script I denotes the edge-index set on page 4. This is an ill-typed or typographical membership chain, not a silently corrected hypothesis. Theorem 2 refers to the conditions of Theorem 1 and inherits this unresolved source wording.',[4,9,12])
issue('S2','Theorem 4 prints exp(-|xi^+| vee max_S |check-theta^+|) without grouping the maximum under the minus sign. Its intended negative-maximum interpretation is suggested by the subsequent chi_p^-1 discussion, but the original theorem formula is not repaired.',[18])
issue('S3','Theorem 4 writes the same rate expression as a literal equality between the intercept error and the maximum sparse-effect error. The preceding triangle inequalities justify bounds, not equality of those random errors. The printed chain is retained.',[18])
issue('S4','The source defines tilde-O_p through some sufficiently small fixed positive epsilon and a factor p^epsilon. It neither means only logarithmic factors nor explicitly quantifies every epsilon. This nonstandard convention is preserved.',[18])
issue('S5','The original and bootstrap moment estimators use logarithms of empirical ratios that may be zero, negative or undefined on finite-sample outcomes. No measurable fallback or truncation is specified. Asymptotic rates do not themselves define the estimator on all outcomes.',[8,11])
issue('S6','Noise variables are described as independent (and bootstrap noises iid), but independence from the original graph or the first sanitized graph is not separately stated. The conditional-flip identities and population-moment identities use fresh release noise. This implicit kernel interpretation is documented rather than added to quoted source statements.',[5,7,11])
issue('S7','The class M uses C_1<alpha,beta<0.5 and gamma=1-alpha-beta. It is empty when gamma>=1-2C_1, despite stating the nominal range gamma in (0,1]. The unnoised gamma=1 case discussed in remarks is outside this class.',[8,10])
issue('S8','Theorem 2 refers to the conditions of Theorem 1. Its own gamma window ranges across the three alternative phase branches; these branches are not simultaneous hypotheses. No Theorem-1 conclusion is imported as a new statement dependency.',[9,10,12])
issue('S9','Theorem 2 is printed as convergence of theta-hat-dagger centered at theta and normalized by population nu-dagger. It is not a conditional bootstrap theorem centered at theta-hat. Theorem 3 uses theta-hat and population V-dagger. The later Monte Carlo variance estimate is a different object.',[11,12,13])
issue('S10','The sparse model uses R_+^p together with a zero minimum, so nonnegativity must include zero here. Its residual parameters can be signed. The source does not define max over an empty support, although the sparsity conditions alone allow empty support.',[17,18])
issue('S11','The norm display following (6.2) omits the inactive coordinates xi/2. In particular it claims o(log p) when omega_1=2omega_2, even though omega_1>0 and inactive nodes yield order log p. This asserted identity is not treated as a separate definition or condition.',[17])
issue('S12','Theorem 4 does not assume the dense-model Condition 1 or give a sparse bootstrap central limit theorem. The preceding section explicitly describes a limited sparse extension. Dense assumptions and bootstrap variance interfaces are excluded from its dependency closure.',[17,18])
issue('S13','The sparse estimates in (6.3) are unthresholded. They are not constrained to be nonnegative or to have support S, and the theorem does not promise support recovery.',[18])
issue('S14','Theorems 1/2 keep s fixed as p grows. Theorem 3 is p-dimensional. Theorem 4 uses s as the size of a potentially growing sparse support with s=o(p). These quantifiers are distinct despite reusing the letter s.',[9,12,13,17,18])
issue('S15','Inverse square roots of variance terms and triangle averaging require positive normalizations and p>=3. These hold eventually under the interior model restrictions for the intended population quantities, but the source does not supply arbitrary-value conventions for excluded finite cases.',[7,9,12])
issue('S16','Theorem 4 uses M(gamma,C_1) with a comma, whereas the class definition uses a semicolon. The same class is resolved from Section 3.3 while the printed theorem punctuation remains unchanged.',[8,18])
issue('S17','Definition 1 takes a supremum only where the denominator Q(Z|X)>0. For general kernels with unequal supports, this does not expressly compare the omitted zero-denominator case; the census retains the exact definition. The interior jittering kernel used by the Theorems has common full support.',[4,5,8])
issue('S18','References to proofs and variance estimates in the Appendix or embedded supplement were not followed. The pinned source is arXiv v2; equality of its statements to final journal wording has not been established.',[9,10,17,18])
resolution={
 'shared':'Finite node indices, indicators, cardinalities and max norm are defined in A1/A3; asymptotic comparisons in A2; N in A6. Expectations, variances, real powers, logarithms, diagonal matrices, transpose, Gaussian laws, convergence in distribution and ordinary deterministic/stochastic big-O use their standard meanings under the pinned graph-and-noise model. Matrix/vector inequalities in Theorem 3 are componentwise (lower orthants). No library-availability claim is made. Conditions uniform in p retain their fixed-constant scope.',
 '1':'p tends to infinity; fixed s and chosen distinct indices ell_1,...,ell_s, fixed C_1 and the three gamma regimes are bound in the theorem. D2 supplies theta, D4 the admissible privacy pair, D5 Condition 1, D8 the original moment estimate and D10 the two population variance components. N=(p-1)(p-2), diag and the standard s-dimensional Gaussian resolve the normalizations. The extra script-I membership remains unresolved source wording (S1).',
 '2':'The opening reference supplies the dense beta-model, admissible privacy pair and Condition 1 from Theorem 1, without conjoining its alternative regimes. Fixed s and its indices are bound again. Delta and c are bound in this theorem; gamma follows its own stated window and A7. D14 is the bootstrap estimator; D16 supplies nu-dagger, D11 supplies nu in part (b). Original theta is the center; no conditional expectation or empirical variance normalization is substituted.',
 '3':'Theorem-bound delta and gamma sequences obey the displayed stronger restrictions. D2/D4/D5 give the dense model and assumptions, D8/A8 the original estimator vector, and D16 nu-dagger. V-dagger is defined inside the theorem as its diagonal matrix, xi is bound there as a p-dimensional standard Gaussian, and u ranges over R^p. The probabilities are unconditional lower-orthant probabilities, not bootstrap empirical CDFs.',
 '4':'D17 supplies xi, check-theta, S, s and the logarithmic reparametrization with little-o residuals; D18 supplies both sparse estimates via D8. D4 supplies M and gamma; omega_1,omega_2 and chi_p are restricted/defined in the theorem. D19 fixes the nonstandard tilde-O_p convention. The source chi_p parentheses and equality chain remain unresolved (S2/S3). No dense Condition 1, Gaussian approximation or bootstrap variance is inherited.'
}
(ROOT/'ambient-conventions.json').write_text(json.dumps(dict(paper_id=PID,auxiliary_passages=aux,unresolved_source_conventions=issues,standard_ambient_resolution=resolution),indent=2,ensure_ascii=False)+'\n')
print('Saved',len(aux),'auxiliary passages and',len(issues),'source-convention notes.')
