# -*- coding: utf-8 -*-
"""Preserve original main-text definitions and referenced conditions for p1927."""
import json
from save_inventory import ROOT,PID
interfaces=[];members={}
def add(n,term,s,pages,deps,symbols,boundary,heading,kind='definition',context=None,context_page=None,phrases=None):
    lid=f'D{n}'
    m=dict(paper_id=PID,local_id=lid,local_label=heading,source_heading=heading,source_kind=kind,statement_original=s,relation='exact',depends_on=[f'D{i}' for i in deps],evidence=[dict(page=p,location=heading) for p in pages],highlight_symbols=symbols,highlight_phrases=phrases or [])
    kw=dict(paper_id=PID,local_id=lid,source_text=term,label=term[0].upper()+term[1:],kind='term')
    if term not in s:
        assert context and term in context,(lid,term)
        m['naming_context']=[dict(context_id=lid+'/name',text=context,evidence=[dict(page=context_page or pages[0],location='Original naming context')])];kw['context_id']=lid+'/name'
    members[lid]=m
    interfaces.append(dict(interface_id=PID+'/'+lid,rank_group='all',name=kw['label'],lean_role='definition',type_shape=boundary,semantic_boundary=boundary,members=[m],source_keywords=[kw],central_claim_uses=[],dependencies=[],theorem_explanations={}))
add(1,'discounted Markov reward process',r'''A discounted Markov reward process, denoted by $\mathscr I(\mathcal P,r,\gamma)$, consists of the combination of a Markov chain, a discount factor $\gamma\in(0,1)$, along with a reward function $r$. In the infinite-horizon discounted setting studied here, the Markov chain is homogeneous, defined on a state space $\mathcal X$ with a transition kernel $\mathcal P:\mathcal X\times\mathcal X\to\mathbb R$. The reward function $r:\mathcal X\to\mathbb R$ models the reward associated with each given state, and for some specified discount factor $\gamma\in(0,1)$, our goal is to maximize the expected discount sum of all future rewards.''',[5],[],[r'\mathscr I(\mathcal P,r,\gamma)',r'\gamma\in(0,1)'],'Homogeneous discounted reward process with given reward and discount. Preserve the printed real-valued transition-kernel signature; a general measure-kernel interpretation is not substituted into the original.','Section 2.1 — Problem formulation')
add(2,'value function',r'''More precisely, we define the value function $V^*:\mathcal X\to\mathbb R$ via
\[
V^*(x):=\mathbb E\left[\sum_{h=0}^\infty\gamma^h r(X_h)\mid X_0=x\right],
\]
(1)
where the expectation is taken over a trajectory $(x,X_1,X_2,\ldots)$ from the Markov chain governed by the transition kernel $\mathcal P$. The existence of the value function $V^*$ is guaranteed by mild assumptions such as the boundedness of reward $r$. For future reference, we note that the value function $V^*$ is the solution to the Bellman fixed point equation
\[
V^*(x)=r(x)+\gamma\,\mathbb E_{X'\mid x}V^*(X')\quad\text{for any }x\in\mathcal X.
\]
(2)''',[5],[1],[r'V^*(x):=',r'\sum_{h=0}^\infty\gamma^h r(X_h)'],'True discounted value function. This is not automatically the projected target theta-star; equality is specific to realizable lower-bound families.','Section 2.1 — Value function (1)-(2)')
add(3,'i.i.d. observation model',r'''Throughout our discussion, we consider the i.i.d. observation model, where the dataset consists of $n$ i.i.d. sample pairs $\{(x_i,x'_i)\}_{i=1}^n\subset\mathcal X\times\mathcal X$. We let $\mu$ be any stationary distribution of the Markov chain $\mathcal P$. The sample pair $(x_i,x'_i)$ is generated by
\[
x_i\sim\mu,\qquad\text{and}\qquad x'_i\sim\mathcal P(\cdot\mid x_i).
\]
(3)
The joint distribution induced by the pair $(\mu,\mathcal P)$ corresponds to the stationary joint distribution over consecutive state pairs in the Markov chain.''',[5,6],[1],[r'x_i\sim\mu',r"x'_i\sim\mathcal P(\cdot\mid x_i)"],'Independent transition pairs sampled from a stationary starting law; within-pair dependence is retained. This is not one correlated trajectory, and uniqueness of the stationary law is not assumed.','Section 2.1 — Observation model (3)',kind='source_passage')
add(4,'projection operator',r'''Given a convex class of functions $\mathbb G$ closed in $L^2(\mu)$, the projection operator $\Pi:L^2(\mu)\to\mathbb G$ is given by
\[
\Pi(f):=\arg\min_{g\in\mathbb G}\|g-f\|_\mu\quad\text{for any function }f\in L^2(\mu).
\]
(5)''',[6],[],[r'\Pi(f):=',r'\arg\min_{g\in\mathbb G}\|g-f\|_\mu'],'Metric projection onto the stated closed convex function class under a given measure. The standard L2 norm is retained as ambient notation; this generic definition does not require iid sampling.','Section 2.1 — Projection operator (5)')
add(5,'projected fixed point',r'''We then seek a solution to the projected fixed point equation
\[
\theta^*=\Pi\big(\mathcal T(\theta^*)\big)
\]
(6)
where $\mathcal T(\theta^*)(x):=r(x)+\gamma\,\mathbb E_{X'\mid x}\theta^*(X')$ is the Bellman operator. Since the Bellman operator is contractive in the $L^2(\mu)$-norm and $\Pi$ is non-expansive, this fixed point equation has a unique solution.''',[6],[1,4],[r'\theta^*=\Pi\big(\mathcal T(\theta^*)\big)',r'\mathcal T(\theta^*)(x):='],'Projected Bellman target for the closed convex class. The stationary-law justification of contraction is preserved separately in the original footnote.','Section 2.1 — Projected fixed point (6)')
add(6,'reproducing kernel Hilbert spaces',r'''An RKHS is a particular type of Hilbert space of real-value functions $f$ with domain $\mathcal X$. As a Hilbert space, the RKHS has an inner product $\langle f,g\rangle_{\mathbb H}$ along with the associated norm $\|f\|_{\mathbb H}$. The distinguishing property of an RKHS is the existence of a symmetric kernel function $\mathcal K:\mathcal X\times\mathcal X\to\mathbb R$ that acts as the representer of evaluation. In particular, for each $x\in\mathcal X$, the function $z\mapsto\mathcal K(z,x)$ belongs to the Hilbert space, and moreover we have
\[
\langle\mathcal K(\cdot,x),f\rangle_{\mathbb H}=f(x)\quad\text{for all }f\in\mathbb H.
\]
(7)
In order to simplify notation, in much of our development, we adopt the shorthand $\Phi_x=\mathcal K(\cdot,x)$ for this representer of evaluation.''',[6],[],[r'\langle\mathcal K(\cdot,x),f\rangle_{\mathbb H}=f(x)',r'\Phi_x=\mathcal K(\cdot,x)'],'Real-function RKHS, its norm and kernel evaluation representer. RKHS completeness in its own norm is distinct from closedness in L2(mu).','Section 2.2 — Reproducing kernel Hilbert spaces',context='We begin with some basic background on reproducing kernel Hilbert spaces; see the books [15, 3, 43] for more details.')
add(7,'covariance and cross-covariance operators',r'''In particular, the covariance and cross-covariance operators are defined as
\[
\Sigma_{\mathrm{cov}}:=\mathbb E_{X\sim\mu}[\Phi_X\otimes\Phi_X]\quad\text{and}\quad\Sigma_{\mathrm{cr}}:=\mathbb E_{(X,X')\sim\mu\times\mathcal P}[\Phi_X\otimes\Phi_{X'}].
\]
(8)
By construction, the covariance operator $\Sigma_{\mathrm{cov}}(f)$, when applied to some $f\in\mathbb H$, has the property that $\langle g,\Sigma_{\mathrm{cov}}(f)\rangle_{\mathbb H}=\mathbb E_{X\sim\mu}[g(X)f(X)]$, with a similar property for the cross-covariance operator.''',[7],[3,6],[r'\Sigma_{\mathrm{cov}}:=',r'\Sigma_{\mathrm{cr}}:=',r'\Phi_X\otimes\Phi_{X\'}'.replace("\\'","'")],'Population operators under the stationary transition-pair law. The source product notation mu times P denotes sampling from the kernel, not independent X and X-prime. Tensor orientation is retained.','Section 2.2 — Covariance and cross-covariance operators (8)')
add(8,'population-level kernel LSTD estimate',r'''The population-level kernel LSTD estimate $\theta^*$ is, by definition, equal to the projected fixed point (6) with the choice $\mathbb G=\mathbb H$. Since $\mathbb H$ is a reproducing kernel Hilbert space, this fixed point has a more explicit expression in terms of certain operators defined on the Hilbert space.''',[7],[5,6],[r'\theta^*',r'\mathbb G=\mathbb H'],'Population projected target in the RKHS. The operator identity (9) and reward-membership footnote are auxiliary characterizations, not a silent claim that every RKHS is L2-closed.','Section 2.2 — Population-level kernel LSTD estimate')
add(9,'empirical operators',r'''\[
\widehat\Sigma_{\mathrm{cov}}:=\frac1n\sum_{i=1}^n\Phi_{x_i}\otimes\Phi_{x_i},\qquad\text{and}\qquad\widehat\Sigma_{\mathrm{cr}}:=\frac1n\sum_{i=1}^n\Phi_{x_i}\otimes\Phi_{x'_i}.
\]''',[7],[3,6],[r'\widehat\Sigma_{\mathrm{cov}}:=',r'\widehat\Sigma_{\mathrm{cr}}:='],'Empirical rank-one operator averages based on the observed transition pairs. The cross term retains its current-state/successor-state orientation.','Section 2.2 — Empirical operators',context='and we have defined the empirical operators')
add(10,'regularized kernel LSTD estimate',r'''In this paper, we analyze the regularized kernel LSTD estimate $\widehat\theta$ given by the solution to the equation
\[
(\widehat\Sigma_{\mathrm{cov}}+\lambda_n\mathcal I)\widehat\theta=(\widehat\Sigma_{\mathrm{cov}}+\lambda_n\mathcal I)r+\gamma\widehat\Sigma_{\mathrm{cr}}\widehat\theta.
\]
(10)
where $\lambda_n>0$ is a user-defined regularization parameter, $\mathcal I$ is the identity operator on the Hilbert space,''',[7],[9,6,1],[r'(\widehat\Sigma_{\mathrm{cov}}+\lambda_n\mathcal I)r',r'\gamma\widehat\Sigma_{\mathrm{cr}}\widehat\theta'],'Regularization acts on the reward term too; preserve the source fixed-point estimator instead of substituting a conventional ridge-regression objective. Existence/uniqueness conventions remain subject to the original conditions.','Section 2.2 — Regularized kernel LSTD estimate (10)')
add(11,'kernel eigenfunctions',r'''under relatively mild conditions (required to satisfy Mercer's theorem, and assumed here), the kernel function admits a decomposition of the form
\[
\mathcal K(x,z)=\sum_{j=1}^\infty\mu_j\phi_j(x)\phi_j(z),
\]
(12)
where $\{\mu_j\}_{j=1}^\infty$ are a non-negative sequence of eigenvalues, and $\{\phi_j\}_{j=1}^\infty$ are the kernel eigenfunctions, orthonormal in $L^2(\mu)$.''',[8],[6,3],[r'\mathcal K(x,z)=\sum_{j=1}^\infty\mu_j\phi_j(x)\phi_j(z)',r'\{\phi_j\}_{j=1}^\infty'],'Mercer-type kernel decomposition under the chosen stationary law. The lower-bound envelope sequence is distinguished from each instance spectrum in the full specification.','Section 2.2 — Kernel eigenfunctions (12)',kind='source_passage')
add(12,'kernel boundedness condition',r'''First, we assume that the kernel function is uniformly bounded, in the sense that
\[
\sup_{x\in\mathcal X}\sqrt{\mathcal K(x,x)}\leq b
\]
(13)
for some finite constant $b$.''',[8],[6],[r'\sup_{x\in\mathcal X}\sqrt{\mathcal K(x,x)}\leq b'],'Uniform bound on square roots of kernel diagonal entries, not a bound b on the diagonal itself.','Section 3.1 — Kernel boundedness condition (13)',kind='assumption',context='Under the kernel boundedness condition (13),',context_page=10,phrases=['(13)'])
add(13,'kernel eigenfunctions',r'''In addition, one of our results—namely, a so-called “fast rate”—requires a bound on the sup-norm of the kernel eigenfunctions $\{\phi_j\}_{j=1}^\infty$: that is, we assume that
\[
\max_{j\geq1}\|\phi_j\|_\infty\leq\kappa\quad\text{for some finite quantity }\kappa.
\]
(14)''',[8],[11],[r'\max_{j\geq1}\|\phi_j\|_\infty\leq\kappa'],'Additional uniform bound for the fast-rate branch. It is not an assumption of Theorem 1(a).','Section 3.1 — Eigenfunction bound (14)',kind='assumption',phrases=['(14)'])
add(14,'effective horizon',r'''The discount factor $\gamma\in(0,1)$ enters via the effective horizon $H:=\frac1{1-\gamma}$.''',[8],[1],[r'H:=\frac1{1-\gamma}'],'Effective horizon defined by the discount factor; distinct from the blackboard-bold RKHS H.','Section 3.1 — Effective horizon')
add(15,'radius',r'''The structural properties of the projected fixed point $\theta^*$ are captured by a user-defined radius $R$ such that
\[
R\geq\max\left\{\|\theta^*-r\|_{\mathbb H},\frac{2\|\theta^*\|_\infty}{b}\right\}.
\]
(15)''',[9],[8,6,12],[r'\|\theta^*-r\|_{\mathbb H}',r'\frac{2\|\theta^*\|_\infty}{b}'],'Joint RKHS-distance and uniform-size bound for the upper-bound target; R may exceed the displayed maximum.','Section 3.1 — Structural properties of fixed point (15)',kind='condition',phrases=['(15)'])
add(16,'Bellman residual variance',r'''Playing the role of the noise level is the variance of the Bellman residual error, when evaluated at $\theta^*$. It is given by
\[
\sigma^2(\theta^*):=\mathbb E\left[(\theta^*(X)-r(X)-\gamma\theta^*(X'))^2\right],
\]
(16)
where $(X,X')$ are successive samples from the Markov chain, with the starting state $X$ drawn according to the stationary distribution.''',[9],[8,3,1],[r'\sigma^2(\theta^*):=',r'(\theta^*(X)-r(X)-\gamma\theta^*(X\'))^2'.replace("\\'","'")],'The source calls this variance but displays an uncentered second moment; preserve the formula and the projected-target argument.','Section 3.1 — Bellman residual variance (16)',context='Bellman residual variance:')
add(17,'critical inequality',r'''More precisely, we consider positive solutions $\delta>0$ to the $\zeta$-based critical inequality
\[
\mathcal C(\delta):=\sqrt{\sum_{j=1}^\infty\min\left\{\frac{\mu_j}{\delta^2},1\right\}}\leq\underbrace{\frac{\sqrt n\,R}{H(\gamma)\,\zeta}}_{\text{Slope (SNR)}}\,\delta,
\]
($\operatorname{CI}(\zeta)$)
where $\zeta>0$ is a parameter to be specified. Note that the function on the left-hand side is decreasing in $\delta$, whereas the right-hand side is linear in $\delta$ with the indicated slope. Consequently, inequality ($\operatorname{CI}(\zeta)$) has a unique smallest positive solution, which we denote by $\delta_n(\zeta)$. To be clear, in addition to depending on the sample size $n$ and $\zeta$, this smallest positive solution also depends on the eigenvalues as well as the pair $(R,\gamma)$, but we suppress this dependence so as to simplify notation.''',[9],[11,15,14],[r'\mathcal C(\delta):=',r'\delta_n(\zeta)',r'\operatorname{CI}(\zeta)'],'Upper critical inequality with instance eigenvalues and user radius. Existence of a smallest positive solution and zero-noise edge cases retain the source qualifications.','Section 3.1.1 — Kernel-based critical inequality')
add(18,'Non-asymptotic upper bounds',r'''Both parts of our theorem guarantee that the kernel LSTD estimator satisfies a bound of the form
\[
\|\widehat\theta-\theta^*\|_\mu^2\leq c_1R^2\left\{\delta^2+\frac{\lambda_n}{1-\gamma}\right\}
\]
(17)
with probability at least $1-2\exp\left(-\frac{c_2n\delta^2(1-\gamma)^2}{b^2}\right)$, where $(c_1,c_2)$ are universal constants. The two parts differ in the allowable settings of $\delta$ and $\lambda_n$ for which the bound (17) holds.''',[10],[10,8,15,12,3],[r'\|\widehat\theta-\theta^*\|_\mu^2',r'\frac{c_2n\delta^2(1-\gamma)^2}{b^2}'],'The bound referenced by Theorem 1 includes both the squared-L2 error and its tail probability. It is a condition/conclusion template, not an extra theorem environment.','Section 3.1.2 — Bound (17)',kind='source_passage',context='3.1.2 Non-asymptotic upper bounds',phrases=['(17)'])
add(19,'trace class',r'''In all cases, our construction ensures that the eigenfunction bound (14) holds with $\kappa=2$, along with the kernel being trace class. In particular, we have
\[
\max_{j\geq1}\|\phi_j\|_\infty\leq\kappa=2,\qquad\text{and}\qquad\sum_{j=1}^\infty\mu_j\leq\frac{b^2}{4}.
\]
(29a)''',[16],[11,13],[r'\max_{j\geq1}\|\phi_j\|_\infty\leq\kappa=2',r'\sum_{j=1}^\infty\mu_j\leq\frac{b^2}{4}'],'The lower-bound construction fixes the eigenfunction cap at 2 and controls the spectral sum. The full specification distinguishes prescribed mu_j from instance eigenvalues in Regime B.','Section 3.4.1 — Spectral conditions (29a)',kind='condition',phrases=['(29a)'])
add(20,'families of MRPs',r'''In addition, our families of MRPs are also defined by the constraints
\[
\max\left\{\|\theta^*-r\|_{\mathbb H},\frac{2\|\theta^*\|_\infty}{b}\right\}\leq\bar R,\qquad\text{and}\qquad\sigma(\theta^*)\leq\bar\sigma.
\]
(29b)''',[16],[8,6,16],[r'\|\theta^*-r\|_{\mathbb H}',r'\sigma(\theta^*)\leq\bar\sigma'],'Simultaneous radius and noise caps for lower-bound families. Realizability r,theta-star in the RKHS is preserved as adjacent model scope; do not replace sigma by sigma squared in this inequality.','Section 3.4.1 — Family constraints (29b)',kind='condition',phrases=['(29b)'])
add(21,'Families of MRPs',r'''We say that a family $\mathfrak M$ of MRPs is $(\bar R,\bar\sigma)$-valid if its members satisfy the bound (29b), along with the conditions (29a).''',[17],[1,19,20],[], 'Validity means both numbered conditions, not merely bounded reward or a named regime. The source construction also has its stated realizability context.','Section 3.4.1 — Valid MRP families',context='3.4.1 Families of MRPs and regular kernels',context_page=16,phrases=['(29b)','(29a)'])
add(22,'critical radius',r'''So as to match our upper bounds, we prove lower bounds that involve an error term $\delta_n$ defined as the smallest positive solution to the inequality
\[
\sqrt{\sum_{j=1}^\infty\min\left\{\frac{\mu_j}{\delta^2},1\right\}}\leq\sqrt n\,\frac{\bar R(1-\gamma)}{2\bar\sigma}\,\delta.
\]
(30)''',[17],[],[r'\frac{\bar R(1-\gamma)}{2\bar\sigma}',r'\delta_n'],'Lower-bound critical radius for the prescribed numerical sequence and positive parameters. In Regime B this is not silently replaced by the actual instance eigenvalue sequence; the source explicitly clarifies this on page 22.','Section 3.4.1 — Critical radius (30)',context=r'In other words, the critical radius $\delta_n$ in the minimax lower bound $\operatorname{LB}(\bar R,\bar\sigma,\delta_n)$ fully depends on the pre-specified parameters of the MRP families $\mathfrak M_A$ and $\mathfrak M_B$.',context_page=22,phrases=['(30)'])
add(23,'statistical dimension',r'''For a given $\delta_n$, the associated statistical dimension $d_n\equiv d_n(\delta_n)$ is given by $d_n(\delta_n):=\max\{j\mid\mu_j\geq\delta_n^2\}$.''',[17],[22],[r'd_n(\delta_n):=\max\{j\mid\mu_j\geq\delta_n^2\}'],'Largest index whose prescribed eigenvalue reaches the lower critical threshold. Retain the maximum-index definition, rather than replacing it by a trace-based effective dimension.','Section 3.4.1 — Statistical dimension')
add(24,'regular kernel',r'''The kernel is regular if there is a universal constant $c$ such that
\[
\left\{\frac{2\bar\sigma}{\bar R(1-\gamma)}\right\}^2d_n\geq c\,n\,\delta_n^2.
\]
(31)''',[17],[22,23],[r'\left\{\frac{2\bar\sigma}{\bar R(1-\gamma)}\right\}^2d_n\geq c\,n\,\delta_n^2'],'Source spectral regularity at the critical radius; the direction is a lower bound involving d_n. Universal-constant and across-n scope remain as written.','Section 3.4.1 — Regular kernel (31)',kind='condition',context='The notion of a regular kernel, which we define here, precludes such pathology.',phrases=['(31)'])
add(25,'minimax lower bounds',r'''With this set-up, we are now ready to state our minimax lower bounds. For a given $(\bar R,\bar\sigma)$-valid family of MRPs, we say that the lower bound $\operatorname{LB}(\bar R,\bar\sigma,\delta_n)$ holds if
\[
\inf_{\widehat\theta}\sup_{\mathscr I\in\mathfrak M(\bar R,\bar\sigma)}\mathbb P_{\mathscr I}\left(\|\widehat\theta-\theta^*\|_\mu^2\geq c_1\bar R^2\delta_n^2\right)\geq c_2.
\]
($\operatorname{LB}(\bar R,\bar\sigma,\delta_n)$)
In this statement, the quantities $(c_1,c_2)$ are universal constants.''',[17],[3,21,22],[r'\operatorname{LB}(\bar R,\bar\sigma,\delta_n)',r'\inf_{\widehat\theta}\sup_{\mathscr I\in\mathfrak M(\bar R,\bar\sigma)}'],'Uniform lower bound on an error-event probability over all measurable estimators, not an expected-risk bound. The L2 measure is each instance stationary law, as explicitly clarified in Section 4.2.1.','Section 3.4.2 — Minimax lower bound',kind='source_passage')
add(26,'Regime A',r'''We prove minimax lower bounds in two regimes of parameters $(\bar R,\bar\sigma)$, depending on how these parameters scale with the effective horizon $\frac1{1-\gamma}$. In Regime A, this scaling is linear in the effective horizon—namely
\[
\bar R\geq\frac1{6(1-\gamma)}\max\left\{\frac\gamma{\sqrt{\mu_1}},\frac2b\right\},\qquad\text{and}\qquad\bar\sigma^2\in\left[\frac{1+\gamma}{5(1-\gamma)},\frac{1+\gamma}{1-\gamma}\right].
\]
(32a)''',[17],[14],[r'\frac1{6(1-\gamma)}',r'\bar\sigma^2\in\left[\frac{1+\gamma}{5(1-\gamma)},\frac{1+\gamma}{1-\gamma}\right]'],'Numerical Regime A conditions on the radius and squared noise cap; preserve both closed endpoints. The symbols mu_1 and b are prescribed parameters here.','Section 3.4.2 — Regime A (32a)',kind='condition',phrases=['(32a)'])
add(27,'Regime B',r'''In Regime B, by contrast, both of these quantities can be order one with the effective horizon—viz.
\[
\bar R\geq\max\left\{\frac1{2\sqrt{\mu_1}},\frac2{\gamma b}\right\},\qquad\text{and}\qquad\bar\sigma^2\in\left(\frac18,1\right].
\]
(32b)''',[17],[14],[r'\frac1{2\sqrt{\mu_1}}',r'\bar\sigma^2\in\left(\frac18,1\right]'],'Numerical Regime B conditions with a strictly open lower variance endpoint; this is distinct from Regime A, not an equivalent formulation.','Section 3.4.2 — Regime B (32b)',kind='condition',phrases=['(32b)'])
add(28,'stationary distribution',r'''We first precisely define a problem instance $\mathscr I$, especially the roles of stationary distribution therein. In either Regime A or B, we fix an RKHS $\mathbb H=\mathbb H_A$ or $\mathbb H_B$ and a reward function $r=r_A$ or $r_B$ such that $r\in\mathbb H$, and then consider MRPs of the form $\mathscr I(\mathcal P,r,\gamma)$. Throughout the proof of lower bounds, we let $\mu(\mathcal P)$ be the stationary distribution associated with transition kernel $\mathcal P$ and always use notation $\mu$ to denote the Lebesgue measure. The stationary distribution $\mu(\mathcal P)$ plays multiple roles. First, the observation pairs $\{(x_i,x'_i)\}_{i=1}^n$ are generated by drawing $x_i$ from distribution $\mu(\mathcal P)$, and then the successor state $x'_i$ from the probability transition. Note moreover that $\|\cdot\|_\mu$ in equation ($\operatorname{LB}(\bar R,\bar\sigma,\delta_n)$) is an abbreviation of the $L^2(\mu(\mathcal P))$-norm. Specifically, we measure the estimation error by
\[
\|\widehat\theta-\theta^*\|_{\mu(\mathcal P)}^2:=\mathbb E_{\mu(\mathcal P)}\left[(\widehat\theta(X)-\theta^*(X))^2\right].
\]
Finally, the covariance operator $\Sigma_{\mathrm{cov}}(\mathcal P)$ is induced by $\mu(\mathcal P)$, i.e. $\Sigma_{\mathrm{cov}}(\mathcal P)=\mathbb E_{X\sim\mu(\mathcal P)}[\Phi_X\otimes\Phi_X]$ with $\Phi_X$ denoting the representer of evaluation. Below, we take $\{(\mu_j(\mathcal P),\phi_j(\mathcal P))\}_{j=1}^\infty$ as the eigen-pairs associated with $\Sigma_{\mathrm{cov}}(\mathcal P)$.''',[21],[1,3,6,7],[r'\mu(\mathcal P)',r'\|\widehat\theta-\theta^*\|_{\mu(\mathcal P)}^2'],'Explicit full specification of the theorem lower-bound experiment and norm. Lebesgue mu used in the construction is distinct from stationary mu(P); the error norm remains stationary-weighted.','Section 4.2.1 — Full specification of the minimax lower bound',kind='source_passage')
add(29,'MRP family',r'''In Regime A, we suppose the reward function $r_A$ is uniformly bounded, i.e. $\|r_A\|_\infty\leq1$, and define a $(\bar R,\bar\sigma)$-valid MRP family
\[
\begin{aligned}
\mathfrak M_A\equiv\mathfrak M_A(\bar R,\bar\sigma)&\equiv\mathfrak M_A(\bar R,\bar\sigma,\{\mu_j\}_{j=1}^\infty;r_A,\gamma,\mathbb H_A)\\
&:=\{\text{MRP }\mathscr I(\mathcal P,r_A,\gamma)\mid\text{(i) The value function }\theta^*\in\mathbb H_A\text{ and inequalities (29b) hold.}\\
&\qquad\text{(ii) The eigenpairs satisfy }\mu_j(\mathcal P)=\mu_j\text{ for }j=1,2,\ldots\text{ and }\sup_{j\in\mathbb Z_+}\|\phi_j(\mathcal P)\|_\infty\leq2.\}
\end{aligned}
\]
(41a)''',[22],[1,2,6,20,28],[r'\mathfrak M_A',r'\mu_j(\mathcal P)=\mu_j',r'\|r_A\|_\infty\leq1'],'Regime A full family specification: fixed RKHS/reward, true-value realizability, bounded reward, exact prescribed eigenvalues and the common eigenfunction bound. This definition is not the proof-only finite packing.','Section 4.2.1 — MRP family (41a)',phrases=['(41a)'])
add(30,'MRP family',r'''In parallel, the $(\bar R,\bar\sigma)$-valid MRP family $\mathfrak M_B$ is given by
\[
\begin{aligned}
\mathfrak M_B\equiv\mathfrak M_B(\bar R,\bar\sigma)&\equiv\mathfrak M_B(\bar R,\bar\sigma,\{\mu_j\}_{j=1}^\infty;r_B,\gamma,\mathbb H_B)\\
&:=\{\text{MRP }\mathscr I(\mathcal P,r_B,\gamma)\mid\text{(i) }\gamma\|\theta^*\|_{\mu(\mathcal P)}\leq1.\ \text{(ii) }\theta^*\in\mathbb H_B\text{ and inequalities (29b) hold.}\\
&\qquad\text{(iii) The eigenpairs satisfy }\mu_j(\mathcal P)\leq\mu_j\text{ for any }j\geq2\text{ and }\sup_{j\in\mathbb Z_+}\|\phi_j(\mathcal P)\|_\infty\leq2.\}
\end{aligned}
\]
(41b)''',[22],[1,2,6,20,28],[r'\mathfrak M_B',r'\gamma\|\theta^*\|_{\mu(\mathcal P)}\leq1',r'\mu_j(\mathcal P)\leq\mu_j'],'Regime B full family specification: bound on the true value norm and only an eigenvalue upper envelope for j>=2. No equality of spectra, j=1 envelope constraint, or Regime A reward bound is inserted.','Section 4.2.1 — MRP family (41b)',phrases=['(41b)'])
def main():
    ROOT.mkdir(parents=True,exist_ok=True)
    for name,data in [('source-passages.json',dict(paper_id=PID,status='extracted',scope='Original main-text definitions and conditions; independent final source review is separate.',source_passages=list(members.values()))),('interface-extraction.json',dict(paper_id=PID,status='extracted',interfaces=interfaces))]:
        (ROOT/name).write_text(json.dumps(data,indent=2,ensure_ascii=False)+'\n')
    print(f'Saved {len(members)} original source entries; full graph review remains pending.')
if __name__=='__main__':main()
