# -*- coding: utf-8 -*-
"""Save original scope passages and explicit unresolved source conventions."""
import json
from save_inventory import ROOT,PID
A=[]
def passage(n,s,pages,note):A.append(dict(local_id=f'A{n}',statement_original=s,evidence=[dict(page=p,location=f'Original main-text context A{n}',**({'before_main_text_end':True} if p==30 else {})) for p in pages],scope_note=note))
passage(1,r'''For any event $\mathcal E$, we use $\mathbb 1\{\mathcal E\}$ to denote the $0-1$-valued indicator function. We use $C,c,c_0$ etc. to denote universal constants whose numerical values may vary from line to line. For any $D\in\mathbb Z_+$, denote $[D]:=\{1,2,\ldots,D\}$. Given a distribution $\mu$, let $\|\cdot\|_\mu$ denote the $L^2(\mu)$-norm, which is defined as $\|f\|_\mu^2:=\int f^2\mu(dx)$ for $f\in L^2(\mu)$. Notation $\|\cdot\|_\infty$ represents the uniform bound given by $\|f\|_\infty:=\sup_{x\in\mathcal X}|f(x)|$.''',[5],'Standard norms, finite-index notation and universal constants remain explicit ambient context; no library-availability claim is made.')
passage(2,r'''In this paper, we study the problem of estimating the value function $V^*$ on the basis of samples from the Markov chain, when the reward function $r$ and discount factor $\gamma\in(0,1)$ are given.''',[5],'Known reward and known discount are standing in the paper experiment. The footnote discusses an extension, but does not change the stated sampling problem.')
passage(3,r'''This fact is a consequence of the choice $\gamma\in(0,1)$ and the non-expansiveness of the transition operator on $L^2(\mu)$, due to the stationarity of $\mu$.''',[6],'Footnote 2 supports the contraction assertion accompanying the projected fixed point. It does not impose temporal independence on a full trajectory.')
passage(4,r'''In terms of these operators, the population-level kernel LSTD fixed point must satisfy the fixed point relation
\[
\Sigma_{\mathrm{cov}}\theta^*=\Sigma_{\mathrm{cov}}r+\gamma\,\Sigma_{\mathrm{cr}}\theta^*.
\]
(9)''',[7],'Additional operator characterization of D8 using D7; the projected definition is retained separately.')
passage(5,r'''In writing this equation, we have assumed that the reward function $r$ belongs to the Hilbert space; if not, it should be replaced by the projection $\Pi(r)$.''',[7],'Footnote 3 to (9). Keep this assumption and its stated alternative explicit; do not replace r by its projection inside the original estimator or theorem statements.')
passage(6,r'''Consider the empirical estimate $\widehat\theta$ as an estimate of the unknown value function $V^*$. The error $\|\widehat\theta-V^*\|_\mu$ can be decomposed as
\[
\|\widehat\theta-V^*\|_\mu\leq\underbrace{\|\widehat\theta-\theta^*\|_\mu}_{\text{Estimation error}}+\underbrace{\|\theta^*-V^*\|_\mu}_{\text{Approximation error}}.
\]
(11)''',[7],'Distinguishes the upper theorem estimation target from the true value. Theorem 1 controls the first term, not the full error without approximation error.')
passage(7,r'''Minimax lower bounds are obtained by assessing the performance of any estimator in a uniform sense over a particular class of problems. In particular, for classes of MRPs $\mathfrak M$ to be defined, we prove lower bounds of the following type. For a given MRP instance $\mathscr I$, we assume that we observe a dataset $\{(x_i,x'_i)\}_{i=1}^n$ of $n$ i.i.d. samples generated from the given MRP. An estimator $\widehat\theta$ of the value function is any measurable function of the data mapping into $\mathbb R^{\mathcal X}$.''',[15],'Domain of the minimax infimum: any measurable estimator, not only kernel LSTD or functions constrained to the RKHS.')
passage(8,r'''We begin by describing the families of MRPs over which we prove minimax lower bounds. In all of our constructions, both the reward function $r$ and the optimal value function $\theta^*$ are members of a Hilbert space with a set of eigenfunctions $\{\phi_j\}_{j=1}^\infty$, and a sequence of eigenvalues $\{\mu_j\}_{j=1}^\infty$ that vary as part of the construction.''',[16],'Realizability is specific to the lower-bound constructions. The original source calls theta-star the optimal value function here, whereas the general setup names the true value V-star.')
passage(9,r'''Apart from the sample size conditions, Theorem 2 also requires the kernel regularity condition (31), along with the eigensequence condition in part (b).''',[18],'The original theorem body omits (31), but its requirement is explicitly stated in adjacent main-text commentary. It belongs to the theorem scope, not a proof-only prerequisite.')
passage(10,r'''As a point of clarification, we recall that the critical inequality (30) is defined by pre-specified constants $\{\mu_j\}_{j=1}^\infty$, not the eigenvalues $\{\mu_j(\mathcal P)\}_{j=1}^\infty$. In other words, the critical radius $\delta_n$ in the minimax lower bound $\operatorname{LB}(\bar R,\bar\sigma,\delta_n)$ fully depends on the pre-specified parameters of the MRP families $\mathfrak M_A$ and $\mathfrak M_B$.''',[22],'The lower radius is computed from the envelope sequence. Regime A has equality of spectra; Regime B has only the j>=2 inequality. Do not conflate either with the upper bound critical inequality evaluated at a particular MRP spectrum.')
passage(11,r'''The major differences between MRP families $\mathfrak M_A$ and $\mathfrak M_B$ are the regularity conditions and the eigenvalue constraints. In Regime A, the reward function $r_A$ is properly normalized so that $\|r_A\|_\infty\leq1$, whereas we impose an upper bound on the value function norm $\gamma\|\theta^*\|_{\mu(\mathcal P)}$ in Regime B. Besides, in Regime A, the pre-specified parameters $\{\mu_j\}_{j=1}^\infty$ in definition (41a) are exactly the eigenvalues for instances in family $\mathfrak M_A$. In contrast, in Regime B, $\{\mu_j\}_{j=1}^\infty$ are approximations of eigenvalues in the definition (41b) of family $\mathfrak M_B$.''',[22],'Original comparison of the two family definitions; the detailed formula (41b), not this informal word approximations, fixes the exact inequality and its index range.')
passage(12,r'''Second, the analysis of this paper was carried out under i.i.d. assumptions on transition sampling model. However, in practice, the data may be collected from Markov chain trajectories or adaptive experiments and the transition pairs are no longer independent. It would be interesting to see how the dependence in data affects sample complexity of policy evaluation. Third, this paper assumes that samples are drawn from the stationary distribution of the Markov chain; in practice, such data may not be available, so that it is interesting to consider extensions of this kernel LSTD estimator suitable for the off-policy setting.''',[30],'Discussion explicitly confirms the iid stationary-pair scope. This passage is above Appendix A and is clipped with the main text.')
ISSUES=[
('transition-kernel-signature','The source writes a real-valued transition kernel on X times X while allowing general state spaces and conditional sampling. It does not specify a reference measure for a density representation; preserve its notation rather than silently replacing the signature.',[5]),
('rkhs-projection-closedness','The generic projection (5) requires a class closed in L2(mu), and page 7 then sets G=H. An RKHS need not be L2-closed merely because it is complete in its own norm. Preserve the source assumptions and do not assert unconditional existence of that projection for every kernel.',[6,7]),
('reward-membership','Footnote 3 assumes r in H for the operator equation, otherwise proposing Pi(r). The main statements and estimator continue to write r. The extraction records this convention separately without rewriting any original formula.',[7]),
('projected-versus-true-target','Theta-star is a projected fixed point in the general setup, while the realizable lower-bound construction calls theta-star the optimal value function. The upper estimation bound does not alone control approximation error to V-star.',[6,7,16,22]),
('uncentered-residual-variance','Equation (16) is an uncentered second moment, although the source calls it a variance. Zero mean is not inserted as an additional assumption in the extracted definition.',[9]),
('zero-noise-critical-radius','CI(zeta) is defined for positive zeta, but the fast-rate substitution kappa*sigma(theta-star) can be zero in degenerate models. The source does not state a limiting convention for that case.',[9,10,11]),
('degenerate-spectrum','A unique smallest positive critical solution and expressions involving 1/sqrt(mu_1) require nondegenerate parameters. The nonnegative eigenvalue statement does not explicitly list all exclusions such as an identically zero kernel.',[8,9,17]),
('mercer-domain','The source assumes relatively mild conditions for Mercer expansion without enumerating all topological and measure-theoretic hypotheses. Preserve the actual expansion and its stated orthonormality; do not invent a fully specified compact-domain setting.',[8]),
('empirical-fixed-point','Equation (10) defines the estimate by a potentially infinite-dimensional, nonsymmetric operator equation. Positive lambda_n alone is not separately stated as a universal existence/uniqueness certificate; retain the theorem parameter regime and original definition.',[7,10]),
('statistical-dimension-order','The source defines d_n as the largest index with mu_j>=delta_n^2, and describes a nonnegative sequence without explicitly stating a global sorting convention. Do not replace the definition by a count or a trace formula.',[8,17]),
('small-dimension-eigengap','The minimum over 3<=j<=d_n in Theorem 2(b) can have an empty index set when d_n<3. No empty-minimum convention is expressly supplied; preserve the printed condition and flag the endpoint.',[18]),
('lower-spectrum-versus-envelope','Section 4.2.1 distinguishes prescribed mu_j from actual mu_j(P). Regime A fixes equality; Regime B imposes only mu_j(P)<=mu_j for j>=2. Do not silently add the omitted j=1 condition or equality of spectra.',[21,22]),
('measure-overloading','In the lower-bound construction mu denotes Lebesgue measure, but the source explicitly says the norm in LB is shorthand for the stationary measure mu(P). The two measures must remain distinguishable.',[21]),
('regularity-quantifier','Condition (31) uses a universal constant at a sample-dependent critical radius. The passage does not fully spell out whether all admissible n and parameter choices share one constant; preserve the quantifier wording.',[17,18]),
('universal-bound-constants','Theorem 1 declares c0, while the referenced (17) introduces c1,c2 in preceding prose. Likewise LB defines its universal constants before Theorem 2. Do not omit these probability constants merely because they are outside the bold theorem environment.',[10,17]),
('reversed-regime-pair','Theorem 2(b) prints (bar-sigma,bar-R), whereas the regime definitions and validity notation use (bar-R,bar-sigma). Preserve the original order and record the intended parameter roles separately.',[17,18]),
('lower-family-existence-scope','Theorem 2 asserts existence of valid hard families; it does not give a lower bound for every valid family or every arbitrary RKHS with the same eigenvalue envelope. The main-text full specification fixes a reward and RKHS within each constructed family.',[16,17,21,22]),
('sample-size-log-domain','Theorem 2(b) contains log n in a denominator and requests a sufficiently large sample size. No n=1 limiting convention or extra explicit cutoff is inserted into its original statement.',[18])]
def main():
    d=dict(paper_id=PID,status='extracted',unranked_auxiliary_passages=A,source_issues=[dict(issue_id=k,description=t,evidence=[dict(page=p,location='Original main-text definition or scope') for p in pages]) for k,t,pages in ISSUES],ambient_prerequisites=[
      'Probability laws, stationary measures, homogeneous Markov kernels and conditional expectation on their stated domains; iid applies to transition pairs, not to the two coordinates of one pair.',
      'Real Hilbert spaces, L2(mu), supremum norm, linear operators and identity; the tensor notation in (8) uses the current-state representer first and successor-state representer second.',
      'Positive sample size and numeric radii, discount in (0,1), the source eigenvalue sequences and finite or infinite sums. Critical-radius degeneracies and empty eigengap indices remain documented.',
      'The natural sample probability P_I is the iid product law of the transition-pair experiment for instance I. The infimum in LB ranges over measurable data-to-function estimators, as stated in A7.',
      'Typefaces distinguish script I for an MRP instance, calligraphic I for the identity operator, calligraphic P for the transition kernel, blackboard-bold H for the RKHS, and H(gamma) for the effective horizon.'
    ],statement_local_bindings={
      'T1':'c0 is bound in the theorem; c1,c2 and the full tail event are in (17). Radius R obeys standing (15), data obey (3), and r/gamma are given. Part (a) assumes (13) and uses CI(bR). Part (b) additionally assumes (14), uses the smallest critical solution only in (18), and permits any solution in the resulting bound. Theta-star is the projected RKHS fixed point, not a silently exact value function.',
      'T2':'The two regimes are alternatives with distinct sample-size conditions. Validity invokes (29a)-(29b), with r and true theta-star in the constructed RKHS and kappa=2. Regularity (31) is explicitly required in adjacent prose A9. The LB experiment and norm are clarified in D28; D29/D30 give its full regime-specific families. Delta_n uses prescribed parameters, not a forced equality with the instance spectrum. No finite packing, Walsh basis, KL/Fano bound or appendix statement is added as a statement dependency.'
    },source_claim_references=[
      dict(from_claim_id=PID+'/T1',reference_kind='numbered_conclusion_with_probability',local_ids=['D18'],scope='Bound (17), including its preceding/following original prose and universal tail constants.'),
      dict(from_claim_id=PID+'/T2',reference_kind='named_conclusion_and_full_specification',local_ids=['D25','D28','D29','D30'],scope='LB and the explicit Section 4.2.1 specification of the experiment, stationary norm and regime-specific families; not proof-only constructions.')])
    (ROOT/'ambient-prerequisites.json').write_text(json.dumps(d,indent=2,ensure_ascii=False)+'\n')
    print(f'Saved {len(A)} original scope passages and {len(ISSUES)} source conventions.')
if __name__=='__main__':main()
