"""Rebuild original main-text passages and local dependencies for this paper.

The saved data is manually transcribed; source audit is a separate stage.
"""
import json
from pathlib import Path
from save_inventory import PID, claims

ROOT = Path(__file__).resolve().parents[1]
interfaces, members, edges = [], {}, {}


def add(lid, term, body, pages, heading, deps=None, *, kind='definition',
        symbols=(), phrases=(), context=None, context_pages=None, shape):
    evidence = [dict(page=p, location=heading) for p in pages]
    member = dict(paper_id=PID, local_id=lid, local_label=heading,
        source_heading=heading, source_kind=kind, statement_original=body.strip(),
        relation='exact', depends_on=list(deps or {}), evidence=evidence,
        highlight_symbols=list(symbols), highlight_phrases=list(phrases))
    keyword = dict(paper_id=PID, local_id=lid, source_text=term,
                   label=term[0].upper()+term[1:], kind='term')
    if term not in body:
        assert context and term in context, (lid, term)
        member['naming_context'] = [dict(context_id=lid+'/name', text=context,
            evidence=[dict(page=p, location=heading+' — naming context') for p in (context_pages or pages)])]
        keyword['context_id'] = lid+'/name'
    interfaces.append(dict(interface_id=PID+'/'+lid, rank_group='all', name=keyword['label'],
        lean_role='hypothesis' if kind in ('condition', 'assumption') else 'definition',
        type_shape=shape, semantic_boundary=shape, members=[member], source_keywords=[keyword],
        central_claim_uses=[], dependencies=[], theorem_explanations={}))
    members[lid] = member
    edges[lid] = deps or {}


add('D1','rough volatility paradigm',r'''
As a prototype model for the log-price of an asset $(S_t)$, we let
\[
\begin{cases}
S_t=S_0+\int_0^t\sigma_s\,dB_s,\\
\sigma_t^2=\sigma_0^2\exp(\eta W_t^H),
\end{cases}\tag{1}
\]
where $(B_t)$ is a Brownian motion and $(W_t^H)$ is an independent fractional Brownian motion with Hurst parameter $H\in(0,1)$. The constants $\sigma_0$ and $\eta$ are positive and considered as nuisance parameters.
''',[1],'Section 1.1 — model (1)',kind='source_passage',context='1.1. The rough volatility paradigm.',symbols=[r'\sigma_t^2=\sigma_0^2\exp(\eta W_t^H)'],shape='Driftless stochastic-integral log-price model with exponential fractional volatility, independent drivers and positive scale. The general model is later restricted to H<3/4; it is not the coarse-volatility model (4).')

add('D2','piecewise constant rough volatility model',r'''
Given parameters $H\in(0,1)$ and $\eta>0$, on a rich enough probability space $(\Omega,\mathcal A,\mathbb P_{H,\eta})$, the price model takes the form
\[
\begin{cases}
S_t=S_0+\int_0^t\sigma_s\,dB_s,\\
\sigma_t^2=\sigma_0^2\exp(X_t),\\
X_t=\eta W^H_{\lfloor t\delta^{-1}\rfloor\delta},
\end{cases}\tag{4}
\]
where $(B_t)$ is a Brownian motion and $(W_t^H)$ is an independent fractional Brownian motion with Hurst parameter $H\in(0,1)$ and $\eta,\sigma_0>0$ are nuisance parameters. With no loss of generality, we further assume $\sigma_0^2=1$.
''',[5],'Section 2.1 — piecewise constant model (4)',kind='source_passage',context='2. The piecewise constant rough volatility model.',symbols=[r'X_t=\eta W^H_{\lfloor t\delta^{-1}\rfloor\delta}'],shape='Volatility is constant on a grid of positive mesh delta; this model supplies the additional delta^(1/2) branch in Theorems 2 and 3. The entire formula is archived separately from continuous model (1).')

add('D3','discrete time points',r'''
We observe a sample path of $(S_t)$ at $n+1$ discrete time points:
\[
S_0,S_{1/n},S_{2/n},\ldots,S_1.
\]
''',[5],'Section 2.1 — observation grid',symbols=[r'S_0,S_{1/n},S_{2/n},\ldots,S_1'],shape='Price observations over fixed horizon [0,1], with n increments and n+1 observations; not direct observations of volatility. The underlying law is specified separately for each experiment.')

add('D4','dyadic scale',r'''
To simplify notation and computations, with no loss of generality, we assume that $n$ and $\delta$ live on a dyadic scale in the following sense: for some integer $N\ge0$, we have
\[
n=2^N\quad\text{and}\quad m=n\delta=2^N\delta\text{ is an integer}.
\]
''',[5],'Section 2.1 — dyadic sample size and block length',symbols=[r'm=n\delta=2^N\delta'],shape='The printed N indexes n, while m is the number of fine price increments per volatility block. Later coarse-signal coefficient indices must be checked against this convention rather than silently redefining N.')

add('D5','statistical experiment',r'''
Writing $\mathcal A^n\subset\mathcal A$ for the $\sigma$-algebra generated by the data $(S_{i/n})_{0\le i\le n}$, we obtain a (sequence of) statistical experiment(s)
\[
\mathcal E^n=(\Omega,\mathcal A^n,(\mathbb P_{H,\eta})_{(H,\eta)\in\mathcal D}),
\]
where the parameter $(H,\eta)$ lies in a compact (with non-empty interior) $\mathcal D\subset(0,1)\times(0,\infty)$.
''',[6],'Section 2.1 — piecewise constant experiment and parameter set',{'D2':'The probability laws in this Section 2 experiment are those of model (4).','D3':'The observable sigma-algebra is generated by the fixed-grid price samples.','D4':'The Section 2 sample and block sizes use the stated dyadic convention.'},symbols=[r'\mathcal E^n',r'\mathcal A^n',r'\mathcal D\subset(0,1)\times(0,\infty)'],shape='Compact two-parameter experiment with nonempty interior. Superscript n denotes the data restriction. No directly observed latent path, ergodic information or microstructure noise is added.')

add('D6','lower rate of convergence',r'''
The rate $v_n$ is said to be a lower rate of convergence for estimating $H$ over $\mathcal D$ in the experiment $\mathcal E^n$ if there exists $c>0$ such that
\[
\liminf_{n\to\infty}\inf_{\widehat H_n}\sup_{(H,\eta)\in\mathcal D}\mathbb P_{H,\eta}(v_n^{-1}|\widehat H_n-H|\ge c)>0,
\]
where the infimum is taken over all $\mathcal A^n$-measurable random variables $\widehat H_n$ (i.e. all estimators).
''',[6],'Section 2.2 — lower rate in the piecewise constant experiment',{'D5':'The risk ranges over the observable estimators and parameter laws of the original Section 2 experiment.'},symbols=[r'\liminf_{n\to\infty}\inf_{\widehat H_n}'],shape='Uniform minimax probability lower bound with infimum over all data-measurable estimators. The theorem uses parameter-dependent rates v_n(H), and explicitly extends the criterion to eta.')

add('D7','general rough volatility model',r'''
We now consider Model (1), with the same accompanying statistical experiment as in the previous section, but we do not require that the volatility process $(\sigma_t)$ is piecewise constant: we now have
\[
\sigma_t^2=\sigma_0^2\exp(\eta W_t^H),
\]
where $W^H$ is a fractional Brownian motion with Hurst index $H$ and independent from $B$. We will write $\mathbb E_{H,\eta}$ for the expectation under the probability measure $\mathbb P_{H,\eta}$. Without loss of generality, we take $\sigma_0=1$. We assume that $(H,\eta)$ lies in a compact subset $\mathcal D$ of $(0,3/4)\times(0,\infty)$. The upper bound $H<3/4$ is a bit artificial and done mainly for technical purposes. It can be improved to $H<1$ using second-order increments, see Section 4.
''',[8],'Section 3.1 — continuous model and restricted parameter set',{'D1':'Section 3 explicitly returns to model (1), with continuous exponential fractional volatility.','D3':'The same fixed-grid price observations generate the experiment, with the new model law.'},kind='source_passage',context='3. The general rough volatility model.',symbols=[r'\mathcal D',r'(0,3/4)\times(0,\infty)'],shape='Distinct model and parameter domain for Theorems 4 and 11. The experiment has the same observation structure but not the piecewise-constant volatility law; no delta dependence is imported through an edge to D5.')

add('D8','lower rate of convergence',r'''
Recall from Section 2.2 that the rate $v_n$ is said to be a lower rate of convergence over $\mathcal D$ for estimating $H$ if there exists $c>0$ such that
\[
\liminf_{n\to\infty}\inf_{\widehat H_n}\sup_{(H,\eta)\in\mathcal D}\mathbb P_{H,\eta}(v_n^{-1}|\widehat H_n-H|\ge c)>0,
\]
where the infimum is taken over all estimators $\widehat H_n$, and similarly for $\eta$.
''',[9],'Section 3.2 — lower rate in the general experiment',{'D7':'The repeated risk definition uses the Section 3 continuous model and its compact parameter domain.'},symbols=[r'\liminf_{n\to\infty}\inf_{\widehat H_n}'],shape='Same kind of minimax probability criterion instantiated in the general model. Its laws and H<3/4 domain remain separate from the Section 2 version.')


add('D9','signal plus noise model',r'''
Recall that we set $m=n\delta_n$, which is assumed to be an integer. For $0\le i<\delta_n^{-1}$, we have
\[
\sum_{j=1}^m(S_{(im+j)/n}-S_{(im+j-1)/n})^2=\sigma_{i\delta_n}^2\sum_{j=1}^m(B_{(im+j)/n}-B_{(im+j-1)/n})^2,
\]
so that
\[
\widehat X_{i,n}=\log\left(\frac nm\sum_{j=1}^m(S_{(im+j)/n}-S_{(im+j-1)/n})^2\right)=\eta W^H_{i\delta_n}+\varepsilon_{i,n,m},
\]
where the $(\varepsilon_{i,n,m})_i$ are independent, each $\varepsilon_{i,n,m}$ being distributed as
\[
\bar\varepsilon_m=\log\left(m^{-1}\sum_{j=1}^m(\bar\xi_j)^2\right)
\]
for i.i.d. standard Gaussian $(\bar\xi_j)_j$. Therefore the random variable $n\delta_n\exp(\varepsilon_{i,n,m})$ has a chi-square law with $n\delta_n$ degrees of freedom.
''',[7],'Section 2.3 — signal plus noise observations',{'D2':'The block variance is constant under model (4).','D3':'The observations are fine-grid price increments.','D4':'m is the number of increments in a volatility block.'},context='Translation into a signal plus noise model.',symbols=[r'\widehat X_{i,n}',r'\bar\varepsilon_m'],shape='Block log-realized variance and its log-chi-square noise distribution. The variance in the estimator is defined by this distribution; no appendix trigamma formula is needed to define it.')

add('D10','empirical counterparts',r'''
In view of these definitions, we introduce their empirical counterparts. We set
\[
\widetilde d_{j,k,p,n}=\frac1{2^{j/2+p}}\left(\sum_{l=0}^{2^p-1}\widehat X_{2^{N-j}(k+l2^{-p}),n}-2\widehat X_{2^{N-j}(k+1+l2^{-p}),n}+\widehat X_{2^{N-j}(k+2+l2^{-p}),n}\right),
\]
which is $\mathcal A^n$-measurable provided that $p+j\le N$.
''',[7],'Section 2.3 — empirical second-difference coefficients',{'D9':'The coefficients use the observed log-block variables hat X.','D4':'The indices use the dyadic parameter N.','D5':'The measurability assertion uses the original data sigma-algebra A^n.'},symbols=[r'\widetilde d_{j,k,p,n}'],shape='Empirical second differences, normalized by 2^(j/2+p), at the exact printed indices. Latent target coefficients are archived as auxiliary context, not required to evaluate this statistic. Potential coarse-grid indexing inconsistency remains unresolved.')

add('D11','energy levels',r'''
We thus finally estimate the energy levels by
\[
\widehat Q_{j,p,n}=\sum_{k=0}^{2^{j-1}-1}\widehat{d^2}_{j,k,p,n},\quad\text{with }\widehat{d^2}_{j,k,p,n}=(\widetilde d_{j,k,p,n})^2-6\operatorname{Var}(\bar\varepsilon_m)2^{-j-p}.\tag{6}
\]
''',[8],'Section 2.3 — estimated energy levels (6)',{'D10':'The squared coefficients are the empirical second differences.','D9':'The subtracted variance uses the original block-noise law.'},symbols=[r'\widehat Q_{j,p,n}',r'\widehat{d^2}_{j,k,p,n}'],shape='Sum of noise-debiased squared coefficients, not the square of a debiased coefficient. The source hat spans d squared; the bias coefficient is 6, unlike the general model estimator.')

add('D12','family of estimators',r'''
Pick $\nu_0>0$. We obtain a family of estimators of $H$ by setting
\[
\widehat H_n=-\frac12\log\left[\frac{\widehat Q_{J_n^*+1,N-J_n^*-1,n}}{\widehat Q_{J_n^*,N-J_n^*-1,n}}\right]
\]
where the data-driven rule for selecting the energy level is given by
\[
J_n^*=\max\{2\le j\le N-1:\widehat Q_{j,N-j-1,n}\ge\nu_0 2^j n^{-1}\}
\]
with the convention that $J_n^*=2$ when this set is empty.
''',[8],'Section 2.3 — coarse-model estimator and scale selection',{'D11':'Both numerator and denominator are estimated energies from (6).','D4':'The admissible scales use the dyadic sample index N.'},symbols=[r'\widehat H_n',r'J_n^*'],shape='Coarse-model H estimator with positive threshold and explicit empty-set fallback. The source prints log, not log_2; no clamping or log-domain fallback is added. Display term H is preserved as prose here.')

add('D13','max and min',r'''
We set
\[
H_-=\min H,\ H_+=\max H,\ \eta_-=\min\eta,\ \eta_+=\max\eta,
\]
where max and min are taken over $(H,\eta)\in\mathcal D$.
''',[9],'Section 3.3 — parameter extrema',{'D7':'The extrema are over the general-model compact parameter set.'},symbols=[r'H_-',r'\eta_+'],shape='Coordinate extrema of the general parameter set. The bounding rectangle need not equal D.')

add('D14','integer',r'''
Here, we fix an integer $S$ such that $S\ge1/(4H_-)+1/2$ and $S>H_+/(2H_-)-1/2$ so that the result of Proposition 5 is in force.
''',[11],'Section 3.4 — fixed expansion order',{'D13':'The expansion order uses both extrema of H over the parameter set.'},kind='condition',symbols=[r'S\ge1/(4H_-)+1/2',r'S>H_+/(2H_-)-1/2'],shape='Fixed integer truncation order, satisfying one weak and one strict inequality. S is different from the price process S_t. Proposition 5 itself is not an inventoried theorem.')

add('D15','fractional Brownian motion',r'''
Let $b\ge1$ and $s\ge1$. Consider $\mathbf r\in\{1,\ldots,2S\}^s$ such that $\sum_i r_i=b$. If $b=1$, we write
\[
\mathfrak W^{H,\mathbf r}_{j,p,k,l}=2^{j+p}\int_{k2^{-j}+l2^{-j-p}}^{k2^{-j}+(l+1)2^{-j-p}}W_u^H\,du=\int_0^1 W^H_{k2^{-j}+(l+u)2^{-j-p}}\,du
\]
and if $b\ge2$, we write
\[
\begin{aligned}
\mathfrak W^{H,\mathbf r}_{j,p,k,l}&=\prod_{i=1}^s\frac{2^{j+p}}{r_i!}\int_{k2^{-j}+l2^{-j-p}}^{k2^{-j}+(l+1)2^{-j-p}}(W_u^H-W^H_{k2^{-j}+l2^{-j-p}})^{r_i}\,du\\
&=\frac1{\mathbf r!}\int_{[0,1]^s}\prod_{i=1}^s(W^H_{k2^{-j}+(l+u_i)2^{-j-p}}-W^H_{k2^{-j}+l2^{-j-p}})^{r_i}\,du
\end{aligned}
\]
where $\mathbf r!=\prod_{i=1}^s r_i!$. Define also $\mathfrak W^{H,\mathbf r}_{p,l}=\mathfrak W^{H,\mathbf r}_{0,p,0,l}$.
''',[30],'Section 8.1 — fractional Brownian integrals used in κ',{'D1':'The integrands use the fractional Brownian motion of model (1).','D14':'The allowed multi-index entries depend on the fixed expansion order S.'},context=r'Since $\mathfrak W^{H,\mathbf r}_{j,p,k,l}=\mathfrak W^{H,\mathbf r}_{j,p,0,2^pk+l}$, we get by self-similarity of fractional Brownian motion that',symbols=[r'\mathfrak W^{H,\mathbf r}_{j,p,k,l}',r'\mathbf r!'],shape='Original Gaussian integral definitions inside the admitted main-text proof section. For b=1 the integrand is uncentered W; for b>=2 it uses increments and factorials. This definition is needed by kappa, unlike surrounding proof decompositions.')

add('D16','sum over all indices',r'''
In the following, we will also use the notation $\overline\sum$ to indicate a sum over all indices $1\le b_1,b_2\le2S$, $1\le s_1,s_2\le2S$ and multi-indices $\mathbf r_1\in\{1,\ldots,S\}^{s_1}$ and $\mathbf r_2\in\{1,\ldots,S\}^{s_2}$ such that $\sum_j r_{1j}=b_1$ and $\sum_j r_{2j}=b_2$. Additional subscripts to $\overline\sum$ will denote additional constraints on the indices.
''',[31],'Section 8.1 — overlined multi-index summation convention',{'D14':'The finite ranges depend on the chosen expansion order.'},symbols=[r'\overline\sum',r'\mathbf r_1'],shape='Overlined sum with all six index families and the two total-degree constraints. Preserve the printed upper bound S on r entries, which differs from the earlier 2S range.')

add('D17','functions of H',r'''
The functions $H\mapsto\kappa_{p,a}(H)$ are explictly given by
\[
\kappa_{p,a}(H)=2^{-2p}\sum_{|l|<2^p}\overline\sum_{b_1+b_2=2a}\frac{(-1)^{s_1+s_2}}{s_1s_2}(2^p-|l|)\mathbb E\left[(\mathfrak W^{H,\mathbf r_1}_{p,2^p}-\mathfrak W^{H,\mathbf r_1}_{p,0})(\mathfrak W^{H,\mathbf r_2}_{p,2^p+l}-\mathfrak W^{H,\mathbf r_2}_{p,l})\right].\tag{36}
\]
''',[31],'Lemma 23 — defining formula (36) for κ',{'D15':'The expectation is of products of the original fractional Brownian integrals.','D16':'The overlined sum carries the preceding multi-index convention, with total degree 2a.'},context=r'There exist functions of H denoted by $H\mapsto\kappa_{p,a}(H)$ and explicitly given in Equation (36)',context_pages=[9],symbols=[r'\kappa_{p,a}(H)',r'\overline\sum_{b_1+b_2=2a}'],shape='Exact main-text coefficient formula; no external Isserlis expansion is imported. The misspelling explictly is printed in the source. Finite ranges and possible S-dependence are retained.')

add('D18','bias correction',r'''
\[
B^{(S)}_{j,p}(I,\nu)=\sum_{a=2}^S\nu^{2a}2^{-2aIj}\kappa_{p,a}(I).
\]
''',[10],'Section 3.3 — bias function in (10)',{'D17':'The correction sums the original kappa functions at the candidate Hurst index I.','D14':'S is the truncation order chosen for the estimator.'},context='Because of the additional terms appearing in Equation (7), we want to add a bias correction to the energy levels.',symbols=[r'B^{(S)}_{j,p}(I,\nu)'],shape='Bias correction only, with sum starting at a=2, as used in estimated corrected energies. Its original generic domain S>0, nu>0 and I>0 is archived in ambient context; the estimator fixes integer S and later uses 0<I<1.')

add('D19','price increments',r'''
We estimate $d_{j,p,k}$ by
\[
\begin{aligned}
\widetilde d_{j,p,k,n}={}&2^{-p-j/2}\sum_{l=0}^{2^p-1}\log\left((S_{(k+1)2^{-j}+(l+1)2^{-j-p}}-S_{(k+1)2^{-j}+l2^{-j-p}})^2\right)\\
&-2^{-p-j/2}\sum_{l=0}^{2^p-1}\log\left((S_{k2^{-j}+(l+1)2^{-j-p}}-S_{k2^{-j}+l2^{-j-p}})^2\right).
\end{aligned}
\]
''',[11],'Section 3.4 — coefficients from price increments',{'D7':'These are observed price increments under the general volatility model.'},context='We now turn to the task of building a good estimator of $Q_{j,p}$ based on the price increments.',symbols=[r'\widetilde d_{j,p,k,n}'],shape='First difference of averaged log-squared increments; no coarse-volatility approximation or second-difference estimator is substituted. j+p<=N and N=log_2 n are resolved as sampling conventions separately.')

add('D20','estimator of the energy level',r'''
In the same way as in (6), we introduce a bias correction for estimating $(d_{j,k,p})^2$ due to the term $e_{j,k,p,n}^2$ by setting
\[
\widehat{d^2}_{j,p,k,n}=(\widetilde d_{j,p,k,n})^2-2^{-j-p+1}\operatorname{Var}(\log\xi^2),
\]
where $\xi$ is a standard normal random variable. We obtain an estimator of the energy level by setting
\[
\widehat Q_{j,p,n}=\sum_k\widehat{d^2}_{j,p,k,n}.
\]
''',[11],'Section 3.4 — variance-corrected estimated energy',{'D19':'The squared coefficients are those formed from the general-model price increments.'},symbols=[r'\widehat{d^2}_{j,p,k,n}',r'\operatorname{Var}(\log\xi^2)'],shape='Debiased square with coefficient 2^(-j-p+1), not the coarse coefficient 6. The target d and error representation e are archived as auxiliary source context. The source leaves the k range implicit and permutes j,p,k.')

add('D21','first estimator',r'''
A first estimator of $(H,\eta)$ is defined by $(\widehat H_n^{(0)},\widehat\eta_n^{(0)})$, with
\[
\widehat H_n^{(0)}=\min\left(\max\left(-\frac12\log_2\left[\frac{\widehat Q_{J_n^*+1,N-J_n^*-1,n}}{\widehat Q_{J_n^*,N-J_n^*-1,n}}\right],H_-\right),H_+\right)
\]
with $J_n^*=\max\{j:\widehat Q_{j,N-j-1,n}\ge2^jn^{-1}\}$, and then
\[
\widehat\eta_n^{(0)}=\min\left(\max\left(\left(\frac{\widehat Q_{\widehat j_n,N-\widehat j_n,n}2^{2\widehat j_n\widehat H_n^{(0)}}}{\kappa_{N-\widehat j_n,1}(\widehat H_n^{(0)})}\right)^{1/2},\eta_-\right),\eta_+\right)
\]
where $\widehat j_n=\left\lfloor\frac1{2\widehat H_n^{(0)}+1}\log_2n\right\rfloor$. The projection onto $[H_-,H_+]\times[\eta_-,\eta_+]\supseteq\mathcal D$ guarantees the stability of the bias correction procedure.
''',[11,12],'Section 3.4 — initial estimators and frozen scale',{'D20':'The initial estimates use the general estimated energies.','D13':'Both estimates are clamped to the coordinate extrema.','D17':'The scale estimate is normalized by kappa_{p,1}.'},symbols=[r'\widehat H_n^{(0)}',r'\widehat\eta_n^{(0)}',r'\widehat j_n'],shape='Clamped initial estimates with a scale selected from initial H. The source does not restate an empty-set convention or j range for J_n*. The rectangle may strictly contain D; the initialization is not projected onto D itself.')

add('D22','bias',r'''
We then refine this estimator by correcting for a bias induced by the functions $\kappa_{p,a}$ that are necessary to achieve a sufficiently accurate scaling as in (7) of Proposition 5. For $\nu>0$ and $0<I<1$, put
\[
\widehat Q^{(S)}_{j,p,n}(I,\nu)=\widehat Q_{j,p,n}-B^{(S)}_{j,p}(I,\nu),
\]
where $B^{(S)}_{j,p}$ is defined in (10).
''',[12],'Section 3.4 — estimated energy with higher-order correction',{'D20':'The observed energy starts from the variance-corrected estimate.','D18':'The subtracted higher-order bias is the original function B from (10).'},symbols=[r'\widehat Q^{(S)}_{j,p,n}(I,\nu)'],shape='Additional bias correction at candidate Hurst I and scale nu. It does not replace the earlier observation-noise variance correction.')

add('D23','bias correction procedure',r'''
Let
\[
\widehat H_n^c(I,\nu)=\min\left(\max\left(-\frac12\log_2\left[\frac{\widehat Q^{(S)}_{J_n^{*c}(I,\nu)+1,N-J_n^{*c}(I,\nu)-1,n}(I,\nu)}{\widehat Q^{(S)}_{J_n^{*c}(I,\nu),N-J_n^{*c}(I,\nu)-1,n}(I,\nu)}\right],H_-\right),H_+\right),\tag{12}
\]
with
\[
J_n^{*c}(I,\nu)=\max\{j:\widehat Q^{(S)}_{j,N-j-1,n}(I,\nu)\ge2^jn^{-1}\}\tag{13}
\]
and
\[
\widehat\eta_n^c(I,\nu)=\min\left(\max\left(\left(\frac{\widehat Q^{(S)}_{\widehat j_n,N-\widehat j_n,n}(I,\nu)2^{2\widehat j_n I}}{\kappa_{N-\widehat j_n,1}(I)}\right)^{1/2},\eta_-\right),\eta_+\right).\tag{14}
\]
''',[12],'Section 3.4 — corrected estimator functions (12)-(14)',{'D22':'Both corrections use the twice-corrected estimated energy.','D21':'The eta function uses the scale hat j_n fixed by the initialization.','D13':'The outputs are clamped to the bounding rectangle.','D17':'The eta function uses kappa_{p,1} at its candidate argument.'},context=r'The projection onto $[H_-,H_+]\times[\eta_-,\eta_+]\supseteq\mathcal D$ guarantees the stability of the bias correction procedure.',symbols=[r'\widehat H_n^c(I,\nu)',r'\widehat\eta_n^c(I,\nu)',r'J_n^{*c}(I,\nu)'],shape='Corrected H and eta maps with recomputed threshold scale for H but frozen initial scale for eta. No new empty-set, negative-energy, logarithm or square-root fallback is inserted.')

add('D24','estimators',r'''
We use these functions to build iteratively a sequence $(\widehat H_n^{(m)},\widehat\eta_n^{(m)})$ of estimators of $(H,\eta)$. Starting with $(\widehat H_n^{(0)},\widehat\eta_n^{(0)})$, we define for an integer $m\ge1$:
\[
\widehat H_n^{(m)}=\widehat H_n^c(\widehat H_n^{(m-1)},\widehat\eta_n^{(m-1)}),
\]
and
\[
\widehat\eta_n^{(m)}=\widehat\eta_n^c(\widehat H_n^{(m)},\widehat\eta_n^{(m-1)}).
\]
Finally, pick an integer $m_{opt}$ such that $m_{opt}>1/(4H)-2H-1$ holds for any $H_-<H<H_+$. We obtain the following upper bound:
''',[12],'Section 3.4 — sequential estimator iteration',{'D21':'The iteration starts at the original clamped initialization.','D23':'Each step evaluates the corrected estimator maps.','D13':'The stopping-order condition ranges over the original H extrema.'},symbols=[r'\widehat H_n^{(m)}',r'\widehat\eta_n^{(m)}',r'm_{opt}'],shape='Sequential update: eta uses the current H estimate and the previous eta estimate. m_opt is an integer; Theorem 11 states the additional intermediate m condition, which is retained separately in its original body.')

def main():
    for lid,m in members.items():
        assert all(d in members for d in m['depends_on']),lid
        assert any(s in m['statement_original']+' '+m['local_label'] for s in m['highlight_symbols']+m['highlight_phrases']),lid
    data=dict(paper_id=PID,status='extracted_pending_source_audit',interfaces=interfaces,local_dependency_reasons=edges,
        remaining_work='Review every theorem path, finalize, rebuild and independently audit all source contents.')
    (ROOT/'interface-extraction.json').write_text(json.dumps(data,indent=2,ensure_ascii=False)+'\n')
    (ROOT/'source-passages.json').write_text(json.dumps(dict(paper_id=PID,status='extracted_pending_source_audit',members=list(members.values())),indent=2,ensure_ascii=False)+'\n')
    print(f'Saved {len(interfaces)} source passages; full source audit remains pending.')

if __name__=='__main__':main()
