"""Transcribe change-acceleration prerequisites from the main text only."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];PID=ROOT.name
interfaces=[];members={};edges={}
def add(lid,term,body,pages,heading,deps=None,*,kind='definition',symbols=(),phrases=(),context=None,note=None,shape):
    m=dict(paper_id=PID,local_id=lid,local_label=heading,source_heading=heading,source_kind=kind,
        statement_original=body.strip(),relation='exact',depends_on=list(deps or {}),
        evidence=[dict(page=p,location=heading) for p in pages],highlight_symbols=list(symbols),highlight_phrases=list(phrases))
    if note:m['variant_note']=note
    terms=term if isinstance(term,list) else [term];keywords=[]
    for t in terms:
        key=dict(paper_id=PID,local_id=lid,source_text=t,label=t[0].upper()+t[1:],kind='term')
        if t not in body:
            assert context and t in context,(lid,t)
            m['naming_context']=[dict(context_id=lid+'/name',text=context,evidence=m['evidence'])];key['context_id']=lid+'/name'
        keywords.append(key)
    interfaces.append(dict(interface_id=PID+'/'+lid,rank_group='all',name=' · '.join(k['label'] for k in keywords),
        lean_role='hypothesis' if kind in ('condition','assumption') else 'definition',type_shape=shape,semantic_boundary=shape,
        members=[m],source_keywords=keywords,central_claim_uses=[],dependencies=[],theorem_explanations={}))
    members[lid]=m;edges[lid]=deps or {}
add('D1','latent stochastic process',r'''
Let $(\Omega,\mathcal F,\mathsf P)$ be a probability space that hosts all random variables we define in this work. Let $\{L_t,t=0,1\ldots\}$ be a latent stochastic process such that $L_t=0$ for every $t<\Theta$ and $L_t=1$ for every $t\ge\Theta$. That is, $\Theta$ denotes the latent time at which there is a change in the state of a system of interest. At each time $t\in\mathbb N\equiv\{1,2,\ldots\}$, we select a treatment, $X_t$, and observe a response, $Y_t$. For each $t\in\mathbb N$, we denote by $\mathcal F_t$ the $\sigma$-algebra generated by the first $t$ responses and treatments, i.e.,
\[
\mathcal F_t\equiv\sigma(X_s,Y_s,\ 1\le s\le t),
\]
and we set $\mathcal F_0\equiv\{\emptyset,\Omega\}$. We denote by $\pi_0$ the probability that the change has occurred before observing any response, and by $\Pi_t$ the conditional probability that the change happens at time $t$ given the current treatment and all past treatments and responses, i.e.,
\[
\pi_0\equiv\mathsf P(L_0=1);\qquad\Pi_t\equiv\mathsf P(L_t=1\mid L_{t-1}=0,\mathcal F_{t-1},X_t),\qquad t\in\mathbb N.
\]
''',[4],'Section 2.1 — latent state, observed filtration and transition probability',kind='source_passage',symbols=[r'\Pi_t',r'\mathcal F_t',r'\Theta'],shape='Single absorbing latent change with the filtration generated only by responses and treatments. The transition probability is conditional on no previous change; the latent state history is not observed.')
add('D2','Treatment assignment model',r'''
Treatment assignment model. Consider $2\le K<\infty$ treatments. For each $t\in\mathbb N$, $X_t$ takes values in $[K]\equiv\{1,\ldots,K\}$, and $X_t=x$ for some $x\in[K]$ if and only if treatment $x$ is assigned at time $t$. For $t\ge2$, we assume that $X_t$ is a deterministic function of the first $t-1$ assigned treatments and observed responses, $X_1,\ldots,X_{t-1}$ and $Y_1,\ldots,Y_{t-1}$ respectively, whereas $X_1$ is deterministic. That is, $X_t$ is a $[K]$-valued, $\mathcal F_{t-1}$-measurable random variable for every $t\in\mathbb N$. We focus on deterministic assignment rules for simplicity, as the extension to randomized rules is straightforward and not necessary for our results.
''',[4],'Section 2.1 — Treatment assignment model',{'D1':'Predictability is defined relative to the observed response-and-treatment filtration.'},kind='source_passage',symbols=[r'\mathcal F_{t-1}'],phrases=['deterministic assignment rules'],shape='Finite-treatment predictable deterministic policies, with a deterministic first treatment. Randomized policies are discussed but are not substituted into the admissible class.')
add('D3','Response model',r'''
Response model. Without loss of generality, we assume that all responses take values in a common Polish space, denoted by $\mathbb Y$. For each treatment $x\in[K]$, let $f_x$ and $g_x$ denote densities with respect to some $\sigma$-finite measure, $\mu$, on the Borel $\sigma$-algebra, $\mathcal B(\mathbb Y)$, on $\mathbb Y$. For each $t\in\mathbb N$, we assume that the current response, $Y_t$, is conditionally independent of the past given the current state of the system, $L_t$, and the current treatment, $X_t$, with density $f_{X_t}$ before the change and $g_{X_t}$ after the change. Formally, for each $t\in\mathbb N$ and $B\in\mathcal B(\mathbb Y)$ we have
\[
\mathsf P(Y_t\in B\mid X_t=x,L_t=i,\mathcal F_{t-1},\{L_s\}_{0\le s\le t-1})=\begin{cases}\int_B f_x\,d\mu,&i=0\\\int_B g_x\,d\mu,&i=1.\end{cases}
\]
''',[4],'Section 2.1 — Response model',{'D1':'The conditional response law uses the latent state and observed history.','D2':'The pre-change and post-change densities are indexed by the selected treatment.'},kind='source_passage',symbols=[r'f_{X_t}',r'g_{X_t}'],shape='Conditionally independent responses in a common Polish space with treatment-specific densities before and after the latent change. No independent unconditional response sequence or Gaussian family is imposed.')
add('D4','Change-point model',r'''
Change-point model. For each $t\in\mathbb N$, we assume that the conditional probability of the change happening at time $t$ given the past observations and the event $\{L_{t-1}=0\}$ is a function of only the first $t$ assigned treatments, i.e., there exists a function $\pi_t:[K]^t\to[0,1)$ such that
\[
\Pi_t=\pi_t(X_1,\ldots,X_t).
\]
Thus, the change-point model is determined by the prior probability $\pi_0\in[0,1)$ and the sequence of functions $\{\pi_t,t\in\mathbb N\}$. To emphasize that the distribution of the change-point, $\Theta$, depends on the treatment assignment rule, $\mathcal X\equiv\{X_t,t\in\mathbb N\}$, we denote it by $\Theta_{\mathcal X}$.
''',[5],'Section 2.1 — Change-point model',{'D1':'The functions pi_t specify the conditional change hazard defined in the latent-state setup.','D2':'The hazard depends on the entire assigned treatment history under a predictable policy.'},kind='source_passage',symbols=[r'\pi_t',r'\Theta_{\mathcal X}'],shape='History-dependent treatment-controlled hazards strictly below one, with a prior probability of an initial change. The policy is a subscript on Theta; no memory restriction is built into this general model.')
add('D5','Markovian',r'''
We refer to a change-point model as Markovian if, for each $t\in\mathbb N$, $\Pi_t$ depends on the previous treatments, $X_1,\ldots,X_{t-1}$, only via a sufficient statistic of fixed dimension $\kappa\ge0$, i.e., if there exist $\kappa$-dimensional random vectors, $\{\mathbb S_t\}$, such that
\[
\Pi_t=\Psi(X_t,\mathbb S_{t-1}),\qquad\mathbb S_t=\Phi(X_t,\mathbb S_{t-1})\text{ for }t\in\mathbb N,\qquad\mathbb S_0=\zeta_0\in\mathbb R^\kappa,\tag{1}
\]
for some link function $\Psi:[K]\times\mathbb R^\kappa\to[0,1)$ and transition function $\Phi:[K]\times\mathbb R^\kappa\to\mathbb R^\kappa$. Note that $\Psi$ links $\Pi_t$ to the current treatment $X_t$ and the sufficient statistic $\mathbb S_{t-1}$, while $\Phi$ updates the sufficient statistic, given $X_t$, from $\mathbb S_{t-1}$ to $\mathbb S_t$.
''',[5],'Section 2.1 — Markovian change-point model (1)',{'D4':'The finite-dimensional sufficient state specializes the general treatment-history hazard.'},symbols=[r'\mathbb S_t',r'\Psi',r'\Phi'],shape='Fixed-dimensional recursively updated sufficient treatment state. Blackboard-bold S is distinct from plain S used later for stage endpoints. Markovian here does not require finite treatment memory.')
add('D6','memoryless',r'''
We refer to a change-point model as memoryless if, for each $t\in\mathbb N$, $\Pi_t$ depends only on the current treatment, $X_t$, i.e., if there is a link function $\Psi:[K]\to[0,1)$ such that
\[
\Pi_t=\Psi(X_t).
\]
''',[5],'Section 2.1 — memoryless model',{'D4':'The memoryless specialization removes all past-treatment dependence from the general hazard.'},symbols=[r'\Pi_t=\Psi(X_t)'],shape='Current-treatment-only change hazard, equivalent to a zero-dimensional sufficient state in the special case of Theorem 3.1.')
add('D7','admissible procedure',r'''Specifically, an admissible procedure is a pair $(\mathcal X,T)$, where $\mathcal X\equiv\{X_t,t\in\mathbb N\}$ is the sequence of assigned treatments and $T$ is an $\{\mathcal F_t\}$-stopping time at which we stop and declare that the change has occurred, i.e., $\{T=t\}\in\mathcal F_t$ for every $t\ge0$, where the $\sigma$-algebra $\mathcal F_t$ is defined in the previous subsection. We denote by $\mathcal C$ the class of all such procedures''',[5],'Section 2.2 — admissible procedures',{'D2':'The treatment sequence belongs to the deterministic predictable assignment model.','D1':'Stopping is measured with respect to the observed filtration.'},symbols=[r'\mathcal C',r'(\mathcal X,T)'],shape='Unconstrained class of assignment/stopping pairs. A false-alarm tolerance is not part of this class; it is imposed separately in C_alpha.')
add('D8','probability of false alarm',r'''
and by $\mathcal C_\alpha$ the subclass of procedures whose probability of false alarm does not exceed $\alpha$, i.e.,
\[
\mathcal C_\alpha\equiv\{(\mathcal X,T)\in\mathcal C:\mathsf P(T<\Theta_{\mathcal X})\le\alpha\},
\]
where $\alpha\in(0,1)$ is a user-specified tolerance level.
''',[5],'Section 2.2 — false-alarm-constrained class',{'D7':'The constrained class is a subclass of admissible policy/stopping pairs.','D4':'The false-alarm event compares stopping with the change time induced by the same policy.'},symbols=[r'\mathcal C_\alpha'],shape='Probability-of-ever-false-alarm constraint, not an average-run-length constraint. The change time varies with the assignment policy.')
add('D9','posterior odds',r'''
Given an assignment rule $\mathcal X$, we denote by $\Gamma_t$ the posterior odds that the change has already occurred at time $t\ge0$, i.e.,
\[
\Gamma_t\equiv\frac{\mathsf P(L_t=1\mid\mathcal F_t)}{\mathsf P(L_t=0\mid\mathcal F_t)},\tag{5}
\]
with the understanding that $\Gamma_0\equiv\pi_0/(1-\pi_0)$. Although $\{\Gamma_t\}$ depends on $\mathcal X$, we do not emphasize this dependence to lighten the notation.
''',[6],'Section 2.3 — posterior odds (5)',{'D1':'The posterior conditions the latent-state event on the observed filtration.','D4':'Its initial value uses the prior change probability and its law depends on the assigned treatment history.'},symbols=[r'\Gamma_t',r'\Gamma_0'],shape='Posterior odds of an already-realized latent change. The source does not specify an explicit convention for a zero posterior denominator in this defining passage.')
add('D10','auxiliary unconstrained sequential optimization problem',r'''
We start by defining an auxiliary unconstrained sequential optimization problem, in which the cost of each new observation is $c>0$ and the cost of a false alarm is $1$. To be specific, when the prior belief $\Gamma_0$ and the initialization $\mathbb S_0$ in (1) take values $\gamma\in\mathbb R_+\equiv[0,\infty)$ and $\zeta\in\mathbb R^\kappa$, respectively, we write $\mathsf P_{\gamma,\zeta}$ and $\mathsf E_{\gamma,\zeta}$ instead of $\mathsf P$ and $\mathsf E$. We define the integrated cost of a procedure $(\mathcal X,T)\in\mathcal C$ to be
\[
\widetilde J_c(\gamma,\zeta;\mathcal X,T)\equiv c\mathsf E_{\gamma,\zeta}[T]+\mathsf P_{\gamma,\zeta}(T<\Theta_{\mathcal X}),
\]
and we study the following problem:
\[
\inf_{(\mathcal X,T)\in\mathcal C}\widetilde J_c(\gamma,\zeta;\mathcal X,T).\tag{6}
\]
''',[6],'Section 3.1 — auxiliary optimization (6)',{'D7':'The cost is minimized over the unconstrained admissible class.','D9':'The initial scalar parameter gamma is the prior posterior odds.','D5':'The parameter zeta initializes the Markov sufficient state.','D4':'The terminal penalty is the probability of stopping before the policy-dependent change.'},symbols=[r'\widetilde J_c',r'\mathsf P_{\gamma,\zeta}'],shape='Bayesian total-sample-cost objective plus a unit false-alarm cost. It is not a detection-delay objective and does not require equality at a prescribed false-alarm level.')
add('D11',['state space','action space'],r'''
Fix a procedure $(\mathcal X,T)\in\mathcal C$. For each $t\ge0$, let $\Delta_t=1\{t>T\}$, where $1\{\cdot\}$ is the indicator function; that is, $\Delta_t$ indicates whether the process has terminated at time $t$. Thus, the triplet $(\Gamma_t,\mathbb S_t,\Delta_t)$ of the posterior odds, the sufficient statistic in model (1), and the stopping indicator takes values in the state space $\mathcal S\equiv\mathbb R_+\times\mathbb R^\kappa\times\{0,1\}$. Further, we define the action space $\mathcal U\equiv[K]\times\{0,1\}$, and we set
\[
U_t\equiv(U_t^{(1)},U_t^{(2)})\equiv(X_{t+1},1\{T=t\})\in\mathcal U,\qquad t\ge0.
\]
That is, the first component of $U_t$ identifies with the treatment assignment $X_{t+1}$, while the second indicates whether the process is stopped at time $t$.

The transition dynamics of the states $\{(\Gamma_t,\mathbb S_t,\Delta_t),t\ge0\}$ under actions $\{U_t,t\ge0\}$ are as follows. Fix $t\ge1$. Due to the definitions of the model (1) and the stopping indicator, we have
\[
\mathbb S_t=\Phi(U_{t-1}^{(1)},\mathbb S_{t-1}),\qquad\Delta_t=1\quad\text{if and only if}\quad\Delta_{t-1}=1\text{ or }U_{t-1}^{(2)}=1.\tag{7}
\]
Further, in Appendix B.1, we show that the conditional $\mu$-density of $Y_t$ given $\mathcal F_{t-1}$ is $\phi(y;\Gamma_{t-1},\Pi_t,X_t)$, where $\Pi_t=\Psi(X_t,\mathbb S_{t-1})$ (see model (1)) and the function $\phi$ is defined in Equation (B.1) in Appendix B.1. Then, by Lemma 2.1, for any Borel subset $B\subset\mathbb R_+$,
\[
\mathsf P(\Gamma_t\in B\mid\mathcal F_{t-1})=\int_{\mathbb Y}1\left\{\frac{\Gamma_{t-1}+\Pi_t}{1-\Pi_t}\frac{g_{X_t}(y)}{f_{X_t}(y)}\in B\right\}\phi(y;\Gamma_{t-1},\Pi_t,X_t)\,\mu(dy).\tag{8}
\]
''',[7],'Section 3.1 — controlled state, action and transition kernel (7)–(8)',{'D7':'The state/action representation starts from an admissible policy and stopping time.','D9':'Gamma is the posterior-odds state.','D5':'The sufficient-state transition uses the Markov update Phi and hazard link Psi.','D3':'The displayed transition kernel uses the treatment-specific response likelihood ratio and dominating measure.'},symbols=[r'\mathcal S',r'\mathcal U',r'\Delta_t'],shape='Controlled state and action encoding, with termination flag delayed until t>T. The response predictive density phi is defined only in Appendix B.1 and remains unresolved; its displayed kernel invocation is retained.')
add('D12','one-stage cost function',r'''
Finally, we define the one-stage cost function $\widetilde c:\mathcal S\times\mathcal U\to[0,\infty)$ as follows:
\[
\widetilde c(\Gamma_t,\mathbb S_t,\Delta_t;U_t)=1\{\Delta_t=0\}\left(c1\{U_t^{(2)}=0\}+(1+\Gamma_t)^{-1}1\{U_t^{(2)}=1\}\right).
\]
By Lemma 2.2, the second term inside the parentheses is the $\mathcal F_t$-conditional false alarm rate if the process is stopped at time $t$. Then, by definition, for each $(\gamma,\zeta,\delta)\in\mathcal S$, the integral cost $\widetilde J_c(\gamma,\zeta;\mathcal X,T)$ is given by $J_c(\gamma,\zeta,0;\mathcal X,T)$, where
\[
J_c(\gamma,\zeta,\delta;\mathcal X,T)\equiv\sum_{t=0}^\infty\mathsf E[\widetilde c(\Gamma_t,\mathbb S_t,\Delta_t;U_t)\mid(\Gamma_0,\mathbb S_0,\Delta_0)=(\gamma,\zeta,\delta)].
\]
Thus, to solve (6), it suffices to find $(\mathcal X,T)$, or equivalently actions $\{U_t:t\ge0\}$, that achieves
\[
J_c^*(\gamma,\zeta,\delta)\equiv\inf_{(\mathcal X,T)\in\mathcal C}J_c(\gamma,\zeta,\delta;\mathcal X,T).
\]
''',[7],'Section 3.1 — stage cost and infinite-horizon value',{'D11':'The stage cost is defined on the controlled state/action space and its expected sums use the controlled transitions.','D10':'The infinite-horizon cost represents the auxiliary integrated sample-and-false-alarm objective.'},symbols=[r'\widetilde c',r'J_c^*'],shape='Nonnegative stage cost with zero costs after termination, its infinite expected sum, and the optimal value. Conditional state initialization is preserved as printed, without inventing a version on null conditioning events.')
add('D13','Bellman operator',r'''
We denote by $\mathcal J$ the space of all non-negative measurable functions $J:\mathcal S\to[0,\infty]$ such that $J(\gamma,\zeta,1)=0$ for any $\gamma,\zeta$. For each action $u\in\mathcal U$, we define the operator $\mathcal T_{c,u}:\mathcal J\to\mathcal J$ as follows
\[
\mathcal T_{c,u}(J)(\gamma,\zeta,0)\equiv\widetilde c(\gamma,\zeta,0;u)+\mathsf E[J(\Gamma_1,\mathbb S_1,\Delta_1)\mid(\Gamma_0,\mathbb S_0,\Delta_0)=(\gamma,\zeta,0),U_0=u].
\]
That is, given the current state $(\gamma,\zeta,0)$ and a cost function $J$, $\mathcal T_{c,u}(J)(\gamma,\zeta,0)$ is the sum of the current cost and the expected one-step cost under the action $u$. Note that once the process has stopped, no further cost is incurred, that is, $\mathcal T_{c,u}(J)(\gamma,\zeta,1)=0$ for any $\gamma,\zeta$. Further, we define the Bellman operator, which corresponds to the cost under the optimal decision over $\mathcal U$, as follows: $\mathcal T_c:\mathcal J\to\mathcal J$,
\[
\mathcal T_c(J)\equiv\min_{u\in\mathcal U}\mathcal T_{c,u}(J),\qquad J\in\mathcal J.
\]
''',[7],'Section 3.1 — action-specific and Bellman operators',{'D11':'The one-step conditional expectation and action minimization use the controlled kernel and finite action space.','D12':'The operator adds the one-stage sample-or-false-alarm cost.'},symbols=[r'\mathcal T_{c,u}',r'\mathcal T_c'],shape='Action-specific dynamic-programming operator and finite-action minimum on nonnegative measurable value functions, with an absorbing zero-cost slice.')
add('D14','procedure',r'''
Once $J_c^*$ is solved, a procedure $(\mathcal X_c^*,T_c^*)$ that achieves (6) can be obtained as follows. For $t\ge0$, if the process has not been terminated, the cost of stopping is $1/(1+\Gamma_t)$, while the optimal cost with assigning treatment $k\in[K]$ is $\mathcal T_{c,u}(J_c^*)(\Gamma_t,\mathbb S_t,0)$ with $u=(k,0)$. Thus, we stop the first time that the cost due to stopping does not exceed the optimal cost, and otherwise select the treatment that minimizes the expected future cost [2, 10], i.e.,
\[
T_c^*=\inf\{t\ge0:1/(1+\Gamma_t)\le J_c^*(\Gamma_t,\mathbb S_t,0)\},\qquad X_{t+1,c}^*=\operatorname*{arg\,min}_{k\in[K]}\mathcal T_{c,(k,0)}(J_c^*)(\Gamma_t,\mathbb S_t,0).\tag{9}
\]
''',[8],'Section 3.1 — optimal procedure (9)',{'D12':'The stopping comparison uses the optimal infinite-horizon value J_c^*.','D13':'The next treatment minimizes the action-specific Bellman cost.'},symbols=[r'T_c^*',r'\mathcal X_c^*'],shape='Optimal stopping and treatment selection from the auxiliary value function. The source uses argmin without a tie-selection rule; the threshold-structure conclusion is separately inventoried as Theorem 3.1.')

add('D15','block',r'''
Specifically, for $\ell\in\mathbb N$, we refer to an element of $[K]^\ell$, i.e., an ordered list of $\ell$ treatments, as a block (of length $\ell$).

For an arbitrary block $\Xi\in[K]^\ell$, we denote by $|\Xi|$ its size, i.e., $|\Xi|=\ell$, by $\Xi(i)$ its $i^{th}$ component, and adopt the following cyclic convention:
\[
\Xi(j\ell+i)\equiv\Xi(i)\text{ for each integer }j\text{ and }1\le i\le\ell.
\]
We set $\Xi(i:j)\equiv(\Xi(i),\ldots,\Xi(j))$ for arbitrary integers $i,j$.
''',[9],'Section 4 — treatment blocks and cyclic indexing',{'D2':'A block is an ordered finite list from the treatment alphabet [K].'},symbols=[r'\Xi(j\ell+i)',r'\Xi(i:j)'],shape='Nonempty finite treatment word with periodic extension to integer indices and contiguous slices. The member preserves two original passages; intervening procedural motivation is omitted.')
add('D16','likelihood ratio',r'''where $\Lambda_t\equiv\frac{g_{X_t}(Y_t)}{f_{X_t}(Y_t)}$.''',[6],'Lemma 2.1 — likelihood ratio definition',{'D3':'The likelihood ratio evaluates the post-change density divided by the pre-change density at the assigned treatment response.'},symbols=[r'\Lambda_t'],context='For this purpose, we use the likelihood ratio of the responses to block $\Xi_2$ for testing the hypothesis that the change has occurred.',shape='Single-observation post-change/pre-change density ratio. Its definition is excerpted from a main-text Lemma without adding that Lemma to the theorem inventory. Null denominator conventions are not supplied in the definition.')
members['D16']['naming_context'][0]['evidence']=[dict(page=9,location='Section 4 — likelihood ratio naming context')]
add('D17','random times',r'''
Moreover, we define the following random times
\[
\sigma(t;b)\equiv\inf\{s\ge0:\Gamma_{t+s}\ge b\},\qquad\tau(t;d)\equiv\inf\left\{s\ge1:\prod_{j=1}^s\Lambda_{t+j}\le1/d\right\},\tag{10}
\]
where $\{\Gamma_t\}$ and $\{\Lambda_t\}$ are defined in (5) and Lemma 2.1 respectively. Thus, $\sigma(t;b)$ represents the number of observations after time $t$ required by the posterior odds process to cross some threshold $b$, and $\tau(t;d)$ the number of observations after time $t$ until the likelihood ratio statistics of the observations go under $1/d$.
''',[9],'Section 4 — posterior and likelihood-ratio crossing times (10)',{'D9':'The first crossing time uses the posterior odds.','D16':'The second crossing time uses the product of response likelihood ratios starting after t.'},symbols=[r'\sigma(t;b)',r'\tau(t;d)'],shape='Two elapsed-time hitting rules. Sigma allows zero elapsed observations, whereas tau starts at one; the displayed threshold inequalities are non-strict.')
add('D18','assignment rule',r'''
We set $S_0\equiv0$, and for each $n\in\mathbb N$ we denote by $S_n$ the time of the end of the $n^{th}$ stage. Then, the assignment rule $\widetilde{\mathcal X}\equiv\{\widetilde X_t,t\in\mathbb N\}$ is as follows:
\[
\widetilde X_t\equiv\begin{cases}\Xi_1(t-S_{2m-2}),&\text{if }t\in(S_{2m-2},S_{2m-1}]\text{ for some }m\in\mathbb N\\\Xi_2(t-S_{2m-1}),&\text{if }t\in(S_{2m-1},S_{2m}]\text{ for some }m\in\mathbb N.\end{cases}
\]
The times $\{S_n:n\in\mathbb N\}$ are defined recursively. We stop the acceleration stage of the $m^{th}$ cycle as soon as the posterior odds process exceeds $b_1$, that is,
\[
S_{2m-1}=S_{2m-2}+\sigma(S_{2m-2};b_1),\text{ for }m\ge1,
\]
and stop the detection stage of the $m^{th}$ cycle as soon as either the posterior odds process exceeds $b_2\ge b_1$, or the likelihood ratio of the observations during this stage becomes smaller than or equal to $1/d$, that is,
\[
S_{2m}=S_{2m-1}+\min\{\sigma(S_{2m-1};b_2),\tau(S_{2m-1};d)\},\text{ for }m\ge1.
\]
More compactly, for each stage $n\in\mathbb N$ we have
\[
S_n=S_{n-1}+\begin{cases}\sigma(S_{n-1};b_1),&n\text{ is odd}\\\min\{\sigma(S_{n-1};b_2),\tau(S_{n-1};d)\},&n\text{ is even}.\end{cases}
\]
Finally, we terminate the whole process at the end of the first cycle in which the detection is positive, that is, $\widetilde T\equiv S_{2N}$, where the number of cycles until stopping is
\[
N\equiv\inf\{m\ge1:\sigma(S_{2m-1};b_2)\le\tau(S_{2m-1};d)\}=\inf\{m\ge1:\Gamma_{S_{2m}}\ge b_2\}.
\]
''',[9,10],'Section 4.1 — cyclic assignment, stage endpoints and stopping rule',{'D15':'Each stage repeatedly applies its designated treatment block with cyclic indexing restarted at the stage boundary.','D17':'Stage durations and the final stopping cycle are determined by the two crossing rules.'},symbols=[r'\widetilde{\mathcal X}',r'\widetilde T',r'S_{2N}'],shape='Alternating acceleration and detection blocks with reset likelihood-ratio tests. Detection wins ties. Plain S_n denotes a stage endpoint, not the blackboard-bold Markov state. The full original construction spans two pages.')
add('D19','assignment rule',r'''
That is, the assignment rule $\widetilde{\mathcal X}$ can be modified only from time $1$ to $S_1$ as follows:
\[
\widetilde X_t=\begin{cases}z_0(t)&\text{if }1\le t\le\min\{t_0,S_1\}\\\Xi_1(t-t_0)&\text{if }t_0<t\le S_1,\end{cases}\tag{11}
\]
for some fixed integer $t_0\ge0$ and $z_0\in[K]^{t_0}$.
''',[10,11],'Section 4.2 — initial treatment-sequence modification (11)',{'D18':'The modification changes only the first acceleration stage of the original cyclic procedure.','D15':'After the finite initial treatment word, the first acceleration block is applied with its periodic indexing.'},symbols=[r'z_0(t)',r'\min\{t_0,S_1\}'],shape='Finite deterministic prefix during the first acceleration stage, cut short if that stage ends early. Subsequent stage definitions are inherited unchanged.')
add('D20','Kullback-Leibler divergences',r'''
For each $x\in[K]$, we denote the Kullback-Leibler divergences between the response densities $g_x$ and $f_x$ as:
\[
I_x\equiv\int_{\mathbb Y}\left(\log\frac{g_x}{f_x}\right)g_x\,d\mu,\qquad J_x\equiv\int_{\mathbb Y}\left(\log\frac{f_x}{g_x}\right)f_x\,d\mu.\tag{13}
\]
''',[11],'Section 5.1 — directional information numbers (13)',{'D3':'The divergences use the two treatment-specific response densities and their common dominating measure.'},symbols=[r'I_x',r'J_x'],shape='Both directions of response-density relative entropy. I averages the post/pre log ratio under g; J reverses both the ratio and averaging law.')
add('D21','assumption',r'''
They are positive and finite under the following assumption: for each $x\in[K]$,
\[
0<V_x^I\equiv\int_{\mathbb Y}\left(\log\frac{g_x}{f_x}-I_x\right)^2g_x\,d\mu<\infty,\qquad V_x^J\equiv\int_{\mathbb Y}\left(\log\frac{f_x}{g_x}-J_x\right)^2f_x\,d\mu<\infty.\tag{14}
\]
''',[11],'Section 5.1 — response assumption (14)',{'D20':'The two centered log-likelihood variances are centered by the directional divergences I_x and J_x.'},kind='assumption',symbols=[r'V_x^I',r'V_x^J'],shape='Finite log-likelihood variances in both directions, with a strictly positive lower bound printed only for V_x^I. The opening They refers to the information numbers (13); positivity is not silently duplicated before V_x^J.')
add('D22',['average information numbers','second moments'],r'''
For any block $\Xi\in[K]^\ell$, we define the average information numbers and second moments over the treatments in block $\Xi$ as follows:
\[
I(\Xi)\equiv\frac1\ell\sum_{i=1}^\ell I_{\Xi(i)},\quad J(\Xi)\equiv\frac1\ell\sum_{i=1}^\ell J_{\Xi(i)},\quad V^I(\Xi)\equiv\frac1\ell\sum_{i=1}^\ell V_{\Xi(i)}^I,\quad V^J(\Xi)\equiv\frac1\ell\sum_{i=1}^\ell V_{\Xi(i)}^J.
\]
''',[11],'Section 5.2 — block-averaged information and moments',{'D15':'The averages range over each position of a treatment block, counting repeated treatments.','D20':'The first two averages use the directional information numbers.','D21':'The last two averages use the centered second moments from (14).'},symbols=[r'J(\Xi)',r'V^I(\Xi)',r'V^J(\Xi)'],shape='Arithmetic block-position averages of information numbers and centered log-likelihood second moments. The source calls the latter second moments; they are not uncentered squared log ratios.')
add('D23','stability assumption',r'''
Moreover, we impose a stability assumption on the transition probabilities so that if a block is assigned repeatedly after some time $t$, starting from any of its components, the transition probability eventually stabilizes in an average sense. Specifically, we assume that for each $\Xi\in[K]^\ell$, there exists a non-negative number $d(\Xi)$ such that
\[
\lim_{M\to\infty}\frac1M\sum_{s=1}^M\omega\left(\pi_{t+s}\left(z,\Xi(j:s+j-1)\right)\right)=d(\Xi),\quad\text{with }\omega(x)\equiv|\log(1-x)|,\tag{15}
\]
for every $t\ge0$, $z\in[K]^t$ and $j\in[\ell]$. In fact, we require this convergence to be uniform, in the sense that for any $\epsilon>0$ and block $\Xi\in[K]^\ell$, there exists a positive integer $M(\Xi,\epsilon)$ such that for any $M\ge M(\Xi,\epsilon)$,
\[
\sup_{t\ge0,z\in[K]^t,j\in[\ell]}\left|\frac1M\sum_{s=1}^M\omega\left(\pi_{t+s}\left(z,\Xi(j:s+j-1)\right)\right)-d(\Xi)\right|\le\epsilon.\tag{16}
\]
''',[11],'Section 5.1 — uniform transition stability (15)–(16)',{'D4':'The averaged function is the negative log survival probability of the treatment-history hazard.','D15':'The continuation repeatedly cycles a specified block from an arbitrary starting position.'},kind='assumption',symbols=[r'M(\Xi,\epsilon)',r'd(\Xi)'],shape='Uniform Cesaro convergence of log-survival hazards over every initial history, start time and block phase. M(Xi,epsilon) is an existence threshold, not explicitly the minimal such integer. The unnamed omega transform is also archived independently for Theorem 6.1.')
add('D24','adjusted information number',r'''
Further, we define the adjusted information number of a block $\Xi$, which combines information from both the response and change-point models, as follows:
\[
\mathsf D(\Xi)\equiv I(\Xi)+d(\Xi).\tag{17}
\]
''',[12],'Section 5.2 — adjusted information number (17)',{'D22':'The first term is the block-averaged post-change information number.','D23':'The second term is the stable average of log-survival hazards from (15)–(16).'},symbols=[r'\mathsf D(\Xi)'],shape='Response information plus averaged change-hazard information, with sans-serif D. The scalar switching threshold d is different from d(Xi).')
add('D25','expected time of change',r'''
We denote by $\lambda(\Xi)$ the expected time of change when block $\Xi$ is repeatedly assigned from the beginning. It is given by the following formula:
\[
\lambda(\Xi)\equiv(1-\pi_0)\left(1+\sum_{t=1}^\infty\prod_{s=1}^t(1-\pi_s(\Xi(1:s)))\right).\tag{18}
\]
''',[12],'Section 5.2 — expected time of change from the beginning (18)',{'D4':'The survival sum uses the initial no-change probability and treatment-history transition hazards.','D15':'The deterministic continuation is the repeated treatment block.'},symbols=[r'\lambda(\Xi)'],shape='Expected change time from the initial prior under indefinite block repetition, including the factor 1-pi_0. It is distinct from the worst-history conditional bound in (19).')
add('D26','upper bound',r'''
Further, we denote by $\widetilde\lambda(\Xi)$ an upper bound on the expected time of change if block $\Xi$ is repeatedly assigned after some initial period. Specifically, for each integer $m\ge0$ and a sequence of treatments $z\in[K]^m$ of length $m$, define
\[
\widetilde\lambda(\Xi;m,z)\equiv1+\sum_{t=1}^\infty\prod_{s=1}^t(1-\pi_{m+s}(z,\Xi(1:s))),
\]
which is the expected duration between the time $m$ and the change-point if the initial $m$ treatments are given by $z$ and the block $\Xi$ is assigned afterwards. Then we define
\[
\widetilde\lambda(\Xi)\equiv\sup_{m\ge0,z\in[K]^m}\widetilde\lambda(\Xi;m,z),\tag{19}
\]
which is the worst case over all possible initial periods.
''',[12],'Section 5.2 — worst-initial-history change-time bound (19)',{'D4':'Each survival product evaluates hazards after an arbitrary deterministic initial treatment history.','D15':'The subsequent assignment repeatedly cycles the specified block.'},symbols=[r'\widetilde\lambda(\Xi)'],shape='Supremum of conditional residual-change-time survival sums over arbitrary initial periods. Unlike lambda(Xi), it has no factor 1-pi_0. The explanatory sentence does not explicitly say conditioned on no previous change; the formula and its scope are retained.')
add('D27','maximal transition probability',r'''
Finally, we denote by $\zeta(\Xi)$ a lower bound on the maximal transition probability within two blocks of $\Xi$, uniformly over the time $t\ge0$, previous assignments $z\in[K]^t$, and the starting position $j\in[|\Xi|]$, i.e.,
\[
\zeta(\Xi)\equiv\inf_{t\ge0,\ z\in[K]^t,\ 1\le j\le|\Xi|}\left[\max_{1\le s\le2|\Xi|}\pi_{t+s}(z,\Xi(j:j+s-1))\right].\tag{20}
\]
''',[12],'Section 5.2 — two-block maximal transition probability (20)',{'D4':'The maximum and infimum range over the treatment-history transition hazards.','D15':'The continuation is two block lengths with an arbitrary cyclic starting phase.'},symbols=[r'\zeta(\Xi)'],shape='Worst-history lower bound on a two-block maximum hazard. It is not a minimum of every hazard or a single-block average; the infimum may be zero unless further conditions establish otherwise.')
add('D28','Asymptotic framework',r'''
Thus, in this section, we parametrize the functions $\{\pi_t\}$ by $\alpha$ and allow them to vanish as $\alpha\to0$. When we want to emphasize this parametrization, we write $\pi_t(\cdot;\alpha)$ instead of $\pi_t(\cdot)$. As a result, all quantities related to the change-point model, such as $\lambda(\Xi)$ and $\widetilde\lambda(\Xi)$ in (18) and (19), $d(\Xi)$ and $M(\Xi,\epsilon)$ in (15) and (16), $\mathsf D(\Xi)$ in (17), $\zeta(\Xi)$ in (20), as well as the blocks $\Xi_1,\Xi_2$ of the proposed procedure and their lengths, $\ell_1,\ell_2$, are allowed to vary with $\alpha$. For simplicity, we assume that the densities $\{f_x,g_x:x\in[K]\}$ do not depend on $\alpha$, although such an extension is straightforward.

For quantities $x$ and $y$ that are parameterized by $\alpha$, we write $x=o(y)$ if $\lim(x/y)=0$, $x=O(y)$ if $\limsup(x/y)<\infty$, $x\ge y(1+o(1))$ if $\liminf(x/y)\ge1$, $x\le y(1+o(1))$ if $\limsup(x/y)\le1$, and $x\sim y$ if $\lim(x/y)=1$, where all limits are taken as $\alpha\to0$.
''',[16],'Section 6.1 — Asymptotic framework',{'D4':'The underlying family varies the change-hazard functions with the false-alarm tolerance.','D3':'The response densities remain fixed across this asymptotic family.'},kind='source_passage',symbols=[r'\pi_t(\cdot;\alpha)',r'\alpha\to0'],context='6.1. Asymptotic framework.',shape='Vanishing false-alarm-tolerance family with potentially vanishing change hazards and fixed response densities. Listed procedure-related quantities are examples of permitted dependence, not extra procedure assumptions for every theorem in Section 6.')
add('D29','transition probabilities',r'''
It holds for any block if the transition probabilities are bounded away from $1$, i.e., there exists a constant $c\in(0,1)$ such that
\[
\sup_{t\ge0,z\in[K]^t}\pi_t(z;\alpha)\le1-c,\text{ for any small enough }\alpha.\tag{27}
\]
''',[17],'Section 6.2 — hazards bounded away from one (27)',{'D4':'The condition applies to every treatment-history transition probability.','D28':'The fixed constant bounds the entire family for all sufficiently small tolerance levels.'},kind='condition',symbols=[r'\pi_t(z;\alpha)\le1-c'],shape='Uniform upper bound below one, over time, histories and small alpha. The displayed t>=0 also includes pi_0 even though the domain convention for pi_0 differs from pi_t for t>=1.')
add('D30','smallest possible expected time of change',r'''
For this, we recall the definition of $\widetilde\lambda(\Xi)$ in (19) and assume that there exists a block $\Xi$ such that
\[
\alpha\widetilde\lambda(\Xi)=o(\lambda^*+|\log(\alpha)|),\qquad\text{where}\quad\lambda^*\equiv\inf_{\mathcal X}\mathsf E[\Theta_{\mathcal X}].\tag{28}
\]
Note that $\lambda^*$ is the smallest possible expected time of change.
''',[17],'Section 6.3 — optimal change time and residual-time condition (28)',{'D26':'The existence condition uses the worst-initial-history residual change-time bound for one block.','D2':'The infimum ranges over admissible treatment assignment rules.','D4':'The quantity minimized is the expected policy-dependent latent change time.','D28':'The little-o comparison is taken as the false-alarm tolerance tends to zero.'},kind='condition',symbols=[r'\lambda^*',r'\alpha\widetilde\lambda(\Xi)'],shape='Best achievable expected change time, together with existence of a block whose alpha-scaled worst-history residual duration is negligible. This is an existence condition, not an assumption that every policy follows that block.')
add('D31','fastest speed',r'''
Further, we assume that there is a positive quantity, $\mathsf D^*$, which depends on $\alpha$ such that $\mathsf D^*=O(1)$, so that for every assignment rule $\mathcal X$ and $\epsilon>0$ we have
\[
\limsup_{\alpha\to0}\sup_{t\ge0,\mathcal X}\frac1{\mathsf D^*N_{\epsilon,\alpha}}\sum_{s=1}^{N_{\epsilon,\alpha}}\left(I_{X_{t+s}}+\omega(\Pi_{t+s}(\mathcal X))\right)\le1+\epsilon/2,\tag{29}
\]
where $N_{\epsilon,\alpha}\equiv\lfloor(1-\epsilon)|\log(\alpha)|/\mathsf D^*\rfloor$ and $\lfloor z\rfloor$ is the largest integer that does not exceed $z$.
''',[17],'Section 6.3 — uniform information bound (29)',{'D20':'The summands use the post-change response information number of the assigned treatment.','D4':'The summands also use the negative-log-survival transform of the current policy-dependent change hazard.','D28':'Both D-star and the window length vary with the asymptotic tolerance.'},kind='condition',symbols=[r'\mathsf D^*',r'N_{\epsilon,\alpha}'],context='The quantity $\mathsf D^*$ in (29) can be interpreted as the fastest speed, under any assignment rule, at which the logarithm of the posterior odds can grow.',shape='Uniform finite-window adjusted-information upper bound over all start times and assignment rules. D-star is positive and bounded above, not stated bounded below. Omega is locally archived without importing the block-stability assumption (16); the printed epsilon>0 is retained despite the window formula requiring care outside (0,1).')
members['D31']['naming_context'][0]['evidence']=[dict(page=18,location='Section 6.3 — original interpretation of D-star')]

def main():
    (ROOT/'interface-extraction.json').write_text(json.dumps(dict(paper_id=PID,status='source_review_pending',interfaces=interfaces,local_dependency_reasons=edges),indent=2,ensure_ascii=False)+'\n')
    print(f'Saved {len(interfaces)} source passages; extraction and independent review remain.')

if __name__ == "__main__":
    main()
