"""Save source conventions and unresolved meanings without altering the original statements."""
import json
from save_inventory import PID,ROOT
A=[];ISSUES=[]
def passage(n,s,pages,note):A.append(dict(local_id=f'A{n}',statement_original=s,evidence=[dict(page=p,location=f'Auxiliary source passage A{n}') for p in pages],scope_note=note))
def issue(key,text,pages):ISSUES.append(dict(issue_id=key,description=text,evidence=[dict(page=p,location='Source scope or notation') for p in pages]))
passage(1,r'''Let $\{(X_i,Y_i)\}_{i=1}^n$ be i.i.d. observations from model (2.1). Our goal is to estimate the unknown regression function $f_0:[0,1]^d\to\mathbb R$.''',[7],'Standing sample law for statistical theorems, empirical losses and estimator sets; not an assumption on the deterministic approximation constructions.')
passage(2,r'''The following notations will be used throughout this paper. We use $c_1,c_2,\ldots$ to denote the global constants that appear in the statement of any theorem, proposition, corollary, and lemma. We use $C_1,C_2,\ldots$ to denote the local intermediate constants in the proof. Hence all the $c_1,c_2,\cdots$ have unique referred numbers, while all the $C_1,C_2,\ldots$ will have different referred numbers in respective proofs. We use $a\lesssim b$ if there exists some universal constant $C$ such that $a\leq Cb$, we use $a\gtrsim b$ if there exists some universal constant $C>0$ such that $a\geq Cb$, we use $a\asymp b$ if $a\lesssim b$ and $a\gtrsim b$.''',[7],'Global constant labels and source comparison notation. Preserve source lack of an explicit positive sign for C in the first comparison convention.')
passage(3,r'''Within a suitably chosen function class $\mathcal F_n$, the nonparametric least squares method aims to find some $\widehat f_n$ that minimizes the $L_2$ loss
\[
\widehat{\mathcal R}(f)=\frac1n\sum_{i=1}^n\{f(X_i)-Y_i\}^2.
\]
(2.3)''',[7],'Squared loss has no factor 1/2, while Huber loss at infinity does. Exact minimizers coincide; numerical objective tolerances must retain their source definitions.')
passage(4,r'''The accuracy of the estimator $\widehat f_n$ can be evaluated through the mean squared error $\mathbb E_X|\widehat f_n(X)-f_0(X)|^2$, which is the excess risk
\[
\mathcal R(\widehat f_n)-\mathcal R(f_0)=\mathbb E_X[|\widehat f_n(X)-f_0(X)|^2],
\]
(2.4)
where $\mathcal R(f)=\mathbb E_{(X,Y)}[|Y-f(X)|^2]$ is the $L_2$ risk of $f$.''',[7],'Distinguish population squared risk, its excess and the unsquared function L2 norm controlled in the Theorems. Infinite-risk subtraction requires the usual integrability qualification, not a rewritten source equality.')
passage(5,r'''The corresponding nonparametric Huber estimator is defined as
\[
\widehat f_n\in\operatorname{argmin}_{f\in\mathcal F_n(d,L,N,M)}\widehat{\mathcal R}_\tau(f),
\]
(2.9)''',[9],'Exact minimizer in introductory methodology; upper-bound theorems instead control all members of an approximate minimizer set. Do not add attainment to those approximate-set definitions.')
passage(6,r'''Assume that $f_0\in\Theta$ and let $\tau\geq c_1=2\max\{2M,(2v_p)^{1/p}\}$.''',[10],'Opening clause of Proposition 3.1 resolving the constant c1 used in Theorems 3.3 and 3.7. Its subsequent excess-risk inequalities are not imported as theorem premises. The symmetry branch and c1 moment-order interpretation remain a source-scope issue.')
passage(7,r'''There exist universal constants $c_3$–$c_5$ that depend only on $l$, $\sup_{(\beta,t)\in\mathcal P}\max\{\beta,t\}$ and $C$ from Definition 2.2 such that for any $L,N\geq3$,
\[
\sup_{f_0\in\mathcal H(d,l,\mathcal P)}\inf_{f_n\in\mathcal F_n(d,\bar L,\bar N,M)}\|f_n-f_0\|_\infty\leq c_5(NL)^{-2\gamma^*},
\]
where $\bar L=c_3\lceil L\log L\rceil$ and $\bar N=c_4\lceil N\log N\rceil$.''',[13],'Complete Proposition 3.4 body supplies the constants explicitly referenced in (3.15). Retained as context rather than an extra Theorem. The source class quantifies C locally, while the proposition constants depend on C; no global C restriction is silently inserted.')
passage(8,r'''with $\nu^*=1-\frac1{2p-1}$.''',[14],'Theorem 3.5 equation (3.14) defines nu-star reused in Theorem 4.1 rates. It is a local algebraic parameter, not a separate mathematical interface.')
passage(9,r'''for $\nu^\dagger=1-1/p$.''',[15],'Theorem 3.6 defines nu-dagger reused in Theorem 4.2 rates. It differs from nu-star.')
passage(10,r'''Without loss of generality, in this section we assume $\|f_0\|_\infty\leq1$, $X$ follows a uniform distribution on $[0,1]^d$ and $\mathbb E[|\varepsilon|^p\mid X=x]\leq1$ (almost surely). Moreover, we assume that the regression function $f_0$ belongs to a class $\mathcal F$ with intrinsic dimension-adjusted smoothness bounded by $\alpha$ in the following sense.''',[17],'Standing lower-bound statistical conventions for Section 4. They do not impose stochastic assumptions on the deterministic approximation Theorems 4.5 and 4.6, and are not propagated to Section 3 upper bounds.')
passage(11,r'''where $B_\infty(x,r)=\{y:\|y-x\|_\infty\leq r\}$ is the hypercube with the half-width $r$.''',[23],'Ambient vector supremum-norm geometry preceding Theorems 4.5 and 4.6. This is not the function L2 norm D13.')
passage(12,r'''Given the high probability bound (3.12) on the population $L_2$ error, one can further establish a similar bound on the empirical $L_2$ error $\|f-f_0\|_n$, defined as $\|f-f_0\|_n^2=(1/n)\sum_{i=1}^n\{f(X_i)-f_0(X_i)\}^2$, using a uniform concentration property of the empirical $L_2$ risk around the population $L_2$ risk.''',[13],'Remark 3.3 distinguishes the empirical norm from the population norm. Its subsequent concentration proof does not redefine the main theorem error norms.')
passage(13,r'''We adopt a neural network assumption similar to those considered in Farrell et al. (2021), Kohler & Langer (2021), and Shen et al. (2021b), which does not require the network weights to be uniformly bounded.''',[13],'Remark 3.2 confirms that output truncation is not a uniform parameter bound. Later examples with bounded weights are not imported as universal restrictions.')
passage(14,r'''For example, the $d$-variate $(\beta,1)$-smooth function class $\mathcal C(d,\beta)$, formally defined as
\[
\mathcal C(d,\beta)=\{f:[0,1]^d\to\mathbb R:f\text{ is }(\beta,1)\text{ smooth}\},
\]
(4.1)
is a function class with intrinsic dimension-adjusted smoothness upper bounded by $\beta/d$.''',[17],'Illustrative class after Definition 4.1, not an added restriction on arbitrary F0 in Theorems 4.1–4.3. The example uses unit-cube domain, whereas Definition 2.1 states derivatives on R^d; extension conventions are not expanded.')
issue('registered-source','Registered source is the 79-page arXiv:2203.10418v2 stamped 30 Dec 2022, not assumed identical to the published 2024 article. Main text ends before References on PDF page 27.',[1,27])
issue('positive-integer-notation','Glyph-position reinspection confirmed superscript plus in the positive-integer notation on pages 8 and 23. The prior inventory transcription used a subscript; the corrected inventory was independently revalidated and the previous bytes are preserved in evidence.',[8,23])
issue('conditional-moment-orders','Condition 2 permits p>=1, while Theorem 3.3 explicitly assumes p>=2. Theorems 3.5 and 3.6 do not repeat p>=2 in their own statements. Preserve the standing finite-moment setting and the exact stronger restrictions actually printed; do not rewrite their hypotheses.',[7,9,11,14,15])
issue('symmetry-first-moment','Condition 3 asserts symmetry and bounded first absolute moment v1. Theorem 3.7 assumes Conditions 1 and 3, not Condition 2 with p=2. Surrounding prose mentioning a second moment is not an extra printed hypothesis.',[10,15])
issue('symmetry-c1','Theorem 3.7 uses c1 from Proposition 3.1, whose formula contains v_p and p. The symmetry condition supplies v1, and the main theorem does not explicitly state the parameter specialization. Preserve that scope issue rather than silently imposing a second moment.',[10,15])
issue('loss-normalization','Huber loss at tau=infinity equals half the ordinary squared loss (2.3). Source prose calls these the same squared loss. Argmin locations coincide, but the source objective tolerances remain on their own scales.',[7,9,11,18])
issue('smoothness-derivatives','Definition 2.1 bounds differences of r-th derivatives, without adding uniform bounds on the function or lower derivatives. Its prose uses partial f in the numerator, while (2.5) uses partial^r f. Preserve both source forms.',[7,8])
issue('composition-C-scope','Definition 2.2 quantifies C>0 within its class formulas. Proposition 3.4 constants depend on C. A common fixed C across the entire class is not explicitly added by this extraction.',[8,13])
issue('component-argmin','The source assumes a selected pair (beta-star,d-star)=argmin beta/t over P. It does not separately require P to be nonempty or closed, prove attainment, or select among ties. Keep this unresolved convention distinct from the ratio itself.',[8])
issue('coordinate-reuse','The coordinate map pi:[t]->[d] in Definition 2.2 is not required to be injective. The recursive l-1 occurrence is an internal definition, not a cyclic dependency or a new condition.',[8])
issue('affine-layer-wording','The source calls L_i(x)=W_i x+b_i a linear transformation, while its displayed formula is affine. Preserve the wording and the exact bias terms.',[9])
issue('network-depth-output','Equation (2.10) has L hidden ReLU stages and L+1 affine maps, with scalar output. Output truncation F_n(d,L,N,M) differs from the untruncated networks asserted in Theorems 4.5 and 4.6 and does not impose bounded weights.',[9,13,24,25])
issue('estimator-sets','S_n,tau(delta) and S_HN_n,tau(delta) are distinct. The first has an objective tolerance delta squared; the latter uses a min condition involving f0,tau OR an n^-100 objective tolerance. Upper bounds are uniform over the first set; lower bounds assert existence of a bad member of the second.',[11,12,18,19])
issue('bare-S-notation','Theorem 3.7 prints S(delta_n,H) without n,tau subscripts. The same section discusses the approximate Huber estimators from Theorem 3.3; that correspondence is recorded explicitly while the original omitted subscripts are retained.',[11,15])
issue('H-argument-order','Theorem 3.7 displays H(l,d,P), whereas Definition 2.2 and the other bounds use H(d,l,P). The original transposition is preserved.',[8,15])
issue('population-minimizer','The source selects f0,tau from argmin over bounded measurable Theta and calls it the global minimizer. Existence, uniqueness and versions of conditional expectations are not separately formalized; asymmetric noise can make f0,tau differ from f0.',[10,11,18])
issue('minimax-experiment','Definition 4.1 defines a risk-rate property using iid observations with standard Gaussian error and uniform design. The definition does not separately spell out noise-design independence; it refers to the standing regression setting. Do not substitute a Holder definition or import an external proof.',[17])
issue('lower-bound-quantifiers','Theorem 4.1 and 4.2 lower bounds use liminf_n inf_architecture sup_data-law P(exists bad approximate estimator)=1. This is not an infimum over all estimators or a claim that every approximate minimizer has large error.',[18,19])
issue('moment-constant-limits','The source does not separately expand zero-moment and tau=infinity limit conventions in formulas involving powers, ratios and logarithms. Preserve original v_p, v2, p and tau restrictions rather than selecting unstated limits.',[11,12,14,15])
issue('conditional-versions','Conditions 2 and 3 state bounds for every x in the cube, while Section 4 says almost surely. Versions of conditional distributions outside the design support are not specified. Preserve the respective source quantifiers.',[9,10,17])
issue('rate-parameters','The lower-bound nu-star and nu-dagger refer to the distinct algebraic parameters defined in Theorems 3.5 and 3.6. The lower-bound source does not redefine them; all logarithmic exponents are preserved.',[14,15,18,19])
issue('region-index-scope','Equation (4.8) lists coordinate inequalities indexed by i without explicitly writing for all i=1,...,d in the set. The source coordinate interpretation is retained without inserting quantifiers into the original passage.',[23])
issue('binary-expansion-index','Theorem 4.5 sums from i=0 but specifies only (theta_1,...,theta_r) as binary. The source does not give theta_0 in that vector. Preserve the index mismatch.',[24])
issue('binary-architecture-reduction','Theorem 4.5 has +2 in the first depth formula, +1 in the second width formula, and a dangling closing parenthesis in its final reduction term. The source exact-fitting branch is preserved without reconciling these expressions.',[24])
issue('fitting-label-index','Theorem 4.6 writes y_i in its hypothesis and y_alpha in the conclusion. Do not silently change the original symbol.',[24,25])
issue('missing-width-word','Theorem 4.6 describes the second network as with depth c24*L, c25*N*log2(1/Delta2), omitting the word width. The omission is retained and its intended architectural role is identified only in the separate explanation.',[25])
issue('fitting-logarithm','Theorem 4.6 permits every Delta2>0 but uses log2(1/Delta2) as a size factor. No positivity restriction or lower bound on the logarithm is added to the original statement.',[24,25])
issue('proof-only-pseudodimension','Pseudo-dimension is discussed after Theorem 3.3 and its definition is deferred to Appendix A.2. No appendix body was read; its proof-oriented role is not an extra dependency of the explicit V_n formula in the theorem.',[12,17])
issue('source-constant-choices','The architecture constants c3,c4 are supplied existentially by Proposition 3.4 and then reused in (3.15). They depend on composition parameters rather than being numerical constants computed by the census.',[13,14])
RESOLUTION={
'shared':dict(local_objects='D1 regression; D2 boundedness; D3 conditional moments; D4 symmetry; D5 smoothness; D6 composition; D7 least component ratio; D8 Huber loss; D9 ReLU network; D10 output truncation; D11 empirical loss; D12 population risk; D13 population L2 norm; D14 measurable comparison class; D15 population minimizer; D16 upper-bound estimator set; D17 minimax smoothness; D18 lower-bound experiment family; D19 lower-bound estimator set; D20 coordinate regions; D21 architecture.',ambient_or_bound='A1–A14 preserve iid sampling, global constants and asymptotic comparison, squared-loss normalization, exact estimator, c1, c3/c4 context, nu-star and nu-dagger, lower-bound standing assumptions, vector geometry and illustrative norms/classes. Standard derivatives, probability, extrema, sample measurability, elementary arithmetic and finite-dimensional norms remain ambient.'),
'3.3':dict(local_objects='Conditions 1 and 2, F_n, empirical Huber risk, S_n,tau and the population L2 norm.',ambient_or_bound='p>=2, omega,D>=1, network sizes and tau are explicit. V_n, delta_b,delta_a,delta_s,delta_n,tau are local formulas. c1 is resolved by A6. The two tail branches retain their own thresholds and exponents.'),
'3.5':dict(local_objects='Condition 1, source moments, H(d,l,P), beta-star,d-star,gamma-star, F_n, S_n,tau and architecture (3.15).',ambient_or_bound='nu-star, tau_n, delta_n,AH and LN scaling are bound in the statement. c3,c4 come from A7; v2 denotes the moment condition at order two. Source p restrictions and moment scaling are not expanded into stronger assumptions.'),
'3.6':dict(local_objects='Condition 1, source moments, H(d,l,P), least component ratio, F_n, S_n,infinity, population norm and (3.15).',ambient_or_bound='nu-dagger and delta_n,LS are local. Objective tolerance is delta_n,LS squared. Huber at infinity differs by a factor from (2.3), without changing the printed tolerance.'),
'3.7':dict(local_objects='Conditions 1 and 3, H(d,l,P) with source argument swap, gamma-star, F_n, population norm, (3.15) and the abbreviated S(delta) correspondence.',ambient_or_bound='delta_n,H and LN are local rates; c1 comes from A6 but its moment-order specialization is not explicit. No finite second moment or Condition 2 is invented.'),
'4.1':dict(local_objects='Definition 4.1 risk-based smoothness, F_n at M=1, U, S_HN, empirical loss, population Huber minimizer and L2 norm.',ambient_or_bound='F0 and alpha are local hypotheses; zero belongs to F0 explicitly. c9,c10,c11,c12 and delta_n,delta_n,* are bound. nu-star comes from A8. The lower-bound event is existential over approximate estimators.'),
'4.2':dict(local_objects='F0 smoothness/zero-member hypothesis, U and S_HN are expressly inherited from Theorem 4.1; the L2 norm and tau=infinity loss follow their definitions.',ambient_or_bound='nu-dagger comes from A9. The constants are those already defined in Theorem 4.1. Original claim records are separate; no proof-only links are added.'),
'4.3':dict(local_objects='F_n at M=1, intrinsic dimension-adjusted smoothness and L2 norm specialized to uniform design.',ambient_or_bound='F0, alpha, L-bar,N-bar and c13 are bound here. No H(d,l,P), Holder-class restriction, Huber loss or approximate estimator is required to state this approximation bound.'),
'4.5':dict(local_objects='Untruncated deep ReLU architecture and the Q_alpha regions with their grid definition.',ambient_or_bound='N,L,d,K,A,y_alpha,epsilon,Delta,s,r and theta_i are source-bound with recorded theta_0 mismatch. Binary expansion and elementary finite sums are ambient. This deterministic statement has no sampling or moment assumption.'),
'4.6':dict(local_objects='Deep ReLU architecture and Q_alpha(Delta1) from (4.8).',ambient_or_bound='N,L,K,Delta1,Delta2,A-tilde,points,labels,u and constants are source-bound. Q is the displayed union; vector sup norm is ambient with A11 context. Theorem 4.5 conclusion is a proof input, not an inherited claim. Retain missing width word and unrestricted Delta2.')}
def main():
    data=dict(paper_id=PID,unranked_auxiliary_passages=A,source_issues=ISSUES,statement_resolution=RESOLUTION,source_claim_references=[dict(from_claim_id=PID+'/T4.2',to_claim_id=PID+'/T4.1',reference_kind='hypothesis_and_definition_inheritance',evidence=[dict(page=19,location='Theorem 4.2 opening sentence'),dict(page=18,location='Theorem 4.1 hypotheses and definitions')],resolution='Import the F0 condition, U, S_HN and named constants, with tau=infinity; do not inherit all prior conclusions or proof dependencies.')],unresolved_source_references=[dict(reference='Definition A.2 of pseudo-dimension',status='appendix_not_read',resolution='Mentioned in main-text discussion following Theorem 3.3; not needed to state its explicit V_n formula. No appendix body is imported.')])
    (ROOT/'ambient-prerequisites.json').write_text(json.dumps(data,indent=2,ensure_ascii=False)+'\n')
    print(f'Saved {len(A)} auxiliary passages and {len(ISSUES)} source issues.')
if __name__=='__main__':main()
