"""Preserve main-text conventions, statement bindings and unresolved source details."""
import json
from save_inventory import ROOT,PID

def main():
    aux=[]
    def add(n,s,pages,note,deps=()):aux.append(dict(local_id='A'+str(n),statement_original=s,evidence=[dict(page=p,location='Original main-text context A'+str(n)) for p in pages],scope_note=note,depends_on=list(deps)))
    add(1,r'''\[
\mathcal X_t=\mathcal M_t+\mathcal E_t,
\]
(1.1)
where $\mathcal X_1,\ldots,\mathcal X_T\in\mathbb R^{d_1\times\cdots\times d_K}$ are the observed tensor time series, $\mathcal M_t$ and $\mathcal E_t$ are the corresponding signal and noise components of $\mathcal X_t$, respectively.''',[2],'Observed series, signal and noise roles; combined with model (1.2), M_t is the loaded factor signal. These are source setup, not an independent noise assumption.',['D1'])
    add(2,r'''where $A_k$ is the deterministic loading matrix of size $d_k\times r_k$ and $r_k\ll d_k$, and the core tensor $\mathcal F_t$ itself is a latent tensor factor process of dimension $r_1\times\ldots\times r_K$.''',[2],'Original deterministic-loading and dimension conventions for the general tensor factor model. Full column rank is stated in Section 2.2.',['D1'])
    add(3,r'''We do not impose any specific structure for the dynamics of the core tensor factor process $\mathcal F_t\in\mathbb R^{r_1\times\cdots\times r_K}$ beyond the independence between the core process and the noise process, and we do not require any additional structure on the correlation among different time series fibers of the noise process $\mathcal E_t$.''',[6],'Standing core/noise process independence. T3.1–T3.3 do not additionally require the fixed-rank/ergodic or mixing assumptions of later corollaries.',['D1','D18'])
    add(4,r'''Define $d=\prod_{k=1}^K d_k$, $d_{-k}=d/d_k$, $r=\prod_{k=1}^K r_k$ and $r_{-k}=r/r_k$.''',[9],'Shared products of dimensions and ranks. These apply to all five theorems; dstar is a sum, separately preserved in A5.')
    add(5,r'''$d^*_{-k}=\sum_{j\ne k}d_jr_j$''',[11],'Dimension of the estimated other-mode matrices, used in both unstarred and starred additional rates. Sharing this dimension symbol does not make the starred rate depend on the unstarred rate formula.',['D26','D29'])
    add(6,r'''with $\Theta_{k,1:h_0}=(\Theta_{k,h},h=1,\ldots,h_0)$. The canonical factor version of (3.2) is $\operatorname{mat}_1(\Phi_{k,1:h_0}^{(cano)})\in\mathbb R^{r_k\times(rr_{-k}h_0)}$ with $\Phi_{k,1:h_0}^{(cano)}=(\Phi_{k,h}^{(cano)},h=1,\ldots,h_0)\in\mathbb R^{r_k\times r_{-k}\times r_k\times r_{-k}\times h_0}$.''',[9],'Lag collection is an extra tensor mode for outer products; its mode-one unfolding concatenates the lagged columns.',['D3','D19','D33'])
    add(7,r'''The noiseless version of (2.7) is
\[
\Theta^*_{k,1:h_0}=(\Theta^*_{k,h},h=1,\ldots,h_0)=\overline{\mathbb E}[\mathrm{TIPUP}_k]\in\mathbb R^{d_k\times(d_kh_0)},
\]
(3.4)
and its canonical factor version is $\Phi_{k,1:h_0}^{*(cano)}=(\Phi_{k,h}^{*(cano)},h=1,\ldots,h_0)\in\mathbb R^{r_k\times(r_kh_0)}$.''',[10],'Horizontal concatenation for the inner-product signal matrices. The source records their conditional-mean representation.',['D12','D17','D20','D34'])
    add(8,r'''For a matrix $A=(a_{ij})\in\mathbb R^{m\times n}$, write the SVD as $A=U\Sigma V^\top$, where $\Sigma=\operatorname{diag}(\sigma_1(A),\sigma_2(A),\ldots,\sigma_{\min\{m,n\}}(A))$, with singular values $\sigma_{\max}(A)=\sigma_1(A)\ge\sigma_2(A)\ge\cdots\ge\sigma_{\min\{m,n\}}(A)\ge0$ in descending order.''',[5],'Source SVD and singular-value order; nonunique singular bases are not assigned a new convention.',['D5','D11'])
    add(9,r'''Write $\sigma_{\min}(A)$ the smallest nontrivial singular value of $A$.''',[5],'The source defines sigma_min as smallest nontrivial, not unconditionally smallest including zeros. The covariance condition in the lower-bound model retains this convention and associated rank ambiguity.',['D32'])
    add(10,r'''For two sequences of real numbers $\{a_n\}$ and $\{b_n\}$, write $a_n=O(b_n)$ (resp. $a_n\asymp b_n$) if there exists a constant $C$ such that $|a_n|\le C|b_n|$ (resp. $1/C\le a_n/b_n\le C$) for all sufficiently large $n$, and write $a_n=o(b_n)$ if $\lim_{n\to\infty}a_n/b_n=0$. Write $a_n\lesssim b_n$ (resp. $a_n\gtrsim b_n$) if there exist a constant $C$ such that $a_n\le Cb_n$ (resp. $a_n\ge Cb_n$). Write $a\wedge b=\min\{a,b\}$ and $a\vee b=\max\{a,b\}$. We use $C,C_1,c,c_1,\ldots$ to denote generic constants, whose actual values may vary from line to line.''',[5],'Deterministic asymptotic/comparison notation as printed; do not reinterpret it as almost-sure order or assume all generic constants coincide.')
    add(11,r'''Let $\operatorname{vec}(\cdot)$ be the vectorization of matrices and tensors.''',[5],'Source vectorization convention; only the mode-three unfolding example gives an explicit indexing formula.')
    add(12,r'''Here the estimators are constructed with given ranks $r_1,\ldots,r_K$, though in theoretical analysis they are allowed to diverge.''',[9],'Remark 2.2: supplied ranks for Algorithms/Theorems 3.1–3.3. No rank-selection method or fixed-rank premise is imported from the corollaries.')
    add(13,r'''The canonical representation of the tensor times series (1.2) is written as
\[
\mathcal X_t=\mathcal F_t^{(cano)}\times_{k=1}^K U_k+\mathcal E_t,
\]
where the diagonal and right singular matrices of $A_k$ are absorbed into the canonical core tensor $\mathcal F_t^{(cano)}=\mathcal F_t\times_{k=1}^K(\Lambda_kV_k^\top)$.''',[6],'Absorption into the core explains the canonical signal coordinates. This reparameterization does not identify raw-factor moment tensors with canonical-factor moments.',['D1','D2','D8'])
    add(14,r'''\[
\overline{\mathbb E}[\|\widehat P_k^{(TIPUP)}-P_k\|_{\mathrm S}]\lesssim R_k^{*(0)}=(\lambda_k^*)^{-2}\sigma T^{-1/2}\sqrt{d_k}\left(\|\Theta^*_{k,0}\|_{\mathrm S}^{1/2}+\sigma\sqrt{d_{-k}}\right)
\]
(3.16)''',[12],'Full cited risk inequality surrounding the rate definition. The rate expression is D27; the risk assertion is not a new premise of T3.2/T3.3. P-hat-TIPUP is the projection from the source TIPUP estimator evaluated at rank rk.',['D5','D8','D17','D20','D22','D27','D36'])
    issues=[]
    def issue(i,pages,note):issues.append(dict(issue_id=i,evidence=[dict(page=p,location='Source scope or notation issue') for p in pages],note=note))
    issue('source-scope',[1,23,24],'Registered arXiv v3 has 58 pages. Main text ends on page 24 before REFERENCES at y650.489; page text clipped at644. Exactly Theorems3.1–3.5. Lemma4.1, propositions and corollaries are not added to the inventory; supplementary bodies starting28 are excluded.')
    issue('radical-scopes',[10,11],'Enlarged PDF formula crops confirm R0 includes sigma*sqrt(dk)*d_-k, Rcal_k2 begins sqrt(rk)*r_-k and ends sigma*sqrt(dk)*r*T^(-1/2), and Rcal_k1 contains sqrt(dk)*r_-k both in its first and third terms. Those factors outside radicals must not be moved underneath them. The first R0 radical does cover dk*d_-k*r_-k.')
    issue('noise-and-conditioning',[6,9,10],'The model prose says the core and noise processes are independent. Assumption1 separately states conditionally independent Gaussian noise tensors and a second-moment bound. Its conditioning names the full factor process over integers, whereas bar-E is defined using F1,...,FT. The displayed assumption does not explicitly state conditional mean zero; no such clause is silently added to the original statement.')
    issue('conditional-and-unconditional-claims',[9,11,13],'T3.1/T3.2 print bar-E for the terminal risk but unqualified probability for the joint event, while rate quantities themselves depend on the factor realization. Preserve this distinction; whether the event probability is intended conditionally is not clarified by rewriting it. No proof from supplementary material is consulted.')
    issue('algorithm-stopping-and-iteration-domain',[8,11,13,14],'Algorithm1 stops at tolerance or maximum J, but T3.1–T3.3 assert bounds for all m>=0. The source does not explicitly define how iterates are extended after stopping for that universal statement. Keep the recurrence and stopping rule intact; do not manufacture a constant continuation. T3.1/T3.2 use floor, not ceiling, for the displayed terminal J.')
    issue('three-three-rate-import',[13,14],'T3.3 explicitly names unstarred R0 even though its displayed assumption/conclusion instead use starred R0; retain the named object. It imports rate definitions from T3.1/T3.2, not both full theorem assumption sets. In particular h0<=T/4 is not repeated in T3.3; applicability may rely on surrounding shared conventions, but the missing clause is not inserted into its original statement.')
    issue('rate-domains',[7,10,11,13],'The rates contain inverse lambda or lambda-star and sqrt signal quantities, requiring positive nonzero strengths for finite real evaluation. The displayed general theorems do not add separate rank/ergodicity/mixing assumptions on the factors. Record the formula-domain requirement without importing stronger sufficient hypotheses from subsequent corollaries.')
    issue('operator-selection',[7,8],'LSVD_m specifies leading singular vectors but no tie-breaking or measurable selection. Algorithm1 prints INIT_k and ITER_k in addition to the operator’s existing k notation. Preserve the formulas and leave selection conventions explicit as ambient requirements for a formal implementation.')
    issue('distinct-procedures',[7,8,13],'iTOPUP uses TOPUP for both steps; iTIPUP uses TIPUP for both; TIPUP-iTOPUP uses TIPUP only for initialization. T3.3 does not supply a theorem for the reverse mixed branch. HOOI appears in comparison and proof motivation, not as the definition of all three procedures.')
    issue('hypothesis-quantifiers',[21,22],'HypothesisI prints any delta>0 and a limsup of testing risk >1/2; T3.4 invokes it for some delta in(0,1/2). Preserve the wording rather than normalize quantifiers or replace limsup by liminf. Its formal test line says polynomial-time, while preceding prose mentions randomized polynomial time. T3.4 explicitly quantifies randomized estimators.')
    issue('lower-model-independence',[22],'The lower-bound class has independent factor component series and positive average lag-one moments. It does not say the factor sequence is independent across time; that would conflict with mean zero and positive lag-one moments. Gaussian iid noise entries are explicit in this class, stronger than general Assumption1.')
    issue('lower-model-and-minimax-notation',[5,22,23],'The paper calls a class of tensor data-generating distributions a probability space and writes sample tuples as its members inside the supremum. Preserve the source notation. Sigma_min is globally smallest nontrivial singular value; whether the covariance restriction additionally means full rank is not made explicit by that convention. Estimator orthonormality in the lower-bound quantifiers is inferred from the loading-space estimation task, not restated in the theorem.')
    issue('proof-only-and-corollary-imports',[11,14,23],'Proposition3.1 supplies definitions Rcal_k2/R_TOPUP and a separate guarantee; T3.1 does not import its maxR0=o(1) condition merely by using those definitions. Lemma4.1 is proof-only. Assumption2 and later conditions specialize corollaries; no such assumptions are added to the five Theorems without a statement-level reference.')
    bindings={
'T3.1':'General tensor factor model with supplied ranks, Assumption1 and h0<=T/4; explicit Pk,Theta,Theta-star,lambda and four maximum rates; iTOPUP m-step iterates. Constants have the printed dependence on K, rho in(0,1), one event covers every k and m. Bar-E is conditional, and J uses floor.',
'T3.2':'General model, Assumption1, h0<=T/4, Pk,Theta-star and lambda-star, the three starred maximum rates and iTIPUP iterates. Initial condition includes the minimum over k of (1-rho)*lambda-star-squared/(8*normTheta-star). One joint event and conditional terminal risk as printed.',
'T3.3':'General model and Assumption1; names unstarred R0,Rideal,Radd from T3.1 and starred R0 from T3.2. Iterates come from mixed TIPUP-iTOPUP. Pk/norm from the same section. Imports definitions, not entire theorem guarantees or all their hypotheses. One joint event, no additional terminal-J conclusion.',
'T3.4':'HypothesisI plus the explicit lower-bound class(3.34)–(3.35); dimension comparability d^(1/K)~dk>=T and fixed ranks, some positive vartheta and the printed signal/noise liminf condition. Arbitrary randomized polynomial-time estimators, a minimum over modes of squared spectral errors, strict probability thresholds. The projection formulas are bound in the theorem.',
'T3.5':'Same lower-bound class(3.35), lambda>0, every dk diverges with T. Infimum over estimators of one mode and supremum over the class, unsquared spectral error, sigma²+sigma*lambda numerator and sqrt(T*r_-k) denominator. No HypothesisI, polynomial-time restriction, comparable dimensions or fixed-rank requirement is inserted.'}
    refs=[]
    def ref(claim,target,kind,note):refs.append(dict(claim_id=PID+'/'+claim,target=target,reference_kind=kind,note=note))
    ref('T3.1','Proposition3.1 — equations(3.8)–(3.9)','definition_reference','Only the auxiliary and TOPUP rate definitions are required; the proposition’s asymptotic small-error premise and bound are separate.')
    ref('T3.3','Theorems3.1 and3.2 — rate definitions','definition_reference','Retain exactly the named rate objects and their same-paper prerequisites; no theorem conclusion or new branch condition is imported.')
    ref('T3.4','Hypothesis I and HPC problem(3.32)','assumption_reference','Computational hardness is a premise, with the graph testing model recursively defined in main text.')
    for n in ['T3.4','T3.5']:ref(n,'Probability space(3.35) and model(3.34)','definition_reference','Preserve the full separate lower-bound class and its immediately preceding mean/covariance/orthonormality conventions.')
    for n in ['T3.1','T3.2','T3.3']:ref(n,'Assumption2 and later corollary specializations','excluded_specialization','These additional factor-process assumptions simplify rates in corollaries; they are not automatic premises of the general theorem.')
    ref('T3.1','Lemma4.1','proof_only','The matrix perturbation bound helps prove a cited estimator bound; its hypotheses are not statement dependencies of the theorem.')
    data=dict(paper_id=PID,unranked_auxiliary_passages=aux,statement_local_bindings=bindings,source_claim_references=refs,source_issues=issues,ambient_prerequisites=['Finite real tensors, mode index sets, dimensions/ranks, matrix transpose/inverse, SVD with the printed singular-value convention and selection issues.','Expectation, conditional expectation, probability, Gaussian laws, temporal versus component independence, operator/Euclidean norms, asymptotic sequences and generic constants.','Mode products, unfolding and tensor outer products are source-defined interfaces. Kronecker product, vectorization, lag concatenation and products/sums of dimensions are retained as local notation.','Polynomial-time tests and estimators, randomized algorithms, uniform hyperedge/clique sampling, minimax infimum/supremum and simultaneous events. No mathlib availability claim.'],validation_limits='Source census only: source ambiguities and formula domains are recorded without silent correction or proof certification. Supplementary proofs and simulation bodies remain outside scope.')
    (ROOT/'ambient-prerequisites.json').write_text(json.dumps(data,indent=2,ensure_ascii=False)+'\n')
if __name__=='__main__':main()
