"""Rebuild original main-text passages and local dependencies for this paper.

The saved data is manually transcribed; source audit is a separate stage.
"""
import json
from pathlib import Path
from save_inventory import PID, claims

ROOT = Path(__file__).resolve().parents[1]
interfaces, members, edges = [], {}, {}


def add(lid, term, body, pages, heading, deps=None, *, kind='definition',
        symbols=(), phrases=(), context=None, context_pages=None, shape):
    evidence = [dict(page=p, location=heading) for p in pages]
    member = dict(paper_id=PID, local_id=lid, local_label=heading,
        source_heading=heading, source_kind=kind, statement_original=body.strip(),
        relation='exact', depends_on=list(deps or {}), evidence=evidence,
        highlight_symbols=list(symbols), highlight_phrases=list(phrases))
    keyword = dict(paper_id=PID, local_id=lid, source_text=term,
                   label=term[0].upper()+term[1:], kind='term')
    if term not in body:
        assert context and term in context, (lid, term)
        member['naming_context'] = [dict(context_id=lid+'/name', text=context,
            evidence=[dict(page=p, location=heading+' — naming context') for p in (context_pages or pages)])]
        keyword['context_id'] = lid+'/name'
    interfaces.append(dict(interface_id=PID+'/'+lid, rank_group='all', name=keyword['label'],
        lean_role='hypothesis' if kind in ('condition', 'assumption') else 'definition',
        type_shape=shape, semantic_boundary=shape, members=[member], source_keywords=[keyword],
        central_claim_uses=[], dependencies=[], theorem_explanations={}))
    members[lid] = member
    edges[lid] = deps or {}


add('D1', 'nonlinear SDR problem', r'''
Consider the following nonlinear SDR problem
\[
Y\mathrel{\perp\!\!\!\perp}X\mid\boldsymbol f^0(X),\tag{5}
\]
where $\boldsymbol f^0(\cdot)$ is a $\mathbb R^d$-valued function $(d\le p)$. That is to say, at least $d$ functions of $p$-dimensional $X$ are needed to fully capture the relationship between $Y$ and $X$. The intrinsic dimension $d$ is assumed known for simplicity. Obviously, $\boldsymbol f^0$ is unidentifiable since we can replace $\boldsymbol f^0(X)$ by any one-to-one function of it without affecting the conditional independence (5).
''', [6], 'Section 3.1 — nonlinear SDR problem (5)', kind='source_passage',
    symbols=[r'\boldsymbol f^0(X)'], shape='Conditional sufficiency model with fixed known intrinsic dimension d <= p. The target is identifiable only through its generated sigma-field; no equality with a particular selected optimum is asserted.')

add('D2', 'central σ-field', r'''
Assume that the family of probability measures $\{P_{X\mid Y}(\cdot\mid y):y\in\Omega\}$ is dominated by a σ-finite measure. Then there exists a unique minimal sufficient σ-field (or central σ-field) $\mathscr G_{Y\mid X}$ such that
\[
Y\mathrel{\perp\!\!\!\perp}X\mid\mathscr G_{Y\mid X}.
\]
Moreover, $\boldsymbol f^0$ in (5) satisfies $E\{\boldsymbol f^0(X)\}=0$, $\operatorname{Var}\{\boldsymbol f^0(X)\}=I_d$ and
\[
\sigma\{\boldsymbol f^0(X)\}=\mathscr G_{Y\mid X}.
\]
''', [6], 'Assumption — dominated conditional distributions and central σ-field',
    {'D1': 'The assumption normalizes the sufficient map in (5) and identifies its sigma-field.'},
    kind='assumption', symbols=[r'\mathscr G_{Y\mid X}', r'\operatorname{Var}\{\boldsymbol f^0(X)\}=I_d'],
    shape='The source unnumbered Assumption combines domination, minimal sufficient sigma-field and normalized generating map. The printed y in Omega is retained rather than changed to Omega_Y.')

add('D3', 'central class', r'''
Following [27], let $\mathfrak M_{\sigma\{\boldsymbol f^0(X)\}}$ be the central class corresponding to the central σ-field $\sigma\{\boldsymbol f^0(X)\}$, which is the set of all square-integrable, $\sigma\{\boldsymbol f^0(X)\}$-measurable functions. Equivalently, $\mathfrak M_{\sigma\{\boldsymbol f^0(X)\}}$ is a subset of $L_2(P_X)$ and it consists of all elements that can be expressed as functions of $\boldsymbol f^0$.
''', [6], 'Section 3.1 — central class',
    {'D2': 'The measurability sigma-field is the original central sigma-field generated by f^0.'},
    symbols=[r'\mathfrak M_{\sigma\{\boldsymbol f^0(X)\}}'],
    shape='All square-integrable functions measurable with respect to the central sigma-field, not only linear combinations of d coordinates, and not implicitly restricted to mean zero. The class can be infinite dimensional.')

add('D4', 'continuous negative definite function', r'''
We can establish a connection between any Lévy measure $\mu$ and a continuous negative definite function (cndf) $\Theta$ using the Lévy–Khintchine formula, as outlined in [4]. Briefly, $\Theta(v)=\int_{\mathbb R^p\setminus\{0\}}\{1-\cos(s^\top v)\}\mu(ds)$. In this case, we assume $\kappa(v_1,v_2)=\Theta(v_1-v_2)$ hereafter
''', [4], 'Section 2.2 — cndf and the kernel κ', symbols=[r'\kappa(v_1,v_2)=\Theta(v_1-v_2)'],
    shape='Difference kernel induced by the displayed Levy integral, used subsequently on the response space. The article does not spell out all Levy-measure or integrability/support hypotheses; these remain external prerequisites. The positive-definite KCMD alternative in Remark 2.1 is not substituted.')

add('D5', 'Generalized martingale difference divergence', r'''
Given a Lévy measure $\mu$, GMDD of $U$ given $V$ is defined as
\[
\operatorname{GMDD}(U\mid V)=\int_{\mathbb R^p}\|g_{U,V}(s)-g_Ug_V(s)\|_2^2\mu(ds),
\]
where $g_{U,V}(s)=E(Ue^{is^\top V})$, $g_U=E(U)$, $g_V(s)=E(e^{is^\top V})$ and $\|\cdot\|_2$ represents $l_2$ norm of complex-valued vector space $\mathbb C^q$.

\[
\operatorname{GMDD}(U\mid V)=-E\{(U-EU)^\top(\widetilde U-E\widetilde U)\kappa(V,\widetilde V)\},
\]
where $(\widetilde U,\widetilde V)$ is an independent copy of $(U,V)$.
''', [4, 5], 'Section 2.2 — GMDD, the two displayed expressions',
    {'D4': 'The expectation expression uses the difference kernel constructed from the same Levy measure.'},
    context='2.2. Generalized martingale difference divergence.', context_pages=[4],
    symbols=[r'\operatorname{GMDD}(U\mid V)', r'g_{U,V}(s)'],
    shape='Two original GMDD expressions, with the intervening kernel construction stored in D4. Copying is joint: the tilde pair is independent of the original pair but its two components need not be independent. Conditions for the equivalence are not expanded from external references.')

add('D6', 'optimal solution', claims[0]['statement_original'], [7],
    'Theorem 3.2 — optimal solution and ordered GMDD values',
    {'D3': 'The optimization size and conclusion refer to the central class.',
     'D4': 'The objective and GMDD matrix use kappa.',
     'D5': 'The matrix and ordering are described using negative GMDD values.'},
    kind='theorem_excerpt', symbols=[r'\boldsymbol f^*', r'\lambda_i^*', r'\bar f_i^*(X)'],
    shape='Complete original theorem passage defining the selected optimizer and its ordered negative GMDD values. This is a source passage used to resolve later theorems, not a second theorem record or an assumption of full recovery of the central class.')

add('D7', 'successive search procedure', r'''
Additionally, the special $\boldsymbol f^*$ diagonalizing GMDD matrix in Theorem 3.2 is directly linked to a successive search procedure: the $k$th step,
\[
\begin{aligned}
\max_{f\in L_2(P_X)}\;&-E\big([f(X)-E\{f(X)\}][f(\widetilde X)-E\{f(\widetilde X)\}]\kappa(Y,\widetilde Y)\big)\\
\text{subject to}\;&\operatorname{Var}\{f(X)\}=1,\operatorname{Cov}\{f(X),f_j^*(X)\}=0,\quad j=1,\ldots,k-1,
\end{aligned}\tag{7}
\]
where $f_1^*,\ldots,f_{k-1}^*$ are the maximizers in the previous $k-1$ steps.
''', [7], 'Section 3.1 — constrained successive search (7)',
    {'D6': 'The special diagonalizing optimum determines the successive directions.',
     'D4': 'The scalar objective uses the response kernel kappa.'},
    symbols=[r'\operatorname{Var}\{f(X)\}=1', r'f_j^*(X)'],
    shape='Successive unit-variance directions orthogonal to previously selected directions. The recursion is internal to this passage; it is distinct from the penalized and empirical recursions.')

add('D8', 'successive direction extraction method', r'''
Let $\boldsymbol\mu=(\mu_1,\ldots,\mu_d)$ with $\mu_j>0$, $1\le j\le d$, be the hyper-parameter vector. First, consider
\[
L_1(\mu_1,f_1)=E\big([f_1(X)-E\{f_1(X)\}][f_1(\widetilde X)-E\{f_1(\widetilde X)\}]\kappa(Y,\widetilde Y)\big)+\mu_1[\operatorname{Var}\{f_1(X)\}-1]^2,
\]
and its corresponding minimizer
\[
f^*_{1,\mu_1}=\operatorname*{argmin}_{f_1\in L_2(P_X)}L_1(\mu_1,f_1).
\]
For $2\le j\le d$, consider
\[
\begin{aligned}
L_j(\mu_j,(\boldsymbol f^*_{[j-1]},f_j))={}&E\big([f_j(X)-E\{f_j(X)\}][f_j(\widetilde X)-E\{f_j(\widetilde X)\}]\kappa(Y,\widetilde Y)\big)\\
&+\mu_j[\operatorname{Var}\{f_j(X)\}-1]^2+\tilde\mu\sum_{i=1}^{j-1}\{\operatorname{Cov}(f^*_{i,\mu_i}(X),f_j(X))\}^2,
\end{aligned}\tag{8}
\]
where $\boldsymbol f^*_{[j-1]}=(f^*_{1,\mu_1},\ldots,f^*_{j-1,\mu_{j-1}})$ and $\tilde\mu>0$ is a predefined constant. Then its corresponding minimizer is
\[
f^*_{j,\mu_j}=\operatorname*{argmin}_{f_j\in L_2(P_X)}L_j(\mu_j,(\boldsymbol f^*_{[j-1]},f_j)).\tag{9}
\]
We refer to the above procedure as the successive direction extraction method.
''', [9, 10], 'Section 3.2 — penalized population objectives and minimizers (8)–(9)',
    {'D1': 'The recursion extracts d directions in the nonlinear SDR setting.',
     'D4': 'The population losses use the same response difference kernel.'},
    symbols=[r'L_1(\mu_1,f_1)', r'L_j(\mu_j,(\boldsymbol f^*_{[j-1]},f_j))', r'f^*_{j,\mu_j}'],
    shape='The original scalar and successive population losses, positive penalties and recursively selected global minimizers. Variance and covariance penalties are squared. Previous directions are penalized population minimizers, not unit-variance f_j^* or sample estimates.')

add('D9', 'strict gap', r'''
(A1) There is a strict gap among $\lambda_i^*$ in Theorem 3.2 for $m=d+1$, that is, $\lambda_i^*<\lambda_j^*\le0$ for $1\le i<j\le m$. Additionally, we assume $\tilde\mu>-\lambda_1^*$, where $\tilde\mu$ is the constant in (8).
''', [10], 'Assumption (A1)',
    {'D6': 'The gap concerns the ordered negative GMDD values of Theorem 3.2 with m=d+1.',
     'D8': 'The extra inequality constrains the cross-direction penalty in (8).'},
    kind='assumption', symbols=[r'\lambda_i^*<\lambda_j^*\le0', r'\tilde\mu>-\lambda_1^*'],
    shape='Distinct first d+1 ordered values and a strictly large cross-direction penalty, not just distinct first d values. The source presupposes the corresponding optimizers exist.')

add('D10', 'matrix Frobenius norm', r'''
\[
L_F(\mu,\boldsymbol f)=E\big([\boldsymbol f(X)-E\{\boldsymbol f(X)\}]^\top[\boldsymbol f(\widetilde X)-E\{\boldsymbol f(\widetilde X)\}]\kappa(Y,\widetilde Y)\big)+\mu\|\operatorname{Var}\{\boldsymbol f(X)\}-I_d\|_F.\tag{10}
\]
''', [10], 'Section 3.2 — objective with Frobenius penalty (10)',
    {'D1': 'The identity matrix has the intrinsic dimension d.', 'D4': 'The objective uses the original difference kernel.'},
    context=r'The variance constraint is equivalent to $\|\operatorname{Var}\{\boldsymbol f(X)\}-I_d\|_F=0$, where $\|\cdot\|_F$ denotes the matrix Frobenius norm.',
    symbols=[r'L_F(\mu,\boldsymbol f)', r'\|\operatorname{Var}\{\boldsymbol f(X)\}-I_d\|_F'],
    shape='Vector objective with an unsquared Frobenius norm penalty and one scalar mu. It is not the sum of the successive squared variance/covariance penalties; no empirical LF estimator is imported from the supplement.')

add('D11', 'candidate function class', r'''
Here we use a candidate function class $\mathcal F_n$ such as feedforward neural networks described in Section 2.3 to approximate $L_2(P_X)$. Additionally, the generally unknown distribution of $Z=(X,Y)$ hinders the calculation of our objective function. Hence, we need to estimate it by observed data. Given the data $\mathscr D_n=\{Z_1,Z_2,\ldots,Z_n\}$, the empirical form of the successive direction extraction method follows as
''', [11], 'Section 3.3 — candidate function class and observed data', kind='source_passage',
    symbols=[r'\mathcal F_n', r'\mathscr D_n'],
    shape='A candidate scalar function class, possibly sample-size dependent, with observed pairs Z_i. Feedforward networks are an example here; they become required only in the Corollary 4.5 clause. The displayed passage does not explicitly state iid sampling.')

add('D12', 'symmetric kernel functions', r'''
\[
\begin{aligned}
h_{\mu,f}(Z_1,Z_2,Z_3,Z_4)={}&\frac1{12}\sum_{(i,j)\in\mathcal I_{4,2}}f(X_i)f(X_j)\kappa(Y_i,Y_j)-\frac1{12}\sum_{(i,j,k)\in\mathcal I_{4,3}}f(X_i)f(X_j)\kappa(Y_j,Y_k)\\
&+\frac1{24}\sum_{(i,j,k,l)\in\mathcal I_{4,4}}f(X_i)f(X_j)\kappa(Y_k,Y_l)\\
&+\mu\Bigg\{\frac1{12}\sum_{(i,j)\in\mathcal I_{4,2}}f(X_i)f(X_i)f(X_j)f(X_j)-\frac1{12}\sum_{(i,j,k)\in\mathcal I_{4,3}}f(X_i)f(X_j)f(X_j)f(X_k)\\
&\hspace{2em}+\frac1{24}\sum_{(i,j,k,l)\in\mathcal I_{4,4}}f(X_i)f(X_j)f(X_k)f(X_l)\Bigg\}\\
&-2\mu\left\{\frac14\sum_{i\in\mathcal I_{4,1}}f(X_i)f(X_i)-\frac1{12}\sum_{(i,j)\in\mathcal I_{4,2}}f(X_i)f(X_j)\right\}+\mu,
\end{aligned}
\]
''', [11], 'Section 3.3 — symmetric kernel for GMDD and variance penalty',
    {'D4': 'The kernel terms use kappa evaluated on observed response pairs.',
     'D11': 'Its arguments Z_i are the observed predictor-response pairs.'},
    context='the two symmetric kernel functions are', symbols=[r'h_{\mu,f}(Z_1,Z_2,Z_3,Z_4)'],
    shape='Literal four-observation kernel including all coefficients, repeated arguments and the additive mu constant. Ordered distinct-index sets I are defined in the ambient source record. No simplified or corrected kernel replaces it.')

add('D13', 'symmetric kernel functions', r'''
\[
\begin{aligned}
h_{\tilde\mu,f_s,f}(Z_1,Z_2,Z_3,Z_4)=\tilde\mu\left\{\right.&\frac1{12}\sum_{(i,j)\in\mathcal I_{4,2}}f(X_i)f_s(X_i)f(X_j)f_s(X_j)\\
&-\frac1{12}\sum_{(i,j,k)\in\mathcal I_{4,3}}f(X_i)f_s(X_i)f(X_j)f_s(X_k)\\
&+\left.\frac1{24}\sum_{(i,j,k,l)\in\mathcal I_{4,4}}f(X_i)f_s(X_j)f(X_k)f_s(X_l)\right\}.
\end{aligned}
\]
''', [11], 'Section 3.3 — symmetric kernel for the covariance penalty',
    {'D11': 'The arguments are observed predictor-response pairs; only predictor coordinates enter this kernel.'},
    context='the two symmetric kernel functions are', symbols=[r'h_{\tilde\mu,f_s,f}(Z_1,Z_2,Z_3,Z_4)'],
    shape='Separate literal covariance-penalty kernel with ordered distinct-index sums. The fixed earlier direction f_s is an argument; it becomes the estimated direction in the empirical recursion. Coefficients are preserved without algebraic repair.')

add('D14', 'empirical form', r'''
\[
\begin{aligned}
L_{1,n}(\mu_1,f_1)&=\binom n4^{-1}\sum_{(\pi_1,\pi_2,\pi_3,\pi_4)\in\mathcal J_{n,4}}h_{\mu_1,f_1}(Z_{\pi_1},Z_{\pi_2},Z_{\pi_3},Z_{\pi_4}),\\
\hat f_{1,\mu_1}&=\operatorname*{argmin}_{f_1\in\mathcal F_n}L_{1,n}(\mu_1,f_1),
\end{aligned}\tag{11}
\]
''', [11], 'Section 3.3 — first empirical objective and minimizer (11)',
    {'D11': 'The empirical minimizers range over the candidate function class and use the observed pairs.',
     'D12': 'Each empirical objective includes the four-observation GMDD/variance kernel.',
     'D8': 'The positive tuning constants and direction count come from the population procedure.'},
    context='the empirical form of the successive direction extraction method follows as',
    symbols=[r'\hat f_{1,\mu_1}'],
    shape='First two displays of (11): the first order-four empirical objective and its global minimizer. Increasing four-tuples are used; there is no previous-direction covariance kernel at this step.')

add('D15', 'excess risk', r'''
We define the excess risk for the $j$th step estimation
\[
R_j(\mu_j,\hat f_{j,\mu_j})=L_j(\mu_j,(\boldsymbol f^*_{[j-1]},\hat f_{j,\mu_j}))-L_j(\mu_j,(\boldsymbol f^*_{[j-1]},f^*_{j,\mu_j}))
\]
and the total excess risk
\[
R(\boldsymbol\mu,\hat{\boldsymbol f})=\sum_{j=1}^dR_j(\mu_j,\hat f_{j,\mu_j}),
\]
where $\boldsymbol\mu=(\mu_1,\ldots,\mu_d)$, $\hat{\boldsymbol f}=\hat{\boldsymbol f}_{[d]}=(\hat f_{1,\mu_1},\ldots,\hat f_{d,\mu_d})$ and $\boldsymbol f^*_{[j-1]}=(f^*_{1,\mu_1},\ldots,f^*_{j-1,\mu_{j-1}})$.
''', [12], 'Section 4 — directionwise and total excess risk',
    {'D8': 'The two losses fix previous penalized population directions and compare to the population minimizer.',
     'D25': 'The fitted direction and vector are the sequential empirical minimizers.'},
    symbols=[r'R_j(\mu_j,\hat f_{j,\mu_j})', r'R(\boldsymbol\mu,\hat{\boldsymbol f})'],
    shape='Population excess risk of each fitted direction evaluated with oracle preceding directions; its sum is total excess risk. This differs from the empirical objective with estimated preceding directions.')

add('D16', 'boundedness', r'''
(A2) There exists an absolute constant $B>1$ such that $\|f^*_{j,\mu_j}\|_\infty\le B$, $\|f\|_\infty\le B$, and $\kappa(y,\tilde y)\le B$ for any $1\le j\le d$, $f\in\mathcal F_n$, and $y,\tilde y\in\mathbb R^q$.
''', [13], 'Assumption (A2)',
    {'D8': 'The bounded population functions are the penalized minimizers.',
     'D11': 'All functions in the candidate class must obey the bound.', 'D4': 'The same bound applies to the response kernel.'},
    kind='assumption', context=r'The boundedness of $\kappa(y,\tilde y)$ can be easily satisfied if we choose certain specific Lévy measures like the second and the third one listed in Table 1 or $Y$ is bounded.', context_pages=[14],
    symbols=[r'\|f^*_{j,\mu_j}\|_\infty\le B', r'\kappa(y,\tilde y)\le B'],
    shape='A single absolute B>1 bounds the population directions, every candidate function and the kernel at every pair of response-space points. Preserve the one-sided printed kernel inequality; bounded Y does not literally impose a global kernel bound on all R^q.')

add('D17', 'Hölder continuous', r'''
(A3) $f^*_{j,\mu_j}$ is β-Hölder continuous for all $1\le j\le d$, that is, $f^*_{j,\mu_j}\in C^\beta([0,1]^p)$.
''', [13], 'Assumption (A3)',
    {'D8': 'The smooth functions are the penalized population directions.',
     'D18': 'The smoothness class is the beta-Holder class defined in the notation section.'},
    kind='assumption', symbols=[r'f^*_{j,\mu_j}\in C^\beta([0,1]^p)'],
    shape='Smoothness of all penalized population directions, required for the Corollary 4.5 consequence inside Theorem 4.6, not an added hypothesis for Theorems 4.2 or 4.4.')

add('D18', 'Hölder continuous', r'''
The function $f:[0,1]^p\to\mathbb R$ is β-Hölder continuous if there exist $\beta\in(0,1]$ and $\zeta>0$ such that
\[
|f(x_1)-f(x_2)|\le\zeta\|x_1-x_2\|_2^\beta\qquad\text{for any }x_1,x_2\in[0,1]^p.
\]
The β-Hölder continuous function class is denoted by $C^\beta([0,1]^p)$.
''', [4], 'Section 2.1 — Hölder class', symbols=[r'C^\beta([0,1]^p)', r'\|x_1-x_2\|_2^\beta'],
    shape='The original scalar Holder definition on the unit cube with beta in (0,1] and an existential finite positive constant zeta. No derivative-based extension to beta>1 or common Holder radius is silently added.')

add('D19', 'covering number', r'''
A finite colloction $f_1,\ldots,f_m:\mathbb R^p\to\mathbb R$ is called a $\epsilon$-covering of $\mathcal F_n$ with the $L_2(Q)$ norm if for any $f\in\mathcal F_n$ there exists $i\in\{1,\ldots,m\}$ such that $\|f-f_i\|_{L_2(Q)}\le\epsilon$. The corresponding $\epsilon$-covering number of $\mathcal F_n$ is defined as
\[
N(\epsilon,\mathcal F_n,\|\cdot\|_{L_2(Q)}):=\inf\{m\in\mathbb N:\exists\text{a }\varepsilon\text{-cover }f_1,\ldots,f_m\text{ of }\mathcal F_n\}.
\]
''', [4], 'Section 2.1 — covering number',
    symbols=[r'N(\epsilon,\mathcal F_n,\|\cdot\|_{L_2(Q)})'],
    shape='Cover centers are functions R^p to R and are not explicitly required to belong to F_n. The closed-radius inequality, infimum over natural cardinalities, printed colloction typo and mixed epsilon/variant-epsilon notation are retained.')

add('D20', 'complexity requirements', r'''
(A4) There exist an absolute constant $C$ and a parameter $V$ depending on $\mathcal F_n$ such that
\[
\log N(\epsilon,\mathcal F_n,\|\cdot\|_{L_2(Q)})\le CV\{1+\log(1/\epsilon)\},
\]
where $Q$ is the probability measure $P_X$ or $P_n$, the empirical probability measure of $X$.
''', [13], 'Assumption (A4)',
    {'D19': 'The logarithm is of the original L2 covering number.',
     'D11': 'The complexity parameter concerns the candidate function class.'},
    kind='assumption', context=r'We will begin by considering a general function $\mathcal F_n$ meeting some complexity requirements and the result of the deep neural network function class is discussed as a corollary.', context_pages=[12],
    symbols=[r'\log N(\epsilon,\mathcal F_n,\|\cdot\|_{L_2(Q)})', r'CV\{1+\log(1/\epsilon)\}'],
    shape='Entropy bound for Q=P_X and the empirical measure P_n. The epsilon range is not specified in the printed assumption; do not replace it by all positive epsilon or by an unprinted restricted range. V may depend on the sample-size-dependent function class.')

add('D21', 'new target function', r'''
\[
\ell_1(\mu_1,f_1,z)=4E\{h_{\mu_1,f_1}(z,Z_2,Z_3,Z_4)\}-3L_1(\mu_1,f_1).
\]
Then, we consider a new target function and its centered version
\[
v_{1,n}(\mu_1,f_1)=\frac1n\sum_{i=1}^n\ell_1(\mu_1,f_1,Z_i),\qquad
\bar v_{1,n}(\mu_1,f_1)=\frac1n\sum_{i=1}^n\ell_1(\mu_1,f_1,Z_i)-L_1(\mu_1,f_1).
\]
''', [15], 'Section 4.2 — first-order projection loss',
    {'D12': 'The first argument of the four-observation kernel is fixed to z and the other three are averaged.',
     'D8': 'The population objective L1 supplies the subtraction term.'},
    symbols=[r'\ell_1(\mu_1,f_1,z)', r'v_{1,n}(\mu_1,f_1)'],
    shape='Two original displayed definitions from Section 4.2: first-order loss ell_1, then its sample average and centered version. The rho variance condition uses ell_1; the v functions are retained to preserve the author-named target containing that loss. The separate Hoeffding decomposition is not substituted for the empirical estimator.')

add('D22', 'distance', r'''
we first need to identify a distance $\rho$ such that
\[
\operatorname{Var}\{\ell_1(\mu_1,f_1,Z)-\ell_1(\mu_1,f^*_{1,\mu_1},Z)\}\le\rho^2(f_1,f^*_{1,\mu_1}).\tag{12}
\]

We thus define a distance on $L_2(P_X)\times L_2(P_X)$ as
\[
\rho^2(f,g)=C_1\min\{\|f-g\|_{L_2(P_X)}^2,\|f+g\|_{L_2(P_X)}^2\},
\]
where $C_1$ is an appropriate constant satisfying (12) (see the proof of Theorem 4.4).
''', [15, 16], 'Section 4.2 — variance bound (12) and distance up to sign',
    {'D21': 'Condition (12) fixes an adequate C1 through the variance of differences of ell_1.',
     'D8': 'Condition (12) compares to the penalized population optimum.'},
    symbols=[r'\rho^2(f,g)', r'\|f+g\|_{L_2(P_X)}^2'],
    shape='Scaled minimum of squared L2 distances to g and -g. It identifies signs and is not a positive-definite metric on unquotiented functions. Exact C1 is delegated to an excluded proof; the main-text variance condition is retained separately.')

add('D23', 'feedforward neural network', r'''
Specifically, the feedforward neural network can be expressed by
\[
f(x)=W_{\mathcal L}\circ\sigma\circW_{\mathcal L-1}\circ\sigma\circ\cdots\circ\sigma\circW_1\circ\sigma\circW_0(x),\qquad x\in\mathbb R^p,
\]
where $W_i(x)=\omega_i x+b_i$ is an affine transformation with the weight matrix $\omega_i\in\mathbb R^{k_{i+1}\times k_i}$ and intercept vector $b_i\in\mathbb R^{k_{i+1}}$, $i=0,1,\ldots,\mathcal L$, and $\sigma(a)=\max\{a,0\}$ is the ReLU activation function applied element-wise. Here $k_0$ and $k_{\mathcal L+1}$ are the input and output dimensions, respectively. And $k_i$, $i=1,2,\ldots,\mathcal L$ is the number of neurons (width) in the $i$th hidden layer.

The depth of a network is defined as the number $\mathcal L$ of hidden layers, and its width refers to the maximum width $\mathcal N=\max\{k_1,k_2,\ldots,k_{\mathcal L}\}$ of hidden layers. The size of a network can be further measured by two more quantities: the total number of neurons $\mathcal U=\sum_{i=1}^{\mathcal L}k_i$, and the total number of parameters $\mathcal S=\sum_{i=0}^{\mathcal L}k_{i+1}\cdot(k_i+1)$.
''', [5, 6], 'Section 2.3 — ReLU feedforward network and architecture sizes',
    symbols=[r'W_i(x)=\omega_i x+b_i', r'\sigma(a)=\max\{a,0\}', r'\mathcal S=\sum_{i=0}^{\mathcal L}k_{i+1}\cdot(k_i+1)'],
    shape='Affine maps composed with elementwise ReLU, including the final affine output; depth counts hidden layers and parameter count includes biases. No particular optimizer or training algorithm is part of the theoretical class.')

add('D24', 'scalar-valued ReLU neural network classes', r'''
For any arbitrary $N\in\mathbb N^+$, consider $\mathcal F_n$ as scalar-valued ReLU neural network classes with width $\mathcal N=3^{p+3}\max\{p\lfloor N^{1/p}\rfloor,N+1\}$ and depth $\mathcal L=\frac{12n^{\frac{p}{2(p+2\beta)}}}{\log n}+14+2p$. Under the assumption (A1), (A2) and (A3), if $n\ge\mathcal S\mathcal L\log(\mathcal S)$,
''', [16], 'Corollary 4.5 — assumptions invoked by Theorem 4.6',
    {'D23': 'The class is specified by the original ReLU architecture, width, depth and parameter count.',
     'D9': 'The corollary explicitly assumes (A1).', 'D16': 'The corollary explicitly assumes (A2).',
     'D17': 'The corollary explicitly assumes (A3).', 'D11': 'This specializes the candidate class to the stated scalar ReLU network class.'},
    kind='condition', symbols=[r'\mathcal N=3^{p+3}', r'n\ge\mathcal S\mathcal L\log(\mathcal S)'],
    shape='Only the original hypotheses of Corollary 4.5, required by the final clause of Theorem 4.6. The corollary is not a separate inventoried theorem. Width parameter N is free, depth is the displayed noninteger expression, and no rounding or bounded-weight restriction is inserted.')


add('D25', 'empirical form', r'''
\[
\begin{aligned}
L_{j,n}(\mu_j,(\hat{\boldsymbol f}_{[j-1]},f_j))&=\binom n4^{-1}\sum_{(\pi_1,\pi_2,\pi_3,\pi_4)\in\mathcal J_{n,4}}\Bigg\{h_{\mu_j,f_j}(Z_{\pi_1},Z_{\pi_2},Z_{\pi_3},Z_{\pi_4})\\
&\hspace{2em}+\sum_{s=1}^{j-1}h_{\tilde\mu,\hat f_{s,\mu_s},f_j}(Z_{\pi_1},Z_{\pi_2},Z_{\pi_3},Z_{\pi_4})\Bigg\},\\
\hat f_{j,\mu_j}&=\operatorname*{argmin}_{f_j\in\mathcal F_n}L_{j,n}(\mu_j,(\hat{\boldsymbol f}_{[j-1]},f_j)),
\end{aligned}\tag{11}
\]
where $\hat{\boldsymbol f}_{[j-1]}=(\hat f_{1,\mu_1},\ldots,\hat f_{j-1,\mu_{j-1}})$ is the collection of previous estimated directions,
''', [11], 'Section 3.3 — later empirical objectives and minimizers (11)',
    {'D14': 'The recursion starts at the first empirical minimizer in (11).',
     'D11': 'The empirical minimizers range over the candidate function class and use the observed pairs.',
     'D12': 'Each empirical objective includes the four-observation GMDD/variance kernel.',
     'D13': 'Later steps add the covariance kernels evaluated at the previous estimated directions.',
     'D8': 'The positive tuning constants and direction count come from the population procedure.'},
    context='the empirical form of the successive direction extraction method follows as',
    symbols=[r'\hat f_{j,\mu_j}', r'L_{j,n}(\mu_j,(\hat{\boldsymbol f}_{[j-1]},f_j))'],
    shape='Order-four U-statistic objectives and global empirical minimizers. J contains increasing four-tuples. All preceding sample directions enter each later step; this is not optimization with oracle preceding directions or a trained network from a specified optimizer.')

# Source-inspected rendering amendment; see the explicit saved review plan.
members['D23']['statement_original'] = 'Specifically, the feedforward neural network can be expressed by\n\\[\nf(x)=W_{\\mathcal L}\\circ\\sigma\\circ W_{\\mathcal L-1}\\circ\\sigma\\circ\\cdots\\circ\\sigma\\circ W_1\\circ\\sigma\\circ W_0(x),\\qquad x\\in\\mathbb R^p,\n\\]\nwhere $W_i(x)=\\omega_i x+b_i$ is an affine transformation with the weight matrix $\\omega_i\\in\\mathbb R^{k_{i+1}\\times k_i}$ and intercept vector $b_i\\in\\mathbb R^{k_{i+1}}$, $i=0,1,\\ldots,\\mathcal L$, and $\\sigma(a)=\\max\\{a,0\\}$ is the ReLU activation function applied element-wise. Here $k_0$ and $k_{\\mathcal L+1}$ are the input and output dimensions, respectively. And $k_i$, $i=1,2,\\ldots,\\mathcal L$ is the number of neurons (width) in the $i$th hidden layer.\n\nThe depth of a network is defined as the number $\\mathcal L$ of hidden layers, and its width refers to the maximum width $\\mathcal N=\\max\\{k_1,k_2,\\ldots,k_{\\mathcal L}\\}$ of hidden layers. The size of a network can be further measured by two more quantities: the total number of neurons $\\mathcal U=\\sum_{i=1}^{\\mathcal L}k_i$, and the total number of parameters $\\mathcal S=\\sum_{i=0}^{\\mathcal L}k_{i+1}\\cdot(k_i+1)$.'

def main():
    for lid, member in members.items():
        assert all(d in members for d in member['depends_on']), lid
        own = member['statement_original'] + ' ' + member['local_label']
        assert any(s in own for s in member['highlight_symbols'] + member['highlight_phrases']), lid
        assert not any(ord(c) < 32 and c != '\n' for c in member['statement_original']), lid
    (ROOT / 'interface-extraction.json').write_text(json.dumps(dict(
        paper_id=PID, status='extracted_pending_source_audit', interfaces=interfaces,
        local_dependency_reasons=edges), indent=2, ensure_ascii=False)+'\n')
    print(f'Saved {len(interfaces)} source passages; dependency and source audit remain pending.')


if __name__ == '__main__':
    main()
