"""Attach source-reviewed theorem-to-interface paths and finalize this paper."""
import copy,json,subprocess,sys
from pathlib import Path
from extract_interfaces import ROOT,PID,interfaces,members,edges
SKILL=Path('skills/statistical-paper-census/scripts');sys.path.insert(0,str(SKILL))
from canonical_dependencies import canonical_dependencies
from census_metrics import derive_metrics
from publication_contract import attach_inventory
DIRECT={
'1':{
'D1':'The opening reference to (3) selects the single-index prior; the final sentence also permits its explicitly defined truncation at k=n.',
'D2':'The first branch specifies (5), here its sigma_k scale.',
'D3':'The second branch selects sigma_k from (6), subject to alpha at least beta.',
'D5':'Both branches require the innovation density conditions (7)-(8).',
'D6':'The hypothesis explicitly requires moment condition (14) with q=2.',
'D8':'The truth belongs to the coefficient Sobolev ball S^beta(L) from (9).',
'D11':'The conclusion averages the ordinary posterior probability Pi[...|X^(n)] under the true sampling law.',
'D13':'The opening clause specifies the independent Gaussian regression model (13).'},
'2':{
'D1':'The theorem specifies the single-index series prior (3).',
'D2':'The first prior branch uses sigma_k from (5).',
'D3':'The alternative prior branch uses sigma_k from (6), with alpha at least beta.',
'D5':'The density assumptions are explicitly (7)-(8).',
'D6':'The theorem explicitly assumes (14) with q=2.',
'D8':'The hypothesis on f0 is membership in S^beta(L) from (9).',
'D11':'Pi[...|X^(n)] is the ordinary posterior under the inverse model.',
'D14':'The model reference (15) specifies singular values of order k^(-nu), with nu nonnegative; that nu also enters the rate denominator.'},
'3':{
'D1':'The theorem specifies wavelet coefficients and prior (4).',
'D2':'Its first branch uses the wavelet scale s_l in (5).',
'D3':'Its second branch uses s_l in (6), with alpha at least beta+1/q.',
'D5':'Both prior branches require conditions (7)-(8) on h.',
'D6':'Condition (14) holds for q at least one; the chosen q also enters the polynomial-branch restriction.',
'D9':'The truth is in the wavelet Hölder-type ball H^beta(L) in (10).',
'D11':'The conclusion is an expected ordinary posterior probability under supremum-norm loss.',
'D15':'The opening sentence explicitly locates the coefficients in model (16).'},
'4':{
'D1':'The prior is explicitly generated by wavelet construction (4).',
'D2':'Its initial branch specifies scale choice (5).',
'D3':'The final sentence specifies (sigma_k) as in (6), although the opening construction is wavelet-indexed; the source wording is preserved as a notation discrepancy.',
'D5':'The prior is required to satisfy (7)-(8).',
'D6':'The theorem explicitly assumes (14) with q=2.',
'D10':'The truth belongs to B^beta_rr(L), with r in [1,2] and the additional beta>1/r-1/2 restriction.',
'D11':'The conclusion is an expected ordinary posterior probability under L2 loss.',
'D12':'The opening clause identifies the white noise regression model (12).',
'D15':'Section 2.4 explicitly sets the Besov result in the projected white noise model (16); X^(n) is that wavelet observation sequence.'},
'5':{
'D1':'The theorem explicitly uses the wavelet series prior (4).',
'D2':'The first branch uses (5), together with the separately specified weight l^(1+kappa+epsilon).',
'D3':'The second branch uses s_l in (6) for any alpha>0 and the different weight l^((1+kappa+epsilon)/2).',
'D5':'The prior assumptions are (7)-(8); kappa in (8) also enters both weight formulas.',
'D9':'The truth is assumed to belong to H^beta(L) from (10).',
'D15':'The wavelet observations are explicitly those in (16).',
'D17':'The theorem explicitly invokes M0 as defined by (18), with its branch-specific weights.',
'D18':'The comparison law L(W) is the law of the standard Gaussian white-noise coefficient sequence.',
'D19':'Pi[.|X^(n)] composed with tau inverse is the centered and rescaled posterior defined immediately before the theorem.',
'D20':'The conclusion uses beta_M0, the bounded-Lipschitz metric specialized to M0.'},
'6':{
'D1':'The initial clause specifies a prior generated by the single-index construction (3).',
'D3':'The first bullet specifies (6) with alpha>1/2, and restricts beta to beta<=alpha.',
'D4':'The second bullet defines the general scale (21) with a,delta>0 and rate (22).',
'D5':'Both bullets explicitly require (7)-(8).',
'D7':'Both bullets explicitly require the tail condition (19), rather than the moment condition (14).',
'D8':'Both prior-mass lower bounds are centered at f0 in the coefficient ball S^beta(L).'},
'7':{
'D1':'The initial clause specifies a prior generated by the wavelet construction (4).',
'D2':'The second bullet selects the wavelet scale (5) and rate (24).',
'D3':'The first bullet selects s_l in (6), with alpha>1/2 and beta<=alpha, and rate (23).',
'D5':'Both bullets require (7)-(8) for h.',
'D7':'Both bullets require tail condition (19).',
'D9':'Both prior-mass lower bounds are centered at f0 in H^beta(L).'},
'8':{
'D1':'The reference to the prior parameters in Theorem 7 selects the wavelet construction (4).',
'D2':'The second prior branch inherited from Theorem 7 uses (5), paired with rate (24).',
'D3':'The first prior branch inherited from Theorem 7 uses s_l in (6), alpha>1/2 and beta<=alpha, paired with rate (23).',
'D5':'The reference to Theorem 7 carries its explicit density conditions (7)-(8).',
'D7':'The same reference carries tail condition (19), without importing moment assumption (14).',
'D9':'The theorem requires the true log-density f0=log g0 to belong to H^beta(L).',
'D21':'The conclusion concerns Pi_rho for rho<1 within the previously defined range 0<rho<=1.',
'D22':'The density prior is generated by map (25); the theorem explicitly allows both branches of Theorem 7 despite the opening example before (25).'},
'9':{
'D1':'The theorem refers explicitly to the prior parameters of Theorem 6, whose opening specifies (3). The preceding classification prose instead mentions (4); this source discrepancy remains recorded.',
'D3':'The polynomial branch inherited from Theorem 6 uses (6), alpha>1/2 and beta<=alpha, paired with rate (20).',
'D4':'The second branch inherited from Theorem 6 uses the general scale (21), paired with rate (22).',
'D5':'The reference to Theorem 6 includes its conditions (7)-(8) on h.',
'D7':'That reference also includes tail condition (19).',
'D8':'The theorem explicitly requires f0 in the Sobolev coefficient ball S^beta(L).',
'D21':'Its conclusion concerns the likelihood-power posterior Pi_rho, for 0<rho<1 by the section convention.',
'D23':'The opening invokes the binary classification model and its true regression function h0.',
'D24':'The true function is defined by f0=Lambda^{-1}h0.',
'D25':'The prior is explicitly generated by the logistic map (26).',
'D26':'The conclusion prints p_f-p_f0, using the joint density defined immediately above; the G,1 norm domain ambiguity is recorded separately.'},
'10':{
'D1':'The prior is explicitly generated by the wavelet construction (4).',
'D2':'The only scale branch specified is (5); no (6) alternative is stated.',
'D5':'The theorem explicitly assumes (7)-(8).',
'D7':'It explicitly assumes the tail condition (19), without adding (14).',
'D10':'The truth lies in B^beta_rr(L), with r in [1,2] and beta>1/r-1/2.',
'D12':'The opening specifies the white noise regression model.',
'D15':'For the wavelet prior (4), the observation X^(n) follows the wavelet sequence convention (16) introduced in Section 2.3.',
'D21':'The conclusion is for the tempered posterior Pi_rho, with 0<rho<1 by the section convention.'}
}
def main():
    import extract_interfaces
    extract_interfaces.ROOT=ROOT
    extract_interfaces.main()
    inv=json.loads((ROOT/'theorem-inventory.json').read_text());data=copy.deepcopy(inv)
    data['schema_version']='statistical-ranked-interfaces-v4'
    data['scope'].update(paper_count=1,
        source_policy='Verified registered arXiv:2308.04916v3 PDF, 59 pages; main text on pages 1-25 and the upper portion of page 26 before Supplementary Material. Supplement and appendices excluded.',
        normalization_policy='Preserve all ten complete original Theorems 1-10, both branches of Theorems 6 and 7, all rate exponents and source notation discrepancies. Explanatory notes remain separate from quotations.',
        semantic_ranking_policy='Resolve the prior constructions, scale alternatives, density and tail conditions, smoothness balls, models and posterior maps. Unpack Theorems 6 and 7 when their parameters and rates are explicitly referenced by Theorems 9 and 8. Do not propagate moment (14) through tail (19), fix a prior branch on a generic transformation, or add proof-only dependencies.',
        build_order_policy='Derive all edges and reach from the original local dependency graph; keep the independent theorem inventory unchanged.')
    data['interfaces']=copy.deepcopy(interfaces);claims={c['claim_id']:c for c in data['claims']}
    assert set(DIRECT)=={c['claim_id'].split('/T')[-1] for c in data['claims']}
    for c in data['claims']:
        n=c['claim_id'].split('/T')[-1];c['depends_on']=list(DIRECT[n])
        for x in data['interfaces']:
            lid=x['members'][0]['local_id']
            if lid in DIRECT[n]:
                evidence=list(c['evidence'])
                evidence.extend(e for e in members[lid]['evidence'] if e not in evidence)
                x['central_claim_uses'].append(dict(use_id=c['claim_id']+'-'+lid,paper_id=PID,claim_id=c['claim_id'],use_kind='statement_dependency',reason=DIRECT[n][lid],evidence=evidence))
    derived=canonical_dependencies(data)
    for x in data['interfaces']:x['dependencies']=derived[x['interface_id']]
    derive_metrics(data)
    for x in data['interfaces']:
        for r in x['related_theorems']:
            cid=r['claim_id'];path=r['via_local_ids'];n=cid.split('/T')[-1]
            sentences=[DIRECT[n][path[0]]];evidence=list(claims[cid]['evidence'])
            for lid in path:evidence.extend(e for e in members[lid]['evidence'] if e not in evidence)
            for a,b in zip(path,path[1:]):sentences.append(edges[a][b])
            x['theorem_explanations'][cid]=dict(paper_id=PID,via_local_ids=path,text=' '.join(sentences),evidence=evidence)
        for m in x['members']:
            own=m['statement_original']+' '+m['local_label']
            linked=own+' '+' '.join(claims[r['claim_id']]['statement_original'] for r in x['related_theorems'])
            selectors=m['highlight_symbols']+m['highlight_phrases']
            assert any(s in own for s in selectors),(m['local_id'],'missing source highlight')
            assert all(s in linked for s in selectors),(m['local_id'],'unmatched selector')
    attach_inventory(data,ROOT/'theorem-inventory.json',ROOT/'ranked-interfaces.json')
    (ROOT/'unfinalized-census.json').write_text(json.dumps(data,indent=2,ensure_ascii=False)+'\n')
    subprocess.run([sys.executable,str(SKILL/'finalize_census.py'),str(ROOT/'unfinalized-census.json'),str(ROOT/'ranked-interfaces.json'),'--inventory',str(ROOT/'theorem-inventory.json')],check=True)
    subprocess.run([sys.executable,str(SKILL/'validate_census.py'),str(ROOT/'ranked-interfaces.json')],check=True)
    print('Structural validation passed; independent full source audit remains pending.')
    finalized=json.loads((ROOT/'ranked-interfaces.json').read_text())
    passages=dict(paper_id=PID,members=[m for x in finalized['interfaces'] for m in x['members']])
    (ROOT/'source-passages.json').write_text(json.dumps(passages,indent=2,ensure_ascii=False)+'\n')

if __name__ == "__main__":
    main()
