"""Rebuild the manually transcribed complete main-text theorem inventory."""
import argparse,hashlib,json,subprocess,sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
REPO=next(p for p in ROOT.parents if (p/'scripts/resolve_paper_pdf.py').is_file())
PID='aos-2024-v52-i04-p1433'
SHA='36a56438156e943f34cd8fd429857a5707dac77a4cd2606c8533def916aca2cb'
claims=[]
def claim(number,page,text,title=None):
    claims.append(dict(claim_id=f'{PID}/T{number}',paper_id=PID,claim_kind='theorem',label=f'Theorem {number}'+(f' ({title})' if title else ''),source_order=len(claims)+1,statement_original=text.strip(),evidence=[dict(page=page,location=f'Theorem {number}, complete original statement')]))
claim('1',7,r'''
In the regression model (13), consider the heavy-tailed series prior (3) with parameters specified by (5) and (7)–(8) as well as (14) with $q=2$. Suppose $f_0\in\mathcal S^\beta(L)$ for some $\beta,L>0$. Then, as $n\to\infty$,
\[
E_{f_0}\Pi\left[\{f:\|f-f_0\|_2>\mathcal L_nn^{-\beta/(2\beta+1)}\}\mid X^{(n)}\right]\to0,
\]
where $\mathcal L_n=(\log n)^d$ for some $d>0$. Further, the same result holds, with a possibly different $d$, for the choice of $(\sigma_k)$ as in (6), provided $\alpha\ge\beta$. Both results also hold for truncated priors at $k=n$, that are the same as the ones considered except they set $f_k=0$ for $k>n$.
''')
claim('2',9,r'''
In the inverse regression model (15) with degree of ill–posedness of the forward operator $\nu\ge0$, consider the heavy-tailed series prior (3) with parameters specified by (5) and (7)–(8) as well as (14) with $q=2$. Suppose $f_0\in\mathcal S^\beta(L)$ for some $\beta,L>0$. Then, as $n\to\infty$,
\[
E_{f_0}\Pi[\{f:\|f-f_0\|_2>\mathcal L_nn^{-\beta/(2\beta+2\nu+1)}\}\mid X^{(n)}]\to0,
\]
where $\mathcal L_n=(\log n)^d$ for some $d>0$. Further, the same result holds, with a possibly different $d$, for the choice of $(\sigma_k)$ as in (6), provided $\alpha\ge\beta$.
''')
claim('3',10,r'''
In the regression model, let us consider the prior on $f$ induced by the heavy-tailed wavelet series prior (4) on coefficients $f_{lk}$ in (16), with parameters specified by (5) and (7)–(8) as well as (14) with $q\ge1$. Suppose $f_0\in\mathcal H^\beta(L)$ for some $\beta,L>0$. Then, as $n\to\infty$,
\[
E_{f_0}\Pi[\{f:\|f-f_0\|_\infty>\mathcal L_n(\log n/n)^{\beta/(2\beta+1)}\}\mid X^{(n)}]\to0,
\]
where $\mathcal L_n=(\log n)^d$ for some $d>0$. Further, the same result holds, with a possibly different $d$, for the choice of $(s_l)$ as in (6) and under (14) with any $q\ge1$, provided $\alpha\ge\beta+1/q$.
''')
claim('4',10,r'''
In the white noise regression model, let $\Pi$ be a heavy tailed prior generated by (4) with parameters specified by (5) and (7)–(8) as well as (14) with $q=2$. Suppose $f_0\in\mathcal B^\beta_{rr}(L)$ for some $\beta,L>0$, $r\in[1,2]$ and $\beta>1/r-1/2$. Then, as $n\to\infty$,
\[
E_{f_0}\Pi[\{f:\|f-f_0\|_2>\mathcal L_nn^{-\beta/(2\beta+1)}\}\mid X^{(n)}]\to0,
\]
where $\mathcal L_n=(\log n)^d$ for some $d>0$. Further, the same result holds, with a possibly different $d$, for the choice of $(\sigma_k)$ as in (6), provided $\alpha\ge\beta$.
''')
claim('5',11,r'''
In the regression model, let us consider the heavy-tailed wavelet series prior (4) on coefficients $f_{lk}$ in (16), with parameters specified by (5) and (7)–(8). Consider the multiscale space $\mathcal M_0$ as in (18) with $w_l=l^{1+\kappa+\varepsilon}$ for some $\varepsilon>0$. Suppose $f_0\in\mathcal H^\beta(L)$ for some $\beta,L>0$. Then
\[
E_{f_0}\beta_{\mathcal M_0}(\Pi[\cdot\mid X^{(n)}]\circ\tau^{-1},\mathcal L(\mathbb W))\to0
\]
as $n\to\infty$, where $\mathcal L(\mathbb W)$ denotes the law of a Gaussian white noise in $\mathcal M_0$. Further, the same result holds for $(s_l)$ as in (6) with $w_l=l^{(1+\kappa+\varepsilon)/2}$, for some $\varepsilon>0$ (and any $\alpha>0$).
''')
claim('6',12,r'''
For $\Pi$ a prior generated by (3),

• suppose $(\sigma_k)$ is as in (6) for $\alpha>1/2$ and assume (7)–(8)–(19). For $\beta>0$, let
\[
\varepsilon_n=(\log n)^{\frac{1+(1+\kappa)\beta}{2\beta+1}}n^{-\frac\beta{2\beta+1}}.\tag{20}
\]
Then for any $\beta\le\alpha$, $L>0$ and $f_0\in\mathcal S^\beta(L)$, it holds that for any $d_2>0$ there exists $d_1>0$ sufficiently large such that
\[
\Pi[\|f-f_0\|_2<d_1\varepsilon_n]\ge e^{-d_2n\varepsilon_n^2}.
\]

• suppose $(\sigma_k)$ is defined, for some $a,\delta>0$, by
\[
\sigma_k=e^{-a(\log k)^{1+\delta}},\tag{21}
\]
and assume (7)–(8)–(19). For $\beta>0$, let
\[
\varepsilon_n=(\log n)^{\frac{(1+\kappa)(1+\delta)\beta}{2\beta+1}}n^{-\frac\beta{2\beta+1}}.\tag{22}
\]
Then for any $\beta>0$, $L>0$ and $f_0\in\mathcal S^\beta(L)$, it holds that for any $d_2>0$ there exists $d_1>0$ sufficiently large such that
\[
\Pi[\|f-f_0\|_2<d_1\varepsilon_n]\ge e^{-d_2n\varepsilon_n^2}.
\]
''',r'Generic prior mass condition in $L^2$')
claim('7',13,r'''
For $\Pi$ a prior generated by (4),

• suppose $(s_l)$ is as in (6) for $\alpha>1/2$ and assume (7)–(8)–(19). For $\beta>0$, let
\[
\varepsilon_n=(\log\log n)^{\frac2{1+2\beta}}(\log n)^{\frac{1+(1+\kappa)\beta}{1+2\beta}}n^{-\frac\beta{2\beta+1}}.\tag{23}
\]
Then for any $\beta\le\alpha$, $L>0$ and $f_0\in\mathcal H^\beta(L)$, it holds that for any $d_2>0$ there exists $d_1>0$ sufficiently large such that, for large enough $n$,
\[
\Pi[\|f-f_0\|_\infty<d_1\varepsilon_n]\ge e^{-d_2n\varepsilon_n^2}.
\]

• suppose $(s_l)$ is as in (5) and assume (7)–(8)–(19). For $\beta>0$, let
\[
\varepsilon_n=(\log n)^{\frac{(2+2\kappa)\beta}{1+2\beta}}n^{-\frac\beta{2\beta+1}}.\tag{24}
\]
Then for any $\beta>0$, $L>0$ and $f_0\in\mathcal H^\beta(L)$, it holds that for any $d_2>0$ there exists $d_1>0$ sufficiently large such that, for large enough $n$,
\[
\Pi[\|f-f_0\|_\infty<d_1\varepsilon_n]\ge e^{-d_2n\varepsilon_n^2}.
\]
''',r'Generic prior mass condition in $L^\infty$')
claim('8',14,r'''
Consider data $X=(X_1,\ldots,X_n)$ sampled independently from a density $g_0$ on $[0,1]$ that is bounded away from 0 and suppose $f_0:=\log g_0\in\mathcal H^\beta(L)$ for some $\beta>0$. Let $\Pi$ be a prior on densities $g$ generated by (25), with parameters on the prior on $f$ as in the statement of Theorem 7 (e.g. $\alpha>1/2$ for the HT($\alpha$) prior) with corresponding rates $\varepsilon_n$ as in (23) or (24). For any $\rho<1$, there exists $M=M(\rho)>0$ with
\[
E_{g_0}\Pi_\rho[\|g-g_0\|_1>M\varepsilon_n\mid X]\to0
\]
as $n\to\infty$, and where $P_0=P_{g_0}$.
''','density estimation')
claim('9',14,r'''
Consider data $(X,Y)$ from the binary classification model. Suppose $f_0=\Lambda^{-1}h_0$ belongs to the Sobolev ball $\mathcal S^\beta(L)$ for $\beta,L>0$. Let $\Pi$ be a prior generated by (26), with parameters on the prior on $f$ as in the statement of Theorem 6 with corresponding rates $\varepsilon_n$ as in (20) or (22). Then for any given $\rho<1$, there exists $M=M(\rho)$ such that, as $n\to\infty$,
\[
E_{P_0}\Pi_\rho[\|p_f-p_{f_0}\|_{G,1}>M\varepsilon_n\mid X_1,Y_1,\ldots,X_n,Y_n]\to0.
\]
''','classification')
claim('10',15,r'''
In the white noise regression model, for $\Pi$ a prior generated by (4) and (5), assume (7)–(8)–(19) hold. Suppose $f_0\in\mathcal B^\beta_{rr}(L)$ for some $\beta,L>0$, $r\in[1,2]$ and $\beta>1/r-1/2$. Then, for any given $\rho<1$, as $n\to\infty$,
\[
E_{f_0}\Pi_\rho\left[\{f:\|f-f_0\|_2>\mathcal L_nn^{-\frac\beta{2\beta+1}}\}\mid X^{(n)}\right]\to0,
\]
where $\mathcal L_n=(\log n)^d$ for some $d>0$.
''')
def main():
    source=Path(subprocess.check_output([sys.executable,str(REPO/'scripts/resolve_paper_pdf.py'),PID],text=True).strip())
    assert hashlib.sha256(source.read_bytes()).hexdigest()==SHA
    paper=dict(paper_id=PID,title='Heavy-tailed Bayesian nonparametric adaptation',authors=['Sergios Agapiou','Ismaël Castillo'],version='arXiv:2308.04916v3, 29 May 2024',source_url='https://arxiv.org/pdf/2308.04916v3',pdf_pages=59,pdf_sha256=SHA,main_text_last_pdf_page=26,main_text_boundary=dict(location='Main text ends after Funding on PDF page 26, before the SUPPLEMENTARY MATERIAL heading at y=157.9671630859375 PDF points. Supplement introduction and all lettered appendix sections are excluded.',shared_page_with_appendix=True),intake_review=dict(status='complete',theorem_ids=[c['claim_id'] for c in claims],zero_theorems_confirmed=False))
    data=dict(schema_version='statistical-theorem-inventory-v1',scope=dict(theorem_scope='main_text_only',source_policy='Verified registered arXiv v3 PDF, pages 1-25 and the Acknowledgments/Funding portion of page 26. Supplement and appendices excluded.'),papers=[paper],claims=claims)
    ROOT.mkdir(parents=True,exist_ok=True);(ROOT/'theorem-inventory.json').write_text(json.dumps(data,indent=2,ensure_ascii=False)+'\n')
if __name__=='__main__':
    p=argparse.ArgumentParser(description=__doc__);p.add_argument('--output-dir',type=Path);a=p.parse_args()
    if a.output_dir:ROOT=a.output_dir.resolve()
    main()
