"""Preserve supporting formulas, source discrepancies and statement scopes."""
import json
from save_inventory import ROOT,PID
def main():
    aux=[]
    def add(n,s,pages,note,deps=()):
        aux.append(dict(local_id='A'+str(n),statement_original=s,evidence=[dict(page=p,location='Original main-text context A'+str(n)) for p in pages],scope_note=note,depends_on=list(deps)))
    add(1,r'''Let $\pi_0$ be the identity permutation of $[n]$.''',[8],'Identity used explicitly by Theorem 3.3.',['D3'])
    add(2,r'''Let $\sigma$ be an arbitrary permutation of $[n]$ and $\sigma^{-1}$ its inverse, such that $\sigma\circ\sigma^{-1}=\sigma^{-1}\circ\sigma=\pi_0$ with $\circ$ denoting composition.''',[8],'Original composition and inverse convention for Condition 3.1.',['D3'])
    add(3,r'''In this section, we establish that PALMRT provides finite-sample type I error guarantees under any design and exchangeable noise. This property is generalized to a family of tests that performs comparisons with paired statistics as realizations of a specially-designed bi-variate function on permutation orders.''',[8],'Source scope for the standing model and exchangeable noise in Theorem 3.3, whose printed preamble does not repeat Assumption 1.1.',['D1','D2'])
    add(4,r'''Set $c_{b1}=\|(I-H^{x_{\pi_b}z_{\pi_b}z})x\|_2^2$, $c_{b2}=x^\top(I-H^{x_{\pi_b}z_{\pi_b}z})y$, $c_{b3}=\|(I-H^{x_{\pi_b}z_{\pi_b}z})y\|_2^2$, and $c_{b4}=\|(I-H^{x_\pi z_{\pi_b}z})y\|_2^2$. Then, we have $c_{b2}^2\geq c_{b1}(c_{b3}-c_{b4})$ and
\[
\omega_b(\beta)=\begin{cases}
\frac12\mathbb 1\{c_{b3}=c_{b4}\}+\mathbb 1\{c_{b3}<c_{b4}\},&\text{if }c_{b1}=0,\\
\frac12\mathbb 1\{\beta\in[s_b,u_b]\}+\mathbb 1\{\beta\in(s_b,u_b)\},&\text{if }c_{b1}>0,
\end{cases}
\]
(5)
where $s_b=\frac{c_{b2}-\sqrt{c_{b2}^2-c_{b1}(c_{b3}-c_{b4})}}{c_{b1}}$ and $u_b=\frac{c_{b2}+\sqrt{c_{b2}^2-c_{b1}(c_{b3}-c_{b4})}}{c_{b1}}$.''',[11],'Complete Lemma 4.3, retained as supporting source, not an inventoried Theorem. Preserve unindexed x_pi in c_b4 and the overlapping indicators in (5). Coefficients and roots depend on D3-D4; the omega identity additionally refers to D8. Root division is used on the c_b1>0 branch.',['D3','D4','D8'])
    add(5,r'''As a result, we first partition of index set of $\{0,\ldots,B\}$ into three sets $A_1=\{b:c_{b1}>0\}$, $A_2=\{b:c_{b1}=0,c_{b3}<c_{b4}\}$, and $A_3=\{b:c_{b1}=0,c_{b3}=c_{b4}\}$. The value of $\omega_b(\beta)$ remains constant as we vary $\beta$ for $b\in A_2\cup A_3$. Hence, the requirement of $f(\beta)>\alpha$ is equivalent to imposing a requirement on $f_{A_1}(\beta)$ that captures the contribution of $\omega_b(\beta)\in A_1$ as shown below:
\[
f(\beta)>\alpha\Longleftrightarrow f_{A_1}(\beta)=\sum_{b\in A_1}\omega_b(\beta)>(B+1)\alpha-1-|A_2|-\frac12|A_3|:=\gamma.
\]''',[11],'Original partition, threshold and reduced sum. Preserve index zero and the omitted fourth coefficient case, rather than silently fixing the claimed partition.',['D3','D4','D8'])
    add(6,r'''It can be shown that the function value of $f_{A_1}(\beta)$ is characterized by comparing $\beta$ to different $s_b/u_b$ values for $b\in A_1$:
\[
f_{A_1}(\beta)=\frac12\#\{b:s_b\leq\beta\}+\frac12\#\{b:s_b<\beta\}-\frac12\#\{b:u_b\leq\beta\}-\frac12\#\{b:u_b<\beta\}.
\]
(6)''',[12],'Original counting formula; the surrounding sentence restricts b to A1. It disagrees with printed (5) on interval interiors and at coincident roots.',['D3','D4','D8'])
    add(7,r'''The set obtained through directly inverting $\{\beta:f(\beta)>\alpha\}$, is often an interval, but not always guaranteed to be so. By taking the infimum and supremum of this set, we obtain a confidence interval $\mathrm{CI}_\alpha$ with worst-case guarantee at least as strong as direct inversion.''',[11],'Remark 4.2: the CI is an interval hull, not an assertion that the inversion set is connected.',['D8','D9'])
    add(8,r'''\[
T^{\mathrm{PALMRT}}(\pi_1,\pi_2;x,Z,\varepsilon)=\|(I-H^{x_{\pi_2}z_{\pi_2}z_{\pi_1}})\varepsilon\|_2^2.
\]
(4)''',[8],'Concrete bivariate example. Theorem 3.3 accepts a generic transferable T and does not acquire this particular formula or its projection prerequisite.',['D3','D4'])
    add(9,r'''Subsequently, we generate $B$ random permutations $\{\pi_b\}_{b=1}^B$ of $[n]$ uniformly and compare the associated original and permuted statistics to compute the p-value for testing $H_0:\beta=0$.''',[6],'Generation convention for Algorithm 1 and the coefficient null. The statement says uniformly, not independently. The source proof sampling convention is recorded separately in A10.',['D3','D6','D7'])
    add(10,r'''Let $\sigma$ and $(\pi_b)_{b=1}^B$ be generated independently and uniformly from $S_n$.''',[14],'Opening sampling premise of Proposition 5.1 in the main-text proof. It clarifies the proof uses independent draws; it is not inserted into the original Theorem quotation or made into a new statement API. S_n denotes all permutations of [n].',['D3'])
    add(11,r'''The confidence interval $\mathrm{CI}_\alpha$ can potentially be an empty set ($\emptyset$). Although this does not invalidate our assertion, an empty set offers limited information in practical contexts and might not be desired. In such situations, one may opt to construct the confidence interval using a normal approximation in the regression $y\sim x+Z$ whenever Algorithm 2 produces an empty set as the output for $\mathrm{CI}_\alpha$.''',[12],'Remark 4.5 offers an optional normal-approximation replacement. This is not an Algorithm 2 instruction or a guarantee established by Theorem 4.4.',['D1','D11'])
    issues=[]
    def issue(key,text,pages):issues.append(dict(issue_id=key,description=text,evidence=[dict(page=p,location='Original main-text statement or construction') for p in pages]))
    issue('standing-exchangeability','Theorem 3.3 omits an explicit repeat of Assumption 1.1. The section opener specifies exchangeable noise and arbitrary design; this standing premise is linked separately, without rewriting the theorem.',[2,8,9])
    issue('sampling-scope','The theorem says uniformly random permutations, while the main-text proof uses independent uniform draws. The sampling discrepancy is recorded without adding independently to the original statement.',[6,9,14])
    issue('lemma-corollary-reference','Theorem 4.4 prints Lemma 4.1. The referenced CI definition is printed as Corollary 4.1. Keep the original theorem and resolve its definition to that actual source passage.',[11,12])
    issue('inversion-algorithm-reference','The Section 4 opening directs response replacement to Algorithm 2 when constructing paired statistics. Their construction is actually Algorithm 1 step 4 and equation (3). Preserve the printed reference and resolve the concrete statistic formulas without creating a circular dependency.',[6,11,13])
    issue('coefficient-four-projection','Lemma 4.3 prints x_pi in the projection defining c_b4, with pi not indexed by b. The residual pair (3) instead uses x in the corresponding unpermuted-feature projection. This unbound or mismatched permutation is not silently repaired.',[6,11])
    issue('overlapping-indicators','For c_b1>0, equation (5) adds half the closed-interval indicator to the open-interval indicator, yielding 1.5 on a nonempty interior. The original comparison weight in Section 4 takes values only 0, 0.5 or 1. The census preserves both formulas.',[11])
    issue('coincident-root-counts','Equation (6) cancels completely when s_b=u_b, whereas equation (5) contributes 0.5 at that root. Its nondegenerate interior weight is 1, also differing from printed (5). No replacement formula is supplied.',[11,12])
    issue('partition-index-and-coverage','The claimed partition uses {0,...,B}, although the coefficients are calculated only for b=1,...,B. It also omits c_b1=0,c_b3>c_b4. Neither an index-zero coefficient nor an additional set is invented.',[11,13])
    issue('algorithm-coverage-comment','Algorithm 2 line 1 prints coverage 1-alpha, but Theorem 4.4 asserts worst-case coverage 1-2alpha. Both originals are retained.',[12,13])
    issue('algorithm-boundary-cases','Algorithm 2 accesses t_1 without a printed M=0 branch and its endpoint formulas refer to t_0^+ or t_M^+ at boundary indices; the loop explicitly records only earlier right-side values. No implicit indexing, empty-set convention or extra computational branch is added.',[12,13])
    issue('interval-and-fallback-scope','Corollary 4.1 defines infimum/supremum of a strict superlevel set. Remark 4.2 takes its interval hull; Remark 4.5 only suggests an optional normal approximation for an empty result. That suggestion is not incorporated into Theorem 4.4 or Algorithm 2.',[11,12,13])
    refs=[dict(from_claim_id=PID+'/T3.3',to_source_label='Condition 3.1; Algorithm 1',reference_kind='construction',scope='Generic T satisfying Condition 3.1 replaces Algorithm 1 statistic construction; only the comparison and p-value recipe are inherited.'),dict(from_claim_id=PID+'/T4.4',to_source_label='Algorithm 2; Corollary 4.1 (printed as Lemma 4.1 in the theorem)',reference_kind='construction',scope='Keep all Algorithm 2 instructions and original CI target; preserve source discrepancies separately.'),dict(from_claim_id=PID+'/T4.4',to_source_label='Appendix A',reference_kind='proof_only',scope='Proof is deferred to the appendix. No appendix body is inspected or imported.')]
    bindings={'T3.3':'Model and coefficient null are D1 and D6. Exchangeable noise is the standing Assumption 1.1, D2, supported by A3. [n], row permutation and identity are D3/A1; composition is A2. B, pi_1,...,pi_B, the generic T and its paired evaluations are bound in the theorem. Condition 3.1 is D5; p_val is D6. The generic substitution does not import D4, D7 or the concrete T^PALMRT in A8. Probability is marginalized over noise and permutations; the proof sampling convention and its difference from the printed statement are recorded in A10.','T4.4':'The interval target is D9, printed Corollary 4.1, despite the theorem saying Lemma. Its f(beta) is D8, based on D6 and the concrete residual pair D7. Algorithm 2 is D11, with its coefficients and roots A4, threshold and partition A5, counting formula A6 and critical-value sweep D10. Model and standing exchangeability remain D1-D2. Alpha is the requested mis-coverage level. Algorithm comments and formula inconsistencies are source issues, not silently added hypotheses. Neither Condition 3.1 nor the optional normal approximation is imported through proof reasoning.'}
    out=dict(paper_id=PID,status='extracted',unranked_auxiliary_passages=aux,source_issues=issues,source_claim_references=refs,statement_local_bindings=bindings,ambient_prerequisites=['Finite-dimensional real vectors, matrices, Euclidean norms, orthogonal projections onto column spaces, indicator functions, finite sums/counts, probability, permutation composition and inverses use their ordinary mathematical meanings. No library availability is asserted.','The model uses x as a vector and Z as a matrix of nuisance features; y and epsilon collect the observations and errors. The source uses both epsilon glyphs; no distributional restriction is inferred from that typography.','B is the permutation count, n the sample size and p the nuisance dimension. The source theorem quantifies alpha>0; no alpha<1 condition is inserted into its quotation.','Theorem 3.3 has generic statistic inputs: its p-value subrecipe is extracted separately from the concrete PALMRT construction. The source null H0 is beta=0.','Unnamed coefficients, partitions and roots are retained in full auxiliary passages and their indexed prerequisites are expanded in D10-D11. Source errors do not justify changing the original formulas or certifying the claimed algorithm correctness.','The strict inversion superlevel set may be disconnected or empty. No extended-real infimum/supremum convention, missing critical-index handling or corrected comparison formula is invented. Appendix proof material is excluded.'])
    (ROOT/'ambient-prerequisites.json').write_text(json.dumps(out,indent=2,ensure_ascii=False)+'\n')
if __name__=='__main__':main()
