"""Preserve original PCM algorithms, regression targets, assumptions and spline source passages."""
import json,hashlib
from save_inventory import ROOT,PID,STATEMENTS
REVIEW_ROOT=ROOT
interfaces=[];members={}
def add(n,term,s,pages,deps,symbols,boundary,heading,kind='definition',context=None,context_page=None,phrases=None):
    lid=f'D{n}'
    m=dict(paper_id=PID,local_id=lid,local_label=heading,source_heading=heading,source_kind=kind,statement_original=s,relation='exact',depends_on=[f'D{i}' for i in deps],evidence=[dict(page=p,location=heading) for p in pages],highlight_symbols=symbols,highlight_phrases=phrases or [])
    kw=dict(paper_id=PID,local_id=lid,source_text=term,label=term[0].upper()+term[1:],kind='term')
    if term not in s:
        assert context and term in context,(lid,term)
        m['naming_context']=[dict(context_id=lid+'/name',text=context,evidence=[dict(page=context_page or pages[0],location='Original naming context')])];kw['context_id']=lid+'/name'
    members[lid]=m
    interfaces.append(dict(interface_id=PID+'/'+lid,rank_group='all',name=kw['label'],lean_role='definition',type_shape=boundary,semantic_boundary=boundary,members=[m],source_keywords=[kw],central_claim_uses=[],dependencies=[],theorem_explanations={}))
add(1,'conditional mean independence',r'''In this work we consider the model-free null hypothesis of conditional mean independence, that is $\mathbb E(Y\mid X,Z)=\mathbb E(Y\mid Z)$; in words, $X$ does not feature in the regression function of $Y$ on $X$ and $Z$.''',[2],[6,7],[r'\mathbb E(Y\mid X,Z)=\mathbb E(Y\mid Z)'],'Original conditional mean null, not equality of the whole conditional distributions. Theorem4 has a separate stronger conditional-independence alternative.','Introduction — Conditional mean independence')
add(2,'target parameter',r'''\[
\tau:=\mathbb E\left[\{\mathbb E(Y\mid X,Z)-\mathbb E(Y\mid Z)\}^2\right],\tag{1}
\]
we have that $\tau=0$ if and only if $Y$ is conditionally mean independent of $X$ given $Z$.''',[3],[8],[r'\tau',r'\tau_P'],'Original squared-L2 signal, indexed byP in later results. It is not the unsquared norm or a conditional covariance.','Introduction — Signal parameter (1)',context=r'To circumvent this issue, Williamson et al. (2023) and independently Dai et al. (2024), utilise an alternative representation of the target parameter $\tau=\mathbb E[{Y-\mathbb E(Y\mid Z)}^2]-\mathbb E[{Y-\mathbb E(Y\mid X,Z)}^2]$')
add(3,'probabilistic notation',r'''In order to present our uniform results on testing, we require some conventions for probabilistic notation used in what follows. Let $(\Omega,\mathcal F)$ be a measurable space equipped with a family of probability measures $(\mathbb P_P)_{P\in\mathcal P}$ where $\mathcal P$ is a collection of distributions on a Euclidean space. We will permit the family $\mathcal P$ to depend on $n$, to allow for settings where the number of parameters grows with $n$, but will typically suppress this in the notation. Given a family of sequences of random variables $(X_{P,n})_{P\in\mathcal P,n\in\mathbb N}$ on $(\Omega,\mathcal F)$ whose distributions are determined by $P\in\mathcal P$, we write $X_{P,n}=o_{\mathcal P}(1)$ if $\sup_{P\in\mathcal P}\mathbb P_P(|X_{P,n}|>\epsilon)\to0$ for every $\epsilon>0$. Similarly, we write $X_{P,n}=O_{\mathcal P}(1)$ if, for any $\epsilon>0$, there exist $M_\epsilon,N_\epsilon>0$ such that $\sup_{n\ge N_\epsilon}\sup_{P\in\mathcal P}\mathbb P_P(|X_{P,n}|>M_\epsilon)<\epsilon$.
In addition, for another family of sequences of random variables $(Y_{P,n})_{P\in\mathcal P,n\in\mathbb N}$, we write $X_{P,n}=o_{\mathcal P}(Y_{P,n})$ if there exists $R_{P,n}$ with $X_{P,n}=Y_{P,n}R_{P,n}$ and $R_{P,n}=o_{\mathcal P}(1)$; likewise, we write $X_{P,n}=O_{\mathcal P}(Y_{P,n})$ if $R_{P,n}=O_{\mathcal P}(1)$ in this representation. We say that $(X_{P,n})_{P\in\mathcal P,n\in\mathbb N}$ converges uniformly in distribution to random variable $X$ with distribution function $F$ if for all continuity points $x$ of $F$, we have
\[
\lim_{n\to\infty}\sup_{P\in\mathcal P}|\mathbb P_P(X_{P,n}\le x)-F(x)|=0.
\]''',[7,8],[],[r'o_{\mathcal P}(1)',r'o_{\mathcal P_0}(n^{\delta/2})'],'Original uniform probabilistic orders with potentially n-dependent distribution classes. Random-scale order uses a multiplicative representation, not an undefined quotient at zero.','Section 1.3 — Uniform probabilistic notation')
add(4,'conditional expectations',r'''We will denote different independent datasets by $\mathcal D_1,\mathcal D_2,\ldots$, each containing $n$ independent observations. We will frequently abuse notation and write conditional expectations conditioning on a random function, e.g. $\mathbb E_P(\hat f(X,Z)\mid\hat f,Z)$ where $\hat f$ is a function produced by some regression estimator. By this we mean formally that we condition on the sample used to construct the regression estimator and any additional randomness involved in the computation of the regression function. We let $(X,Y,Z)$ be random variables in $\mathcal X\times\mathbb R\times\mathcal Z$, where $\mathcal X$ and $\mathcal Z$ are measurable spaces, although we will at times think of $\mathcal X$ and $\mathcal Z$ being specific $d_X$- and $d_Z$-dimensional Euclidean spaces, respectively.''',[8],[],[r'\mathbb E_P(\hat f(X,Z)\mid\hat f,Z)'],'Original conditioning convention includes the entire training sample and algorithmic randomness, not merely the sigma-field generated by a function-valued output. Separate data splits have n observations each.','Section 1.3 — Data and conditioning convention',kind='source_passage')
add(5,'standard normal distribution',r'''We use the notation $z_\alpha$ to denote the $\alpha$th quantile of the standard normal distribution, whose distribution function is denoted by $\Phi$.''',[7],[],[r'z_\alpha',r'\Phi',r'z_{1-\alpha}'],'Original normal reference quantile andCDF; reject in the upper tail only.','Section 1.3 — Normal reference distribution')
add(6,'conditional expectation',r'''Next, given an estimate $\hat m(\cdot)$ of $m(\cdot):=\mathbb E(Y\mid Z=\cdot)$, the oracular test statistic (3) suggests a numerator of our test statistic of the form''',[8],[],[r'm(\cdot):=\mathbb E(Y\mid Z=\cdot)'],'Original response-on-Z conditional mean target. Hats refer to supplied fitted functions; the dataset depends on the selected algorithm.','Section 2.1 — Response regression target',context=r'To motivate our specific strategy, consider an oracular test statistic that uses knowledge of the conditional expectation $\mathbb E(Y\mid Z)$:',context_page=4)
add(7,'conditional mean',r'''for $P\in\mathcal P$, let $g_P(x,z):=\mathbb E_P(Y\mid X=x,Z=z)$.''',[21],[],[r'g_P(x,z)'],'Original full response regression function used inAssumption4; the same g is introduced withoutP on12.','Assumption 4 — Full regression target',kind='definition',context=r'the conditional mean of $Y$ given $X$ and $Z$ does not depend on $X$.',context_page=1)
add(8,'projection',r'''where $h(X,Z):=\mathbb E(Y\mid X,Z)-\mathbb E(Y\mid Z)$ and $v(X,Z):=\operatorname{Var}(Y\mid X,Z)$. We therefore see that the optimal $f$ is a version of the projection $h$ of $Y$ onto the space of square-integrable functions of $(X,Z)$ that are orthogonal to functions of $Z$, inversely weighted by the conditional variance $v$.''',[4],[6,7],[r'h(X,Z):=\mathbb E(Y\mid X,Z)-\mathbb E(Y\mid Z)',r'h_P(X,Z)'],'Original unweighted regression differenceh and adjacent variance/weighted-projection interpretation. Theorem5 needs positive correlation withh, not consistency for h/v.','Section 1.1 — Regression projection')
add(9,'conditional expectation',r'''where $\hat m_{\hat f}$ is an estimate of $m_{\hat f}(\cdot):=\mathbb E(\hat f(X,Z)\mid Z=\cdot,\hat f)$.''',[8],[4],[r'm_{\hat f}(\cdot)'],'Original population regression target of a supplied learned projection onZ. Conditioning onhatf follows the training-sample convention on8. It is distinct from the fitted regressionhatm_hatf.','Section 2.1 — Projection regression target',context=r'for instance by subtracting from $\hat f(X,Z)$ an estimate of its conditional expectation given $Z$, to reduce bias;',context_page=5)
add(10,'single sample split',r'''Input: Data $(X_i,Y_i,Z_i)_{i=1}^{2n}$, significance level $\alpha\in(0,1)$, partition of $[2n]=\mathcal I_1\cup\mathcal I_2$ into index sets $\mathcal I_1$ and $\mathcal I_2$, each of size $n$.
Options: Regression methods for each of the regressions.
Define: $\mathcal D_j=(X_i,Y_i,Z_i)_{i\in\mathcal I_j}$ for $j\in[2]$.
1: Form $\hat h$.
(i) Regress $Y$ onto $(X,Z)$ using $\mathcal D_2$ to give fitted regression function $\hat g$.
(ii) If $\hat g$ can be modified so that all components involving only $Z$ are set to $0$, let $\tilde g$ be this modified version of $\hat g$. Alternatively, set $\tilde g:=\hat g$.
(iii) Regress $\tilde g(X,Z)$ onto $Z$ using $\mathcal D_2$ to give fitted regression function $\tilde m$, and then set $\tilde h(x,z):=\tilde g(x,z)-\tilde m(z)$.
(iv) Compute
\[
\hat\rho:=\frac1n\sum_{i\in\mathcal I_2}\{Y_i-\hat g(X_i,Z_i)+\tilde g(X_i,Z_i)-\tilde m(Z_i)\}\tilde h(X_i,Z_i),
\]
and set $\hat h(x,z):=\operatorname{sgn}(\hat\rho)\tilde h(x,z)$,
2: Form $\hat v$.
(i) Regress $\{Y-\hat g(X,Z)\}^2$ onto $(X,Z)$ using $\mathcal D_2$ to give $\tilde v$.
(ii) Define $a:[0,\infty)\to[0,\infty]$ by
\[
a(c):=\frac1n\sum_{i\in\mathcal I_2}\frac{\{Y_i-\hat g(X_i,Z_i)\}^2}{\max\{\tilde v(X_i,Z_i),0\}+c}.
\]
If $a(0)\le1$, set $\hat c:=0$; otherwise find $\hat c$ by solving $a(c)=1$. Set $\hat v(x,z):=\max\{\tilde v(x,z),0\}+\hat c$.
3: Compute test statistic.
(i) Set $\hat f(x,z):=\hat h(x,z)/\hat v(x,z)$ and regress $\hat f(X,Z)$ onto $Z$ using $\mathcal D_1$, giving $\hat m_{\hat f}$.
(ii) Regress $Y$ onto $Z$ using $\mathcal D_1$ to give $\hat m$.
(iii) For $i\in\mathcal I_1$ set $L_i:=\{Y_i-\hat m(Z_i)\}\{\hat f(X_i,Z_i)-\hat m_{\hat f}(Z_i)\}$ and let
\[
T:=\frac{\frac1{\sqrt n}\sum_{i\in\mathcal I_1}L_i}{\sqrt{\frac1n\sum_{i\in\mathcal I_1}L_i^2-\left(\frac1n\sum_{i\in\mathcal I_1}L_i\right)^2}}.
\]
4: Reject $H_0$ if $T>z_{1-\alpha}$.''',[11],[4,5],[r'\hat f(x,z):=\hat h(x,z)/\hat v(x,z)',r'L_i:=\{Y_i-\hat m(Z_i)\}\{\hat f(X_i,Z_i)-\hat m_{\hat f}(Z_i)\}'],'Full original Algorithm1. Fitshatf onD2 and both residualization regressions onD1; statistic uses empirical variance with divisor n. Spline choices on20 explicitly override defaultvariance/sign steps. Zero-division/sign conventions are archived as ambient source context.','Algorithm 1 — Projected Covariance Measure: single sample split',context=r'Algorithm 1 Projected Covariance Measure: single sample split',phrases=['Algorithm 1'])
add(11,'theoretical version',r'''Input: Data $(X_i,Y_i,Z_i)_{i=1}^{4n}$, significance level $\alpha\in(0,1)$, partition of $[4n]=\mathcal I_1\cup\mathcal I_2\cup\mathcal I_3\cup\mathcal I_4$ into index sets $\mathcal I_1$, $\mathcal I_2$, $\mathcal I_3$ and $\mathcal I_4$, each of size $n$.
Options: Regression methods for each of the regressions.
Define: $\mathcal D_j=(X_i,Y_i,Z_i)_{i\in\mathcal I_j}$ for $j\in[4]$.
Perform Algorithm 1 but in steps 3 (i) and 3 (ii), perform the regressions on $\mathcal D_3$ and $\mathcal D_4$, respectively, instead of on $\mathcal D_1$.''',[17],[4,5,10],[r'\mathcal D_3',r'\mathcal D_4'],'Complete original Algorithm2 modification: mhatf onD3 andmhat onD4. n remains the per-split size. Theorem7 requires separate auxiliary training samples; the source’s allowedD3=D4 relaxation excludes7.','Algorithm 2 — Projected Covariance Measure: theoretical version',context=r'Algorithm 2 Projected Covariance Measure: theoretical version',phrases=['Algorithm 2'])
add(12,'residuals',r'''\[
\varepsilon_{P,i}:=Y_i-m_P(Z_i),\tag{11}
\]''',[17],[6],[r'\varepsilon_{P,i}',r'\varepsilon_P'],'Original response-on-Z residual and its unindexed counterpart as specified after11. Under alternatives it is notY minus the full regressiong; preserve this inAssumption4(a).','Section 4 — Response residual (11)',context=r'In words, the residuals $Y-\mathbb E(Y\mid Z)$ from regressing $Y$ on $Z$ alone are uncorrelated with any square-integrable function of $X$ and $Z$.',context_page=4)
add(13,'population residual',r'''\[
\xi_{P,i}:=\hat f(X_i,Z_i)-m_{P,\hat f}(Z_i),\tag{11}
\]
for $i\in[n]$, and an analogous version of (11) without a subscript $i$.''',[17],[9],[r'\xi_{P,i}',r'\xi_P'],'Original population-residualized learned projection, distinct from the fitted residualhatf-hatm_hatf used inL_i. Suppliedhatf is learned on independentD2 by the selected algorithm.','Section 4 — Projection residual (11)',context=r'we now ask in part (d) of Theorem 5 for $\xi_P$, the population residual from regressing our estimated projection $\hat f$ onto $Z$, to be positively correlated with $h_P$ with high probability',context_page=20)
add(14,'variance',r'''\[
\sigma_P^2:=\operatorname{Var}_P(\xi_P\mid\hat f),\tag{12}
\]''',[17],[4,13],[r'\sigma_P^2'],'Original random conditional variance of the population projection residual. It may shrink to zero; Theorem4(a) excludes exact zero with asymptotically high probability.','Section 4 — Projection variance (12)',context=r'The second MSPE $\mathcal E_{P,2}$ in the display above is normalised by the variance of the errors $\xi_{P,i}$ featuring in the corresponding regression.')
add(15,'mean squared prediction error (MSPE)',r'''\[
\mathcal E_{P,1}:=\frac1n\sum_{i=1}^n\{m_P(Z_i)-\hat m(Z_i)\}^2\tag{13}
\]''',[17],[6],[r'\mathcal E_{P,1}'],'Original response-regression MSPE onD1 evaluation points. hatm is a supplied estimator whose training set isD1 inAlgorithm1 andD4 inAlgorithm2.','Section 4 — Response MSPE (13)',context=r'Importantly, the bias term can then be controlled by a product of the mean squared prediction error (MSPE) of $\hat m$,',context_page=8)
add(16,'second MSPE',r'''\[
\mathcal E_{P,2}:=\frac1{n\sigma_P^2}\sum_{i=1}^n\{m_{P,\hat f}(Z_i)-\hat m_{\hat f}(Z_i)\}^2.\tag{13}
\]''',[17],[9,14],[r'\mathcal E_{P,2}'],'Original normalized projection-regression MSPE, retaining divisor sigma_P². Fittedhatm_hatf is supplied by the selected method and training split; not the population targetmP,hatf.','Section 4 — Normalized projection MSPE (13)',context=r'The second MSPE $\mathcal E_{P,2}$ in the display above is normalised by the variance of the errors $\xi_{P,i}$ featuring in the corresponding regression.')
add(17,'Assumption 3',r'''Assume that the class of distributions $\mathcal P$ of $(X,Y,Z)$ on $\mathcal X\times\mathbb R\times\mathcal Z$ satisfies:
(a) $\mathcal E_{P,1}=o_{\mathcal P}(1)$, $\mathcal E_{P,2}=o_{\mathcal P}(1)$ and their product satisfies $\mathcal E_{P,1}\mathcal E_{P,2}=o_{\mathcal P}(n^{-1})$.
(b) The weighted MSPE satisfies
\[
\frac1{n\sigma_P^2}\sum_{i=1}^n\{m_P(Z_i)-\hat m(Z_i)\}^2\xi_{P,i}^2=o_{\mathcal P}(1).
\]
(c) There exists $C>0$ such that $\sup_{P\in\mathcal P}\operatorname{Var}_P(Y\mid X,Z)\le C$.''',[17],[3,13,14,15,16],[r'\mathcal E_{P,1}\mathcal E_{P,2}',r'\xi_{P,i}^2'],'Complete original predictive-error assumption, with the normalized product and weighted error, and conditional variance bound. It is directly assumed by4/5;6/7 replace it by their own spline assumptions rather than inheriting it as a new hypothesis.','Assumption 3',kind='assumption',context=r'Assumption 3.',phrases=['Assumption 3'])
add(18,'sufficiently stable',r'''To this end, we say that $\hat m$ is sufficiently stable if conditions (ii) and (iii) of Proposition S15 in Section S2 hold.''',[18],[],[],'Original stability definition is solely an external-to-main-text reference. Preserve its two clause numbers; do not invent the supplementary conditions or treat stability as verified for arbitrary learners.','Section 4.1 — Stability reference',kind='condition',phrases=['sufficiently stable'])
add(19,'tensor product B-spline bases',r'''Throughout this section, we assume that $(X,Z)\in[0,1]^{d_X}\times[0,1]^{d_Z}$ and set $d:=d_X+d_Z$. In Section S4, we give a self-contained description of spline spaces and their tensor product B-spline bases, containing all the results that we require for our analysis. Given a spline order $r\in\mathbb N$ (i.e. degree $r-1$) and $N\in\mathbb N_0$ equi-spaced interior knots in each dimension, we denote by $\mathcal S^{d_Z}_{r,N}$ the corresponding spline space on $[0,1]^{d_Z}$, and by $\phi^Z$ its $d_Z$-tensor B-spline basis, which consists of $K_Z:=(N+r)^{d_Z}$ basis functions. Writing $\mathcal S^{d_X}_{r,N}$ for the corresponding spline space on $[0,1]^{d_X}$ with $d_X$-tensor B-spline basis $\phi^X$, having $K_X:=(N+r)^{d_X}$ basis functions, we can define the $d$-tensor product basis $\phi(x,z):=\phi^X(x)\otimes\phi^Z(z)$ for $\mathcal S^d_{r,N}$, where $u\otimes v:=\operatorname{vec}(uv^\top)$, having $K_{XZ}:=K_XK_Z$ basis functions. Further, we let $\psi$ denote the tensor product B-spline basis for $\mathcal S^{d_Z}_{2r-1,N}$, and write $\tilde K_Z:=(N+2r-1)^{d_Z}$; the higher order of the spline basis functions that make up $\psi$ affords better approximation properties that turn out to be useful for our theory.''',[20],[],[r'\phi(x,z)',r'K_{XZ}',r'\tilde K_Z'],'Original spline spaces and dimensions, order versus degree, common equispaced knots and source vectorization order. Precise endpoint conventions are deferred to excluded Section S4.','Section 5 — Spline spaces and bases')
add(20,'spline regressions',r'''In what follows, when we write that a variable is regressed on a spline basis, we mean that OLS is used for the regression. In Theorems 6 and 7 below, we use the terminology that $T$ is computed using spline regressions if the regressions (following the notation of Algorithm 1) are as follows:
• $\hat v\equiv1$ for simplicity;
• $\hat g$ is formed by regressing $Y$ onto $\phi(X,Z)$;
• $\tilde m$ is formed by regressing $\hat g(X,Z)$ onto $\phi^Z(Z)$, or equivalently by regressing $Y$ onto $\phi^Z(Z)$;
• $\hat m_{\hat f}$ and $\hat m$ are formed by regressing $\hat f(X,Z)$ and $Y$, respectively, on $\psi(Z)$.
In addition, we also omit discussion of the sign correction step (Algorithm 1, Step 1(iv)), since $\hat\rho$ is always non-negative for the estimators given above.''',[20],[10,19],[r'\hat v\equiv1'],'Original OLS specialization of the selected algorithm. The variance learner is replaced by the constant one and sign correction omitted. The source retains different bases for the projection and the final two regressions.','Section 5 — Spline regressions',phrases=['spline regressions'])
add(21,'Hölder spaces',r'''We start by stating our main distributional assumptions, which rely on the definitions of Hölder spaces $\mathcal H^d_s$ and Hölder norms $\|\cdot\|_{\mathcal H_s}$ given in Definition S24.''',[21],[],[r'\mathcal H^d_s',r'\|\cdot\|_{\mathcal H_s}'],'Original reference to supplemental Definition S24. The main text names the spaces and norms but does not specify their precise derivative and integer-smoothness conventions; retain this unresolved reference.','Section 5.1 — Hölder space reference',kind='source_passage')
add(22,'Assumption 4',r'''Let $\mathcal P$ be a class of distributions of $(X,Y,Z)$ on $[0,1]^{d_X}\times\mathbb R\times[0,1]^{d_Z}$, and for $P\in\mathcal P$, let $g_P(x,z):=\mathbb E_P(Y\mid X=x,Z=z)$. Assume that there exist $C\ge1$ and $c\in(0,1]$ with the following properties:
(a) For each $P\in\mathcal P$, we have $\mathbb E_P(\varepsilon_P^2\mid X,Z)\ge c$ and there exists $\delta\in(0,2]$ such that $\mathbb E_P(|\varepsilon_P|^{2+\delta}\mid X,Z)\le C$.
(b) For each $P\in\mathcal P$, the marginal distribution of $(X,Z)$ is absolutely continuous with respect to Lebesgue measure on $[0,1]^d$, with density $p_P$ satisfying $\sup_{(x,z)\in[0,1]^d}p_P(x,z)\le C$ and $\inf_{(x,z)\in[0,1]^d}p_P(x,z)\ge c$.
(c) Let $s\in(0,r]$ and let $p_{X\mid Z,P}(\cdot\mid z)$ denote the conditional density of $X$ given $Z=z$. Assume that for all $P\in\mathcal P$, we have $p_{X\mid Z,P}(x\mid\cdot)\in \mathcal H^{d_Z}_s$ for all $x\in[0,1]^{d_X}$, and that $m_P\in \mathcal H^{d_Z}_s$ and $g_P\in \mathcal H^d_s$, with
\[
\max\left\{\sup_{x\in[0,1]^{d_X}}\|p_{X\mid Z,P}(x,\cdot)\|_{\mathcal H_s},\|m_P\|_{\mathcal H_s},\|g_P\|_{\mathcal H_s}\right\}\le C.
\]''',[21],[6,7,12,19,21],[r'\mathbb E_P(\varepsilon_P^2\mid X,Z)',r'p_{X\mid Z,P}(x\mid\cdot)'],'Complete original assumption. The response residual is Y minus m_P(Z), not Y minus g_P(X,Z). Preserve the printed quantifier order for delta and the conditional density smoothness direction.','Assumption 4',kind='assumption',context=r'Assumption 4.',phrases=['Assumption 4'])
add(23,'projection',r'''In order to state our Type I error control result for spline regressions, it will be convenient to define the projection $\Pi:\mathbb R^{K_{XZ}}\to\mathbb R^{K_{XZ}}$ by $\Pi(x)\equiv\Pi(x_1,\ldots,x_{K_{XZ}}):=x-\mathbf1\otimes\bar x$, with $\bar x=(\bar x_1,\ldots,\bar x_{K_Z})$ given by $\bar x_k:=K_X^{-1}\sum_{\ell=1}^{K_X}x_{(k-1)K_X+\ell}$ for $k\in[K_Z]$.''',[21],[19],[r'\Pi(x)',r'\Pi x=x'],'Original projection subtracting within-block coefficient means, using the source tensor ordering. Theorem 6 uses a restricted Rayleigh minimum on its fixed-point space, not the full minimum eigenvalue.','Section 5.1 — Coefficient projection')
add(24,'coefficients',r'''Let $\hat\beta_{XZ}\in\mathbb R^{K_{XZ}}$ denote the coefficients obtained when forming the $\hat g$ regression and similarly let $\hat\beta_Z\in\mathbb R^{K_Z}$ denote the coefficients from the $\tilde m$ regression. Using the fact that $\phi^X$ forms a partition of unity (Proposition S23(a)), it follows that if we write $\hat\beta:=\hat\beta_{XZ}-\mathbf1\otimes\hat\beta_Z$, where $\mathbf1\in\mathbb R^{K_X}$ denotes a vector of ones, then $\hat f(x,z)=\hat\beta^\top\phi(x,z)$.''',[21],[19,20],[r'\hat\beta:=\hat\beta_{XZ}-\mathbf1\otimes\hat\beta_Z',r'\Pi\hat\beta'],'Original coefficient contrast and learned spline projection identity. The source states the partition-of-unity implication here; the supplemental proof has not been imported.','Section 5.1 — Regression coefficients')
add(25,'scale equivariant',r'''$\hat m_{\hat f}$ is scale equivariant in the sense that $\hat m_{a\cdot\hat f}(Z)=a\cdot\hat m_{\hat f}(Z)$ for all $a>0$;''',[19],[],[r'\hat m_{a\cdot\hat f}(Z)=a\cdot\hat m_{\hat f}(Z)'],'Original positive-scale equivariance of the fitted regression method. This is a condition on a supplied learner, not a definition of its population target or a claim about all methods.','Theorem 5(a)',kind='theorem_excerpt')
add(26,'linear smoother',r'''$T$ is computed using Algorithm 1 and $\hat m$ is a linear smoother;''',[18],[10],[],'Original alternative (iii) of Theorem 4. The main text names a linear smoother and gives spline examples; do not add an unstated formal representation as an original quotation.','Theorem 4(iii)',kind='theorem_excerpt',phrases=['linear smoother'])
add(27,'conditional independence',r'''It is interesting to compare this to the conditional independence null $Y\perp\!\!\!\perp X\mid Z$, which has attracted much attention in recent years. The latter asks not just for the regression function to be expressed as a function of $Z$ alone, but in fact for the entire conditional distribution of $Y$ given $(X,Z)$ to equal the conditional distribution of $Y$ given $Z$.''',[2],[],[],'Original full conditional-distribution independence, stronger than conditional mean independence. Required only by branch (ii) of Theorem 4, not its other alternatives or the power results.','Introduction — Conditional independence',phrases=['conditional independence'])
def main():
    r=json.loads((REVIEW_ROOT/'inventory-review.json').read_text());assert r['status']=='complete' and r['source_checked']
    assert hashlib.sha256((ROOT/'theorem-inventory.json').read_bytes()).hexdigest()==r['inventory_sha256']
    assert len(interfaces)==len(members)==27
    for x in interfaces:
        m=x['members'][0];assert set(m['depends_on'])<=set(members)
        assert any(v in m['statement_original']+' '+m['local_label'] for v in m['highlight_symbols']+m['highlight_phrases'])
    (ROOT/'source-passages.json').write_text(json.dumps(dict(paper_id=PID,members=list(members.values())),indent=2,ensure_ascii=False)+'\n')
    (ROOT/'interface-extraction.json').write_text(json.dumps(dict(paper_id=PID,interfaces=interfaces),indent=2,ensure_ascii=False)+'\n')
    print('Saved 27 original source entries; full review remains pending.')
if __name__=='__main__':main()
