"""Retain source-local invariance definitions, scope and unresolved notation separately."""
import json
from save_inventory import ROOT,PID

def main():
    aux=[]
    def add(n,s,pages,note,deps=()):aux.append(dict(local_id='A'+str(n),statement_original=s,evidence=[dict(page=p,location='Original main-text context A'+str(n),**({'before_main_text_end':True} if p==20 else {})) for p in pages],scope_note=note,depends_on=list(deps)))
    add(1,r'''A variable set $S\subseteq[p]$ is conditional expectation invariant (CE-invariant) across environments $\mathcal E$ if there exists some $\boldsymbol\beta$ with support set $S$ such that
\[
\forall e\in\mathcal E,\quad\mathbb E[y^{(e)}\mid\mathbf x_S^{(e)}]=\boldsymbol\beta_S^\top\mathbf x_S^{(e)}.
\]
(2.4)''',[7],'Definition2.1. Preserve exact support S and common coefficient across environments. Theorems use the model class explicitly; CE-invariance is contextual terminology, not an additional assumed equivalence with LLS-invariance.')
    add(2,r'''We say a variable set $S\subseteq[p]$ is linear least squares invariant (LLS-invariant) across environments $\mathcal E$ if there exists some $\boldsymbol\beta$ with support set $S$ such that
\[
\forall e\in\mathcal E,\quad\boldsymbol\beta\in\underset{\operatorname{supp}(\boldsymbol\beta)\subseteq S}{\operatorname{argmin}}\mathbb E[|y^{(e)}-\boldsymbol\beta^\top\mathbf x^{(e)}|^2].
\]
(3.3)''',[10],'Definition3.1. The witness has support exactly S, while the minimization domain allows smaller supports. The source reuses beta for witness and optimization binder; retained.',['D4'])
    add(3,r'''LLS-invariance is weaker than CE-invariance because the CE-invariance of $S^\star$ implies the LLS-invariance of $S^\star$ while the converse is false. In this paper, we only leverage linear information to facilitate LLS-invariance on the solution we find.''',[10],'Do not rewrite the focused linear moment condition as full conditional-expectation invariance.')
    add(4,r'''To simplify the presentation, we consider the case of balanced data with equal weights, that is, $n^{(e)}\equiv n$ and $\omega^{(e)}\equiv1/|\mathcal E|$, and defer the results of varying $(n^{(e)},\omega^{(e)})$ to Appendix A.''',[11],'Standing scope of all Section4 theorem statements. General method definitions retain varying n^(e) and weights; appendix extensions are excluded.',['D6','D26'])
    add(5,r'''We focus on the centered covariate case that $\mathbb E[\mathbf x^{(e)}]=0$, and it can be easily generalized to the non-centered counterpart.''',[12],'Source’s centered-covariate scope makes the raw second-moment matrices covariances. Noncentered extension is not a separate audited theorem.',['D3'])
    add(6,r'''We first examine the population EILLS loss (3.8) when $G\ne\varnothing$. Specifically, we show that with a large enough $\gamma$, the population EILLS loss satisfies certain strong convexity with respect to $\boldsymbol\beta^*$ under the following identification condition.''',[12],'Preceding scope of T4.2. Empty-G critical supremum and later minimum conventions are not supplied explicitly.',['D12','D18'])
    add(7,r'''Here we refer to $b_S$ as bias mean because $b_S$ is the bias of running least squares on $\mathbf X_S$ using all the data when $S\supseteq S^*$, that is, $\|\widehat{\boldsymbol\beta}_{R,S}-\boldsymbol\beta^*\|_2^2\asymp b_S$ by Proposition 4.1.''',[13],'Remark4.2 labels b_S; its coefficient-bias interpretation assumes S contains the true support. The definition b_S in T4.2 itself is over every relevant S.',['D20'])
    add(8,r'''Currently, we use an algorithm whose computational complexity scales exponentially with $p$ to search for the global minima of the EILLS objective function.''',[20],'Theorems concern global minimizers. The paper does not establish polynomial-time optimization under its statistical assumptions.',['D11'])
    add(9,r'''One is expected to derive theoretical results analogous to Theorem 4.2–4.5; we leave this for future studies.''',[20],'Section6.1 nonlinear/generalized-linear extension is future work. Do not count it as another theorem or extend the linear results to it.')
    add(10,r'''We use $\operatorname{supp}(\mathbf x)=\{j\in[d]:x_j\ne0\}$ to denote the support set of the vector $\mathbf x$.''',[7],'Coordinate support, with complements taken within the ambient coordinate index set. The l0 penalty counts nonzero coordinates.')
    add(11,r'''In the well-conditioned regime where $\min_{j\in S^*}|\beta_j^*|\gtrsim p^{-1/2}$, $\kappa_L\gtrsim1$, and $\gamma^*\asymp1$, one can adopt a constant-level hyper-parameter $\gamma$ such that
\[
\|\widehat{\boldsymbol\beta}_Q-\boldsymbol\beta^*\|_2\lesssim\sqrt{\frac p{n\cdot|\mathcal E|}}+\frac pn
\]
with high probability provided $n\gtrsim p$.''',[15],'Simplified regime after T4.4; does not replace the complete finite-sample bound or its beta-min term.',['D11','D22'])
    add(12,r'''With the variable selection consistency given in Theorem 4.5, we can then attain the optimal $\ell_2$-rate by running the least squares on $\operatorname{supp}(\widehat{\boldsymbol\beta}_L)$, as if assisted by an oracle.''',[16],'Post-selection least-squares refitting is a separate operation. T4.5 itself concludes exact support recovery for the penalized minimizer.',['D13'])
    issues=[]
    def issue(i,pages,note):issues.append(dict(issue_id=i,evidence=[dict(page=p,location='Source scope or notation issue',**({'before_main_text_end':True} if p==20 else {})) for p in pages],note=note))
    issue('population-loss-typo',[8,11],'Equation(3.8) prints y^(e)−x^T x^(e) in R(beta;gamma,omega), rather than the beta^T x^(e) of the earlier environment risk (2.5) and empirical risk. Preserve the printed x in the original passage and record the source-backed intended interpretation separately.')
    issue('balanced-sampling',[10,11],'General objective definitions allow unequal counts and positive weights, but all main-text Section4 theorems use equal n and uniform weights. Unequal-weight/count results are deferred to AppendixA and were not read.')
    issue('pooled-whitening',[8,11,12],'Sigma^(e) and its empirical version are raw second moments. Centering is a standing convention. Condition4.3 uses pooled Sigma^-1/2, not environment-specific whitening.')
    issue('focused-support-gate',[9,10,11,19],'The objective gates its moment penalty on beta_j≠0; it is generally nonconvex. T4.2’s lower bound relative to beta* is not a global pairwise convexity claim despite the theorem title. Empirical squared means also differ from means of squared products.')
    issue('global-minimizers',[11,20],'Theorems apply to global minimizers. Gumbel approximations and tuning guidance are deferred to appendices, and Section6.2 states exponential computational complexity for the current global search. No guarantee for generic stationary points is inferred.')
    issue('empty-support-and-empty-g',[6,12,13,14,15,16],'Section4.2 explicitly treats G nonempty. The supremum defining gamma*, the minimum defining s_-, beta_min and s_+, and log(|E||S*|) require nonempty families/supports or conventions not given in the main text. Keep these domains explicit without inventing values for empty minima.')
    issue('pooled-spuriousness',[12,13,14],'G is defined by a sum of residual correlations across environments, which may cancel. It is not the union of individually endogenous variables. Condition4.5 quantifies over all S meeting G, with the differentiating environment pair allowed to depend on S.')
    issue('screening-versus-exact-selection',[14,15,16],'T4.3 only yields S*⊆supp(beta-hat_Q)⊆G^c and can retain irrelevant exogenous variables. T4.5 yields equality for the l0-penalized estimator. Refitting after selection is separately described and is not the estimator in the theorem.')
    issue('conditional-improved-bound',[14,15],'T4.4 first gives a p-dimensional bound with probability 1−7e^-t. Only its moreover branch imports the extra T4.3 sample bounds and gives the |G^c| bound with probability 1−14e^-t. Neither branch is silently discarded or made an unconditional conjunction.')
    issue('source-constants-and-stars',[13,15,16],'T4.4 names c1–c4 although c4 does not appear in its formulas. T4.5 prints both s^star and s^* for the same sparsity count in epsilon(n). Preserve these source forms and do not invent another parameter or missing c4 term.')
    issue('penalty-feasibility',[15,16],'Condition4.6 gives two sample bounds, while T4.5 additionally requires a nonempty lambda interval with a two-term epsilon(n). Preserve all terms and the upper bound c2 kappa_L beta_min²; simplified asymptotic lambda ranges following the theorem are not substitutes.')
    issue('conditional-mean-versus-linear-invariance',[6,7,10],'The model has common conditional expectation only on S*, allowing residual dependence on other covariates. The focused linear conditions imply LLS-invariance rather than CE-invariance in general. No SCM, full exogeneity, conditional sub-Gaussian tail or residual independence is added.')
    refs=[dict(from_claim_id=PID+'/T'+n,to_source_label='Theorem 4.2, equation (4.5)',reference_kind='definition_reference',scope='Import the definition of gamma*, b_S and dbar_S, not an additional assumption of the theorem conclusion.') for n in ['4.3','4.4','4.5']]
    refs.append(dict(from_claim_id=PID+'/T4.4',to_source_label='Theorem 4.3',reference_kind='assumption_reference',scope='Additional per-environment and total-sample conditions only in the moreover branch (4.11).'))
    refs.append(dict(from_claim_id=PID+'/T4.3',to_source_label='Appendix C.3 and Lemma C.4',reference_kind='proof_only',scope='Main-text discussion names the localization proof; appendix body excluded. The same discussion also concerns T4.4 and T4.5.'))
    bindings={
'T4.2':'Conditions4.1,4.2,4.5 only; C4.3–4.4 tails are not required. Balanced model, centered covariance context, and preceding G≠empty scope. Q is the population objective with the printed typo noted. Gamma* and b_S,dbar_S,beta-bar^(S) are defined in the theorem. Epsilon∈(0,1), gamma≥epsilon^-1 gamma*, and the pointwise lower bound in beta are preserved; no pairwise global convexity is inferred.',
'T4.3':'Conditions4.1–4.5; gamma≥max(3gamma*,1). Both independent sample bounds are retained with signals s_+,s_-. The estimator is the global empirical Qhat minimizer. The event retains S* and excludes G, but need not equal S*. Constants depend only on kappa_U,sigma_x,sigma_epsilon; t>0 is a confidence parameter.',
'T4.4':'Conditions4.1–4.5; same gamma threshold, n≥p+log(2|E|)+t and n|E|≥c1(gamma/kappa_L)(p+t). Preserve the complete three-term first bound, including sqrt(|S*|)/n and beta-min denominator, at 1−7e^-t. Only the moreover clause additionally assumes T4.3’s sample bounds and replaces p by |G^c| at 1−14e^-t. Its c1–c4 wording is retained though c4 is unused.',
'T4.5':'Conditions4.1–4.6; s*=|S*| and beta_min come from Section4.4. Gamma threshold references T4.2’s definition only. Lambda is between c1[(gamma/kappa_L)^2 s*log p/(n|E|)+epsilon(n)] and c2 kappa_L beta_min², with both terms of epsilon(n) retained. The global penalized Lhat minimizer has exact support recovery at 1−p^-10. No T4.3 screening-signal requirement or post-selection refit is added.'}
    out=dict(paper_id=PID,status='extracted',unranked_auxiliary_passages=aux,source_issues=issues,source_claim_references=refs,statement_local_bindings=bindings,ambient_prerequisites=['Finite environment set E, p-dimensional vectors and coordinate subsets, coordinate support and l0 cardinality, Euclidean norm and spectral norm, Loewner order, positive-definite square roots, gradients, expectation and conditional expectation.','n is the per-environment count, n|E| is the total count, and omega is uniform in all four theorem statements. True beta* and S*=supp(beta*) are common to every environment.','The source class uses sigma² for variance/second-moment bounds, sigma_x for covariate tails and sigma_epsilon for residual tails; these are distinct parameters. Lambda in the residual moment-generating function is a bound dummy variable, not the estimator’s penalty parameter.','Constants are universal subject to the dependencies stated in each theorem. A chosen lambda must satisfy both displayed endpoints; confidence levels and nonempty-support issues are preserved.'],extraction_policy='All four complete main-text Theorems. Definitions, assumptions and theorem excerpts preserve source kinds and scope. Appendix bodies, mathlib search, nonlinear extensions and proof certification excluded.')
    (ROOT/'ambient-prerequisites.json').write_text(json.dumps(out,indent=2,ensure_ascii=False)+'\n')
if __name__=='__main__':main()
