"""Archive main-text notation, scope conventions and unresolved source wording."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];PID=ROOT.name
aux=[]
def add(aid,text,pages,loc,meaning):
    aux.append(dict(auxiliary_id=aid,statement_original=text.strip(),evidence=[dict(page=p,location=loc) for p in pages],resolution=meaning))
add('A1',r'''
For a function $f:\mathbb R^p\to\mathbb R$, we define $\boldsymbol f=(f(\boldsymbol x_1),\ldots,f(\boldsymbol x_n))^\top$ to be the $n\times1$ vector of $f$ evaluated at the design points $\boldsymbol X=(\boldsymbol x_1,\ldots,\boldsymbol x_n)^\top\in\mathbb R^{n\times p}$. Likewise, we use $\widehat{\boldsymbol\mu}(T_K)$ to denote the $n\times1$ vector of fitted values of $\widehat\mu(T_K)$. For functions $f,g\in\mathcal L_2(P_{\boldsymbol x})$, let $\|f\|^2=\int_{\mathcal X}(f(\boldsymbol x))^2dP_{\boldsymbol x}(\boldsymbol x)$ be the squared $\mathcal L_2(P_{\boldsymbol x})$ norm and let $\|\boldsymbol f\|_n^2=\frac1n\sum_{i=1}^n(f(\boldsymbol x_i))^2$ denote the squared norm with respect to the empirical measure on the data. Let $\langle\boldsymbol f,\boldsymbol g\rangle_n=\frac1n\sum_{i=1}^nf(\boldsymbol x_i)g(\boldsymbol x_i)$ denote the inner product with respect to the empirical measure on the data. The response data vector $\boldsymbol y=(y_1,\ldots,y_n)^\top\in\mathbb R^n$ is viewed as a relation, defined on the design matrix $\boldsymbol X$, that associates $\boldsymbol x_i$ with $y_i$. Thus, for example, $\|\boldsymbol y-\boldsymbol f\|_n^2=\frac1n\sum_{i=1}^n(y_i-f(\boldsymbol x_i))^2$ and $\langle\boldsymbol y,\boldsymbol f\rangle_n=\frac1n\sum_{i=1}^ny_if(\boldsymbol x_i)$. We use $[T]$ to denote the collection of internal (non-terminal) nodes and $\{t:t\in T\}$ to denote the terminal nodes of the tree. The cardinality of a set $A$ is denoted by $|A|$.
''',[6],'Section 2.1 — norms, fitted vectors and node notation','Population L2 risk is distinct from the empirical squared error used by pruning. Brackets [T] select internal nodes, whereas t in T selects terminal nodes. These standard primitives are preserved locally without increasing the interface inventory.')
add('A2',r'''Throughout the paper, we use $\mathbb E$ to denote the expectation with respect to the joint distribution of the (possibly random) search spaces $\{\mathcal A_t:t\in[T_K]\}$ and the data.''',[10],'Section 2.4 — expectation convention','The outer risk expectation and split-probability expectation average the data and search mechanism. P_A_t itself is conditional on data as specified in D3.')
add('A3',r'''For this result to be non-vacuous, the only additional assumption needed is that the largest of the reciprocal probabilities, $P_{\mathcal A_t}^{-1}(\kappa)$, are integrable with respect to the data and (possibly random) search spaces. A simple sufficient condition is that the splitting probabilities are almost surely bounded away from zero, which we record in the following assumption for future reference.''',[10],'After Lemma 2 — finiteness discussion','This paragraph motivates Assumption 1. It does not make Assumption 1 an unprinted hypothesis of Theorems 1 and 5, whose expressions retain the reciprocal probability expectation.')
add('A4',r'''Consistency of oblique trees follows from Theorem 1 under the additional assumption that the splitting probabilities are bounded away from zero (Assumption 1) and that the depth $K$ grows appropriately with the sample size.''',[12],'Before Corollary 2 — additional assumptions','Assumption 1 and depth-growth conditions belong to the corollaries. The census includes only the printed Theorems and does not import these additional hypotheses.')
add('A5',r'''It should be noted that the expectation in the second term of the bound in Theorem 5 is over the subsampled data (instead of over the entire data set as in Theorem 1).''',[17],'After Theorem 5 — subsampling expectation','The effective sample size in the forest bound is N. Candidate success probabilities and the tree in its oracle term are evaluated with respect to the subsample, not the full n observations.')
add('A6',r'''However, this alone is not enough to validate Assumption 3 because $q$ may depend on the sample size through its dependence on the depth $K=K_n$. Hence, it is important that (12) hold for the same $q$ uniformly over all depths.''',[14],'After Assumption 3 — uniform exponent','The exponent q cannot be selected anew for each tree depth in the fast-rate result.')
add('A7',r'''As mentioned earlier, we see from (15) that $A=A_n$ (as well as $V=V_n$) is allowed to grow poly-logarithmically without affecting the convergence rate.''',[16],'After Theorem 4 — sample-size dependent bounds','A and V may vary with n as discussed, while the all-depth quantifiers in the assumptions are retained. This rate interpretation does not rewrite Theorem 4 into a new asymptotic theorem.')
add('A8',r'''In particular, note that $\gamma=1$ for sub-Exponential data, $\gamma=2$ for sub-Gaussian data, and $\gamma=\infty$ for bounded data.''',[12],'Before Theorem 1 — tail exponent interpretation','The bounded-response convention takes 4/gamma as zero. The source describes gamma infinity separately from the positive-constant wording of Assumption 2; its threshold exponent at infinity is not fully defined.')
add('A9',r'''For a fixed $\lambda$, the optimal subtree $T_{opt}$ can be found efficiently by weakest link pruning, i.e., by successively collapsing the internal node that decreases $\|\boldsymbol y-\widehat{\boldsymbol\mu}(T)\|_n^2$ the most, until we arrive at the single-node tree consisting of the root node.''',[11],'Section 2.5 — weakest link description','Collapsing least-squares terminal nodes cannot decrease their unpenalized training error. This printed algorithm description is archived as a discrepancy; the estimator in the census retains the explicit optimization (8).')
add('A10',r'''However, one can aggregate the data in each node in a number of ways, depending on the form of the target estimand. In the most general setting, under weak assumptions, all of our forthcoming theory holds when the node output is the result of a least squares projection onto the linear span of a finite dictionary $\mathcal H$ that includes the constant function (e.g., polynomials, splines), that is, $\widehat y_t\in\operatorname*{argmin}_{h\in\operatorname{span}(\mathcal H)}\sum_{\boldsymbol x_i\in t}(y_i-h(\boldsymbol x_i))^2$.''',[3],'After equation (2) — possible general node outputs','The main text mentions a broader finite-dictionary extension without specifying all weak assumptions here. The stored theorem statements use the concrete canonical mean output (2); this extension is archived without inserting arbitrary H into their hypotheses.')
add('A11',r'''While Lemma 1 below focuses on the special case of constant fit at the terminal nodes for concreteness, all proofs in Appendix A are given in full generality. To be more precise, our results in the appendix allow for any finite-dimensional least squares fit at the terminal nodes, and thus give a general orthogonal tree expansion in the function space for adaptive oblique decision trees, covering canonical adaptive axis-aligned decision trees as a special case.''',[8],'Section 2.3 — scope of generalization','This is a main-text notice of appendix generality. No appendix content or proof-only orthonormal stump construction is needed to state the three retained Theorems.')
add('A12',r'''By slightly expanding the notion of an internal node to include the empty node (i.e., the empty set), we define $\psi_t(\boldsymbol x)\equiv1$ if $t$ is the empty node, in which case the tree outputs the grand mean of all the response values.''',[8,9],'Section 2.3 — empty-node convention','The orthogonal expansion introduces a formal empty internal node to represent the intercept. This is relevant to the scope of [T], although the proof-only basis itself is not a new theorem dependency. The source does not define its split-success probability.')
issues=[]
def issue(i,pages,location,detail):issues.append(dict(id=i,evidence=[dict(page=p,location=location) for p in pages],detail=detail))
issue('source_version',[1],'Cover and arXiv stamp','The pinned source is arXiv:2210.14429v2, stamped 30 August 2023 with cover date 1 September 2023. Equality to the 2024 journal typesetting has not been established.')
issue('finite_norm_notation',[5,6],'Library G and finite additive norm','Section 2.1 prints h(x)=sum h_k(x), then sums V(h_k,a_k,t), with directions a_k not bound in that displayed expansion and the node t suppressed in the norm notation. The following relaxed norm uses ridge expansions explicitly. The source passages are kept intact. The dependency graph uses the finite-sum construction for the finite library before the closure/relaxed-norm construction; this is an interpretation of the source staging, not a claim that the notation is fully unambiguous.')
issue('variation_not_a_norm_without_quotient',[6],'Total variation and closure','The source calls these functionals norms. Constant functions have zero variation, so they are seminorms unless an additional quotient or normalization is intended. No such change is made to the source definitions. F is an L2 closure, and finite relaxed variation for every member is not explicitly asserted.')
issue('partition_indexing',[6],'Definition of V','The text defines |A| as cardinality, but writes a partition P={z_0,...,z_|P|}, containing |P|+1 points. The sum and indexing are preserved rather than silently renumbered.')
issue('projection_endpoints',[6],'Interval I(a,t)','The projection interval uses min/max even though tree cells can be relatively open or unbounded. Infinite endpoints are explicitly allowed, but endpoint evaluation of h and finite unattained extrema are not given conventions. No replacement by infimum/supremum or truncation is inserted into the quotation.')
issue('pruning_smallest_comparison',[11],'Explanation after equation (8)','The printed smallest-minimizer explanation says T_opt precedes every pruned subtree, without limiting the comparison to minimizing subtrees. The optimization definition and this wording are retained; the natural minimizing-subtrees interpretation is not substituted into the original.')
issue('weakest_link_direction',[11],'Weakest link algorithm prose','The statement that collapsing a node decreases unpenalized empirical squared error conflicts with least-squares node means. This is not used as a replacement for the explicit penalized optimization defining T_opt.')
issue('all_depths_node_bound',[3,15],'Stopping rule and Assumption 4','Assumption 4 quantifies over every K>=1 with a fixed finite A at a given n. Under the printed finite-sample stopping rule, a nonempty sample always leaves a terminal node with at least one observation, whereas An/2^K tends to zero. Thus the literal unlimited-depth quantifier needs clarification if the same stopped tree family is used for arbitrarily large K. The source is not silently restricted to feasible depths.')
issue('split_degeneracy',[3,7],'Split criterion and candidate search','Node means require nonempty children, but the displayed optimization permits all real b and all candidate directions. Candidate nonemptiness, tie selection, and empty-child handling are not explicitly specified. The source finite-values argument establishes attainment only once the criterion and admissible splits are defined.')
issue('empty_internal_nodes_and_zero_probability',[3,7,8,9,10,12],'Oracle inverse probabilities','A tree stopped at its root has no ordinary internal nodes. Section 2.3 adds a formal empty node for the orthogonal expansion, but does not specify a search set or split-success probability for it, nor explicitly state whether that augmentation applies to the oracle maximum. Thus either a maximum-over-empty convention or a formal-node probability convention needs clarification. Zero success probability also requires an extended-real reciprocal, possibly multiplied by zero variation. The separate non-vacuous integrability discussion does not impose Assumption 1 on Theorems 1 or 5.')
issue('sparsity_and_logarithm_domain',[7,12,17],'Sparsity bound and oracle logarithms','Section 2.2 declares d to be a positive integer bounding the number of nonzero coordinates. It does not explicitly add d<=p, although choosing an effective bound no larger than p is natural. The logarithmic terms and tiny sample sizes also need boundary conventions (n=1 or N=1 can make complexity terms zero). These parameter restrictions are not invented.')
issue('gamma_infinity',[11,12],'Assumption 2 and bounded-data convention','The positive-constant statement for gamma is followed by the separate gamma=infinity convention for bounded responses. The meaning of B^infinity at boundary thresholds is not stated; the natural 4/gamma=0 interpretation of risk exponents is recorded separately.')
issue('forest_randomization',[16,17],'Forest construction','The text states without-replacement subsampling and independent copies of Theta, with all trees sharing the original sample. Independence is therefore read conditionally on that sample. The subsampling law is not further specified in the defining paragraph; uniform selection independent of observed values is conventional but is not inserted into the source. The purely random candidate directions on page 8 are examples, not a unique prescribed law.')
issue('general_node_dictionary',[3,8],'Main-text finite-dictionary extension','The paper announces broader finite-dimensional least-squares node fits under weak assumptions and refers to appendix generality. The inspected main text does not completely specify that generalized theorem version. The census preserves the canonical mean-output statements and archives the announcement without consulting appendices.')
issue('sample_and_variation_representatives',[2,6],'Sampling and L2 closure','Random sample is read conventionally as i.i.d.; the defining sentence does not separately spell out independence. The source describes F as an L2 closure but evaluates ridge representatives pointwise to measure variation, without specifying an equivalence-class representative convention. No choice is silently added.')
issue('parameter_reuse',[5,11,16],'Library, tail and forest parameters','M is the number of terms in a finite ridge representation on page 5 and a separate positive tail-shift constant in Assumption 2; C in Theorems 1 and 4 depends on the latter. B is a tail threshold in Assumption 2 and separately the number of forest trees on page 16. These uses are scoped separately.')
resolution={
 'shared':'D1 fixes n,p, the sample, covariate marginal P_x, supports X/Y and conditional mean mu. A1 defines population and empirical L2 norms, fitted-value vectors, internal versus terminal nodes and cardinality. A12 records the formal empty internal node used in the orthogonal expansion and the unresolved scope of that extension for oracle probabilities. Node count n(t) is the ordinary count defined after (2); it does not require a new tree-output dependency where only counting is used. A2 supplies expectation scope. Standard primitives include integration, conditional probability, finite sums, closure, nonnegative powers, indicator functions, sparse coordinate count and optimization over sets. The comparison gtrsim means a bound up to a positive multiplicative constant in the stated penalty regime; no exact numeric constant is supplied. No library availability is claimed.',
 '1':'Direct interfaces D1,D3,D4,D5,D8,D9,D10 resolve mu, sample parameters, candidate success probabilities, the depth-K tree, node-average prediction, F and global variation, penalized pruning and Assumption 2. K>=1 and the oracle variable f are bound inside the theorem, with a further infimum over K in (11). The outer expectation and inner inverse-probability expectation use A2. C depends on c1,c2,gamma,M from Assumption 2. The theorem permits approximation error ||mu-f|| and does not require mu in F, Assumption 1, or the additional consistency corollary regimes.',
 '4':'Direct interfaces D1,D3,D4,D5,D9,D10,D11,D12 resolve the data, full-optimization parameters, tree and output, pruning, and Assumptions 2-4. A,V,q,nu come from Assumptions 3/4; nu affects the hypothesis even though absent from the rate. Local variation and F enter recursively through Assumption 3. C uses the tail parameters, and lambda_n is the penalization coefficient. K is uniformly quantified in the first bound; no proof-only Lemma 3 or moment hypothesis is separately imported. A6/A7 preserve the common q and permitted sample-size dependence of A,V.',
 '5':'D13 supplies Theta, B,N and the forest output; D4 supplies the depth-K tree appearing in its oracle term. D3 gives candidate sparsity d, kappa and conditional success probabilities, D8 supplies F and global variation, and D10 is the explicit Assumption 2. Node mean predictions enter through the forest definition, not as an extra direct edge for a symbol absent from the theorem. A5 fixes the RHS expectation over subsampled data; Section 4 gives N<n. K is the positive integer tree depth and f is the inline oracle variable. C is stated only to be some positive constant here; the precise dependence from Theorem 1 is not inserted. No pruned-forest version or fast-rate forest theorem is manufactured from the following discussion.'
}
def main():
    (ROOT/'ambient-conventions.json').write_text(json.dumps(dict(paper_id=PID,auxiliary_passages=aux,standard_ambient_resolution=resolution,unresolved_source_conventions=issues),indent=2,ensure_ascii=False)+'\n')
    print('Saved',len(aux),'auxiliary passages and',len(issues),'source notes.')


if __name__ == '__main__':
    main()
