"""Rebuild original supporting formulas and the paper's notation resolutions."""
import json
from pathlib import Path
from save_inventory import PID
ROOT=Path(__file__).resolve().parents[1]
aux=[]
def passage(lid,pages,heading,text,note):
    aux.append(dict(local_id=lid,source_heading=heading,statement_original=text.strip(),evidence=[dict(page=p,location=heading) for p in pages],note=note))
passage('A1',[3,4],'Section 2.1 — sampling, integration and index abbreviations',r'''
We work on a Polish space $(\mathcal Z,\mathcal B)$ with a collection of distributions $\mathcal P$, which we refer to as the model. Let $Z_1,Z_2,\cdots,Z_n\sim P_0$ be an independent and identically distributed (iid) sample from a distribution $P_0\in\mathcal P$, and let $P_n$ denote the corresponding empirical distribution. Let $\widehat P_n\in\mathcal P$ be an estimate of $P_0$. To ease notation, for now we consider a sample splitting approach wherein $\widehat P_n$ is fitted using an iid sample that is independent of $Z_1,Z_2,\cdots,Z_n$; in Section 2.5, we describe the case where cross-fitting is used (Schick, 1986; Klaassen, 1987), which is our preferred approach. For $Q$ a signed measure on $(\mathcal Z,\mathcal B)$ and a measurable function $f:\mathcal Z\to\mathbb R$, we use the shorthand $Qf:=\int f\,dQ$. For any object indexed by $P_0$, we will abbreviate the notation by replacing ‘$P_0$’ by ‘$0$’; for example, we will write $f_0$ rather than $f_{P_0}$. Similarly, we will replace ‘$\widehat P_n$’ by ‘$n$’ and write $f_n$ rather than $f_{\widehat P_n}$.
''','Theorems 2-6 use the later two-fold convention D10 rather than an extra independent training sample. P_0^n is the iid product law, while P_n^j is a held-out empirical measure. E_0 is expectation under P_0. In (30), dot-nu_n^{j,*} denotes the adjoint at the fitted law by these indexing conventions.')
passage('A2',[4],'Section 2.1 — real Hilbert and scalar square-integrability conventions',r'''
All Hilbert spaces mentioned in this paper are real Hilbert spaces. For a measure $\mu$ on a measurable space $(\mathcal X,\Sigma)$, we write $L^2(\mu)$ to denote the Hilbert space of $\mu$-a.s. equivalence classes of $\mathcal X\to\mathbb R$ functions equipped with inner product $\langle f,g\rangle_{L^2(\mu)}:=\int fg\,d\mu$. If $\mathcal X\subset\mathbb R^d$, $\mu$ is the Lebesgue measure, and $\Sigma$ is the Borel $\sigma$-algebra on $\mathbb R^d$, we will sometimes write $L^2(\mathcal X)$ instead of $L^2(\mu)$. In what follows $\mathcal V$ denotes a generic Hilbert space. We let $\|\cdot\|_{\mathcal V}$ and $\langle\cdot,\cdot\rangle_{\mathcal V}$ denote the norm and inner product associated with $\mathcal V$.
''','Square integrability is implicit in the named Hilbert space L2; the prose does not spell out a separate scalar finiteness condition. D1 preserves the explicit Bochner norm definition. The action space is additionally separable by D4.')
passage('A3',[4],'Section 2.1 — operator norm, sequence spaces and zero-padded basis convention',r'''
The operator norm of a linear functional $f:\mathcal V\to\mathbb R$ is defined as $\|f\|_{\mathrm{op}}:=\inf\{c\ge0:|f(v)|\le c\|v\|_{\mathcal V}\text{ for all }v\in\mathcal V\}$. If $\mathcal W$ is a closed subspace of $\mathcal V$, then let $\Pi_{\mathcal V}[h\mid\mathcal W]$ denote the orthogonal projection of $h$ to $\mathcal W$. We let $\ell^2$ denote the space of all square-summable sequences and $\|b\|_{\ell^2}:=[\sum_{k=1}^\infty b_k^2]^{1/2}$. We also let $[0,1]^{\mathbb N}$ denote the space of all $[0,1]$-valued sequences. To avoid having to use different notation to treat finite- and infinite-dimensional Hilbert spaces, throughout we use the convention that, if $\mathcal V$ is finite-dimensional, then we call $(v_k)_{k=1}^\infty$ an orthonormal basis of $\mathcal V$ if $(v_k)_{k=1}^{\dim(\mathcal V)}$ is an orthonormal system that spans $\mathcal V$ and $v_k=0$ for all $k>\dim(\mathcal V)$.
''','The finite-dimensional basis is explicitly zero-padded. For Hilbert-valued operators the source uses the standard induced operator norm; the displayed definition here is for functionals. Standard adjoints, Riesz representation, Bochner integration and weak convergence are ambient notions, not proof claims established by this census.')
passage('A4',[6],'Equation (4) — asymptotic linearity and Hilbert-valued small-o',r'''
\[
\widehat\nu_n-\nu(P_0)=\frac1n\sum_{i=1}^n\phi_0(Z_i)+o_p(n^{-1/2}),\tag{4}
\]
where throughout we let Hilbert-valued quantities of the form $o_p(n^{-a})$ denote terms whose Hilbert norm goes to zero in probability even after being multiplied by $n^a$.
''','Theorem 2 says (4) holds for the cross-fitted bar-nu_n, though (4) originally uses hat-nu_n. Retain the original display and state this change of estimator in analysis only. Theorem 6 uses the same asymptotic-linearity meaning with tilde-nu_n^beta, target nu^beta(P_0), and influence function phi_0^beta; it does not impose an EIF for nu.')
passage('A5',[7],'Section 2.3 — fixed basis used in the series formulas',r'''
where here and throughout we let $(h_k)_{k=1}^\infty$ denote an orthonormal basis of $\mathcal H$.
''','This original clause following (7) binds the basis in D17-D24. The preceding EIF expansion is background for the regularization construction; the existence of an original EIF is not required for that construction.')
passage('A6',[8],'Section 2.4 — regularized operator and admissible sequences',r'''
For a square summable $[0,1]$-valued sequence $\beta:=(\beta_k)_{k=1}^\infty$, the $\beta$-regularized efficient influence operator is given by $r_P^\beta(h)(z):=\sum_{k=1}^\infty\beta_k\langle h,h_k\rangle_{\mathcal H}\dot\nu_P^*(h_k)(z)$. We now show that $r_P^\beta(\cdot)(z)$ is always $P$-a.s. bounded and linear, and we also provide an explicit expression for its Riesz representation. In what follows we let $\ell^2_*:=\ell^2\cap[0,1]^{\mathbb N}$.
''','D17 preserves the defining Riesz representation and norm bound from Lemma 1. This auxiliary passage resolves its r_P^beta and ell2-star without adding a requirement that the original parameter has an EIF. Zero entries are allowed here and in Theorem 5, but excluded in Theorem 6.')
passage('A7',[14,15],'Section 4.2 — coverage level and data-measurable threshold',r'''
As we will now show, the weak convergence result in Theorem 2 can be used to facilitate the construction of $(1-\alpha)$-level confidence sets for the Hilbert-valued parameter $\nu(P_0)$, where $\alpha\in(0,1)$ is some fixed constant.

The following result establishes the asymptotic validity of the confidence set in (24) based on a threshold $\widehat\zeta_n$ that is measurable with respect to the $\sigma$-field generated by the iid sample $Z_1,\ldots,Z_n$ from $P_0$. This threshold is an estimate of the $(1-\alpha)$-quantile $\zeta_{1-\alpha}$ of $w(\mathbb H;\Omega_0)$.
''','Two original excerpts: level convention on page 14 and threshold convention before Theorem 3 on page 15. The Gaussian H is the one explicitly specified in Theorem 2, with variance E_0[<phi_0(Z),h>^2]. Theorem 3 allows either consistency or conservative estimation; Theorem 4 concerns the specific bootstrap threshold D16. No extra atom-free or positive-variance hypothesis is inserted into Theorem 4.')
passage('A8',[16],'Equation (25) — expansion incorporated by Theorem 5',r'''
\[
\bar\nu_n^{\beta_n}-\nu(P_0)=\frac12\sum_{j=1}^2\mathcal B_n^{j,\beta_n}+P_n\phi_0^{\beta_n}+O_p\left(\|\beta_n\|_{\ell^2}/n^{1/2}\right).\tag{25}
\]
Above $\phi_0^{\beta_n}$ is as defined in Lemma 1 and $\mathcal B_n^{j,\beta_n}:=\mathcal B_{\widehat P_n^j}^{\beta_n}$ denotes the bias term defined below (9).
''','Theorem 5 explicitly asserts this full expansion. The remainder is big-O in probability, not little-o. D19 defines the bias, D17 the regularized influence function and D18 the estimator. P_n is the empirical distribution of the full sample.')
passage('A9',[16],'Section 5.1 — sample-size and coordinate indices',r'''
We will denote the $k$th entry of a generic regularization parameter $\beta\in\ell^2_*$ by $\beta_k$, which should not be mistaken for the sample-size-$n$ dependent regularization parameter $\beta_n$, whose $k$th entry we will denote by $\beta_{n,k}$.
''','Theorem 5 permits beta to vary with n. Its printed statement does not impose a selection algorithm, entrywise convergence to one, or lack of an original EIF.')
passage('A10',[18],'Section 5.2 — fixed regularization and inverse on the image',r'''
Since the methods in Section 4.2 require the parameter of interest to be fixed and not depend on sample size, when constructing $\mathcal C_n^\beta(\widehat\zeta_n)$ we require the choice of $\beta$ to remain fixed as $n\to\infty$. Handling cases where $\beta$ changes with $n$ or is selected data-adaptively is an interesting area for future work.

The transformation $\Gamma_\beta$ has a left inverse if all entries of $\beta$ are nonzero, with $\Gamma_\beta^{-1}(h)=\sum_{k=1}^\infty\beta_k^{-1}\langle h,h_k\rangle_{\mathcal H}h_k$ for $h$ in the image of $\Gamma_\beta$.
''','Two original excerpts from page 18. Preimage of a set D24 is always well-defined; the inverse formula here is only on the image, and need not be bounded. In finite dimension the zero-padding convention means nonzero entries outside the active basis are unnecessary for injectivity, although Theorem 6 explicitly requires all entries to be positive.')
passage('A11',[18],'Section 5.2 — weighted seminorm',r'''
where $\|h\|_\beta:=[\sum_{k=1}^\infty\beta_k^2\langle h,h_k\rangle_{\mathcal H}^2]^{1/2}$. Here we note that $\|\cdot\|_\beta$ is a norm on $\mathcal H$ if all of the entries of $\beta$ are nonzero and is otherwise a seminorm.
''','This is supporting context for Theorem 6; its actual statement uses the ordinary Hilbert norm of the transformed Gaussian shift. The discussion of a nonshrinking ordinary Hilbert diameter concerns the infinite-dimensional setting and is not appended as a new theorem conclusion.')
passage('A12',[19],'Before Theorem 6 — regularized Gaussian law',r'''
In what follows we let $\mathbb H^\beta$ denote a tight $\mathcal H$-valued Gaussian random variable that is such that, for each $h\in\mathcal H$, the marginal distribution $\langle\mathbb H^\beta,h\rangle_{\mathcal H}$ follows a $N(0,E_0[\langle\phi_0^\beta(Z),h\rangle_{\mathcal H}^2])$ distribution, where $\phi_0^\beta$ is as defined in Lemma 7. Unlike in the rest of the paper, the following theorem requires all entries of $\beta$ to be nonzero, since its proof will rely on $\|\cdot\|_\beta$ being a norm.
''','The Gaussian variable is blackboard H; the action space is calligraphic H; E_0 is ordinary italic E. Theorem 6 binds a fixed submodel and hence a fixed first-order direction. It does not guarantee nontrivial power uniformly over changing directions.')
NOTES=[
'The registered source is the 83-page arXiv:2303.16711v3 PDF. Its arXiv stamp says 27 September 2023 while the manuscript title page says 28 September 2023. Both dates are retained; the published DOI does not replace this inspected source version.',
'Main text and references end on page 30 after Zheng and Laan (2011), before Appendices at y=638.9385986328125. Only the main-text portion of that page is admitted. Appendix contents and bodies are excluded.',
'Exactly six main-text Theorem environments occur: 1 on page 6, 2 on page 14, 3 and 4 on page 15, 5 on pages 16-17, and 6 on page 19. Theorem 5 in prose on page 21 is a reference. Main-text Lemmas are not inventoried as Theorems.',
'Theorem 2 incorporates (4), originally written for hat-nu_n, while its cross-fitted estimator is bar-nu_n. The original display is archived unchanged with an explicit analytical explanation. Its drift assumption prints uppercase o_P while its remainder prints lowercase o_p; both are preserved.',
'Theorem 5 incorporates the entire expansion (25), including the half-sum bias and full-sample empirical mean. Both its remainder and final rate use big-O_p; no little-o or central limit assertion is substituted.',
'The source calls the image of the local parameter a closed subspace. A continuous linear map need not have closed image. This source assertion is preserved, not silently replaced by a closure or a new closed-range hypothesis.',
'Pointwise efficient influence operator evaluations use selected representatives with a common full-probability set and a separable-process convention. Boundedness as an L2-valued operator does not itself give almost-sure boundedness of the pointwise functional.',
'An EIF is defined as a Hilbert-valued Riesz representative on a common full-measure set. Bochner square integrability is separately imposed where required; it is not inserted into the original EIF definition.',
'Theorem 1 permits the local parameter space to be an RKHS even if the full action space is not. Its candidate formula is stated for each t, P-almost surely in z. Do not strengthen that formula to an unqualified simultaneous-in-t statement or add a bounded-kernel hypothesis from Example 3.',
'Theorem 1 gives two implications: an existing EIF has the displayed form, and finite Bochner L2 norm of the candidate suffices for existence. It does not state that square integrability is necessary for EIF existence.',
'Lemma 1 prints dot-nu_P without an adjoint star in the middle formula for sigma_P(beta), although its argument h_k belongs to the action space. This apparent type mismatch is retained in D17 and is not silently repaired.',
'The finite-dimensional convention calls a zero-padded infinite sequence an orthonormal basis. All series formulas must be read with this explicit convention, not with a requirement of infinitely many unit vectors in finite dimension.',
'Cross-fitting uses an even-sized iid sample and two complementary halves. P_n^j denotes an empirical measure of n/2 observations, not a j-fold product law. Bootstrap sample labels deliberately reverse the halves, and fitted EIFs are not refitted per bootstrap draw.',
'The conditions of Theorem 2 imported into Theorems 3 and 4 are its hypotheses. They do not import its conclusion of regularity as a further assumption. Gaussian quantile notation from its conclusion is retained as supporting context.',
'Theorem 3 explicitly assumes the EIF has positive L2 norm and distinguishes exact limiting coverage from a conservative lower bound. Theorem 4 does not repeat that nondegeneracy condition; it instead adds fitted EIF L2 consistency. Preserve the difference.',
'Standardization operators are continuous, self-adjoint and positive definite as printed. Uniform coercivity, invertibility and bounded inverse are not stated. The Wald example and its appendix construction do not add assumptions to every confidence-set theorem.',
'Theorem 3 admits general consistent or conservative thresholds. Theorem 4 validates the particular conditional split-bootstrap quantile. Theorem 6 requires a consistent spherical Gaussian quantile without mandating bootstrap estimation.',
'Theorem 5 allows a sequence beta_n in ell2-star, including zero coordinates. Section 5.2 and Theorem 6 fix beta as n grows, and Theorem 6 requires every entry to be in (0,1]. No data-adaptive confidence-set result is asserted.',
'The generic drift/remainder definition on page 16 prints beta in ell2, while Lemma 1 and Theorem 5 use ell2-star. This source domain difference is preserved; it does not expand the theorem hypotheses.',
'The regularized bar estimator uses the untransformed plug-in nu(hat-P) and targets nu(P0). The tilde estimator instead uses Gamma_beta composed with nu(hat-P) and targets nu^beta(P0). These are distinct definitions even though both use the same regularized influence correction.',
'Theorem 6 assumes asymptotic linearity for the transformed target. It does not import Theorem 5 rate conditions, an original EIF, lack of an original EIF, or a particular sufficient condition from Corollary S1.',
'The preimage in (30) is a set preimage. The pointwise inverse formula is only defined on the image of Gamma_beta. The nonshrinking ordinary-norm diameter discussion depends on infinite-dimensional directions and is not a conclusion of Theorem 6.',
'Theorem 6 fixes a smooth submodel with nonzero original derivative, asserts strictly greater-than-alpha local power, and separately gives the O(n^-1/2) distance of its alternatives. It does not claim uniform power over sample-size-varying directions.',
'The six general Theorems do not assume the causal, density, or kernel-embedding examples. Main-text example Lemmas, proof-route results, tuning algorithms, and all appendix proofs are excluded from the theorem dependency graph. Standard RKHS, Gaussian, operator and probability notions remain ambient where the source gives no general definition.'
]
RESOLUTION={
'shared':'A1 fixes the iid sample, P_n, model, integration and abbreviated indices. A2-A3 fix real Hilbert spaces, L2 equivalence classes, norms, ell2 and the finite-dimensional basis convention; D4 adds separability of the action space. A5 binds h_k. D2-D5 give the dominated submodels, tangent space, derivative and adjoint. D7 resolves pointwise versions. Standard Gaussian laws, Bochner integration, weak convergence, Riesz representation, inner products, RKHS reproduction and quantiles are ambient; no external theorem is substituted for a source statement.',
'1':'Direct D4,D6,D8,D9 resolve pathwise differentiability, the local RKHS, the existing EIF and the candidate. D1 resolves the Bochner L2 condition in part (ii). A2 supplies the Hilbert conventions. The RKHS feature K_t represents evaluation on the local parameter space; no kernel bound or causal model is required.',
'2':'Direct D1,D4,D8,D11,D12 resolve square integrability, derivative, EIF, cross-fitted estimator and both error terms. A4 stores conclusion (4) with its original hat notation; the theorem applies it to bar-nu_n. D13 resolves regularity, including local submodels and common limiting law. The Gaussian law and tightness are explicitly bound in the theorem; E_0 is expectation under P_0 and convergence is weak convergence in the action space.',
'3':'D1,D4,D8,D12 are the inherited hypotheses of Theorem 2. D14 defines O, Omega and w; D15 defines C_n with its D11 center. A7 binds alpha, measurability and the limiting quantile, whose Gaussian law is in Theorem 2. The added positive EIF norm and alternative quantile hypotheses remain in the theorem. Its P_0^n is the iid product law; delta is locally universally quantified.',
'4':'D1,D4,D8,D12 are the inherited hypotheses of Theorem 2. D14 resolves the operator assumptions and D16 defines the particular bootstrap threshold. D10 and D8 resolve phi_n^j and the split. A7 fixes the target quantile. No theorem-3 positive-norm hypothesis or regularity conclusion is added.',
'5':'D4 gives pathwise differentiability. D17 and A6 give the regularized influence function and ell2-star, using A5 basis; D18 gives bar-nu_n^beta. D20 resolves both regularized errors. D19 and A8 resolve B_n^{j,beta_n}. A8 preserves incorporated conclusion (25) and A9 distinguishes sample-size and coordinate indices. P_n in (25) is the full-sample empirical measure. No original EIF is required.',
'6':'D2,D4 bind the fixed submodel, score and original derivative. D17,A6,A12 resolve the regularized influence function and Gaussian law; D21 gives the transformed target and derivative. D22 defines the tilde estimator; A4 explains its assumed asymptotic linearity with this target. D24 incorporates the complete preimage formula (30), including D23 spherical set. A1 resolves dot-nu_n^{j,*}. A7 fixes alpha; the theorem binds its own consistent norm-square quantile. A10-A11 record fixed beta, inverse and weighted-norm context. The theorem itself binds h0, h_n and the local alternative sequence.'
}
def main():
    data=dict(paper_id=PID,scope='Main text only; appendices excluded.',unranked_auxiliary_passages=aux,source_issues=NOTES,statement_resolution=RESOLUTION,
      branch_resolution={
        '1':dict(first_implication='EIF existence implies equality to the RKHS candidate.',second_implication='Finite candidate Bochner L2 norm implies existence; necessity is not asserted.'),
        '3':dict(consistent='Exact limiting coverage 1-alpha.',conservative='Liminf coverage at least 1-alpha, with a condition for every positive delta.'),
        '5':dict(base='Regularized remainder and drift rate assumptions imply (25).',additional='The two bias bounds additionally imply rate (27).'),
        '6':dict(fixed='Fixed beta with every entry positive; fixed differentiable submodel with nonzero derivative.',conclusions='Strictly nontrivial local power and the stated local-alternative distance rate.')},
      unresolved_source_references=[
        dict(reference='Local parameter space on page 5',status='source_assertion_preserved',reason='The image is called closed without an additional closed-range hypothesis. No silent correction or proof certification.'),
        dict(reference='Lemma 1 sigma formula',status='source_notation_issue_preserved',reason='The middle expression lacks the adjoint star printed in the series and norm bound.'),
        dict(reference='Appendices D-F,H and Lemmas S5-S7,S11; Corollary S1',status='excluded_not_opened',reason='Cited implementation details, influence-function theory, proof approximations and sufficient conditions remain outside the main-text census.'),
        dict(reference='External functional analysis and asymptotic statistics references',status='external_not_imported',reason='Standard ambient notions are identified; external proofs and stronger hypotheses are not imported.')])
    (ROOT/'ambient-prerequisites.json').write_text(json.dumps(data,indent=2,ensure_ascii=False)+'\n')
if __name__=='__main__':main()
