"""Keep local notation and source discrepancies separate from original statements."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];PID=ROOT.name
aux=[]
def add(aid,text,pages,loc,meaning):aux.append(dict(auxiliary_id=aid,statement_original=text.strip(),evidence=[dict(page=p,location=loc) for p in pages],resolution=meaning))
add('A1',r'''Empirical correlations between data vectors are measured via the empirical inner product $\langle a,b\rangle_n:=n^{-1}\sum_{i=1}^na_ib_i$ with norm $\|a\|_n:=\langle a,a\rangle_n^{1/2}$, for $a,b\in\mathbb R^n$.''',[3],'Section 1.1 — empirical inner product','The norm in the empirical risk, residual and noise level is scaled by 1/n. It is not the unnormalized Euclidean norm.')
add('A2',r'''The population counterpart of the empirical inner product is $\langle f,g\rangle_{L^2}:=\mathbb E(f(X_1)g(X_1))$ with norm $\|f\|_{L^2}:=\langle f,f\rangle_{L^2}^{1/2}$ for functions $f,g\in L^2(P_{X_1})$, where $P_{X_1}$ denotes the distribution of one observation of the covariates. Identifying $\widehat F^{(m)}$ with its corresponding function in the covariates, the population risk of the estimators is given by $\|\widehat F^{(m)}-f^*\|_{L^2}^2$, $m\geq0$.''',[5],'Section 1.2 — population norm and risk','The fitted function is held fixed when integrating over a new covariate. The displayed risk remains random through training data; it is not an expectation over all training samples.')
add('A3',r'''
We overload both the notation of the empirical and the population inner products with functions and vectors respectively, i.e., for $f,g:\mathbb R^p\to\mathbb R$, we set
\[
\|f\|_n^2:=\frac1n\sum_{i=1}^nf(X_i)^2\quad\text{and}\quad\langle f,g\rangle_n:=\frac1n\sum_{i=1}^nf(X_i)g(X_i)\tag{1.22}
\]
and also, e.g.,
\[
\langle\varepsilon,f\rangle_n:=\frac1n\sum_{i=1}^n\varepsilon_if(X_i)\quad\text{or}\quad\|Y\|_{L^2}^2:=\mathbb EY_1^2.\tag{1.23}
\]
''',[9],'Section 1.3 — vector/function overloading','Clarifies the coexistence of f* as a function and its observed vector in the theorems. Standard norm notation is retained as ambient context, not a separate bespoke API.')
add('A4',r'''Throughout the paper, variables $c>0$ and $C>0$ denote small and large constants respectively. They may change from line to line and can depend on constants defined in our assumptions. They are, however, independent of $n$, $\overline\sigma^2$ and $\rho^2$.''',[10],'Section 1.3 — constants','Generic C values in Theorem 5.1 need not be the same numerical constant. The explicit c>=0 in that theorem includes zero despite the general positive-c convention.')
add('A5',r'''Many statements in our results are formulated with a postpositioned “with probability converging to one”. This always refers to the whole statement including quantifiers. E.g. in Lemma 2.5, the result is to be read as: There exists an event with probability converging to one on which for all iterations $m\geq0$, the inequality $s_m\leq C\overline\sigma^2m\log(p)/n$ is satisfied.''',[10],'Section 1.3 — event scope','The simultaneous event convention supports the minimum over iterations in Theorem 1.2. It is not a separate pointwise-in-m claim for each index.')
add('A6',r'''where we introduce the notation $\widehat\Pi_m:=\widehat\Pi_{\widehat J_m}$, $b_m^2:=\|(I-\widehat\Pi_m)f^*\|_n^2$ for the squared empirical bias and $s_m:=\|\widehat\Pi_m\varepsilon\|_n^2$ for the empirical stochastic error.''',[4],'After equation (1.5) — empirical bias and stochastic error','These resolve the explanatory empirical-risk decomposition and are distinct from the population bias and stochastic error. The main theorem statements do not use the proof-only balanced oracle m^b.')
add('A7',r'''
Further, as in Bühlmann [6], for $j\leq p$, we denote the $j$-th coordinate projection as $g_j(x):=x^{(j)}$, $x\in\mathbb R^p$, and vectors of dot products via
\[
\langle\cdot,g_J\rangle_n:=(\langle\cdot,g_j\rangle_n)_{j\in J}\in\mathbb R^{|J|}\quad\text{and}\quad\langle\cdot,g_J\rangle_{L^2}:=(\langle\cdot,g_j\rangle_{L^2})_{j\in J}\in\mathbb R^{|J|}\tag{1.24}
\]
for $J\subset\{1,\ldots,p\}$. This way, Equation (1.13) in Assumption (CovB) can be restated as
\[
\sup_{|J|\leq M_n,k\notin J}\|\Gamma_J^{-1}\langle g_k,g_J\rangle_{L^2}\|_1\leq C_{Cov}.\tag{1.25}
\]
''',[9],'Section 1.3 — coordinate functions and CovB restatement','Coordinates and vector inner products are ambient notation. The original (CovB) uses a strict bound; its restatement uses a weak bound. The original assumption remains authoritative in the census.')
add('A8',r'''
Analogously to the population covariance matrix $\Gamma=(\langle g_j,g_k\rangle_{L^2})_{j,k\leq p}$, we define the empirical covariance matrix $\widehat\Gamma:=(\langle g_j,g_k\rangle_n)_{j,k\leq p}$. Using the same notation for partial matrices as in Assumption (CovB) and $X^{(J)}=(X_i^{(j)})_{i\leq n,j\in J}\in\mathbb R^{n\times|J|}$, the projections $\widehat\Pi_J$ and $\Pi_J$ can be written as
\[
\begin{aligned}
\widehat\Pi_J:&\ \mathbb R^n\to\mathbb R^n,&\widehat\Pi_Jy&:=(X^{(J)})^\top\widehat\Gamma_J^{-1}\langle y,g_J\rangle_n,\\
\Pi_J:&\ L^2(P_{X_1})\to L^2(P_{X_1}),&\Pi_Jh&:=g_J^\top\Gamma_J^{-1}\langle h,g_J\rangle_{L^2}
\end{aligned}\tag{1.26}
\]
for $J\subset\{1,\ldots,p\}$.
''',[10],'Section 1.3 — printed projector formulas','The empirical formula has a transposed n-by-|J| design matrix multiplying a |J|-vector, so its dimensions do not agree. The geometric definition on page 3 is preserved independently. Ordinary inverses for arbitrary J may also fail when the empirical subset Gram matrix is singular.')
add('A9',r'''$(\Gamma_J^{-1}v_k)_{j\in J}$ is the vector of coefficients for the $X_1^{(j)}$, $j\in J$, in the conditional expectation $\mathbb E(X_1^{(k)}\mid X_1^{(j)},j\in J)$.''',[7],'After (CovB) — conditional-expectation interpretation','Covariance regression coefficients specify a linear L2 projection in general. A conditional expectation need not be linear under the stated subgaussian assumptions. This interpretive claim is archived separately without replacing the geometric population projector by conditional expectation.')
add('A10',r'''Maximizing the empirical correlation between the residuals $Y-\widehat F^{(m)}$ and $X^{(\widehat j_{m+1})}$ at iteration $m$ is equivalent to minimizing $\|Y-\widehat F^{(m+1)}\|_n^2$, i.e., OMP performs greedy optimization for the residual norm.''',[4],'After Algorithm 1 — greedy optimization assertion','The algorithm itself uses raw-column normalization. Fully refitted residual decrease depends on the residualized column norm, so this asserted equivalence needs additional conditions. The census retains Algorithm 1 exactly rather than replacing it with a different greedy selection rule.')
add('A11',r'''Since the empirical noise level $\|\varepsilon\|_n^2$ is unknown, it has to be replaced by an estimator $\widehat\sigma^2$''',[4],'Before equation (1.8) — noise-estimator input','The target is the random empirical noise energy, not the population variance underline-sigma squared. Theorems 1.8 and 5.1 bind admissible estimates by their own conditions; the Scaled Lasso construction in Section 4 is an example sufficient to meet them, not a mandatory procedure.')
add('A12',r'''In the term $b_m^2$, we use the standard overloading of notation, letting $f^*$ denote $(f^*(X_i))_{i\leq n}$, see Section 1.3.''',[4],'Footnote 1 — signal vector','The same f* denotes either the linear function or its n observed values according to the norm or projection being used.')
issues=[]
def issue(i,pages,loc,detail):issues.append(dict(id=i,evidence=[dict(page=p,location=loc) for p in pages],detail=detail))
issue('source_version',[1],'arXiv stamp','The source is arXiv:2210.07850v1, stamped 14 October 2022. The audit does not establish equality of its theorem wording or numbering with the 2024 journal article.')
issue('conditional_noise_scope',[3],'Minimal assumptions and (SubGE)','The prose says conditional on the design and joint parameter, but the displayed MGF inequality conditions only on X_i for each scalar epsilon_i. The text gives i.i.d. design rows and i.i.d. noise terms separately, without an explicit joint conditional independence statement given the full design. A vector subgaussian MGF inequality or conditional product law is not substituted for the printed condition.')
issue('omp_zero_columns_and_ties',[3,4],'Full row rank and Algorithm 1','Full row rank n does not exclude an individual zero column, whose normalization in the argmax is undefined. The algorithm permits all j<=p at every iteration, including already selected indices, and does not specify a tie or zero-column rule. These are left as source limitations.')
issue('projection_formula_dimensions',[10],'Equation (1.26)','The empirical projector formula uses (X^(J))^T although X^(J) is expressly n by |J|. With the following |J| by |J| inverse and |J|-vector this is dimensionally inconsistent in general. Its original formula is archived; the census uses the earlier geometric projector definition without silently correcting the display.')
issue('empirical_inverse_and_population_extension',[3,5,10],'Projectors and fitted functions','An arbitrary empirical subset Gram matrix can be singular even when the full design has row rank n. The main text neither specifies generalized inverses nor a coefficient selection convention for extending a fitted n-vector to a population function in such cases. The geometric empirical projector is still unique; its full coefficient representation need not be.')
issue('conditional_expectation_vs_projection',[7],'Interpretation after (CovB)','The covariance coefficient vector is identified with the coefficients of a conditional expectation. For a general subgaussian design that expectation need not be linear. The original covariance condition and population L2 projection are retained, and the extra interpretation is not imposed as a new theorem hypothesis.')
issue('raw_vs_residualized_column_selection',[4],'Prose after Algorithm 1','OMP selects by correlation divided by the original column norm. For fully refitted candidate models, the decrease in squared residual is instead proportional to squared residual correlation divided by the squared residualized-column norm. The claimed equivalence with maximizing the next-step decrease need not hold for correlated columns. The displayed algorithm remains the defining procedure.')
issue('sparsity_endpoint_conventions',[5,6],'(Sparse)','The s-sparse branch permits s=0, leaving the displayed minimum over an empty support without an explicit convention. The gamma-sparse branch permits gamma=1; empty or zero coefficient subsets then lead to a zeroth power of zero. Neither an endpoint exclusion nor a convention is inserted into the original.')
issue('branch_overlap',[5,6,8,15],'(Sparse), rate (1.20), iteration (3.2)','A coefficient sequence may meet both sparsity alternatives. The formulas are interpreted for the chosen hypothesis branch; they are not asserted equal where both apply. The support-coverage threshold and population-bias threshold remain distinct.')
issue('covariance_strictness',[6,9],'Equations (1.13) and (1.25)','The defining condition uses a strict less-than bound whereas the claimed restatement uses less-than-or-equal. The source (CovB) statement is preserved with the strict sign.')
issue('population_bias_assignment',[5],'After equation (1.9)','The source prints B_m^2 : a = instead of the usual assignment punctuation. The original anomaly is preserved; the preceding decomposition and following bias norm identify the intended quantity.')
issue('stopping_totality_and_estimate_range',[4,23],'Equation (1.8) and Theorem 5.1','The source calls sigma-hat squared a noise-level estimator without explicitly giving a nonnegative range. Theorem 5.1 permits C_tau=0; a negative estimate could make the stopping set empty even after residuals vanish. Interpreting a variance estimator as nonnegative is conventional, but it is not inserted into the theorem. Infinite stopping times and argmin selections require conventions not stated here.')
issue('oracle_argmin_selection',[4,22],'Equations (1.6), (5.5), (5.6)','The source writes an argmin as a single iteration without prescribing how ties are resolved. Nonnegative integer indexing comes from Algorithm 1; the prefix optimization (5.6) prints only m<=tau. No specific tie-breaking convention is invented.')
issue('same_event_scope',[10,23],'Probability convention and Theorem 5.1','The lower bound for tau_two-step and its risk bound in Theorem 5.1 concern the corresponding common high-probability event. The latter is not converted to an expectation bound or a new independent event.')
issue('lower_bound_iteration',[15,23],'Equation (3.2) and Theorem 5.1','The theorem explicitly states tau_two-step >= tilde-m, not merely tau >= tilde-m. The preceding discussion on page 22 focuses on the first-stage stopping time; the theorem\'s stronger printed conclusion is retained without importing appendix proof content.')
resolution={
 'shared':'D1 defines the linear signal f*, coefficients beta*, response Y, design X, and noise epsilon. D2 is the main-text sampling/rank context, and D17 the asymptotic model sequence. A1-A3/A12 distinguish empirical vectors and norms from population functions and norms. All iteration indices are nonnegative integers as in Algorithm 1. Standard primitives include finite-dimensional span, geometric orthogonal projection, conditional MGF, covariance and eigenvalues, finite sums, norms, cardinality, little-o, min/argmin/infimum and high-probability events. A4 fixes generic constant scope and A5 the simultaneous-event convention. No library availability is asserted.',
 '1.2':'Direct D1,D2,D3,D5,D7,D8,D17 resolve the model, basic assumptions, (SubGE), OMP, stopping rule, ideal oracle and sequence. The minimization variable m is inline. Bar-sigma squared is the conditional MGF proxy, sigma-hat squared an input estimate of empirical noise energy, and underline-sigma squared is the separate true variance, absent from the theorem formula. The risk remains an empirical random quantity. No sparsity, subgaussian design, covariance bounds, population projector, rate R or Scaled Lasso construction is imported.',
 '1.8':'Direct D1,D2,D3,D5,D7,D9,D10,D11,D13,D17 resolve all nonlocal objects. The theorem binds C_Noise, c>0 and C_PopRisk, with C_tau set by the noise/design proxies. R(s,gamma) uses the chosen (Sparse) branch. The population L2 norm is A2; no population projector is needed merely to state this risk. It requires a two-sided absolute error bound for the empirical noise estimate, without selecting a particular estimator. Theorem 1.2\'s larger penalty lower bound is not added to this distinct result.',
 '5.1':'Direct D1,D2,D3,D5,D7,D9,D10,D11,D13,D14,D15,D16,D17 resolve the model, assumptions, sequential stage, branch rate and threshold, additive AIC and prefix selection. G>0 is inline, C_tau permits c=0, and C_AIC requires a sufficiently large positive multiple. Generic C can change by A4. The inequality for sigma-hat squared is one-sided. The lower-bound iteration uses population projection D12 through D14, and its support S is from (Sparse). The introductory comparison tau<tilde-m in D14 gives context; the value of tilde-m depends on the OMP path and population bias, not on a chosen noise estimator. Both conclusions use the corresponding common event. Multiplicative HDAIC and the Scaled Lasso are not defining components of this theorem.'
}
(ROOT/'ambient-conventions.json').write_text(json.dumps(dict(paper_id=PID,auxiliary_passages=aux,standard_ambient_resolution=resolution,unresolved_source_conventions=issues),indent=2,ensure_ascii=False)+'\n')
print('Saved',len(aux),'auxiliary passages and',len(issues),'source notes.')
