"""Resolve inherited hypotheses and retain source ambiguities without changing quotations."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];PID=ROOT.name
inventory=json.loads((ROOT/'theorem-inventory.json').read_text())
claims={c['claim_id'].split('/T')[-1]:c for c in inventory['claims']}
aux=[]
def add(aid,text,pages,loc,meaning):
    aux.append(dict(auxiliary_id=aid,statement_original=text.strip(),evidence=[dict(page=p,location=loc) for p in pages],resolution=meaning))
add('A1',r'''Throughout $L^2(\mathcal O)$ will denote the Hilbert space of square integrable functions for Lebesgue measure $dx$ on $\mathcal O$. We also assume (solely for notational convenience) that the volume of $\mathcal O$ is normalised to one, $vol(\mathcal O)=1$.''',[5],'Section 2 — measure and volume convention','The stationary uniform density is one and transition kernels are joint densities under this normalization. The explicitly constructed geometric domains (15) have their own dimensions; they are not silently rescaled to volume one.')
add('A2',r'''We emphasise again that the time interval $D>0$ between consecutive observations remains fixed in the $N\to\infty$ asymptotics.''',[5],'Section 2 — observation regime','N is the number of transitions, so there are N+1 observations from the same path. D does not shrink with N. This is not an i.i.d. data model.')
add('A3',r'''The symbols $\|\cdot\|_{H\to H},\|\cdot\|_{HS}$ denote the operator and Hilbert-Schmidt (HS) norm of a linear operator on a Banach space $H$, respectively. We denote by $\|\cdot\|_\infty$ the supremum norm and by $\|\cdot\|_B$ the norm of a normed space $B$, with dual space $B^*$. Throughout, $\lesssim,\gtrsim,\simeq$ denotes inequalities (in the last case two-sided) up to fixed multiplicative constants, while $Z\sim\mu$ means that a random variable $Z$ has law $\mu$.''',[5],'Section 2 — norms and asymptotic comparisons','The applications of HS are on the Hilbert space L2(O), as specified before Theorem 11. Operator norms on H2 are distinct from operator norms on L2 and from Hs norms of scalar coefficients. Standard O_P means boundedness in probability after scaling; convergence in P_f0 is under the true path law.')
add('A4',claims['3']['statement_original'].split('Then the estimator')[0],[6],'Theorem 3 — setting inherited by Theorem 4','Retains fixed D, uniform start, smooth bounded convex domain, f0 in C2 intersect Hs, s>2d-1, positivity and the combined C2/Hs bound. Theorem 4 quantifies all estimators and asserts existence of a domain, so (63), its chosen J and a particular domain from the lower-bound proof are not inherited requirements. The supremum in Theorem 4 itself prints only the Hs ball and positivity; the C2 norm scope is left explicitly ambiguous.')
add('A5',claims['5']['statement_original'].split('Then there exists')[0],[7],'Theorem 5 — hypotheses inherited by Theorems 6 and 7','The pair f,f0 is uniformly positive, agrees on O outside compact O0, and has the stated sum of C2 norms bounded by U on a bounded convex smooth domain. These are inherited by Theorems 6 and 7. They are not part of condition (10) alone and therefore are not imposed on Theorem 8 or on all prior draws in Theorem 10.')
add('A6',claims['6']['statement_original'].split('Then we have')[0],[7],'Theorem 6 — additional hypotheses inherited by Theorem 7','In addition to A5, the sum of Hs norms is bounded by U for s>d, and (10) holds for some positive mu,c0 and vector iota. D16 records only (10), and D12 resolves its first-eigenspace function. All these clauses are inherited by Theorem 7.')
add('A7',r'''By standard interpolation inequalities for Sobolev norms (p.44 in [45]) and Proposition 3 with some $s\geq2,k=3$, the bound (11) directly implies a Hölder stability estimate
\[
\|f-f_0\|_{L^2}\lesssim\|P_{D,f}-P_{D,f_0}\|_{L^2\to L^2}^{\gamma}\tag{12}
\]
for $\gamma=1/3$. Whenever $f,f_0\in H^s$ we can let $\gamma=\gamma(s)\to1$ as $s\to\infty$.''',[8],'Equation (12) — exponent referenced by Theorem 7','Theorem 7 refers here for gamma, requiring 0<gamma<1. The source gives gamma=1/3 via the described interpolation and qualitative improvement with smoothness, without an explicit general formula gamma(s). Its s>=2 qualification is preserved; no new numerical exponent is inferred for other parameter ranges.')
add('A8',claims['9']['statement_original'].split('Then there exists')[0],[12],'Theorem 9 — setting inherited by Theorem 10','Resolves Theorem 10 completely: fixed-D uniform-start diffusion; bounded convex smooth domain; truth in Hs for s>max(2+d/2,2d-1), inf f0>1/4, and f0=1/2 outside the smaller compact O00; posterior (16); prior (17) with K comparable to N raised to d/(2s+2+d) and the same s. O00 and O0 are different nested sets.')
add('A9',r'''Let $\mathcal O$ be a bounded convex domain in $\mathbb R^d$ with smooth boundary and let $f\in C^1(\mathcal O)$ be s.t. $\inf_{x\in\mathcal O}f(x)\geq f_{min}>0$.''',[14],'Proposition 2 — opening hypotheses referenced by Theorem 11','Apply this opening condition separately to f and f0. The proposition conclusions about spectral Sobolev spaces are not assumptions required to state Theorem 11.')
add('A10',r'''If we assume in addition that for some integer $k\geq2$ either A) $\|f\|_{C^{k-1}}\leq U$ or B) $\|f\|_{H^s}\leq U$ for some $s>d$ s.t. $k\leq s+1$, then we have''',[14],'Proposition 2 — alternatives, with branch B referenced by Theorem 11','Theorem 11 explicitly selects branch B, for each of f and f0, with the same bound U and positivity lower bound. The auxiliary integer k satisfies 2<=k<=s+1 but does not enter Theorem 11\'s result. Branch A is quoted only to preserve the exact source clause and is not substituted for B. No Hs norm-sum condition is invented.')
add('A11',r'''In the following theorem $\|\cdot\|_{HS}$ denotes the HS norm for operators on the Hilbert space $L^2(\mathcal O)$ (or just $L_0^2(\mathcal O)$). Note further that $H_c^1\subset H_0^1$ implies $(H_0^1)^*=H^{-1}\subset(H_c^1)^*$ so the r.h.s. in (45) can be bounded by $\|f-f_0\|_{H^{-1}}^2$ and then also by $\|f-f_0\|_{L^2}$.''',[17],'Before Theorem 11 — compact-support dual and HS space','H_c^1 is the compact-support subspace from D6, endowed with its Sobolev norm; H_0^1 is its closure as specified on page 5. Duality means continuous linear functionals. L2_0 denotes the mean-zero subspace, whose constant mode cancels in this operator difference. The final unsquared L2 bound is retained as source prose, not used to rewrite (45).')
add('A12','See Theorems 9 and 10 for details.',[4],'Immediately after Theorem 2','This explicit source instruction supplies the detailed prior and regularity setting for the introductory Theorem 2. Its original broad wording remains intact. It does not mean every Gaussian prior is admissible, nor does it add the optional eigenfunction condition to the baseline consistency result.')
add('A13',r'''For fixed $K$, the $Law(\theta)$ of $\theta$ is a probability measure supported in the space $\mathbb R^{K+1}\simeq\{\zeta g:g\in E_K\}$ where $E_K\subset C^\infty$ is the finite-dimensional linear span of the $\{e_k:0\leq k\leq K\}$.''',[10],'Section 2.3 — finite Gaussian coordinates','The theta prior has K+1 coefficients, including the constant mode. The source uses E_K here for indices 0 through K; estimator D11 instead uses E_J for indices 0 through J-1. These conventions are kept local.')
add('A14',r'''In this subsection we follow general ideas from Bayesian nonparametrics [24] and specifically in our diffusion context adapt the results from [56] to our multi-dimensional setting to obtain a contraction theorem for posteriors arising from general possibly $N$-dependent priors $\Pi$. Recall the information distance $KL$ from (44) on parameter spaces $\mathcal F\subset C^2(\mathcal O)\cap\{f\geq f_{min}\},f_{min}>0$.''',[25],'Section 3.6.1 — general-prior scope','Theorem 12 uses this general parameter class and arbitrary priors subject to its mass, sieve and test assumptions. The N-dependent Gaussian construction, cutoff support, spectral condition, test implementation, and estimator (63) are not statement dependencies for this theorem.')
add('A15',r'''The key variance estimate in that lemma can then be replaced by our (72) with $h=\log\frac{p_{D,f}(X_0,X_D)}{p_{D,f_0}(X_0,X_D)}$.''',[25],'Proof of Lemma 3 — contrasting log-density ratio','This short source passage documents the discrepancy in D15: the B_delta definition prints f in both numerator and denominator, whereas its own proof uses f0 in the denominator. It is retained as evidence of a source issue, not as a silent correction or theorem dependency.')
add('A16',r'''The latter matrix corresponds to the operator on $L^2$ arising from the composition $\pi_{E_J}P_{D,f}$ where $\pi_{E_J}$ describes the projection onto $E_J$ – note that $E_J$ are not the eigen-spaces of $P_{D,f}$ unless $f=1$.''',[22],'After equation (63) — expected operator restatement','The displayed finite matrix and its zero extension set all coefficients outside both index ranges to zero. On full L2 this is a two-sided compression, whereas this explanatory sentence prints only a left projection. D11 preserves the actual defining matrix and the zero extension; no proof formula replaces them.')
add('A17',r'''Let us define $\theta_0=\log(4f_0-1)$ which is zero outside of $\mathcal O_{00}$ and lies in $H_c^s$ by the hypotheses on $f_0$.''',[26],'Section 3.6.2 — true log parameter','This is the inverse of link (17). It resolves the theta0 used in the posterior-mean discussion, without imposing a separate algorithm or RKHS proof construction on Theorem 2.')
add('A18',r'''The above contraction results holds as well for the ‘linear’ parameter $\theta-\theta_0$, as $\log$ is $L^2$-Lipschitz on $\|\cdot\|_{H^s}$-bounded sets of $f$’s bounded away from zero (and using that $\|f-f_0\|_\infty\to0$ for $f\to f_0$ in $L^2$ bounded in $H^s$). In turn we further deduce a convergence rate for the posterior mean vectors
\[
\|E^\Pi[\theta\mid X_0,\ldots,X_{ND}]-\theta_0\|_{L^2}=O_{\mathbb P_{f_0}}(\widetilde\delta_N)\tag{83}
\]
using that we have exponential convergence to zero in (78) for any $b>0$ if we just increase the constant $M$, and by a uniform integrability argument as in Theorem 2.3.2 of [54] (or see also the proof of Theorem 3.2 in [50], to whom this argument is due). This then implies the same $L^2(\mathcal O)$-rates for $\overline f_N=f_{E^\Pi[\theta\mid X_0,\ldots,X_{ND}]}$ towards $f_0$ and and in particular implies the second limit in Theorem 2.''',[27],'Section 3.6.3 — posterior-mean interpretation','Retains the original transformed posterior-mean interpretation and its cross-reference to Theorem 2. The proof paragraph uses tilde-delta_N without restating the spectral condition required for the preceding algebraic rate; Theorem 2 itself claims consistency without a numerical rate. Its statement is not strengthened using this proof shorthand. No external proof references are read for the census.')
add('A19',r'''In order to obtain faster rates $\eta_N$, the hypothesis (10) needs to hold only at the ground truth $f_0$ and not throughout the parameter space of prior diffusivities $f$.''',[12],'After Theorem 10 — truth-only spectral condition','This explicit source clarification fixes the quantifier scope of the optional faster-rate branch. The prior is not restricted to coefficients satisfying (10).')
issues=[]
def issue(i,pages,loc,detail):issues.append(dict(id=i,evidence=[dict(page=p,location=loc) for p in pages],detail=detail))
issue('source_version',[1],'arXiv stamp','The source is arXiv:2210.13008v3, stamped 27 January 2024, 34 pages. This audit does not establish textual identity with the journal typesetting.')
issue('kl_ball_variance_ratio',[25],'Lemma 3, definition of B_delta','Both numerator and denominator are p_(D,f), making the printed log ratio zero. The immediately following proof uses p_(D,f0) in the denominator. The original definition and its use in Theorem 12 remain unchanged; this unresolved source discrepancy is material to the neighborhood condition.')
issue('general_prior_scope',[10,25],'Sections 2.3 and 3.6.1','The symbol F first denotes a general positive C2 parameter class, is specialized to f>=1/4 for prior (17), then is explicitly reset to a general f_min class before Theorem 12. The latter does not inherit the Gaussian prior or boundary support restrictions.')
issue('prior_coordinate_overload',[4,10],'Theorem 2 and equation (17)','Theorem 2 assigns Pi to theta; (17) assigns Pi to f=f_theta. Posterior expectations are understood in their printed coordinate. E[f_theta|data] and f_(E[theta|data]) are different objects; only the latter occurs in Theorem 2.')
issue('introductory_hypothesis_resolution',[4,12,27],'Theorem 2 and its explicit detail references','Sufficient regularity and an appropriate prior are not fully quantified in Theorem 2 itself. The source explicitly points to Theorems 9 and 10; their detailed setting and the posterior-mean paragraph are archived. No claim is made for arbitrary Gaussian priors or for the optional algebraic rate absent its condition.')
issue('theorem4_parameter_ball',[6],'Theorems 3 and 4','Theorem 4 says in the setting of Theorem 3, but its supremum prints an Hs ball and positivity without the explicit C2 norm bound of Theorem 3. Both source clauses are retained; the census does not silently change the supremum to a norm-sum ball.')
issue('theorem4_operator_domain',[6],'Theorem 4','The infimum includes all measurable bounded-L2-operator-valued estimators, while the loss uses an H2-to-H2 operator norm. An arbitrary bounded L2 operator need not map H2 into H2. The source does not state an extended-infinity convention or restrict the estimator class further.')
issue('gamma_scope',[8],'Equation (12) and Theorem 7','Theorem 7 refers to (12) for gamma. The adjoining text gives 1/3 under an interpolation invoking s>=2 and qualitative gamma(s) approaching one with smoothness. It gives no complete explicit formula for all s>d, particularly when d=1 and s<2. The reference and qualification are preserved.')
issue('domain_smoothness',[9],'Equation (15)','The source asserts that Euclidean distance-neighborhood enlargements of the hyperrectangle have smooth boundaries for every m. Such offsets generally have joins between flat and curved pieces and need not have a C-infinity boundary. The displayed domain and the assertion are preserved separately from the general smooth-domain requirement; no alternative smoothing construction is invented.')
issue('volume_normalization_scope',[5,9],'Volume convention and equation (15)','The general diffusion setup normalizes volume to one, whereas the geometric construction retains width w>=2 and a positive enlargement. The explicit O_(m,w) is not volume one as written. The normalization is kept as an ambient convention with this scope discrepancy, rather than changing the geometric definition or automatically adding a unit-volume hypothesis to Theorem 8.')
issue('prior_basis_indices',[10,21],'Gaussian series and estimator basis','The source calls indices 0 through K the first K eigenfunctions, although there are K+1 including the constant mode. It also prints mixed strict and non-strict signs in the eigenvalue ordering. These are preserved without imposing simplicity. The estimator basis instead uses 0 through J-1.')
issue('estimator_expected_compression',[21,22],'Equations (62)-(63) and their explanation','The defining empirical matrix has zero coefficients outside both retained index ranges. The expected full-L2 operator is therefore a two-sided compression, while the next paragraph writes only pi_EJ P_D,f. The defining estimator is preserved and the discrepancy is separately documented.')
issue('theorem11_regularity_scope',[10,14,17],'Equation (44) and Proposition 2B','KL is defined for arguments in F, introduced as a positive C2 class. Theorem 11 instead explicitly assumes Proposition 2B, whose opening condition is C1 with Hs bounds for s>d. Those bounds alone need not yield C2 for every allowed s,d. The source does not explain whether F additionally restricts this theorem; both clauses are retained without silently upgrading its stated regularity.')
issue('sobolev_and_hs_conventions',[5,17],'Notation and Theorem 11 preface','Page 5 defines integer-order Sobolev/Hölder spaces explicitly but the theorems allow real s; the fractional Sobolev convention is left standard rather than given an invented formula. The same paragraph calls the HS norm a norm on operators on a Banach space; the actual theorem applications use the Hilbert space L2. Page 17 ends a squared-dual-norm comparison with an unsquared L2 norm, retained only as source prose.')
issue('logarithmic_zero_endpoint',[7],'Theorem 5','The logarithmic modulus contains reciprocal operator difference. At equality of the two operators the printed expression requires a limiting endpoint interpretation, consistent with the ensuing injectivity sentence; the source does not define that endpoint separately.')
issue('posterior_mean_rate_shorthand',[12,27],'Section 3.6.3 and Theorems 2/10','The posterior-mean paragraph writes the preceding polynomial tilde-delta_N rate without restating its spectral hypothesis. Theorem 10 distinguishes the baseline logarithmic rate from an optional polynomial rate, and Theorem 2 states only consistency. The proof shorthand is not promoted to an unconditional theorem conclusion.')
resolution={
 'shared':'D1 gives the uniform-start reflected model and P_f path law; D2 gives the bounded convex smooth domain; D3/D4 give the Neumann generator and its transition family. A1 gives Lebesgue L2 and unit-volume stationarity, with explicit geometric scope notes. A2 fixes D>0 as N tends to infinity. A3 fixes norms, comparison notation and duality. Standard ambient objects include real Sobolev spaces, continuous derivatives, finite-dimensional Gaussian vectors, conditional expectations, linear-operator norms, HS norms on L2, variance, compact sets, probability limits, boundedness in probability, infima and suprema. Generic constants have exactly the dependencies printed in each theorem. U as a coefficient norm bound is distinct from the potential fixed to one in model (2), the spatial region in the transition-kernel prose, and other locally bound symbols.',
 '1':'D4 resolves P_(D,fi), and its graph resolves the generator and domain. The positive coefficients f1,f2, their C2 membership and near-boundary agreement are inline hypotheses, with D>0 existentially specified. The conclusion is equality on O; no spectral hypothesis or prior is assumed.',
 '2':'D1,D2,D4,D8,D9,D10 resolve the data, domain, operator, posterior, appropriate Gaussian field and link. A12 points to detailed hypotheses A8 from Theorems 9/10. A17/A18 identify theta0 and explain the transformed posterior mean, while the full original theorem binds bar-theta_N and bar-f_N inline. The truth exceeds one quarter and is one half near the boundary. Only consistency for each fixed t>0 is asserted. The optional spectral condition and numerical rates of Theorem 10 are not additional hypotheses or conclusions here.',
 '3':'D1,D2,D4,D11 resolve model, domain, target operator and the specific estimator. The theorem binds s>2d-1, U bounding the sum of Hs and C2 norms, f_min, and J_N at the displayed asymptotic order. J_N is an integer sequence with that order; no particular rounding rule is specified. O_P is under the fixed true diffusion law, with the printed constants.',
 '4':'D1,D2,D4 resolve observation model, existential domain and estimand. A4 preserves the setting reference. The estimator is an arbitrary measurable function of all N+1 observations valued in bounded L2 operators, with H2 loss as printed. The liminf, infimum over estimators, supremum parameter ball, constant c and lower bound 1/4 retain their order. The explicit estimator D11, its J and the proof\'s chosen domain are not requirements.',
 '5':'D2,D4 resolve the domain and transition operators; all coefficient regularity, positivity, compact agreement, D>0 and constant dependencies are inline. The norm of the operator difference is L2-to-L2. The zero endpoint of its logarithmic modulus remains documented separately.',
 '6':'A5 resolves all inherited Theorem 5 hypotheses, while its own Hs norm-sum bound and s>d are inline. D16 resolves (10) through D12/D5/D3; mu,c0>0 and iota are existential choices. The result compares coefficient L2 error with H2-to-H2 operator error. No simplicity of the first eigenvalue is imposed.',
 '7':'A5 and A6 resolve the nested Theorem 6 then Theorem 5 references in full. D4 gives the operators at t and D, with 0<t<D; D16 gives the inherited condition (10). A7 retains the exact exponent reference and its scope limitations. HS is on L2(O). The first-eigenspace condition remains an assumption of this theorem, not a consequence of its comparison bound.',
 '8':'D13 gives O_(w) and its enlargements; D3/D5 give the Laplacian or variable-coefficient generator eigen-pairs, with the additional index m denoting the domain. The m-large and kappa-small quantifiers and dependencies remain as printed. Condition D16 is a conclusion at the chosen eigenfunction, with O0 compactly contained in the original rectangle, not merely in the enlargement. Part B binds an Hs ball and closeness to the constant coefficient one. The pair f,f0 agreement and C2 norm-sum from Theorem 5 are not inherited just by reference to (10). The smoothness and volume scope issues in the domain construction are explicitly unresolved.',
 '9':'D1,D2,D4,D8,D10 and their prerequisites resolve all named objects. D9 provides the smaller O00 and larger O0, cutoff zeta, smoothness s and truncation. The truth condition uses O outside O00; prior draws equal one half outside O0. The theorem fixes K at its displayed order and asserts posterior mass of an error >= threshold tends to zero in P_f0, not a deterministic error bound. U bounds the truth Hs norm as printed.',
 '10':'A8 expands the entire Theorem 9 setting, with the same prior, truncation, sample and truth. D8/D4 resolve posterior and transition family. Eta_N tends to zero and bounds two different errors; t>0 is fixed, not a uniform supremum over times. Delta-prime is some positive logarithmic exponent. D16 appears only in the optional faster-rate branch and only at f0. No test implementation, lower-bound construction or assumption on every prior draw is added.',
 '11':'A9 and branch B of A10 resolve the Proposition 2B hypothesis separately for f and f0. Compact-interior agreement and D>0 are inline. D14 specifies KL with truth in the numerator, D4 gives the HS difference, and D6/A11 specify the compact-support dual norm. The source F-versus-C1/Hs regularity ambiguity remains explicit. Spectral Sobolev spaces, perturbation identities and eigenfunction summations used only in the proof are not added as statement requirements.',
 '12':'D7/A14 give the general parameter class, D1 the law of observations, D8 the posterior and D15 the neighborhood through KL (D14). Pi_N, F_N, positive A, B>A+2, 0<b<B-A-2, delta_N with sqrt(N)delta_N tending to infinity, bar-delta_N, tests Psi_N, and distance d on F are bound inline. The local distance symbol d is not the ambient dimension. Delta_N and bar-delta_N are distinct sequences with no asserted equality. Tests are measurable statistical tests, with the usual [0,1] range implicit in the source terminology. Both mass and uniform type-II bounds use delta_N, whereas the posterior radius is bar-delta_N. The conclusion retains intersection with F_N and the exponential O_P remainder. Gaussian-specific restrictions are absent; the printed neighborhood variance discrepancy is not repaired.'
}
(ROOT/'ambient-conventions.json').write_text(json.dumps(dict(paper_id=PID,auxiliary_passages=aux,standard_ambient_resolution=resolution,unresolved_source_conventions=issues),indent=2,ensure_ascii=False)+'\n')
print('Saved',len(aux),'auxiliary passages and',len(issues),'source notes.')
