"""Archive original context and explicitly retain unresolved source conventions."""
import json
from save_inventory import ROOT,PID

def main():
    aux=[]
    def add(n,s,ps,note,deps=()):aux.append(dict(local_id='A'+str(n),statement_original=s,evidence=[dict(page=p,location='Original main-text context A'+str(n)) for p in ps],scope_note=note,depends_on=list(deps)))
    add(1,r'''However, as we highlight in Section 3.2, simple approximation arguments can be used to leverage our finite-dimensional results to determine minimax rates of convergence for estimating an element $\theta^\star$ of the infinite-dimensional sequence space $\ell^2(\mathbb N)$.''',[3],'Original bridge to infinite-dimensional applications. It does not make ordinary finite-matrix inverse5 a general infinite-dimensional inverse theorem.',['D2'])
    add(2,r'''Inspecting the proof of Theorem 1—specifically, as a consequence of Proposition 3—if the supremum on the righthand side of (5) is attained at the matrix $\Omega_\star$, then the following estimator, in view of the lower bound (7), is near minimax-optimal,
\[
\hat\theta(T_\xi,y):=(\Omega_\star^{-1}+T_\xi^T\Sigma_w^{-1}T_\xi)^{-1}T_\xi^T\Sigma_w^{-1}y.\tag{9}
\]
It is perhaps instructive to write this estimator in its “ridge” formulation
\[
\hat\theta(T_\xi,y)=\operatorname*{argmin}_{\vartheta\in\mathbb R^d}\{\|y-T_\xi\vartheta\|_{\Sigma_w^{-1}}^2+\|\vartheta\|_{\Omega_\star^{-1}}^2\}.
\]''',[9],'Original conditional-on-attainment estimator. Theorem1 bounds minimax risk without requiring a supplied optimizer or a restriction to ridge estimators.',['D1','D8','D10','D12'])
    add(3,r'''In the language of Bayesian statistics, our order-optimal procedure is a maximum a posteriori (MAP) estimate for $\theta^\star$ when $y\sim N(T_\xi\theta^\star,\Sigma_w)$ and the parameter follows the prior distribution $\theta^\star\sim N(0,\Omega_\star)$. The optimal prior is identified via the choice of $\Omega_\star$ which is determined by the functional appearing in Theorems 1 and 2. If the supremum in (5) is not attained, then by selecting a sequence of matrices $\Omega_k$ that approach the maximal value of the functional, one can similarly argue there exists a sequence of estimators that approach the order-optimal minimax risk.''',[9],'Original Bayesian interpretation and explicit nonattainment handling. General model noise remains theN1/N2 class. Gaussian prior has unbounded support and is not itself a supported prior on the parameter ellipse.',['D9','D12'])
    add(4,r'''In general, Jensen’s inequality along with the convexity of the trace of the inverse of positive matrices [8, Exercise 1.5.1] implies that it is always lower bounded by
\[
\sup_\Omega\left\{\operatorname{Tr}\left(K_e^{1/2}(\Omega^{-1}+\mathbb E T_\xi^T\Sigma_w^{-1}T_\xi)^{-1}K_e^{1/2}\right):\Omega\succ0,\ \operatorname{Tr}(K_c^{-1/2}\Omega K_c^{-1/2})\le\varrho^2\right\}.\tag{17}
\]
Comparing displays (15) and (17), we have simply moved the expectation over $\xi$ into the inverse.''',[10],'Original loosened bound, not the definition5. General theory does not impose a finite second-moment condition on the operator; ordinary finite entries of this expected information matrix would require such integrability. Do not replaceE(inverse) by inverse(E).',['D2','D8','D12'])
    add(5,r'''In order to derive an upper bound, we restrict our focus to estimators that are conditionally linear. Formally, we consider the class of procedures
\[
\hat\theta_C(T_\xi,y):=C(T_\xi)T_\xi^T\Sigma_w^{-1}y,\tag{57}
\]
where $C$ is a $\mathbb R^{d\times d}$-valued measurable function of $T_\xi$.''',[21],'Original proof-only subclass. The original minimax problem still ranges over all measurable estimators of(T_xi,y).',['D1','D10'])
    add(6,r'''on the space of symmetric positive definite matrices of the form
\[
\mathcal K(\varrho,K_c):=\{\Omega\succeq0\mid\operatorname{Tr}(K_c^{-1/2}\Omega K_c^{-1/2})\le\varrho^2\}.
\]''',[22],'Original proof auxiliary set: prose says positive definite but display permits semidefinite matrices. Keep this separate from strictOmega>0 in functional5.',['D8','D12'])
    add(7,r'''In order to do so, we focus on lower bounding the Gaussian minimax risk
\[
\mathfrak M^G(T,\mathbb P,\Sigma_w,\varrho,K_e,K_c):=\inf_{\hat\theta}\sup_{\theta^\star\in\Theta(\varrho,K_c)}\mathbb E_{(\xi,w)\sim\mathbb P\times N(0,\Sigma_w)}\left[\|\hat\theta(T_\xi,T_\xi\theta^\star+w)-\theta^\star\|_{K_e}^2\right].
\]
Evidently, the Gaussian minimax risk lower bounds the general minimax risk, so that we have $\mathfrak M^G\le\mathfrak M$.''',[23],'Original lower-bound proof restriction. Neither Gaussian noise nor a Gaussian prior is an added hypothesis of Theorem2.',['D1','D7','D8','D9','D10','D11'])
    bindings={
    'T1':'Both M andPhi use the original argument order(T,P,Sigma_w,varrho,K_e,K_c). M resolves to the observed linear model, finite measurable operator law, conditional-noise class withN1/N2, kernel-composed observation law, all measurable estimators of(T_xi,y), SPD error/constraint norms, and parameter ellipse. Phi is the supremum over a deterministic strictly positive Omega under a weighted trace budget, outside expectation overxi, with ordinary matrix inverses and square roots. No IID, Gaussian, full-rank design, ridge-estimator or optimizer-attainment assumption is added. Sigma_w inverse and positive radius conventions are not explicit in the original general assumptions.',
    'T2':'Same complete source definitions asT1. Preserve both inequalities: M at radiusvarrho is at leastPhi at radiusvarrho/2, which is at leastone quarterPhi at the original radius. Radius halving changes the trace budget byfour; K_e andK_c do not change. Gaussian observation and prior reductions are proof machinery, not changes to the robust conditional-noise minimax problem. Supremum overtheta/noise andOmega optimization remain outside their respective expectations.'}
    refs=[]
    for n in ['1','2']:
        refs.append(dict(claim_id=PID+'/T'+n,target='Minimax definition(3), operator/noise assumptions1.1.1, decision formulation1.1.2, functional(5)',reference_kind='definition_reference',note='Both short theorem statements depend on the full main-text model and definitions.'))
        refs.append(dict(claim_id=PID+'/T'+n,target='Ridge estimator(9), conditional-linear class(57), Proposition3, Gaussian reduction and proof lemmas',reference_kind='proof_only',note='Do not restrict the general minimax estimator/noise classes to these proof witnesses.'))
        refs.append(dict(claim_id=PID+'/T'+n,target='Appendix C deferred calculations',reference_kind='proof_only',note='All appendix bodies are excluded; no definition needed by the two statements is available only there.'))
    issues=[]
    def issue(k,ps,note):issues.append(dict(issue_id=k,evidence=[dict(page=p,location='Source issue '+k) for p in ps],note=note))
    issue('registered-source',[1,32],'Registered arXiv2303.12613v1,53pages,stamp22Mar2023. Main text ends32 after simulations and acknowledgements; Appendix A starts33. Two actual Theorem environments occur on8; numbered Corollaries/Propositions and external citations are not inventoried.')
    issue('conditional-noise',[3,4],'N1 is conditional mean zero andN2 is a conditional second-moment upper bound in every fixed direction, not covariance equality or merely a marginal bound. Noise may depend onxi and have dependent coordinates; it need not be Gaussian. In finite dimensions, a common full-measure set for quadratic-form bounds can be recovered from a countable dense set after integrability; preserve original almost-everywhere wording.')
    issue('operator-versus-latent-input',[1,3,4],'The observed pair is(T_xi,y), whilexi indexes the operator and conditional noise. An estimator is not automatically allowed to observe additional information inxi. The product-looking P timesnu is kernel composition, not independence. Parameter and worst-case noise distribution are chosen before averaging over operator realizations.')
    issue('matrix-invertibility',[3,4,8],'K_e andK_c are explicitly symmetric positive definite. N2 only bounds conditional covariance bySigma_w and does not explicitly assumeSigma_w is invertible. Functional5 usesSigma_w inverse, so its ordinary formula requires positive definiteness or a separately supplied extension. ForSigma_w=0 admissible noiseless observations exist but that formula is undefined; no pseudoinverse convention is stated. T_xi itself may be rank deficient; positiveOmega regularizes its information matrix whenSigma_w is positive definite.')
    issue('radius-and-open-feasible-set',[4,8,9],'The ellipse display usesvarrho but its following prose saysradiusR. No positive-radius condition is explicit in the two theorem sentences; strictOmega>0 under trace<=varrho² requiresvarrho>0. Atvarrho=0 the parameter set is{0} while the strict feasible matrix set is empty. Preserve this endpoint limitation. The open feasible set need not attain its supremum; Section2.1 explicitly discusses approximating sequences.')
    issue('geometry-and-order',[4,8],'Error is measured withK_e, parameter norm withK_c inverse, and trace budget withK_c inverse square roots. The matrix products cannot be reordered by assuming commutativity. The estimator output need not lie inTheta. Theorem2 halves the radius, notK_c, the noise variance, or the constant alone.')
    issue('expectation-location',[8,10],'Omega is deterministic and selected before averaging overxi. Phi uses expectation of the inverse information-plus-precision matrix, not inverse of the mean information matrix;17 is a different lower bound. T_xi has no moment/rank assumption in the general setup, so17 may require extended-value/integrability interpretation. For the well-defined positive-definite noise case, the inverse in5 is bounded in PSD order byOmega, keepingPhi finite under its trace budget.')
    issue('proof-restrictions',[9,21,22,23],'Conditionally linear estimators, Gaussian noise reductions and prior constructions serve proofs and discussion. They do not narrow the all-measurable estimator class or theN1/N2 noise class in3. The auxiliary setK on22 permitsOmega semidefinite despite positive-definite prose; do not substitute it directly into5 with an ordinary inverse.')
    issue('finite-versus-infinite',[3,9,10],'The two theorem formulas use finite n-by-d matrices. Infinite-dimensional sequence/RKHS and IID/covariate-shift models are separate applications via approximation, not assumptions of both general Theorems. In particular, conditional noise bounds do not imply an IID sampling law.')
    data=dict(paper_id=PID,unranked_auxiliary_passages=aux,statement_local_bindings=bindings,source_claim_references=refs,source_issues=issues,unresolved_external_prerequisites=[],ambient_prerequisites=['Finite-dimensional real matrices and Euclidean inner products, symmetric positive definiteness and semidefinite order, ordinary inverse and positive square roots, trace and weighted quadratic norms.','Measurable operator laws, Borel regular conditional kernels, kernel-composed observation distributions, vector conditional expectations and covariance bounds, joint observation expectations.','Infimum over measurable estimators, supremum over parameters and conditional-noise kernels, nonnegative risks, ellipsoidal constraint geometry, deterministic matrix optimization and expectations of matrix functions.','Ordinary inverse ofSigma_w and positive radius require the explicit source-limit notes; no unprovided generalized-inverse or empty-supremum convention is silently chosen. No proof or mathlib audit verdict.'],validation_limits='Source fidelity and structural validation concern only original main-text statements and their dependencies. They do not certify theorem truth or fill missing covariance/radius conventions; all appendices are excluded.')
    (ROOT/'ambient-prerequisites.json').write_text(json.dumps(data,indent=2,ensure_ascii=False)+'\n')
if __name__=='__main__':main()
