"""Preserve original elliptical-test definitions, source assumptions and statistical functionals."""
import json
from save_inventory import ROOT,PID,STATEMENTS
interfaces=[];members={}
def add(n,term,s,pages,deps,symbols,boundary,heading,kind='definition',context=None,context_page=None,phrases=None):
    lid=f'D{n}'
    m=dict(paper_id=PID,local_id=lid,local_label=heading,source_heading=heading,source_kind=kind,statement_original=s,relation='exact',depends_on=[f'D{i}' for i in deps],evidence=[dict(page=p,location=heading) for p in pages],highlight_symbols=symbols,highlight_phrases=phrases or [])
    kw=dict(paper_id=PID,local_id=lid,source_text=term,label=term[0].upper()+term[1:],kind='term')
    if term not in s:
        assert context and term in context,(lid,term)
        m['naming_context']=[dict(context_id=lid+'/name',text=context,evidence=[dict(page=context_page or pages[0],location='Original naming context')])];kw['context_id']=lid+'/name'
    members[lid]=m
    interfaces.append(dict(interface_id=PID+'/'+lid,rank_group='all',name=kw['label'],lean_role='definition',type_shape=boundary,semantic_boundary=boundary,members=[m],source_keywords=[kw],central_claim_uses=[],dependencies=[],theorem_explanations={}))
add(1,'Polar coordinate transformation',r'''$\theta=(\theta_1,\ldots,\theta_{d-1})^\top\in(-\pi/2,\pi/2]\times\cdots\times(-\pi/2,\pi/2]\times(-\pi,\pi]\equiv\Omega_\Theta$.
$\Omega_U=[0,\infty)$.''',[4,5],[],[r'\Omega_\Theta',r'\Omega_U'],'Radius domain and half-open angular rectangle, with d−2 latitude angles and one longitude. The displayed coordinates implicitly require d≥2. Endpoint and pole ambiguities are recorded separately.','Section 2.2 — Coordinate domains',context='Polar coordinate transformation and equivalent condition.',context_page=4)
add(2,'reproducing kernel Hilbert space',r'''Let $\kappa_U:\Omega_U\times\Omega_U\to\mathbb R$ and $\kappa_\Theta:\Omega_\Theta\times\Omega_\Theta\to\mathbb R$ be positive definite kernels, and let $\mathcal H_U$ and $\mathcal H_\Theta$ be the reproducing kernel Hilbert space (RKHS) generated by $\kappa_U$ and $\kappa_\Theta$.''',[5],[1],[r'\mathcal H_U',r'\mathcal H_\Theta'],'The two RKHSs associated with positive definite radial and angular kernels. Characteristicness, smoothness, bounds and Lipschitz conditions are separate theorem-specific properties.','Section 2.3 — Kernel Hilbert spaces')
add(3,'tensor product space',r'''Let $\mathcal B$ be the collection of linear operators $\{f\otimes g:f\in\mathcal H_U,g\in\mathcal H_\Theta\}$. Thus, each member of $\mathcal B$ is a linear operator mapping from $\mathcal H_\Theta$ to $\mathcal H_U$ such that, for any $h\in\mathcal H_\Theta$, $(f\otimes g)(h)=f\langle g,h\rangle_{\mathcal H_\Theta}$. Let $\mathcal S$ be the linear span of $\mathcal B$, consisting of finite linear combinations of members of $\mathcal B$ with real coefficients. Define in $\mathcal S$ the inner product
\[
\langle\alpha_1(f_1\otimes g_1)+\cdots+\alpha_r(f_r\otimes g_r),\widetilde\alpha_1(\widetilde f_1\otimes\widetilde g_1)+\cdots+\widetilde\alpha_r(\widetilde f_s\otimes\widetilde g_s)\rangle=\sum_{i=1}^r\sum_{j=1}^s\alpha_i\widetilde\alpha_j\langle f_i,\widetilde f_j\rangle_{\mathcal H_U}\langle g_i,\widetilde g_j\rangle_{\mathcal H_\Theta}.
\]
Endowed with this inner product, $\mathcal S$ is an inner product space; its completion as a Hilbert space is the tensor product space $\mathcal H_U\otimes\mathcal H_\Theta$.''',[5,6],[2],[r'\mathcal H_U\otimes\mathcal H_\Theta',r'(f\otimes g)(h)'],'Hilbert tensor product identified with Hilbert-Schmidt operators from angular to radial RKHS. Preserve the printed r/s coefficient mismatch in the second finite sum. The outer products defining Gamma act one Hilbert-space level higher.','Section 2.3 — Hilbert tensor product')
add(4,'probability measures',r'''Let $\mathcal F_U$ and $\mathcal F_\Theta$ be the Borel $\sigma$-fields on $\Omega_U$ and $\Omega_\Theta$, and let $\mathcal F_U\times\mathcal F_\Theta$ be the product $\sigma$-field. Abbreviate $\Omega_U\times\Omega_\Theta$ and $\mathcal F_U\times\mathcal F_\Theta$ by $\Omega_{U,\Theta}$ and $\mathcal F_{U,\Theta}$. Let $\mathcal M(\Omega_{U,\Theta},\mathcal F_{U,\Theta})$ denote the class of all probability measures on $(\Omega_{U,\Theta},\mathcal F_{U,\Theta})$.''',[6],[1],[r'\mathcal M(\Omega_{U,\Theta},\mathcal F_{U,\Theta})'],'All Borel probability measures on the radial-angular product domain; T1 does not assume a particular data distribution or independence of coordinates.','Section 2.3 — Product probability measures')
add(5,'characteristic',r'''Recall that a kernel $\kappa$ is characteristic if the mapping $P\mapsto\int\kappa(\cdot,X)\,dP$ is injective. Here, the dot notation $\int\kappa(\cdot,X)\,dP$ simply means the function $x\mapsto\int\kappa(x,X)\,dP$. So $\kappa$ being characteristic means if $\int\kappa(x,X)\,dP_1=\int\kappa(x,X)\,dP_2$ for all $x$ then $P_1=P_2$.''',[6],[2],[r'P\mapsto\int\kappa(\cdot,X)\,dP'],'Injectivity of the probability mean embedding, assuming the displayed integrals exist. Do not replace it by a generic positive-definiteness condition, or import it into concentration theorems that do not assume it.','Section 2.3 — Characteristic kernel')
add(6,'mean and variance',r'''For any $F\in\mathcal F$, let
\[
\mu(F)=\int x\,dF(x),\qquad\Sigma(F)=\int(x-\mu(F))(x-\mu(F))^\top\,dF(x).
\]
Clearly, $\mu(F_0)=\mu$, $\mu(F_n)=\widehat\mu$, $\Sigma(F_0)=\Sigma$, and $\Sigma(F_n)=\widehat\Sigma$.''',[10,11],[],[r'\mu(F)',r'\Sigma(F)'],'Population mean/covariance functionals on distributions with the needed moments. F0 is the true distribution and Fn the empirical distribution. Positive definiteness is needed when inverse square roots are used; finite variance alone does not guarantee it.','Section 5.2 — Mean and covariance functionals',context='In this paper, we always assume that X has finite mean and variance.',context_page=4)
add(7,'arc tangent function',r'''For a real number $r\in\mathbb R$, let $\arctan(r)$ be the unique $\theta\in(-\pi/2,\pi/2)$ such that $r=\tan(\theta)$. Then, for $(x,y)\in\mathbb R^2$, let
\[
\operatorname{Arctan}(x,y)=\begin{cases}
\arctan(y/x),&x>0,\\
\arctan(y/x)+\pi,&x<0,y\ge0,\\
\arctan(y/x)-\pi,&x<0,y<0,\\
\pi/2,&x=0,y>0,\\
-\pi/2,&x=0,y<0.
\end{cases}
\]
(2.5)''',[4],[],[r'\operatorname{Arctan}(x,y)'],'Quadrant-aware angle with the source’s branch conventions; no value at (0,0) is given. No totalized arctangent is substituted.','Section 2.2 — Arctangent (2.5)',context='the precise meaning of the arc tangent function',context_page=4)
add(8,'polar coordinate transformation',r'''In the following, we use $S_j$ to denote the Euclidean norm of the vector $(v_j,\ldots,v_d)^\top$.
The following function from $\Omega_\Theta$ to $S^{d-1}$
\[
v_1=\sin\theta_1,\quad v_2=\cos\theta_1\sin\theta_2,\quad\ldots,\quad v_{d-1}=\cos\theta_1\cos\theta_2\cdots\cos\theta_{d-2}\sin\theta_{d-1},\quad v_d=\cos\theta_1\cos\theta_2\cdots\cos\theta_{d-2}\cos\theta_{d-1}.
\]
(2.6)
is bijective with inverse
\[
\theta_j=\begin{cases}\operatorname{Arctan}(S_{j+1},v_j),&j=1,\ldots,d-2,\\\operatorname{Arctan}(v_d,v_{d-1}),&j=d-1.\end{cases}
\]
(2.7)
We will denote the first function (2.6) as $v=\rho(\theta)$ and the second function (2.7) as $\theta=g(v)$. Then $x=uv=u\rho(\theta)\equiv\tau(u,\theta)$.''',[5],[1,7],[r'\theta=g(v)',r'\operatorname{Arctan}(S_{j+1},v_j)'],'Original polar chart formulas, including the source’s global bijectivity claim. Poles and zero radius prevent literal global bijectivity; regular-coordinate or almost-everywhere interpretation is necessary and recorded separately.','Lemma 1 and following notation — Polar maps',kind='source_passage',context='where $g(\cdot)$ is the polar coordinate transformation',context_page=7)
add(9,'centered and rescaled version',r'''For any $x\in\Omega_X$, let
\[
W(x)=\Sigma^{-1/2}(x-\mu),\quad U(x)=\|W(x)\|,\quad V(x)=W(x)/U(x),\quad\Theta(x)=g(V(x)).
\]''',[7],[6,8],[r'W(x)=\Sigma^{-1/2}(x-\mu)',r'\Theta(x)=g(V(x))'],'Population whitening, radius, direction and polar angle. Sigma denotes covariance rather than the original unnormalized elliptical shape matrix. Requires invertibility and nonzero radius where the formulas are evaluated.','Section 3 — Population transformations',context='replacing X with its centered and rescaled version',context_page=2)
add(10,'known distribution',r'''$P_\Theta$ has p.d.f. $f_\Theta(\theta)=c\cos^{d-2}(\theta_1)\cos^{d-3}(\theta_2)\cdots\cos(\theta_{d-2})$, where $\theta\in\Omega_\Theta$ and $c=(\int_{\Omega_\Theta}\cos^{d-2}(\theta_1)\cos^{d-3}(\theta_2)\cdots\cos(\theta_{d-2})\,d\theta)^{-1}$.
$P_0$ is the known true $P_\Theta$ with its form given in Proposition 2.''',[5,6],[1],[r'P_0',r'f_\Theta(\theta)'],'Fixed angular law induced by uniform direction on the sphere. It is a reference distribution under alternatives, not the observed angular marginal.','Proposition 2 and Corollary 1 — Reference angular law',kind='source_passage',context='Θ has a known distribution.',context_page=5)
add(11,'centered kernel function',r'''For convenience, let $\widetilde\kappa_\Theta(\cdot,\theta)=\kappa_\Theta(\cdot,\theta)-\int\kappa_\Theta(\cdot,\theta)\,dP_0(\theta)$ denote the centered kernel function in $\mathcal H_\Theta$.''',[7],[2,10],[r'\widetilde\kappa_\Theta(\cdot,\theta)'],'Angular feature centered against the fixed reference law P0. This is not empirical centering or centering against the actual angular marginal under an alternative.','Section 3 — Reference-centered feature')
add(12,'cross-covariance operator',r'''Let
\[
\Sigma_{U\Theta}=E[\kappa_U(\cdot,U)\otimes\kappa_\Theta(\cdot,\Theta)]-E[\kappa_U(\cdot,U)]\otimes E_0[\kappa_\Theta(\cdot,\Theta)]
\]
(3.1)
where $E_0$ refers to the expectation with respect to $P_0$. Note that $\Sigma_{U\Theta}$ is different from a usual cross-covariance operator between two random variables, because $P_\Theta$ is given the specific form $P_0$.
$\Sigma_{U\Theta}=E[\kappa_U(\cdot,U)\otimes\widetilde\kappa_\Theta(\cdot,\Theta)]$.''',[7],[3,9,11],[r'\Sigma_{U\Theta}',r'E_0'],'Difference of joint mean embedding and radial mean times fixed angular reference mean. It tests more than independence. Preserve the source’s name and its explicit distinction from ordinary cross-covariance.','Section 3 — Population discrepancy (3.1)')
add(13,'sample estimate',r'''Let
\[
\breve\Sigma_{U\Theta}=E_n[\kappa_U(\cdot,\widehat U)\otimes\kappa_\Theta(\cdot,\widehat\Theta)]-E_n[\kappa_U(\cdot,\widehat U)]\otimes E_0[\kappa_\Theta(\cdot,\Theta)],
\]
(3.3)
$\breve\Sigma_{U\Theta}=E_n[\kappa_U(\cdot,\widehat U)\otimes\widetilde\kappa_\Theta(\cdot,\widehat\Theta)]$.''',[7],[3,11,32],[r'\breve\Sigma_{U\Theta}',r'\widehat U',r'\widehat\Theta'],'Empirical feature average after estimating mean and covariance on the same data; the angular centering still uses known P0. The distinct known-parameter formula (7.1) is stored separately.','Section 3 — Estimated-parameter discrepancy (3.3)',context='this operator is not the usual sample estimate of the cross-covariance operator',context_page=7)
add(14,'Hilbert-Schmidt norm',r'''The squared Hilbert-Schmidt norm $\|\breve\Sigma_{U\Theta}\|_{\mathrm{HS}}^2$ is the sum of eigenvalues of the operator $\breve\Sigma_{U\Theta}\breve\Sigma_{U\Theta}^*$, where $\breve\Sigma_{U\Theta}^*$ is the adjoint operator of $\breve\Sigma_{U\Theta}$. This is analogous to the Frobenius norm of a matrix.''',[7],[3],[r'\|\breve\Sigma_{U\Theta}\|_{\mathrm{HS}}'],'Hilbert-Schmidt operator norm, with squared norm equal to trace of AA*. This norm is used for population, estimated-parameter and known-parameter operators; its definition does not impose a particular estimator.','Section 3 — Operator norm')
add(15,'Frechet differentiable',r'''Let $\mathcal F$ denote the class of all distributions on $(\Omega_X,\mathcal F_X)$. Let $\mathcal H$ be a generic Hilbert space. Let $T:\mathcal F\to\mathcal H$ be a mapping — such mappings are known as statistical functionals. Endow $\mathcal F$ with the uniform metric, and $\mathcal H$ with the metric induced by its inner product. Let $F_0$ be a member of $\mathcal F$. Then $T$ is Frechet differentiable at $F_0$ if there is a linear operator $A:\mathcal F\to\mathcal H$ such that
\[
\lim_{\|F-F_0\|_{\mathcal F}\to0}\frac{\|T(F)-T(F_0)-A(F-F_0)\|_{\mathcal H}}{\|F-F_0\|_{\mathcal F}}=0.
\]''',[10],[],[r'\|F-F_0\|_{\mathcal F}',r'T(F)-T(F_0)-A(F-F_0)'],'Printed differentiability condition for the distribution functional. A vector space of signed directions and the precise multivariate uniform-metric realization are implicit; probability measures alone are not a linear domain. T2 explicitly assumes this property; T3 does not restate it.','Section 5.1 — Functional differentiability')
add(16,'statistical functional',r'''For each $x\in\Omega_X$, let
\[
W(x,F)=\Sigma(F)^{-1/2}(x-\mu(F)),\quad U(x,F)=\|W(x,F)\|,\quad V(x,F)=W(x,F)/U(x,F),\quad\Theta(x,F)=g(V(x,F)).
\]''',[11],[6,8],[r'U(x,F)',r'\Theta(x,F)'],'Distribution-dependent whitening, radius, direction and angle evaluated at arbitrary F, reducing to population or fitted transforms at F0 or Fn.','Section 5.2 — Transformation functionals',context='Now let us consider the statistical functional',context_page=10)
add(17,'statistical functional',r'''\[
\Sigma_{U\Theta}(F)=\int\kappa_U(\cdot,U(x,F))\otimes\kappa_\Theta(\cdot,\Theta(x,F))\,dF(x)-\int\kappa_U(\cdot,U(x,F))\,dF(x)\otimes\int\kappa_\Theta(\cdot,\theta)\,dP_0(\theta).
\]
(5.2)
The operator in (5.2) can be re-expressed via the centered kernel as
\[
\Sigma_{U\Theta}(F)=\int\kappa_U(\cdot,U(x,F))\otimes\widetilde\kappa_\Theta(\cdot,\Theta(x,F))\,dF(x).
\]
(5.3)''',[11],[3,11,16],[r'\Sigma_{U\Theta}(F)'],'Operator-valued functional: both the transforms and outer integration depend on F, whereas P0 is held fixed. It is the operator, not its squared norm, to which T2 applies the delta method.','Section 5.2 — Discrepancy functional',context='Our statistical functional of interest',context_page=11)
add(18,'influence function',r'''we denote the influence function of the statistical functional $F\mapsto G(x,F)$ as $G^\star(x,z)$. That is,
\[
G^\star(x,z)=[\partial G(x,(1-\epsilon)F_0+\epsilon\delta_z)/\partial\epsilon]_{\epsilon=0}.
\]''',[11],[],[r'G^\star(x,z)',r'(1-\epsilon)F_0+\epsilon\delta_z'],'Contamination derivative at fixed x, with z as the contamination point. Star denotes influence, whereas the separate asterisk denotes an adjoint. The derivative definition alone is not the Frechet regularity assumption.','Section 5.3 — Influence-function convention')
add(19,'influence function',r'''If $X$ is integrable, then the influence function of $\mu$ is $\mu^\star(z)=z-\mu$. Furthermore, if $X$ is square integrable, then
\[
\Sigma^\star(z)=(z-\mu)(z-\mu)^\top-\Sigma,\qquad(\Sigma^{-1})^\star(z)=-\Sigma^{-1}\Sigma^\star(z)\Sigma^{-1},
\]
(5.4)
\[
\operatorname{vec}[(\Sigma^{-1/2})^\star(z)]=-(\Sigma^{1/2}\otimes\Sigma+\Sigma\otimes\Sigma^{1/2})^{-1}\operatorname{vec}[\Sigma^\star(z)],
\]
(5.5)
where, for a matrix $A$ with columns $a_1,\ldots,a_m$, $\operatorname{vec}(A)$ denotes the vector $(a_1^\top,\ldots,a_m^\top)^\top$.''',[11],[6,18],[r'\mu^\star(z)',r'\Sigma^\star(z)',r'(\Sigma^{-1/2})^\star(z)'],'Original influence formulas for moments and inverse square root, including columnwise vectorization and the Kronecker-sum inverse. Invertibility and moments are retained as domain requirements rather than filled in as unquoted theorem assumptions.','Lemma 2 — Moment influence formulas',kind='source_passage')
add(20,'influence functions',r'''Suppose that $F\mapsto U(x,F)$, $F\mapsto V(x,F)$ and $F\mapsto\Theta(x,F)$ are Frechet differentiable at $F_0$. Let
\[
A_1(x)=-\frac{(x-\mu)^\top\Sigma^{-1}}{[(x-\mu)^\top\Sigma^{-1}(x-\mu)]^{1/2}},\qquad A_2(x)=-\frac{[(x-\mu)^\top\Sigma^{-1}]\otimes[(x-\mu)^\top\Sigma^{-1}]}{2[(x-\mu)^\top\Sigma^{-1}(x-\mu)]^{1/2}},
\]
\[
B_1(x)=-\frac{\Sigma^{-1/2}(x-\mu)A_1(x)}{(x-\mu)^\top\Sigma^{-1}(x-\mu)}-\frac{\Sigma^{-1/2}}{[(x-\mu)^\top\Sigma^{-1}(x-\mu)]^{1/2}},
\]
\[
B_2(x)=-\frac{\Sigma^{-1/2}(x-\mu)A_2(x)}{(x-\mu)^\top\Sigma^{-1}(x-\mu)}-\frac{[(x-\mu)^\top\otimes I_d](\Sigma^{1/2}\otimes\Sigma+\Sigma\otimes\Sigma^{1/2})^{-1}}{[(x-\mu)^\top\Sigma^{-1}(x-\mu)]^{1/2}},
\]
\[
C_i(x)=[\partial g(V(x))/\partial v^\top]B_i(x),\quad i=1,2,
\]
(5.6)
where $\partial g(V(x))/\partial v^\top$ is the matrix given by Lemma 3. Then, the influence functions of $U(x,F)$, $V(x,F)$ and $\Theta(x,F)$ are
\[
U^\star(x,z)=A_1(x)\mu^\star(z)+A_2(x)\operatorname{vec}[\Sigma^\star(z)],
\]
(5.7)
\[
V^\star(x,z)=B_1(x)\mu^\star(z)+B_2(x)\operatorname{vec}[\Sigma^\star(z)],
\]
(5.8)
\[
\Theta^\star(x,z)=C_1(x)\mu^\star(z)+C_2(x)\operatorname{vec}[\Sigma^\star(z)].
\]
(5.9)''',[12],[15,16,19],[r'U^\star(x,z)',r'\Theta^\star(x,z)',r'A_1(x)',r'C_i(x)'],'Full source coefficient and influence formulas, including their differentiability premise. The polar derivative is the derivative of the archived g chart, defined on regular coordinates. Its illustrative matrix in Lemma3 contains index typos; no repaired matrix is inserted into this quotation.','Lemma 4 — Transformation influence functions',kind='source_passage')
add(21,'partial derivative',r'''Henceforth, for a kernel function $\kappa(\cdot,t)$, we use $\dot\kappa(\cdot,t)$ to denote the partial derivative with respect to the second argument, $\partial\kappa(\cdot,t)/\partial t$.''',[12],[2],[r'\dot\kappa(\cdot,t)'],'Feature derivative in the second argument; vector-valued for angular inputs. This notation alone is not the C² bounded-Hessian assumption.','Section 5.3 — Kernel derivative notation')
add(22,'influence function',r'''Suppose $F\mapsto\Sigma_{U\Theta}(F)$ is Frechet differentiable at $F_0$. Then
\[
\Sigma_{U\Theta}^\star(z)=\kappa_U(\cdot,U(z))\otimes\widetilde\kappa_\Theta(\cdot,\Theta(z))-\Sigma_{U\Theta}+E\{[\dot\kappa_U(\cdot,U(X))U^\star(X,z)]\otimes\widetilde\kappa_\Theta(\cdot,\Theta(X))\}+E\{\kappa_U(\cdot,U(X))\otimes\dot\kappa_\Theta(\cdot,\Theta(X))^\top\Theta^\star(X,z)\},
\]
(5.10)
where $U^\star(x,z)$ and $\Theta^\star(x,z)$ are given by Lemma 4.''',[12],[3,9,11,12,15,17,20,21],[r'\Sigma_{U\Theta}^\star(z)',r'-\Sigma_{U\Theta}'],'Full discrepancy influence function, including the negative population term and both corrections for estimated location/scatter. It is not the null-only version that drops Sigma_UTheta, nor the later empirically centered estimator.','Lemma 5 — Discrepancy influence function (5.10)',kind='source_passage',context='The next lemma gives the influence function of',context_page=12)
add(23,'twice differentiable',r'''\[
\kappa_U\in C^2(\Omega_U\times\Omega_U),\qquad\kappa_\Theta\in C^2(\Omega_\Theta\times\Omega_\Theta),
\]
(5.11)
where, for a set $A\subseteq\mathbb R^m$, $C^2(A\times A)$ denotes the set of all real-valued functions on $A\times A$ that are twice differentiable with a bounded Hessian matrix.''',[13],[2],[r'\kappa_U\in C^2',r'\kappa_\Theta\in C^2'],'The source’s C² convention explicitly includes bounded Hessian. It is distinct from Assumption4’s feature-space Lipschitz bounds and is explicitly invoked only in T2.','Section 5.3 — Kernel smoothness (5.11)',kind='condition')
add(24,'operator',r'''$\Gamma:\mathcal H_U\otimes\mathcal H_\Theta\to\mathcal H_U\otimes\mathcal H_\Theta$ is the operator
\[
\Gamma=E[\Sigma_{U\Theta}^\star(X)\otimes\Sigma_{U\Theta}^\star(X)],
\]
and $\Sigma_{U\Theta}^\star(z)$ is given by (5.10).''',[13],[3,22],[r'\Gamma',r'E[\Sigma_{U\Theta}^\star(X)\otimes\Sigma_{U\Theta}^\star(X)]'],'Covariance operator of the centered discrepancy influence element, on the tensor RKHS. Theorem3 uses its spectral decomposition; zero eigenvalues and local-alternative regularity require separate treatment.','Theorem 2 — Asymptotic covariance operator',kind='theorem_excerpt')
add(25,'test statistic',r'''In this case $\widehat U$ and $\widehat\Theta$ are replaced by $U$ and $\Theta$, and our test statistic reduces to
\[
\breve\Sigma_{U\Theta}=E_n[\kappa_U(\cdot,U)\otimes\kappa_\Theta(\cdot,\Theta)]-E_n[\kappa_U(\cdot,U)]\otimes E[\kappa_\Theta(\cdot,\Theta)].
\]
(7.1)''',[18],[2,3,9],[r'\breve\Sigma_{U\Theta}',r'\otimes E[\kappa_\Theta(\cdot,\Theta)]'],'Known-parameter statistic exactly as printed, with E rather than E0 in its last factor. Under an alternative this centers against the actual angular marginal, unlike the target Sigma in (3.1). Preserve and flag the discrepancy; no silent correction.','Section 7.1 — Known-parameter formula (7.1)')
add(26,'absolute constant',r'''we call a constant that doesn’t depend on $d$ or $n$ an absolute constant.''',[19],[],[], 'Dimension- and sample-size-independent constants, allowing dependence on fixed distribution/kernel parameters as permitted by context. Repeated c1,c2 labels are reused across assumptions and rate definitions.','Section 7.2 — Absolute constants',phrases=['absolute constant'])
add(27,'covariance matrix',r'''There exist absolute constants $c_1>0$ and $c_2>0$ such that
\[
c_1\le\lambda_{\min}(\Sigma)\le\lambda_{\max}(\Sigma)\le c_2.
\]''',[19],[6,26],[r'\lambda_{\min}(\Sigma)',r'\lambda_{\max}(\Sigma)'],'Uniform positive lower and upper covariance eigenvalue bounds, independent of d and n. Not just pointwise nonsingularity.','Assumption 1',kind='assumption',context='the mean vector and covariance matrix',context_page=2)
add(28,'uniform sub-Gaussian distribution',r'''The random vector $X$ has a uniform sub-Gaussian distribution in the sense that, there is a constant $\sigma^2$ that is independent of $d$ such that, for all $v\in\mathbb S$,
\[
E(e^{\lambda\langle v,X-\mu\rangle})\le e^{\sigma^2\lambda^2/2}.
\]''',[19],[6],[r'E(e^{\lambda\langle v,X-\mu\rangle})'],'Dimension-uniform directional MGF bound centered at mu. The source prints S without a dimension and leaves the lambda quantifier implicit; record the intended unit sphere and all-real-lambda interpretation separately.','Assumption 2',kind='assumption')
add(29,'density',r'''The density of $W$ is bounded by $c^d$ for some absolute constant $c$.''',[19],[9,26],[r'c^d'],'Density bound for whitened W, with exponential dependence on dimension. The superscript d must not be transcribed as multiplication by d.','Assumption 3',kind='assumption')
add(30,'bounded and Lipschitz continuous',r'''The kernel functions $\kappa_U$ and $\kappa_\Theta$ are bounded and Lipschitz continuous:
\[
0\le\kappa_U(u,u')\le M_U,\quad\forall u,u',\qquad0\le\kappa_\Theta(\theta,\theta')\le M_\Theta,\quad\forall\theta,\theta',
\]
and
\[
\|\kappa_U(\cdot,u)-\kappa_U(\cdot,u')\|\le L_U|u-u'|,\quad\forall u,u',
\]
(7.4)
\[
\|\kappa_\Theta(\cdot,g(v))-\kappa_\Theta(\cdot,g(v'))\|\le d^{-1}L_V\|v-v'\|,\quad\forall v,v'.
\]
(7.5)''',[19],[2,8],[r'd^{-1}L_V',"L_U|u-u'|"], 'Feature-space Lipschitz control for the radial input and angular feature composed with the polar map, with explicit d^−1 scaling. The left norms are RKHS norms and the directional right norm is Euclidean. Not merely scalar-kernel Lipschitz continuity.','Assumption 4',kind='assumption')
add(31,'concentration bounds',r'''Let
\[
f_1(n,d,u)=c_1\sqrt{\frac{d[\log(2d)+u]}n},\qquad f_2(n,d,u)=c_2d\max\left\{\left[\frac{d+u}n\right]^{1/4},\left[\frac{d+u}n\right]^{1/2}\right\}+c_3\sqrt d,
\]
\[
f_3(n,d,u)=c_4d\sqrt{\frac{d+u}n},\qquad f_4(n,u)=c_9\sqrt{\frac un}+c_{10}\sqrt{\frac1n},
\]
(7.6)
where $c_1,c_2,c_3,c_4,c_9,c_{10}$ are some positive absolute constants.''',[19],[26],[r'f_1(n,d,u)',r'f_2(n,d,u)',r'f_3(n,d,u)',r'f_4(n,u)'],'The exact four rate functions in T5, including the max of quarter- and half-power terms and the c3 sqrt(d) term. T6 inherits assumptions only, not these bound-specific definitions. T5 writes f4(n,u), matching the definition.','Section 7.2 — Rate functions (7.6)',context='we would like our concentration bounds to reflect',context_page=19)
add(32,'sample mean and sample variance',r'''Let $X_1,\ldots,X_n$ be an i.i.d. sample of $X$. For a function $A(x)$, we use $E_nA(X)$ to denote the sample average of $A(X_1),\ldots,A(X_n)$. Let $\widehat\mu$ and $\widehat\Sigma$ denote the sample mean and sample variance; that is, $\widehat\mu=E_n(X)$ and $\widehat\Sigma=E_n[(X-\widehat\mu)(X-\widehat\mu)^\top]$.
\[
\widehat W(x)=\widehat\Sigma^{-1/2}(x-\widehat\mu),\quad\widehat U(x)=\|\widehat W(x)\|,\quad\widehat V(x)=\widehat W(x)/\widehat U(x),\quad\widehat\Theta(x)=g(\widehat V(x)).
\]''',[7],[8],[r'\widehat\Sigma=E_n',r'\widehat\Theta(x)'],'Sample moments with n-denominator covariance and fitted whitening/radius/direction/angle. Finite-sample invertibility and polar exceptional points are explicit domain concerns; no regularized or pseudoinverse estimator is inserted.','Section 3 — Sample moments and transformations')
# Source-inspected rendering amendment; see the explicit saved review plan.
members['D14']['highlight_symbols'] = ['\\|\\breve\\Sigma_{U\\Theta}\\|_{\\mathrm{HS}}^2']
members['D22']['highlight_symbols'] = ['\\Sigma_{U\\Theta}^\\star(z)', '\\Sigma_{U\\Theta}']
members['D25']['highlight_symbols'] = ['\\breve\\Sigma_{U\\Theta}', 'E[\\kappa_\\Theta(\\cdot,\\Theta)]']

def main():
    (ROOT/'source-passages.json').write_text(json.dumps(dict(paper_id=PID,members=list(members.values())),indent=2,ensure_ascii=False)+'\n')
    (ROOT/'interface-extraction.json').write_text(json.dumps(dict(paper_id=PID,interfaces=interfaces),indent=2,ensure_ascii=False)+'\n')
if __name__=='__main__':main()
