"""Preserve original context and unresolved source conventions separately from theorem quotations."""
import json
from save_inventory import ROOT,PID

def main():
    aux=[]
    def add(n,s,pages,note,deps=()):aux.append(dict(local_id='A'+str(n),statement_original=s,evidence=[dict(page=p,location='Original main-text context A'+str(n)) for p in pages],scope_note=note,depends_on=list(deps)))
    add(1,r'''More generally, $X$ is said to have an elliptical distribution centered at $\mu\in\mathbb R^d$ with a positive definite shape parameter $\Lambda\in\mathbb R^{d\times d}$ if
1. $P_X$ is dominated by the Lebesgue measure in $\mathbb R^d$ with density $f_X=dP_X/d\lambda$;
2. the density of $X$ is a function of $(x-\mu)^\top\Lambda^{-1}(x-\mu)$, that is,
\[
f_X(x)=|\Lambda|^{-1/2}h((x-\mu)^\top\Lambda^{-1}(x-\mu)),
\]
for some nonnegative function $h$ satisfying (2.2), where $|\Lambda|$ denotes the determinant of $\Lambda$.
\[
\int_{-\infty}^{\infty}\cdots\int_{-\infty}^{\infty}h(x^\top x)\,dx_1\cdots dx_d=1.
\]
(2.2)''',[3,4],'Original density-based notion and its normalization. The theorem inventory concerns kernel embeddings and statistics; elliptical distribution is the testing problem, not an assumption added to every theorem. Singular elliptical laws outside this source definition are not silently included.')
    add(2,r'''In this paper, we always assume that $X$ has finite mean and variance.''',[4],'Standing population-moment convention. Positive definiteness of covariance and finite-sample invertibility still need to be distinguished from finiteness.',['D6'])
    add(3,r'''Thus, our goal is to test the hypothesis $H_0:\Sigma_{U\Theta}=0$.
(3.2)
We use $T_n=n\|\breve\Sigma_{U\Theta}\|_{\mathrm{HS}}^2$ as our test statistic for the hypothesis (3.2).''',[7],'T2 is centered around general Sigma_UTheta; only the corollaries impose H0. Characteristic kernels connect the zero-discrepancy null to ellipticity, but are not explicitly reimposed in the concentration inequalities.',['D12','D13','D14'])
    add(4,r'''An equivalent definition of $\|\Sigma_{U\Theta}\|_{\mathrm{HS}}$ is
\[
\|\Sigma_{U\Theta}\|_{\mathrm{HS}}=\|E[\kappa_U(\cdot,U)\otimes\kappa_\Theta(\cdot,\Theta)]-E[\kappa_U(\cdot,U)]\otimes E_0[\kappa_\Theta(\cdot,\Theta)]\|_{\mathrm{HS}}=\sup_{f_1\otimes f_2\in\mathcal F}|E_{P_{U\Theta}}[f_1(U)f_2(\Theta)]-E_{P_U}[f_1(U)]E_{P_0}[f_2(\Theta)]|
\]
where $\mathcal F=\{f_1\otimes f_2\in\mathcal H_U\otimes\mathcal H_\Theta:\|f_1\otimes f_2\|\le1\}$.''',[8],'The printed supremum is over simple tensors, which generally gives the operator norm rather than the Hilbert-Schmidt norm. Preserve the passage as a source issue; keep the trace-of-AA* definition for the theorem norm.',['D3','D12','D14'])
    add(5,r'''Under the null hypotheses $H_0:\Sigma_{U\Theta}=0$ and the conditions in Theorem 2, we have
\[
n\|\breve\Sigma_{U\Theta}\|_{\mathrm{HS}}^2\xrightarrow{\mathcal D}\sum_{i=1}^{\infty}\lambda_iZ_i^2,
\]
(5.13)
where $Z_1,Z_2,\ldots$ are i.i.d. standard normal random variables, and $\lambda_1,\lambda_2,\ldots$ are eigenvalues of $\Gamma$ in Corollary 2.''',[13],'Corollary3 explains the calibration distribution. It is not an additional Theorem environment or a premise of the concentration statements.',['D13','D14','D24'])
    add(6,r'''Notice that $\widehat\Gamma$ is a consistent estimator of $\Gamma$. Suppose that $\sum_{j=1}^\infty\lambda_j^{1/2}<\infty$, then, by Theorem 1 of Gretton et al. (2009), we have
\[
\sum_{j=1}^n\widehat\lambda_jZ_j^2\xrightarrow{\mathcal D}\sum_{j=1}^\infty\lambda_jZ_j^2,
\]
which indicates the validity of the test.''',[18],'Additional square-root eigenvalue summability is stated in calibration prose, not among the numbered theorem assumptions. Estimated-Gamma implementation is contextual and is not imported into Theorem3’s population Gamma.',['D24'])
    add(7,r'''One side-note is that we add a small number, $\epsilon=10^{-6}$, to the diagonal of a matrix whenever we compute its inverse, square-root or eigenvalues. This is done to avoid numerical instability that can happen in some extreme samples.''',[20],'Simulation-only numerical regularization. It does not change the exact covariance inverse or estimator definitions in the census.',['D32'])
    add(8,r'''\[
\kappa_U(u_1,u_2)=\exp[-\gamma_U(u_1-u_2)^2],\qquad\kappa_\Theta(\theta_1,\theta_2)=\exp(-\gamma_\Theta\|\theta_1-\theta_2\|^2),
\]
(2.11)
for some $\gamma_U,\gamma_\Theta>0$''',[6],'Gaussian radial basis examples are not an assumption that restricts every theorem to this kernel family. In particular, Assumption4 must be checked for the feature composed with the polar map.',['D2'])
    issues=[]
    def issue(i,pages,note):issues.append(dict(issue_id=i,evidence=[dict(page=p,location='Source scope or notation issue') for p in pages],note=note))
    issue('density-and-inverse-domains',[3,4,7,19],'The source defines elliptical laws via a Lebesgue density and assumes finite mean/covariance. Population whitening requires nonsingular covariance; sample whitening requires invertible sample covariance, which in the absolutely continuous case needs n>d. No pseudoinverse or ridge correction is in the original theorem definitions.')
    issue('polar-exceptional-sets',[4,5,7,12],'Arctan(0,0) is undefined and direction is undefined at radius zero. The claimed global chart bijection fails at poles, where multiple angle vectors describe the same direction, and at excluded latitude endpoints. Use the printed formulas and record the need for regular-coordinate or almost-everywhere conventions; do not invent a global inverse.')
    issue('tensor-index-and-star-conventions',[6,10,12],'The finite tensor inner-product display uses tilde-alpha-r with tilde-f-s in its last second-sum term. Preserve this printed mismatch. Star denotes an influence derivative, asterisk an adjoint; Gamma’s outer tensor acts on the tensor RKHS rather than directly between the two base RKHSs.')
    issue('embedding-and-clt-domain',[6,10,13],'Theorem1 quantifies over all probability measures without separately stating kernel measurability or embedding integrability. Theorem2 assumes Frechet differentiability and (5.11), but does not explicitly list the influence element’s square integrability, covariance trace or Hilbert-space empirical-process conditions needed for a CLT. Record the printed result; do not certify that the hypotheses suffice.')
    issue('frechet-linear-domain',[10,11],'The source calls A:F→H linear even though F is a class of probability distributions and uses A(F−F0). The signed-measure tangent domain and exact multivariate uniform metric are implicit. The influence formula uses contamination directions; it is not an adjoint operation.')
    issue('local-alternative-and-zero-eigenvalues',[13,14],'Theorem3 refers to Gamma and gives two spectral/local-shift conditions without explicitly restating Theorem2’s assumptions or specifying a triangular-array CLT under local alternatives. Its shifted-normal mean sigma_j/sqrt(lambda_j) is undefined at zero eigenvalues unless a separate convention is provided; none is printed. Do not silently require all eigenvalues positive or drop null-space shifts.')
    issue('known-parameter-centering',[7,18],'Equation(7.1) prints E[kappa_Theta] while (3.1) and (3.3) use E0 under the fixed spherical angular law. Off the null these differ, so the printed known-parameter statistic may have a different population target from Sigma_UTheta in Theorem4. Preserve the discrepancy; do not silently replace E by E0 or impose the null on the theorem.')
    issue('hilbert-schmidt-versus-simple-tensors',[7,8],'The trace-of-AA* definition gives the Hilbert-Schmidt norm. The claimed equivalent supremum on page8 is restricted to simple unit tensors and generally gives the operator norm instead. Retain the original norm used in the theorem statements and flag this explanatory mismatch.')
    issue('subgaussian-sphere-and-quantifiers',[19],'Assumption2 prints v∈S without a dimension and leaves the quantifier on lambda unstated. Its intended meaning is every unit direction and all real lambda; preserve the printed inequality and record the missing explicit conventions. Assumption3 is c^d, not c*d.')
    issue('feature-lipschitz-versus-coordinate-smoothness',[13,19],'Assumption4 is a bound on RKHS feature differences, with the angular feature composed with g and scaled by d^−1. It is distinct from C² bounded-Hessian condition(5.11), and can be affected by chart discontinuities. Do not infer it merely from scalar-kernel smoothness or from choosing a Gaussian kernel.')
    issue('concentration-parameters-and-constants',[18,19],'Theorem4 does not explicitly quantify t; its tail-bound interpretation uses t≥0 and positive kernel bound product. Theorem5 explicitly quantifies epsilon>0 but leaves the nonnegative tail parameter u implicit. Absolute constants are independent of n,d. Reused c1,c2 in Assumption1 and (7.6) should not be assumed numerically identical without further source information.')
    issue('growing-dimension-target',[19],'Theorem6 uses log n≺d≺n^(1/4) without a separate definition of ≺ in the inspected main text; interpret as vanishing ratios for the stated asymptotic regime and retain the original notation. The convergence compares a sequence of norms with a possibly dimension-dependent target, not necessarily a fixed limiting real number. It inherits Theorem5’s assumptions, not its rate functions as premises.')
    issue('implementation-not-theorem-definition',[7,10,15,17,18,20],'The source refers to g as (2.6) on page7 although g is the inverse (2.7). Coordinate sections assume nonsingular Gram matrices; the displayed final m-hat formula uses e_j in an unsummed first term. Equation(4.5) ends its product at d−2 although (4.3) has d−1 factors. These implementation issues do not authorize changing the population/statistic definitions, and simulation ridge adjustments are not theorem assumptions.')
    refs=[dict(from_claim_id=PID+'/T1',to_source_label='Theorem 4 of Szabo and Sriperumbudur (2018)',reference_kind='proof_only',scope='External proof attribution; keep the locally labeled Theorem1, without searching or importing an external theorem statement.'),dict(from_claim_id=PID+'/T2',to_source_label='Lemma 5, equation (5.10)',reference_kind='definition_reference',scope='Full influence expression, including the population subtraction and both estimation corrections; follow its local formula definitions.'),dict(from_claim_id=PID+'/T3',to_source_label='Gamma in Theorem 2 and Corollary 2',reference_kind='definition_reference',scope='Covariance operator for the spectral decomposition; no explicit import of all Theorem2 assumptions is printed. Local-alternative regularity is flagged separately.'),dict(from_claim_id=PID+'/T4',to_source_label='Equation (7.1)',reference_kind='definition_reference',scope='Known-parameter formula exactly as printed, including E rather than E0.'),dict(from_claim_id=PID+'/T4',to_source_label='Supplementary Material',reference_kind='proof_only',scope='Deferred proof; appendix bodies excluded.'),dict(from_claim_id=PID+'/T5',to_source_label='Equation (7.6)',reference_kind='definition_reference',scope='Exact four concentration functions and their absolute constants.'),dict(from_claim_id=PID+'/T6',to_source_label='Theorem 5',reference_kind='assumption_reference',scope='Iid sampling and Assumptions1–4; not the tail bound or helper functions f1–f4 as additional assumptions.')]
    bindings={
'T1':'Two positive definite kernels on the stated radial and angular domains, their RKHS/tensor spaces and all product-domain probability measures. Explicitly assumes characteristicness. No elliptical distribution, covariance estimation, polar random-variable transformation, smoothness or concentration assumption is added.',
'T2':'Iid source sampling; full estimated-parameter operator (3.3) and population operator (3.1). Explicit Frechet condition on F↦Sigma_UTheta(F) and bounded-Hessian kernel condition(5.11). Gamma is defined from the full influence formula(5.10) with both location/scatter corrections and the negative population term. The theorem itself is not restricted to H0.',
'T3':'Same discrepancy/statistic objects and population covariance Gamma, together with the printed orthonormal spectral decomposition and fixed nonzero local shift Sigma1. No full Theorem2-assumption reference is printed. Conditional influence-formula definitions are retained to identify Gamma; local-alternative CLT conditions and zero-eigenvalue conventions remain unresolved source issues.',
'T4':'Known mu,Sigma, the literal formula(7.1), nonnegative bounded kernels and the Hilbert-Schmidt norm. No Assumptions1–4, characteristicness, Frechet regularity or estimated-parameter correction is required by the printed statement. The E-versus-E0 target discrepancy is preserved separately.',
'T5':'Iid sampling; population moments and fitted whitening; Assumptions1–4 with c^d whitened-density bound and d^−1 angular feature Lipschitz factor. Exact f1–f4 formulas, epsilon>0, and the implicit nonnegative tail parameter u. This is a concentration inequality for the difference of operator norms, not their squared norms.',
'T6':'Inherit iid sampling and Assumptions1–4 from Theorem5, with log n≺d≺n^(1/4). Compare fitted and population Hilbert-Schmidt norms in probability along the growing-dimension sequence. No f1–f4 premise, characteristicness, local alternative or plug-in-eigenvalue calibration assumption is imported.'}
    out=dict(paper_id=PID,status='extracted',unranked_auxiliary_passages=aux,source_issues=issues,source_claim_references=refs,statement_local_bindings=bindings,ambient_prerequisites=['Borel random vectors, finite mean/covariance, iid sampling and empirical averages; symmetric positive definite covariance inverses and square roots on their valid domains.','Euclidean spheres and norms, Dirac contamination directions, distribution functions and uniform metric as used by the source, Frechet and directional derivatives on appropriate domains.','Positive definite kernels, RKHS evaluation, Hilbert tensor products, Bochner-type expectations when defined, Hilbert-Schmidt norm, adjoints, Gaussian Hilbert-space laws and covariance operators.','Kronecker products, columnwise vectorization, matrix derivatives, standard normal variables, spectral decompositions, finite and infinite weighted chi-square sums. Numerical regularization is a separate simulation convention.'],extraction_policy='Six complete main-text Theorems. Preserve definitions, theorem-specific assumptions, original formulas and source issues. Supporting Lemma formulas identify statement objects but are not extra Theorem records. Appendix bodies, proof certification, library search and HTML generation excluded.')
    (ROOT/'ambient-prerequisites.json').write_text(json.dumps(out,indent=2,ensure_ascii=False)+'\n')
if __name__=='__main__':main()
