# -*- coding: utf-8 -*-
"""Reproduce original main-text definitions and condition passages for p1899."""
import json
from save_inventory import PID,ROOT,NUMBERS,STATEMENTS
from save_ambient import A
AUX={a['local_id']:a for a in A}
T=dict(zip(NUMBERS,STATEMENTS))
interfaces=[];members={}
def add(n,term,s,pages,deps,symbols,boundary,heading,kind='definition',context=None,context_page=None):
    lid=f'D{n}'
    m=dict(paper_id=PID,local_id=lid,local_label=heading,source_heading=heading,source_kind=kind,statement_original=s,relation='exact',depends_on=[f'D{i}' for i in deps],evidence=[dict(page=p,location=heading) for p in pages],highlight_symbols=symbols,highlight_phrases=[])
    kw=dict(paper_id=PID,local_id=lid,source_text=term,label=term[0].upper()+term[1:],kind='term')
    if term not in s:
        assert context and term in context,(lid,term)
        m['naming_context']=[dict(context_id=lid+'/name',text=context,evidence=[dict(page=context_page or pages[0],location='Original naming context')])]
        kw['context_id']=lid+'/name'
    members[lid]=m
    interfaces.append(dict(interface_id=PID+'/'+lid,rank_group='all',name=kw['label'],lean_role='definition',type_shape=boundary,semantic_boundary=boundary,members=[m],source_keywords=[kw],central_claim_uses=[],dependencies=[],theorem_explanations={}))
add(1,'data sources',r'''We consider $K$ data sources that generate data simultaneously in discrete time and denote by $X_n^k$ the random element whose value is generated by data source $k\in[K]$ at time $n\in\mathbb N$. For any subset of data sources, $s\subseteq[K]$, we set
\[
X_n^s:=\{X_n^k:k\in s\}\quad\text{and}\quad\mathcal F_n^s:=\sigma(X_m^s:m\in[n]),\qquad n\in\mathbb N,
\]
i.e., $X_n^s$ is the set of observations by the data sources in $s$ at time $n$ and $\mathcal F_n^s$ the $\sigma$-field generated by the observations from the data sources in $s$ up to time $n$, and
\[
X^s:=\{X_n^s,n\in\mathbb N\}\quad\text{and}\quad\mathcal F^s:=\sigma(\mathcal F_n^s,n\in\mathbb N),
\]
i.e., $X^s$ is the complete sequence of observations by the data sources in $s$ and $\mathcal F^s$ the $\sigma$-field it generates. In what follows, we omit the superscipt in the above notations whenever $s=[K]$, and replace it by $k$ whenever $s=\{k\}$ for some $k\in[K]$.''',[3],[],[r'X_n^s',r'\mathcal F_n^s'],'Discrete-time data and subsystem filtrations; no temporal or spatial independence is imposed by this definition.','Section 2.1 — Data')
add(2,'global distributions',r'''We consider a finite family, $\mathcal P$, of plausible distributions of $X$, to the elements of which we refer as global distributions. We say that two subsets of data sources $s_1\subseteq[K]$ and $s_2\subseteq[K]$ are independent under some $P\in\mathcal P$ if $X^{s_1}$ and $X^{s_2}$ are independent under $P$. For any global distribution, $P\in\mathcal P$, and any subset of sources, $s\subseteq[K]$, we denote by $P^s$ the restriction of $P$ on $\mathcal F^s$, i.e., the marginal distribution of $X^s$ under $P$. For any family of global distributions, $\mathcal Q\subseteq\mathcal P$, and any subset of data sources, $s\subseteq[K]$, we set
\[
\mathcal Q^s:=\{P^s:P\in\mathcal Q\},
\]
e.g., $\mathcal P^s$ is the family of distributions of $X^s$ induced by $\mathcal P$. As before, we omit the superscript whenever $s=[K]$, and replace it by $k$ whenever $s=\{k\}$ for some $k\in[K]$.''',[3],[1],[r'P^s',r'\mathcal Q^s'],'Finite family of laws of full observation sequences, their subsystem restrictions and independence of full sequences. This is not merely independence at each time.','Section 2.2 — Global distributions')
add(3,'local hypotheses',r'''We consider a finite family of subsets of $[K]$, $\mathcal K$, to the elements of which we refer as units. For each $e\in\mathcal K$, we consider two hypotheses for the marginal distribution of $X^e$,
\[
\mathcal H^e\text{ (null)}\qquad\text{versus}\qquad\mathcal G^e\text{ (alternative)},
\]
where $\mathcal H^e$, $\mathcal G^e$ are non-empty, disjoint subfamilies of $\mathcal P^e$. For any global distribution, $P\in\mathcal P$, we we say that $e\in\mathcal K$ is a signal under $P$ if $P^e\in\mathcal G^e$, and we denote by $\mathcal A(P)$ the set of signals under $P$, i.e.,
\[
\mathcal A(P):=\{e\in\mathcal K:P^e\in\mathcal G^e\}.
\]''',[3],[2],[r'\mathcal H^e',r'\mathcal G^e',r'\mathcal A(P)'],'Units are subsets, not necessarily singleton sources. Local null and alternative law families are disjoint and nonempty; compatibility with all units is imposed later.','Section 2.3 — A family of local hypotheses',context='2.3. A family of local hypotheses.')
add(4,'Prior information about the signal configuration',r'''We assume that the set of signals is known a priori to belong to a family of subsets of $\mathcal K$, $\Psi$, and denote by $\mathcal P_\Psi$ the family of global distributions that are compatible with $\Psi$, i.e.,
\[
\mathcal P_\Psi:=\{P\in\mathcal P:P^e\in\mathcal H^e\cup\mathcal G^e\text{ for every }e\in\mathcal K\quad\text{and}\quad\mathcal A(P)\in\Psi\}.
\]
We refer to $\mathcal H_0\equiv\mathcal P_\emptyset$ as the family of global null distributions. Clearly, $\mathcal H_0\subseteq\mathcal P_\Psi\Longleftrightarrow\emptyset\in\Psi$.''',[4],[3],[r'\mathcal P_\Psi',r'\mathcal H_0'],'Compatible global laws and the global null. Preserve the printed P_emptyset shorthand without replacing it by a newly interpreted family.','Section 2.5 — Prior information about the signal configuration',kind='source_passage',context='2.5. Prior information about the signal configuration.')
add(5,'number of signals',r'''For example, if it is assumed that there are at least $l$ and at most $u$ signals, then $\Psi$ takes the following form:
\[
\Psi_{l,u}:=\{A\subseteq\mathcal K:l\leq|A|\leq u\}.
\]
When, in particular, $l=0$ and $u=K$, $\Psi_{l,u}$ coincides with the powerset of $\mathcal K$ and corresponds to the case of no prior information about the signals whatsoever.''',[4],[],[r'\Psi_{l,u}'],'Cardinality-constrained family on the ambient set of units. The printed u=K powerset claim is retained even though the general unit count is |K-calligraphic|; source issues distinguish these quantities.','Section 2.5 — Bounds on the number of signals',context=AUX['A8']['statement_original'],context_page=15)
add(6,'cluster',r'''Alternatively, the available prior information may be of topological nature. For example, if the signals are assumed to form a cluster, in the sense of being stable with respect to symmetric differences, then $\Psi$ takes the following form:
\[
\Psi_{\mathrm{clus}}:=\{A\subseteq\mathcal K:\text{if }e,e'\in A\text{ and }e\triangle e'\in\mathcal K,\text{ then }e\triangle e'\in A\}.
\]''',[4],[],[r'\Psi_{\mathrm{clus}}'],'Source closure condition under symmetric differences that remain units. Do not replace by a standard graph-clustering definition.','Section 2.5 — Cluster prior')
add(7,'disjoint',r'''Alternatively, if the signals are assumed to be disjoint, then $\Psi$ becomes
\[
\Psi_{\mathrm{dis}}:=\{A\subseteq\mathcal K:\text{if }e,e'\in A\text{ then }e\cap e'=\emptyset\}.
\]''',[4],[],[r'\Psi_{\mathrm{dis}}'],'Printed disjoint-signal family. The source omits e different from e-prime, so its self-pair ambiguity is recorded and not silently repaired.','Section 2.5 — Disjoint prior')
add(8,'test',r'''More formally, we say that $(T,D)$ is a test if

• $T$ is an $\{\mathcal F_n\}$-stopping time, i.e., $\{T=n\}\in\mathcal F_n$ for every $n\in\mathbb N$,

• $D$ is $\mathcal F_T$-measurable and $\Psi$-valued, i.e., $\{T=n,D=A\}\in\mathcal F_n$ for every $n\in\mathbb N$, $A\in\Psi$,

and we denote by $\mathcal C_\Psi$ the family of all tests.''',[5],[1,4],[r'\mathcal C_\Psi',r'\mathcal F_T'],'Common stopping time and terminal signal-set decision, using the global filtration and prior-valued decision convention. No almost-sure finiteness is inserted into the original definition.','Section 2.6 — Tests')
add(9,'Pure isolation',r'''When $\emptyset\notin\Psi$, false alarms and missed detection are not possible. In this case, we consider tests that control the probabilities of false positives and false negatives, as in classical familywise error control. That is, the class of tests of interest is
\[
\mathcal C_\Psi(\gamma,\delta):=\{(T,D)\in\mathcal C_\Psi:P(D\setminus\mathcal A(P)\ne\emptyset)\leq\gamma\quad\&\quad P(\mathcal A(P)\setminus D\ne\emptyset,D\ne\emptyset)\leq\delta\quad\forall P\in\mathcal P_\Psi\},
\]
where $\gamma$ and $\delta$ are user-specified tolerance levels in $(0,1)$.''',[5],[8,3,4],[r'\mathcal C_\Psi(\gamma,\delta)'],'Two error probabilities under the nonempty-signal prior, preserving the explicit nonempty-decision event in the false-negative term.','Section 2.8.1 — Pure isolation',context='2.8.1. Pure isolation.')
add(10,'Pure detection',r'''When $\emptyset\in\Psi$, or equivalently $\mathcal H_0\subseteq\mathcal P_\Psi$, false alarms and missed detections are possible. If, also, these are the only errors we want to explicitly control, the class of tests of interest becomes
\[
\mathcal D_\Psi(\alpha,\beta):=\{(T,D)\in\mathcal C_\Psi:P(D\ne\emptyset)\leq\alpha\quad\forall P\in\mathcal H_0\quad\&\quad P(D=\emptyset)\leq\beta\quad\forall P\in\mathcal P_\Psi\setminus\mathcal H_0\},
\]
where $\alpha$ and $\beta$ are user-specified tolerance levels in $(0,1)$.''',[5],[8,4],[r'\mathcal D_\Psi(\alpha,\beta)'],'False-alarm control under the global null and missed-detection control under non-null laws; it does not require correct identification of all signals.','Section 2.8.2 — Pure detection',context='2.8.2. Pure detection.')
add(11,'Familywise error control',r'''\[
\mathcal E_\Psi(\gamma,\delta):=\{(T,D)\in\mathcal C_\Psi:P(D\setminus\mathcal A(P)\ne\emptyset)\leq\gamma\quad\&\quad P(\mathcal A(P)\setminus D\ne\emptyset)\leq\delta\quad\forall P\in\mathcal P_\Psi\},
\]
where, as before, $\gamma$ and $\delta$ are user-specified tolerance levels in $(0,1)$.''',[6],[8,3,4],[r'\mathcal E_\Psi(\gamma,\delta)'],'Unconditional familywise false-positive and false-negative control over all compatible global laws. Unlike the pure-isolation display, its false-negative event has no D nonempty qualifier.','Section 2.8.3 — Familywise error control',context='2.8.3. Familywise error control.')
add(12,'Joint detection and isolation',r'''Specifically, the proposed class of tests is
\[
\mathcal C_\Psi(\alpha,\beta,\gamma,\delta):=\mathcal D_\Psi(\alpha,\beta)\cap\mathcal C_{\Psi\setminus\emptyset}(\gamma,\delta),
\]
where $\alpha,\beta,\gamma,\delta$ are user-specified tolerance levels in $(0,1)$.''',[6],[9,10],[r'\mathcal C_\Psi(\alpha,\beta,\gamma,\delta)'],'Source intersection expression for four error controls. The Psinonempty decision-domain issue and the empty-set difference shorthand are retained as source ambiguities, not repaired.','Section 2.8.4 — Joint detection and isolation',context='2.8.4. Joint detection and isolation.')
add(13,'non-null global distributions',r'''In order to do so, for each unit $e\in\mathcal K$ we denote by $\mathcal H_{\Psi,e}$ the family of non-null global distributions under which the null is correct in unit $e$, and by $\mathcal G_{\Psi,e}$ the family of global distributions under which $e$ is a signal, i.e.,
\[
\mathcal H_{\Psi,e}:=\{P\in\mathcal P_\Psi\setminus\mathcal H_0:e\notin\mathcal A(P)\}\quad\text{and}\quad\mathcal G_{\Psi,e}:=\{P\in\mathcal P_\Psi:e\in\mathcal A(P)\}.
\]''',[6],[3,4],[r'\mathcal H_{\Psi,e}',r'\mathcal G_{\Psi,e}'],'Global hypothesis-specific alternatives; the H-family explicitly excludes the global null. Projected families can differ from the original local hypothesis families.','Section 3 — Non-null global distributions')
add(14,'mutually absolutely continuous',r'''We assume that for every
\[
e\in\mathcal K,\quad P\in\mathcal G_{\Psi,e}\cup\mathcal H_0,\quad Q\in\mathcal H_{\Psi,e}\cup\mathcal H_0,\quad e\subseteq s\subseteq[K],\quad n\in\mathbb N,
\]
$P^s$ and $Q^s$, i.e, the marginal distributions of $X^s$ under $P$ and $Q$ respectively, are mutually absolutely continuous when restricted to $\mathcal F_n^s$,''',[7],[1,2,13,4],[r'\mathcal F_n^s'],'Finite-time mutual absolute continuity for the specified law pairs and subsystems; not equivalence of full infinite-sequence laws. The original sentence continues into the likelihood notation saved in D15.','Section 3 — Finite-time absolute continuity',kind='assumption')
add(15,'likelihood ratio',r'''and we denote the corresponding likelihood ratio (Radon-Nikodym derivative) and log-likelihood ratio as follows:
\[
\Lambda_n(P^s,Q^s):=\frac{dP^s}{dQ^s}(\mathcal F_n^s)\quad\text{and}\quad Z_n(P^s,Q^s):=\log\Lambda_n(P^s,Q^s).
\]''',[7],[14],[r'\Lambda_n(P^s,Q^s)',r'Z_n(P^s,Q^s)'],'Finite-time likelihood ratio and its logarithm, using the source law restrictions and absolute-continuity domain.','Section 3 — Likelihood ratio')
add(16,'detection statistic',r'''\[
\Lambda_{e,\mathrm{det}}(n):=\frac{\max\{\Lambda_n(P,P_0):P\in\mathcal G_{\Psi,e}^{s_e}\}}{\max\{\Lambda_n(P,P_0):P\in\mathcal H_0^{s_e}\}},
\]''',[7],[13,4,15],[r'\Lambda_{e,\mathrm{det}}(n)',r'\mathcal H_0^{s_e}'],'GLR over the detection subsystem, with alternative signal-in-e laws versus global-null laws. Source subsystem containment and reference-law choices are preserved as auxiliary context.','Section 3.1 — Detection statistic',context=r'Thus, we refer to $s_e$ as the detection subsystem for unit $e$ and to $\Lambda_{e,\mathrm{det}}$ as the detection statistic for unit $e$.')
add(17,'isolation statistic',r'''\[
\Lambda_{e,\mathrm{iso}}(n):=\frac{\max\{\Lambda_n(P,P'_0):P\in\mathcal G_{\Psi,e}^{s'_e}\}}{\max\{\Lambda_n(P,P'_0):P\in\mathcal H_{\Psi,e}^{s'_e}\}},
\]''',[7],[13,15],[r'\Lambda_{e,\mathrm{iso}}(n)',r'\mathcal H_{\Psi,e}^{s\'_e}'.replace('\\\'',"'")],'GLR over the isolation subsystem; its denominator uses non-null global distributions with no signal in e, not the global null. Reference-law and subsystem conventions remain separate source context.','Section 3.1 — Isolation statistic',context=r"Thus, we refer to $s'_e$ as the isolation subsystem for unit $e$ and to $\Lambda_{e,\mathrm{iso}}$ as the isolation statistic for unit $e$.")
add(18,'estimated signal set',r'''For each $n\in\mathbb N$ we also denote by $D_{\mathrm{iso}}(n)$ the set of units whose isolation statistics at time $n$ have values larger than $1$, i.e.,
\[
D_{\mathrm{iso}}(n):=\{e\in\mathcal K:\Lambda_{e,\mathrm{iso}}(n)>1\}.
\]
(4)
Therefore, $D_{\mathrm{iso}}(n)$ can be interpreted as the estimated signal set based on the from the isolation subsystems in the first $n$ time instances.''',[7],[17],[r'D_{\mathrm{iso}}(n)'],'Isolation estimate uses a strict greater-than-one rule; it need not lie in the prior family until a stopping rule imposes that restriction. Preserve the printed prose typo.','Section 3.1 — Estimated signal set (4)')
add(19,'local statistic',r'''\[
\Lambda_e(n):=\frac{\max\{\Lambda_n(P,P_0):P\in\mathcal G^e\}}{\max\{\Lambda_n(P,P_0):P\in\mathcal H^e\}}.
\]
(5)
We refer to $\Lambda_e(n)$ as the local statistic of unit $e$ at time $n$, as it is computed based solely on data from unit $e$ up to time $n$. Furthermore, we denote the ordered versions of the local statistics by $\Lambda_{(1)}(n)\geq\cdots\geq\Lambda_{(|\mathcal K|)}(n)$, and the corresponding indices by $i_1(n),\ldots,i_{|\mathcal K|}(n)$. We also denote by $p(n)$ the number of units whose local statistics at time $n$ have values larger than $1$, i.e., $p(n):=|\{e\in\mathcal K:\Lambda_e(n)>1\}|$.''',[7],[3,15],[r'\Lambda_e(n)',r'\Lambda_{(1)}(n)',r'p(n)'],'Local GLR, descending order, indices and strict-positive count. The source does not specify a tie-breaking rule. Its claimed reduction from projected GLRs is preserved separately, without equating the prior-restricted and unrestricted families by fiat.','Section 3.1 — Local statistic (5)')
add(20,'test for pure isolation',r'''When $\emptyset\notin\Psi$, we stop sampling when the value of every isolation statistic is either too large or too small, and we identify as signals those units for which these values are large. Therefore, the proposed test in this case, $\chi^*:=(T^*,D^*)$, is:
\[
T^*:=\inf\{n\in\mathbb N:D_{\mathrm{iso}}(n)\in\Psi,\ \Lambda_{e,\mathrm{iso}}(n)\notin(1/A_e,B_e)\ \forall e\in\mathcal K\}\quad\text{and}\quad D^*:=D_{\mathrm{iso}}(T^*),
\]
where $\{A_e,B_e\}_{e\in\mathcal K}$ are thresholds to be determined so that $\chi^*\in\mathcal C_\Psi(\gamma,\delta)$.''',[7],[17,18,9],[r'\chi^*:=(T^*,D^*)',r'\mathcal C_\Psi(\gamma,\delta)'],'Pure-isolation test used when the prior excludes the empty signal set; distinct from the later joint test that reuses chi-star and T-star.','Section 3.2.1 — The test for pure isolation',context='3.2.1. The test for pure isolation.')
add(21,'stopping times',r'''\[
T_0:=\inf\{n\in\mathbb N:\Lambda_{e,\mathrm{det}}(n)\leq1/C_e\quad\text{for every }e\in\mathcal K\},
\]
\[
T_{\mathrm{det}}:=\inf\{n\in\mathbb N:\Lambda_{e,\mathrm{det}}(n)\geq D_e\quad\text{for some }e\in\mathcal K\},
\]''',[8],[16],[r'T_0:=',r'T_{\mathrm{det}}:='],'All-small versus some-large detection stopping times. Their threshold values are bound parameters; neither stopping time by itself is a complete test.','Section 3.2.2 — Detection stopping times',context=r'Then, the stopping times, $T_0$ and $T_{\mathrm{det}}$, defined as in Subsection 3.2.2, take the following form:',context_page=16)
add(22,'test for pure detection',r'''When $\emptyset\in\Psi$ and the focus is on the pure detection problem, we stop sampling when either all detection statistics are small, in which case the null hypothesis is selected in all units, or at least one detection statistic is large enough, in which case some non-empty subset of units is identified as the set of signals. Specifically, the proposed test in this case, $\chi^*_{\mathrm{det}}:=(T^*_{\mathrm{det}},D^*_{\mathrm{det}})$, is:
\[
T^*_{\mathrm{det}}:=\min\{T_0,T_{\mathrm{det}}\}\quad\text{and}\quad D^*_{\mathrm{det}}=\emptyset\quad\Longleftrightarrow\quad T_0<T_{\mathrm{det}},
\]''',[8],[21,10],[r'\chi^*_{\mathrm{det}}',r'D^*_{\mathrm{det}}=\emptyset'],'Detection-only decision specifies empty versus nonempty output rather than a unique nonempty set. Prior-valuedness follows the source test convention and is not completed by an invented selection rule.','Section 3.2.2 — The test for pure detection',context='3.2.2. The test for pure detection.')
add(23,'test for joint detection and isolation',r'''When $\emptyset\in\Psi$ and the goal is to control all four kinds of error, the proposed test in this case, $\chi^*:=(T^*,D^*)$, is based on a combination of the two previous ones:
\[
T^*:=\min\{T_0,T_{\mathrm{joint}}\},\qquad D^*:=\begin{cases}\emptyset&\text{if }T_0<T_{\mathrm{joint}}\\D_{\mathrm{iso}}(T^*)&\text{if }T_{\mathrm{joint}}<T_0,\end{cases}
\]
where $T_0$ is defined as before,
\[
\begin{aligned}
T_{\mathrm{joint}}:=\inf\{n\in\mathbb N:{}&\Lambda_{e,\mathrm{det}}(n)\geq D_e\quad\text{for some }e\in\mathcal K,\\
&\Lambda_{e,\mathrm{iso}}(n)\notin(1/A_e,B_e)\quad\text{for every }e\in\mathcal K,\\
&D_{\mathrm{iso}}(n)\in\Psi\setminus\emptyset\},
\end{aligned}
\]
and $\{A_e,B_e,C_e,D_e\}_{e\in\mathcal K}$ are thresholds to be determined so that $\chi^*\in\mathcal C_\Psi(\alpha,\beta,\gamma,\delta)$.''',[8],[16,17,18,21,12],[r'T_{\mathrm{joint}}',r'\mathcal C_\Psi(\alpha,\beta,\gamma,\delta)'],'Four-threshold joint test. Strict comparisons leave simultaneous hitting or both-infinite cases unspecified; these are recorded separately rather than assigned an invented decision.','Section 3.2.3 — The test for joint detection and isolation',context='3.2.3. The test for joint detection and isolation.')
add(24,'test for familywise error control',r'''When $\emptyset\in\Psi$ and we are interested in the familywise error control of Subsection 2.8.3, we utilize
\[
\chi^*:=(T^*,D^*)\quad\text{with}\quad A_e=C_e,B_e=D_e\quad\text{for every }e\in\mathcal K,
\]
and denote the resulting test by $\chi^*_{\mathrm{fwer}}:=(T^*_{\mathrm{fwer}},D^*_{\mathrm{fwer}})$.''',[8],[23,11],[r'\chi^*_{\mathrm{fwer}}',r'A_e=C_e,B_e=D_e'],'Familywise specialization of the joint test with paired thresholds. Its gamma/delta calibration is separate from the alpha/beta calibration of the pure detection test.','Section 3.2.4 — The test for familywise error control',context='3.2.4. The test for familywise error control.')
calibration=AUX['A2']['statement_original']
cut='\n• when $\\emptyset\\in\\Psi$'
assert cut in calibration
cal_i,cal_d=calibration.split(cut,1)
cal_d='• when $\\emptyset\\in\\Psi$'+cal_d
add(25,'Selection of thresholds',cal_i,[9],[20,9],[r'\log A_e\sim|\log\delta|',r'\log B_e\sim|\log\gamma|'],'Pure-isolation threshold-family admissibility and first-order log calibration, for every gamma/delta. These are assumed properties, not a mandate to use one particular bound from Theorem 3.1.','Section 3.4 — Threshold selection (8)',kind='assumption',context='3.4. Selection of thresholds.')
add(26,'Selection of thresholds',cal_d,[9],[22,23,24,10,11,12],[r'\log C_e\sim|\log\beta|',r'\log D_e\sim|\log\alpha|'],'Threshold-family admissibility and log calibration for problems including detection. The source uses shared notation for separately calibrated procedures; mixed fixed-tolerance paths and paired familywise thresholds remain scope issues.','Section 3.4 — Threshold selection (9)',kind='assumption',context='3.4. Selection of thresholds.')
add(27,'thresholds',AUX['A3']['statement_original'],[9],[],[r'A_e=A',r'C_e=C'],'Unit-invariant thresholds used for explicit implementations in Section 5.1 and Theorem 6.1. The source expressly says that Section 4 results do not need this extra restriction.','Section 3.4 — Common thresholds (10)',kind='assumption',context='3.4. Selection of thresholds.')
conditions=AUX['A4']['statement_original']
head=conditions.split('\\[\nP\\left',1)[0]
upper,lower=conditions.split('(11)',1)
add(28,'Distributional assumptions',upper+'(11)',[9,10],[15,13,2],[r'\max_{1\leq m\leq n}Z_m(P^s,Q^s)',r'\rho>\mathcal I(P^s,Q^s)'],'Maximal upper-tail convergence in both likelihood directions for every specified unit, global-law pair and subsystem. The positive information numbers are bound parameters shared with (12), not an extra requirement that (12) hold.','Section 4.1 — Distributional assumptions (11)',kind='assumption',context='4.1. Distributional assumptions.')
add(29,'Distributional assumptions',head+lower.lstrip(),[9,10],[15,13,2],[r'\sum_{n=1}^\infty P(Z_n(P^s,Q^s)<n\rho)',r'\rho<\mathcal I(P^s,Q^s)'],'Summability of lower-tail probabilities in both likelihood directions, separately retained from (11). Theorems 4.1 and 4.2 explicitly use this condition.','Section 4.1 — Distributional assumptions (12)',kind='assumption',context='4.1. Distributional assumptions.')
add(30,'divergences',r'''For any $P\in\mathcal P_\Psi$, $\mathcal Q\subseteq\mathcal P_\Psi$ and $s\subseteq[K]$ we set
\[
\mathcal I(P^s,\mathcal Q^s):=\inf_{Q\in\mathcal Q}\mathcal I(P^s,Q^s),
\]
whenever the quantities in the right-hand side are well defined. We also set
\[
\mathcal I(P,Q;s):=\mathcal I(P^s,Q^s)\quad\text{and}\quad\mathcal I(P,\mathcal Q;s):=\min_{Q\in\mathcal Q}\mathcal I(P,Q;s).
\]
As before, we omit $s$ when $s=[K]$ and replace it by $k$ whenever $s=\{k\}$ for some $k\in[K]$.''',[10],[2,4],[r'\mathcal I(P,\mathcal Q;s)',r'\mathcal I(P^s,\mathcal Q^s)'],'Notation for information numbers against a law or law family after subsystem projection. The information parameters have the roles specified in (11)-(13); using their notation does not itself add the upper-tail assumption to a theorem assuming only (12).','Section 4.2 — Information notation',context=r'thus, the limits, $\mathcal I(P^s,Q^s)$ and $\mathcal I(Q^s,P^s)$, can be interpreted as (Kullback-Leibler) divergences between the global distributions $P$ and $Q$ based on the data from the sources in $s$.')
# Exact formula excerpts retain their source labels; the theorem hypotheses remain in the inventory.
signal_iso=T['4.3'].split('\\[',1)[1].split('(15)',1)[0]
add(31,'isolation subsystems','\\['+signal_iso+'(15)',[12],[30,13],[r'\mathcal I(P,\mathcal H_{\Psi,e};s\'_e)'.replace('\\\'',"'")],'Equality of the hardest signal-isolation information for chosen versus full subsystems. It concerns a minimum over signals; the non-signal condition (16) is different.','Theorem 4.3 — Isolation subsystems (15)',kind='theorem_excerpt',context=T['4.3'].split('\\[',1)[0])
non_signal_iso=T['4.3'].split('(15)\n',1)[1].split('(16)',1)[0]
add(32,'isolation subsystems',non_signal_iso+'(16)',[12],[30,13],[r'\mathcal I(P,\mathcal G_{\Psi,e};s\'_e)'.replace('\\\'',"'")],'Equality of the hardest non-signal-isolation information for chosen versus full subsystems; not the same condition as (15).','Theorem 4.3 — Isolation subsystems (16)',kind='theorem_excerpt',context=T['4.3'].split('\\[',1)[0])
null_det='\\['+T['4.4'].split('\\[',1)[1].split('(17)',1)[0]+'(17)'
add(33,'detection subsystems',null_det,[12],[30,13],[r'\min_{e\in\mathcal K}\mathcal I(P,\mathcal G_{\Psi,e};s_e)'],'Global-null detection condition: minimum information over all units matches full-data information.','Theorem 4.4 — Detection subsystems (17)',kind='theorem_excerpt',context=T['4.4'].split('\\[',1)[0])
signal_det='\\['+T['4.5'].split('\\[',1)[1].split('(18)',1)[0]+'(18)'
add(34,'detection subsystems',signal_det,[13],[30,4],[r'\max_{e\in\mathcal A(P)}\mathcal I(P,\mathcal H_0;s_e)'],'Non-null detection condition: maximum signal-subsystem information equals full information against the global null. This differs from the minimum condition (17).','Theorem 4.5 — Detection subsystems (18)',kind='theorem_excerpt',context=T['4.5'].split('\\[',1)[0])
add(35,'independence assumption',AUX['A7']['statement_original'],[14],[2,4],[r'P=P^1\otimes\cdots\otimes P^K'],'Independence of all full source sequences for every plausible global law, a Subsection 5.1 restriction. Theorems 5.5 and 5.6 do not inherit this assumption.','Section 5.1 — Independence assumption (21)',kind='assumption',context='In this subsection we do not assume that the independence assumption (21) holds,',context_page=17)
are=AUX['A11']['statement_original'].split('\\[',1)[1]
add(36,'asymptotic relative efficiency','\\['+are,[17,18],[23,12],[r'\operatorname{ARE}_P[\chi^*]'],'Limsup of proposed expected sample size divided by the optimum in the four-error class. It is a loss factor, not the reciprocal efficiency; the theorem-specific path can permit some tolerances to remain fixed.','Section 5.2 — Asymptotic relative efficiency (22)',context=AUX['A11']['statement_original'].split('\\[',1)[0],context_page=17)
add(37,'anomalous sources',AUX['A6']['statement_original'],[14],[3,28,29],[r'\mathcal K=\{\{k\}:k\in[K]\}'],'Section 5 specialization to singleton-source hypotheses, with its explicitly standing distributional conditions. Independence is separately assumed only in Subsection 5.1.','Section 5 — Detection and isolation of anomalous sources',kind='source_passage')
add(38,'pairs of data sources',AUX['A12']['statement_original'],[19,20],[3,28,29],[r'\mathcal K=\{\{i,j\}:1\leq i<j\leq K\}'],'Section 6 specialization: pair null means independence and pair alternative dependence, with conditions (11)-(12). This does not impose a Gaussian model or the extra group-independence condition (23).','Section 6 — Pairs of data sources',kind='source_passage')
add(39,'disjoint and independent',AUX['A13']['statement_original'],[20],[2,3,4],[r'\{i,j\}\notin\mathcal A(P)'],'Source equivalence between group independence and absence of cross-pair signals. Apply only where the theorem explicitly requires it or uses it in a sufficient-condition example.','Section 6 — Group independence condition (23)',kind='assumption')
partition=AUX['A14']['statement_original'].split('We also note that,',1)[1]
add(40,'disjoint partition','We also note that,'+partition,[20],[2,4],[r'v_0,v_1,\ldots,v_{L(P)}',r'P=P^{v_0}\otimes P^{v_1}'],'Independent-block partition of full sequences, with v0 containing independent sources. The source does not define uniqueness or minimality of the remaining blocks; condition (23) is not an automatic prerequisite.','Section 6 — Independent-block partition',kind='source_passage')
add(41,'thresholds',r'''\[
a_e:=|\mathcal H_{\Psi,e}^{s'_e}|,\qquad b_e:=|\mathcal G_{\Psi,e}^{s'_e}|,\qquad c_e:=|\mathcal H_0^{s_e}|,\qquad d_e:=|\mathcal G_{\Psi,e}^{s_e}|\qquad e\in\mathcal K.
\]
(7)''',[8],[2,13,4],[r'a_e:=',r'b_e:=',r'c_e:=',r'd_e:='],'Cardinalities of projected law families, not the numbers of units or streams. Projection can identify distinct global laws; count distinct restrictions.','Section 3.3 — Threshold coefficients (7)',context='We next select the thresholds in each of the above tests in order to satisfy the desired error constraints.')
# Make selectors include explicit numbered conditions where the source names them.
for n,num in [(28,'11'),(29,'12'),(31,'15'),(32,'16'),(33,'17'),(34,'18'),(39,'23')]:
    members[f'D{n}']['highlight_phrases']=['('+num+')']
members['D14']['highlight_phrases']=['mutually absolutely continuous']
members['D41']['highlight_symbols']=[r"a_e:=|\mathcal H_{\Psi,e}^{s'_e}|",r"b_e:=|\mathcal G_{\Psi,e}^{s'_e}|",r"c_e:=|\mathcal H_0^{s_e}|",r"d_e:=|\mathcal G_{\Psi,e}^{s_e}|"]
def main():
    ROOT.mkdir(parents=True,exist_ok=True)
    for name,data in [('source-passages.json',dict(paper_id=PID,status='extracted',scope='Original main-text passages; independent full source review remains a separate gate.',source_passages=list(members.values()))),('interface-extraction.json',dict(paper_id=PID,status='extracted',interfaces=interfaces))]:
        (ROOT/name).write_text(json.dumps(data,indent=2,ensure_ascii=False)+'\n')
    print(f'Saved {len(members)} original source entries; full graph review remains pending.')
if __name__=='__main__':main()
