"""Record main-text conventions, inherited conditions and unresolved source details."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];PID=ROOT.name
aux=[]
def add(lid,text,pages,location):
    aux.append(dict(local_id=lid,statement_original=text.strip(),evidence=[dict(page=p,location=location) for p in pages]))
add('A1',r'''For any compact set $K\subset\mathbb R$ we denote by $\mathcal C(K)$ the set of continuous functions $f:K\to\mathbb R$. Unless stated otherwise, we denote by $\|\cdot\|_{L^2}$ the $L^2$-norm with respect to the Lebesgue measure on $\mathbb R$.''',[7],'Section 2 — continuous-function and Lebesgue-norm notation')
add('A2',r'''Let $\Psi_{T,y,h}^{b_0}(X)$ be given as above for a continuous kernel $K$ of bounded variation with support $[-1,1]$ and $\|K\|_{[-1,1]}\le1$.''',[9],'Theorem 3.1 — original signed-kernel condition')
add('A3',r'''for arbitrary numbers $\epsilon_T>0$ with $\lim_{T\to\infty}\epsilon_T=0$ and $\lim_{T\to\infty}\epsilon_T\sqrt{\log T}=\infty$''',[16],'Theorem 5.2 — sequence condition inherited by Theorems 5.3 and 5.4')
add('A4',r'''For $\eta=0$ the hypothesis $H_0(b_0,\eta)$ reduces to the simple hypothesis $b=b_0$ (on $[-A,A]$). Here, we find minimax optimality including the efficiency constant even on the full range $\beta,L>0$.''',[16],'Section 5.2 — simple-null context immediately before Theorem 5.4')
add('A5',r'''Furthermore, for all $\beta>0$, $K_\beta$ is compactly supported, an even function and satisfies $K_\beta(0)=1>|K_\beta(x)|$ for $x\ne0$.''',[15],'Section 5.2 — additional optimal-recovery kernel properties')
add('A6',r'''For technical convenience, all of our results were derived under the assumption that the diffusion $X$ is stationary, i.e. $X_0\sim\mu_b$. However, it is not necessary. In Remark H.6 and H.7 we give the details how Theorem 4.1, 5.1, 5.2, 5.3 and 5.4 can be established for $X$ started at a fixed point $x_0\in[-A,A]$.''',[17],'Remark 5.5 — fixed-point extensions are deferred to the supplement')
add('A7',r'''Note that in the respective definitions of $\widetilde\Psi_{T,y,h}^{b_0}(f)$ and $\widetilde T_T^\eta(f)$, no division by zero occurs due to the restriction of $f$ to $D_{A,T}$.''',[19],'Section 6.1 — printed nonzero-denominator assertion')
add('A8',r'''For any metric space $E$, $\mathcal F_{BL}(E)$ denotes the closed unit ball of bounded Lipschitz functions on $E$, see Appendix F.1.''',[25],'Section 7.2 — bounded-Lipschitz unit-ball description')
add('A9',r'''Finally, we show that the test $\widetilde\phi_T^\eta$ is indeed powerful for $H\approx1/2$ by establishing a lower bound in the spirit of Theorem 5.1 for $H$ being close to the Brownian case $H=1/2$. A corresponding upper bound follows in the same way as (6.4) from Theorem 6.3.''',[21],'Section 6.2 — lower-bound context before Theorem 6.5')
resolution={
 'shared':'The continuous record, scalar drift and constant positive sigma are D1. D2 gives growth, inward drift and local Lipschitz restrictions; its Appendix D reference is not read. D5 is pointwise sup norm, while A1 specifies continuous functions and Lebesgue L2. Brownian motion, deterministic and Ito integrals, indicator functions, derivatives, expectations, real suprema/infima, conditional probabilities, tightness and uniform convergence are ambient. The common scalar model parameters A,gamma,sigma are positive and C>=1 at the original definition. Any extra compatibility of the tightened parameters remains a source issue. Eta is a nonnegative tolerance except where explicitly positive; alpha has the significance-level role. Generic tests and numeric constants bound inside a theorem do not become a separate proposed-test interface.',
 '3.1':'Psi is D8, with the localized kernel D7 and its zero-denominator convention. The continuous bounded-variation signed-kernel condition is reproduced in A2 and differs from D26. The reference b0 inherits Sigma(C/2,A,gamma,sigma) from Section 3; P_b0 is D4. The rational index set is D9. Both empirical scales are defined inline and preserved as D10, including the squared interval indicator. Upsilon and the zero-over-zero argument rule are defined inline and preserved as D11. Tightness is an assertion about the family indexed by T. It does not assert a Gaussian approximation or impose similarity-test nonnegativity on K.',
 '4.1':'T_T^eta is D17; the opening kernel restriction is D26. The tightened b0 class is D2 instantiated with C/2-eta and gamma+eta/sigma^2. Uniform P_b over H0 uses the stationary law D4 and similarity class D15. U1,U2 are defined completely in the statement and preserved as D18, using D3 densities, D7 kernels, D9 indices and D11 correction. Their common W and pointwise maximum do not imply independence. Lebesgue norms and the deterministic 4 sqrt(A eta/sigma^2) shift retain their printed meaning. The conclusion uses >=r, whereas the rejection event later uses a strict inequality.',
 '5.1':'The test psi_T is any test satisfying the displayed uniform size restriction under D4 on D15; it is not phi_T^eta. D21 is the density-weighted distance to the null, D22 the Holder class of b-b0, D23 the rate and D24 the sharp constant. Beta,L>0 and an interior compact J come from Section 5 and the final sentence. The epsilon_T conditions are stated in full. The below-boundary threshold and the order limsup_T inf_alternative E_b remain unchanged. Optimal recovery enters only through c_*; neither the proposed test nor its kernel assumptions are needed to state this lower bound.',
 '5.2':'The reference class, positive eta and kernel D27 are explicit. D20 is the similarity indicator test (4.7), calibrated by D19 from D18. The infimum uses D15,D21,D22,D23 and stationary probability D4. The sufficient c(beta,L,K) is an existential scalar in the theorem, not the universal sharp constant. Only the final beta<=1 clause explicitly chooses D25 and sets c=c_* from D24. The epsilon_T conditions and interior J are explicit; do not substitute the weaker <=1 kernel normalization from Theorem 4.1.',
 '5.3':'The reference to Theorem 5.2 imports b0, K and the epsilon_T sequence A3, with the ongoing similarity setting. D20,D15,D21,D22,D23 and D4 resolve both displayed power assertions; c(beta,L,K) is the sufficient constant discussed by Theorem 5.2. D24 enters the sharp-L assertion. The first outer infimum literally uses (b,L), not (beta,L); this is a source discrepancy. J is inherited from the fixed compact interior interval in Theorem 5.2. The sharp-L sentence does not explicitly restate K=K_beta; its relationship to the previous theorem’s sharp-kernel case remains contextual, not a rewritten hypothesis.',
 '5.4':'A4 fixes eta=0 in the paragraph immediately preceding the theorem, despite its partial reference to Theorem 5.2, whose main statement assumes eta>0. The reference imports b0 and epsilon_T, not that theorem’s positive-tolerance or kernel condition. The proposed test is D14 and the two-sided alternative is D6. Its kernel is explicitly D25 for all beta,L>0. D21,D22,D23,D24 and D4 resolve separation and power. The original minus sign in (1-epsilon_T)c_*delta_T is preserved even though it conflicts with the expected lower-bound interpretation. A5 states compact support of K_beta generally but does not identify that support with [-1,1] for every beta.',
 '6.1':'D33 is the full deterministic extension on D30. Its definition uses the ordinary-integral extension D29 and extended score D31, inherited C1 kernel condition D28, restricted index set D32 and classical tolerance/occupation/correction functions D16,D10,D11. A1 and D5 provide the topology of uniform convergence on \mathcal C([0,T]). No diffusion law, stationarity assumption, fractional Brownian covariance or proposed-test calibration is required for the deterministic continuity assertion. The source retains X in the Lambda term of the f-dependent formula and does not state the exact appendix-only h_min(T). A7 asserts denominators are positive on D30 although D26 permits a zero kernel; this is not silently repaired.',
 '6.3':'D37 supplies the fixed-initial-value pair on one common-noise probability space, resolved via D1,D36,D35,D34. The domain event is D30 and the compared statistic is D33 with its pathwise prerequisites. The uniform drift range explicitly includes D2 and D22 specialized to H(1,L), which is global Lipschitz regularity under the strict lower integer convention. P is the unsubscripted common coupling law, not stationary P_b. Both iterated liminf orders for the conditioning event are part of the theorem. Proposition 6.2, tightness, Arzela–Ascoli and mapping theorems are proof ingredients and create no statement-dependency interfaces.',
 '6.5':'X^{H,b} belongs to the Section 6 fixed-initial-value experiment D37; x0 is explicitly in [-A,A]. Generic tests psi_T^H are bound locally by the displayed uniform-level condition. D15,D21,D22,D23,D24 resolve the null, alternatives and weighted below-boundary threshold. The common E is not stationary E_b. A9 refers to the lower-bound framework of Theorem 5.1; beta,L,epsilon_T and J are not bound again inside Theorem 6.5, so their Section 5 context is recorded rather than inserted into the original. The Hurst neighborhood delta(T,epsilon) is a locally bound sequence distinct from delta_T(beta). The order limsup_T sup_H sup_test inf_alternative is preserved. The printed drift suprema omit the global-Lipschitz qualifier used to introduce X^{H,b} on page 20, leaving a source-scope ambiguity; do not narrow their displayed domains. The proposed tilde-phi test in Remark 6.4 and the pathwise statistic are not prerequisites of this all-test lower bound.',
 '7.1':'D26 resolves the explicit kernel reference to Theorem 4.1. Z_b, sigma_b, sigma_b,max and S_b are fully bound inline; their prerequisites are D3 density, D7 kernel, D9 rational index set, D11 correction and ambient Lebesgue L2 and two-sided Brownian W on [-A,A]. The observed T_T^b is D12 with reference b, under stationary law D4. The supremum is over the full Sigma class D2, not the smaller similarity null. D38 records the bounded-Lipschitz metric and b-dependent-law convention. A8 names a closed unit ball in later main-text proof context but still does not provide its exact norm normalization. Local Gaussian approximation proof processes and Proposition 7.3 are not imported as statement prerequisites.'
}
issues=[
 'The pinned source is arXiv:2203.13776v3 dated 16 April 2024, 153 pages. Equivalence to every detail of final journal typesetting is not asserted.',
 'Main text and references end on page 31; the separately titled supplement starts on page 32. No supplementary or appendix mathematics is used.',
 'All ten actual main-text Theorems are preserved, including the short continuity statement and Theorem 7.1 in the main-text proof overview. Lemmas, Propositions, Remarks and citations are not extra Theorems.',
 'Sigma imposes local Lipschitz regularity, global linear growth and inward drift outside [-A,A]. Its C>=1 parameter convention is not explicitly reconciled with C/2-eta in later tightened reference classes.',
 'The invariant density has a normalized exponential signed integral from zero to x. The density can be used as a deterministic weight without assuming the observed process starts in that invariant law.',
 'Sections 2–5 use stationary P_b and E_b. Section 6 fixes x0 and a common unsubscripted P,E; those laws must not be conflated. Remark 5.5 points to supplement-only details for fixed-point extensions of the earlier results.',
 'The simple null is equality on [-A,A]. References to the simple hypothesis {b0} do not justify changing it into equality of drifts everywhere on R.',
 'K_y,h has no 1/h amplitude prefactor. The rational index set includes only pairs whose location interval lies inside [-A,A].',
 'Theorem 3.1 allows signed continuous bounded-variation kernels of norm at most one. Theorem 4.1 additionally requires nonnegativity. Theorem 5.2 uses norm exactly one and does not restate continuity. Section 6 adds C1 to the conditions of Theorem 4.1.',
 'The local score has an explicit zero-denominator value zero; Lambda has a zero-over-zero rule, and Upsilon has a zero-over-zero convention for its argument. The empirical maximum scale retains the squared indicator from the source.',
 'Upsilon at zero is given by a printed logarithm-times-indicator expression. Its intended convention must not be replaced by ordinary arithmetic on an undefined logarithm. Gaussian ratio formulas may also degenerate when K=0, permitted by the printed <=1 condition.',
 'U1 and U2 are driven by the same W in the source; no independence is stated. Both normalizers use Lebesgue L2 and the appropriate boundary-drift density.',
 'Finite-T null quantiles and the limiting similarity threshold are distinct. Both use minimum and a non-strict CDF inequality, while both tests reject with a strict inequality.',
 'Delta_J depends on the alternative density q_b. Its infimum-of-norms definition is nonnegative, but the following supremum formula omits a positive part and can be negative when band violation occurs only outside J. Both formulas are preserved.',
 'The Holder lower integer is strictly smaller than beta, even at integer beta. The printed condition quantifies over k but displays only a derivative of order floor(beta); no derivative sup-norm constraints are inserted.',
 'The separation rate delta_T and sharp constant c_* are distinct from the arbitrary sufficient c(beta,L,K) and the later Hurst neighborhood delta(T,epsilon). The star in c_* is a subscript.',
 'The explicit optimal recovery kernel formula is stated for beta<=1 only. General beta has compact support but not a main-text guarantee that this support is exactly [-1,1], raising a normalization issue for its use in the earlier fixed-support statistic.',
 'Theorem 5.3 prints (b,L) in its outer infimum over the beta,L rectangle. The source index mismatch is retained, not corrected to (beta,L).',
 'Theorem 5.3 does not explicitly restate the K=K_beta choice in its sharp-L assertion. Its context from Theorem 5.2 is recorded without inventing a new explicit hypothesis.',
 'Theorem 5.4 follows an eta=0 paragraph but refers to b0 and epsilon_T from Theorem 5.2. Its power-one condition prints (1-epsilon_T)c_*delta_T; the minus sign is retained as an apparent conflict with the matching lower-bound interpretation.',
 'The pathwise integral functional suppresses its y,h dependence in the symbol tilde-I_T. Its formula uses classical integrals and the fixed sigma^2/2 correction.',
 'D_A,T requires a path to visit both -A and A. The source claim that this prevents zero denominators does not cover the zero kernel permitted by its inherited kernel condition.',
 'The pathwise statistic defines a function of f but still prints X in its Lambda term. The original formula and the surrounding ordinary-integral explanation are preserved separately.',
 'The exact h_min(T) threshold is deferred to Remark B.1 in Appendix B. The main-text restricted index set is saved, with that missing formula explicitly unresolved.',
 'Fractional Brownian covariance does not determine the cross-H coupling. The common Volterra representation is given, but K_H is specified only in Appendix I equation (I.8), which is excluded.',
 'Theorem 6.3 contains a conditional probability statement and both orders of iterated liminf for the conditioning event. They are not collapsed to a single unconditional limit.',
 'Theorem 6.5 does not rebind epsilon_T,beta,L,J in its body; the preceding lower-bound reference supplies context but not a rewritten statement. Its displayed hypothesis classes do not repeat the global-Lipschitz restriction used to introduce the coupled solution notation.',
 'Theorem 6.5 concerns all uniformly level tests and preserves the supremum over H followed by the supremum over tests and infimum over alternatives. The proposed pathwise test in Remark 6.4 is not imposed on that all-test class.',
 'Theorem 7.1 defines its Gaussian objects inline and ranges uniformly over the full Sigma class. Its two-sided Brownian driver is indexed by space, distinct from the observation-time driver in (2.1).',
 'The bounded-Lipschitz metric is named on page 24 and its unit ball is described on page 25, but the exact norm convention is deferred to Appendix F.1. No alternative normalization is supplied by assumption.',
 'Plain italic T_T,D_A,T and H0,H1 are distinct from script index T and Holder H. Z_b,S_b,sigma_b use subscripts; X^{H,b} uses superscripts. These source roles remain distinct.',
 'Girsanov likelihood derivations, Proposition 6.2, continuity-mapping arguments, Gaussian approximation proof processes and Proposition 7.3 are not separately extracted as theorem statement prerequisites.'
]
excluded=[
 dict(reference='Appendix D',location='Section 2, page 6',resolution='Local Lipschitz terminology retained as ambient; no appendix definition read.'),
 dict(reference='Remark B.1, Appendix B',location='Section 6.1, page 19',resolution='Exact h_min(T) implementation threshold unresolved; original truncated index set retained.'),
 dict(reference='Equation (I.8), Appendix I',location='Section 6.2, page 20',resolution='Exact fractional coupling kernel K_H unresolved; original common Volterra representation retained.'),
 dict(reference='Appendix F.1',location='Sections 7.1–7.2, pages 24–25',resolution='Exact bounded-Lipschitz metric norm convention unresolved; main-text metric and unit-ball descriptions retained.'),
 dict(reference='Remarks H.6 and H.7',location='Remark 5.5, page 17',resolution='Fixed-point extensions of earlier stationary results are mentioned but not imported from the supplement.')
]
if __name__=='__main__':
    out=dict(paper_id=PID,scope='main_text_only',auxiliary_source_passages=aux,statement_resolution=resolution,source_issues=issues,excluded_references=excluded)
    (ROOT/'ambient-prerequisites.json').write_text(json.dumps(out,indent=2,ensure_ascii=False)+'\n')
    print(f'Saved {len(aux)} auxiliary source passages and {len(issues)} source notes.')
