"""Preserve source conventions, imported assumptions and unresolved formula domains."""
import json
from save_inventory import ROOT,PID,STATEMENTS

def main():
    aux=[]
    def add(n,s,pages,note,deps=()):aux.append(dict(local_id='A'+str(n),statement_original=s,evidence=[dict(page=p,location='Original main-text context A'+str(n)) for p in pages],scope_note=note,depends_on=list(deps)))
    add(1,r'''Let $\widehat\sigma_t^2$ be an estimator of $\widetilde\sigma_t^2$ constructed using $Y_1,\ldots,Y_t$ such that
\[
\widehat\sigma_t^2/\widetilde\sigma_t^2\xrightarrow{\mathrm{a.s.}}1.
\]
(13)''',[11],'Original ConditionL-3, including the definition of the data-based variance estimator. T2.8 explicitly requires its stronger polynomial-rate version L3eta; the weaker ratio property is retained as source context, not an implication-only graph edge.',['D6'])
    add(2,r'''Going forward, we may omit “a.s.” from $o_{\mathrm{a.s.}}(\cdot)$ and $O_{\mathrm{a.s.}}(\cdot)$ and instead simply write $o(\cdot)$ and $O(\cdot)$, respectively to simplify notation.''',[6],'Global source convention: unqualified little-o and big-O in the later nuisance-error and moment conditions are almost-sure rates, not rates merely in probability.')
    add(3,r'''In what follows, let $\mathcal T$ be a totally ordered infinite set that includes a minimum value $t_0\in\mathcal T$ (for example, one may think about $\mathcal T$ as $\mathbb R^{\ge0}$ or $\mathbb N$ with $t_0=0$) and let $(\widehat\theta_t)_{t\in\mathcal T}$ be a sequence of estimators for the real-valued parameters $(\theta_t)_{t\in\mathcal T}$.''',[9],'Shared ordered-time and estimator/parameter setup for G1–G4. The abstract theorem is not restricted to Gaussian or iid approximating processes.',['D2','D3','D4','D5'])
    add(4,r'''we have that $\psi$ can be written as a (non-counterfactual) functional of the distribution $\mathbb P$:
\[
\psi=\psi(\mathbb P)=\mathbb E\{\mathbb E(Y\mid X,A=1)-\mathbb E(Y\mid X,A=0)\}.
\]
Throughout the remainder of this section, we will operate under these identification assumptions and aim to derive efficient AsympCSs for $\psi$ by using tools from semiparametric theory.''',[16],'Observed-data representation of the ATE under the preceding named causal assumptions. The original potential-outcome definition and the assumption passage remain separate. This representation also identifies the roles of the treatment-specific regression functions in24.',['D14','D15','D16'])
    add(5,r'''To solidify the notation and problem setup, suppose that we observe a (potentially infinite) sequence of i.i.d. variables $Z_1,Z_2,\ldots$ from a distribution $\mathbb P$ where $Z_t:=(X_t,A_t,Y_t)$ denotes the $t$th subject’s triplet and $X_t\in\mathbb R^d$ are their measured baseline covariates, $A_t\in\{0,1\}$ is the treatment that they receive, and $Y_t\in\mathbb R$ is their measured outcome after treatment.''',[15,16],'Standing iid observed-data model for T3.1/T3.2. T3.3 explicitly generalizes to independent non-identically distributed triples. No biological/clinical conclusion is inferred from this mathematical model.')
    add(6,r'''or more generally under a Lyapunov-type condition that states $\sum_{t=1}^\infty[\mathbb E(|Y_t-\mu_t|^{2+\delta}\mid Y_1^{t-1})/\sqrt{V_t}^{2+\delta}]<\infty$ a.s. for some $\delta>0$.''',[11],'The preceding main-text Lyapunov condition supplies the positive exponent delta used but not re-quantified in Corollary2.6. Under its independence hypothesis this becomes the unconditional moment sum retained in D13. No appendix proof of implication to L2 is imported.',['D6','D7','D13'])
    add(7,r'''Let $(Y_t)_{t=1}^\infty$ be a sequence of random variables with conditional mean $\mu_t:=\mathbb E(Y_t\mid Y_1^{t-1})$ and conditional variance $\sigma_t^2:=\operatorname{var}(Y_t\mid Y_1^{t-1})$. Then under Assumptions L-1, L-2, and L-3, we have that''',[11],'Original Proposition2.5 setup referenced by T2.8. The theorem explicitly selects L1,L2 and the stronger L3eta, rather than the proposition’s weaker variance-rate assumption. Its new interval is18, not a silently copied earlier formula.',['D6','D7','D8'])
    add(8,r'''Then using the sample variance for $\widehat\sigma_t^2$, $\widetilde C_t$ forms a $(1-\alpha)$-AsympCS for the running average mean $\widetilde\mu_t:=\frac1t\sum_{i=1}^t\mu_i$.''',[12],'Original final sentence of Corollary2.6: sample variance supplies its estimator after the listed assumptions. T3.3 imports those assumptions for bar-f(Z_t) and prints varhat_t(bar-f). Its formula is retained, but the main text does not explicitly equate this with the fitted cross-fold variance26 or supply an observable replacement.',['D1','D6','D13'])
    add(9,r'''$\widehat{\operatorname{var}}_t(\overline f)$''',[21],'Exact variance symbol in T3.3. Unlike T3.1/T3.2 it takes the limiting bar-f as argument. Formula26 explicitly defines a cross-fit variance for fitted hat-f; Corollary2.6 discusses sample variance. The inspected main text does not resolve whether the printed symbol means the ideal full-sample variance, the fold functional evaluated at bar-f, or a feasible fitted substitution. Preserve this unresolved source object; do not assert a new dependency/equality to D22.')
    add(10,r'''where $f$ is the uncentered efficient influence function (EIF) defined in (24).''',[22],'The source explicitly calls f uncentered: it has expectation psi rather than0. No minus-psi term is silently inserted into24 or27.',['D18'])
    add(11,r'''Note that unlike Theorems 3.1 and 3.2, Theorem 3.3 actually does require the use of the cross-fit AIPW estimator $\widehat\psi_t^\times$ and would not capture $\widetilde\psi_t$ if the sample-split version were used in its place.''',[22],'Original distinction between the full cross-fit and single evaluation-fold estimator for moving effects. Do not replace the two-fold estimator with a more convenient single-fold estimate.',['D21','D25'])
    add(12,STATEMENTS[0].split('Let ',1)[1].split(' Then,',1)[0],[8],'Original definitions of empirical mean and variance with denominator t. These supply ambient sample-moment notation reused by the non-iid boundaries; they do not impose iid sampling wherever a sample mean is evaluated.')
    issues=[]
    def issue(i,pages,note):issues.append(dict(issue_id=i,evidence=[dict(page=p,location='Source scope or notation issue') for p in pages],note=note))
    issue('registered-source-and-numbering',[1,11,12,28],'Registered source is arXiv2103.06476v9 marked14Mar2024,69pages. Actual main text ends on28 before References y638.557, clipped632. The outline has stale/displaced labels and page references; actual bold headings establish exactly six Theorems. Proposition2.5 and Corollary2.6 are not added as Theorems. Appendix bodies begin33 and remain excluded.')
    issue('asympcs-versus-coverage',[6,13],'Definition2.1 is almost-sure relative-width approximation to an existing valid CS with the same center. Definition2.7 instead describes limiting all-future coverage as the starting index m increases. Neither definition is substituted for the other; T2.8 additionally proves an ordinary limit equality. Separate marginal-in-time coverage is insufficient.')
    issue('zero-width-and-degenerate-variance',[6,8,13],'Definition2.1 requires strictly positive bounds at every time. T2.2 assumes finite variance without explicitly excluding zero population variance, and its empirical variance is zero at t=1. Rho_m also divides by the variance estimate at m. No initial padding, start-time or degenerate-case convention is printed in these statements; preserve and flag rather than silently correcting them.')
    issue('tuning-domain-and-data-dependence',[13],'The numerator -2log(alpha)+log(-2log(alpha))+1 in rho_m can be negative for alpha sufficiently close to1, while the source generally allows alpha∈(0,1). A further domain restriction would be required for that displayed square root to be real. Rho_m also depends on estimated variance at the first peeking time, so it must not be replaced by arbitrary fixed rho in the sharp-coverage theorem.')
    issue('variance-divergence-wording',[10],'The prose before L1 says the average variance either does not vanish or does so superlinearly. Formal L1 requires V_t=t times average variance to diverge; surrounding explanation says the average does not vanish faster than1/t, with an omega_a.s.(1/t) formula. Preserve the original wording and use the explicit formal condition, without rewriting it.')
    issue('almost-sure-rate-convention',[6,18,19,20,21],'The source globally suppresses a.s. on little-o/big-O. Later nuisance convergence, product rates and uniform/average conditions inherit almost-sure meaning. Do not downgrade them to in-probability rates because L2(P) norms themselves resemble mean-square convergence.')
    issue('true-versus-estimated-overlap',[18,19,21],'T3.1 explicitly bounds the true propensity away from0 and1, and T3.2 inherits this common setup while estimating propensity. The main-text statements do not separately bound or clip estimated propensities, though they enter denominators. T3.3 does not explicitly import T3.1 overlap; retain named causal positivity and its own moment hypotheses without inventing a stronger uniform-overlap premise.')
    issue('identification-and-regression-source-detail',[16,17,18,20],'Consistency, positivity and exchangeability are named and cited rather than formally expanded in the main text. Mu^a is described as a conditional mean function and used in the identified ATE/EIF formulas, but a separate explicit conditional-regression equality is not printed in these passages. Preserve this source limitation instead of synthesizing an original definition or reading an appendix.')
    issue('uncentered-and-misspecified-influence',[17,18,19,22],'Formula24 is explicitly an uncentered EIF; subtracting psi would change the AIPW estimator25. Formula27 uses potentially misspecified regression limits with the true propensity. T3.1 allows such limits, whereas T3.2 requires consistent nuisance functions and convergence to the efficient f. Its common-setup reference does not reimpose known propensity.')
    issue('fold-size-and-variance-conventions',[16,17],'The infinity-subscript split streams are counted at current time t by an explicit convention. Early times may leave a fold empty; the source does not define all estimator/variance values then. Variance26 averages two fold variances equally, not by random fold size, and the within-fold normalization is named sample variance rather than reprinted. Preserve these choices and ambiguities.')
    issue('theorem-three-three-variance',[12,17,21],'T3.3 prints varhat_t(bar-f), not varhat_t(hat-f). The former is not separately defined in the main text as an observable statistic; Corollary2.6 uses sample variance while26 defines a cross-fit fitted variance. Preserve the printed expression and unresolved interpretation. No fabricated equivalence or direct D22 dependency is introduced for T3.3.')
    issue('time-varying-regressions-and-effects',[20,21],'Section3.4 permits changing data distributions and expected treatment effects but writes common functions mu^a andpi without time subscripts. Their applicability across all t is not fully spelled out beyond the displayed conditions. The term individual treatment effects denotes expected Y_t^1-Y_t^0 in the source, not realized unit-level effects. Uniformity over all i in ATE1 differs from the average-product condition ATE2.')
    issue('corollary-import-and-pointwise-shortcut',[11,12,21],'T3.3 imports all Corollary2.6 assumptions after substituting bar-f(Z_t): L1, positive-delta Lyapunov summability, squared-observation moments, mean growth and relative mean variation. The following informal statement that pointwise-in-i product rates imply the averaged ATE2 rate needs uniform control and is not used as a replacement for the actual average condition.')
    issue('abstract-boundary-and-ordered-time',[6,9,10],'The abstract theorem permits general totally ordered infinite time sets. Meaning of t→infinity, existence of a cofinal sequence and simultaneous-event measurability require ordinary analytical conventions not fully specified for arbitrary ordered sets. Preserve the source generality. Hatted approximating boundaries, unadorned approximate widths and starred valid widths are distinct objects.')
    bindings={
'T2.2':'Iid Y_t fromP, meanmu, finite variance, sample mean and sample variance are bound in the statement. Alpha is a miscoverage level in(0,1), rho is prespecified positive. Its conclusion uses AsympCS Definition2.1; no sub-Gaussian or higher-moment hypothesis is imported from the proof.',
'T2.4':'Ordered infinite T, minimal t0, real estimator process and parameters from G-setup. Explicit conditionsG1–G4 bind the coupled processZ, rate r, hatted boundaries and their unadorned approximations. Starred valid widths are existential outputs on a potentially enlarged probability space.',
'T2.8':'Conditional moment process from Proposition2.5; explicitL1,L2,L3eta, interval18 and start-dependent rho_m. Running targetmu_tilde, alpha and the all-future event are bound in the theorem/source setup. No iid assumption, convergent average variance, fixedrho or Corollary2.6 conditions are added.',
'T3.1':'Section3 iid triplets and named causal identification assumptions; known propensity in the randomized specialization, cross-fit estimator25 and variance26. Regression limits bar-mu may be misspecified, true propensity satisfies overlap, and the limit bar-f has2+epsilon moments. Nuisance L2 error rates are almost sure by the global convention.',
'T3.2':'Inherits Section3 sampling/identification, cross-fitting, true propensity overlap and estimator/variance definitions from the common setup. Overrides known propensity with consistent estimates, requires actual regression consistency and the product rate, and replaces limitbar-f with efficientf and its stated moment condition. No randomized-only known-propensity requirement is imported.',
'T3.3':'Independent possibly nonidentical triples, moving effectpsi_t and its running mean, explicitATE1 uniform regression convergence andATE2 average product error, and every Corollary2.6 assumption with Y replaced bybar-f(Z_t). Full cross-fitting is required. The printed variance argumentbar-f is an unresolved source object retained in A9; no fitted substitution is asserted. Rho>0 andalpha∈(0,1) follow the preceding boundary convention.'}
    refs=[]
    def ref(claim,target,kind,note):refs.append(dict(claim_id=PID+'/'+claim,target=target,reference_kind=kind,note=note))
    ref('T2.8','Proposition 2.5 and Conditions L-1/L-2/L-3-η','assumption_reference','Retain the conditional moment setup and explicitly strengthened variance estimation condition; no unrelated independent-data hypotheses.')
    ref('T3.2','Theorem 3.1 — common setup with stated overrides','assumption_reference','Preserve shared iid data, identification, cross-fitting and true overlap. Known propensity and misspecified-limit choices are changed by the new theorem, not imported unchanged.')
    ref('T3.3','Corollary 2.6 — all assumptions under substitution','assumption_reference','Apply every original condition to the sequencebar-f(Z_t), preserving the moment/mean/variance requirements and the non-iid distinction.')
    for n in ['T3.1','T3.2']:ref(n,'Theorem 2.2','proof_only','The proof discussion invokes the Gaussian-mixture AsympCS; the full theorem’s iid-observation premise is not imported onto trained pseudo-outcomes as a new condition.')
    ref('T2.2','Strassen approximation and Robbins boundary','proof_only','These main-text facts explain the derivation, but the stated theorem already binds its iid finite-variance model and explicit width. No Gaussian data assumption is introduced.')
    ref('T3.3','Martingale alternative in Appendix B.6','excluded_alternative','The source explicitly defers a predictable-estimator/martingale alternative. It does not replace this theorem’s full cross-fitting or allow appendix intake.')
    data=dict(paper_id=PID,unranked_auxiliary_passages=aux,statement_local_bindings=bindings,source_claim_references=refs,source_issues=issues,ambient_prerequisites=['Expectation, conditional expectation, variance, probability, finite real moments, L2(P) norms, almost-sure convergence and order notation with the explicit source convention A2.','Real-valued stochastic processes on ordered time sets, simultaneous-event measurability, positive widths, pointwise parameter sequences and existential couplings on enlarged probability spaces.','Binary treatment, real outcome, vector covariates, counterfactual outcomes, training/evaluation fold indexing, empirical means and sample variances. No library availability claim.'],validation_limits='Source census only: original statements, definitions and references are preserved. Source domain/notation gaps and deferred appendix detail are recorded without proof certification or silent repair.')
    (ROOT/'ambient-prerequisites.json').write_text(json.dumps(data,indent=2,ensure_ascii=False)+'\n')
if __name__=='__main__':main()
