"""Retain branch-specific assumptions, source ambiguities and unranked context."""
import json
from save_inventory import ROOT,PID,STATEMENTS

def main():
    aux=[]
    def add(n,s,pages,note,deps=()):aux.append(dict(local_id='A'+str(n),statement_original=s,evidence=[dict(page=p,location='Original main-text context A'+str(n)) for p in pages],scope_note=note,depends_on=list(deps)))
    add(1,'Assume that'+STATEMENTS[0].split('Assume that',1)[1].split('then,',1)[0],[11],'Theorem1’s uniform nondegeneracy (11) and all five dimension/block-exponent inequalities (12). Retain the independent growth exponents B and alpha_p1, together with 0<alpha_s<alpha_l<1. These general-combination conditions are not imported through Theorem4’s reference to the numeric v_T definition.',['D1','D10'])
    add(2,'Suppose further that'+STATEMENTS[1].split('Suppose further that',1)[1].split('(i) If',1)[0],[14],'Theorem2’s common nonempty lag sets, lag growth and five inequalities (17). Shared by its two branches and by Theorem4(i)–(ii), but not the fixed-order AR branches.')
    add(3,'If'+STATEMENTS[1].split('(i) If',1)[1].split('then,',1)[0],[14],'Autocovariance nondegeneracy (18), restricted to j in H. This premise belongs to Theorem2(i) and Theorem4(i), not their autocorrelation branches.',['D1','D6'])
    add(4,'suppose there exists'+STATEMENTS[1].split('and suppose there exists',1)[1].split('Then',1)[0],[15],'Autocorrelation nondegeneracy (20), including sigma_0>c, restricted to j in I. Use the Theorem2(ii) definition of Z, not Theorem1 or the AR Z.',['D1','D6','D11'])
    add(5,'Let $p$'+STATEMENTS[2].split('Let $p$',1)[1].split('Then,',1)[0],[18],'Fixed positive integer order, explicit weak stationarity, uniform minimum eigenvalue bound and AR nondegeneracy (28). Theorem4(iii) inherits the assumptions of Theorem3 through Lemma4(iii).',['D1','D6','D14','D16'])
    add(6,r'''Suppose $K(\cdot):\mathbb R\to[0,\infty)$ is a kernel function satisfying Definition 2 and $k_T\to\infty$ as $T\to\infty$. The random variables $\{X_i,i\in\mathbb Z\}$ are $(m,\alpha_X)$-short range dependent with $m\ge8$, $\alpha_X>2$.''',[19],'Common Lemma4 assumptions explicitly imported by Theorem4. The corresponding branch assumptions are archived separately in A7–A9.',['D5','D17'])
    add(7,r'''(i) Suppose that $d=O(T^{\beta_X})$ is a positive integer, that the set $\mathcal H\subset\{0,1,\ldots,d\}$ is not empty and that (17) and (18) hold true.''',[19],'Lemma4(i) assumptions imported for Theorem4(i). The covariance-estimator conclusion of Lemma4 is not an extra hypothesis or the definition of the bootstrap statistic.')
    add(8,r'''(ii) Suppose that $d=O(T^{\beta_X})$ is a positive integer, the set $\mathcal I\subset\{1,\ldots,d\}$ is not empty and that (17) and (20) hold true.''',[19],'Lemma4(ii) assumptions imported for Theorem4(ii). Its estimated linearization is a covariance-estimation object, not the nonlinear bootstrap autocorrelation definition (40).')
    add(9,r'''(iii) Suppose that the conditions of Theorem 3 are satisfied.''',[20],'Lemma4(iii) explicitly imports the complete assumptions of Theorem3. Theorem4(iii) therefore inherits weak stationarity, fixed order, dependence and AR nondegeneracy; no analogous whole-Theorem1 import follows from defining v_T.')
    add(10,'(i) In addition suppose'+STATEMENTS[3].split('(i) In addition suppose',1)[1].split('Then',1)[0],[23],'Theorem4(i) bandwidth conditions; its (ii) branch repeats the same rates. Preserve 7*alpha_X*beta_X and 8*beta_X/m+7*alpha_X*beta_X−1/2. These are not the weaker covariance-estimator rates of Lemma4.',['D18'])
    add(11,'(iii) In addition suppose'+STATEMENTS[3].split('(iii) In addition suppose',1)[1].split('Then,',1)[0],[23],'Theorem4(iii) fixed-order bandwidth conditions v_T=o(1), k_T*T^(−1/2)=o(1), with (28) and the minimum eigenvalue bound. Preserve the printed positive-number wording for p; the inherited context requires an integer.',['D14','D18'])
    add(12,r'''Recall the definition of a sample quantile: For a numerical sequence $a_b$, $b=1,\ldots,B$ such that $a_1\le a_2\le\cdots\le a_B$,
\[
C^*_{1-\alpha}=a_{b^*},\text{ where }b^*=\min\left\{b=1,\ldots,B:\frac1B\sum_{c=1}^B\mathbf1_{\{a_c\le a_b\}}\ge1-\alpha\right\}.
\]
(42)''',[22],'Finite-bootstrap empirical quantile with its exact tie convention. Theorem4 concerns the exact conditional law. The separate B→infinity simulation approximation is discussed in prose and is not a missing fourth theorem branch.')
    add(13,r'''the solution of the $p$th order system of Yule-Walker equation, determines the coefficients of the best linear predictor of $X_i$ in the Hilbert space spanned by $X_{i-1},\ldots,X_{i-p}$. More precisely, the best linear predictor of $X_i$ is given by $\sum_{j=1}^p\beta_jX_{i-j}$, which by (2.7.15) in Brockwell and Davis (1991), satisfies
\[
EX_iX_{i-k}=\sum_{j=1}^p\beta_jEX_{i-j}X_{i-k}\text{ for }k=1,2,\ldots,p
\]
(25)
and, therefore, coincides with (23).''',[17],'Interpretation of Definition3 as linear prediction for a general weakly stationary series. Do not add the fitted AR model (22) or iid innovations as generating assumptions.',['D12'])
    add(14,r'''Define the filter $\mathcal F_i$ as the $\sigma$-field generated by $\ldots,e_{i-2},e_{i-1},e_i$ and $\mathcal F_{i,k}$ as the $\sigma$-field generated by $e_{i-k},e_{i-k+1},\ldots,e_i$, where $i\in\mathbb Z$ and $k\ge0$. Using these definitions, $X_{i,j}$ is $\mathcal F_i$ measurable.''',[7],'Filtration context for the causal construction. Conditional projections used in main-text lemmas or proofs are not added as theorem statement dependencies.',['D2'])
    add(15,r'''Observations $X_1,\ldots,X_T$, the maximum lag $d$, the lag for calculating AR coefficients $p$ ($p\le d$), the kernel function $K(\cdot):\mathbb R\to[0,\infty)$, a bandwidth $k_T$, the nominal coverage probability $1-\alpha$ and the number of bootstrap replicates $B$. We also need the index set $\mathcal H\subset\{0,1,\ldots,d\}$ for autocovariances and the index set $\mathcal I\subset\{1,2,\ldots,d\}$ for autocorrelations.''',[21],'Algorithm1 input domains, including p≤d and the different lag-zero conventions for H and I. The nominal level and finite simulation count are implementation inputs; Theorem4 controls the exact conditional laws.',['D17','D18'])
    issues=[]
    def issue(i,pages,note):issues.append(dict(issue_id=i,evidence=[dict(page=p,location='Source scope or notation issue') for p in pages],note=note))
    issue('short-range-tail-summand',[8],'Remark2 prints sum from l=k to infinity of delta_m(k), whereas Definition1 uses delta_m(l). Preserve both. The explicit beta=0 specialization identifies the intended short-range condition; the literal constant-summand display is inconsistent except in degenerate cases.')
    issue('gaussian-covariance-lag-indices',[15,19],'Theorem2(i) prints unbound j in both covariance factors instead of j1 and j2. The intended two-lag covariance is shown correctly in Lemma4(i), equation(30). No repair is inserted into the original theorem statement or the CDF definition that refers to it.')
    issue('undefined-ar-centering',[18],'Equation(27) prints sigma_k^(i), without a definition of this time-indexed quantity in the main text. Weak stationarity suggests E X_i X_(i−k)=sigma_k. Preserve the printed superscript and record this inferred interpretation separately; do not pretend a source definition was found.')
    issue('stationarity-and-triangular-arrays',[6,7,14,18],'The causal construction allows independent nonidentically distributed innovations and functions that vary with i,j,T. Theorem1 need not be weakly stationary. Section3 assumes weak stationarity for autocovariance/autocorrelation inference, and Theorem3 explicitly assumes it; this is not strict stationarity. Parameters and Gaussian approximants may change with T.')
    issue('branchwise-lemma-four-import',[19,20,23],'Read Theorem4’s Lemma4 reference branchwise: common kernel/dependence assumptions plus the corresponding (i),(ii),(iii) premise. Importing all three branches simultaneously would spuriously require an AR model/order in pure autocovariance inference and impose growing-lag constraints on the fixed-order AR result.')
    issue('definition-reference-not-whole-lemma',[13,23],'Theorem4 says define v_T as in Lemma3. This imports the three-case numerical sequence and its parameter alpha=alpha_X, not Lemma3’s whole-Theorem1 assumption reference or its covariance estimator conclusion.')
    issue('ratio-and-sample-solution-domains',[14,16,22],'The source gives no explicit value for sample or bootstrap correlations if their lag-zero denominator vanishes. Population autocorrelation inference assumes sigma_0>c. The original sample Yule–Walker definition specifies solving a system; only the bootstrap definition explicitly uses a Moore–Penrose inverse. Domain conventions remain separate from source transcriptions.')
    issue('ar-interpretation-and-order',[16,17,18,23],'Definition3 concerns general-process Yule–Walker coefficients, not a linear AR data-generating restriction. Theorem3 has positive integer p=O(1); Theorem4(iii) prints positive number but inherits that integer setting. A strictly positive spectral density is a sufficient condition in prose, not an extra theorem premise.')
    issue('symbol-overloading',[6,7,11,12,18,21,22],'d first denotes vector dimension and later maximum lag; e_i is an innovation and later a coordinate vector; B is a growth exponent, an AR derivative matrix, and a bootstrap-replicate count. Alpha is a decay exponent or nominal error probability, depending on context. Z and xi are redefined between theorems; preserve paper-local scope.')
    issue('kernel-normalization-and-psd',[12,13,21],'Definition2 imposes K(0)=1, not integral K=1. Nonnegative integrable Fourier transform yields positive-semidefinite multiplier covariance. The Gaussian example is optional. Preserve the printed unusual word di-fferentiable without altering its mathematical meaning.')
    issue('bootstrap-laws-and-rates',[22,23],'Theorem4 bounds conditional Gaussian-bootstrap CDF errors with outer stochastic rates. Only branch(i) gives the explicit sum of sixth-root Op rates; branches(ii),(iii) state op(1). Finite B simulation quantile error is separate, discussed using B→infinity in prose; T4 is not an exact finite-sample coverage theorem.')
    issue('finite-lag-boundary-and-centering',[11,14,18,21],'Observed lag-product sums start at j+1 and have denominator T. Gaussian covariance targets use ideal centered sums over i=1..T of the infinite process. No circular or zero-padded data, sample-mean subtraction, T−j denominator or stationary simplification is silently inserted into Theorem1.')
    issue('nondegeneracy-and-growth-scope',[11,14,15,18,23],'Uniform positive lower bounds concern the standard deviation of each normalized centered sum, not merely the variance of X_i. The autocorrelation branch additionally requires sigma_0>c. Keep all five exponent inequalities in(12) and(17), but use(17) only for growing-lag covariance/correlation branches; AR order remains O(1).')
    bindings={
      'T1':dict(standing_context='Mean-zero causal triangular array via short-range Definition1/Remark2; no weak stationarity.',assumptions=['A1'],parameters='m≥8, alpha>2; positive d=O(T^B); p1=O(T^alpha_p1); deterministic coefficient row-square bound; separate B and alpha_p1.',local_objects=['D10'],conclusion='Kolmogorov approximation of the maximum of p1 normalized linear combinations by a mean-zero Gaussian vector with the displayed T-dependent covariance.'),
      'T2':dict(standing_context='Section3 mean-zero weak stationarity, possibly T-dependent law.',common_assumptions=['A2'],branches={'i':dict(assumptions=['A3'],objects=['D6','D7'],gaussian_covariance_issue='gaussian-covariance-lag-indices'),'ii':dict(assumptions=['A4'],objects=['D8','D9','D11'])},conclusion='Two Gaussian approximation statements in one Theorem environment; branch premises remain separate.'),
      'T3':dict(standing_context='Explicit weak stationarity; general time series, not a linear AR data-generating model.',assumptions=['A5'],local_objects=['D12','D13','D14','D15','D16'],conclusion='Gaussian maximum approximation for fixed-order Yule–Walker estimation error; unresolved sigma_k^(i) notation retained.'),
      'T4':dict(standing_context='Common Lemma4 kernel and short-range hypotheses, plus corresponding branch assumptions; Section3 or T3 weak-stationarity context.',common_assumptions=['A6'],definition_only_reference='D18 from Lemma3',branches={'i':dict(assumptions=['A2','A3','A7','A10'],objects=['D6','D7','D19','D22','D25'],rate='Op sum of two sixth-root terms in (45)'),'ii':dict(assumptions=['A2','A4','A8','A10'],objects=['D8','D9','D19','D23','D25'],rate='op(1) in (46); A10 stores the identical bandwidth restrictions from branch(i)'),'iii':dict(assumptions=['A5','A9','A11'],objects=['D12','D13','D14','D16','D19','D24','D25'],rate='op(1) in (47)')},conclusion='Conditional bootstrap maximum-CDF approximation; B→infinity empirical-quantile context A12 is separate.')}
    refs=[
      dict(claim_id=PID+'/T1',reference='Definition1 and Remark2',reference_kind='definition_reference',resolution='D2–D5 preserve the causal construction and beta=0 short-range definition.'),
      dict(claim_id=PID+'/T2',reference='Section3 setting and (16)',reference_kind='definition_reference',resolution='D6–D9 identify stationary covariance/correlation targets and sample estimates; A2–A4 preserve separate assumptions.'),
      dict(claim_id=PID+'/T3',reference='Definition3 and (27)',reference_kind='definition_reference',resolution='D12–D16 preserve Yule–Walker targets, sample equations and full AR linearization.'),
      dict(claim_id=PID+'/T4',reference='conditions of Lemma4',reference_kind='assumption_reference',resolution='A6 common assumptions, A7 for(i), A8 for(ii), A9 importing T3 assumptions for(iii). Do not union all branch premises within each branch.'),
      dict(claim_id=PID+'/T4',reference='define v_T as in Lemma3',reference_kind='definition_reference',resolution='D18 only; no import of Lemma3’s whole-Theorem1 assumption reference.'),
      dict(claim_id=PID+'/T4',reference='H_sigma,H_rho,H_a; Algorithm1 equations(38)–(40)',reference_kind='definition_reference',resolution='D19–D25 preserve exact conditional probability, bootstrap statistics and T-dependent Gaussian targets.'),
      dict(claim_id=PID+'/T3',reference='Definition1.3.2 in Brockwell and Davis(1991)',reference_kind='external_definition_reference',resolution='Weak stationarity is cited externally in Definition3. The paper’s own lag-invariant second-moment convention is retained; external text was not fetched.')]
    data=dict(paper_id=PID,unranked_auxiliary_passages=aux,source_issues=issues,statement_local_bindings=bindings,source_claim_references=refs,ambient_conventions=['Real random variables, expectation, Gaussian vectors, finite sums, absolute values and real matrices are ambient mathematical objects; library availability is not assessed.','O,o concern deterministic asymptotic quantities; Op,op concern stochastic quantities, with T the observed sample size. All uniformity and dimension-growth restrictions are preserved in the theorem statements and auxiliary conditions.','There are no implication-only dependency edges. Inline numerical assumptions remain branch-specific source context rather than invented named definitions.'])
    (ROOT/'ambient-prerequisites.json').write_text(json.dumps(data,indent=2,ensure_ascii=False)+'\n')
if __name__=='__main__':main()
