"""Resolve the four statements while preserving the source's infinite-family conventions."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];PID=ROOT.name
aux=[]
def add(aid,text,pages,loc,meaning):aux.append(dict(auxiliary_id=aid,statement_original=text.strip(),evidence=[dict(page=p,location=loc) for p in pages],resolution=meaning))
add('A1',r'''Note that this setting encompasses the classical setting as a special case, in which $\mathcal F_i=\mathcal A$ for all $i\in\mathbb N$ and the testing process is stopped after $m\in\mathbb N$ steps, e.g. by choosing $H_i=\mathcal P$ and $d_i=0$ for all $i>m$. In a similar way, online batch testing [39] can be embedded in our framework. Even though the theoretical results of this paper apply in this general setting, we focus on the strict online case of $\mathcal F_1\subset\mathcal F_2\subset\ldots$ when deriving concrete online closed procedures.''',[3],'Section 2 — general versus strict information growth','The generic theorems allow non-strictly increasing sigma-fields; strict growth is an application focus. Finite and batch testing are included through the stated embedding, not by replacing the countably infinite index domain of the original statements.')
add('A2',r'''In contrast to strong control, weak FWER control only requires that $\operatorname{FWER}_{\mathbb P}\leq\alpha$ for all distributions contained in the global null hypothesis $\mathbb P\in\bigcap_{i\in\mathbb N}H_i$. This is only of limited use in practice. Hence, when we write control in the remainder of this paper, we always mean strong control.''',[3],'Section 2 — default meaning of FWER control','Theorem 3.5’s shorter phrase FWER control still means strong control. It does not merely assume control under the global null.')
add('A3',r'''If $\boldsymbol\phi=(\phi_I)_{I\subseteq\mathbb N}$ is predictable, then $d_i^\phi$ defined in Theorem 3.2 satisfies $d_i^\phi=\min\{\phi_I:I\subseteq\{1,\ldots,i\}\text{ with }i\in I\}$ for all $i\in\mathbb N$.''',[4],'Lemma 3.3 — source statement of the finite-prefix reduction','This main-text lemma explains why the predictable closure can be online and measurable. It is archived as context, not added to the Theorem inventory and not used to repair the arbitrary-family first assertion of Theorem 3.2. Simultaneous validity of the predictability comparisons is required for a pointwise reduction.')
add('A4',r'''It should be noted that in order to obtain online procedures with the required error rate control, $p_i$ and $\alpha_i$ are often chosen to be measurable with respect to smaller $\sigma$-fields $\mathcal X_i\subseteq\mathcal F_i$ and $\mathcal Y_i\subseteq\mathcal F_i$, respectively, such that $\mathbb P(p_i\leq\alpha_i\mid\mathcal Y_i)\leq\alpha_i$ for all $\mathbb P\in H_i$. However, this is contained in our more general setting.''',[7],'Section 4 — optional conditional-validity construction','Conditional superuniformity is one way to achieve error control. It is not an implicit condition in the general definition of an online alpha-adjustment, whose threshold can use current information.')
add('A5',r'''The individual significance levels $(\alpha_i)_{i\in\mathbb N}$ are then usually chosen as non-random functions of indicators (e.g. rejections) of the previous p-values, which ensures that $\alpha_i$ is measurable with respect to $\mathcal F_{i-1}\subseteq\mathcal F_i$. If the p-values are independent, we have $\mathbb P(p_i\leq\alpha_i\mid\mathcal F_{i-1})\leq\alpha_i$ for all $\mathbb P\in H_i$.''',[7],'Section 4 — previous-p-value example','This follows the example F_i=sigma(p_1,...,p_i). Its independence and previous-time measurability are example assumptions, not prerequisites of Theorems 3.2,3.5,3.9 or the general Theorem 4.2.')
add('A6',r'''Note that this condition implies that the corresponding family of online intersection tests $\boldsymbol\phi=(\phi_I)_{I\subseteq\mathbb N}$ defined by (3) is predictable as well (Definition 3.1) and hence the resulting closed procedure $\boldsymbol d^\phi$ is an online procedure (Theorem 3.2). However, it is not necessary for predictability of $\boldsymbol\phi$, as one could also choose $\alpha_j^I<\alpha_j^K$, where $I$ and $K$ are defined as in Definition 4.1.''',[7],'After Definition 4.1 — distinction between the two predictability notions','Equality of old thresholds under future extensions implies rejection persistence, but the concepts are not identical. The strict-inequality suggestion is retained as source prose; it is not substituted for Definition 4.1 in the threshold shortcut theorem.')
issues=[]
def issue(key,text,pages):issues.append(dict(issue_id=key,description=text,evidence=[dict(page=p,location='Inspected main-text source convention') for p in pages],resolution_status='source_preserved'))
issue('S1','The first assertion of Theorem 3.2 minimizes over all subsets I of N containing i, an uncountable family. An uncountable infimum of individually measurable binary tests need not be measurable. The source does not state a common measurability or outer-probability convention for this arbitrary-family closure. The predictable case has a finite-prefix reduction, but that extra premise is not inserted into the first assertion.',[3,4])
issue('S2','Section 2 interprets random-variable equalities and inequalities almost surely for every model law. The predictability definitions compare uncountably many intersections, so separate almost-sure comparisons need not have a common full-measure event. The finite-prefix reduction requires a simultaneous interpretation or consistent versions; the source does not explicitly resolve this distinction.',[2,3,4,7])
issue('S3','Theorem 3.5 writes max{d_i:i in I} for every I, including the empty set. Section 3 explicitly fixes phi_empty=0, supplying the intended empty-maximum convention. For a nonempty infinite subset the binary maximum is well defined; no real-valued compactness assumption is needed.',[3,4])
issue('S4','Online intersection tests use F_sup(I), with F_infinity=A. The empty set has no explicitly defined supremum or F_0, but its test is the separately fixed constant zero. This is not replaced by an unstated time-zero filtration definition.',[3])
issue('S5','An online test is only a measurability property. Its alpha-level property is a separate probability bound, and predictability is a third, across-intersection property. None is inferred automatically from the others in the census.',[3,7])
issue('S6','Definition 3.1 adds only future indices to a finite prefix intersection. It does not require rejection to persist when omitted earlier indices are inserted, and it is not the standard stochastic-process notion of predictability.',[3])
issue('S7','Definition 4.1 requires equality of existing thresholds when future indices are added. Definition 3.1 requires only persistence of rejection. The source explicitly says the threshold condition is stronger; the two are kept as different interfaces and are not merged.',[3,7])
issue('S8','Online alpha-adjustments are allowed to be measurable with respect to F_i, not only F_{i-1}. Thus they may depend on the current p-value. Marginally valid p-values alone do not give error control for arbitrary such thresholds; Theorem 4.2 expressly assumes level-alpha intersection tests.',[7,8])
issue('S9','The general results do not assume independent p-values, conditional superuniformity, or a filtration generated solely by previous p-values. Those assumptions appear only in explanatory examples. Theorem 4.2’s explicit intersection-test level condition remains the controlling hypothesis.',[7,8])
issue('S10','The recursion I_i in both shortcut theorems selects a random finite subset of {1,...,i}. Evaluation of phi_{I_i} or alpha_i^{I_i} uses the relevant finite-valued selection; it is not an evaluation at a fixed deterministic subset. The second theorem uses p_j>alpha_j^{I_j}, whereas the first uses phi_{I_j}=0, and both recursions are preserved literally.',[6,8])
issue('S11','Equality of procedure decisions is interpreted almost surely under each model law by the standing convention. Since the decision coordinates are countable, coordinatewise equalities can be made simultaneous per law. This is stronger than merely having the same distribution and distinct from a common event across all laws or all uncountably indexed tests.',[2,4,6,8])
issue('S12','Strong FWER is required for every model law and over the entire sequence. The increasing count v_P can equal infinity; the error event remains v_P>0. Weak global-null control is not substituted for strong control, including where Theorem 3.5 abbreviates the terminology.',[3,4])
issue('S13','The model treats each hypothesis as a subset of a fixed abstract family of probability laws. The introduction’s emphasis on hypotheses not being known in advance does not by itself define arbitrary data-dependent random hypotheses or permit selection without accounting for validity.',[2])
issue('S14','Consonance supplies a witness inside each rejected intersection whose containing sub-intersections are rejected. It does not impose rejection of arbitrary supersets. A raw intersection rejection is not silently identified with a rejection by every superset in the closed procedure.',[4,6])
issue('S15','The shortcut theorem gives one selected intersection test for each individual decision. It does not specify the computational cost of evaluating an arbitrary intersection test or guarantee constant-time updates for every possible family.',[6,8])
issue('S16','Individual thresholds lie in [0,1), and the decision uses a non-strict p_i<=alpha_i comparison. Non-rejections in Theorem 4.2 use the strict complement p_j>alpha_j^{I_j}; threshold equality is not reassigned to acceptance.',[7,8])
issue('S17','Theorem 3.5 is in the admissibility section but assumes no admissibility hypothesis. Definition 3.4 and later admissibility Propositions/Corollaries are not necessary statement prerequisites. Alpha-Spending, Online-Graph and ADDIS rules later instantiate the general framework but are not parameters required to state any of the four inventoried Theorems.',[4,5,8,9,10,11,12])
issue('S18','The PDF carries an arXiv v3 margin stamp of 21 December 2023 but a title-page date of 22 December 2023. The pinned version and both dates are recorded. Equality to the final journal wording has not been established.',[1])
resolution={
 'shared':'Indices are the positive integers starting at 1. The abstract measurable experiment, hypothesis subsets and increasing information fields are D1. Unless otherwise stated, random comparisons hold almost surely under each model law. Binary acceptance/rejection decisions, natural-index set operations, conditional and ordinary probabilities use their usual meanings. The empty intersection test is explicitly zero; F_infinity is A. Uncountable-family measurability and simultaneous-version conventions remain unresolved source issues.',
 '3.2':'D4 and D6 supply intersection hypotheses and level-alpha tests. D8 is the inline all-subsets closure; D3 supplies strong FWER. The online conclusion separately uses D5, D7 and D2 for intersection adaptedness, future-extension rejection persistence and adapted individual decisions. The arbitrary-family first assertion does not assume these additional conditions and retains its uncountable-minimum measurability limitation. The lemma in A3 is supporting source context, not a new premise added to the first clause.',
 '3.5':'D2/D3 give the online input procedure and strong FWER. The statement binds phi_I as the maximum of its decisions; D4’s empty-set convention supplies phi_empty=0. The conclusion uses D5/D6/D7 for online, level and predictable tests and D8 for the closure equality. No admissibility property is assumed merely because the theorem appears in the admissibility section.',
 '3.9':'D5/D6/D7 give the online level-alpha predictable family; D9 is the exact consonance condition (2). D8 defines the closed comparator and D2 its online nature. I_1, I_i and d^{phi,s} are fully bound in the theorem, with adaptive finite-subset evaluation. The conclusion is decision equality under the standing almost-sure convention, not an approximation or a new numerical error bound.',
 '4.2':'D10 provides adapted marginally valid p-values; D11 the threshold range, decision comparison and online measurability. D12 supplies the sub-adjustment family and equation (3), D13 its exact threshold-equality predictability, D6 the separately assumed alpha-level guarantee and D9 consonance. D8 is the closed comparator. Both the recursive I_i and the three procedures are defined in the theorem. Independence and F_{i-1}-measurable thresholds are not assumed, and the particular spending/graph/ADDIS constructions are not needed. Rejection-persistence predictability follows from D13 as explained in A6 but is not identical to that source definition.'
}
(ROOT/'ambient-conventions.json').write_text(json.dumps(dict(paper_id=PID,auxiliary_passages=aux,unresolved_source_conventions=issues,standard_ambient_resolution=resolution),indent=2,ensure_ascii=False)+'\n')
print('Saved',len(aux),'auxiliary passages and',len(issues),'source-convention notes.')
