"""Retain source conventions, unresolved appendix references and scope distinctions."""
import json
from save_inventory import ROOT,PID
def main():
    aux=[]
    def add(n,s,pages,note,deps=()):aux.append(dict(local_id='A'+str(n),statement_original=s,evidence=[dict(page=p,location='Original main-text context A'+str(n)) for p in pages],scope_note=note,depends_on=list(deps)))
    add(1,r'''Let $n\ge1$ be the sample size, $p\ge2$ be the dimension of the ambient space, $d\in\{1,\ldots,p\}$ the intrinsic dimension of the data, $\beta\ge1$ the regularity of the data, $\gamma\in[1,\beta+1]$ the regularity of the discriminator and $K>1$ a bounding constant for several parameters to come.''',[4],'Global parameters. Do not silently strengthen d>=1 or n>=1 to repair later displayed resolutions or logarithms. Model 3 separately requires d<p for nonemptiness.')
    add(2,r'''In this work, we suppose that there exists a map $g^\star\in\mathcal H_K^{\beta+1}(\mathbb T^d,\mathbb R^p)$ with $\mathbb T^d=\mathbb R^d/\mathbb Z^d$ the $d$-dimensional torus, such that $\mu=g^\star_{\#U}$, with $U\sim\mathcal U([0,1]^d)$ a uniform random variable on the cube. In particular, there exist $Y_1,\ldots,Y_n$ i.i.d. such that $Y_i\sim\mathcal U([0,1]^d)$ and $g^\star(Y_i)=X_i$. Note that the $Y_i$ are unknown, we only have access to the $X_i$.''',[2],'Torus, cube representatives and observed/latent data distinction. The true latent Y_i are unobserved; the GAN uses its separately sampled U_i.',['D1','D2'])
    add(3,r'''In the case where $\gamma=1$, the Wasserstein and the $d_{\mathcal H_1^1}$ distances are equivalent on compact domains. This can be shown using the dual formulation of the 1-Wasserstein distance $W_1$ (Villani, 2009): for two probability measures $\mu,\nu$ with support in the ball $B^p(0,K)$, we have
\[
d_{\mathcal H_1^1}(\mu,\nu)\le W_1(\mu,\nu)\le(2K+1)d_{\mathcal H_1^1}(\mu,\nu).
\]
Therefore, in the case where $\gamma=1$ and the discriminator class $\mathcal D$ is a subset of $\mathcal H_1^1$, the GAN estimator (1.3) is called the Wasserstein GAN estimator.''',[5],'Equivalence with constants on compact support, not equality of W1 and the bounded Hölder IPM. The inventoried conclusions are expressed in the latter.',['D1','D4','D5'])
    add(4,r'''We will denote $|A|$ the cardinality of a set $A$. For $a,b\in\mathbb R$, $a\wedge b$ and $a\vee b$ will denote the minimum and maximum value between $a$ and $b$ respectively. Throughout, letters $C$, $C_2$, $C_3$ ... denote constants that can vary from line to line and that only depend on $p,d,\beta$ and $K$.''',[5],'Constant dependence, extrema and covering-cardinality notation. In particular constants are not stated to depend on n; no unprinted n>=2 qualification is inserted.')
    add(5,r'''The projection on $T_x(\mathcal M)$ the tangent space at the point $x\in\mathcal M$, will be denoted by $P_{T_x(\mathcal M)}$. We will write $\int_{\mathcal M}f(x)d\lambda_{\mathcal M}(x)$ the integral of a function $f:\mathcal M\to\mathbb R$ with respect to the volume measure on $\mathcal M$, i.e. the $d$-dimensional Hausdorff measure.
Given a differentiable map $f:\mathbb R^k\to\mathbb R^l$ we denote by $\nabla f$ its differential and by $\|\nabla f(x)\|$ its operator norm at $x$. We denote by $(\nabla f(x))^\top$ its transpose matrix. If $k\le l$, $\lambda_{\min}((\nabla f(x))^\top\nabla f(x))$ corresponds to the smallest eigenvalue of the matrix $(\nabla f(x))^\top\nabla f(x)$.''',[4],'Ambient geometry and differential conventions for Definition 2.1; square-root minimum Gram eigenvalue is the minimum singular value, not determinant or density value.')
    add(6,r'''Consider two closed sets of functions: a set of generators $\mathcal G\subset\mathcal H_K^{\beta+1}(\mathbb T^d,\mathbb R^p)$ and a set of discriminators $\mathcal D\subset\mathcal H_1^\gamma(B^p(0,K),\mathbb R)$.''',[10],'Section 3.1.1 inherited closed-class assumption for Theorem 3.1 and approximation errors. The theorem binds arbitrary such classes; do not import the specific later network constructions.',['D1'])
    add(7,r'''Using the torus $\mathbb T^d$ as the latent space constrains the manifold $\mathcal M_{g^\star}$ to have empty boundary. In particular, Model 3 is non-empty only when $d<p$. This empty boundary assumption is common for manifold-based statistical models Divol (2022), Tang and Yang (2023).
The choice of a fixed latent space (here $\mathbb T^d$) allows to bypass any multi-patch support estimation step usually required in broader settings of densities bounded below on compact submanifolds.''',[7],'Topology and nonempty-model scope. The paper does not cover arbitrary compact manifolds of every topology through this one fixed latent torus.',['D10'])
    add(8,r'''For $\eta\in(0,\beta+1),\delta\in(0,1)$, and $C_\eta>0$ such that $\mathcal H_1^\eta(\mathbb T^d,\mathbb R^p)\subset\mathcal B_{\infty,\infty}^\eta(\mathbb T^d,\mathbb R^p,C_\eta)$, define
\[
\mathcal F_{\mathrm{per}}^{\eta,\delta}:=\{f\in\mathcal B_{\infty,\infty}^\eta(\mathbb T^d,\mathbb R^p,C_\eta K)\mid\langle f_i,\psi_{jlz}^{\mathrm{per}}\rangle_{L^2}=0,\forall j\ge\log_2(\delta^{-1})\}
\]
(3.8)
the set of functions in $\mathcal B_{\infty,\infty}^\eta$ that do not have frequencies higher than $\log_2(\delta^{-1})$. We will later build our class of generators $\mathcal G$ as an approximation by neural network of the class $\mathcal F_{\mathrm{per}}^{\eta,\delta}$.''',[14],'Ideal periodic low-frequency comparison class, retained for the definition context of the neural approximation. It is not the actual generator class. The source initially restricts eta<beta+1, then instantiates eta=beta+1.',['D1','D14','D15'])
    add(9,r'''We will use this basis to describe functions in $\mathcal H^{\beta+1}(\mathbb T^d,\mathbb R^p)$ as Lemma 3.3 still holds for the periodised Besov spaces $\mathcal B_{\infty,\infty}^{\beta+1}(\mathbb T^d,\mathbb R^p)$ (Section 4.3.4 in Giné and Nickl (2015)).''',[13],'Source explicitly invokes periodized/vector Besov conventions. No detailed coordinate norm or infinite-q modification is supplied in its displayed finite-q formula; these conventional extensions remain stated as such.',['D1','D14','D15'])
    add(10,r'''As in the full dimensional case, we have:
• When $\beta+1<d/2$, $\widehat g$ is computed using a discriminator class of regularity $\beta+1$ and attains minimax rates up to logarithmic factors for all $\gamma\in[1,\beta+1]$ at the same time.
• When $\beta+1\ge d/2$, $\widehat g$ is computed using a discriminator class of regularity $d/2$ and attains minimax rates up to logarithmic factors for all $\gamma\in[1,\infty)$ at the same time.''',[24],'Post-Theorem-5.8 explanatory prose, distinct from the narrower gamma range printed in the formal theorem. Preserve it as context without expanding the original theorem quotation.',['D5','D21'])
    add(11,r'''For $\eta\in(0,\beta+1)$ and $\delta\in(0,1)$, define
\[
\mathcal F^{\eta,\delta}=\{f\in\mathcal B_{\infty,\infty}^\eta(\mathbb R^p,\mathbb R,C_\eta K)\mid\langle f,\psi_{jlw}\rangle_{L^2}=0,\forall j\ge\log_2(\delta^{-1})\text{ and }\operatorname{supp}(f)\subset B^p(0,K)\}
\]
the set of functions in $\mathcal B_{\infty,\infty}^\eta$ that do not have high frequencies and have compact support in $B^p(0,K)$. As in Section 4.1, we are going to approximate the class $\mathcal F^{\eta,\delta}$ by neural networks.''',[17],'Ideal nonperiodic comparison class for (4.3), not a density constraint on its approximating network class and not the full-dimensional estimator from (2.2).',['D1','D14','D15'])
    add(12,r"""It is a neural network architecture (with either tanh or ReQU activation) composed of a core block $\widehat\psi^{\mathrm{per}}$ (trained to approximate the periodised wavelet $\psi^{\mathrm{per}}$) and a final layer that outputs a linear combination of the $O(n^d\log(n))$ blocks $\widehat\psi^{\mathrm{per}}(2^j\cdot-w_i)$. The core block $\widehat\psi^{\mathrm{per}}$ has width $O(n)$, depth $O(1)$, and the linear layer is of size $O(n^d\log(n))$. In particular, (4.1) is a subclass of the classical fully-connected architecture with width $O(n^{d+1}\log(n))$ and depth $O(1)$. We detail in Section A.2.2 how to implement the class (4.1) in practice.""",[15],'Main-text architecture description retained as printed. It supplies size/depth assertions but not the appendix-only core network implementation; no executable construction is inferred.',['D16','D17'])
    issues=[]
    def issue(k,t,ps):issues.append(dict(issue_id=k,description=t,evidence=[dict(page=p,location='Original source convention or scope') for p in ps]))
    issue('overview-density-scope','The overview of Theorem 5.1 imposes both regularity conditions on both maps. The formal Theorem 5.1 imposes manifold regularity on both but density regularity only on g-star. Preserve the two labeled statements separately.',[7,20])
    issue('overview-gamma-range','Theorem 5.8 overview asserts simultaneous gamma in [1,beta+1]; the formal theorem prints [1,tilde-beta+1]. Subsequent prose extends the claimed conclusion when beta+1>=d/2. All versions retain their original ranges without merging.',[7,24])
    issue('delta-endpoint-and-critical-indicator','Theorems 3.1 and 5.4 minimize over delta in [0,1] while using log(delta^{-1}) and possibly nonpositive powers. No endpoint convention is supplied. Theorem 5.4 also prints beta+1=d/2 in its indicator although its other terms use tilde-beta; do not silently replace it.',[11,23])
    issue('low-dimension-resolution','Global d includes 1. With tilde-beta+1=min(beta+1,d/2), the resolution denominator 2 tilde-beta+d equals zero at d=1, and [1,tilde-beta+1] is empty. No lower dimension restriction repairing these formulas is added by the census.',[4,22,24])
    issue('optimizer-and-cover-choice','The GAN, optimal discriminators and Besov approximation use exact argmin/argmax without specifying measurable selection. The covering definition uses argmin as a selected cover and does not state centers must lie in F. Preserve these conventions rather than invent a selection algorithm or altered covering definition.',[3,10,16,22])
    issue('wavelet-conventions','Page 12 initially calls psi the scaling function and phi the wavelet, while page 13 periodization and page 14 call phi the scaling function. The Euclidean l range ends at 2^p-1, but periodic/network sums end at 2^d or 2^p. Preserve the printed roles and ranges without correcting the basis.',[12,13,14,17])
    issue('network-indices-and-coarse-mode','Formula (3.11) sums over z but prints coefficient alpha(j,l,w)_i, with its bound using z. Network sums do not explicitly supply the separate constant/coarse mode used in the source bases. Logarithmic and spatial summation endpoints have no explicit rounding convention. These details remain unresolved rather than repaired.',[13,14,17])
    issue('appendix-network-construction','The hat-wavelet constructions refer to (A.4), (A.5) and (A.10) and Lemmas A.1-A.2. Preserve main-text precision, coefficient and architecture formulas, but do not claim that the appendix-only neural implementation has been extracted.',[14,15,17])
    issue('appendix-numerical-condition','The chi-numerical regularity condition in (5.1) is defined in Appendix E.1. Main text gives only a description and a claimed implication to manifold regularity. Its exact formula and admissible chi are unresolved within the permitted main-text scope.',[22])
    issue('holder-source-conventions','The Hölder display places max_i before the first derivative sum and leaves the second unparenthesized. Its definition starts at eta>0, while the pushforward display invokes H^0 test functions. The finite-q Besov norm is later used at infinity and on periodic/vector spaces without all modifications written out. Preserve these conventions explicitly.',[4,12,13])
    issue('gan-summation-scope','The GAN display places the summation directly before D(X_i)-D(g(U_i)) without enclosing parentheses. The accompanying empirical-loss explanation indicates paired sample terms; the original display is retained rather than silently inserting grouping into its quotation.',[3])
    issue('discriminator-latent-variable','Formula (4.2) prints D(g(U))-D(g-prime(u)) inside its expectation, mixing uppercase U and lowercase u. Preserve this original typo separately from its apparent intended meaning.',[16])
    issue('network-versus-holder','The generic GAN definition requires Holder-bounded classes; the instantiated classes are expressed by approximate wavelet coefficients, with no explicit Holder-ball intersection in (4.1),(4.3),(5.1). Do not invent this intersection or infer exact Holder membership solely from approximation/Besov membership.',[3,14,15,17,22])
    issue('endpoint-and-log-scope','The class construction initially states eta in (0,beta+1) and delta in (0,1), then uses eta=beta+1. Global n>=1 also permits log(n)=0 and delta=1 in displayed rates/classes. The census preserves these source endpoints and does not add an unprinted sufficiently-large-n clause.',[4,14,15,22,24])
    refs=[]
    for n in ['4.1','5.1','5.8']:refs.append(dict(from_claim_id=PID+'/T'+n+'-overview',to_claim_id=PID+'/T'+n,reference_kind='overview_relation',scope='Separately labeled overview occurrence of the later formal theorem. Preserve both statements, including differences in quantifiers, assumptions and specified classes.'))
    refs.extend([dict(from_claim_id=PID+'/T4.1',to_claim_id=PID+'/T3.1',reference_kind='proof_only',scope='Bias-variance theorem establishes the rate for the chosen classes, but its error bound is not part of the final theorem statement.'),dict(from_claim_id=PID+'/T5.8',to_claim_id=PID+'/T5.1',reference_kind='proof_only',scope='Interpolation proves the final rate; the theorem does not assume its closeness premise separately.'),dict(from_claim_id=PID+'/T5.8',to_claim_id=PID+'/T5.7',reference_kind='proof_only',scope='The capped-regularity rate is used in the proof, not as an added hypothesis.'),dict(from_claim_id=PID+'/T5.1',to_source_label='Compatible maps (Definition D.3) and Proposition D.5',reference_kind='proof_only',scope='Compatibility is a proof construction in the appendix. It is not needed to state the interpolation inequality and is not imported.'),dict(from_claim_id=PID+'/T4.1',to_source_label='(A.10), Lemmas A.1 and A.2',reference_kind='appendix_reference_unresolved',scope='The actual hat-wavelet is defined there; retain main-text network formulas and precision, without reading or filling in the appendix.'),dict(from_claim_id=PID+'/T5.4',to_source_label='Appendix E.1; (A.4), (A.5), (A.10)',reference_kind='appendix_reference_unresolved',scope='The shared generator and discriminator construction used by 5.4, 5.7 and 5.8 contains these unresolved exact numerical-condition/network references.')])
    bindings={
'T4.1-overview':'Model 1 is D6, the Hölder IPM D4 and GAN estimator D5. Theoretical G and D_gamma are existentially bound here; later explicit class definitions (4.1)-(4.2) are not inserted into this overview statement. Global constants and data conventions are A1-A4.',
'T5.8-overview':'Model 3 is D10, the IPM D4 and GAN D5. This statement existentially binds tractable G,D and asserts the gamma range [1,beta+1] simultaneously. It does not print the later capped range or the exact network class formulas. A7 retains topology/nonempty-model scope.',
'T5.1-overview':'D1,D2,D4 define the maps, pushforwards and distances. Both g and g-star satisfy D8 and D9 in this overview. Epsilon, gamma, constants and the closeness threshold are bound here. No GAN estimator or neural network enters this deterministic inequality.',
'T3.1':'D1,D2,D4,D5 resolve the regularity, distributions, loss and estimator; A6 retains inherited closed generator/discriminator classes. Delta_G and Delta_D are distinct errors D11-D12, and D13 the two class-covering numbers. Delta, n and constants are locally bound with A1-A4 conventions. No particular wavelet/network class is imposed.',
'T4.1':'D1,D2,D4,D5 define the generic objects, while D17-D18 specify exactly G and D in (4.1)-(4.2), including the wavelet precision, 1/n-cover and selected optimal discriminators. All network prerequisites follow those class definitions; the overview does not replace this full statement. No manifold assumption or proof regularization operator is added.',
'T5.1':'D1,D2,D4,D8,D9 resolve this deterministic interpolation inequality. Manifold regularity is imposed on both maps but density regularity only on g-star, unlike the overview. No compatible map from the appendix, GAN class or stochastic estimator is required to state the result.',
'T5.4':'D1,D2,D4,D5,D8,D9 resolve the target and estimator. G,D are D19,D21 with the cap and resolution (5.2), and unresolved numerical regularity in G. Delta_G is D11 at the current tilde-beta+1 regularity. D22 gives the supremum of fixed-generator composition covering numbers using D13. D23 gives the candidate-specific Besov discrepancy whose expectation is evaluated at ghat. The printed untilded critical indicator and delta=0 endpoint are retained.',
'T5.7':'D1,D2,D4,D5,D8,D9 define the target regularity, distributions, IPM and GAN; D19,D21 fix the numerical-condition generator and capped discriminator. The rate has tilde-beta in numerator and denominator and no printed max with n^{-1/2}; do not change it. Proof error terms and compatibility are not statement dependencies.',
'T5.8':'The target regularity and GAN are D1,D2,D4,D5,D8,D9, with actual G,D from D19,D21. The statement prints gamma in [1,tilde-beta+1] but beta in the final rate. Overview and subsequent extended-range explanation remain separate. The closeness hypothesis of the proof interpolation theorem is not an extra assumption here.'}
    out=dict(paper_id=PID,status='extracted',unranked_auxiliary_passages=aux,source_issues=issues,source_claim_references=refs,statement_local_bindings=bindings,ambient_prerequisites=['Finite-dimensional Euclidean spaces, compact tori and quotient representatives, uniform and pushforward probability measures, iid sampling, integration and expectations, smooth manifolds, tangent spaces and differentials.','Supremum norms, Holder and Besov regularity, wavelet coefficient pairing, exact function-space optimization and covering cardinalities follow the source conventions. Main-text appendix references remain unresolved rather than replaced by conjectured definitions.'],extraction_policy='Every labeled main-text theorem occurrence retained. Dependencies follow statements and specified class definitions, not proof lemmas. No appendix body, mathlib verdict or source repair is included.')
    (ROOT/'ambient-prerequisites.json').write_text(json.dumps(out,indent=2,ensure_ascii=False)+'\n')
if __name__=='__main__':main()
