"""Pin the cached preprint and validate its complete main-text Theorem inventory."""
import datetime
import hashlib
import json
from pathlib import Path
import re
import subprocess
import sys
import fitz
ROOT=Path(__file__).resolve().parents[1];PID=ROOT.name
REPO=ROOT.parents[3]
SKILL=Path('skills/statistical-paper-census/scripts')
SHA='86f5c1d84076a2f712856aca7b818569180f3701b882efa75eb4ca865a3eff5e'
STATEMENTS=[
('2.4',6,r'''Suppose that $K=K_0$ and $s=s_0$ in (2.1). We have
\[
\mathbb P(\widehat\theta^{\mathrm g}\neq\widehat\theta^{\mathrm{ol}})\leq6\exp\left[-\frac{3n}{40\sigma^2}\left\{c_{\min}-\frac{\sigma^2}{n}\big(27\log(pK_0)+12\big)\right\}\right],
\]
which implies that when $c_{\min}\geq\frac{\sigma^2}{n}\{d_1\log(pK_0)+12\}$ for some universal constant $d_1>27$, $\widehat\theta^{\mathrm g}$ consistently reconstructs $\widehat\theta^{\mathrm{ol}}$, i.e., as $n,p\to\infty$, $\mathcal L_g(\widehat\theta^{\mathrm g};\theta^*)\to0$.'''),
('2.5',7,r'''Define
\[
r(\mathbf X,\mathbf Z,K_0,s_0):=\frac{\max_{1\leq j\leq p}n^{-1}\|\mathbf X_j\|_2^2}{\min_{\theta^*\in\widetilde\Theta(K_0,s_0)}c_{\min}(\theta^*,\mathbf X,\mathbf Z)}.
\]
For any $K_0\geq1$, $p\geq s_0\geq K_0$ and $\ell>0$, we have
\[
\inf_{\widehat\theta}\sup_{\theta^*\in\Theta_c(K_0,s_0,\ell)}\mathcal L_g(\widehat\theta;\theta^*)\geq1-\frac{2nr(\mathbf X,\mathbf Z,K_0,s_0)\ell+\sigma^2\log2}{\sigma^2\log(\lfloor\frac{K_0+3}{4}\rfloor p)}.
\]
Consequently, if $\inf_{\widehat\theta}\sup_{\theta^*\in\Theta_c(K_0,s_0,\ell)}\mathcal L_g(\widehat\theta;\theta^*)\to0$, as $n,p\to\infty$, one must have that
\[
\ell\geq\frac{\sigma^2\{\log(\lfloor\frac{K_0+3}{4}\rfloor p)-\log2\}}{2nr(\mathbf X,\mathbf Z,K_0,s_0)}.
\]'''),
('3.2',11,r'''For the sequence $\{\theta_m\}_{m=1}^{\infty}$ generated by Algorithm 2, if $L>l$, then there exists $c\in\mathbb R$, such that for any $M\in\mathbb Z^+$ we have
\[
\min_{m=1,\ldots,M}\|\theta_{m+1}-\theta_m\|_2^2\leq\frac{2(g(\theta_1)-c)}{M(L-l)},
\]
where $g(\theta_m)\downarrow c$ as $m\to\infty$.''')]
def digest(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def write(name,data):(ROOT/name).write_text(json.dumps(data,indent=2,ensure_ascii=False)+'\n')
def main():
    PDF=Path(subprocess.check_output([sys.executable,str(REPO/'scripts/resolve_paper_pdf.py'),PID],text=True).strip())
    (ROOT/'evidence').mkdir(parents=True,exist_ok=True)
    assert digest(PDF)==SHA
    doc=fitz.open(PDF);assert len(doc)==31
    assert 'arXiv:2201.01036v1' in doc[0].get_text()
    toc=doc.get_toc();assert [x for x in toc if x[1]=='Appendices']==[[1,'Appendices',20]]
    heads=[]
    for i in range(19):
        text=doc[i].get_text();(ROOT/'evidence'/f'page-{i+1:02}.txt').write_text(text)
        for m in re.finditer(r'(?m)^THEOREM (\d+\.\d+)\.',text):heads.append(dict(number=m[1],page=i+1))
    assert heads==[dict(number=n,page=p) for n,p,_ in STATEMENTS]
    for n in [1,6,7,11,12,19]:doc[n-1].get_pixmap(matrix=fitz.Matrix(1.6,1.6)).save(ROOT/'evidence'/f'page-{n:02}.png')
    doc[19].get_pixmap(matrix=fitz.Matrix(1.6,1.6),clip=fitz.Rect(0,0,doc[19].rect.width,85)).save(ROOT/'evidence'/'appendix-heading-only.png')
    claims=[dict(claim_id=PID+'/T'+n,paper_id=PID,claim_kind='theorem',label='Theorem '+n,source_order=i,statement_original=body,evidence=[dict(page=p,location='Theorem '+n)]) for i,(n,p,body) in enumerate(STATEMENTS,1)]
    paper=dict(paper_id=PID,title=doc.metadata['title'],version='arXiv:2201.01036v1',source_url='https://arxiv.org/pdf/2201.01036v1',pdf_pages=31,pdf_sha256=SHA,main_text_last_pdf_page=19,
        main_text_boundary=dict(location='Section 5 Discussion and acknowledgments end on PDF page 19. A new page 20 begins with Appendices; the saved boundary image ends immediately after that heading. No appendix passage contributes to the census.',shared_page_with_appendix=False),
        intake_review=dict(status='complete',theorem_ids=[c['claim_id'] for c in claims],zero_theorems_confirmed=False))
    write('theorem-inventory.json',dict(schema_version='statistical-theorem-inventory-v1',scope=dict(theorem_scope='main_text_only'),papers=[paper],claims=claims))
    subprocess.run([sys.executable,str(SKILL/'validate_census.py'),str(ROOT/'theorem-inventory.json')],check=True)
    write('evidence/enumeration.json',dict(headings=heads,method='Use the PDF outline and a heading-only crop to establish the page-20 appendix boundary; enumerate printed THEOREM paragraphs only on pages 1-19 and inspect all three complete statements visually.',outline=toc,source_pdf_metadata=doc.metadata,appendix_start_pdf_page=20,appendix_content_used=False))
    manifest=REPO/'corpus/aos/2024/local-pdf-manifest.json';source=next(x for x in json.loads(manifest.read_text())['papers'] if x['paper_id']==PID);assert source['sha256']==SHA
    write('evidence/source-provenance.json',dict(source_manifest_path=str(manifest),source_record=source,pdf_path=str(PDF),verified_sha256=SHA,verified_pdf_pages=31,version_evidence='Page 1 stamp: arXiv:2201.01036v1 [stat.ML] 4 Jan 2022',version_limitation='This is the pinned 2022 preprint, not a claim of identity with the 2024 published text.'))
    write('inventory-review.json',dict(paper_id=PID,status='complete',source_checked=True,validator_status='passed',reviewed_at=datetime.datetime.now(datetime.timezone.utc).isoformat(),theorem_count=3,inventory_sha256=digest(ROOT/'theorem-inventory.json'),notes=[
        'The pinned source is arXiv v1 dated 4 January 2022. Its title and author list match this corpus article, but no equivalence with the later publication is assumed.',
        'Every main-text result labelled Theorem is retained: 2.4, 2.5 and 3.2. Definitions, propositions and corollaries remain outside the theorem inventory.',
        'Theorem 2.4 preserves K=K0, s=s0, the exact probability bound, c_min threshold, d1>27, and its asymptotic grouping-risk conclusion.',
        'Theorem 2.5 preserves its full definition of r(X,Z,K0,s0), the tilde-Theta denominator, the Theta_c minimax class, the floor in log(floor((K0+3)/4)*p), and the necessary-condition conclusion.',
        'Theorem 3.2 retains the Algorithm 2 sequence, L>l, existence of real c, the minimum over the first M squared step lengths, denominator M(L-l), and monotone convergence of g(theta_m) to c.',
        'The appendix boundary is between pages 19 and 20. Only main-text pages and a crop of the appendix heading are retained as source-reading evidence.']))
    write('checkpoint.json',dict(paper_id=PID,stage='interface_extraction',inventory_status='validated',source_pdf_path=str(PDF),source_pdf_sha256=SHA,
        remaining_work='Extract the regression model, grouping structure/distance/sensitivity, constrained L0-Fusion estimator, oracle estimator and grouping risk, lower-bound parameter subclasses, smooth objective assumptions, projection map and Algorithm 2. Preserve main-text definitions while leaving the appendix-only projection subroutine unexpanded.'))
    print('Saved and independently validated all three main-text Theorems of the pinned source.')
if __name__=='__main__':main()
