"""Preserve auxiliary source context and unresolved conventions without ranking them."""
import json
from save_inventory import PID,ROOT
A=[]
def passage(n,s,pages,note):
    A.append(dict(local_id=f'A{n}',statement_original=s,evidence=[dict(page=p,location=f'Auxiliary source passage A{n}') for p in pages],scope_note=note))
passage(1,r'''Let $\xrightarrow{d}$, $\xrightarrow{P}$ and $\Rightarrow$ denote convergence in distribution, convergence in probability and weak convergence, respectively.''',[4],'The source convergence notation. Big-O, little-o in probability and arrow-to-one for deterministic probabilities retain their ordinary sequence meanings; no new ranked interface is needed.')
passage(2,r'''$\omega_{Ti}=(\tau_i/T)\wedge(1-\tau_i/T)$''',[8],'The definition inside (3.8) is reused in Theorem 2. This isolated defining equation does not import the maximum-signal alternative condition from (3.8) into that theorem.')
passage(3,r'''where $\lambda_i$, $i=1,2,\cdots$, are the eigenvalues defined in (2.7) and $B_i(\cdot)$, $i=1,2,\cdots$, are independent standard Brownian bridges defined on $[0,1]$.''',[8],'Original Theorem 1 context binds the bridge sequence and refers to local eigenvalues. A standard bridge is an ambient probability-law prerequisite; the source does not construct it.')
passage(4,r'''where $z_\alpha$ is the upper $\alpha$-quantile of $\sup_{0\leq x\leq1}\sum_{i=1}^{\infty}\lambda_i B_i^2(x)$.''',[8],'Original Theorem 1 defines its critical value locally. The alpha domain and quantile selection convention are implicit.')
passage(5,r'''In Section 5 below, we also consider $\xi_{NT}=c_\xi\ln(NT)\ln\ln(NT)$ in the simulation study and compare the finite-sample numerical performance between these two choices of high-criticism thresholding parameters.''',[7,8],'The simulation alternative is preserved separately; it does not replace the max-based threshold fixed for the main asymptotic theory.')
passage(6,r'''From Assumption 1(i), the functional linear process $\epsilon_{it}$ defined in (2.3) with coefficient operators satisfying (2.4) is stationary and short-range dependent over time $t$, but its distribution is allowed to vary over $i$. This assumption is a natural extension of the assumptions in Bai (2010) and Horváth and Hušková (2012) for panel time series setting. Assumption 1(ii) shows that the functional time series may be weakly cross-sectionally correlated over $i$.''',[5],'This main-text discussion resolves the iid convention as temporal within each subject; it does not impose cross-subject independence before Theorem 4.')
passage(7,r'''Note that the common break setting is nested in the latent structure (4.6) with $b_1=\cdots=b_{K_0}=\tau_0$ and $\mathcal C(\tau_0)=\mathcal C_\bullet$. The latent structure (4.6) shows that $X_{it}$ have the common break point $b_k$ when $i\in\mathcal C(b_k)$.''',[10],'The printed equality of all b_k is retained, although the preceding partition uses distinct b_k; the consistent one-group interpretation requires K0=1.')
ISSUES=[]
def issue(key,text,pages):ISSUES.append(dict(issue_id=key,description=text,evidence=[dict(page=p,location='Original source notation or scope') for p in pages]))
issue('source-dates','The registered v1 PDF has an arXiv stamp of 14 April 2023 and a title-page version date of April 17, 2023. Both identify the inspected bytes; neither is silently corrected.',[1])
issue('hilbert-quotient','The source calls the set of square-integrable measurable functions a Hilbert space but does not state the almost-everywhere quotient or underlying measure-space assumptions needed for a definite L2 norm.',[4])
issue('domain-symbol','The bounded function domain is printed as blackboard C. It is a domain of integration in this real function-space model, not an asserted complex scalar field.',[4])
issue('lp-finiteness','The general Lp expression is defined for p>=1, but membership in L2 on a bounded domain alone does not ensure finite Lp norm for p>2. No such implication is inserted.',[4])
issue('operator-wording','The source says operation norm when defining the continuous-operator norm; the original wording is retained.',[4])
issue('iid-scope','Assumption 1(i) calls eta_it iid, while the adjacent discussion permits cross-subject correlation and varying distributions. It is interpreted temporally for each subject; Theorem 4 separately adds independence over i.',[5,12])
issue('eta-index','Assumption 1(ii) defines eta-tilde_Nt using eta_is on the right with no bound s. The source subscript mismatch is preserved rather than replacing s by t.',[5])
issue('random-element-operator-norm','The left side of (2.6) uses an O-subscript norm on a sum of random Hilbert-space elements, although O was defined for operators. The printed expression is retained; its intended norm remains unresolved.',[4,5])
issue('lag-zero','The coefficient condition sums j times max_i ||A_ij||_O starting at j=0. This gives no uniform bound on A_i0 by itself. No unprinted lag-zero bound is added.',[5])
issue('linear-process-convergence','Convergence mode of the infinite random-element series and coefficient-operator sum is not separately stated. The source assumes these objects exist under its standing setup; the census does not prove convergence.',[5])
issue('moment-uniformity','Exponential integrability is stated for any i with positive bounded c_eta. A uniform numerical upper bound on these expectations and on all asymptotic constants is not explicitly supplied.',[5])
issue('operator-moment-quantifier','The cross-sectional moment restriction quantifies over any sequence B_i and 0<=iota<=1. Dependence of the hidden big-O constant on that sequence is not spelled out.',[5])
issue('spectral-domain','The covariance-kernel limit is pointwise as written. Compactness, trace summability, eigenfunction normalization and a topology for operator convergence are not explicitly established by the eigenpair passage.',[5,6])
issue('bridge-series','Theorem 1 uses an infinite eigenvalue-weighted Brownian-bridge series and a supremum; convergence and measurability conditions are not stated separately. These are source well-definedness obligations, not extra extracted assumptions.',[8])
issue('quantile-convention','Theorem 1 names an upper alpha-quantile without specifying alpha in (0,1) or a generalized-inverse/tie convention. No unique critical value is invented.',[8])
issue('limit-regimes','Theorem 1 distinguishes joint N,T limits from its T-only PE statement. The kappa=0 growth case permits bounded N and is compatible with the latter, but not a joint N->infinity branch.',[8])
issue('threshold-domains','The prescribed log-log threshold may be nonpositive or undefined for small N vee T. The asymptotic setup implicitly uses sufficiently large indices; no finite-sample truncation is inserted.',[7])
issue('threshold-equality','The PE component uses strict >xi_NT, whereas the detected-subject set uses >=xi_NT and its complement <xi_NT. The difference at equality is preserved.',[7,9])
issue('centering-difference','The deterministic mean process (3.9) is centered with x, while the data CUSUMs use floor(Tx)/T. Its normalization is 1/sqrt(T), without an added sqrt(N). Both printed differences are preserved.',[6,7,8])
issue('break-domain','Break locations are treated as integer sample indices in estimator maximizations, but the initial model does not explicitly state their integer or interior domain.',[4,9])
issue('argmax-ties','The individual and pooled argmax formulas do not specify tie-breaking or measurable selection. The census preserves argmax rather than choosing a minimizer/maximizer convention.',[9,12])
issue('missed-subjects','The individual estimator is defined only on the detected set, while Theorem 2 takes a maximum over the true broken set. Extension on missed-subject events is not specified; the first conclusion establishes correct detection asymptotically.',[9,10])
issue('empty-true-set','The minimum over true broken subjects and the latent partition require nonempty groups in the estimation regime. Empty-set conventions are not stated in the theorem hypotheses.',[10,11])
issue('common-break-wording','The paragraph after (4.6) equates all b_k although the structure orders them strictly. The common-break case is consistent with K0=1; the original sentence is preserved separately.',[10])
issue('clustering-ties','Largest-gap selection does not specify how equal gaps are ordered. Coincident selected boundaries can create empty candidate clusters; no repair is invented.',[10,11])
issue('clustering-endpoint','The last cluster interval ends strictly before T, while individual argmax candidates include T. Subjects estimated at T are not assigned by the printed half-open intervals.',[9,11])
issue('candidate-feasibility','The criterion minimizes over 1<=K<=K-bar without spelling out K<=number of detected subjects, nonempty candidate clusters, or K-bar>=K0. These are unresolved domain requirements.',[11])
issue('average-break-integer','The within-cluster average of integer break estimates can be noninteger, yet is used directly as a summation limit and denominator in (4.8). No floor, rounding or interpolation convention is stated.',[11])
issue('residual-log-domain','The residual average divides by the detected-set size and takes log V(K). Empty detected sets, zero residuals and zero pre/post segment lengths have no explicit conventions.',[11])
issue('group-count-wording','The source says the true cluster number is determined by the formula for K-hat. The formula remains the estimator, and that wording is not silently rewritten in the original passage.',[11])
issue('proportional-integrality','Assumption 2(i) writes exact proportional break locations and group sizes. Integer subsequences, rounding, fixed K0, and uniformity of c_k,d_k across asymptotics are implicit.',[11])
issue('conditional-membership','Theorem 3 states joint membership equality conditional on K-hat=K0. The conditioning event and group labels must be retained; this is not replaced with unconditional pointwise accuracy.',[12])
issue('theorem4-construction','Theorem 4 expressly assumes only Assumption 2(i), but its estimated-group construction cites the tuning restriction in 2(iii). This is recorded as an indirect construction dependency; Assumption 2(ii) and the conclusion of Theorem 3 are not imported.',[11,12])
issue('theorem4-consistency-scope','Theorem 4 asserts exact recovery using estimated groups while omitting the full hypotheses of the preceding group-consistency theorem and an explicit N=O(T^kappa) condition. The source claim is preserved without claiming its proof is valid.',[12])
issue('theorem4-exceptional-groups','The pooled estimate is indexed by estimated groups, while the conclusion ranges over true K0 groups. Its definition on events with the wrong estimated group count is not specified.',[11,12])
issue('brownian-prerequisite','Independent standard Brownian bridges and ordinary probabilities/expectations are named source primitives. Their constructions and probability-space choices remain ambient.',[8])
RESOLUTION={
'shared':{'local_objects':'D1–D2 resolve the real function space, norms, operators and adjoints. D3 resolves observed functions, mean and jump functions, error and break notation. Ordinary finite indices, cardinality, indicator, expectation, probability, logarithms, order symbols, floor, max/min and positive constants are ambient.', 'source_scope':'Only main-text source passages are used. Appendix A and supplementary proofs are excluded. Source conditions and unresolved conventions are retained separately from original statements.'},
'1':{'local_objects':'Assumption 1 resolves to D4 and D5; eigenvalues to D6; H0 to D7; PE and combined tests to D12 and D13; alternative regions to D14.', 'ambient_or_bound':'Kappa and the polynomial growth restriction are local hypotheses. Brownian bridges are locally introduced in the theorem and preserved in A3; the critical value is locally defined in A4. A1 gives convergence notation.', 'branch_scope':'The null and final power statement have joint N,T limits; the PE-component statement has a T-only limit.'},
'2':{'local_objects':'D4/D5 give Assumption 1; D1 and D3 give jump norms and model locations; D11 gives xi_NT; D15/D16 give true and estimated subject partitions; D17 gives the individual break estimate.', 'ambient_or_bound':'A2 supplies only omega_Ti from (3.8); the maximum-signal alternative D14 is not a dependency. Conditions (4.2) and (4.4), c_delta, kappa and zeta are bound directly in the theorem.', 'branch_scope':'Detection uses (4.2); the stronger uniform localization assertion uses (4.4).'},
'3':{'local_objects':'D4/D5 resolve Assumption 1, D18 the latent structure, D22/D23/D24 the three parts of Assumption 2, and D21 the selected group count and estimated memberships.', 'ambient_or_bound':'Kappa and the growth condition are local. Conditional probability retains the event K-hat=K0 and the joint membership event over all k.', 'branch_scope':'Neither Theorem 2 nor its conclusions are additional assumptions.'},
'4':{'local_objects':'D4/D5 give Assumption 1 and the innovations; D18 and D22 give the latent structure and only the explicitly cited part 2(i); D15 gives the broken-subject count; D1/D3 resolve the jump norms; D25 gives the pooled estimator.', 'ambient_or_bound':'The two growth constraints, signal condition (4.14), cross-subject innovation independence and joint limit are local theorem hypotheses.', 'branch_scope':'D24 is reached only through the explicit restriction on the tuning parameter in the estimator construction D25->D21. D23 is not reached. No preceding theorem conclusion is imported.'}}
def main():
    data=dict(paper_id=PID,unranked_auxiliary_passages=A,source_issues=ISSUES,statement_resolution=RESOLUTION,
        unresolved_source_references=[dict(reference='Appendix A and supplementary technical proofs',status='excluded_by_scope',resolution='Not consulted for theorem-statement dependencies.'),dict(reference='Standard Brownian bridges and upper quantiles',status='ambient_named_prerequisites',resolution='The source names these objects without constructing their laws or selecting a quantile convention.')])
    (ROOT/'ambient-prerequisites.json').write_text(json.dumps(data,indent=2,ensure_ascii=False)+'\n')
    print(f'Saved {len(A)} auxiliary passages and {len(ISSUES)} source issues.')
if __name__=='__main__':main()
