"""Preserve source context, branch scopes, unresolved references and notation issues."""
import json
from save_inventory import ROOT,PID,STATEMENTS

def main():
    aux=[]
    def add(n,s,pages,note,deps=()):aux.append(dict(local_id='A'+str(n),statement_original=s,evidence=[dict(page=p,location='Original main-text auxiliary passage A'+str(n)) for p in pages],scope_note=note,depends_on=list(deps)))
    add(1,r'''For non-negative sequences $\{a_n\}$ and $\{b_n\}$, the following asymptotic notations will be used: let $a_n=O(b_n)$ denote $\limsup_{n\to\infty}a_n/b_n<\infty$, and $a_n=\widetilde O(b_n)$ (or $a_n\lesssim b_n$) denote $a_n=O(b_n\log^c n)$ for some $c>0$. Moreover, $a_n=\Omega(b_n)$ (resp. $a_n=\widetilde\Omega(b_n)$ or $a_n\gtrsim b_n$) means $b_n=O(a_n)$ (resp. $b_n\lesssim a_n$), and $a_n=\Theta(b_n)$ (resp. $a_n=\widetilde\Theta(b_n)$ or $a_n\asymp b_n$) means both $a_n=O(b_n)$ and $b_n=O(a_n)$ (resp. $a_n\lesssim b_n\lesssim a_n$).''',[5],'Original soft-order convention. Preserve ordinary O versus polylogarithmic lesssim/gtrsim; Theorems6/9/10 use ordinary O, whereas most introductory comparison bounds use soft order.')
    add(2,r'''First, in Section 3.1, we introduce an algorithm based on iterative direction search which finds a good initial action $a_0$ with $\langle\theta^\star,a_0\rangle\ge x_0$ for a given target level $x_0\in(0,1)$; this algorithm could even be made agnostic to the knowledge of $f$. Based on this action, we proceed with a different regression-based algorithm in Section 3.2 for the learning phase. For the ease of presentation, we assume that $f$ in monotone on $[-1,1]$ in the above sections, and leave the case where $f$ is even to Appendix C with slight algorithmic changes.''',[20],'Original x0 domain and main-text algorithm scope; preserve the printed in/monotone wording. The even-link algorithm changes are outside scope. This passage does not resolve the sign-identifiability discrepancy in the estimation target.',['D17','D21'])
    add(3,r'''We note that although Theorem 1 is stated in terms of the derivative $f'$, in general we do not need to assume that $f$ is differentiable, and our general result (cf. Theorem 9) is stated in terms of finite differences of $f$.''',[6],'Original explanation of derivative versus finite-difference bounds. Preserve Theorems1/3 as printed and record the derivative-domain issue; do not silently impose Assumption2 or differentiability throughout Assumption1.',['D8','D20'])
    add(4,r'''The same idea could also be applied to recursive certification steps, with two additional caveats. First, the CDF of $\langle\theta^\star,v\rangle$ with $v\sim\operatorname{Unif}(\mathbb S^{d-1}\cap V^\perp)$ involves an unknown magnitude $\|\operatorname{Proj}_{V^\perp}(\theta^\star)\|_2$; in the algorithm we estimate it and apply an induction in the analysis. Second, the optimal value of $\lambda$ in Algorithm 3 is unknown; we overcome it by searching over a geometric grid on $\lambda$. The detailed algorithms, as well as the proofs of Lemma 5 and Theorem 10, are postponed to the appendix.''',[25],'Main-text explanation of the existential unknown-link algorithm. Its detailed appendix code and proof are excluded. Theorem10 depends on the setting and finite-difference parameters of9, but does not require Algorithm1 or the infinite-armed-bandit lemma as additional hypotheses.',['D19','D20'])
    add(5,r'''The crucial observation here is that both
\[
p=F^{-1}(f(1/\sqrt d))=\mathbb P(\langle\theta^\star,v\rangle\le1/\sqrt d),
\]
\[
q=F^{-1}(f((1+\kappa_1)/\sqrt d))=\mathbb P(\langle\theta^\star,v\rangle\le(1+\kappa_1)/\sqrt d)
\]
are known thanks to the strict monotonicity of $f$, and Lemma 6 tells that $q-p=\Omega(1)$.''',[25],'Original explanatory CDF/quantile discrepancy: the displayed F inverse is equated to a probability that would normally use F. Preserve it as proof/motivation context, not a definition required by Theorem10, and do not inspect Lemma6 in the appendix.',['D2'])
    add(6,r'''Suppose the link function $f$ satisfies the monotonicity condition in Assumption 1, and $f'(x)/f'(y)\le C$ as long as $1/c\le x/y\le c$ for some constants $c,C>1$.''',[28],'Exact theorem-local derivative-ratio condition in13. Only the monotonicity part of Assumption1 is imported; normalized scale, Assumption2 and global Lipschitzness are not automatically added. Domains of ratios and zero denominators remain source issues.',['D25'])
    issues=[]
    def issue(i,pages,note):issues.append(dict(issue_id=i,evidence=[dict(page=p,location='Source scope or notation issue',**({'before_main_text_end':True} if p==29 else {})) for p in pages],note=note))
    issue('registered-source-and-boundary',[1,29],'The source is arXiv:2302.06025v3 marked10Jan2024, title-page date11Jan2024,55PDFpages. Its title spells Non-linear. Main text ends on29 before AppendixA at y654.115; evidence is clipped at y648. Exactly Theorems1–14 are retained, including weaker versions1/2. No appendix body is used.')
    issue('even-link-signed-identifiability',[3,6,7,8,20],'The default sphere parameter space contains theta and minus theta. For even f their reward distributions are identical under every adaptive policy, but Definition1 uses expected signed correlation. Thus a uniform signed-correlation guarantee above zero cannot distinguish the two orientations without extra information. No main-text sign-equivalence convention was found. Preserve both the even branch and original loss rather than replacing it with absolute correlation. The source’s appendix-only even-link modifications do not resolve this within the inspected scope.')
    issue('accuracy-domain-extension',[3,8],'Definition1 specifies epsilon∈(0,1/2], whereas Definition4 calls Tstar(f,d,1-epsilon) for epsilon∈(0,1/2]. Except at1/2, that argument exceeds the stated Definition1 domain. Preserve this apparent implicit extension. Expected-correlation complexity is distinct from a high-probability path or fixed-prior guarantee.')
    issue('derivative-form-versus-monotonicity',[6,8,22],'Theorems1/3 use f-prime although Assumption1 requires only monotonicity. The source explicitly says the general theorem need not assume differentiability and points to finite differences in9. Preserve both forms and flag the derivative interpretation. Flat intervals may make denominators vanish; do not silently assume strict increase or finite complexity.')
    issue('gaussian-noise-and-oracle-information',[3,10,21,24,26],'The introductory model states standard normal noise and history-adapted actions; the sampling algorithms use repeated Gaussian oracle queries, with fresh independent noise understood operationally. Theorem5 instead gives the learner only oracle outputs; online and offline models are alternatives. Theorem10 explicitly removes knowledge of f, overriding the default known-link convention without changing the ridge observation formula.')
    issue('oracle-quantifiers-and-domains',[9,10,11],'Theorem4 asserts existence of a bad action tie-breaking rule, not a bound for every tie rule. Theorem5 asserts existence of improper online or proper offline oracle choices that defeat every learner under the corresponding transcript model; it does not quantify over every possible oracle. The main text does not give a complete separate success-probability/minimax definition of Tstar_UCB or Tstar_RO. Improper outputs need not lie on the sphere, leaving f(inner product) outside[-1,1] potentially unresolved.')
    issue('learning-assumptions-and-constants',[11,12],'Assumption2 states differentiability and local derivative bounds near1 but does not explicitly quantify positive c_f,C_f or the range of gamma. Theorems use inverse c_f and positive local intervals, so those conventions are required for nonvacuous rates. Theorem6 adds Assumption1 only for regret; Theorem7 names Assumptions2/3, not1. Do not propagate the scale/even branches into all learning claims.')
    issue('algorithm-four-initialization-and-budget',[11,25,26],'Algorithm4 lists input correlation≥1-gamma, while Theorem6 supplies the stronger≥1-3gamma/4 used to keep exploration in the local interval. Preserve both. Its budget min(T,d sqrt(T)/c_f) need not be integral and the cyclic design need not complete full coordinate cycles; rounding and small-budget conventions are not specified. The theorem’s ordinary O and proof’s tilde-O notation remain distinct, with no proof-correctness certification.')
    issue('theorem-nine-parameters-and-ranges',[21,22],'Theorem9 declares epsilon_i for i≥0 but gives formulas only for1≤i≤m. Algorithm1 runs the firstd0 epochs even ifm<d0; candidate sampling may then have an empty orthogonal sphere in small dimensions. Finite differences may vanish for monotone f. Preserve the original pseudocode, positive-epsilon premise and parameter ranges instead of truncating loops, redefining positivity or inserting unstated large-d conditions.')
    issue('appendix-only-constant-and-algorithms',[20,21,22,25],'The function c(.) in Theorem9’s c0 is referenced to Lemma6, which is outside the main text in AppendixA. Its meaning remains unresolved. Algorithm1 uses c0 but its parameter definition can still be archived verbatim. Theorem10’s detailed unknown-link algorithm and the even-link modifications to Algorithm1 are also deferred to excluded appendices. These are recorded limitations, not permission to read appendix bodies.')
    issue('recursion-and-link-domain',[10,15,27],'Theorem8 defines epsilon_t for all t and everydelta∈(0,1), but the default f and g are defined only up to absolute argument1; epsilon1 or later values can exceed1. Theorem11 also maximizes over allK≥1, allowing sqrt(logK/d)>1. No main-text clipping or extension convention was identified. Preserve these formulas and the potentially vacuous1-t delta probability bound without silently extending f.')
    issue('bayes-minimax-and-action-space',[15,27,28],'Theorem8 is a uniform-sphere-prior path bound for any adaptive learner. Theorem11 is a nonadaptive Bayes expected-correlation bound. Theorem12 asserts existence of a hard finite action set at each subexponential K and uses a worst-parameter expectation target≥4/5. Theorem13 instead takes a worst parameter in the unit ball. These scopes and quantifier orders must not be merged into the default Definition1/2 sphere minimax problem.')
    issue('unit-ball-endpoints-and-scale',[28],'Theorem13 includes r=0 in a maximum containing f(r)/r^4 or f(r)/r^2 and integrals with zero endpoints. It also uses derivative ratios without stating all positivity/nonzero-domain conventions. Only the monotonicity part of Assumption1 is explicit; the normalized-scale item is not. The displayed bound involving Tf(r) is sensitive to additive shifts of f, unlike regret. Preserve this missing-normalization/endpoint issue rather than adding scale assumptions.')
    issue('soft-order-versus-ordinary-order',[4,5,11,22,24],'The source defines lesssim/gtrsim/asymp to ignore constant and polylogarithmic factors. Ordinary O is separate. Preserve the source-specific hidden-constant dependencies and distinguish log-squared cost in9 from log-cubed cost in10. Integrals in d(x^2) are not ordinary dx integrals; retain the measure notation.')
    issue('regret-notation-binding',[3,4,11],'The general regret display uses max over a-star but evaluates f_theta(a), leaving a free a; Definition2 correctly evaluates the comparator at a-star. Theorem6 describes an achieved algorithm regret using the minimax symbol Rstar. Preserve both original displays and explain the intended comparator/upper-bound roles without rewriting source text.')
    issue('unknown-link-cdf-explanation',[25],'The explanatory p,q formulas print F inverse applied to f-values while equating the results to CDF probabilities. This appears to be an inverse/CDF typo. The passage is archived as auxiliary source context, not a Theorem10 assumption or an invented prerequisite.')
    bindings={
'T1':dict(objects=['D1','D2','D6','D8','D17'],scope='Default ridge model, complete Assumption1, fixed kappa in(0,1/4), and a minimax burn-in upper bound with Algorithm1 as witness.',caveat='Main-text Algorithm1 handles monotone links. Even-link modifications are appendix-only, and signed identifiability remains unresolved.'),
'T2':dict(objects=['D1','D2','D6','D8'],scope='Complete Assumption1 plus even or odd f, conditional on burn-in cost at most T. No Algorithm1 premise.'),
'T3':dict(objects=['D1','D2','D7','D8'],branches={'upper':'Fixed kappa and epsilon at least c1/sqrt(d); derivative-form upper bound.','lower':'Additionally even or odd f, epsilon at least sqrt(c2 log(T)/d), and complexity at most T.'},scope='One original theorem with both branches. Derivational references do not add algorithm or theorem-conclusion premises.'),
'T4':dict(objects=['D1','D2','D8','D10','D13'],scope='Every Lipschitz link satisfying Assumption1; there exists a tie-breaking rule for Eluder-UCB giving the lower bound.',bound_inline='Tstar_UCB, epsilon, T, c and g; the source does not fully restate the algorithm-specific risk convention.'),
'T5':dict(objects=['D2','D8','D10','D14','D15','D16'],scope='There exist adverse improper online or proper offline oracles, each with its own error guarantee, such that every learner under that model has the stated lower bound.',alternatives='Online and offline guarantees are alternatives; the oracle transcript replaces raw reward observations.'),
'T6':dict(objects=['D1','D2','D5','D8','D9','D21'],branches={'estimation':'Assumption2 and supplied initial action with correlation at least1-3gamma/4; epsilon below gamma; expected signed correlation at least1-epsilon.','regret':'Additionally Assumption1; Algorithm4 achieves the ordinary-O regret bound.'},scope='A good initial action is supplied. No burn-in search algorithm or initial-search cost is assumed.'),
'T7':dict(objects=['D1','D2','D3','D5','D9','D10'],scope='Assumptions2/3; sphere minimax estimation and regret lower bounds. Constants may depend on gamma, c_f and L. No Assumption1 dependency.'),
'T8':dict(objects=['D1','D2','D8'],scope='Any learner under the uniform sphere prior; the full intersection over s at most t has probability at least1-t delta.',bound_inline='g, c, delta and recursive epsilon_t in(8). This Bayes path bound is distinct from Definition4’s expected minimax complexity.'),
'T9':dict(objects=['D1','D2','D17'],scope='Monotone f, target x0 in(0,1), delta/kappa ranges and all finite-difference constants bound inline. Algorithm1 has a high-probability output and query bound.',parameter_resolution='D20 is the exact parameter block used by Algorithm1 and Theorem10. Its c(.) reference remains unresolved; no performance-conclusion cycle is added.'),
'T10':dict(objects=['D1','D2','D20'],scope='Same setting and parameters as Theorem9, with continuous strictly increasing f. An algorithm exists without knowledge of f.',excluded='No Algorithm1 knowledge premise or certification procedure is imported. The detailed unknown-link algorithm is appendix-only.'),
'T11':dict(objects=['D1','D2','D8','D22'],scope='Uniform sphere prior and nonadaptive actions; no estimator attains expected signed correlation above1/2 below the bound.',bound_inline='K maximization, g, c, T and the prior; no minimax complexity symbol is invoked.'),
'T12':dict(objects=['D1','D2','D8','D23'],scope='For every K=exp(o(d)), there exists a finite unit-ball action set of cardinality K that defeats every learner at a worst-parameter expected correlation target of at least4/5.',bound_inline='K, A, c, c-prime, g and T. The lower-bound numerator is c, not cd.'),
'T13':dict(objects=['D1','D2','D24','D25'],scope='Parameter in the unit ball; only the monotonicity item of Assumption1 plus the inline derivative-ratio condition.',bound_inline='c,C above1; kappa in(0,1/4); radius maximum over[0,1] and both integrals. Endpoint and normalization issues are preserved.',excluded='No literal Definition2 sphere supremum, normalized-scale item or Assumptions2/3 is imported.'),
'T14':dict(objects=['D6'],scope='Linear link id(x)=x and dimension d; minimax burn-in lower bound d squared. No extra nonlinear regularity predicate or Brascamp–Lieb proof dependency.')}
    refs=[]
    def ref(ns,text,kind,resolution):
        for n in ns:refs.append(dict(claim_id=PID+'/T'+str(n),reference=text,reference_kind=kind,resolution=resolution))
    ref([1,2,3,4,5,8,11,12],'Assumption1','assumption_reference','D8 preserves both normalized scale and the original alternative monotonicity branches.')
    ref([6],'Assumptions2 and additionally1 for regret','assumption_reference','D9 applies to both branches; D8 applies only to the regret branch. No prior burn-in algorithm is required.')
    ref([7],'Assumptions2/3','assumption_reference','D9 local slope and D10 global Lipschitzness; Assumption1 is not named.')
    ref([13],'monotonicity condition inAssumption1','assumption_reference','OnlyD25; the derivative-ratio condition is bound inline and archived asA6.')
    ref([1,9],'Algorithm1','definition_reference','D17 preserves complete main-text pseudocode, including callsD18/D19 and parameterblockD20. Appendix even-link modifications are excluded.')
    ref([6],'Algorithm4','definition_reference','D21 preserves both budget branches and the cap-constrained least-squares estimator, with theorem-specific initialization recorded.')
    ref([10],'same setting ofTheorem9','assumption_reference','D20 preserves parameter/hypothesis formulas, with continuous strictly increasingf and no knowledgeoff explicit in10. This is not an Algorithm1 performance premise.')
    ref([9,10],'c(.) inLemma6','unresolved_appendix_reference','The reference occurs inTheorem9’s parameterblockD20 but Lemma6 is in an excluded appendix; no lemma body is imported.')
    ref([1,2,3],'later generalTheorems8/9 andCorollary3','proof_only','Weaker versions and consequences remain separate inventory records. Derivational relationships are not additional statement assumptions.')
    ref([8],'chi-square informativity lemmas','proof_only','Main-text information inequalities prove the path bound but are not needed to state its recursion or probability guarantee.')
    ref([10],'infinite-armed-bandit Lemma5 and appendix algorithm','proof_only','Main-text motivation isA4/A5; no infinite-armed-bandit or CDF correctness premise is imported intoTheorem10.')
    ref([14],'Brascamp–Lieb inequality on manifolds','proof_only','Mentioned beforeTheorem14 as a proof tool; no theorem dependency or appendix material is added.')
    data=dict(paper_id=PID,unranked_auxiliary_passages=aux,source_issues=issues,statement_local_bindings=bindings,source_claim_references=refs,ambient_conventions=['Euclidean vectors, unit ball/sphere, inner products, coordinate basis, orthogonal subspaces, uniform surface measure, Gaussian query laws, adapted policies, expectations and probability events retain their usual ambient meanings. All source variants explicitly override the default information or parameter/action domains where stated.','Expected signed correlation, worst-parameter risk, fixed-prior Bayes risk and pathwise high-probability success are distinct. Algorithm/oracle-specific sample-complexity criteria are retained with the source’s incomplete conventions, not silently replaced by a stronger target.','Function g is defined inline wherever used and need not become another ranked API. Positive integers/dimensions, finite horizons, ceilings, logarithms, derivatives, maxima/minima, asymptotic sequences and integrals in d(x²) remain ambient or theorem-local. No mathlib availability is assessed.','Source algorithms are preserved as numbered pseudocode with their original mathematical formulas. Reproducing the census does not execute these statistical algorithms, supply missing integer-rounding conventions or verify their proofs.','Appendix bodies, including Lemma6, even-link algorithm changes and the unknown-link algorithm details, are excluded. Unresolved source references and apparent source errors are retained explicitly.'])
    (ROOT/'ambient-prerequisites.json').write_text(json.dumps(data,indent=2,ensure_ascii=False)+'\n')
if __name__=='__main__':main()
