"""Save original local formulas and the scopes needed to read both Theorems."""
import json
from save_inventory import ROOT,PID
def main():
    aux=[]
    def add(n,s,pages,note,deps=()):
        aux.append(dict(local_id='A'+str(n),statement_original=s,evidence=[dict(page=p,location='Original main-text context A'+str(n)) for p in pages],scope_note=note,depends_on=list(deps)))
    add(1,r'''Note that if we define
\[
\Omega=\Sigma_Z+k_n\Sigma_Z^{1/2}\boldsymbol\alpha\boldsymbol\alpha^\top\Sigma_Z^{1/2},
\]
then $\sigma_n^2=\frac2{n^2}\operatorname{tr}(\Omega^2)$.''',[4,5],'Original unnamed population normalization matrix. Sigma_Z is read as Cov(z) from the immediately preceding variance formula A2 and the population-score derivation on pages 8-10; this alias is source-context interpretation, not a new quoted definition. Alpha and k_n are the theorem tuning inputs.',['D3'])
    add(2,r'''\[
\sigma_n^2=\frac2{n^2}\left[\operatorname{tr}(\operatorname{Cov}(\mathbf z)^2)+2k_n\boldsymbol\alpha^\top\operatorname{Cov}(\mathbf z)^2\boldsymbol\alpha+k_n^2(\boldsymbol\alpha^\top\operatorname{Cov}(\mathbf z)\boldsymbol\alpha)^2\right].
\]''',[4,10],'Population variance expression used next to the Omega definition. The exact n^2 denominator is retained; the earlier display on page 9 derives an asymptotic expansion.',['D3'])
    add(3,r'''where $\boldsymbol\mu_X=\mathbb E(\mathbf x)$ and $\mu_Y=\mathbb E(y)$.''',[3],'Population means used in the score definition, before substitution by the sample means.',['D1'])
    add(4,r'''Hence, for nonsingular $\Sigma_X$, testing the hypothesis in (2) is equivalent to a one-sample mean testing problem on the mean of the score function
\[
H_0:\boldsymbol\mu=\mathbf0\quad\text{versus}\quad H_1:\boldsymbol\mu\ne\mathbf0.
\]
(3)''',[3],'The equivalence explicitly requires nonsingular Sigma_X. The original theorem preambles are retained without silently adding that condition.',['D1','D2','D3'])
    add(5,r'''We next turn to the case where $\boldsymbol\mu_X$ and $\mu_Y$ are unknown. We calculate $\mathbf z$ using the sample means as $\mathbf z_i=(\mathbf x_i-\bar{\mathbf x})\{y_i-\bar y-(\mathbf x_i-\bar{\mathbf x})^\top\boldsymbol\beta_0\}$. For clarity, here we use $\mathbf z$ and $W_n$ to refer to $\mathbf z$ and $W_n$ calculated using the sample means and use $\mathbf z^0$ and $W_n^0$ to refer to $\mathbf z$ and $W_n$ calculated using the population means.''',[11],'Explicit main-text convention distinguishes the practical statistic from its population-centered comparison. This does not make the sample-centered scores iid.',['D3','D4','D5'])
    add(6,r'''Without loss of generality, we assume that $\boldsymbol\beta_0=\mathbf0$ in the null hypothesis, and we also assume that $\operatorname{Var}(y_i\mid\mathbf x_i)=\sigma^2=1$.''',[13],'Opening normalization in the proof of Theorem 2. Retained as context for the REM and risk; not inserted as an extra hypothesis into the original Theorem statement.',['D1','D2','D12'])
    add(7,r'''For the second part of Theorem 2, note that Theorem 1 already shows that the proposed test statistic $T_n$ has a standard normal distribution asymptotically under the null, thus we only need to show that the proposed test statistic goes to infinity in probability under the alternative to establish the asymptotic powerfulness of the proposed test in the second part of the theorem. Recall that our proposed test statistic $T_n$ is defined in (5).''',[17],'Original main-text explanation of powerfulness for the proposed rule. This is proof context, not a new theorem or an instruction to import Theorem 1 assumptions into Theorem 2(ii).',['D8','D13'])
    add(8,r'''\[
\boldsymbol\alpha^\top\widehat\Sigma_Z\boldsymbol\alpha=\frac1{n-1}\sum_{i=1}^n\|\boldsymbol\alpha^\top(\mathbf z_i-\bar{\mathbf z})\|_2^2.
\]''',[20],'Original practical formula confirms the usual centered sample-covariance projection and n-1 divisor. It is distinct from the squared-covariance estimator (6).',['D4','D6'])
    add(9,r'''where $\bar{\mathbf z}=n^{-1}\sum_{i=1}^n\mathbf z_i$.''',[20],'Sample score mean in the implementation formulas.',['D4'])
    add(10,r'''Note that we use $a=O(b)$ to mean that $a/b$ is bounded as $n$ and $p$ go to infinity, and the bound does not depend on $n$ or $p$.''',[17],'Original joint-dimension asymptotic convention. Theorems themselves print n tending to infinity; their statements are not rewritten.')
    issues=[]
    def issue(key,text,pages):issues.append(dict(issue_id=key,description=text,evidence=[dict(page=p,location='Original main-text definition or statement') for p in pages]))
    issue('score-reuse','The source deliberately reuses z_i for population-centered and sample-centered scores. The latter share estimated means. Separate original entries and the explicit page-11 convention retain this distinction.',[3,4,11])
    issue('population-covariance-alias','The Omega display uses Sigma_Z without a separate displayed Sigma_Z:=Cov(z) definition. The adjacent variance expression and population-score derivation identify the intended population covariance. This correspondence is recorded as interpretation supported by those passages.',[4,5,8,9,10])
    issue('covariance-square-hat','Equation (6) defines an estimate of Sigma_Z squared with off-diagonal matrix products. It is not (Sigma-hat_Z)^2. Both lines, the hat placement and matrix-square operations are retained.',[5,10])
    issue('normalization-domain','The source does not prescribe a fallback if the estimated trace in T_n is zero or negative, or separately state positivity of every population denominator. No truncation, absolute value or replacement estimator is added.',[5,6,8])
    issue('variance-equality','Pages 4 and 9 write Var(W_n)=sigma_n^2 with a 2/n^2 formula, while page 9 also gives a preceding asymptotic variance expansion. The census preserves the displayed normalization without silently changing n^2 to n(n-1).',[4,9,10])
    issue('identification-and-eigenvalues','The coefficient-to-score null equivalence on page 3 assumes nonsingular Sigma_X. Theorem preambles print an upper bound on its largest eigenvalue, without an explicit lower spectral bound. The equivalence condition is preserved separately rather than inserted into all results.',[3,6,8])
    issue('theorem-two-tuning-scope','Theorem 2(ii) prints the directional k_n quadratic-form condition, but not Theorem 1 k_n=o(sqrt(p)). Its proof refers to Theorem 1 for null calibration. Preserve this mismatch in stated scope; do not silently inherit the omitted condition or the local alternative.',[6,8,17])
    issue('rem-support-and-tail-conventions','REM specifies S=p^(1-s), uniform size-S support and nonzero iid sub-Gaussian coefficients with variance gamma^2. It gives no rounding rule for noninteger S and no explicit uniform sub-Gaussian proxy constant in the inspected definition. The variance is not relabeled as a proxy.',[8])
    issue('rem-null-normalization','REM is written for beta itself, while the general null is beta=beta_0. Theorem 2 proof sets beta_0=0 and sigma^2=1 without loss of generality. This normalization is retained as source context, without rewriting the REM as a quoted prior on beta-beta_0.',[3,8,13])
    issue('testing-criterion','Theorem 2 uses powerful/powerless without a separate formal definition of the asymptotic error limits in its preamble. The main text supplies the prior-average risk on page 13 and the proposed statistic divergence criterion on page 17. A fixed-size normal-quantile test is not silently replaced by a vanishing-size rule, and likelihood-ratio proof machinery is not treated as a required API.',[6,8,13,17])
    refs=[dict(from_claim_id=PID+'/T1',to_source_label='Assumptions A1 and A2; local alternative (7)',reference_kind='assumptions',scope='A1-A2 in both parts; the deterministic local alternative only in part (ii).'),dict(from_claim_id=PID+'/T2',to_source_label='Assumptions A1 and A2; REM',reference_kind='assumptions',scope='A1-A2 and REM with s in [0,1/2] in both parts. Additional Gaussian errors only in (i); tuning-vector restrictions only in (ii).'),dict(from_claim_id=PID+'/T2',to_claim_id=PID+'/T1',reference_kind='proof_only',scope='Page-17 proof invokes the null calibration result. No theorem-to-theorem statement edge and no automatic inheritance of Theorem 1 assumptions.')]
    bindings={'T1':'The iid linear model and coefficient null are D1-D2. The proposed statistic is D8, using sample scores D4, W_n D5 and estimators D6-D7. A1-A2 are D9-D10. Part (ii) uses local alternative D11; delta_z is defined in the statement. Omega is original local formula A1 with population score covariance D3. Alpha,k_n and spectral/rate conditions are locally stated; n,p are asymptotic model dimensions. Part (i) does not assume Ha.','T2':'The model D1, assumptions D9-D10 and REM D12 are common. Gamma_0 squared is defined inside the theorem. The lower bound (i) additionally assumes Gaussian errors and concerns all binary tests, with source average-risk convention D14. The upper bound (ii) concerns the proposed rejection rule D13, hence T_n and its sample estimators; it does not acquire the population local alternative D11 or Theorem 1 k_n=o(sqrt(p)) by implication. Sub-Gaussian coefficients are part of the REM, not an error-law assumption.'}
    out=dict(paper_id=PID,status='extracted',unranked_auxiliary_passages=aux,source_issues=issues,source_claim_references=refs,statement_local_bindings=bindings,ambient_prerequisites=['Real finite-dimensional vectors and covariance matrices, symmetric square roots, matrix multiplication/squares, traces/eigenvalues, expectations, variances, Euclidean norms, iid sampling, standard normal laws and convergence notation retain their source meanings. No mathlib availability claim is made.','Population means and covariance aliases are explicitly resolved in A1-A5; sample means and the sample covariance are distinct. The matrix square in (6) is not an entrywise square.','The nonnegative local-alternative constant and bounds on moments remain as the author states them. Coordinate factorization in A1 only ranges through total degree four; it is not full independence.','The source only names sub-Gaussian distributions in the REM; no invented moment-generating-function definition or uniform proxy constant is added.','Original asymptotic testing terminology is supported by the risk and divergence passages, with unresolved conventions noted separately. No likelihood-ratio or martingale proof objects are added as statement prerequisites.'])
    (ROOT/'ambient-prerequisites.json').write_text(json.dumps(out,indent=2,ensure_ascii=False)+'\n')
if __name__=='__main__':main()
