"""Build dependencies without importing unrelated approximation conclusions or proof devices."""
import copy,json,subprocess,sys
from pathlib import Path
from extract_interfaces import ROOT,PID,interfaces,members
SKILL=Path('skills/statistical-paper-census/scripts')
sys.path.insert(0,str(SKILL))
from canonical_dependencies import canonical_dependencies
from census_metrics import derive_metrics
from publication_contract import attach_inventory
DIRECT_NUMS={'2.1':[1,3,4],'2.2':[3,4,7,8,9,10,12],'2.3':[3,4,7,8,11,13],'2.4':[3,4,7,8,10,12],'2.5':[3,4,7,8,11,13],'3.1':[6,7,14],'3.2':[3,4,7,8,15],'4.1':[3,4,7,8,12,16,17,18,19]}
DIRECT={n:['D'+str(i) for i in v] for n,v in DIRECT_NUMS.items()}
EDGE_TEXT={
'D5':{'D1':'The single-innovation coupling difference is measured in the Lp random-variable norm.','D2':'The coupled variable replaces one iid input of the time-dependent causal map g_i.'},
'D6':{'D5':'Theta_(i,p) sums the uniform functional-dependence coefficients delta_p(k) from k=i onward.'},
'D7':{'D2':'Condition2.1 explicitly considers the causal representation (1.2).','D6':'The adjusted norm mu_(p,A) is the supremum of (i+1)^A times the dependence tail Theta_(i,p).'},
'D8':{'D1':'Condition2.2 concerns uniform tail expectations of the p-th absolute moments, with the same moment order p used in the theorem.'},
'D9':{'D1':'Condition2.3 uses the square of the unsubscripted L2 norm of growing block sums.'},
'D11':{'D1':'Condition2.4 lower-bounds the squared L2 norm of each block sum divided by its length.'},
'D19':{'D16':'The local linear estimator smooths the observed trend-plus-noise data X_i=mu(t_i)+Z_i.','D17':'Its weights use the deterministic quantile design t_i generated by density f.','D18':'Its design moments and weights use the smooth symmetric kernel K and support radius omega.'}}
def direct_reason(n,lid):
    label='Theorem '+n
    if lid=='D1':return 'Theorem2.1 directly assumes uniformly bounded Lp norms of the independent variables; no causal representation is required.'
    if lid=='D3':return label+(' applies the partial-sum convention to noise Z_i, using S_i=sum_j≤i Z_j in the Brownian increments. The general weighted-noise convention (4.1) and the explicit assumption reference for Z_i resolve the notation.' if n=='4.1' else ' approximates the original partial sums S_i=sum_j≤i X_j. Even a truncated-covariance approximation still targets S_i.')
    if lid=='D4':return label+' asserts existence of a Gaussian coupling under the Section2 convention: an equal-joint-law copy may be placed on an enriched probability space. It does not assert an independent Gaussian on the original space.'
    if lid=='D6':return 'Theorem3.1 explicitly assumes Condition2.1 for Theta_(i,p), the cumulative tail of the uniform functional-dependence coefficients.'
    if lid=='D7':return label+(' inherits Condition2.1 from Theorem2.3.' if n=='2.5' else ' inherits Condition2.1 from Theorem2.4, applied to noise Z_i.' if n=='4.1' else ' assumes Condition2.1 for the causal process, controlling mu_(p,A) through polynomial decay of the dependence tail.')+(' Its p>4 branch also uses the same norm at moment order4; no stronger A cutoff than A>1 is imposed.' if n=='3.1' else '')
    if lid=='D8':return label+(' inherits Condition2.2 through the assumptions of Theorem2.3.' if n=='2.5' else ' inherits the same truncated uniform integrability condition through Theorem2.4 for the noise Z_i.' if n=='4.1' else ' assumes the printed truncated uniform integrability Condition2.2 at moment order p. The supremum and every-fixed-a quantifiers remain as printed.')
    if lid=='D9':return 'Theorem2.2 assumes Condition2.3, divergence of the minimum second moment over every growing block length. This is weaker than a uniform linear-in-length bound.'
    if lid=='D10':return label+(' matches the Gaussian covariance to Cov(X_s^oplus,X_t^oplus) in its faster branch, while retaining the original partial sum S_i as the approximation target.' if n=='2.2' else ' uses E[(S_j^oplus)^2] as the Brownian time in its faster branch. S_j^oplus is the centered sum of variables clipped at n^(1/p), not the square of an uncentered clipped sum.')
    if lid=='D11':return label+(' explicitly assumes' if n=='2.3' else ' inherits from Theorem2.3')+' Condition2.4, the uniform positive lower bound on block second moment per unit length. It does not need a separate graph edge to Condition2.3 merely because that condition is weaker.'
    if lid=='D12':return label+(' defines' if n=='2.2' else ' references (2.7) for' if n=='2.4' else ' inherits from Theorem2.4 for the noise')+' the cutoff A>A0 with denominator4p and radical p²+10p+1. The definition reference does not import Theorem2.2’s nonsingularity premise.'
    if lid=='D13':return label+(' defines' if n=='2.3' else ' inherits from Theorem2.3')+' the cutoff A>A0-prime with denominator8p and radical p²+20p+4, distinct from A0.'
    if lid=='D14':return 'Theorem3.1 defines the banded upper-triangular quadratic form, its terminal-index blocks V_k and centered block partial sums R_k in (3.3). The two p ranges in its tail bound apply to these objects.'
    if lid=='D15':return 'Theorem3.2 uses zeta1=min{1,2−4/p}/(1+2A) from the preceding block-length discussion. Only this numeric definition enters its rate; no estimated BRV variance or conditional bootstrap law is a premise.'
    if lid=='D16':return 'Theorem4.1 concerns the trend mu estimated from X_i=mu(t_i)+Z_i and imposes approximation assumptions on the centered noise Z_i.'
    if lid=='D17':return 'Theorem4.1 requires C³ density f bounded above and away from zero, which generates the observation times t_i=F^-1(i/n). The printed endpoint convention is separately flagged.'
    if lid=='D18':return 'Theorem4.1 uses K in the local-linear weights and bias constant beta=one-half integral u²K(u)du, and uses its support radius omega in the interior supremum. The preceding assumption (4.9) supplies the kernel regularity.'
    if lid=='D19':return 'Theorem4.1 uses the local linear estimator mu-hat_h and its weights (4.7)–(4.8); the same weights applied to the specified Gaussian increments define Q_h. The design moments S_j(t) are distinct from noise partial sums S_i.'
    raise ValueError((n,lid))
def main():
    import extract_interfaces,save_ambient
    extract_interfaces.ROOT=ROOT;extract_interfaces.main();save_ambient.ROOT=ROOT;save_ambient.main()
    inv=json.loads((ROOT/'theorem-inventory.json').read_text());data=copy.deepcopy(inv)
    data['schema_version']='statistical-ranked-interfaces-v4'
    data['scope'].update(semantic_ranking_policy='All eight main-text Theorems retained, including the independent-variable result, truncation alternatives and both quadratic-form moment ranges.',build_order_policy='Preserve original versus truncated covariance, centered truncation, different A cutoffs and block-variance conditions, unconditional versus bootstrap rates, and noise versus observed data in smoothing.')
    data['interfaces']=copy.deepcopy(interfaces);claims={c['claim_id']:c for c in data['claims']}
    for lid,m in members.items():assert set(m['depends_on'])==set(EDGE_TEXT.get(lid,{})),lid
    for c in data['claims']:
        n=c['claim_id'].split('/T')[-1];c['depends_on']=DIRECT[n]
        for x in data['interfaces']:
            lid=x['members'][0]['local_id']
            if lid in DIRECT[n]:
                ev=copy.deepcopy(c['evidence'])+copy.deepcopy(members[lid]['evidence'])
                x['central_claim_uses'].append(dict(use_id=c['claim_id']+'-'+lid,paper_id=PID,claim_id=c['claim_id'],use_kind='statement_dependency',reason=direct_reason(n,lid),evidence=ev))
    edges=canonical_dependencies(data)
    for x in data['interfaces']:x['dependencies']=edges[x['interface_id']]
    derive_metrics(data)
    for x in data['interfaces']:
        for rel in x['related_theorems']:
            cid=rel['claim_id'];n=cid.split('/T')[-1];path=rel['via_local_ids']
            reason=' '.join([direct_reason(n,path[0])]+[EDGE_TEXT[a][b] for a,b in zip(path,path[1:])])
            ev=copy.deepcopy(claims[cid]['evidence'])
            for lid in path:ev.extend(e for e in members[lid]['evidence'] if e not in ev)
            x['theorem_explanations'][cid]=dict(paper_id=PID,via_local_ids=path,text=reason,evidence=ev)
        for m in x['members']:
            own=m['statement_original']+' '+m['local_label'];linked=own+' '+' '.join(claims[r['claim_id']]['statement_original'] for r in x['related_theorems'])
            selectors=m['highlight_symbols']+m['highlight_phrases']
            assert any(s in own for s in selectors) and all(s in linked for s in selectors),(m['local_id'],[s for s in selectors if s not in linked])
    attach_inventory(data,ROOT/'theorem-inventory.json',ROOT/'ranked-interfaces.json')
    (ROOT/'unfinalized-census.json').write_text(json.dumps(data,indent=2,ensure_ascii=False)+'\n')
    subprocess.run([sys.executable,str(SKILL/'finalize_census.py'),str(ROOT/'unfinalized-census.json'),str(ROOT/'ranked-interfaces.json'),'--inventory',str(ROOT/'theorem-inventory.json')],check=True)
    subprocess.run([sys.executable,str(SKILL/'validate_census.py'),str(ROOT/'ranked-interfaces.json')],check=True)
    print('Census structurally validated; independent source review remains pending.')
if __name__=='__main__':main()
