"""Preserve approximation conventions and source limitations outside original theorem quotations."""
import json
from save_inventory import ROOT,PID

def main():
    aux=[]
    def add(n,s,pages,note,deps=()):aux.append(dict(local_id='A'+str(n),statement_original=s,evidence=[dict(page=p,location='Original main-text context A'+str(n)) for p in pages],scope_note=note,depends_on=list(deps)))
    add(1,r'''We will assume $\mathbb E(X_i)=0$.''',[5],'Standing mean-zero convention for the causal process in Section2.2. In T4.1 the approximation applies to noise Zi rather than observations Xi.',['D2'])
    add(2,r'''Similarly for a sequence of random variables $(X_n)_{n\ge1}$ and a positive sequence $y_n$, if $X_n/y_n\to0$ in probability, we write $X_n=o_{\mathbb P}(y_n)$, and if $X_n/y_n$ is stochastically bounded, we write $X_n=O_{\mathbb P}(y_n)$.''',[4],'All theorem approximation errors use convergence in probability, not almost-sure convergence from the introductory classical KMT discussion.')
    add(3,r'''Let
\[
W^\diamond(t)=\sum_{i=1}^nw_i(t)\big(\mathbb B(\mathbb E(S_i^2))-\mathbb B(\mathbb E(S_{i-1}^2))\big)
\]
(4.1)
be the Gaussian process that we want to use to approximate $W(t)$, where $S_i=\sum_{j=1}^ie_j$.''',[14],'The preceding W(t)=sum e_i w_i(t) concerns mean-zero errors e_i. This explicitly resolves S_i as the noise sum when T4.1 sets e_i=Z_i.',['D3'])
    add(4,r'''Usually the block length $m$ is taken so as $m\to\infty$ with $m/n\to0$. Define for $1\le a,k,j\le\lceil n/m\rceil$,
\[
B_a:=\sum_{i=(a-1)m+1}^{am\wedge n}X_i;\quad T_k=\sum_{a=1}^kB_a^2+2\sum_{a=1}^{k-1}B_aB_{a+1};\quad R_j:=\mathbb I_{\{j/m\notin\mathbb N\}}\sum_{i=\lfloor j/m\rfloor m+1}^jX_i.
\]
(3.1)
Note that $S_j=\sum_{a=1}^kB_a+R_j$, where $k=\lfloor j/m\rfloor$. We shall estimate $\mathbb E(S_j^2)$ by the following ‘Block-based Running Variance’ (BRV) estimator $\mathcal T_j$ where
\[
\mathcal T_j:=T_{\lfloor j/m\rfloor}+R_j^2+2B_{\lfloor j/m\rfloor}R_j\quad\text{for all }1\le j\le n
\]
(3.2)
simultaneously.''',[11],'Original BRV construction is contextual to T3.1–T3.2, not a premise of either theorem. Preserve its printed initial j range, though the later formula uses every j≤n, and flag the unprovided B0 convention.',['D3'])
    add(5,r'''Since $\mathcal T_j$’s may be negative, so instead of Brownian motion we use two-sided Brownian motion. A two-sided Brownian motion is defined as $\mathbb W(t)=\mathbb B_1(t)\mathbb1_{t\ge0}+\mathbb B_2(-t)\mathbb1_{t<0}$, where $\mathbb B_1$ and $\mathbb B_2$ are two independent standard Brownian motions starting at $0$.''',[11],'Empirical BRV evaluation can require negative times. Theorem3.2 itself uses ordinary Brownian motion at nonnegative true second moments.')
    add(6,r'''where $\mathbb P^*$ refers to the conditional distribution after observing $X_1,\ldots,X_n$, and $\mathbb B_1(\cdot)$ is the same Brownian motion defining the positive half-line of $\mathbb W(\cdot)$.''',[13],'This defines the bootstrap order symbol following (3.10); T3.2 instead states an unconditional little-o_P result.')
    add(7,r'''We emphasize that to avoid notational cumbersomeness, in (3.4) we have used same notation $C_p$ to denote multiple constants, each depending solely on $p$.''',[12],'Different occurrences of Cp in T3.1 need not be the same numeric constant.',['D14'])
    add(8,r'''The classical uniform integrability condition for $(|X_t|^p)_t$ is $\sup_i\mathbb E(|X_i|^p\mathbb I_{\{|X_i|^p\ge k\}})\to0$ as $k\to\infty$. Note that Condition 2.2 is weaker.''',[6],'Preserve the author’s comparison. With a fixed sequence and an unrestricted supremum over i, the printed conditions are equivalent by reparameterizing the truncation level. No triangular-array index restriction is silently inserted.',['D8'])
    add(9,r'''In fact, our proof works for $A>1/2-1/q$ and matches their non-uniform bound for the corresponding case. A similar argument can be followed to yield a bound for a process satisfying $\mu_{p,A}<\infty$ for some general $A$.''',[12],'Remark3.2 describes a proof extension and uses an undefined q in this main-text sentence. T3.1 retains Condition2.1 with A>1; no unstated weaker theorem is substituted.',['D7'])
    add(10,r'''Since $A>1$, $\zeta_2<\zeta_1$, and therefore''',[13],'Source comparison has its inequality reversed for the printed zeta1=min{1,2−4/p}/(1+2A) and zeta2=min{1,2−4/p}/3. Keep the actual zeta1 formula in T3.2; do not change it to fit the prose.',['D15'])
    add(11,r'''By the argument in Theorem 3.1 in [34], $\mathbb E[\widehat\mu_{h_n}(t)]-\mu(t)=h_n^2\mu''(t)\beta+O(h_n^3+n^{-1}h_n^{-1})$.''',[15],'Proof-local bias expansion helps check scale placement; it is not an extra theorem or a replacement for the full statement.',['D19'])
    add(12,r'''Using (4.10) to construct simultaneous confidence band requires estimation of $\mu''(t)$. Following [48], we use the jackknife-based bias corrected estimator
\[
\widetilde\mu_{h_n}(t)=2\widehat\mu_{h_n}(t)-\widehat\mu_{h_n\sqrt2}(t).
\]
(4.11)''',[15],'Subsequent bias correction is separate from the uncorrected local linear estimator in T4.1. Bootstrap bands and wavelet/CUSUM applications in prose are not additional Theorem environments.',['D19'])
    issues=[]
    def issue(i,pages,note):issues.append(dict(issue_id=i,evidence=[dict(page=p,location='Source scope or notation issue') for p in pages],note=note))
    issue('coupling-space',[2,4,5],'The Gaussian processes coexist with an equal-joint-law copy on a possibly enriched probability space. The original variable notation suppresses this convention. The theorem rates are o_P, not the introductory classical almost-sure KMT rate.')
    issue('truncated-target-and-centering',[6,7,8],'Clipping at n^(1/p) defines X^oplus; S^oplus additionally subtracts the clipped means. T2.2’s second branch matches Cov(X^oplus) yet compares to original S. T2.4’s faster Brownian time is the second moment of the centered clipped sum, while its slower branch uses the original sum.')
    issue('distinct-nonsingularity-and-decay',[6,7,8,13],'Condition2.3 diverges over blocks with m_n+1 terms; Condition2.4 bounds length-l second moments below by c l. A0 and A0-prime are different formulas. T2.4 and T3.2 require neither nonsingularity condition; T3.1 only uses A>1. No implication is turned into an additional dependency.')
    issue('uniform-integrability-comparison',[6],'The paper calls Condition2.2 weaker than classical uniform integrability. As printed for a fixed sequence with sup over all i, taking a=1 and reparameterizing the truncation threshold yields the same criterion. Any triangular-array interpretation would need explicit index conventions absent here.')
    issue('variance-time-not-necessarily-monotone',[3,7,8],'For a dependent process the curve j↦E(S_j²) can decrease. Evaluating Brownian motion at these times is meaningful, but successive differences indexed by observations need not be independent increments. Preserve the actual time-change formulas without inferring monotonicity from the section title.')
    issue('quadratic-bandwidth-and-constants',[11,12],'T3.1 prints D_n≤n; its sums and division implicitly require a positive integer bandwidth. Different Cp occurrences may be different constants depending only on p. At p=4 use the first polynomial branch; the second branch and mu_(4,A) require p>4.')
    issue('block-notation-overload',[11],'R_j in (3.1) is a leftover linear block sum, whereas R_k in (3.3) is a centered quadratic-block partial sum. The BRV formulas initially restrict j≤ceil(n/m) then use all j≤n, and use B0 when j<m without an explicit convention. These contextual formulas are not assumed in T3.1–T3.2.')
    issue('bootstrap-versus-theoretical-rate',[12,13],'Equation(3.10) is O_(P*) conditional on observations and uses estimated possibly negative BRV times. T3.2 is an unconditional o_P existence result at true second moments. Import only the numerical zeta1 definition, not the BRV estimator or a bootstrap-conditioning assumption.')
    issue('reversed-block-exponent-comparison',[13],'With A>1 and p>2, the printed zeta1 denominator 1+2A exceeds3, hence zeta1<zeta2. The subsequent prose prints zeta2<zeta1. The census keeps the theorem’s actual exponent and flags this reversed comparison.')
    issue('quantile-grid-endpoint',[15],'The source first states t_n<t_(n+1)=1 but then sets t_i=F^-1(i/n), giving t_n=1 for its positive density. Preserve both statements; do not silently replace i/n by i/(n+1). The theorem supremum itself is on the interior interval.')
    issue('kernel-normalization-and-denominator',[15],'The source calls K a smooth symmetric kernel with bounded support and an integrated modulus condition. It does not separately state integral K=1 or nondegeneracy of S2 S0−S1². The displayed bias beta=one-half integral u²K(u)du uses the usual normalized-kernel interpretation; do not insert unquoted assumptions into the original statement.')
    issue('noise-and-sum-notation',[14,15],'In the trend model Xi=mu(t_i)+Zi, the approximation assumptions apply to Zi and Si in the Gaussian increments is its noise partial sum, as resolved by (4.1). S_j(t) instead denotes deterministic kernel-weighted design moments. Q_n in T3.1 and Q_h(t) in T4.1 are unrelated reused symbols.')
    refs=[dict(from_claim_id=PID+'/T2.4',to_source_label='Theorem 2.2, equation (2.7)',reference_kind='definition_reference',scope='Import A0 only; no block-nonsingularity Condition2.3.'),dict(from_claim_id=PID+'/T2.5',to_source_label='Theorem 2.3',reference_kind='assumption_reference',scope='Conditions2.1,2.2,2.4 and A>A0-prime; no Gaussian covariance-matching conclusion is a premise.'),dict(from_claim_id=PID+'/T4.1',to_source_label='Theorem 2.4',reference_kind='assumption_reference',scope='Conditions2.1,2.2 and A>A0 for Zi; the untruncated conclusion is used to construct the Gaussian smoother. Truncation is not an additional assumption.'),dict(from_claim_id=PID+'/T3.2',to_source_label='Section 3.2 before (3.10)',reference_kind='definition_reference',scope='Numerical zeta1 formula only, not an empirical BRV premise.'),dict(from_claim_id=PID+'/T3.1',to_source_label='Appendix Section 10.1',reference_kind='proof_only',scope='Deferred proof; appendix body excluded.'),dict(from_claim_id=PID+'/T4.1',to_source_label='Equation (4.3), Theorem 3.1 of [34], Lemma 11.1',reference_kind='proof_only',scope='Summation-by-parts and bias arguments prove the result; no proof-only weighted-variation or appendix lemma becomes a statement dependency.')]
    bindings={
'T2.1':'Independent mean-zero variables, bounded p norms, p>2 and some gamma≥2 with the complete minimum-moment condition (2.1). Uses ordinary S_i and Brownian time E(S_i²). No causal representation, dependence norm, Condition2.2 or block variance assumption is imported. Coupling-space convention applies.',
'T2.2':'Mean-zero causal process, Conditions2.1–2.3 and A>A0. First Gaussian covariance matches original Xi with n^(1/p)sqrt(log n) rate. Second covariance matches clipped Xi^oplus while the approximation still targets original Si at n^(1/p). Gaussian means are not separately specified in the printed theorem; no independent-increment conclusion is added.',
'T2.3':'Conditions2.1,2.2,2.4 and the distinct A0-prime cutoff; original covariance matching and n^(1/p) rate. Does not explicitly assume Condition2.3 or use clipping.',
'T2.4':'Conditions2.1,2.2 and A>A0 only; no nonsingularity. One Brownian approximation uses E[(S_j^oplus)²] with centered clipping and the faster rate; the original E(S_j²) time has an additional sqrt(log n).',
'T2.5':'Inherit T2.3 assumptions: decay with A>A0-prime, truncated UI, and linear block variance lower bound. The conclusion is Brownian evaluation at original partial-sum second moments; do not import the Gaussian-process covariance-matching conclusion as a premise.',
'T3.1':'Mean-zero causal process under Condition2.1, p>2 and A>1. Banded bounded coefficients define Q_n,V_k and centered R_k. For 2<p≤4 retain the x^(-p/2)n D_n^(p/4) mu_(p,A)^p term; for p>4 retain D_n^(p/2−1) and the exponential term with mu_(4,A)^4. No UI, nondegeneracy, Gaussian coupling or estimated-variance assumption.',
'T3.2':'Mean-zero causal process, Condition2.1 with A>1, and Condition2.2. Zeta1=min{1,2−4/p}/(1+2A) is taken from preceding text. Brownian coupling has an unconditional little-o_P rate n^((1−A zeta1)/2)sqrt(log n). No empirical BRV input or conditional law is required.',
'T4.1':'Trend model on the quantile design, C³ mu and f with density bounds C1,C2, and preceding kernel assumption (4.9). T2.4 assumptions apply to centered noise Zi. Si=sum_{j≤i}Zj in Yi=B(E(Si²))−B(E(S_(i−1)²)), S0=0; use the same local-linear weights to form Q_h. S_j(t) denotes distinct design moments. Interior supremum, bias constant, h→0, h^4=O(n^(1/p−1)), nh→infinity and the full error scale remain intact.'}
    out=dict(paper_id=PID,status='extracted',unranked_auxiliary_passages=aux,source_issues=issues,source_claim_references=refs,statement_local_bindings=bindings,ambient_prerequisites=['Real-valued random variables, joint distributions, iid innovations, measurable causal maps, expectation, covariance, Brownian motion, Gaussian processes, enriched-space coupling, Lp norms and convergence in probability.','For dependent-process theorems the Section2.2 mean-zero convention applies. T2.1 independently states its own mean-zero/independence/moment conditions; it is a locally labeled theorem even though attributed to earlier work.','Covariance-matching processes and Brownian evaluations are distinct constructions. True second moments are nonnegative but not necessarily monotone in the observation index.','Kernel functions, C³ smoothness, deterministic quantile grids, matrix-free local-linear weights, interior intervals and bandwidth sequences. Standard Brownian B(0)=0 and empty partial sum S0=0 resolve T4.1’s first increment.'],extraction_policy='All eight complete main-text Theorems. Preserve every original/truncated and moment-range branch, original definitions, and source limitations. Appendix bodies and proof certification excluded.')
    (ROOT/'ambient-prerequisites.json').write_text(json.dumps(out,indent=2,ensure_ascii=False)+'\n')
if __name__=='__main__':main()
