"""Archive source matrix conventions, degeneracies and proof-only relationships."""
import json
from save_inventory import ROOT,PID
def main():
    aux=[]
    def add(n,s,pages,note,deps=()):
        aux.append(dict(local_id='A'+str(n),statement_original=s,evidence=[dict(page=p,location='Original main-text context A'+str(n)) for p in pages],scope_note=note,depends_on=list(deps)))
    add(1,r'''The observations can be seen as entries of a matrix $X\in\mathbb C^{n\times n}$ with $X_{jj}:=0$ and $X_{kj}:=\overline{X_{jk}}$ for any $1\leq j<k\leq n$. Define $A_{jj}:=0$ and $A_{kj}:=A_{jk}$ for all $1\leq j<k\leq n$. Then the matrix $A\in\{0,1\}^{n\times n}$ can be interpreted as the adjacency matrix of an Erdős-Rényi random graph with edge probability $p$. Define $W\in\mathbb C^{n\times n}$ such that $W_{jj}:=0$ and $W_{kj}:=\overline{W_{jk}}$ for all $1\leq j<k\leq n$. Then all the matrices $A,W,X$ are Hermitian and $X$ can be written equivalently as
\[
X=A\circ(z^*z^{*H}+\sigma W)=A\circ(z^*z^{*H})+\sigma A\circ W.
\]
(2)''',[1,2],'Complete Hermitian data construction. Mask and noise are independent only on the upper triangle; diagonal entries are zero.',['D1','D2'])
    add(2,r'''The data matrix $\mathcal X\in\mathbb R^{nd\times nd}$ can be written equivalently in a way that is analogous to (2). Define $A_{jj}:=0$ and $A_{kj}:=A_{jk}$ for all $1\leq j<k\leq n$. Define $\mathcal W\in\mathbb C^{nd\times nd}$ such that $\mathcal W_{jj}:=0_{d\times d}$ and $\mathcal W_{kj}:=\mathcal W_{jk}^T$ for all $1\leq j<k\leq n$. Then we have the expression:
\[
\mathcal X=(A\otimes J_d)\circ(Z^*Z^{*T}+\sigma\mathcal W)=(A\otimes J_d)\circ Z^*Z^{*T}+\sigma(A\otimes J_d)\circ\mathcal W.
\]
(21)''',[10],'Original block-mask formula. The source writes a complex ambient space for W here despite its real matrix-normal blocks. Preserve that notation; its completion uses transpose.',['D5','D6'])
    add(3,r'''A random matrix $X$ follows a matrix Gaussian distribution $\mathcal{MN}(M,\Sigma,\Omega)$ if its density function is proportional to $\exp\left(-\frac12\operatorname{Tr}\left(\Omega^{-1}(X-M)^T\Sigma^{-1}(X-M)\right)\right)$.''',[10],'Footnote 1 defining the matrix-normal convention. At zero mean and identity row/column covariances this is the standard real matrix Gaussian law; no extra scalar factor is inserted.')
    add(4,r'''We note that in this paper, $p$ and $\sigma^2$ are not constants but functions of $n$. This dependence can be more explicitly represented as $p_n$ and $\sigma_n^2$. However, for simplicity of notation and readability, we choose to denote these as $p$ and $\sigma^2$ throughout the paper.''',[2],'Sequence-level convention for Theorems 1 and 2. The phase and orthogonal models use the same asymptotic regime, with d bounded in the latter.')
    add(5,r'''For two positive sequences $\{a_n\}$ and $\{b_n\}$, $a_n\lesssim b_n$ and $a_n=O(b_n)$ both mean $a_n\leq Cb_n$ for some constant $C>0$ independent of $n$. We also write $a_n=o(b_n)$ or $\frac{b_n}{a_n}\to\infty$ when $\limsup_n\frac{a_n}{b_n}=0$.''',[6],'Original asymptotic convention. Theorems explicitly discuss sigma=0 although some displayed ratios divide by sigma squared; that convention is recorded as a source issue.')
    add(6,r'''Denote $I_n$ as the $n\times n$ identity matrix and $J_n:=\mathbf1_n\mathbf1_n^T\in\mathbb R^{n\times n}$ as the $n\times n$ matrix with all entries being one.''',[6],'J_d is the all-ones block used to expand each edge mask, not an identity matrix.')
    add(7,r'''For $U,V\in\mathbb C^{d_1\times d_2}$, $U\circ V\in\mathbb R^{d_1\times d_2}$ is the Hadamard product $U\circ V:=(U_{jk}V_{jk})$.''',[6],'The source prints a real output space even for complex inputs. The entrywise multiplication formula is preserved; no cast to real parts is inferred.')
    add(8,r'''Let $\widehat Z\in O(d)^n$ be an $nd\times d$ matrix such that $\widehat Z_j$ is its $j$th submatrix for each $j\in[n]$. Then the performance of $\widehat Z$ can be quantified by a loss function $\ell^{od}(\widehat Z,Z^*)$ that is analogous to (5). The detailed definitions of $\mathcal P$ and $\ell^{od}$ are deferred to Section 3.''',[4],'Original stacked-estimator convention and loss reference. It supports the apparent intent of a global block loss, but the printed page-11 definition omits its sum; no corrected quotation is substituted.',['D5','D8','D9'])
    add(9,r'''Denote $\mathbb S_n:=\{x\in\mathbb C^n:\|x\|=1\}$ as including all unit vectors in $\mathbb C^n$.''',[6],'Unit-vector convention for spectral analysis. The estimator definitions do not specify eigenvalue tie-breaking; eigenvectors/eigenspaces are understood through their stated leading-eigenvalue construction.')
    add(10,r'''Define $O(d_1,d_2):=\{V\in\mathbb R^{d_1\times d_2}:V^TV=I_{d_2}\}$ to include all $d_1\times d_2$ matrices that have orthonormal columns.''',[6],'Main-text orthonormal-column convention for eigenspace matrices. It does not impose a determinant-one restriction on the alignment group.',['D5'])
    add(11,r'''Its non-asymptotic version will be given in Theorem 3 that only requires $\frac{np}{\sigma^2}$, $\frac{np}{\log n}$ to be greater than a certain constant.''',[2],'Relationship between Theorems 1 and 3. They remain separate inventoried claims, not duplicates to discard.')
    add(12,r'''Our main result for the spectral method in the $O(d)$ synchronization is summarized below in Theorem 2. The non-asymptotic version will be given in Theorem 4.''',[5],'Relationship between Theorems 2 and 4. Both are stored in full.')
    issues=[]
    def issue(key,text,pages):issues.append(dict(issue_id=key,description=text,evidence=[dict(page=p,location='Original main-text source convention') for p in pages]))
    issue('unit-circle-variable','The source definition C1={x in C:|z|=1} binds x but uses z in the constraint. The accompanying description says unit complex numbers. Both the printed definition and this contextual interpretation remain separate.',[1])
    issue('orthogonal-loss-missing-sum','The printed orthogonal loss contains (1/n)||Zhat_j-Z*_j O||_F^2 with a free j and no summation. The text calls it analogous to the summed phase loss and describes stacked matrices, but does not supply a corrected display. The original is preserved and the ambiguity remains explicit.',[2,4,11])
    issue('zero-noise-ratios','Theorems 1 and 2 explicitly include sigma=0 consequences, while their preambles and Theorems 3-4 contain np/sigma^2. The author also says the finite-sample result covers no additive noise. No unprinted extended-real division convention is added to the original statements.',[2,5,9,12])
    issue('polar-domain-and-fallback','The mapping P is displayed on all square matrices but its defining polar formula assumes full rank. Estimator (13) explicitly outputs I_d for singular blocks. That fallback is retained rather than extending the polar factor arbitrarily.',[4,10])
    issue('spectral-choice','The estimator definitions specify leading eigenvectors/eigenspaces without an explicit tie-selection rule. Main-text unit-vector and orthonormal-column conventions are retained. No deterministic eigensolver or measurable tie-breaking procedure is invented.',[2,4,6])
    issue('complex-real-ambient','The orthogonal-model W is written in a complex ambient matrix space despite real matrix-Gaussian blocks; the Hadamard-product definition also declares a real result for complex inputs. Preserve these source type inconsistencies without discarding imaginary parts or changing the model.',[6,10])
    issue('finite-sample-constant-scope','Theorem 3 writes C1,C2,C3>0. Theorem 4 writes C1,C2,C3 without >0 and assumes 2<=d<=C0. The text does not separately spell out every dependence on C0. Original scopes are retained; the bounded-d result is not advertised as uniform over growing d.',[9,12])
    refs=[dict(from_claim_id=PID+'/T1',to_claim_id=PID+'/T3',reference_kind='summary_relation',scope='Asymptotic summary and finite-sample statement; both are retained independently.'),dict(from_claim_id=PID+'/T2',to_claim_id=PID+'/T4',reference_kind='summary_relation',scope='Asymptotic summary and finite-sample statement for bounded d; both retained.'),dict(from_claim_id=PID+'/T3',to_source_label='Population eigenvector (8); first-order approximation (9); Proposition 2',reference_kind='proof_only',scope='These tools establish the estimator bound but do not define the estimator or loss.'),dict(from_claim_id=PID+'/T4',to_source_label='Population eigenspace (14); first-order approximation (22); Proposition 4',reference_kind='proof_only',scope='Proof machinery is not part of the estimator/statement dependency graph; appendix proofs remain excluded.')]
    bindings={}
    for n in [1,3]:bindings['T'+str(n)]='The phase model is D2 with Hermitian completion A1 and unit-circle convention D1. The estimator is D3 and phase-aligned averaged loss D4. n,p,sigma retain the model meaning and sequence convention A4. The eigenvector approximations and minimax lower bounds are proof/comparison material, not statement dependencies. '+('Delta=o(1) is existential in the statement; the sigma=0 exact-recovery consequence is part of this Theorem.' if n==1 else 'C1-C3 and the exact finite-sample remainder/probability expressions are bound in this statement. The reciprocal logarithm is outside the square root.')
    for n in [2,4]:bindings['T'+str(n)]='The real orthogonal model is D6 with group D5, block completion A2 and matrix-Gaussian convention A3. The estimator D8 uses the full-rank polar factor D7 and the explicit identity fallback. Loss D9 is kept exactly as printed with its missing sum/free-index issue, supported by stacked-matrix context A8. d is bounded by the theorem; no unrestricted dimension growth is inferred. No phase model or first-order perturbation API is imported. '+('Delta=o(1) and the no-noise exact-recovery consequence are stated explicitly.' if n==2 else 'The fixed C0 bound and finite-sample constants/rates are local binders; the theorem does not repeat >0 for C1-C3.')
    out=dict(paper_id=PID,status='extracted',unranked_auxiliary_passages=aux,source_issues=issues,source_claim_references=refs,statement_local_bindings=bindings,ambient_prerequisites=['Finite-dimensional real/complex vectors and matrices, conjugation, transpose, Hermitian spectral decomposition, singular-value and polar decompositions, Frobenius norms, Bernoulli and Gaussian laws, probability and asymptotic notation retain the source meanings. No library verdict is asserted.','The parameter p is the Bernoulli edge probability; sigma is the noise scale and the no-noise case is explicitly included. Independence is only across the upper-triangle mask/noise variables. Symmetric or Hermitian completion couples opposite edges.','The phase loss has one global complex alignment. The orthogonal loss is intended by the prose to use one global orthogonal alignment, but its printed aggregation is incomplete and remains flagged. Orthogonal matrices include reflections.','Both asymptotic summaries are preserved alongside their finite-sample versions, including their no-additive-noise consequences. The lower-bound displays from cited work are not newly inventoried Theorems.','No population-eigenvector, first-order approximation, perturbation lemma or proof-only minimax object is added as a statement prerequisite. Appendix bodies are excluded.'])
    (ROOT/'ambient-prerequisites.json').write_text(json.dumps(out,indent=2,ensure_ascii=False)+'\n')
if __name__=='__main__':main()
