"""Source conventions, unresolved source issues and statement-by-statement resolution."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];PID=ROOT.name
aux=[]
def add(aid,text,pages,loc,meaning):
    aux.append(dict(auxiliary_id=aid,statement_original=text.strip(),evidence=[dict(page=p,location=loc) for p in pages],resolution=meaning))
add('A1',r'''We denote by $\mathcal F$ the class of all distribution functions on $\mathbb R^p$ for which the expectation $\mathbb E_F[U]$ exists, and we set $\theta_i=\theta_{F,i}=\mathbb E_F[h_i(X_1,\ldots,X_m)]$ to be the ith component of $\theta_F$, where $h_i$, the ith component of the vector $h$ in (2.1), is a symmetric kernel of order $m$.''',[5,6],'Section 2.1 — distribution class and coordinate notation','F is a law on the observation space R^p, whereas theta_F is a vector in R^d. All probabilities are under iid sampling from the selected F; F can vary with n. The existence class F does not impose tail, non-degeneracy or correlation conditions by itself.')
add('A2',r'''\[
a_d=\sqrt{2\log d}\quad\text{and}\quad b_d=a_d-\frac{\log(\log d)+\log(4\pi)}{2a_d}.
\]''',[6],'Constants following equation (2.11)','These constants and the Gumbel quantile are part of the asymptotic test D9. Theorems 2.2/2.4 use q/a_d+b_d. They are not needed to state the bootstrap-calibrated tests or the minimax lower bound.')
add('A3',r'''Let Assumptions (A1') and (A2) be satisfied, assume that $\log d=o(n^\gamma)$ with $0\leq\gamma\leq\frac1{2/\beta+1}$ and that
\[
\frac{B_n^2(\log(nd))^{5+2/\beta}}n+\frac{B_n^3(\log(nd))^{1+2/\beta}}{\sqrt n}=o(1),\quad n\to\infty.\tag{2.24}
\]''',[10],'Theorem 2.5 — inherited assumptions','Theorem 2.8 explicitly inherits this full hypothesis block, including (2.24). It does not inherit the squared statistic or jackknife estimator merely by referencing assumptions. Its own absolute statistic and bootstrap quantile replace those constructions.')
add('A4',r'''The covariance is a special case of (3.1) choosing $h(x_1,x_2)=(x_1-x_2)(x_1-x_2)^\top/2$,''',[15],'Section 3.1 — covariance kernel, excerpt','For the covariance specialization, m=2 and the pairwise kernel is the corresponding off-diagonal entry of this matrix kernel; the upper-triangle convention of D4 gives d=p(p-1)/2. This resolves which kernel is meant by the A1-based alternative class in Theorem 3.5. Conditions C1/C2 from Corollary 3.1 are not imported.')
add('A5',r'''Note that in this case only values $\Delta\in(0,1)$ are useful thresholds for the hypotheses (2.5).''',[18],'Before Theorem 3.5','The covariance lower bound works with unit variances and a positive threshold below one. Its c_0,alpha,beta are positive and alpha+beta<1. Beta is reused here as an error allowance despite its earlier use as the Orlicz shape parameter.')
add('A6',r'''The null hypothesis (2.5) is rejected, whenever
\[
\mathcal T_n^{*,\mathrm{abs}}>q_{1-\alpha}^{*,\mathrm{abs}}.\tag{2.32}
\]''',[12],'Decision formula (2.32), as printed','The formula mistakenly puts a starred bootstrap statistic on the left, whereas the actual Theorem 2.8 uses the observed unstarred T_abs. Both original passages are preserved, with the theorem’s own formula controlling its recorded event.')
add('A7',r'''To be precise, we define
\[
\mathcal T_\alpha:=\{T_\alpha\mid\sup_{F\in\mathcal H_0(\Delta)}\mathbb P(T_\alpha\text{ does not reject }H_0)\leq\alpha\}
\]
as the set of all tests with (uniform) level $\alpha$.''',[18],'Definition of the minimax test class','The source event is nonrejection under the null. That includes an always-reject test and conflicts with a positive lower bound on worst-case nonrejection under alternatives. It is preserved in D25 and flagged; rejection is not silently substituted.')
issues=[]
def issue(key,pages,loc,note):issues.append(dict(key=key,evidence=[dict(page=p,location=loc) for p in pages],note=note))
issue('uniform_supremum_cases',[8],'Theorem 2.2','After the supremum over the whole null class, the statement gives cases and a strictness condition in terms of theta_i of an unspecified F. The dependence of these conditions on the law over which the supremum ranges is not made precise. These are preserved as printed rather than converted to pointwise limits or different subclasses.')
issue('dimension_domain',[4,5,8],'Sampling class and null class','The model and class F use distribution functions on R^p, while the prose introducing H_0 says R^d. The parameter is in R^d. This mismatch is recorded without changing either source passage.')
issue('empirical_variance_zero',[6,7,9],'Equations (2.9)-(2.10), Assumption (A2), Theorem 2.4','The normalized statistic divides by the jackknife standard error, but no convention is given for zero estimates. Assumption (A2) permits degeneracy when |theta_i| is small; Theorem 2.4 uses an alternative class imposing only (A1). The census does not silently define 0/0 or add non-degeneracy to that alternative class.')
issue('sample_and_dimension_domains',[4,6,8,9],'U-statistic order and Gumbel normalization','The combinatorial statistic requires enough observations and the jackknife formula requires n>m. The Gumbel constants require d>1, while the printed gamma range includes gamma=0 and does not by itself force d to diverge. These are implicit domain or regime needs, not additions to the original theorem statements.')
issue('orlicz_norm_name',[7],'Equation (2.13)','For beta<1 the exponential function used here is not a Young function giving an ordinary norm. The source calls the quantity an Orlicz norm throughout beta in (0,2]. Its actual formula, not a different norm definition, is recorded.')
issue('a3_correlation_domain',[7],'Assumptions (A2)-(A3)','The correlation condition presupposes meaningful first-projection correlations in (-1,1), whereas (A2) permits zero variances on coordinates close to zero. The sum excludes i=j, though the introductory correlation definition does not separately state that index restriction. No zero-variance correlation convention is supplied.')
issue('null_class_inclusion_claim',[7,10],'Remark 2.6(1)','The source claims H_0(Delta) is contained in H_(0,boot)(Delta). The latter adds uncentered and repeated-index bounds (A1-prime), which do not follow simply from centered distinct-index bounds in (A1). The two actual class definitions are kept separate; the inclusion is not used to remove a condition.')
issue('truncation_sign',[10],'Equation (2.21)','Every value outside [-Delta,Delta] is mapped to positive Delta, including negative values. The formula is preserved; signed clipping would be a different bootstrap construction.')
issue('conditional_bootstrap_quantile',[9,10,12],'Bootstrap definitions','The prose calls q* a quantile of the bootstrap statistic’s distribution without always repeating conditional on the observations. The resampling construction and conditional mean V_i establish the conditional bootstrap law. It is not treated as an unconditional Monte Carlo quantile.')
issue('bootstrap_alternative_scope',[9,10,12],'Theorems 2.5 and 2.8','The hypothesis block assumes (A1-prime),(A2), but the displayed power infimum ranges over H_1 as defined using only (A1). The census retains that written class and separately records the theorem’s overall hypotheses; it does not silently replace the displayed class by an intersection. The bounded-kernel refinement removes only the extra logarithmic factor in the separation.')
issue('starred_decision_typo',[11,12],'Equations (2.29),(2.32) and Theorem 2.8','The proposed rejection formulas in (2.29),(2.32) use starred bootstrap statistics as their observed statistics. Theorem 2.8 instead explicitly uses the unstarred absolute statistic. The saved theorem follows its own printed event; the conflicting decision formula is archived separately.')
issue('threshold_nesting_direction',[12],'Remark 2.9','The source says rejection for Delta_0 implies rejection for every Delta>Delta_0, immediately after noting the observed statistic decreases with Delta. The displayed preceding comparison points toward smaller thresholds. This remark is not an inventoried Theorem and is not used to strengthen one.')
issue('minimax_test_class_event',[18],'Uniform-level test class and Theorem 3.5','The printed test class bounds null nonrejection instead of null rejection. It therefore includes the always-reject test, for which alternative nonrejection is zero, contradicting the positive right side 1-alpha-beta in (3.3). The source definition and theorem are preserved; the audit does not certify this claim or repair the event.')
issue('minimax_beta_reuse',[7,18],'Theorem 3.5','The letter beta previously parameterizes Orlicz tails; Theorem 3.5 introduces beta again as a positive error allowance with alpha+beta<1. This overloading is recorded, with both source formulas unchanged. The covariance unit-variance and c_0<1-Delta conditions are specific to this theorem.')
resolution={
 'shared':'The iid sample model is D1, with p observation coordinates and a possibly different d-dimensional expectation parameter D2. U-statistic coordinates are D3. F and theta_F coordinates are resolved by A1. The relevance threshold Delta is positive in D5, while n and dimensions can vary along a sequence; m is the kernel order. Standard ambient objects include symmetric measurable maps, expectations, conditional expectations, covariance, finite sums, binomial coefficients, suprema/infima, little-o, logarithms and probability limits. Source-specific domain omissions are documented separately.',
 '2.2':'Explicit hypotheses (A1),(A2),(A3) are D11,D12,D13. The normalized statistic is D8 and its jackknife variance D7; q_(1-alpha),a_d,b_d are D9. The uniform null class H_0 is D14 and region V_0 is D16. Beta and B_n come from (A1); gamma, alpha, the growth condition and (2.16) are inline. The restricted alpha range, strictness clause and both subsequent cases are all retained, including the source ambiguity of theta_i under the supremum.',
 '2.4':'The statement assumes the printed log-d growth condition and binds a separation constant c depending only on gamma,beta. H_1(c) is D15 and imposes only (A1), with separation using its B_n. The statistic D8 and constants D9 are as in (2.11). Neither (A2),(A3) nor the rate (2.16) is imported. The tested alpha is the fixed level in the preceding asymptotic-test setup; the theorem does not restate its range.',
 '2.5':'The hypothesis block is (A1-prime) D17, (A2) D12, log-d growth and exact rate (2.24). Part (1) uses H_(0,boot) D22 with V_0 D16. The observed normalized statistic is D8 and the conditional bootstrap statistic/quantile is D21, built from U* D18, V D19 and the exact truncation D20. Part (2) explicitly ranges over D15 at c(log(nd))^(1/beta) and permits c without that factor for a bounded kernel. The null and alternative classes retain their different written conditions. No (A3) is inherited.',
 '2.8':'The opening reference inherits the assumptions of Theorem 2.5, archived in A3: (A1-prime), (A2), log-d growth and (2.24). The statistic is now unnormalized absolute T_abs D23 and its conditional quantile comes from D24. The null class remains D22 and alternatives D15, with the same bounded-kernel refinement. No jackknife variance, squared statistic, Gumbel constants or correlation assumption is needed to state this theorem. The starred typo in the preceding decision rule is not substituted for its actual unstarred event.',
 '3.5':'The theorem specializes the pairwise measure D4 to the covariance D26 with unit diagonal, so d=p(p-1)/2; A4 identifies its order-two kernel. A5 supplies Delta in (0,1). The source test class is D25 and literally uses H_0 D14, while the worst-case alternative is H_1(c_0) D15. It quantifies arbitrary tests in that class, not the proposed statistic, so there are no jackknife, bootstrap or Gumbel construction prerequisites. The constants c_0,alpha,beta and their inequalities, both dimension rates and the sufficiently-large-n,p qualifier are inline. The erroneous nonrejection definition of the test class is retained and separately identified.'
}
def main():
    (ROOT/'ambient-conventions.json').write_text(json.dumps(dict(paper_id=PID,auxiliary_passages=aux,unresolved_source_conventions=issues,standard_ambient_resolution=resolution),indent=2,ensure_ascii=False)+'\n')
    print('Saved',len(aux),'auxiliary passages and',len(issues),'source notes.')


if __name__ == "__main__":
    main()
