"""Retain original algorithm alternatives and source-definition limits separately."""
import json
from save_inventory import ROOT,PID

def main():
    aux=[]
    def add(n,s,ps,note,deps=()):aux.append(dict(local_id='A'+str(n),statement_original=s,evidence=[dict(page=p,location='Original main-text context A'+str(n)) for p in ps],scope_note=note,depends_on=list(deps)))
    add(1,r'''More generally than (7), we can let $\hat L:=\max\{i:R_i\le R_m^{(J)}\}$, for fixed $J$, where $R_m^{(J)}$ denotes the $J$th smallest value amongst the block averages $R_1,\ldots,R_m$. With this generalized definition we have more data to estimate the long-run variance.''',[4],'Original optional fixed-J order-statistic selection rule. Preserve separately from the basic argmin in (7); it does not supply an unstated tie rule for every estimator.',['D7','D8'])
    add(2,r'''The long-run variance estimate $\hat\sigma_\infty^2$ can be specified by the user. Our estimator $\hat\sigma^2$, defined in (8), is a canonical choice, but any consistent estimate can be used.''',[5],'Original choice allowed in blockwise statistic (9) and Theorem3.3. Theorem3.2 studies the particular estimator (8); its stronger assumptions are not automatically imposed on the global test.',['D2','D5','D11','D13'])
    add(3,r'''Let $\mathbb B$ denote a standard Brownian motion and $\mathbb B_1(u)=\mathbb B(u)-u\mathbb B(1)$ be the Brownian bridge. For all $x\le0$, we have
\[
\mathbb P\left(\inf_{u\in[0,1]}\mathbb B_1(u)\le x\right)=e^{-2x^2};\tag{18}
\]''',[7],'Original interpretation of the limiting distribution. A Brownian representation of the observed noise is not an extra assumption in Theorem3.1.',['D6'])
    add(4,r'''Theorem 3.1(i) suggests that, given level $\alpha\in(0,1)$, we can use the $\alpha$-quantile of the limit, $-(-0.5\log\alpha)^{1/2}$, as the cutoff value to test $H_0$.''',[7],'Original lower-tail global cutoff, distinct from the standard-normal blockwise cutoff z_(1-1/m).',['D3','D6'])
    add(5,r'''As a rule of thumb, we use $\rho=1/2$.''',[6],'Optional practical default; the original locating estimator and Theorem3.3 permit rho in (0,1), subject to gap comparability.',['D18'])
    add(6,r'''In particular, we do not require that $\tau\asymp n$. The requirement $k\ll\tau$ ensures that there is an increasing number of blocks before the change. The requirement $n-\tau\ge2k$ is slightly weaker and ensures that there is at least one complete block after the change.''',[9],'Original explanation allowing early or late changes; do not impose a fixed interior change fraction on the localization theorem.',['D4','D7','D24','D26'])
    add(7,r'''We show (Lemma A.5) that our proposed $\hat d$ consistently estimates $d_*$. By definition $d_*\ge d$; i. e., $d_*$ provides an upper bound for the gap $d$. The regularity condition $d>Kd_*$, for a constant $K>\rho$, requires that $d_*$, which is tractable, also facilitates a lower bound with respect to $d$.''',[9],'Original distinction between the lower pointwise gap bound and the estimable averaged gap. The supplementary proof is not read or imported.',['D4','D17','D18','D26'])
    add(8,r'''If the true $d$ were known, we could use the following estimate for $\tau$:
\[
\tilde\tau:=\operatorname*{argmin}_{j=2,\ldots,n}\sum_{t=1}^{j-1}(X_t-\hat\mu_1-\rho d).\tag{21}
\]''',[9],'Original oracle alternative, distinct from the actual estimator using d_hat in (12). Do not replace the main estimator by this easier known-gap procedure.',['D1','D4','D16'])
    add(9,r'''Condition 3.1 holds, for example, under the geometric moment contraction $\delta_{n,\theta}=O(\rho^n)$ for some $\rho\in(0,1)$,''',[8],'Original sufficient example, not an additional geometric-decay hypothesis. This rho is a decay factor, distinct from the localization tuning parameter.',['D20','D22'])
    bindings={
    'T3.1':'Common model has stationary centered causal noise with strictly positive finite long-run variance. Theorem assumes summability of L2 functional dependence. Under constant-mean H0 the minimum CUSUM statistic has the printed one-sided Brownian-bridge minimum distribution. Under the irregular one-sided H1, the signal rate forces the statistic to negative infinity in probability. Definition (5) requires a consistent variance estimate under the hypothesis being considered. It need not be estimator (8), and the stronger Condition3.1/block rates are not added as general premises.',
    'T3.2':'This theorem studies the particular selected-prefix overlapping-block estimator sigmahat² in (8). Resolve block size/count, minimum-block index and prefix endpoint, preliminary mean, sliding block averages and the true block index eta=floor(tau/k). d,tau come from H1 and can depend onn. Condition3.1 supplies the same theta used in the d and k rate requirements. Preserve the deterministic O(1/k) and separate random O_P(eta^(2/min(4,theta)-1)) terms. No blockwise decisions or refined localization step is required.',
    'T3.3':'Actual estimator (12) uses the improved prefix mean and estimated averaged gap, which depend on block means, preliminary index/mean, standardized block statistics, normal-quantile decisions and binary step fit. Variance estimate in (9) may be any consistent estimator, not necessarily (8). Resolve d_star using the true block index and signal means, retain d>K*d_star with K>rho and rho in(0,1), the same theta across all rates, and n-tau>=2k. The conclusion is the printed d_star^(-theta/(theta-1)) localization rate for the first changed observation.'}
    refs=[]
    for n in ['3.1','3.2','3.3']:refs.append(dict(claim_id=PID+'/T'+n,target='Model(1), long-run variance(2), relevant hypotheses(3)/(4), causal process(13), functional dependence(14)/(15)',reference_kind='definition_reference',note='Main-text definitions resolve the observed data, signal and temporal dependence.'))
    refs.append(dict(claim_id=PID+'/T3.1',target='Statistic(5) and any consistent variance estimator',reference_kind='definition_reference',note='The canonical batch variance estimator is optional; do not impose its stronger consistency theorem as a general requirement.'))
    refs.append(dict(claim_id=PID+'/T3.2',target='Blocking(6), prefix selection(7), selected overlapping variance estimator(8), Condition3.1 and eta on5/8',reference_kind='definition_reference',note='All components of the specific estimator and its rate parameters are stored.'))
    refs.append(dict(claim_id=PID+'/T3.3',target='Steps(9)–(12), preliminary block selection/mean, Condition3.1 and d_star(20)',reference_kind='definition_reference',note='Separate the generic variance choice from estimator(8), and the actual estimated-gap algorithm from oracle(21).'))
    for n,sec in [('3.1','A.1'),('3.2','A.2'),('3.3','A.3')]:refs.append(dict(claim_id=PID+'/T'+n,target='Supplementary Section '+sec,reference_kind='proof_only',note='All appendix bodies are excluded; source extraction does not certify the deferred proof.'))
    refs.append(dict(claim_id=PID+'/T3.3',target='Lemma A.5, KMT coupling(19), oracle estimator(21)',reference_kind='proof_only',note='These justify or interpret the result; they do not replace its original algorithm or become extra assumptions.'))
    issues=[]
    def issue(k,ps,note):issues.append(dict(issue_id=k,evidence=[dict(page=p,location='Source issue '+k) for p in ps],note=note))
    issue('registered-source',[1,16],'Registered arXiv2409.08863v1, stamped13September2024,39pages. Main text ends after acknowledgments/funding on16. Supplementary availability listings and references occupy17–18; appendix bodies start19 and are excluded. Exactly three main-text Theorems3.1–3.3; Corollary3.1 is not inventoried.')
    issue('change-index-and-gap',[3,6,8,9],'Tau denotes the first changed observation, so pre-change means stop at tau-1 and the final argmin sums through j-1. d is a positive lower bound for all post-change gaps, not necessarily the attained minimum. d_star averages the signal over sliding blocks; d_hat estimates that averaged quantity. Preserve the strict d>K*d_star inequality with K>rho; feasibility with d_star>=d implies K<1 rather than an arbitrary large constant.')
    issue('true-block-index-boundary',[5,8],'The source defines eta=floor(tau/k) and also calls it the last fully pre-change block, writing eta*k+1<=tau<=(eta+1)*k. At tau exactly divisible byk, that interval is inconsistent and the eta-th block includes the first changed observation. Retain the literal floor definition and the contradictory prose; do not silently substitute floor((tau-1)/k).')
    issue('generic-versus-specific-variance',[4,5,7,8,9],'Definitions(5) and(9) permit any consistent long-run-variance estimator; estimator(8) is a suggested canonical choice. Theorem3.2 supplies a rate for(8) under its own stronger moment/block/gap conditions. These do not become mandatory premises ofTheorem3.1, and Theorem3.3 does not require that its user-chosen variance estimate be(8). The mean muhat0 from(8) is still a required preliminary mean for(9).')
    issue('overlapping-window-normalization',[4,5],'R_(s/k) extends nonoverlapping R_j to sliding windows even for noninteger s/k. The variance estimate uses k/(ellhat-k+1), all endpoints s=k..ellhat and centering by the entire selected-prefix mean. It is not an average over only the original disjoint block means.')
    issue('ties-and-empty-minima',[4,5,6],'Argmin tie-breaking for L_hat, eta_hat and tau_hat is not stated. The optional fixed-J max-index selection is not a general tie convention. For finite data, eta_hat=m-1 is allowed by(10) but makes the sliding-window range in d_hat empty; no fallback is supplied. High-probability asymptotics do not by themselves define these bad finite-sample outputs.')
    issue('finite-sample-denominators',[3,4,5],'Population long-run variance is explicitly positive and finite. Generic consistent estimates can still be zero or negative on finite-sample events; estimator(8) is nonnegative but can be zero. The source does not fully specify square-root/sign/zero-division conventions. m>=2 is needed for the interior normal quantile and step-fit range, and follows eventually from the stated growth regime.')
    issue('dependence-parameters',[6,7,8],'Functional dependence replaces only innovation0 by an independent copy. Cumulative dependence sums over future indices, while long-run covariance sums over all integer lags. Condition3.1 retains both theta regimes and the exact gamma_theta radical/log threshold; gamma_theta is not the autocovariance gamma(k). The same theta must satisfy all moment, signal and block-rate conditions.')
    issue('rates-and-optional-defaults',[6,7,8,9],'Theorem3.2 has separate deterministic and probabilistic error terms. Theorem3.3 uses d_star with negative exponent theta/(theta-1). Rho=1/2, block length ceil(n^(1/3)) and geometric moment contraction are optional examples, not universal hypotheses. Early and late changes are allowed; tau need not be proportional ton.')
    issue('proof-and-application-scope',[7,8,9,16],'Brownian-bridge limits and KMT coupling interpret or prove the statistical results, not extra assumptions on observed noise. Oracle true-gap estimator(21) is not the actual estimator(12). Appendix proofs are excluded. The empirical interpretation of a search-index change as an epidemic starting date is application context and is not certified by this theorem census.')
    data=dict(paper_id=PID,unranked_auxiliary_passages=aux,statement_local_bindings=bindings,source_claim_references=refs,source_issues=issues,unresolved_external_prerequisites=[],ambient_prerequisites=['Real deterministic mean sequences and stationary centered processes; covariance and positive finite two-sided long-run variance.','Causal measurable processes driven by IID innovations, independent-copy coupling, Ltheta norms and summable functional-dependence tails.','Finite partial sums, integer floors and sliding windows, empirical prefix means, minimum/argmin operations and binary indicator step fitting.','Standard-normal quantiles for blockwise decisions; Brownian-bridge minimum distribution only as the global-test limiting interpretation.','Convergence in probability, little-o and stochastic O_P, deterministic versus random rate remainders and n-dependent change positions/gap sequences.','Tie, empty-window, exact block-boundary and finite-estimate division issues are recorded rather than filled with invented conventions. All statement definitions are available in main text; no appendix-only definition is needed.'],validation_limits='Main-text source fidelity and dependency scope only. No proof or library-availability verdict, and no certification of empirical causal interpretations. The recorded source indexing and finite-sample definition limitations remain unresolved.')
    (ROOT/'ambient-prerequisites.json').write_text(json.dumps(data,indent=2,ensure_ascii=False)+'\n')
if __name__=='__main__':main()
