"""Preserve auxiliary notation and resolve the five statements without reading supplements."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];PID=ROOT.name
aux=[]
def add(aid,text,pages,loc,meaning):
    aux.append(dict(auxiliary_id=aid,statement_original=text.strip(),evidence=[dict(page=p,location=loc) for p in pages],resolution=meaning))
add('A1',r'''Let $\mathbf R$ represent a vector (or a matrix) valued function defined on $(0,1)\times\mathbb R^d$, such that for some constant $C$, $\|\mathbf R(a,\mathbf x)\|<aC(1+\|\mathbf x\|)^C$ for all $a$, $\mathbf x$. When denoted $R$, it is a scalar.''',[6],'Notation — remainder convention','R is a generic order bound with polynomial state dependence; different appearances need not be the same function or constant. Its first argument must lie in (0,1) under the literal convention.')
add('A2',r'''The differential operator $D$ denotes the Jacobian matrix $D\mathbf F(\mathbf x)=[\partial_i F^{(j)}(\mathbf x)]_{i,j=1}^d$, for a vector-valued function $\mathbf F:\mathbb R^d\to\mathbb R^d$. $H$ denotes the Hessian matrix of a real-valued function $g$, $H_g(\mathbf x)=[\partial_{ij}g(\mathbf x)]_{i,j=1}^d$.''',[6],'Notation — differential operators','The source puts derivative index i first in the Jacobian. The trace in (23) is insensitive to transpose; this does not resolve the orientation of every proof-only matrix product.')
add('A3',r'''For an open set $A$, the bar $\overline A$ indicates closure. We use $\overset{\boldsymbol\theta}=$ to indicate equality up to an additive constant that does not depend on $\boldsymbol\theta$. We write $\xrightarrow{\mathbb P}$, $\xrightarrow{d}$ and $\xrightarrow{\mathbb P\text{-a.s.}}$ for convergence in probability, distribution, and almost surely, respectively.''',[6],'Notation — closures, additive constants and stochastic convergence','The full contrasts below are specified up to a parameter-independent additive constant. This convention does not make different approximate and full contrasts identical.')
add('A4',r'''Since only one-sided Lipschitz continuity is assumed, the solution to (4) might not exist for all $h<0$ and all $\mathbf x_0\in\mathbb R^d$, implying that the inverse $\mathbf f_h^{-1}$ might not exist. If it exists, then $\mathbf f_h^{-1}=\mathbf f_{-h}$. For the S estimator, we need a well-defined inverse. This is not an issue when $\mathbf N$ is globally Lipschitz.''',[8],'Remark 3 — inverse flow','This is the source context for (A6). Forward completeness does not by itself provide a globally defined backward flow.')
add('A5',r'''The LT scheme (10) follows a Gaussian distribution. Consequently, the objective function corresponds to (twice) the negative pseudo-log-likelihood:
\[
\mathcal L^{[\mathrm{LT}]}(\mathbf X_{0:t_N};\boldsymbol\theta)\overset{\boldsymbol\theta}=N\log(\det\boldsymbol\Omega_h(\boldsymbol\theta))
+\sum_{k=1}^N(\mathbf X_{t_k}-\boldsymbol\mu_h(\mathbf f_h(\mathbf X_{t_{k-1}};\boldsymbol\beta);\boldsymbol\beta))^\top\boldsymbol\Omega_h(\boldsymbol\theta)^{-1}(\mathbf X_{t_k}-\boldsymbol\mu_h(\mathbf f_h(\mathbf X_{t_{k-1}};\boldsymbol\beta);\boldsymbol\beta)).\tag{12}
\]
''',[9],'Section 2.4.1 — full LT objective','Archived to distinguish the full contrast from the approximate (22) named in the Theorems; it is not substituted for (22).')
add('A6',r'''Afterwards, we apply a change of variables to derive the following objective function:
\[
\mathcal L^{[\mathrm S]}(\mathbf X_{0:t_N};\boldsymbol\theta)\overset{\boldsymbol\theta}=N\log(\det\boldsymbol\Omega_h(\boldsymbol\theta))+\sum_{k=1}^N\mathbf Z_{t_k}(\boldsymbol\beta)^\top\boldsymbol\Omega_h(\boldsymbol\theta)^{-1}\mathbf Z_{t_k}(\boldsymbol\beta)
-2\sum_{k=1}^N\log|\det D\mathbf f_{h/2}^{-1}(\mathbf X_{t_k};\boldsymbol\beta)|.\tag{14}
\]
''',[9],'Section 2.4.1 — full S objective','Z is equation (13), archived with D16. The full contrast contains the inverse-flow Jacobian at the observation, unlike the trace term in (23).')
add('A7',r'''The inverse function $\mathbf f_h^{-1}$ may not exist for all parameters in the search domain of the optimization algorithm. However, this problem can often be solved numerically. When $\mathbf f_h^{-1}$ is well defined, we use the identity $-\log|\det D\mathbf f_h^{-1}(\mathbf x;\boldsymbol\beta)|=\log|\det D\mathbf f_h(\mathbf x;\boldsymbol\beta)|$ in (14) to increase the speed and numerical stability.

Finally, we define the estimators as
\[
\widehat{\boldsymbol\theta}_N^{[k]}:=\operatorname{argmin}_{\boldsymbol\theta}\mathcal L^{[k]}(\mathbf X_{0:t_N};\boldsymbol\theta),\qquad k\in\{\mathrm{LT},\mathrm S\}.\tag{15}
\]
''',[10],'Section 2.4.1 — inverse identity and full-contrast minimizers','The inverse-Jacobian identity is preserved literally with x on both sides. In general the forward Jacobian must instead be evaluated at the inverse image. The minimizer display also does not specify a tie-breaking or failed-domain rule.')
add('A8',r'''The objective functions are formulated in simple terms without hyperparameters, such as the order of the expansions. Hence, our approach is robust and user friendly, as we directly employ (12) and (14). The approximations (22) and (23) are only used for the proofs.''',[17],'Section 5 — practical versus theoretical objective functions','The surrounding prose says full objectives are used in practice, whereas both printed estimation Theorems explicitly specify minimizers of (22) or (23). Their text is retained without replacing those references.')
issues=[]
def issue(key,text,pages):
    issues.append(dict(issue_id=key,description=text,evidence=[dict(page=p,location='Inspected source convention') for p in pages],resolution_status='source_preserved'))
issue('S1','Theorems 5.1 and 5.2 explicitly minimize approximate objectives (22)/(23), while the full estimators in (15) minimize (12)/(14) and the surrounding prose says these full objectives are used in practice. The census does not silently assert identical minimizers or transfer a theorem between them.',[9,10,17,18])
issue('S2','The parameter search space in Section 2 is the closure of the product of bounded open convex domains. The true parameter is interior. In contrast, the forward-flow domain, semigroup quantifier and (A6) on page 8 use unbarred Theta_beta. The different printed domains are retained; inverse availability at every boundary search parameter is not asserted.',[6,8,10])
issue('S3','The initial parameter is (beta,Sigma), the consistency target is (beta,Sigma Sigma^T), and the normality coordinates are (beta,varsigma). The paper explains covariance identifiability but does not explicitly redefine Theta under these coordinate changes. A parameter domain for a future implementation needs to respect this distinction.',[6,17,18])
issue('S4','The shorthand Sigma Sigma_0^T means the true covariance Sigma_0 Sigma_0^T, not a product of a candidate Sigma with the true transpose. Derivatives of F_0 and the true covariance in (27) are interpreted as differentiating the family before evaluation at the true parameter.',[6,18])
issue('S5','Assumption (A6) says the inverse is defined asymptotically for all x and beta when h tends to zero. It does not specify a uniform small-step threshold over states and parameters, or a global inverse for every finite h. The source itself acknowledges possible nonexistence within the optimization search domain.',[8,10])
issue('S6','Corollary 3.8 proof invokes polynomial growth of the inverse flow. That extra inverse-growth statement is not explicit in (A6). The census preserves (A6) rather than adding this proof claim as a new theorem hypothesis.',[8,15])
issue('S7','The inverse-Jacobian identity printed on page 10 evaluates the forward and inverse Jacobians at the same x. The general inverse-function identity evaluates the forward Jacobian at f_h^{-1}(x). The source formula is archived unchanged and not treated as a verified algebraic identity.',[10])
issue('S8','The OU covariance expansion (6) literally ends with the weaker matrix remainder R(h,x_0) after its h and h^2 terms. It is not transcribed as R(h^3,x_0), even though a stronger order is natural from the integral formula.',[8])
issue('S9','R is defined for a first argument in (0,1), with polynomial state dependence and an unspecified constant. Theorems use it as order notation, not a fixed common function. The approximate-objective introduction also writes R(Nh^2,x_0), while consistency alone assumes h to zero and Nh to infinity, without Nh^2 to zero.',[6,13,14,15,17])
issue('S10','Strong Lp errors compare paths, so the OU innovations must be coupled to the driving Wiener increments. The source identifies them through the OU flow and states their iid Gaussian law; a distribution-only construction with unrelated independent noise would not preserve the strong comparison.',[6,8,14,15])
issue('S11','The grid has N increments and N+1 observations, with T=Nh. Numerical moment/error bounds are on a finite horizon; the estimation Theorems explicitly let the observation horizon diverge. The census does not assume every numerical-bound constant is uniform in a growing horizon.',[7,13,14,15,17,18])
issue('S12','Definition 3.1 uses a conditional mean error of order q1 and a conditional 2p-moment root of order q2, with q1 at least q2+1/2. Theorem 3.3 uses 2p moments for p>=1; Theorems 3.5 and 3.7 use p moments for p>=2. The printed existential C>=1 is retained even though C does not explicitly occur in the displayed conclusions.',[13,14,15])
issue('S13','Assumption (A1) explicitly gives C2 regularity for N, while Section 2 only describes A and b as parameterized functions and F as locally Lipschitz. The information matrix needs parameter derivatives of F. The source extraction does not silently add a separate smoothness assumption on A and b.',[6,7,18])
issue('S14','Assumption (A3) states existence of an invariant probability. It does not itself explicitly assert uniqueness, ergodicity, stationary initialization, or all invariant moments. Assumption (A5) states equality of drifts for every state, not merely almost everywhere under that probability.',[7])
issue('S15','Section 2 assumes positive-definite covariance and the estimation Theorems explicitly include (A4). Prose discusses the potential applicability of S to hypoelliptic models, with proofs deferred to a separate paper. Those extensions are not added to the scope of the printed Theorems.',[6,7,17,18,23])
issue('S16','The source vech ordering is S_11,S_12,S_22,...,S_1d,...,S_dd. It must not be replaced by a different triangular ordering without coordinating derivatives and information blocks. For a diagonal covariance the source uses diag instead; its dimension is d rather than the general s=d(d+1)/2.',[17,18])
issue('S17','The source Jacobian convention puts derivative index first. Transposition does not alter the trace used in (23), but the convention should not be silently replaced when interpreting other matrix products. The census records the original definition separately.',[6,17])
issue('S18','The statement minimizers are not accompanied by explicit existence, measurable-selection, tie-breaking or failed-inverse-domain conventions. These are unresolved implementation choices, not extra conditions inserted into the original Theorems.',[10,17,18])
issue('S19','Theorems 3.3 and 3.5 repeat cited external results but are nevertheless printed as Theorems in the main text and are included. Lemmas, Propositions and Corollaries remain outside the inventory; no supplementary proofs or code have been opened.',[13,14,15,23])
resolution={
 'shared':'D1 gives the filtered additive-noise diffusion with deterministic initial state; D2 specifies its linear/nonlinear decomposition, closed parameter search domain, interior true parameter and covariance shorthand. D8 gives N+1 equidistant observations. Euclidean vectors, matrix operations, Gaussian laws, expectations and stochastic convergence are ambient. A1-A3 archive the generic remainder, derivative, closure and additive-constant notation. A4-A8 preserve inverse-flow and full-objective context. Source ambiguities remain explicitly recorded, without certifying proofs.',
 '3.3':'D1/D3/D4 specify the exact SDE and A1-A2. The numerical process and one-step map are bound in the theorem; D14 is its conditional Lp consistency and D15 its bounded moments. D8 resolves k,N,h; x_0 is the exact initial state. The q1,q2 conditions come from Definition 3.1 and the conclusion uses the generic scalar remainder. No particular splitting, invariant measure or inverse flow is required.',
 '3.5':'D12 resolves the exact nonlinear-then-OU LT approximation (10), with D9/D10 resolving its stochastic and deterministic steps. D3/D4 are the explicit A1-A2 hypotheses; D1 and D8 resolve the exact solution and grid. The p-moment root, p>=2 and R(h,x_0) conclusion are preserved; no A3-A6 assumptions are imported from the estimation section.',
 '3.7':'D13 resolves the nonlinear-half/OU-full/nonlinear-half S scheme (11). D3/D4 supply A1-A2 and D11 supplies the explicitly added A6. D1/D8 resolve the exact solution and time grid; D9/D10 recursively resolve the forward steps. The theorem assumes inverse availability although its displayed forward scheme contains no inverse. Invariant probability and identifiability are not additional premises.',
 '5.1':'D3-D7 and D11 separately unpack A1-A6. D16 is the pair of approximate objectives (22)/(23), with Z from (13) archived as its application context; D9/D10 resolve the OU mean and deterministic flow. D1/D2 give the model, parameter and true covariance. D8 resolves the high-frequency long-horizon limits. The minimizer is bound by the theorem; covariance half-vectorization and the Fisher information are not necessary for this consistency statement.',
 '5.2':'The same model, A1-A6 and approximate objectives as in Theorem 5.1 are used. D17 resolves varsigma, and D18 resolves the positive-definite matrix C(theta_0) whose inverse is the Gaussian covariance. The two convergence scales are sqrt(Nh) for beta and sqrt(N) for covariance coordinates. The extra Nh^2 tending to zero condition and the explicit interior true-parameter condition are preserved. No particular Lorenz model or comparison estimator is required.'
}
def main():
    (ROOT/'ambient-conventions.json').write_text(json.dumps(dict(paper_id=PID,auxiliary_passages=aux,unresolved_source_conventions=issues,standard_ambient_resolution=resolution),indent=2,ensure_ascii=False)+'\n')
    print('Saved',len(aux),'auxiliary passages and',len(issues),'source-convention notes.')


if __name__ == "__main__":
    main()
