"""Rebuild main-text ambient conventions, branch resolution and source issues."""
import json
from pathlib import Path
from save_inventory import PID
ROOT=Path(__file__).resolve().parents[1]
aux=[]
def passage(lid,pages,heading,text,note):
    aux.append(dict(local_id=lid,source_heading=heading,statement_original=text.strip(),evidence=[dict(page=p,location=heading) for p in pages],note=note))
passage('A1',[5,6],'Section 1.1 — norms and asymptotic notation',r'''
For $k\in\mathbb N$, we define the set $[k]:=\{1,2,\cdots,k\}$. We typically use lower case non-bold letters for scalars ($m,n,j$), and bold for vectors and matrices ($\boldsymbol x,\boldsymbol y,\boldsymbol z,\boldsymbol A,\boldsymbol B,\boldsymbol C$). We use $\|\boldsymbol v\|$ to denote the Euclidean norm of a vector $\boldsymbol v$, and $\|\boldsymbol M\|_F$ to denote the Frobenius norm of a matrix $\boldsymbol M$. For $\{c_n\}_{n\in\mathbb N_+},\{d_n\}_{n\in\mathbb N_+}\subseteq\mathbb R_+$, we say $c_n\gg d_n$ if and only if $c_n/d_n\to\infty$, and for $\{e_n\}_{n\in\mathbb N_+}\subseteq\mathbb R$, we say $e_n=o_n(1)$ if and only if $e_n\to0$ as $n\to\infty$. We denote by p-lim convergence in probability.
''','Explains vector/Frobenius losses and convergence notation. Operator norm in (5), conditional expectations, products of measures and measurable estimators retain their standard ambient meanings.')
passage('A2',[6],'Section 1.1 — matrix cone, orthogonal group and square root',r'''
For $k\in\mathbb N_+$, we denote by $S_k^+$ the set of positive semi-definite matrices in $\mathbb R^{k\times k}$, and denote by $\mathcal O(k)$ the set of orthogonal matrices in $\mathbb R^{k\times k}$. For $\boldsymbol M\in S_k^+$, we let $\boldsymbol M^{1/2}\in S_k^+$ be any positive semi-definite matrix such that $\boldsymbol M=\boldsymbol M^{1/2}\boldsymbol M^{1/2}$.
''','The source requires the matrix square root to remain positive semidefinite. Orthogonal matrices in O(k) are not the same as orthogonal projection matrices; the latter are incorrectly assigned to O(n) before (5).')
passage('A3',[6],'Section 1.1 — factor-row and posterior notation',r'''
We denote the $i$-th row of the factors $\boldsymbol\Lambda,\boldsymbol\Theta$ by $\boldsymbol\Lambda_i$ and $\boldsymbol\Theta_i$, respectively. We use $\boldsymbol\Lambda_0$ and $\boldsymbol\Theta_0$ to represent length-$r$ random vectors drawn from probability distributions $\mu_\Lambda$ and $\mu_\Theta$. We sometimes need to write the posterior distribution of $(\boldsymbol\Lambda,\boldsymbol\Theta)$ given particular observations. In this case, we use the lower case letters $\boldsymbol\theta,\boldsymbol\lambda,\boldsymbol\lambda_i,\boldsymbol\theta_i$ to represent variables corresponding to $(\boldsymbol\Theta,\boldsymbol\Lambda,\boldsymbol\Lambda_i,\boldsymbol\Theta_i)$ in the posterior distribution.
''','The index zero denotes a generic draw, not an observed row or null hypothesis. Lowercase lambda in the free-energy integral is an integration variable under the Lambda prior.')
passage('A4',[8],'Theorem 3.2 — Gaussian variables for limiting Bayes risks',r'''
where $\boldsymbol G\sim\mathsf N(0,\boldsymbol I_r)$, $\boldsymbol\Theta_0\sim\mu_\Theta$ are mutually independent. Notice that the right hand side of Eq. (7) is independent of $(n,d)$.
''','The conditional expectations in Theorems 3.2 and 3.3 use this same finite-dimensional Gaussian experiment Q_Lambda^(1/2)Theta_0+G. Conditional expectation, its outer product and the norm are ambient operations; a new named definition is not invented for an inline expression.')
passage('A5',[9],'Free energy functional — expectation convention',r'''
In the above expression, expectation is taken over $\boldsymbol\Lambda_0\sim\mu_\Lambda$ and $\boldsymbol z\sim\mathsf N(0,\boldsymbol I_r)$ independent of each other. These functionals are directly related to the mutual information and the Bayes MMSE of model (10), as stated below.
''','Completes the probabilistic scope of (13). The integration variable lambda is a separate prior variable, while the outer expectation includes both a planted draw Lambda_0 and independent Gaussian noise z.')
passage('A6',[13],'Gaussian mixture model — common known covariance',r'''
As an application of our theory, we consider clustering under Gaussian mixture model (GMM). Throughout, we will assume that all Gaussian components have equal covariance $\boldsymbol\Sigma$, and that $\boldsymbol\Sigma$ is known. Without loss of generality, we can therefore assume that data are preprocessed so that $\boldsymbol\Sigma=\boldsymbol I_d$. We will focus on the weak signal regime, because it is mathematically the most interesting regime.
''','Section 5.2 and Theorem 5.1 inherit known equal component covariance and its identity normalization. This covariance is the observation-noise covariance, not the center-row covariance q_Theta I_k.')
passage('A7',[12],'Remark 4.1 — unproven continuity condition',r'''
In particular, Theorem 4.4 establishes that the estimation errors under the symmetric and asymmetric models coincide asymptotically, provided that the error in the perturbed model $\operatorname{MMSE}_n^{\mathrm{asym}}(\mu_\Lambda,\mu_\Theta;\varepsilon)$ is uniformly continuous (in $n$) as $\varepsilon\downarrow0$. We expect this to be generically the case, but proving this remains an open problem.
''','The extra uniform continuity is not an assumption or conclusion of Theorem 4.4 itself. Its two inequalities and the order of the limits must remain distinct. Theorem 4.5 supplies separate sufficient alternatives for equality.')
passage('A8',[7],'Remark 3.1 — free signal parameter',r'''
Note that this argument shows that we could assume $q_\Theta=1$ as well, but it is convenient to keep this as a free parameter.
''','The source reparameterization retains a positive signal parameter. In the symmetric model it is treated as a freely varying parameter; Theorem 4.1 also expressly includes q_Theta=0.')
passage('A9',[14],'Clustering — minimax interpretation is separate from the theorem model',r'''
While we state our results for random $\boldsymbol\Theta$, we can generalize Remark 5.1 to the present setting. This argument implies that the results of this section also characterize the minimax estimation error over the class of problems with orthogonal centers $\boldsymbol\Theta^{\mathsf T}\boldsymbol\Theta=d\,q_\Theta\boldsymbol I_k$.
''','This is Remark 5.2, not a replacement for the random iid-center assumptions in Theorem 5.1. Do not silently impose exact finite-sample center orthogonality on its original model.')
NOTES=[
'The registered source is the 74-page arXiv:2211.00488v1 PDF dated 1 November 2022. Main text and references end after [ZSF22] on page 28. The separately inspected Appendix A heading is on page 29; no appendix bodies were read.',
'Nine main-text Theorems are stored in source order: 3.1-3.3, 4.1-4.5 and 5.1. Theorem 4.1 remains included despite its citation to [LM19]. Proposition 5.1, Corollary 4.1 and numbered remarks remain outside this inventory.',
'Theorem 4.2 continues onto page 10 and ends with its null-estimator attainment sentence. Theorem 5.1 continues onto page 15; the threshold table inserted before its two clauses is not part of its statement.',
'The general model has fixed known factor-row distributions and fixed rank, independent across rows and between factors and noise. Priors depending on n,d, proportional-aspect-ratio results and swapped-factor analogies are not silently substituted for this scope.',
'The exact scales are n^(-1/2) in (4) and (nd)^(-1/4) in (9). Symmetric model (10) uses q_Theta/n times the Gram matrix and a GOE with diagonal variance 2/n and off-diagonal variance 1/n.',
'Q_Lambda and Q_Theta are uncentered second moments, not general covariance matrices. The full Remark 3.1 conditions and the explicit Theta normalization selected in Theorem 4.3 are recorded separately. The symmetric comparison model itself requires no Theta prior or Assumption 4.1.',
'Before equation (5), the source writes that the column-space projection matrices P and P-hat lie in O(n), although O(n) is defined as the orthogonal group. Nontrivial projections are not orthogonal matrices. Preserve this apparent source error, not a repaired definition.',
'The source calls alpha the principal angle, while the operator-norm formula corresponds to the largest relevant angle for equal-dimensional subspaces. Finite-sample rank degeneracy of Lambda and repeated-eigenvalue choices are not explicitly addressed. The projector formula and spectral normalization are preserved.',
'Claim 2 of Theorem 3.1 explicitly adds a 4+epsilon moment of Lambda_0 for Gram-matrix consistency. Claim 3 separately states an orthogonal distributional-identifiability condition. The word further leaves some scope ambiguity; extraction treats the separately numbered claims as additions to the common opening hypotheses and records, rather than invents, any cumulative moment requirement.',
'Theorem 3.3 cites Theorem 3.1 claim 3. It does not itself print the additional fourth moment of Theta_0 used in Theorem 3.2\'s matrix-risk lower bound. Do not import that fourth moment merely by comparing the two conclusions; all literal assumptions remain available for later formalization.',
'Theorem 4.1 prints Q-star(s) in a formula otherwise parameterized by q_Theta, without binding s. The adjacent functional suggests s=q_Theta^2, but the original statement is retained and the substitution is not silently performed.',
'Equation (13) is introduced for s>0, while Theorem 4.1 and threshold definition (26) also use q_Theta=0. A zero-s extension is not separately defined there. The source argmax is not asserted unique, and the countable exception in Theorem 4.1 applies only to its MMSE conclusion.',
'Theorem 4.2 has no zero-mean or sub-Gaussian requirement from Assumption 4.1, which is introduced later for the Lambda-estimation section. Its two bounds allow a nonzero Theta mean and require a fourth moment only for the second bound.',
'Assumption 4.1 requires zero first and full third tensor moments of Theta_0, but not of Lambda_0. Both priors are sub-Gaussian. The main text does not give a precise vector sub-Gaussian norm convention, and appendix definitions are not imported.',
'Theorems 4.4 and 4.5 refer to conditions of Theorem 4.3; they do not need its mutual-information objects merely because those objects occur in its conclusion. Likewise Theorem 4.5 does not depend on the perturbation model solely because its proof uses Theorem 4.4.',
'Theorem 4.4 first gives a liminf lower bound for the unperturbed risk, then a vanishing-side-channel limsup upper bound. Epsilon tends to zero after the n,d limit. The independent extra observation is available together with A, not in place of A. Generic equality without extra assumptions is not claimed.',
'Theorem 4.5 requires at least one of alternatives (a), (b) and (c), not all three. Bounded support and the final countable-exception qualification belong to (b). The rank-one scalar-channel condition belongs only to (c). Logarithmic powers and the two aspect-ratio inequalities are retained exactly.',
'Theorem 4.5(c) prints global maximum for Psi(gamma,s)=s^2/4+gamma^2/(4s)-gamma/2+I(gamma) over gamma>0. If I is the stated Gaussian-channel mutual information, it is nonnegative, so for fixed s>0 this displayed expression is unbounded above. The maximum requirement is therefore an apparent source inconsistency. Do not replace maximum with minimum, change the signs or certify this alternative as meaningful.',
'Theorem 5.1 uses uniform one-hot labels and iid random center rows with vanishing first/third moments and covariance q_Theta I_k. The signed two-cluster encoding and its threshold from Proposition 5.1 are different and are not imported.',
'The threshold baseline Q0 is the outer product of the one-hot prior mean, 1_k 1_k^T/k^2; it is not the second moment I_k/k. Definition (26) uses strict free-energy improvement. Theorem 5.1 says nothing at equality q_Theta=q_info_Theta(k).',
'Theorem 5.1(a) asserts convergence in probability to chance overlap 1/k for every measurable estimator. Part (b) asserts existence with liminf expected overlap above 1/k and adds either of two growth conditions. These two modes of convergence and quantifiers are not homogenized.',
'Norms, expectations, conditional means, Gaussian channels specified inline, matrix square roots, tensor products, sub-Gaussianity and measurable estimators remain ambient or local binders where appropriate. All required main-text conventions are retained; source review does not certify proofs or the correctness of cited results.'
]
RESOLUTION={
'shared':'A, Lambda and Theta are matrices with dimensions n-by-d, n-by-r and d-by-r. D1-D2 fix their observation law, row priors, independence and fixed-rank/known-parameter scope. A1-A3 give indices, Euclidean/Frobenius norms, probability convergence, positive semidefinite roots, orthogonal groups and generic row draws. d/n tends to infinity for asymmetric results; the symmetric model D11 only has n. Standard conditional expectation, measure laws and their Radon-Nikodym ratios are ambient.',
'3.1':'D3 is the strong model, D5 the second moments and D6 their nonsingular isotropic normalization. Claim 1 uses spectral estimator D7 and subspace loss D8. Claim 2 binds the extra 4+epsilon moment and a Gram-matrix estimator locally. Claim 3 binds the factor estimator and uses D9 distributional identifiability. The numbered extra assumptions are not combined into one blanket hypothesis.',
'3.2':'D3 and D6 fix the model and conventions, while D5 supplies Q_Lambda^(1/2). A4 specifies the independent Gaussian G and prior Theta_0 in the conditional means. The theorem binds arbitrary measurable vector and matrix estimators; a fourth moment of Theta_0 is required only for the second inequality. Risks are normalized by d and d^2 respectively.',
'3.3':'The reference to Theorem 3.1 claim 3 brings D3,D6,D9 and the n,d regime; D5 and A4 resolve the two limiting Gaussian conditional expectations. No spectral estimator or subspace loss is used to state these existence results. Any cumulative moment-scope ambiguity is recorded in the source notes, not resolved by appendix reading.',
'4.1':'D13 and D12 are the two symmetric-model targets, with D11 and D10 their experiment and noise. D14 supplies F and D15 its maximizer. A2,A3,A5 resolve the cone, square root, generic prior variable and independent Gaussian expectation. The countable set is locally bound; s in Q-star(s) is unresolved, and no Theta-law or asymmetric Assumption 4.1 is inserted.',
'4.2':'D4 specifies the weak experiment, D5-D6 the earlier moment conventions. The mean of Theta_0, arbitrary estimators and their null versions are inline/ambient. The fourth moment applies only to the matrix bound. Assumption 4.1 is not invoked, so the prior mean may be nonzero.',
'4.3':'D18 is the defined asymmetric mutual information, under D4 and hence the fixed-prior model D1-D2. D13 is its symmetric counterpart under D11-D10. D17 supplies Assumption 4.1; D25 supplies the explicitly stated Theta normalization via D5. No free-energy limit formula is claimed in this theorem.',
'4.4':'The inherited conditions are D4,D17,D25. D16 and D12 are the two unperturbed risks; D19 defines the extra independent observation and D20 its corresponding risk, using D10 for the added noise. The exception sets, positive epsilon and the nested limit order are local. Neither a mutual-information conclusion nor the unproven continuity condition from A7 is added.',
'4.5':'D4,D17,D25 are inherited conditions, with D16,D12 the two risks. Alternatives (a),(b) bind the dimension sequences and bounded-support condition locally. D21 preserves the complete scalar-channel alternative (c), including its apparent maximum inconsistency. The conclusion has the countable exception expressly attached to (b); the perturbation model and AMP proof constructions are not statement dependencies.',
'5.1':'D22 supplies random centers, uniform one-hot labels and weak model, with identity observation covariance from A6. D23 defines overlap up to a single global label permutation. D24 defines the threshold through D14 at the one-hot prior and Q0. k is fixed with r=k; estimator codomain and measurability are explicit. Part (a) is probability convergence below threshold; part (b) is positive liminf expected overlap above threshold under either growth condition.'
}
def main():
    data=dict(paper_id=PID,scope='Main text only; appendices excluded.',unranked_auxiliary_passages=aux,source_issues=NOTES,statement_resolution=RESOLUTION,branch_resolution={
      '3.1':dict(common='Strong model (4), finite nonsingular moments, Q_Theta=q_Theta I_r, diverging aspect ratio.',claims={'1':'Subspace consistency of the spectral estimator.','2':'Additional Lambda_0 moment of order 4+epsilon; Gram-matrix consistency.','3':'Additional absence of nonidentity orthogonal distributional symmetry; factor consistency.'},scope_note='Further in claim 3 is not silently made to import claim 2; preserve the original and record this scope ambiguity.'),
      '3.2':dict(vector_bound='Common model and moment normalization.',matrix_bound='Additionally E||Theta_0||^4 finite.'),
      '4.1':dict(mutual_information='All q_Theta>=0.',mmse='q_Theta>=0 outside a deterministic countable set; s remains unbound in the printed formula.'),
      '4.2':dict(vector_bound='Common model and normalization, allowing nonzero mean.',matrix_bound='Additionally bounded fourth moment of mu_Theta.'),
      '4.4':dict(first='Unperturbed liminf risk lower bound.',second='Extra independent observation; epsilon->0+ after limsup in n,d.',exception='Each bound states all but countably many q_Theta>0.'),
      '4.5':dict(connective='at least one',a='d n^-3 (log n)^-6 -> infinity',b='d (log d)^(8/5) / n^(6/5) -> 0 and bounded support of mu_Lambda; countable exceptional q_Theta values allowed',c='r=1 and the original scalar-channel maximum/first-stationary-point condition; apparent inconsistency preserved'),
      '5.1':dict(a='Below threshold, every estimator has overlap tending in probability to 1/k.',b='Above threshold and either growth condition, an estimator exists with liminf expected overlap greater than 1/k.',threshold_equality='Not covered.')},
      unresolved_source_references=[
        dict(reference='Appendices A-G',status='excluded_not_opened',reason='All further notation, proofs, AMP constructions and Wasserstein background in appendices remain outside scope.'),
        dict(reference='Theorem 4.1, Q-star(s)',status='source_ambiguity_preserved',reason='The theorem leaves s unbound; the likely squared-signal substitution is not inserted.'),
        dict(reference='Theorem 4.5(c)',status='source_inconsistency_preserved',reason='Printed global maximum conflicts with the displayed positive quadratic plus nonnegative mutual information on an unbounded domain.'),
        dict(reference='Theorem 3.1 claim 3 and Theorem 3.3',status='source_scope_ambiguity_preserved',reason='The numbered further assumptions and absent explicit Theta fourth moment are retained without imposing extra hypotheses.'),
        dict(reference='[LM19], Corollary 42 and Proposition 43',status='external_not_imported',reason='The complete restatement is preserved as Theorem 4.1; external source hypotheses or corrections are not substituted.')])
    (ROOT/'ambient-prerequisites.json').write_text(json.dumps(data,indent=2,ensure_ascii=False)+'\n')
if __name__=='__main__':main()
