"""Preserve original model context, conditional scope and source ambiguities."""
import json
from save_inventory import ROOT,PID

def main():
    aux=[]
    def add(n,s,pages,note,deps=()):aux.append(dict(local_id='A'+str(n),statement_original=s,evidence=[dict(page=p,location='Original main-text context A'+str(n)) for p in pages],scope_note=note,depends_on=list(deps)))
    add(1,r'''We are interested in the asymptotic behavior of estimators when $n\to\infty$, $T\to\infty$, and $\rho\to0$. It is perhaps the easiest to relate $L$ and $\rho$ to $n$ by considering sequences $(T_n,\rho_n)_{n=1}^\infty$, which makes it more natural to write the corresponding mixture model sequence $P_{1,n}=P_1(n,T_n,\rho_n)$, and $P_{0,n}=P_0(n,T_n,\rho_n)$ as in Definition 1.''',[5],'Source sequence convention, retaining the stray L in the prose. Assumption1 is explicitly invoked by Conjecture3.2 and Theorems3.3/4.2; Theorems3.1/4.1 state their own sufficient threshold conditions without that numbered reference.',['D4','D5','D9'])
    add(2,r'''Lemma 2.1 (Detection implies recovery). Under the MLSBM specified in Definition 1, if $P_{1,n}$ is asymptotically recoverable for a sequence $(T_n,\rho_n)$, then it is distinguishable for $(T_n+2,\rho_n)$ with polynomial additional computing time.''',[5],'The caption reverses the implication actually stated: recovery implies detection, with two additional layers. The main-text discussion says this change does not affect the considered asymptotic thresholds. Preserve the direction and layer change; do not add a sixth Theorem or an implication-only definition edge.',['D7','D8','D14'])
    add(3,r'''As detailed in the proof, the exponent of $-1.4$ can be improved to $-1.01$ if $T_n\gg\log^{2.02}n$. Here the notion of “polynomial-time” means polynomial in $n$, because when $\rho_n$ satisfies Assumption 1, the condition $nT_n^{1/2}\rho_n\le(1/2)(\log n)^{1.4}$ implies $T_n=O(n^2)$ and hence the total size of $A$ is polynomial in $n$.''',[8],'Prose following Theorem3.3, not part of its italic theorem statement. It prints a positive log exponent in the input-size explanation, unlike the theorem’s negative exponent; preserve and flag that discrepancy. The improved threshold requires an extra layer-growth condition and is not inserted into the theorem.',['D9','D14'])
    add(4,r'''The original version of the conjecture in [20] is more general and requires various forms of regularity conditions. These conditions can be directly verified for our MLSBM sequence $(P_{0,n},P_{1,n})_{n\ge1}$ specified in Definition 1 with $(T_n,\rho_n)$ satisfying Assumption 1.''',[8],'Remark1 asserts applicability of the externally cited conjecture’s regularity conditions. The main text does not enumerate those conditions; the current census preserves the specialized Conjecture3.2 and does not certify the external assertion.',['D4','D5','D9','D10'])
    add(5,r'''Recall that for two sequences of probability distributions, $(P_{0,n},P_{1,n})_{n\in\mathbb N}$, over a common sequence of measurable spaces, we say $P_{1,n}$ is contiguous to $P_{0,n}$, if for any sequence of events $(E_n:n\ge1)$, $P_{0,n}(E_n)\to0$ implies $P_{1,n}(E_n)\to0$.''',[8],'Contiguity is explanatory context in Remark2, not a premise of Theorems2.2 or3.3 and not the same as vanishing chi-square divergence. Do not add it as a dependency simply because it motivates low-degree hardness.')
    add(6,r'''the computation thresholds for detection and recovery in the multi-layer stochastic block model. The computational upper bound for recovery (and hence detection) has been studied in [28, 29], in which a variant of spectral clustering was proved to consistently recover the membership when $nT_n^{1/2}\rho_n\gtrsim O(\sqrt{\log(n)})$.''',[6,7],'External algorithmic provenance for Theorem3.1; the main text does not give the algorithm’s complete construction. Preserve the theorem’s existence statement and exact threshold without inventing a local spectral-estimator definition.',['D7','D8','D14'])
    add(7,r'''These two priors can be changed to the corresponding Bernoulli models (i.e., $\sigma(i)\overset{\mathrm{iid}}\sim\operatorname{Bernoulli}(1/2)$) with additional bookkeeping.''',[5],'Discussed alternative priors, not the exact balanced priors in Definition1. No new theorem or mathematically equivalent prior variant is inferred.',['D2','D4'])
    add(8,r'''Unlike the MLE considered in Section 4.2, the bias-adjusted spectral method works for a more general class of MLSBMs, allowing $B_t$ to vary arbitrarily as long as $T_n^{-1}\rho_n^{-2}\sum_tB_t^2\succeq cI$ for some positive constant $c$. It would be interesting to develop a corresponding method for the information-theoretic upper bound that works for such more general MLSBMs.''',[12],'Discussion of broader models and future work. The theorems here are for the special balanced mixture; do not transfer their information-theoretic conclusions to arbitrary layer matrices.',['D1','D13'])
    issues=[]
    def issue(i,pages,note):issues.append(dict(issue_id=i,evidence=[dict(page=p,location='Source scope or notation issue') for p in pages],note=note))
    issue('joint-versus-observation-marginals',[4,5,10],'P1,n is explicitly called the joint law of (A,sigma,tau), and P1,tau,n the conditional joint law of (A,sigma). Testing and chi-square formulas instead use their A marginals, as the explicit sum over A demonstrates. The null law is on A only. Preserve the original notation while keeping the sample spaces separate.')
    issue('balanced-priors-and-conditional-independence',[4,5],'Uniform priors are on exactly balanced node and layer assignments, not iid Bernoulli labels. The generative list gives separate prior draws without explicitly writing their independence; the natural product-prior interpretation is recorded as such. Edge independence holds conditional on latent assignments, not under their marginal mixture.')
    issue('binary-labels-and-observation-domain',[3,4,5,11],'The general model uses labels in [K], then the K=2 specialization uses {0,1}. Edges are observed only for i<j, with symmetric matrices and no modeled self-loops. The MLE parity sum inherits those index ranges. Recovery is invariant to the global node-label complement.')
    issue('asymptotic-integer-and-boundary-regimes',[4,6],'Both n and T must be even, while Theorem2.2 writes T_n=n^a for arbitrary a>0. Appropriate subsequences or rounding are implicit. Its inequalities are strict and make no claim on 1+a−b=0 or1+a/2−b=0. Assumption1 is stronger than just rho_n→0, and threshold limits nT rho and n sqrt(T) rho must remain distinct.')
    issue('conditional-computational-hardness',[6,7,8],'The computational impossibility statements depend on the specialized low-degree polynomial conjecture. The conjecture tests uniform boundedness over all centered null-L2-normalized polynomials of degree at most log^1.01(n); boundedness for a single polynomial is insufficient. It is not a proved impossibility theorem or P-versus-NP result.')
    issue('recovery-and-detection-strength',[5,6,10,11],'Recoverability means vanishing normalized Hamming fraction in probability under the mixture prior, not exact recovery or a uniform fixed-label minimax guarantee. Distinguishability means vanishing total testing error. Failure of that property alone does not imply failure of every weak test; Theorem4.1 separately establishes the stronger vanishing chi-square result.')
    issue('recovery-detection-lemma-caption',[5,6],'Lemma2.1 is captioned Detection implies recovery, but its actual statement is recovery implies detection with T_n+2 layers and polynomial extra work. The source says the two-layer change is negligible for its threshold regimes. No reversed reduction or same-finite-T identity is inserted.')
    issue('chi-square-pmf-naming',[10],'The prose assigns q,p to P,Q respectively, while the displayed d_chi2(Q,P)=E_P[(q/p−1)^2] requires q for Q and p for P. Preserve the printed mismatch and use the theorem’s explicit null-denominator formula to identify the intended direction. P0 has positive mass on every observed tensor when0<rho<2/3.')
    issue('conditional-layer-quantifier',[10],'Theorem4.1 quantifies over every balanced tau in S_Tn while summing the A-marginal likelihood ratio. It keeps sigma unobserved even when tau is known. Balanced layer permutations make these cases symmetric; do not reinterpret the claim as observing both sigma and tau.')
    issue('runtime-logarithm-sign',[8],'Theorem3.3 has threshold (1/2)(log n)^−1.4, but the following runtime explanation prints exponent+1.4. Its claimed T_n=O(n²) does not follow from that weaker positive-exponent condition alone; the actual negative-exponent theorem condition does support polynomial input size. Preserve both passages and the distinct optional −1.01 improvement. The n-based runtime convention is stated in the lower-bound discussion; its relation to input-size complexity for unrestricted layer growth in the upper-bound result is not fully specified locally.')
    issue('mle-domain-and-ties',[11],'Equation(4) jointly optimizes balanced sigma and tau by counting edges on even-parity triples. A choice among ties is not specified. Theorem4.2 asserts approximate consistency for sigma only; it supplies neither a polynomial-time implementation nor a claim of consistent tau recovery.')
    issue('external-spectral-and-conjecture-details',[7,8,12],'Theorem3.1 credits[28] and refers to an externally developed spectral method without defining it completely. Remark1 claims external conjecture regularity can be verified but does not list it. Retain these source limitations; neither missing implementation details nor a conjecture becomes an invented locally verified API.')
    bindings={
      'T2.2':dict(parameters='T_n=n^a, rho_n=n^−b, a>0,0<b<2; positive even dimensions implicit.',objects=['D4','D7','D8','D10','D14'],branches={'information_theoretic':'No computational constraint; strict sign of1+a−b. No conjecture premise.','computational':'Conjecture3.2 is assumed in the second bullet; strict sign of1+a/2−b. The credited computational upper result3.1 is itself unconditional.'},boundary_cases='Both equality boundaries are unstated.'),
      'T3.1':dict(parameters='n*sqrt(T_n)*rho_n≥C*sqrt(log n), some absolute C>0; Definition1 model and source sequence context.',objects=['D4','D7','D14'],conclusion='Existence of a polynomial-time recovery algorithm; its full construction is external, not reconstructed from a name.'),
      'T3.3':dict(parameters='Definition1 model; Assumption1 and Conjecture3.2; negative-log threshold eventually.',objects=['D4','D5','D8','D9','D10','D14'],conclusion='Conditional impossibility of strong polynomial-time detection. Main-text optional exponent improvement is not part of the original theorem statement.'),
      'T4.1':dict(parameters='Definition1 observation experiment; n*T_n*rho_n→0; every balanced tau.',objects=['D2','D4','D5','D8','D11','D12'],conclusion='Known-tau alternative A-marginal chi-square tends to zero; then mixed alternative chi-square tends to zero and strong detection fails. No hardness conjecture.'),
      'T4.2':dict(parameters='Definition1 and Assumption1; n*T_n*rho_n→infinity.',objects=['D4','D5','D6','D7','D8','D9','D13'],conclusion='Joint-MLE sigma component has vanishing normalized Hamming fraction for every epsilon>0, hence asymptotic recovery and detection. No polynomial runtime assertion or tau-consistency conclusion.')}
    refs=[dict(claim_id=PID+'/T2.2',reference='low-degree polynomial conjecture',reference_kind='assumption_reference',resolution='D10, Conjecture3.2, for the computational bullet only; not a premise of the information-theoretic bullet.'),dict(claim_id=PID+'/T3.1',reference='Computational upper bound[28]',reference_kind='external_result_reference',resolution='Existential algorithm result with spectral provenance A6; its full algorithm is not defined in the main text.'),dict(claim_id=PID+'/T3.3',reference='Conjecture3.2 and Assumption1',reference_kind='assumption_reference',resolution='D9,D10, preserving uniform low-degree polynomial quantifiers and the conjectural implication.'),dict(claim_id=PID+'/T4.1',reference='conditional P1,tau,n and chi-square definition',reference_kind='definition_reference',resolution='D11,D12; explicit theorem sum uses the A marginals.'),dict(claim_id=PID+'/T4.2',reference='Assumption1',reference_kind='assumption_reference',resolution='D9 in addition to n*T_n*rho_n→infinity.'),dict(claim_id=PID+'/T4.2',reference='Definition2 and MLE(4)',reference_kind='definition_reference',resolution='D6–D8 and D13 preserve loss, recovery/detection and the joint maximization.'),dict(claim_id=PID+'/T4.2',reference='Lemma2.1 recovery-to-detection reduction',reference_kind='proof_only',resolution='A2 preserves its direction and two-layer change; this implication does not create a definition edge between recovery and detection.'),dict(claim_id=PID+'/T3.3',reference='Lemma3.4 projected likelihood and subsequent proof lemmas',reference_kind='proof_only',resolution='Proof machinery is not a new statement assumption. No projected-likelihood or combinatorial-moment API is imported into the theorem dependency graph.')]
    data=dict(paper_id=PID,unranked_auxiliary_passages=aux,source_issues=issues,statement_local_bindings=bindings,source_claim_references=refs,ambient_conventions=['Finite labeled graph tensors, Bernoulli laws, uniform distributions on finite sets, Hamming distance, conditional probabilities, polynomial degree and ordinary limits are ambient mathematical objects; no mathlib availability is assessed.','The observed data are A only. Joint and marginal uses of P1 symbols are distinguished by their arguments; all testing errors and likelihood-ratio sums are on the common A sample space.','Unconditional information-theoretic results, conjecture-dependent computational impossibility and externally credited algorithm existence remain separate. Source review is not proof certification.'])
    (ROOT/'ambient-prerequisites.json').write_text(json.dumps(data,indent=2,ensure_ascii=False)+'\n')
if __name__=='__main__':main()
