"""Attach source-reviewed theorem-to-interface paths and finalize this paper."""
import copy,json,subprocess,sys
from pathlib import Path
from extract_interfaces import ROOT,PID,interfaces,members,edges
SKILL=Path('skills/statistical-paper-census/scripts');sys.path.insert(0,str(SKILL))
from canonical_dependencies import canonical_dependencies
from census_metrics import derive_metrics
from publication_contract import attach_inventory
DIRECT={
'2.7':{
'D1':'The active manifold, its local defining equations G=0 and tangent space use the embedded-manifold convention from Section 2.1.',
'D2':'The matrix Sigma is defined using orthogonal projection onto the tangent space at x-bar.',
'D4':'The hypothesis explicitly requires -A(x-bar) to belong to the regular subdifferential of f.',
'D5':'The displayed set-valued F is A plus the limiting subdifferential of f.',
'D6':'The opening assumes a Cp+1 active manifold for f at the specified regular subgradient.',
'D7':'The opening requires f to be subdifferentially continuous near x-bar.',
'D8':'The equivalence concerns Cp invertibility with local inverse sigma from Definition 2.6; the source prints the reversed basepoint order (0,x-bar).',
'D9':'The opening names the set-valued map F, whose inverse is localized in the conclusion.'},
'3.1':{
'D8':'The first displayed formula explicitly identifies the graph of the C1 local inverse sigma.',
'D9':'The localization formula uses the inverse graph of the set-valued F.',
'D10':'The limiting covariance uses the stochastic map A(x-bar,z) and the samples have its baseline law P.',
'D11':'The first sentence invokes Assumption A, identifying F=A+H and its local inverse.',
'D12':'The first sentence invokes the two integrability and differentiability conditions of Assumption B.',
'D13':'The selected x_k solves the empirical inclusion (3.2) for the iid sample S.'},
'3.2':{
'D8':'The limiting Gaussian covariance uses the Jacobian of the local solution map sigma from Assumption A.',
'D10':'The covariance is that of A(x-bar,z) under the baseline population law from (3.1).',
'D11':'The first sentence expressly assumes the smooth localization in Assumption A.',
'D12':'The first sentence expressly assumes Assumption B, without the extra Lipschitz-Jacobian condition of Theorem 3.1.',
'D15':'The supremum ranges over B_(c/k), with the perturbed center x-bar_P-prime defined in its admissibility condition.'},
'5.1':{
'D1':'The coercivity bound quantifies over the tangent space of the manifold, and the final matrix uses that space.',
'D2':'The final pseudoinverse formula uses the orthogonal tangent-space projectors.',
'D3':'Both the coercivity condition (5.1) and the final derivative formula use the covariant Jacobian of F_M.',
'D8':'The conclusion asserts Cp smooth invertibility at (x-bar,0), with the displayed local inverse sigma.',
'D16':'The theorem concerns the fixed solution x-bar of the abstract inclusion (4.1) and its map F.',
'D17':'The first sentence invokes Assumption C and uses its single-valued tangent reduction F_M.',
'D18':'The assumed convergent sequence is generated by the generalized update (4.2).',
'D19':'The first sentence invokes the uniform steplength bound in Assumption D.',
'D20':'The first sentence invokes both tangent comparison and proximal aiming from Assumption E.',
'D21':'The first sentence invokes Assumption I; the theorem further restricts its exponent to gamma<1.',
'D22':'The first sentence invokes Assumption J and its noise covariance Sigma in the limiting Gaussian; the tangent-coordinate mismatch is preserved in the source notes.'}
}
def main():
    import extract_interfaces
    extract_interfaces.ROOT=ROOT
    extract_interfaces.main()
    inv=json.loads((ROOT/'theorem-inventory.json').read_text());data=copy.deepcopy(inv)
    data['schema_version']='statistical-ranked-interfaces-v4'
    data['scope'].update(paper_count=1,
        source_policy='Verified registered arXiv:2301.06632v1 PDF, 47 pages; pages 1-25 and references above Appendix A on page 26 only.',
        normalization_policy='Preserve all four original Theorems 2.7, 3.1, 3.2 and 5.1, complete hypotheses and conclusions. Keep source coordinate, regularity and notation issues separate from the quotations.',
        semantic_ranking_policy='Resolve manifold and subdifferential definitions, local smooth invertibility, population and empirical inclusions, local law perturbations, and abstract stochastic-update assumptions. Do not import special algorithms, active-manifold sharpness into Assumption C, or Theorem 3.1 assumptions into Theorem 3.2.',
        build_order_policy='Derive all edges and reach from the original local dependency graph; keep the independent theorem inventory unchanged.')
    data['interfaces']=copy.deepcopy(interfaces);claims={c['claim_id']:c for c in data['claims']}
    assert set(DIRECT)=={c['claim_id'].split('/T')[-1] for c in data['claims']}
    for c in data['claims']:
        n=c['claim_id'].split('/T')[-1];c['depends_on']=list(DIRECT[n])
        for x in data['interfaces']:
            lid=x['members'][0]['local_id']
            if lid in DIRECT[n]:
                evidence=list(c['evidence'])
                evidence.extend(e for e in members[lid]['evidence'] if e not in evidence)
                x['central_claim_uses'].append(dict(use_id=c['claim_id']+'-'+lid,paper_id=PID,claim_id=c['claim_id'],use_kind='statement_dependency',reason=DIRECT[n][lid],evidence=evidence))
    derived=canonical_dependencies(data)
    for x in data['interfaces']:x['dependencies']=derived[x['interface_id']]
    derive_metrics(data)
    for x in data['interfaces']:
        for r in x['related_theorems']:
            cid=r['claim_id'];path=r['via_local_ids'];n=cid.split('/T')[-1]
            sentences=[DIRECT[n][path[0]]];evidence=list(claims[cid]['evidence'])
            for lid in path:evidence.extend(e for e in members[lid]['evidence'] if e not in evidence)
            for a,b in zip(path,path[1:]):sentences.append(edges[a][b])
            x['theorem_explanations'][cid]=dict(paper_id=PID,via_local_ids=path,text=' '.join(sentences),evidence=evidence)
        for m in x['members']:
            own=m['statement_original']+' '+m['local_label']
            linked=own+' '+' '.join(claims[r['claim_id']]['statement_original'] for r in x['related_theorems'])
            selectors=m['highlight_symbols']+m['highlight_phrases']
            assert any(s in own for s in selectors),(m['local_id'],'missing source highlight')
            assert all(s in linked for s in selectors),(m['local_id'],'unmatched selector')
    attach_inventory(data,ROOT/'theorem-inventory.json',ROOT/'ranked-interfaces.json')
    (ROOT/'unfinalized-census.json').write_text(json.dumps(data,indent=2,ensure_ascii=False)+'\n')
    subprocess.run([sys.executable,str(SKILL/'finalize_census.py'),str(ROOT/'unfinalized-census.json'),str(ROOT/'ranked-interfaces.json'),'--inventory',str(ROOT/'theorem-inventory.json')],check=True)
    subprocess.run([sys.executable,str(SKILL/'validate_census.py'),str(ROOT/'ranked-interfaces.json')],check=True)
    print('Structural validation passed; independent full source audit remains pending.')
    finalized=json.loads((ROOT/'ranked-interfaces.json').read_text())
    passages=dict(paper_id=PID,members=[m for x in finalized['interfaces'] for m in x['members']])
    (ROOT/'source-passages.json').write_text(json.dumps(passages,indent=2,ensure_ascii=False)+'\n')

if __name__ == "__main__":
    main()
