"""Regenerate the complete manually transcribed main-text theorem inventory."""
import argparse,hashlib,json,subprocess,sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
REPO=next(p for p in ROOT.parents if (p/'scripts/resolve_paper_pdf.py').is_file())
PID='aos-2024-v52-i04-p1485'
SHA='32e48d4bfd9b0520b093cc0a28210a96c57548b0b696b2cdb5451defa86fb6a3'
claims=[]
def claim(number,page,title,text):
    claims.append(dict(claim_id=f'{PID}/T{number}',paper_id=PID,claim_kind='theorem',label=f'Theorem {number} ({title})',source_order=len(claims)+1,statement_original=text.strip(),evidence=[dict(page=page,location=f'Theorem {number}, complete original statement')]))
claim('2.7',12,'Smooth Invertibility and Active Manifolds',r'''
Consider the set-valued map
\[
F(x):=A(x)+\partial f(x),
\]
where $A:\mathbb R^d\to\mathbb R^d$ is $C^p$-smooth and $f:\mathbb R^d\to\mathbb R\cup\{\infty\}$ is subdifferentially continuous near a point $\bar x$. Suppose that $f$ admits a $C^{p+1}$ active manifold $\mathcal M$ at some point $\bar x$ for $-A(\bar x)\in\widehat\partial f(\bar x)$. Let $G(x)=0$ be any $C^{p+1}$-smooth local defining equations for $\mathcal M$ near $\bar x$ and let $\widehat f$ be any $C^{p+1}$-smooth function that agrees with $f$ on a neighborhood of $\bar x$ in $\mathcal M$. Define the map
\[
\mathcal H(x,y):=A(x)+\nabla\widehat f(x)+\nabla G(x)^\top y.
\]
Then there exists a unique multiplier vector $\bar y$ satisfying the condition $0=\mathcal H(\bar x,\bar y)$. Moreover, $F$ is $C^p$-invertible around $(0,\bar x)$ with inverse $\sigma(\cdot)$ if and only if the matrix
\[
\Sigma:=P_{T_{\mathcal M}(\bar x)}\nabla_x\mathcal H(\bar x,\bar y)P_{T_{\mathcal M}(\bar x)}
\]
is nonsingular on $T_{\mathcal M}(\bar x)$, and in this case equality $\nabla\sigma(0)=\Sigma^\dagger$ holds.
''')
claim('3.1',13,'Sample average approximation',r'''
Suppose that Assumptions A and B hold. In particular, there exist $\epsilon_1,\epsilon_2>0$ and a $C^1$-smooth map $\sigma:B_{\epsilon_1}(0)\to B_{\epsilon_2}(\bar x)$ satisfying
\[
\operatorname{gph}\sigma=(B_{\epsilon_1}(0)\times B_{\epsilon_2}(\bar x))\cap\operatorname{gph}F^{-1}.
\]
Suppose moreover that there exists a square integrable function $L(z)$ satisfying
\[
\|\nabla A(x_1,z)-\nabla A(x_2,z)\|\le L(z)\|x_1-x_2\|\qquad\forall x_1,x_2\in B_{\epsilon_2}(\bar x).\tag{3.3}
\]
Shrinking $\epsilon_2$, if necessary, let us ensure that $\epsilon_2\le\min\left\{\frac{\operatorname{lip}(\sigma)^{-1}}{2\mathbb E L},\sqrt{\frac{\epsilon_1}{2\mathbb E L}}\right\}$. Let $S=\{z_1,\ldots,z_k\}$ be i.i.d samples drawn from $\mathcal P$ and let $x_k$ be a measurable selection of the solutions (3.2) such that $\Pr[x_k\in B_{\epsilon_2}(\bar x)]\to1$ as $k$ tends to infinity. Then asymptotic normality holds:
\[
\sqrt k(x_k-\bar x)\xrightarrow D\mathsf N\left(0,\nabla\sigma(0)\cdot\operatorname{Cov}(A(\bar x,z))\cdot\nabla\sigma(0)^\top\right).
\]
''')
claim('3.2',14,'Asymptotic optimality',r'''
Suppose that Assumption A and B hold. Let $\mathcal L:\mathbb R^d\to[0,\infty)$ be any symmetric, quasiconvex, and lower semicontinuous function, and let $\widehat x_k:\mathcal Z^k\to\mathbb R^d$ be a sequence of estimators. Then the inequality
\[
\lim_{c\to\infty}\liminf_{k\to\infty}\sup_{\mathcal P'\in\mathcal B_{c/k}}\mathbb E_k^{\mathcal P'}\left[\mathcal L\left(\sqrt k(\widehat x_k-\bar x_{\mathcal P'})\right)\right]\ge\mathbb E[\mathcal L(Z)]
\]
holds, where $Z\sim\mathsf N\left(0,\nabla\sigma(0)\cdot\operatorname{Cov}(A(\bar x,z))\cdot\nabla\sigma(0)^\top\right)$.
''')
claim('5.1',20,'Asymptotic Normality',r'''
Suppose that Assumption C, D, E, I, and J hold. Suppose that $\gamma\in(\frac12,1)$ and that the sequence $x_k$ generated by the process (4.2) converges to $\bar x$ with probability one. Suppose that there exists a constant $\mu>0$ satisfying
\[
\langle\nabla_{\mathcal M}F_{\mathcal M}(\bar x)v,v\rangle\ge\mu\|v\|^2\qquad\text{for all}\qquad v\in T_{\mathcal M}(\bar x).\tag{5.1}
\]
Then $F$ is $C^p$-smoothly invertible around $(\bar x,0)$ with inverse $\sigma(\cdot)$ and the average iterate $\bar x_k=\frac1k\sum_{i=1}^k x_i$ satisfies
\[
\sqrt k(\bar x_k-\bar x)\xrightarrow D N\left(0,\nabla\sigma(0)\cdot\Sigma\cdot\nabla\sigma(0)^\top\right).
\]
Moreover, $\nabla\sigma(0)$ can be equivalently written as $\nabla\sigma(0)=(P_{T_{\mathcal M}(\bar x)}\nabla_{\mathcal M}F_{\mathcal M}(\bar x)P_{T_{\mathcal M}(\bar x)})^\dagger$.
''')
def main():
    source=Path(subprocess.check_output([sys.executable,str(REPO/'scripts/resolve_paper_pdf.py'),PID],text=True).strip())
    assert hashlib.sha256(source.read_bytes()).hexdigest()==SHA
    paper=dict(paper_id=PID,title='Asymptotic normality and optimality in nonsmooth stochastic approximation',authors=['Damek Davis','Dmitriy Drusvyatskiy','Liwei Jiang'],version='arXiv:2301.06632v1, 16 January 2023',source_url='https://arxiv.org/pdf/2301.06632v1',pdf_pages=47,pdf_sha256=SHA,main_text_last_pdf_page=26,main_text_boundary=dict(location='Main text and references end after [37] on PDF page 26, before Appendix A (Proofs from Section 2) beginning at y=489.0146179199219 PDF points. Only the upper part of page 26 is admitted.',shared_page_with_appendix=True),intake_review=dict(status='complete',theorem_ids=[c['claim_id'] for c in claims],zero_theorems_confirmed=False))
    data=dict(schema_version='statistical-theorem-inventory-v1',scope=dict(theorem_scope='main_text_only',source_policy='Verified registered arXiv v1 PDF, main-text pages 1-25 and reference portion of page 26; appendix bodies excluded.'),papers=[paper],claims=claims)
    ROOT.mkdir(parents=True,exist_ok=True);(ROOT/'theorem-inventory.json').write_text(json.dumps(data,indent=2,ensure_ascii=False)+'\n')
if __name__=='__main__':
    p=argparse.ArgumentParser(description=__doc__);p.add_argument('--output-dir',type=Path);a=p.parse_args()
    if a.output_dir:ROOT=a.output_dir.resolve()
    main()
