"""Preserve source conventions and computation context without adding proof dependencies."""
import json
from save_inventory import ROOT,PID

def main():
    aux=[]
    def add(n,s,pages,note,deps=()):aux.append(dict(local_id='A'+str(n),statement_original=s,evidence=[dict(page=p,location='Original main-text context A'+str(n)) for p in pages],scope_note=note,depends_on=list(deps)))
    add(1,r'''One can verify that the correlation coefficient $\rho$ between two Bernoulli random variables with parameter $q$ takes values in $[-\min\{\frac q{1-q},\frac{1-q}q\},1]$. While most of previous work focuses on the positively correlated case, in this paper we allow negative correlation.''',[2],'Source footnote restricts feasible negative correlation; rho²>alpha does not override this domain. Conditional edge-pair independence and a uniform latent permutation are in D1.',['D1'])
    add(2,r'''We say a test statistic $f(G_1,G_2)$ with threshold $\tau\in\mathbb R$ achieves consistent detection if the sum of type I and type II errors converges to $0$ as $n\to\infty$, that is,
\[
\lim_{n\to\infty}[\mathcal Q(f(G_1,G_2)\ge\tau)+\mathcal P(f(G_1,G_2)<\tau)]=0.
\]
(1)''',[3],'Definition uses a strict alternative-side inequality, while Theorems1/2 use ≤ on that side. Their displayed bound is conservative at equality and implies the definition; retain both original forms. The theorem formulas bind the error events directly, so this explanatory definition is not a required additional graph edge.',['D2'])
    add(3,r'''We define $\operatorname{sub}(H,G)$ as the number of subgraphs in $G$ that are isomorphic to $H$, i.e., $\operatorname{sub}(H,G)\triangleq\sum_{H'\subset G}\mathbf1_{\{H'\cong H\}}$.
\[
\operatorname{sub}_n(H)\triangleq\operatorname{sub}(H,K_n)=\binom n{|V(H)|}\frac{|V(H)|!}{\operatorname{aut}(H)},
\]
(2)
For each subset $S\subset\binom{[n]}2$, we identify it with an (edge-induced) subgraph of $K_n$.
Throughout the paper, unless otherwise stated, all subgraphs are edge-induced subgraphs and contain no isolated vertices.''',[5,8],'Separate source passages establish the ambient copy-count and no-isolated-vertices conventions. The embedding formula is not substituted for W_H or imported as a theorem assumption. A tree with K edges has K+1 vertices; counts run over edge-set copies, not all labeled maps.',['D3','D5','D6'])
    add(4,r'''For two real numbers $a$ and $b$, we let $a\vee b\triangleq\max\{a,b\}$ and $a\wedge b\triangleq\min\{a,b\}$. We use standard asymptotic notation: For two sequences $\{a_n\}$ and $\{b_n\}$ of positive numbers, we write $a_n=O(b_n)$, if $a_n\le Cb_n$ for an absolute constant $C$ and for all $n$; $a_n=\Omega(b_n)$, if $b_n=O(a_n)$; $a_n=\Theta(b_n)$, if $a_n=O(b_n)$ and $a_n=\Omega(b_n)$; $a_n=o(b_n)$ or $b_n=\omega(a_n)$, if $a_n/b_n\to0$ as $n\to\infty$.''',[5],'The max symbol in the denominator of(7) must not be read as a min, addition or a logical disjunction. K is an integer sequence tending to infinity; q may vary with n. No uniform result for rho approaching the Otter threshold is explicitly formulated.',['D10'])
    add(5,r'''Proposition 3. Suppose that (7) holds. Then as $n\to\infty$, under both $\mathcal P$ and $\mathcal Q$,
\[
\frac{\widetilde f_{\mathcal T}-f_{\mathcal T}}{\mathbb E_{\mathcal P}[f_{\mathcal T}]}\xrightarrow{L_2}0.
\]
(33)''',[16],'Approximation-error control used to prove Theorem2, not a third Theorem or a new input assumption. It normalizes by the alternative mean of the exact statistic, not by the random statistic itself. The proof is deferred to an appendix that is excluded from this audit.',['D2','D8','D10','D14'])
    add(6,r'''Algorithm 1 Computation of test statistic via color coding
1: Input: Centered adjacency matrices $\overline A$ and $\overline B$, correlation coefficient $\rho$, and an integer $K$.
2: Apply the constant-time free tree generation algorithm in [Din15, WROM86] to list all non-isomorphic unrooted unlabeled trees with $K$ edges and return $\mathcal T$.
3: For each $[H]\in\mathcal T$, compute $\operatorname{aut}(H)$ by algorithm in [CB81].
4: Generate i.i.d. random colorings $\{\mu_i\}_{i=1}^t$ and $\{\nu_i\}_{i=1}^t$ mapping $[n]$ to $[K+1]$.
5: for each $i=1,\ldots,t$ do
6: For each $H\in\mathcal T$, compute $X_H(\overline A,\mu_i)$ and $X_H(\overline B,\nu_i)$ via Algorithm 2 given in Section 4.1.
7: end for
8: Compute $Y_{\mathcal T}(A,B)$ according to (31).
9: Output: $Y_{\mathcal T}(A,B)$.''',[16],'Computation provenance for Theorem2. Algorithm1 outputs Y_T; the tested approximation is beta/r² times that output. Tree generation and automorphism routines are cited externally; Algorithm2 is the main-text weighted dynamic-programming subroutine. These implementation/proof details do not become prerequisites of the explicit mathematical sum defining tilde-f.',['D3','D4','D5','D12','D13','D14'])
    add(7,r'''Proposition 4. Algorithm 1 computes $Y_{\mathcal T}(A,B)$ in time $O(n^2(3e/\alpha)^K)$, where $\alpha$ is Otter's constant in (6). Furthermore, under condition (7), the time complexity reduces to $n^{2+o(1)}$.''',[16],'Proposition4 supplies computational provenance for Theorem2, not an additional inventoried theorem. Under(7), exponential dependence on K becomes subpolynomial in n. The source counts weighted arithmetic operations without specifying precision/bit complexity.',['D9','D10','D14'])
    add(8,r'''Then $\mathbb E[X_H(M,\mu)\mid M]=rW_H(M)$, where $W_H(M)$ is defined in (5). Hence, $X_H(M,\mu)/r$ is an unbiased estimator of $W_H(M)$.''',[15],'Conditional-on-host-graph expectation clarifies that colorings are independent auxiliary randomness. The definition of X_H uses colorful edge-set copies; unbiasedness is a property, not a new theorem assumption or an implication edge.',['D6','D12','D13'])
    issues=[]
    def issue(i,pages,note):issues.append(dict(issue_id=i,evidence=[dict(page=p,location='Source scope or notation issue') for p in pages],note=note))
    issue('registered-version-and-main-boundary',[1,2,22],'The source is arXiv:2110.11816v2, marked2 Apr2022, with cover dated April5,2022. The repository entry belongs to the 2024 journal corpus but this is the pinned inspected version. Acknowledgment and numerical discussion end on shared page22, clipped at y565 before AppendixA at y574.126.')
    issue('latent-mixture-and-correlation-domain',[2,3],'The alternative observation law averages a uniform latent permutation. Aligned edge pairs are iid only conditional on that permutation; the two observed graphs are not independent under the alternative. Negative correlation is allowed only within the Bernoulli feasibility interval, despite the squared correlation threshold.')
    issue('signed-counts-and-copy-multiplicity',[4,5,6,8],'W_H multiplies centered edge weights within each edge-set copy. This differs from subtracting the expectation of a raw unsigned subgraph count. The sum uses one copy per subgraph, the outer sum uses one unrooted isomorphism class, and aut(H) supplies an explicit separate weight. Edge-induced subgraphs have no isolated vertices; do not replace them by vertex-induced copies or labeled injections.')
    issue('parameter-and-tree-size-scope',[5,6,7],'q is strictly between0 and1 and the tree size K is an integer with K+1 vertices. Condition(7) requires K→infinity but at most a logarithmic bound with a maximum in its denominator. The sparsity condition is symmetric under q↔1−q. The source states rho²>alpha but does not formulate uniformity for an n-dependent gap shrinking to zero; no boundary-equality claim is inferred.')
    issue('threshold-and-inequality-conventions',[3,6,7],'Definition(1) uses P(f<tau); the two theorem displays use P(f≤tau) while retaining Q(f≥tau). Their bound includes ties on both sides and is sufficient for the strict-event detection definition. Theorem2 inherits tau=C*rho^(2K)*|T| from Theorem1, with fixed0<C<1; it does not use the approximate statistic’s empirical mean or a bootstrap threshold.')
    issue('algorithmic-randomness-in-laws',[3,7,15,16],'P and Q initially name graph-pair laws, but tilde-f also depends on2t independent random colorings. Theorem2 suppresses this extra randomness in its arguments and probability notation. Its natural interpretation extends each data law by the same independent coloring distribution, not a guarantee conditional on every fixed coloring or a data-adaptive coloring scheme.')
    issue('independent-coloring-averages',[15,16],'The approximation uses t=ceil(1/r), two independent arrays of t colorings, and the product of the two sample averages. Arrays are shared across tree classes. Replacing this by the average of t paired products, sharing one coloring array across graphs, omitting a factor r, or resampling edges changes the statistic.')
    issue('scaling-and-algorithm-output',[5,6,15,16],'Algorithm1 outputs Y_T, while Theorem2 tests tilde-f_T=beta*Y_T/r². Beta has sign rho^K and the expected exact statistic has rho^(2K); this distinction matters for negative rho. The centered inputs require q, while the normalization/threshold require the stated model parameters; estimating unknown parameters is not covered by these statements.')
    issue('computational-and-proof-scope',[7,8,15,16],'Theorem2 asserts existence of an n^(2+o(1)) computation with exponential-in-K color coding. Main-text equations(29)–(32) fully define the approximation; the forward reference to appendix equation(54) is not followed. The likelihood-ratio representation, low-degree hardness discussion and Propositions3/4 explain the method or its proof; neither theorem assumes a computational hardness conjecture. The source does not specify a finite-precision bit-complexity model.')
    bindings={
      'T1':dict(parameters='n→infinity; q∈(0,1), feasible correlation rho, integer K→infinity satisfying the exact bound(7), and any fixed0<C<1.',objects=['D2','D5','D8','D9'],local_binders='Condition(7), the testing-error events(8) and tau=C E_P[f_T]=C rho^(2K)|T| are bound within this original theorem. D10 and D11 separately preserve these excerpts for their reuse by Theorem2.',conclusion='Exact signed-tree statistic has vanishing sum of the two displayed non-strict error probabilities. No efficient evaluation claim is made for exhaustive counting.'),
      'T2':dict(parameters='Inherits condition(7), including Otter constant, sparsity and K regime, and the threshold of(8) with the same fixed C.',objects=['D2','D10','D11','D14'],randomness='Graph-pair observations plus2t iid uniform colorings independent of the graphs; probability notation suppresses these coloring arguments.',conclusion='The normalized color-coding statistic has the same vanishing error guarantee and can be computed in n^(2+o(1)) time.',proof_scope='Proposition3 supplies relative L2 approximation, Proposition4 supplies runtime; neither is an extra assumption and neither is an inventoried Theorem.')}
    refs=[dict(claim_id=PID+'/T1',reference='f_T in(3)',reference_kind='definition_reference',resolution='D8 and its original centered-weighted-count, automorphism, tree-family and scaling dependencies.'),dict(claim_id=PID+'/T1',reference='Otter constant(6)',reference_kind='definition_reference',resolution='D9, with unrooted unlabeled trees counted by K edges; rounded decimal is not substituted for the defining growth constant.'),dict(claim_id=PID+'/T2',reference='condition(7)',reference_kind='assumption_reference',resolution='D10 imports only the condition excerpt from Theorem1, not a theorem-as-premise implication.'),dict(claim_id=PID+'/T2',reference='(8) and tau',reference_kind='definition_reference',resolution='D11 preserves the original threshold, including its alternative mean and fixed C.'),dict(claim_id=PID+'/T2',reference='approximation described as(54) in preceding prose',reference_kind='definition_reference',resolution='The main-text equations(29)–(32), D12–D14, define it fully. Appendix equation(54) is not read.'),dict(claim_id=PID+'/T2',reference='Theorem1 and Propositions3/4',reference_kind='proof_only',resolution='A5–A7 retain approximation and runtime provenance. Proof references do not add assumptions beyond(7) or import the low-degree conjecture.'),dict(claim_id=PID+'/T2',reference='Algorithm1, Algorithm2 and[Din15,WROM86,CB81]',reference_kind='computation_reference',resolution='Algorithm1 is preserved in A6 and the original main-text dynamic-programming routine is identified by its source label; externally credited tree-generation and automorphism routines are not independently certified here.')]
    data=dict(paper_id=PID,unranked_auxiliary_passages=aux,source_issues=issues,statement_local_bindings=bindings,source_claim_references=refs,ambient_conventions=['Simple undirected loop-free graphs, edge-set subgraphs, integer dimensions, products over edges, Bernoulli correlation, uniform permutations, factorials, max/min and asymptotic notation are ambient; no mathlib availability is assessed.','K_n is the complete graph on[n]. Abar and Bbar center off-diagonal Bernoulli edge entries by q. The weighted sums do not use diagonal entries.','Graph isomorphism, unlabeled classes and aut(H) retain original source definitions. K counts edges; all queried trees therefore have K+1 vertices.','D14’s mentions of W_H and f_T explain the approximation target; its explicit formula is resolved through colorful counts, centered matrices, weights and tree classes, without a proof-only edge to the exact statistic.','Source and structural validation do not certify proofs, finite-precision algorithm complexity, the hardness conjecture discussed elsewhere, or unstated uniformity at a threshold.'])
    (ROOT/'ambient-prerequisites.json').write_text(json.dumps(data,indent=2,ensure_ascii=False)+'\n')
if __name__=='__main__':main()
