"""Reproduce the seven complete main-text Theorems from the registered arXiv v1 PDF."""
import argparse,hashlib,json,subprocess,sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
REPO=next(p for p in ROOT.parents if (p/'scripts/resolve_paper_pdf.py').is_file())
PID='aos-2024-v52-i06-p2668'
SHA='a19bdc1387f0ca02c7e8ec6ebe846db9e39bd5404fda10b5b04641a4e430a7ac'
URL='https://arxiv.org/pdf/2410.04384v1'
NUMBERS=['3.1','3.2','3.3','4.1','5.1','6.1','6.2']
PAGES=[6,6,8,10,13,15,16]
STATEMENTS=[r'''Under Assumptions 1–3, let $\widehat\theta=(\widehat\gamma^\top,\widehat\beta^\top)^\top$ for any $\widehat\gamma\in\widehat{\mathcal G}$, , then $\widehat\theta\xrightarrow{p}\theta_0$ as $T\to\infty$.''',r'''Under Assumptions 1–4, $\|\widehat\beta-\beta_0\|=O_p(1/\sqrt T)$ and $\|\widehat\gamma-\gamma_0\|=O_p(1/T)$ for any $\widehat\gamma\in\widehat{\mathcal G}$.''',r'''Under Assumptions 1-5, we have (i) $\sqrt T(\widehat\beta_k-\beta_{k0})\xrightarrow{d}\mathcal N(0,\Sigma_k)$ for $k=1,\cdots,4$ and $T(\widehat\gamma^c-\gamma_0)\xrightarrow{d}\gamma_D^c$; (ii) $\{\sqrt T(\widehat\beta_k-\beta_{k0})\}_{k=1}^4$ and $\{T(\widehat\gamma_i^c-\gamma_{i0})\}_{i=1}^2$ are asymptotically independent.''',r'''For any small $\epsilon>0$ in (4.7), let $\widetilde\theta=(\widetilde\gamma^\top,\widetilde\beta^\top)^\top$ be a solution of the MIQP defined with (4.6) and (4.7), then $\mathbb M_T(\widehat\theta)=\mathbb M_T(\widetilde\theta)$ where $\widehat\theta$ is a solution in (3.2).''',r'''Suppose that Assumptions 1-6 hold. Then $\rho(\mathcal L_{T,B},\mathcal L_T)\xrightarrow{p}0$ as $B,T\to\infty$, for any metric $\rho$ that metrizes weak convergence of distributions.''',r'''For Model (6.6) with $K_0$ regimes and $L_0$ splitting hyperplanes, where $1\le K_0<4$ and $0\le L_0\le2$, under Assumption 1 and Assumptions S2-S4 in the SM ([33]), which adapt Assumptions 3–4 to the degenerate model settings, then for each $\beta_{k0}$ with $1\le k\le K_0$, $d(\beta_{k0},\widehat{\mathcal B})=O_p(1/\sqrt T)$. If $L_0=1$, then $d(\gamma_0,\widehat{\mathcal G})=O_p(1/T)$. If $L_0=2$, then $d(\gamma_{i0},\widehat{\mathcal G})=O_p(1/T)$ for each $i=1$ and $2$. Moreover, for any of the degenerated models with $K_0<4$ regimes, there exists an index set $Q_k\subset\{1,\cdots,4\}$ such that $\mathbb P\{Z\in R_k(\gamma_0)\mathbin{\triangle}\cup_{i\in Q_k}R_i(\widehat\gamma)\}=O(1/T)$ for each $1\le k\le K_0$.''',r'''Under the assumptions of Theorem 6.1, and $\lambda_T\to\infty$, $\lambda_T/T\to0$ as $T\to\infty$, then $\widehat K$ selected in (6.8) satisfies $\mathbb P(\widehat K=K_0)\to1$ as $T\to\infty$. In addition, $\mathbb P\{\widehat R_k^{(\widehat K)}\mathbin{\triangle}R_k(\gamma_0)\}=O(1/T)$ and $\|\widehat\beta_k^{(\widehat K)}-\beta_{k0}\|=O_p(1/\sqrt T)$ for any $k\in\{1,\cdots,K_0\}$.''']
def inventory():
    claims=[dict(claim_id=PID+'/T'+n,paper_id=PID,claim_kind='theorem',label='Theorem '+n+(' (Asymptotic distribution)' if n=='3.3' else ''),source_order=i,statement_original=s,evidence=[dict(page=p,location='Theorem '+n+' — complete original statement')]) for i,(n,p,s) in enumerate(zip(NUMBERS,PAGES,STATEMENTS),1)]
    paper=dict(paper_id=PID,title='Statistical inference for four-regime segmented regression models',authors=['Han Yan','Song Xi Chen'],version='arXiv:2410.04384v1, marked 6 Oct 2024',pdf_pages=25,pdf_sha256=SHA,source_url=URL,main_text_last_pdf_page=24,main_text_boundary=dict(location='Discussion and acknowledgements end on PDF page24 before the SUPPLEMENTARY MATERIAL notice at y395.594; evidence clipped at y390. This is a notice about a separate supplement, not an appendix body. References start later on24 at y466.770. No supplementary body is included or read.',shared_page_with_appendix=False),intake_review=dict(status='complete',theorem_ids=[c['claim_id'] for c in claims],zero_theorems_confirmed=False,method='Independently enumerate actual small-cap THEOREM headings throughout pages1–24, clipping24 after acknowledgements. Visually compare all seven complete statements. Exclude Corollaries3.1–3.2, remarks, theorem mentions, simulations and external supplementary bodies.'))
    return dict(schema_version='statistical-theorem-inventory-v1',scope=dict(paper_count=1,theorem_scope='main_text_only',source_policy='Verified registered local arXiv v1 PDF pinned by SHA256; inspect main text and exclude supplementary bodies. Preserve explicit references to uninspected supplementary assumptions.',normalization_policy='Preserve all seven original statements and printed numbers/titles, hypotheses, formulas and subparts. Normalize line wrapping and mathematical typesetting only. Preserve the duplicated comma in T3.1, arbitrary versus centroid minimizers, the ordinary O rate for regime errors, both degenerate-model cases, and the original implicit probability notation in T6.2.'),papers=[paper],claims=claims)
def main():
    source=Path(subprocess.check_output([sys.executable,str(REPO/'scripts/resolve_paper_pdf.py'),PID],text=True).strip());assert hashlib.sha256(source.read_bytes()).hexdigest()==SHA
    ROOT.mkdir(parents=True,exist_ok=True);(ROOT/'theorem-inventory.json').write_text(json.dumps(inventory(),indent=2,ensure_ascii=False)+'\n');print('Saved seven complete main-text Theorems; independent inventory review remains separate.')
if __name__=='__main__':
    parser=argparse.ArgumentParser();parser.add_argument('--output-dir',type=Path);args=parser.parse_args()
    if args.output_dir:ROOT=args.output_dir.resolve()
    main()
