"""Preserve local notation and source limitations without rewriting theorems."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];PID=ROOT.name
aux=[]
def add(aid,text,pages,loc,meaning):aux.append(dict(auxiliary_id=aid,statement_original=text.strip(),evidence=[dict(page=p,location=loc) for p in pages],resolution=meaning))
add('A1',r'''
Here, $\varepsilon_{\mathrm{test}}$ is a measure of the adversary’s power and $\varepsilon$ is the “perceived” adversary’s power used by the algorithm. Our theory allows for $\varepsilon$ to be different from $\varepsilon_{\mathrm{test}}$; cf Theorem 4.2. In our numerical experiments in Section 2 we consider $\varepsilon=\varepsilon_{\mathrm{test}}$ to focus on other relevant quantities, namely $\psi_1$, $\psi_2$ on adversarial risk.
''',[11],'Section 4 — training and test radii','The risk limit allows distinct training and test radii. The equality imposed in some numerical plots is not a theorem assumption.')
add('A2',r'''Here, $\boldsymbol 1=(1,1,\ldots,1)\in\mathbb R^N$ and $\zeta>0$ is an arbitrary small but fixed constant.''',[15],'After equation (6.1) — all-ones vector','The all-ones vector used in Theorem 6.9 is defined here. Its reuse does not import the auxiliary loss, Omega matrix, or zeta limit into the theorem.')
add('A3',r'''
We use $O_d(\cdot)$, $o_d(\cdot)$ to denote the standard big-O and little-o notation, where we stress the asymptotic variable $d$. Likewise, we use $O_{d,\mathbb P}$ and $o_{d,\mathbb P}$ to indicate asymptotic behavior in probability. Specifically, $f(d)=O_{d,\mathbb P}(g(d))$ if for any $\varepsilon>0$, there exists $C_\varepsilon>0$ and large enough $d_\varepsilon$ such that $P(|f(d)/g(d)|>C_\varepsilon)\leq\varepsilon$, for all $d\geq d_\varepsilon$. Similarly, $f(d)=o_{d,\mathbb P}(g(d))$ if $f(d)/g(d)$ converges to zero in probability. We write $f(d)\approx g(d)$ as $d\to\infty$, when $f(d)-g(d)\to0$, in probability.
''',[15,16],'Section 6 — asymptotic notation','The limit variable is d with dimensions growing as specified in the separate proportional-growth passage. A difference tending to zero is distinct from ratio convergence.')
add('A4',r'''
For a matrix $\boldsymbol A$, we denote by $\|\boldsymbol A\|$ its operator norm, $\|\boldsymbol A\|_F=(\sum_{ij}A_{ij}^2)^{1/2}$ the Frobenius norm of $\boldsymbol A$. For an integer $n$, we use the shorthand $[n]=\{1,\ldots,n\}$.

Finally, the indicator function is denoted by $\mathbb I(\cdot)$ – i.e., $\mathbb I(A)=1$ only if the event $A$ holds true, and otherwise $\mathbb I(A)=0$.
''',[16],'Section 6 — norms and indicators','Resolves the spectral norm in E_W and componentwise sign indicators in the J matrix. The Hadamard product and entrywise inverse cosine in (6.10) have their matrix-entry interpretation; no appendix notation is needed.')
add('A5',r'''for a large enough constant $C$ (note that $N/d:=\psi_{1,d}$ – see Assumption 1).''',[15],'After equation (6.2) — finite aspect ratio','The finite ratio psi_(1,d) in E_W is N/d. Using that notation does not import the signal normalization part of Assumption 1.')
add('A6',r'''In the following, our statements are proven conditioned on the event $\mathcal E_{\boldsymbol W}$ which holds with high probability.''',[15],'Section 6 — conditional scope','Theorem 6.9 expressly assumes E_W and is read with this section convention. Theorem 4.2 explicitly states probability over both W and the training data and is not turned into a conditional theorem by its proof strategy.')
add('A7',r'''Let $\eta_i(\boldsymbol\theta):=\|\boldsymbol W^\top\operatorname{diag}(\mathbb I(\boldsymbol W\boldsymbol x_i>0))\boldsymbol\theta\|_{\ell_2}$''',[17],'Proposition 6.4 — definition fragment','Resolves the auxiliary quantity in the displayed interpretation E[eta_i(theta)^2]=||J theta||^2. Only this definition fragment is needed; the proposition\'s uniform concentration claim and its coefficient constraint set are not imported.')
add('A8',r'''where the expectation is with respect to $\boldsymbol x_i$ and $\boldsymbol W$ is fixed.''',[17],'After equation (6.9) — conditional matrix expectation','J averages over a fresh Gaussian covariate at fixed W. Its defining matrix square root is the positive-semidefinite square root, as stated in the next paragraph.')
add('A9',r'''where $\boldsymbol f_i$ are generated i.i.d. according to (6.15).''',[19],'After equation (6.16) — surrogate sample','The noisy linear features used in Theorem 6.9 are the sample-indexed copies of (6.15). W is shared across the sample, so this construction is interpreted with W held fixed, consistently with the section convention.')
add('A10',r'''Note that the random variables $\sigma(\boldsymbol w_i^\top\boldsymbol x)$ have zero mean and unit variance, by construction.''',[18],'After equation (6.14) — printed variance assertion','The source prints sigma rather than sigma-perp here. Shifted ReLU itself has variance 1/2-1/(2 pi), so the asserted unit variance does not match the defined activation. The original assertion is archived as a source discrepancy; the surrogate uses the explicitly given mu coefficients without normalizing sigma.')
add('A11',r'''Consider sequences of parameters $(N,n,d)$ that diverge proportionally to each other''',[10],'Section 4 — sequence convention (excerpt)','The exact source sentence is recorded below; N and n are indexed by d, rather than limits over unrelated independent dimensions.')
aux[-1]['statement_original']=r'We consider sequences of parameters $(N,n,d)$ that diverge proportionally to each other and sometimes, we index such sequences by $d$, with $N=N(d)$ and $n=n(d)$ functions of $d$.'
issues=[
 dict(id='source_version',evidence=[dict(page=1,location='arXiv stamp')],detail='The source is arXiv:2201.05149v2, stamped 1 February 2024. Title and authors match the corpus record. Equality with the published journal version is not established.'),
 dict(id='supplement_boundary_and_title',evidence=[dict(page=22,location='Supplementary Material notice'),dict(page=25,location='last reference page')],detail='The attached supplement starts on PDF page 26 before the first appendix bookmark at page 27. Its title refers to classification accuracies although the main paper is about random-features regression. The notice on main page 22 uses that same supplement title. Supplementary definitions/proofs are excluded; introductory content exposed while checking the boundary is not used as census evidence.'),
 dict(id='phi_b_absolute_value',evidence=[dict(page=20,location='Theorem 6.9 objective Phi_B and Proposition 6.10')],detail='Phi_A uses (|residual|+epsilon||J theta||)^2 but Phi_B prints (residual+epsilon||J theta||)^2 without absolute-value bars. The adjacent noisy-linear loss in Proposition 6.10 includes the bars. The theorem\'s asymmetric formulas are retained, not silently reconciled.'),
 dict(id='root_star_position',evidence=[dict(page=11,location='Theorem 4.2 root equation and risk formula (4.6)')],detail='Part (a) defines nu with a superscript star; (4.6) uses nu with a subscript star, without an explicit sentence equating that symbol to the root evaluated at the saddle point. That evaluation is the apparent intended reading, but original notation is preserved and the distinction is recorded.'),
 dict(id='zero_boundary_scalar_objective',evidence=[dict(page=11,location='Theorem 4.2(a), optimization (4.5)')],detail='The optimization domain permits zero alpha, beta, tau_g and tau_q, but the objective and root equation divide by these quantities. No boundary extension or extended-real convention is given in the inspected main-text statement. The domain is not silently restricted to strict positivity.'),
 dict(id='root_domain',evidence=[dict(page=11,location='Theorem 4.2(a) — unique-root equation')],detail='No domain for nu is stated in the root assertion. The objective multiplies a root-dependent term by an indicator threshold, but no separate definition is supplied for inactive branches or zero denominators. A nonnegative-root restriction or zero-root fallback is not added.'),
 dict(id='noise_independence',evidence=[dict(page=4,location='data model (2.1)')],detail='The source gives i.i.d. pairs, Gaussian x marginals and Gaussian xi marginals, but does not explicitly write xi independent of x in the model statement. Independent additive Gaussian noise is the conventional intended model; the missing explicit independence is recorded rather than inserted into the source quotation.'),
 dict(id='surrogate_joint_randomness',evidence=[dict(page=18,location='equation (6.15)'),dict(page=19,location='i.i.d. surrogate features after (6.16)')],detail='The surrogate Gaussian u is explicitly independent of x; its independence from response noise and W is not separately stated in the defining sentence. The sample uses one shared W. The audit does not replace the conditional-on-W interpretation with unconditional independence of all feature vectors.'),
 dict(id='theorem69_signal_regime',evidence=[dict(page=10,location='Assumption 1'),dict(page=16,location='Section 6 asymptotic convention'),dict(page=20,location='Theorem 6.9')],detail='Theorem 6.9 does not cite Assumption 1. Section 6 explicitly reiterates proportional n,d,N growth, but not the signal norm tending to one. The graph includes the repeated dimensional convention and records the unstated signal-regime scope; it does not silently impose the stronger normalization merely because the theorem is used to prove Theorem 4.2.'),
 dict(id='unit_variance_activation',evidence=[dict(page=18,location='after equation (6.14)')],detail='The printed assertion that sigma(w_i^T x) has unit variance conflicts with the shifted-ReLU definition. The Gaussian decomposition coefficients are retained as stated, and sigma is not replaced by its standardized nonlinear component.'),
 dict(id='stieltjes_appendix_reference',evidence=[dict(page=11,location='equation (4.4) and following sentence')],detail='The main text defines S by a complete real formula and refers to Lemma F.2 for further transform details. The appendix is not consulted and no additional convention from it is assumed.'),
 dict(id='reuse_of_symbols',evidence=[dict(page=11,location='Theorem 4.2'),dict(page=20,location='Theorem 6.9')],detail='The scalar beta in the saddle problem is distinct from the bold signal vector beta in data model (2.1). Scalar sigma squared in Theorem 4.2 is distinct from the activation function sigma. The scalar lambda inside the supremum of (4.5) is distinct from the positive regularization lambda in Theorem 6.9.'),
 dict(id='constant_c_and_penalty_regime',evidence=[dict(page=20,location='Theorem 6.9')],detail='The limit c has no separately printed quantifier or range, and lambda,lambda_s,lambda_w are stated only to be positive. Treating c as a deterministic finite real limit and penalties as fixed is conventional context; the theorem does not explicitly describe a growing/diminishing penalty regime.'),
 dict(id='argmin_and_max_totality',evidence=[dict(page=10,location='Definition 4.1 and (4.3)')],detail='The general adversarial-risk definition uses max for an arbitrary predictive model and nonnegative loss, without general regularity guaranteeing attainment. The specialized shifted-ReLU squared loss is continuous on a compact perturbation ball. The robust ERM uses an argmin without a general tie-selection convention; no tie rule is invented.')
]
resolution={
 'shared':'n is sample size, d the covariate dimension and N the number of random features. Bold W has shape N by d, its rows are w_l, and bold theta is an N-vector. The data-model signal bold beta is a d-vector. Standard primitives include Gaussian laws, sphere-uniform laws, Euclidean norms, inner products, matrix transpose, positive-semidefinite square root, Hadamard product, finite sums, expected loss, min/max/supremum and convergence in probability. A2 supplies the N-dimensional all-ones vector, A4 the matrix norm and indicator conventions. No library availability is asserted.',
 '4.2':'D1-D7 resolve all nonlocal objects. Tau squared is the noise marginal variance in (2.1), psi1 and psi2 come from Assumption 1, epsilon is the positive training radius and epsilon_test the separate test radius. Scalar sigma squared, the five saddle variables, their starred solution, the objective R and its lambda supremum are bound/defined inside the theorem. The ordinary error function erf is used without a main-text definition; its conventional real definition is 2/sqrt(pi) times the integral of exp(-t^2) from 0 to its argument. The root nu-star and the subscripted nu_star in the final formula are not silently identified; see source note. The limiting probability is expressly over both training data and W. Proof-only J, Gaussian surrogates, the event E_W, zeta penalties and constraint sets C_theta are not statement dependencies.',
 '6.9':'D1/D2/D3 supply data, W and the shifted activation. D8 is the explicitly assumed event E_W, D9 supplies J, and D11 supplies sample surrogate features f_i with coefficients D10. D12 supplies the reiterated dimensional limit convention. Phi_A and Phi_B are inline definitions, theta ranges over the N-dimensional coefficient space, lambda/lambda_s/lambda_w are inline positive parameters, bold1 is A2, and c is the common proposed limit. The theorem compares optimum values, not minimizers or risks. Its adjacent Proposition 6.10 and constraint set C_theta-prime are not imported as hypotheses.'
}
def main():
    (ROOT/'ambient-conventions.json').write_text(json.dumps(dict(paper_id=PID,auxiliary_passages=aux,standard_ambient_resolution=resolution,unresolved_source_conventions=issues),indent=2,ensure_ascii=False)+'\n')
    print('Saved',len(aux),'auxiliary passages and',len(issues),'source notes.')


if __name__ == '__main__':
    main()
