"""Derive source-backed statement relationships for all six ridge and resolvent Theorems."""
import copy,json,subprocess,sys
from pathlib import Path
from extract_interfaces import ROOT,PID,interfaces,members
SKILL=Path('skills/statistical-paper-census/scripts')
sys.path.insert(0,str(SKILL))
from canonical_dependencies import canonical_dependencies
from census_metrics import derive_metrics
from publication_contract import attach_inventory
DIRECT_NUMS={'1':[7,12,13,15,16,17,18,19,20,22],'2':[3,4,7,12,13,15,16,17,18],'3':[7,11,12,13,14,15,16,17,18,23,24,25,26],'4':[7,8,11,12,13,16,17,18],'5':[7,12,13,15,18,25,27,28,29],'6':[7,18,21,30,31]}
DIRECT={n:['D'+str(i) for i in v] for n,v in DIRECT_NUMS.items()}
EDGE_TEXT={
'D2':{'D1':'The covariance is a trace-class operator on the original real separable feature space.'},
'D3':{'D2':'The signal condition uses the inverse square root of the population covariance and its spectral domain.'},
'D4':{'D2':'The effective-rank envelope bounds tails of the ordered population covariance eigenvalues.'},
'D5':{'D1':'The coordinate alternative applies to the finite or infinite coordinate representation of the feature space.'},
'D6':{'D1':'The convex concentration alternative is stated for convex Lipschitz functions on the feature-coordinate space.'},
'D7':{'D2':'Assumption 1 requires normalized trace-class covariance and lists its eigenvalues.','D3':'Assumption 1 explicitly requires finite inverse-covariance signal norm.','D4':'Part I imposes the effective-rank tail envelope.','D5':'Part II permits the independent sub-Gaussian coordinate alternative (a).','D6':'Part II alternatively permits the convex concentration condition (b); it is not imposed jointly with (a).'},
'D8':{'D1':'The row features belong to the original finite-dimensional or separable Hilbert space.'},
'D9':{'D1':'The linear model uses features and a signal in the stated finite or Hilbert space.','D2':'The feature covariance in model (3) is the normalized trace-class operator Sigma.'},
'D10':{'D8':'The ridge objective and inverse formula use the matrix of observed feature rows.','D9':'The ridge response is generated by the original IID linear signal-plus-noise model.'},
'D11':{'D10':'Ridgeless regression is explicitly the positive-zero-regularization limit of the ridge estimator.'},
'D12':{'D2':'Conditional variance uses population covariance in its trace loss.','D9':'Its ridge formula contains the original independent noise variance tau².','D10':'Formula (5a) is the variance of the ridge estimator from (1)–(2).','D14':'The formula uses the normalized sample covariance inside its resolvent factors.'},
'D13':{'D2':'Conditional squared bias is measured in the population-covariance norm.','D10':'Formula (5b) is the ridge estimator bias.','D14':'The two sample-covariance inverse factors in (5b) surround population covariance.'},
'D14':{'D8':'The normalized sample covariance is X transpose X divided by n.'},
'D15':{'D2':'The scalar effective-regularization equation (7) is a trace function of population covariance.'},
'D16':{'D2':'The deterministic variance equivalent uses the population-covariance trace, not sample covariance.','D9':'Its numerator uses the original regression noise variance tau².','D15':'The covariance resolvent in (8) is evaluated at the implicit effective regularization lambda_star.'},
'D17':{'D2':'The deterministic bias equivalent uses population covariance and its trace denominator.','D9':'The signal beta in (9) is the regression parameter in the original model.','D15':'The effective bias formula uses lambda_star from (7).'},
'D19':{'D2':'chi_n uses the ordered covariance eigenvalue indexed by floor(eta*n).','D4':'The numerator of (24) uses the effective-rank envelope and its logarithm.'},
'D20':{'D15':'The positive-ridge kappa in (25) uses lambda divided by effective lambda_star.'},
'D21':{'D2':'The modified population resolvent is the weighted trace of an inverse affine function of Sigma.'},
'D22':{'D3':'The directional ratio uses beta=Sigma^(1/2)theta with finite theta norm.','D15':'Its population resolvents are evaluated at lambda_star.','D21':'The numerator and denominator are the modified population resolvent (26) with different PSD weights.'},
'D23':{'D2':'The ridgeless replacement uses the same ordered covariance eigenvalue.','D4':'Its numerator retains the original effective-rank envelope.','D15':'The denominator uses the zero-limit effective regularization lambda_star(0), multiplied by the free kappa.'},
'D24':{'D3':'The limiting ratio uses the same inverse-covariance signal coordinate theta.','D15':'Its resolvents are evaluated at the overparameterized positive zero-limit root.','D21':'The limiting ratio compares weighted population resolvents from (26).'},
'D25':{'D2':'Spectral prefix and tail projections use the eigenvectors of the covariance operator.'},
'D27':{'D2':'Regular variation is imposed on the ordered population-covariance eigenvalue sequence.'},
'D28':{'D18':'The polynomial-decay condition is an original deterministic big-O relation between two spectral integrals.','D25':'Its cumulative measure sums squared signal coefficients in the covariance eigenbasis up to floor(n*x).'},
'D29':{'D18':'The rapid-decay condition uses the source deterministic big-O convention.','D25':'Its cumulative measure uses the same eigenbasis with a distinct floor((n/log n)*x) cutoff.'},
'D30':{'D2':'The sample resolvent trace retains population-covariance weighting.','D8':'X_k consists of the first k feature rows of the observed design.','D21':'The source explicitly extends population R_0 from (26), recovering it under the k=0 convention.'},
'D31':{'D21':'The implicit equation (44) evaluates the population resolvent at the unknown mu_star.'}}
REASONS={
'1':{7:'Theorem 1 explicitly assumes the full Assumption 1.',12:'Its first conclusion approximates the actual conditional ridge variance script V_X(lambda) from (5a).',13:'Its second conclusion approximates the actual squared conditional ridge bias script B_X(lambda) from (5b).',15:'The bias error explicitly contains lambda_star(lambda)^(k+1), with lambda_star defined in (7).',16:'The deterministic reference in the variance bound is V_n(lambda) from (8).',17:'The deterministic reference and multiplicative factor in the bias bound are B_n(lambda) from (9).',18:'The probability and approximation statements use the source big-O and Omega constants with the printed k,C_x,D dependencies.',19:'The theorem explicitly invokes chi_n(lambda), the ratio defined in (24), in its assumptions and error bounds.',20:'It explicitly invokes the positive-ridge interior parameter kappa from (25).',22:'The extra bias assumptions and error denominator use rho(lambda) from (27).'},
'2':{3:'The optional bias premise directly bounds the inverse-covariance squared signal norm by C double prime.',4:'The theorem defines dtilde_Sigma(n) from the original effective-rank envelope d_Sigma(n).',7:'Theorem 2 begins with Assumption 1.',12:'The first conclusion approximates script V_X(lambda), the sample-conditional variance.',13:'The second conclusion approximates script B_X(lambda), the sample-conditional squared bias.',15:'The theorem-local non-negligible ratio nu is lambda/lambda_star(lambda), using the effective root (7).',16:'The variance approximation and its multiplicative reference use V_n(lambda).',17:'The optional bias approximation and its multiplicative reference use B_n(lambda).',18:'The bounds use the original deterministic big-O convention, with explicit constant-suppression wording and distinct decay exponents.'},
'3':{7:'Theorem 3 explicitly assumes Assumption 1 with n<d and adds sigma_n>0.',11:'The result concerns actual and effective quantities in the ridgeless positive limit.',12:'Its first conclusion controls script V_X(0), the actual ridgeless conditional variance.',13:'Its second conclusion controls script B_X(0), including relative and additive errors.',14:'The theorem introduces s_min as the minimum nonzero eigenvalue of normalized sample covariance and uses it in the event and error bounds.',15:'The premises, event, errors and auxiliary C_Sigma definition use the zero-limit effective regularization lambda_star(0).',16:'The variance reference is the zero-limit deterministic equivalent V_n(0).',17:'The relative part of the bias bound is multiplied by the zero-limit deterministic equivalent B_n(0).',18:'The theorem retains its k,C_x,D-dependent deterministic orders and high-probability statements.',23:'It explicitly invokes chi_prime_n(kappa), the ridgeless replacement (31), with kappa freely chosen under its own bounds.',24:'Its bias assumptions and error denominator invoke the limiting directional ratio rho(0).',25:'The additive bias error uses theta_<=n and beta_>n, following the original spectral prefix/tail convention.',26:'The phrase on the event {s_min>=8*lambda_star(0)*kappa}, with the stated probability, uses the explicitly defined intersection-probability convention.'},
'4':{7:'Theorem 4 explicitly assumes Assumption 1 in the n>d regime.',8:'Its zero-bias conclusion is stated deterministically on rank(X)=d for the observed feature matrix.',11:'Both conclusions concern the underparameterized positive-zero-regularization limit.',12:'The variance conclusion approximates script V_X(0).',13:'The bias conclusion sets script B_X(0) to zero on the stated rank event.',16:'Its deterministic variance comparison is V_n(0).',17:'The bias statement also asserts B_n(0)=0 in the same limit.',18:'The variance premise and conclusion use the source k,C_x,D-dependent orders and Omega context.'},
'5':{7:'Theorem 5 begins with Assumption 1, retaining all of its explicit conditions.',12:'Equations (35) and (38) give asymptotics for actual conditional variance at the printed positive regularization levels.',13:'Equations (36) and (39) give asymptotics for actual conditional squared bias under their respective extra coefficient conditions.',15:'Equations (34) and (37) give asymptotics for lambda_star at the two printed regularization arguments.',18:'The probability statement, coefficient predicates and small relative errors use the original order conventions.',25:'Both F_beta measures are defined using signal coefficients along the covariance eigenvectors.',27:'The two branches impose regularly varying spectral sequences, with different exponent regimes.',28:'The optional bias conclusion in branch 1 requires the polynomial-decay condition with the n-scaled F_beta measure.',29:'The optional bias conclusion in branch 2 requires the rapid-decay condition with the different n/log n-scaled measure.'},
'6':{7:'Theorem 6 explicitly assumes Assumption 1, even though its conclusion is a design-only resolvent approximation.',18:'Its smallness conditions and approximation/probability bounds use deterministic big-O and Omega notation.',21:'The conclusion and local sans-serif R0 shorthand use the modified population resolvent script R_0.',30:'The random quantity being approximated is script R_n(zeta,mu;Q), the sample resolvent from (43).',31:'The comparison resolvent and error parameters are evaluated at the implicit mu_star(zeta,mu)>mu defined by (44).'}}
def direct_reason(n,lid):return REASONS[n][int(lid[1:])]
def main():
    import extract_interfaces,save_ambient
    extract_interfaces.ROOT=ROOT;extract_interfaces.main();save_ambient.ROOT=ROOT;save_ambient.main()
    inv=json.loads((ROOT/'theorem-inventory.json').read_text());data=copy.deepcopy(inv);data['schema_version']='statistical-ranked-interfaces-v4'
    data['scope'].update(semantic_ranking_policy='Preserve all six original main-text Theorems and original ridge, covariance, spectral and resolvent definitions.',build_order_policy='Derive same-paper paths from the original source definitions. Distinguish sample quantities from deterministic equivalents, positive and zero-limit parameters, alternative concentration hypotheses and design-only resolvents. Proof machinery does not become an additional theorem premise.')
    data['interfaces']=copy.deepcopy(interfaces);claims={c['claim_id']:c for c in data['claims']}
    for lid,m in members.items():assert set(m['depends_on'])==set(EDGE_TEXT.get(lid,{})),lid
    for c in data['claims']:
        n=c['claim_id'].split('/T')[-1];c['depends_on']=DIRECT[n];assert set(REASONS[n])==set(DIRECT_NUMS[n])
        for x in data['interfaces']:
            lid=x['members'][0]['local_id']
            if lid in DIRECT[n]:
                x['central_claim_uses'].append(dict(use_id=c['claim_id']+'-'+lid,paper_id=PID,claim_id=c['claim_id'],use_kind='statement_dependency',reason=direct_reason(n,lid),evidence=copy.deepcopy(c['evidence'])+copy.deepcopy(members[lid]['evidence'])))
    edges=canonical_dependencies(data)
    for x in data['interfaces']:x['dependencies']=edges[x['interface_id']]
    derive_metrics(data)
    for x in data['interfaces']:
        for rel in x['related_theorems']:
            cid=rel['claim_id'];n=cid.split('/T')[-1];path=rel['via_local_ids']
            reason=' '.join([direct_reason(n,path[0])]+[EDGE_TEXT[a][b] for a,b in zip(path,path[1:])]);ev=copy.deepcopy(claims[cid]['evidence'])
            for lid in path:ev.extend(e for e in members[lid]['evidence'] if e not in ev)
            x['theorem_explanations'][cid]=dict(paper_id=PID,via_local_ids=path,text=reason,evidence=ev)
        for m in x['members']:
            own=m['statement_original']+' '+m['local_label'];linked=own+' '+' '.join(claims[r['claim_id']]['statement_original'] for r in x['related_theorems']);selectors=m['highlight_symbols']+m['highlight_phrases']
            assert any(s in own for s in selectors) and all(s in linked for s in selectors),(m['local_id'],[s for s in selectors if s not in linked])
    attach_inventory(data,ROOT/'theorem-inventory.json',ROOT/'ranked-interfaces.json')
    (ROOT/'unfinalized-census.json').write_text(json.dumps(data,indent=2,ensure_ascii=False)+'\n')
    subprocess.run([sys.executable,str(SKILL/'finalize_census.py'),str(ROOT/'unfinalized-census.json'),str(ROOT/'ranked-interfaces.json'),'--inventory',str(ROOT/'theorem-inventory.json')],check=True)
    subprocess.run([sys.executable,str(SKILL/'validate_census.py'),str(ROOT/'ranked-interfaces.json')],check=True)
    print('Census structurally validated; independent source review remains pending.')
if __name__=='__main__':main()
