"""Preserve original ambient ridge conventions and explicit source limitations."""
import json
from save_inventory import ROOT,PID

def main():
    aux=[]
    def add(n,s,ps,note,deps=()):aux.append(dict(local_id='A'+str(n),statement_original=s,evidence=[dict(page=p,location='Original main-text context A'+str(n)) for p in ps],scope_note=note,depends_on=list(deps)))
    add(1,r'''For an estimator $\hat{\boldsymbol\beta}=\hat{\boldsymbol\beta}(\boldsymbol X,\boldsymbol y)$ we define the excess risk as
\[
\mathscr R_X(\hat{\boldsymbol\beta};\boldsymbol\beta)=\mathbb E_{\boldsymbol x_{\mathrm{new}},\boldsymbol y}[(\boldsymbol x_{\mathrm{new}}^\top\hat{\boldsymbol\beta}-\boldsymbol x_{\mathrm{new}}^\top\boldsymbol\beta)^2\mid\boldsymbol X]=\mathbb E_{\boldsymbol y}[\|\hat{\boldsymbol\beta}-\boldsymbol\beta\|_{\boldsymbol\Sigma}^2\mid\boldsymbol X],
\]
where $\boldsymbol x_{\mathrm{new}}$ is an independent copy of $\boldsymbol x_1,\cdots,\boldsymbol x_n$ and $\|\boldsymbol x\|_{\boldsymbol\Sigma}^2:=\boldsymbol x^\top\boldsymbol\Sigma\boldsymbol x$.''',[5],'Original conditional prediction risk and weighted norm. Randomness remaining in the risk is the design. Theorems state the separate conditional bias/variance, not merely total risk.',['D2','D8','D9','D12','D13'])
    add(2,r'''We will state four theorems. The first two concern ridge regression with positive regularization $\lambda>0$: Theorem 1 is our most general result that forms the basis for all of other ones; Theorem 2 is a simplified version of the previous one, and covers values of ridge regularization $\lambda$ that we expect to include the optimal $\lambda$. The other two theorems apply to the ridgeless case $\lambda=0+$: Theorem 3 applies to overparametrized case, and Theorem 4 to the underparametrized one.''',[9],'Original domain context. This paragraph describes Section 3 only; Theorems 5 and 6 later in the main text are also inventoried.',['D10','D11'])
    add(3,r'''Finally we define
\[
C_\Sigma:=1-\frac1n\operatorname{Tr}(\boldsymbol\Sigma^2(\boldsymbol\Sigma+\lambda_\star(0)\boldsymbol I)^{-2})\in(0,1).
\]''',[12],'Original scalar constant used in Theorem 3, retained as a local auxiliary definition with no invented API title. Its positive range presupposes a positive effective zero-limit root.',['D2','D15'])
    add(4,r'''In the underparameterized regime $d<n$, we have $\lim_{\lambda\downarrow0}\lambda_\star(\lambda)=0$ and therefore the previous bounds do not apply. In this case, we trivially have $\mathscr B_X(0)=B_n(0)=0$.''',[13],'Original zero-limit context; Theorem 4 subsequently qualifies the zero-bias statement by rank(X)=d. Do not substitute an ordinary inverse at zero into a singular covariance.',['D11','D13','D15','D17'])
    add(5,r'''This condition appears to be a proof artifact and we would expect that the conclusion of the theorem should hold under the weaker condition $\|\boldsymbol\beta\|_{\boldsymbol\Sigma}<\infty$, which is required in the equivalent sequence model in Eq. (18). This condition cannot be eliminated by an approximation argument, because it appears (implicitly) in the definition of $\rho(\lambda)$, via $\|\boldsymbol\theta\|^2=\|\boldsymbol\beta\|_{\boldsymbol\Sigma^{-1}}^2$.''',[10],'Original conjectural discussion does not remove the inverse-covariance signal condition from any theorem that explicitly assumes Assumption 1.',['D3','D7','D22'])
    add(6,r'''Recall that we defined $\boldsymbol\theta:=\boldsymbol\Sigma^{-1/2}\boldsymbol\beta$, and assumed $\|\boldsymbol\theta\|<\infty$. By homogeneity, we can and will assume $\|\boldsymbol\theta\|=1$ throughout the proof.''',[23],'Original proof normalization only. Theorem statements and their coefficient conditions are not restricted to unit signal norm.',['D3'])
    add(7,r'''For $\zeta=n\lambda$ and $\mu=0$, this equation reduces to Eq. (7), via the change of variables $\mu_\star=n\lambda/\lambda_\star$.''',[23],'Original special-case relation between the two implicit parameters. The general resolvent theorem does not require the ridge interior ratio kappa.',['D15','D31'])
    add(8,r'''The random features $\boldsymbol x_i\in\mathbb R^d$ and noise $\varepsilon_i$ are independent, and the $(\boldsymbol x_i,\varepsilon_i)$ are i.i.d. samples with $1\le i\le n$.''',[4],'Common sampling context supplies IID feature rows even to the design-only Theorem 6. Its covariance conclusion does not require a response/noise interface merely because the paper motivates it through regression.',['D8','D9'])
    add(9,r'''However, the inequality also holds for $d=\infty$ on the Hilbert space $\ell_2$ by a standard approximation argument. Namely, one can project the vector $\boldsymbol x$ on the span of the top $k$-eigenvectors of $\boldsymbol\Sigma$, establish concentration, and take $k\to\infty$ at the end.''',[6],'Original finite-projection extension of the quadratic-form concentration argument. It does not assert that an isotropic infinite coordinate sequence z is itself Hilbert-valued.',['D1','D2','D5','D6','D25'])
    bindings={
    'T1':'Positive ridge regularization is supplied by Section 3. Resolve actual and deterministic bias/variance through the original IID linear model, covariance, sample covariance, ridge objective and effective root. Assumption 1 retains inverse-signal norm, tail envelope and disjunctive concentration conditions. chi, interior kappa and directional rho are the definitions on page9. Bias has its own additional smallness and lambda*k*n^(-1/k) conditions; preserve constant dependencies and the probability level.',
    'T2':'Same positive-ridge model and full Assumption 1, with the theorem-local non-negligible ratio nu=lambda/lambda_star and dtilde=d_Sigma*log²(d_Sigma). Do not import Proposition3.1 as an additional assumption. Preserve different exponents0.99/0.49 and4/3 versus7/6, the extra Cdoubleprime inverse-signal bound, and the source constant/index ambiguities.',
    'T3':'Overparameterized positive-limit estimator with n<d and sigma_n>0. kappa is freely chosen under its printed bounds, not the positive-ridge definition25. Resolve chi_prime, limiting rho and auxiliary C_Sigma on12; theta is the inverse-covariance signal coordinate and prefixes/tails use the eigenbasis convention on7. The event-qualified probability means P(failure intersect E)<=Delta. The bias retains both a relative term and the minimum of two additive errors. The final nonzero-eigenvalue bound has separate separation assumptions and probability; no full-rank covariance or positive lower bound is silently supplied.',
    'T4':'Underparameterized n>d and theorem-local nu=min(d/n,1-d/n). The covariance/ridge definitions are read in the positive-zero-limit sense. The zero-bias conclusion is deterministic on rank(X)=d, not an unqualified assertion for every design. k,D and epsilon conventions are inherited/partly implicit as printed. No proportional-regime Assumption2 is added.',
    'T5':'Full Assumption1 in the infinite-dimensional Section4.2 context. The two regularly varying spectral branches have distinct c_star definitions and n-dependent F_beta measures; their optional bias conditions are polynomial-decay versus rapid-decay. Scalar theta in those predicates is different from the bold whitened signal. Preserve every printed regularization argument and the possible slow-factor scaling mismatch. Theorem5 states actual bias and variance, not V_n or B_n; deterministic equivalents are proof machinery here.',
    'T6':'Design-only weighted resolvent approximation for zeta>0, mu>=0 and fixed bounded PSD Q of operator norm1, under the explicitly stated Assumption1. Sample R_n and population R_0 are script symbols; sans-serif R0 denotes population R_0 evaluated at the implicit mu_star>mu root. All gamma/alpha/beta parameters are bound inside the theorem, with denominators1+R0(I)^2 or1+R0(I)^3 exactly as printed. Do not impose ridge kappa/rho conditions, response-noise assumptions, unit signal normalization, or finite-difference lemmas as additional premises.'}
    refs=[]
    for n in ['1','2','3','4','5','6']:refs.append(dict(claim_id=PID+'/T'+n,target='Assumption 1; common Hilbert/covariance and IID feature setup',reference_kind='definition_reference',note='Resolve the full original assumption, including its alternative concentration clauses; do not replace it by the abstract description.'))
    for n in ['1','2','3','4','5']:refs.append(dict(claim_id=PID+'/T'+n,target='Ridge or ridgeless estimator; sample-dependent variance and bias; theorem-specific effective quantities',reference_kind='definition_reference',note='Use the source branch and parameter domain, not a universal zero-regularization substitution.'))
    refs.append(dict(claim_id=PID+'/T3',target='Section3.3 event convention and C_Sigma; spectral projection definitions in Proposition2.2',reference_kind='definition_reference',note='These are main-text statement definitions, not proof-only links.'))
    refs.append(dict(claim_id=PID+'/T6',target='Population resolvent26, sample resolvent43 and implicit parameter44',reference_kind='definition_reference',note='All definitions are in the main text; adjacent proof constructions remain separate.'))
    for n in ['1','2','3','4','5','6']:refs.append(dict(claim_id=PID+'/T'+n,target='Appendix proof bodies and technical lemmas; main-text proof witnesses',reference_kind='proof_only',note='Appendix bodies are excluded. Main-text lemmas and proof reductions do not become extra theorem assumptions.'))
    issues=[]
    def issue(k,ps,note):issues.append(dict(issue_id=k,evidence=[dict(page=p,location='Source issue '+k) for p in ps],note=note))
    issue('source-version',[1,34],'Registered arXiv2210.08571v3 is stamped19June2025, title date23June2025,86pages. It is a revision of the2024 article. Six Theorems occur in main text, including6 in the proof section. Main text ends beforeReferences on34; all appendices beginning38 are excluded.')
    issue('zero-limit-and-rank',[3,6,12,13,14],'Ridge inverse formulas are for lambda>0; ridgeless is a positive limit. In the underparameterized case the effective root tends to zero and Theorem4 conditions zero bias on rank(X)=d. Do not assume all random designs are full rank or use a singular ordinary inverse atzero. Assumption1 permits covariance zeros; d>n and sigma_n>0 do not alone force covariance rank>n, so the asserted positive lambda_star(0) and positive C_Sigma may need additional support-rank conditions.')
    issue('signal-domain-and-zero-signal',[5,9,10],'The inverse-covariance norm and theta=Sigma^-1/2 beta require a domain/nullspace convention when covariance has zero eigenvalues or an unbounded inverse. The source does not fully specify that convention. The directional ratio normalizes by||theta||², undefined atzero signal absent a separate convention; preserve the limitation rather than deleting a stated signal condition.')
    issue('infinite-whitened-coordinates',[5,6],'Trace-class covariance permits H-valued features in infinite dimensions, but their isotropic whitened coordinate sequence need not be square summable. The main text gives a finite-projection extension for concentration; do not reinterpret z as an H-valued isotropic vector with finite trace covariance.')
    issue('concentration-alternatives',[5,6],'Assumption1II(a) allows independent non-identically distributed standardized coordinates; II(b) allows dependence with convex concentration. These are alternatives, not joint Gaussianity or concentration for every Lipschitz function. Whitening/support isotropy conventions under a singular covariance remain implicit.')
    issue('effective-rank-and-indices',[5,11,13],'d_Sigma(n) is an admissible envelope>=n, with tails including k, not an exact minimized quantity. Theorem2 uses sigma_2n and sigma_floor(eta*n); Theorem3 uses sigma_(C5*n) and sigma_d even for potentially infinite d. Finite-rank zero extensions, noninteger rounding and sigma_infinity conventions are not explicitly given in those statements; retain these source limitations.')
    issue('event-probability-and-bias-error',[12,13],'Theorem3 uses P(A^c intersect E)<=Delta, not a conditional probability given E. Its final spectral lower bound has a separate probability statement. The bias error includes a minimum of two additive bounds, in addition to a relative B_n term; it is not wholly multiplicative.')
    issue('regularization-parameters',[9,11,12,13],'Positive-ridge kappa is the interior ratio in25; ridgeless kappa is a free positive parameter constrained inTheorem3. Theorem2 nu is lambda/lambda_star while Theorem4 nu is min(d/n,1-d/n). Do not merge these merely because symbols recur. Zero-limit trace equations require a limiting interpretation.')
    issue('theorem2-and4-quantifiers',[11,13,14],'Theorem2 states suppression of C,Cprime,epsilon while the optional signal bound uses Cdoubleprime; its precise dependence is not fully restated. Theorem4 uses k,D without newly quantifying them, and epsilon is only stated positive although useful rates require its exponent regime. Preserve original wording and inherited context rather than silently rewriting quantifiers.')
    issue('theorem5-spectral-scale',[16,17],'Theorem5 permits an arbitrary slowly varying factor in sigma_i but evaluates lambda_star and actual risk at nu*n^(-alpha), while its proposed limit constants depend on nu as though the regularization were scaled by sigma_n. A varying slow factor changes that effective ratio. In branch2 a_i can converge to a positive constant different from1, creating a related scale issue. Preserve the printed formulas; do not silently replace their arguments by nu*sigma_n or assert the formulas are proved correct.')
    issue('theorem5-branch-measures',[17],'The two F_beta measures use floor(n*x) and floor((n/log n)*x), respectively; both depend onn. The scalar decay exponent theta is distinct from the bold inverse-covariance signal theta. c_star is defined separately in each spectral branch. The optional bias predicates remain tied to their own branches.')
    issue('resolvent-notation-and-scope',[9,23,25],'Script R_n is a covariance-resolvent trace, plain R_n is total effective prediction risk, and sans-serif R0 is a local shorthand inTheorem6. Its general mu_star parameter need not obey the positive-ridge kappa/rho conditions. Keep1+R0(I)^2 distinct from(1+R0(I))² in the error parameters. No proof-only theta normalization or ridge learner/noise requirement is added to the design-only resolvent conclusion.')
    issue('proof-versus-assumption',[6,7,8,15,16,23,24],'Hanson–Wright lemmas, equivalent Gaussian sequence model, application Proposition hypotheses, finite-difference lemmas, filtrations and proof normalization are not extra requirements of every theorem. Theorem6 itself is retained because it is a labeled main-text Theorem. Source review certifies extraction fidelity and dependency scope, not proof validity.')
    data=dict(paper_id=PID,unranked_auxiliary_passages=aux,statement_local_bindings=bindings,source_claim_references=refs,source_issues=issues,unresolved_external_prerequisites=[],ambient_prerequisites=['Real separable Hilbert spaces, finite-output feature operators, trace-class covariance, bounded PSD test operators, spectral theorem, weighted norms and domains of covariance inverse powers.','IID feature rows; for regression risk, independent zero-mean finite-variance noise and conditional expectations/covariances given the observed design.','Positive-ridge inverses and positive-zero limits; fixed-point scalar roots, trace operations, spectral prefix/tail projections and minimum nonzero sample eigenvalues.','Deterministic big-O notation with specified constant dependencies; event-qualified high-probability bounds use the original intersection convention.','Theorem3 local scalar C_Sigma is preserved in auxiliary passageA3; theorem-local c_star, F_beta, gamma/alpha/beta parameters retain their original bound definitions. No invented natural-language API name is required for every scalar constant.','Regular variation and Stieltjes integrals against n-dependent spectral coefficient measures; source endpoint, scaling and domain ambiguities are recorded separately. No appendix-only statement definition was needed; all appendix bodies are excluded.'],validation_limits='Original main-text statements, definitions and dependency scope only. No proof or library-availability verdict. Source ambiguities about zero roots, domains, spectral scaling and index conventions are not silently repaired.')
    (ROOT/'ambient-prerequisites.json').write_text(json.dumps(data,indent=2,ensure_ascii=False)+'\n')
if __name__=='__main__':main()
