"""Resolve the main-text conventions and inherited hypotheses, without reading appendices."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];PID=ROOT.name
inventory=json.loads((ROOT/'theorem-inventory.json').read_text())
claims={c['claim_id'].split('/T')[-1]:c for c in inventory['claims']}
aux=[]
def add(aid,text,pages,loc,meaning):
    aux.append(dict(auxiliary_id=aid,statement_original=text.strip(),evidence=[dict(page=p,location=loc) for p in pages],resolution=meaning))
add('A1',r'''We denote the topological dual space of a separable Banach space, $V$, by $V'$. For complex separable Hilbert spaces $\mathcal H,\mathcal H_1,\mathcal H_2$, we let $\mathcal H_1\otimes\mathcal H_2$ denote the Hilbert tensor product space, and we denote the $r$th Schatten class by $S_r(\mathcal H)$, which is the class of bounded linear operators $A:\mathcal H\to\mathcal H$ with bounded $r$th Schatten norm, i.e, $\|A\|_{S_r}<\infty$, $1\leq r\leq\infty$. We denote the respective subspaces of self-adjoint and non-negative definite operators by $(\cdot)^\dagger$ and $(\cdot)^+$, respectively. We remark that the cone of non-negative definite elements satisfies $S_r(\mathcal H)^+\subseteq S_r(\mathcal H)^\dagger$, and that $S_\infty(\mathcal H)\cong(S_1(\mathcal H))'$. We furthermore denote the tensor product operator $h\otimes g:\mathcal H_1\to\mathcal H_2$, which is the bounded linear operator $(h\otimes g)v=\langle v,g\rangle h$, $v,g\in\mathcal H_1,h\in\mathcal H_2$. We emphasize that the meaning of $\cdot\otimes\cdot$ will be clear from the context.''',[3],'Notation — operator spaces and rank-one convention','The actual main theorems use S1 trace topology, not S2 Hilbert-Schmidt topology. The source uses S_infinity for the bounded-operator dual of S1; no compact-only convention at infinity is imposed. The inner product is linear in its first variable under the rank-one formula.')
add('A2',r'''Throughout this paper, we use the notation $I=[0,1]$ for the unit interval in order to refer to a process indexed by a parameter $\eta\in I$, while we use the parameter $u\in[0,1]$ to refer to re-scaled time. The set of all continuous functions $f:I\to V$ is denoted by $C_V=C(I,V)$.''',[3],'Notation — path and time parameters','Eta is the sequential fraction, u is rescaled time, and omega is frequency. T is sample size, N is local block length, M is the number of time-grid points, and x in Theorem 3.1 is the transformation exponent. These are distinct parameters.')
add('A3',r'''For a measurable space $(T,\Sigma)$ with $\sigma$-finite measure $\mu$, we define $L_V^p(T,\mu)$ as the Banach space of all strongly measurable functions $f:T\to V$ with finite norm $\|f\|_{L_V^p(T,\mu)}=(\int\|f(\tau)\|_V^p d\mu(\tau))^{1/p}$, $1\leq p<\infty$. If $T\subset\mathbb R^d$ and $\mu$ is the Lebesgue measure on $T$, we simply write $L_V^p(T)$. Given a probability space $(\Omega,\mathcal A,P)$, we write $L_V^p=L_V^p(\Omega,\mathcal A,P)$ for the space of all strongly measurable functions $X:(\Omega,\mathcal A,P)\to(V,\mathcal B_V)$ with $\|X\|_{V,p}=(\mathbb E\|X\|_V^p)^{1/p}<\infty$. The (conditional) expectation of $X\in L_V^p$ thus exist (in the sense of a Bochner integral), and the $k$th moments $k\leq p$ can be naturally defined using tensor products. We use $\overset{\mathscr D}{\Longrightarrow}$ for process convergence, $\overset{\mathscr D}{\longrightarrow}$ for distributional convergence of a vector, and $\overset{\mathbb P}{\longrightarrow}$ for convergence in probability. Finally, we let $\lfloor\cdot\rfloor$ denote the floor function and for two positive sequences, $(a_T)$, $(b_T)$, we write $a_T\sim b_T$ if $\lim_{T\to\infty}a_T/b_T=1$.''',[3],'Notation — Bochner spaces and convergence','Strong moments use Bochner integration; the theorem branches use high p even though earlier assumptions initially say p>0. Process convergence is in the continuous-path space with the indicated Banach norm. Standard asymptotic O, o and their probability variants retain their usual meaning.')
add('A4',r'''\[
\sup_\omega\sup_{u\in U_M}\sup_{\eta\in I}\left\|\eta\big(\widehat{\mathscr F}_{u,\omega}(\eta)-\mathscr F_{u,\omega}\big)\right\|_{S_1}=o_P(1),\qquad(T\to\infty).\tag{3.30}
\]
To prove (3.30), we make use of the mixing condition exhibiting polynomial decay, where the speed of the decay is controlled by the parameter $\rho$ in condition (3.28). For most reasonable choices of $\kappa$ and $\rho$, $p=7$ suffices. We refer to Theorem C.3 in the supplement, which gives the details for the specific choice of $p$ depending on $\rho$ and $\kappa$.''',[17],'Condition (3.30) and its moment-order reference','Theorem 3.1(b) requires p such that this actual uniform consistency property holds. The precise p(rho,kappa) recipe is appendix-only and remains unresolved; p=7 is not imposed universally. U_M is D13, the estimate is D9 and the truth is D2.')
add('A5',r'''Suppose that the conditions of Theorem 3.1 hold true for $k$ mappings $\Upsilon_1,\ldots,\Upsilon_k$ that satisfy Assumption 3.6. Furthermore, let $W$ denote a separable Banach space and consider $k$ Fréchet differentiable mappings $\Psi_1,\Psi_2,\ldots,\Psi_k:C_{S_1}\to C_W$.''',[17],'Corollary 3.1 — complete hypotheses inherited by Theorem 3.2','This expands the full reference, including all conditions of the applicable branch of Theorem 3.1, for each mapping. The identity branch uses p>=6 and h=1; the nonlinear branch additionally uses A4, D18, the D1 calculus domain and analytic homogeneity. The corollary is a prerequisite passage, not an extra Theorem inventory record.')
add('A6',r'''where $\Psi'_{j,(L^{a,b}\circ\mathscr G_{\Upsilon_j}(\mathscr F))}$ denotes the Fréchet derivatice of $\Psi_j$ at $L^{a,b}\circ\mathscr G_{\Upsilon_j}(\mathscr F)$ and $\mathbb W_{\mu_{\Upsilon_1}},\ldots,\mathbb W_{\mu_{\Upsilon_k}}$ are $S_1(\mathcal H)$-valued Brownian motions corresponding to a complex Gaussian measure with covariance operator $\tau_{\Upsilon_j}$ and pseudo-covariance operator $\widetilde\tau_{\Upsilon_j}$ as defined in Theorem 3.1 $(j=1,\ldots,k)$.''',[17],'Corollary 3.1 — derivative point and Brownian convention','Retains the source spelling and tau notation without squares, whereas Theorem 3.1 writes squared tau. The derivative point abbreviated in (3.33)-(3.34) is supplied here. Cross-covariances are not reconstructed from unread appendix formulas.')
add('A7',r'''In particular
\[
\mathscr T_j(\mathscr F)(\eta)=\Psi_j\Big(\int_0^1\int_a^b\Upsilon_{u,\omega}\big(\eta^{x-1}h(\eta)\phi(\mathscr F(\eta)_{u,\omega})\big)d\omega du
\]
defines for $\eta=1$ the $j$th measure of deviation, that is $\mathscr T_j(\mathscr F)=\mathscr T_j(\mathscr F)(1)$, and
\[
\mathscr T_{j,T}(\widehat{\mathscr F})(\eta)=\Psi_j\Big(\frac1M\sum_{u\in U_M}\int_a^b\Upsilon_{u,\omega}\big(\eta^{x-1}h(\eta)\phi(\eta\widehat{\mathscr F}(\eta)_{u,\omega})\big)d\omega\tag{3.32}
\]
defines for $\eta=1$ a corresponding estimator.''',[17,18],'Expansions following equation (3.31), including (3.32)','These are archived separately from the formal composition D20. The population expansion omits eta inside phi, the empirical expansion includes it, and both include h absent from (3.23). The unclosed outer parentheses are printed that way; the transcription does not silently reconcile the formulas.')
add('A8',r'''In case of compact operators on infinite-dimensional spaces, an open neighborhood $D\subset\mathbb C$ containing the spectrum, say $\sigma(A)$, of a compact operator $A$ will also contain the origin. Consequently, functions of the form $\phi(z)=z^x,x<1,z\in\mathbb C$ are not analytic on $D$. However, part (b) of Theorem 3.1 then holds for the subspace of finite rank operators.''',[17],'Remark 3.3(b)','The stationarity application invokes finite-rank restrictions D31. The main text does not specify a common restricted space or remove the eta=0 spectral endpoint. Do not infer a complete holomorphic square-root domain from this remark.')
add('A9',r'''More specifically, it follows from the latter work that, for fixed $u$, the functional Cramer representation of the approximating stationary process $\{X_t^{(u)}\mid t\in\mathbb Z;u\in[0,1]\}$ is given by
\[
X_t^{(u)}=\int_{-\pi}^{\pi}e^{i\omega t}dZ_{u,\omega}\quad a.e.\text{ in }\mathcal H,\tag{2.4}
\]
where $\{Z_{u,\omega}:\omega\in(-\pi,\pi]\}$ is an $\mathcal H$-valued right-continuous orthogonal increment process for each $u\in[0,1]$.''',[5],'Equation (2.4) — orthogonal-increment notation','Z in the component and coherence definitions is the Cramer orthogonal-increment process. This binds the symbol without importing an external theorem. D28 preserves the later equality between the spectral density and moments of Z, rather than replacing it by a density of increment covariances.')
add('A10',r'''To this end, consider the case where the Hilbert space arises as the direct sum of Hilbert spaces, i.e., $\mathcal H=\mathcal H_1\oplus\mathcal H_2$. Then, we may write $\{X_{t,T}\mid t=1,\ldots,T,T\in\mathbb N\}=\{(X_{t,T,1},X_{t,T,2})^\top\mid t=1,\ldots,T,T\in\mathbb N\}$, where we refer to $\{X_{t,T,j}\mid t=1,\ldots,T,T\in\mathbb N\}$ as the $j$th component process, which takes values in the Hilbert space $\mathcal H_j$ $(j=1,2)$.''',[6],'Section 2.2.3 — component process','This is the direct-sum model for coherence, not the tensor-product model used for separability. Component Z processes are the components of A9 for the stationary approximants.')
add('A11',r'''Theorem 3.3-Theorem 3.5 are given under the assumption of no multiplicity of the eigenvalues. This simplifies the asymptotic derivations but the authors believe that this can be relaxed using a blocking technique as for example given in [2]. We leave the details for future work.''',[21],'Remark 3.5','The applications retain the source simple-spectrum restriction. The dotted multiplicity list in D3 and the distinct-eigenvalue list are not interchangeable in general; no blocking extension is imported.')
add('A12',r'''In this case, Theorem 3.1 and Corollary 3.1 are applicable with $k=2$ and $x=3$, and (3.34) holds with $h(\eta)=1$ and $g_{jj}(\eta)=\eta^2$.''',[20],'Opening of Section 3.5.1 continuation','This is the PCA-specific specialization. The statement of Theorem 3.3 nevertheless expressly invokes Theorem 3.1(b); this reference remains in the inventory and is not silently changed to branch (a).')
add('A13',r'''Theorem 3.2 applies with $g_{n,n}(\eta)=\eta^2$ and $f_n(\eta)=\eta^3$, yielding an asymptotically pivotal statistic.''',[20],'After Theorem 3.3','This is a subsequent inference claim, not an additional condition in the Gaussian-limit theorem. Such pivotal applications retain Theorem 3.2 nondegeneracy. Analogous source choices are g=eta^2,f=eta^3 for separability, g=eta^3,f=eta^4 for coherence, and g=eta,f=eta^2 for restricted stationarity.')
add('A14',r'''\[
\widehat{\mathbb T}_d\overset{\mathscr D}{\longrightarrow}\mathbb T_d\quad\text{if}\quad d=d^*,\ s_{d^*}=\nu,\tag{4.6}
\]
\[
\widehat{\mathbb T}_d\overset{\mathbb P}{\longrightarrow}-\infty\text{ if }d<d^*,\quad
\widehat{\mathbb T}_d\overset{\mathbb P}{\longrightarrow}+\infty\text{ if }d>d^*,\quad
\widehat{\mathbb T}_d\overset{\mathbb P}{\longrightarrow}+\infty\text{ if }d=d^*\text{ and }s_{d^*}>\nu.\tag{4.7}
\]''',[24],'Equations (4.6)-(4.7) — threshold boundary discussion','Equation (4.6) allows equality at d*, in tension with the strict first-exceedance definition D36. If an earlier index has accuracy exactly nu, the first clause in (4.7) also needs care. These are source discrepancies, not corrections to Theorem 4.3. In contrast, (4.9) and (2.17) are equivalent under the strict definition and monotonicity, including equality at s_d0=nu.')
add('A15',r'''We conclude this section with the important observation that the assumptions $\Delta>0$ and $r>0$ are crucial for the statement in Theorem 4.2. First note that $\Delta=0$ implies $r=0$ (but not vice versa). If $r=0$, the asymptotic distribution (under the null hypothesis) of the numerator and denominator on the left hand side of (4.1) is a Dirac measure at the point $0$.''',[23],'Section 4.1 — zero-deviation qualification','The positive r qualification is explicit in this source discussion, although Theorem 4.2 itself prints only Delta>0 and the Theorem 3.2 assumptions. The asserted implication Delta=0 implies r=0 has a null-hypothesis qualification implicit in the surrounding discussion; it is not a general relation between a chosen threshold and the true deviation. The quotation is retained without strengthening the theorem body.')

issues=[]
def issue(key,pages,loc,text):
    issues.append(dict(key=key,evidence=[dict(page=p,location=loc) for p in pages],note=text))
issue('uncentered_covariances',[4,10,11],'Equation (2.1) and Assumptions 3.1-3.3','The source calls E(X_h tensor X_0) a covariance without subtracting means. A main-text search for zero, mean and centering, together with inspection of the definitions and assumptions, found no process mean-zero restriction. No missing centering hypothesis is inserted.')
issue('dependence_absolute_index',[10],'Equation (3.2)','The replacement field uses the absolute index k before a supremum over t; the stationary reduction later anchors X_k with replacement at zero. This indexing difference is retained.')
issue('moment_scope_and_trace_topology',[3,10,17],'Notation, assumptions and Remark 3.3','Earlier p>0 wording differs from the p>=1 Bochner convention. Actual S1 results retain Assumption 3.2 II and high moment requirements; the S2 relaxation in the remark is not applied. The identity branch prints p>=6, while a proof-technical p/2 integer comment is not promoted to an extra theorem hypothesis.')
issue('estimator_path_and_positive_cone',[11,12],'Equation (3.6) and Assumption 3.4','The printed estimator divides by floor(eta N), has a single interpolation factor on the final self-product, is zero for floor zero, and has an unclosed parenthesis. Its claimed path continuity and positivity do not follow from these formulas and window conditions without further qualifications. No conventional replacement estimator or positive-definite window restriction is substituted.')
issue('normalization_and_bandwidth',[12,13],'Equations (3.11) and Assumption 3.5','The display uses k_f, whereas the following line defines kappa_f. The two kappa regimes share their boundary and both stated bounds are retained there. N=T^alpha is printed without integer rounding; the growth exponent alpha differs from the later significance level.')
issue('operator_field_type',[15],'Assumption 3.6','Upsilon starts as an operator on continuous S_r paths, but its time derivatives are given in L(S1) and the displayed map is evaluated pointwise. The original typing is retained without inventing a stronger operator field.')
issue('calculus_domain',[15,17,21],'Equations (3.20)-(3.23) and Remark 3.3(b)','The source switches L1 to L in the D_r formula. Square roots are not holomorphic at zero; the finite-rank recommendation alone does not specify subspace identification, treatment of zero extension, or the eta=0 endpoint. Appendix E is not read.')
issue('discrete_evaluation_on_L1',[16],'Equation (3.25)','Point evaluations at U_M are specified on an L1 space, which normally consists of almost-everywhere equivalence classes. A representative or sufficient time regularity must be supplied; the source formula is preserved.')
issue('appendix_only_covariance',[16,17],'Theorem 3.1 and Corollary 3.1','Gamma and Sigma are defined only by (B.11) and (B.12). Those formulas and joint covariance details remain unresolved because appendix bodies are excluded. Corollary 3.1 uses tau without squares where Theorem 3.1 uses tau squared.')
issue('appendix_only_moment_recipe',[17],'Condition (3.30)','The main-text consistency condition is saved as A4. The exact choice of p as a function of rho and kappa is deferred to Theorem C.3 and remains unresolved; the heuristic p=7 is not a universal replacement.')
issue('composition_expansion_mismatch',[16,17,18],'Equations (3.23), (3.31), (3.32)','Formal composition and explicit expansions disagree about extra h and eta inside phi. A7 preserves both expansions, including unclosed outer parentheses; D16/D20 preserve the formal definitions.')
issue('scaling_is_not_additivity',[18],'Equation (3.35)','The author uses the word linear for a specified scaling identity, with a path-valued right-hand side lacking an explicit eta evaluation. Additivity is not substituted.')
issue('self_normalizer_matrix',[18,19],'Equations (3.37), (3.39), (3.40)','The second factors are conjugated, while the quadratic form uses ordinary transpose despite permitting proper complex Brownian motions. V_k and U have squared-entry notation, not matrix squares. Limiting nonsingularity does not supply a finite-sample inverse convention. The extra closing parenthesis in (3.37) is retained.')
issue('positive_g_endpoint',[18,20,21],'Theorem 3.2 and its application comments','The theorem writes a positive diagonal function on all I using positive-entry matrix notation, whereas (3.34) allows nonnegative g and the examples vanish at eta=0. The source difference is retained.')
issue('spectral_multiplicity',[4,5,20,21],'Equation (2.3), PCA ratio and Remark 3.5','The dotted sequence counts multiplicities; the undotted sequence lists distinct values. The ratio of eigenvalue sums equals the trace version only with the appropriate multiplicity interpretation. The specialized theorems retain their simple-spectrum conditions.')
issue('separability_conventions',[5,6],'Tensor identifications and (2.10)','The complex Hilbert-space rearrangement is printed without conjugate-space qualifications. The separability ratio also prints integration limits with differentials in the opposite order from the later theorem. Neither is silently rewritten.')
issue('coherence_source_assertions',[6,7],'Equation (2.11) and its surrounding text','The source equates a spectral density with moments of cumulative Z, maximizes a complex inner product without an explicit real-part or modulus convention, and identifies cross-spectrum singular-vector maximizers with marginal leading eigenfunctions. Those identifications require additional justification and are preserved as source assertions. The ratio is not replaced by a different standard canonical-correlation definition.')
issue('specialized_gaussian_vs_pivotal',[20,21],'Theorems 3.3-3.6','Theorems 3.3-3.5 allow sigma=0; Theorem 3.6 omits a separate sigma qualifier. Following claims about pivotal statistics still require the positive-definite limit and nonsingularity conditions of Theorem 3.2. The Gaussian-limit statements do not acquire those additional assumptions.')
issue('coherence_chain_punctuation',[21],'Theorem 3.5','The marginal eigenvalue chain contains a comma before its last eigenvalue rather than another greater-than sign. The statement is retained exactly.')
issue('stationarity_target_eta',[21],'Equation (3.46)','The first argument of population r_d lacks eta, although the next display defines an eta-dependent mean square root. Both are retained without substituting a normalized stationarity measure.')
issue('deviation_accuracy_notation',[9,23],'Equations (2.16) and (4.4)','T_d denotes a deviation r_d in Section 2.4 and an accuracy s_d in Section 4.2. This source-local change is recorded; the two are related by s_d=1-r_d in the nested-model setup.')
issue('scalar_limit_44',[22,23],'Equations (4.1) and (4.4)','Equation (4.4) prints f_d(eta) B_d eta) - g_dd(1) B_d(1), with a missing opening argument parenthesis and a different f/g placement from (4.1). The original formula is retained rather than repaired to the expected pivotal expression.')
issue('strict_threshold_boundary',[9,24,25],'Equations (2.18), (4.6), (4.7)','Equation (2.18) uses strict > with Latin v and a following prose subscript/superscript typo. The later equality case s_d*=nu conflicts with that definition. The hypotheses (4.9) and (2.17), however, are equivalent under the strict definition and monotonicity; there is no separate error in that equivalence.')
issue('quantile_and_search_scope',[23,24,25],'Equations (4.4), (4.8), (4.11)','The first-exceedance estimator uses lower q_alpha, while the accuracy rejection rule uses upper q_(1-alpha,d0). The limiting variables may depend on d and need not be independent. No finite search cutoff, empty-minimum convention or quantile continuity restriction is specified.')
issue('vanishing_level_claim',[24],'Theorem 4.3','Consistency is asserted for any alpha_T tending to zero, without a rate restriction. This is recorded as the source claim, without adding uniform-tail assumptions or certifying its proof.')

common=('D5-D7 and D10-D11 resolve Assumptions 3.1-3.5, including both parts of 3.2, zeta=1, the window and bandwidth regimes. D14 resolves all of Assumption 3.6. D2 and D9 are the true and estimated spectral fields; D12 and D13 give rho_T and U_M. D15-D17 give the calculus domain, transform and integration maps. The base theorem binds [a,b] within [0,pi], a<=b and x>=1. In branch (a), phi=z and p>=6; in branch (b), p must satisfy A4, F lies in D_1, D18 holds with 0<rho<1, and phi is analytic with phi-prime(cz)=h(c)phi-prime(z), continuous h and h(1)=1. The branches are conditional alternatives, not simultaneous assumptions. Appendix-only covariance and moment-recipe references remain unresolved.')
pivotal=('A5 expands Corollary 3.1 using the applicable base branch for each Upsilon_j and k Frechet outer maps D19. D20 gives T_j,T and T_j. D21 and D22 give the factorization (3.34) and scaling (3.35), with known f_j(1)=1 and g diagonal; Theorem 3.2 additionally requires positive-definite real sigma and nonsingular U. D23 gives errors and V; U is defined inline by (3.39), using the same measure nu on (0,1). A6 fixes derivative points. The source permits real or proper complex independent Brownian coordinates, retains conjugation in U/V but ordinary transpose in the quadratic form, and leaves finite-sample singular inversion unspecified. Scalar uses take the appropriate diagonal normalizer and limiting root. These assumptions do not select a PCA, separability, coherence or stationarity application.')
resolution={
 'shared':('A1-A3 give complex Hilbert spaces, Schatten norms, Bochner moments, path spaces and convergence notation. Standard ambient notions include spectrum, trace, positive operator square roots, conditional expectation, iid innovations, ordinary real/complex Brownian motion, Frechet derivatives, Gaussian measures, asymptotic O/o, quantiles and hypothesis-test consistency. The threshold nu in Sections 2/4 is distinct from the measure nu(d eta) in self-normalization and from singular values nu_d in coherence; rho in the dependence tail is distinct from rho_T. The test level alpha is in (0,1), distinct from the block-growth exponent. ') + common,
 '3.1':common+' The Brownian motion is on S1(H), with zero mean; only the integral form of its covariance and pseudocovariance is available in the main text. A1 resolves the tensor space of Gamma/Sigma. Both subparts and all quantifiers remain in the original body.',
 '3.2':common+' '+pivotal+' The theorem binds f, g, sigma and the vector Dhat at eta=1. U is assumed nonsingular, and the result includes both the vector quadratic form and every scalar j specialization.',
 '3.3':common+' Branch (b) is explicitly referenced. D3 and D25 resolve the PCA eigenvalue ratio; D9 supplies the empirical eigenvalues and D13 the time grid. The displayed denominator is an integrated trace, whereas (2.7) uses eigenvalue sums. The theorem adds uniform ordered positivity for the first d values on the full [0,1]x[0,pi] plane; A11 records no multiplicity. Its eta^3-scaled difference converges to eta^2 sigma B with sigma>=0. A12 preserves the neighboring identity-phi discussion, without rewriting the explicit branch reference. D21-D23 are not requirements of this Gaussian-limit statement merely because the next sentence discusses pivotal inference.',
 '3.4':common+' Branch (b) is explicitly referenced. D26-D27 supply the tensor-product rearrangement and squared separable scores. The hats in (3.43)-(3.44) apply the same construction to D9, as the displayed empirical ratio specifies. These are delta scores, not the eigenvalues lambda of the original operator. Uniform ordered positivity on the full time-frequency plane and the source no-multiplicity qualification remain. The limit has eta^2 sigma B with sigma>=0 after eta^3 scaling; it is not yet a self-normalized statistic.',
 '3.5':common+' Branch (b) is explicitly referenced. D28-D29, A9-A10 resolve the direct-sum model, Z, block operators, cross-spectrum singular values, marginal eigenvalues, coherence ratio and its empirical squared definition. The theorem adds ordered positivity, with its printed comma retained. It does not explicitly repeat the uniform qualifier from Theorems 3.3/3.4. The eta^4-scaled integral difference has eta^3 sigma B limit with sigma>=0. No assumption of equality between marginal eigenvectors and singular vectors is silently added beyond the source assertion.',
 '3.6':common+' Branch (b) is explicitly referenced. D30-D32 resolve d_R, spectral restrictions, population r_d(eta), empirical rhat_d(eta) and the mean-root targets. A8 records the finite-rank calculus issue. The whole positive frequency range [0,pi] is used. Eta is the sequential parameter; d is a fixed truncation in this statement, not necessarily the data-selected dhat. Sigma and B follow the surrounding Gaussian-limit usage, with no additional sentence appended to the original short theorem. The missing eta on the population target remains a source issue.',
 '4.1':common+' '+pivotal+' Use the applicable scalar real statistic D24: r=T(F)>0 is the deviation functional D33, rhat is the corresponding estimate at eta=1, V=V_11 and f=f_1,g=g_11. The theorem defines q_beta from (4.1), retains both plus signs in the interval, and claims asymptotic coverage 1-alpha. It does not specialize to a particular structural assumption.',
 '4.2':common+' '+pivotal+' D34 defines H0:r<=Delta versus r>Delta with Delta>0; D37 is the rejection rule (4.3), using the scalar statistic D24. The positive threshold is distinct from positivity/nondegeneracy of the scalar limiting regime. The source discussion of zero deviation is retained separately. The test is stated consistent and asymptotic level alpha without importing a particular application.',
 '4.3':common+' '+pivotal+' D35 gives the nested model classes and accuracy sequence; D36 defines d* at the strict threshold. D38-D40 supply each accuracy estimate, its limiting variable and quantile, the threshold-centered statistic and the first-exceedance estimator (4.8). These scalar uses must satisfy Theorem 3.2 in their relevant instances. Dependence across d is permitted. Both asymptotic error bounds and the additional alpha_T-to-zero conclusion are retained; no rate or finite maximum dimension is invented. A14 records the contradictory boundary discussion independently.',
 '4.4':common+' '+pivotal+' D35-D36 define the nested accuracy and d*. D38-D40 define dhat and its lower-quantile selection rule. The null is d*<=d0, alternative d*>d0, and rejection is dhat>d0; d0 is a fixed positive integer as specified in surrounding text. The direction differs from Theorem 4.5. The original asymptotic-level and consistency claims are preserved.',
 '4.5':common+' '+pivotal+' D35-D36 supply the accuracy threshold and strict d* definition, D38 supplies shat_d0,V_d0,d0 and the limiting variable, and D41 gives the upper-quantile rejection rule. Under the strict definition and monotonicity, d*>d0 is equivalent to s_d0<=nu, including equality; thus (4.9) and (2.17) have matching nulls. This test does not use the estimator dhat from (4.8). A14 documents the separate inconsistent s_d*=nu case.'
}
(ROOT/'ambient-conventions.json').write_text(json.dumps(dict(paper_id=PID,auxiliary_passages=aux,standard_ambient_resolution=resolution,unresolved_source_conventions=issues),indent=2,ensure_ascii=False)+'\n')
print('Saved',len(aux),'auxiliary passages and',len(issues),'source notes.')
