"""Preserve source conventions without importing appendix results or synthesizing definitions."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];PID=ROOT.name
aux=[]
def add(aid,text,pages,loc,meaning):
    aux.append(dict(auxiliary_id=aid,statement_original=text.strip(),evidence=[dict(page=p,location=loc) for p in pages],resolution=meaning))
add('A1',r'''consider testing the hypothesis of conditional independence (CI)
\[
H_{0n}:\boldsymbol Y\perp\!\!\!\perp\boldsymbol X\mid\boldsymbol Z\tag{1}
\]
at level $\alpha\in(0,1)$''',[2],'Section 1.1 — testing problem and level','The global testing level lies in (0,1). This defines the hypothesis of interest, not a standing assumption that every theorem is under the null. Theorem 1 explicitly does not require null membership.')
add('A2',r'''We use boldface font to denote population quantities and regular font to denote sample quantities.''',[5],'Section 1.4 — notation convention','Bold X,Y,Z are population random variables, while plain X,Y,Z are sample arrays and X_i,Y_i,Z_i are sample components. The distinction is retained in every transcribed formula.')
add('A3',r'''Output: $\widehat{\mathrm{dCRT}}$ p-value
\[
\frac1{M+1}\left(1+\sum_{m=1}^M\mathbb 1\{T_n^{\widehat{\mathrm{dCRT}}}(\widetilde X^{(m)},X,Y,Z)\geq T_n^{\widehat{\mathrm{dCRT}}}(X,Y,Z)\}\right).
\]
''',[6],'Algorithm 1 — finite-resampling p-value','The finite-M algorithm retains a plus-one correction and a non-strict tail comparison. The theoretical decisions are instead defined directly by the infinite-resampling conditional quantile. No finite-M approximation theorem is asserted.')
add('A4',r'''While the CRT is in general computationally costly, using a test statistic of the form
\[
T_n^{\mathrm{dCRT}}(X,Y,Z)\equiv\frac1{\sqrt n}\sum_{i=1}^n(X_i-\mu_{n,x}(Z_i))(Y_i-\widehat\mu_{n,y}(Z_i))
\]
gives a fast and powerful test called the distilled CRT (dCRT, Liu et al., 2022). Here, $\mu_{n,x}$ is known under the MX assumption and $\widehat\mu_{n,y}$ is learned in sample.''',[6],'Section 1.4 — known-law dCRT for comparison','The unaccented dCRT uses the known predictor mean. The three inventoried Theorems involve the learned-law version or GCM; this comparison does not impose exact knowledge of the predictor law on them.')
add('A5',r'''Note that this is a rate double robustness property rather than a model double robustness property; see Smucler, Rotnitzky, and Robins (2019) for a discussion of this distinction.''',[7],'Section 1.4 — meaning of double robustness','The product-rate and weighted-error assumptions remain explicit. Correctness of one model alone is not substituted for the numerical rate requirements.')
add('A6',r'''The semiparametric model (29) plays the role of the alternative distribution with respect to which power is evaluated, and need not hold under the null hypothesis. To bridge this gap, it suffices to find an open ball within the conditional independence null hypothesis containing the semiparametric null hypothesis (38).''',[18],'Section 5.3 — scope of the GPLM family','The first sentence distinguishes the null class from the alternative model. The open-ball explanation is interpretive prose; the exact directional, eventually-in-R requirement (38) is retained without strengthening it to a uniform neighborhood assumption.')
add('A7',r'''Based on an extension of the Lyapunov central limit theorem to conditional convergence in distribution (Theorem 8), we get the following result:''',[8],'Before Theorem 1 — proof reference','Theorem 8 is an appendix proof tool and is not part of this main-text inventory. Definition 1 and the explicit Lyapunov condition suffice to state Theorem 1; no appendix theorem is imported.')
issues=[]
def issue(key,text,pages):
    issues.append(dict(issue_id=key,description=text,evidence=[dict(page=p,location='Inspected main-text source convention') for p in pages],resolution_status='source_preserved'))
issue('S1','Theorem 1 describes the conditional resampling law for general true and learned laws; it does not assume conditional independence or guarantee Type-I error control by itself. Theorem 2 explicitly restricts the true law to the null class.',[8,9,12,13])
issue('S2','Theoretical dCRT decisions use the infinite-resampling limit and a strict comparison to a conditional quantile. The finite-M algorithm has a plus-one corrected p-value and a non-strict resampled-tail comparison. The main Theorems do not quantify Monte Carlo error for a fixed number of resamples.',[6,8])
issue('S3','The fitted predictor kernel is learned from (X,Z) and the response mean from (Y,Z). Resampled predictors are independent across observations conditional on the original data, and nuisance estimates are held fixed. Original fitted residuals need not be unconditionally independent.',[6,8,9])
issue('S4','The same raw fitted-mean residual-product functional is used by GCM and dCRT. Evaluating GCM requires fitted means and an empirical variance, not a complete learned predictor kernel or resampling. The extra kernel-to-mean identity is retained with Algorithm 1, rather than imposed as an algorithmic prerequisite of the GCM optimality theorem.',[6,7,16])
issue('S5','The resampling variance (11) averages learned predictor variances times squared observed response residuals. The GCM variance (10) is the empirical variance of residual products. These are different finite-sample quantities; Theorem 2 asserts their ratio converges to one under its hypotheses.',[7,8,12,13])
issue('S6','The empirical variance notation in (10) does not explicitly select the n versus n-1 divisor or a zero-denominator decision rule. The census preserves the operator rather than inventing a finite-sample normalization. Asymptotic nondegeneracy does not by itself define the statistic on every exceptional dataset.',[7,8])
issue('S7','NDG2 is a comma-separated chain imposing strict positivity and finiteness on the learned predictor variance and both squared response residuals. NDG1 is a distinct probability lower bound on the total resampling variance. Theorem 2 names NDG2 but does not add NDG1 as an explicit premise.',[8,12])
issue('S8','Definition 1 requires conditional CDF convergence in probability at every continuity point of the limiting CDF. The conditioning sigma-field varies with n. The result is not recorded as almost-sure conditional convergence or merely unconditional asymptotic normality.',[8,9])
issue('S9','Lyap-1 uses observed fitted response residual powers; Lyap-2 instead uses conditional true response residual moments given Z_i. Both use learned predictor moments conditional on the full (X,Z) sample. They are not identical conditions and neither is replaced by a generic finite-moment assumption.',[9,12])
issue('S10','Lyap-1 explicitly quantifies some delta>0. Lyap-2 uses delta without a fresh quantifier in Theorem 2; SP2 already supplies a positive moment exponent. The source’s notation is retained, with a compatible positive exponent required to interpret the displayed condition.',[7,9,12])
issue('S11','The error quantities are empirical root-mean-square errors evaluated at the training covariates, including opposite-variable variance weights. The additional error in (24) uses a learned predictor-variance weight, unlike E-prime_n,y. No cross-fitting or independent training sample is assumed.',[6,7,12])
issue('S12','Variance consistency (23) is a signed weighted average of errors. It does not require absolute-error convergence or uniform pointwise variance estimation. The source’s weaker displayed condition is preserved.',[12,13])
issue('S13','SP1 is a product-rate requirement together with two weighted errors. SP1-prime adds the learned-variance-weighted response error. Theorem 3 requires SP1 and SP2, not the stronger SP1-prime used by Theorem 2.',[7,12,16])
issue('S14','Theorem 3 works at fixed p, whereas the earlier laws may form a triangular array with growing p. Its GPLM alternative model fixes the predictor/covariate law and uses a canonical exponential-family response. That model need not contain every null law in R.',[1,2,15,18])
issue('S15','Condition (36) has two alternative branches: constant positive second log-partition derivative with finite predictor second moment, or compact support of (X,Z) with continuous nuisance functions. The census preserves the OR and does not impose both branches simultaneously.',[16])
issue('S16','The nuisance space H_g is a linear subspace of L2, not explicitly a closed subspace. Condition (37) requires the conditional predictor mean itself to belong to H_g, not merely its closure. Function equivalence classes and continuous representatives need compatible choices when instantiating the compact-support branch.',[15,16])
issue('S17','The local-path definition (31) is stated for positive coefficient direction, but (38) evaluates the same formula at direction zero. The base g_0 dependence is suppressed in theta_n. The eventual sample-size threshold in (38) may depend on g_0 and h_g; no uniform threshold over the whole nuisance space is stated.',[15,16])
issue('S18','Definition 2 compares limsup competitor power with liminf power of the candidate test, first at a fixed direction, then for every direction and base nuisance function. LAUMP is not rewritten as a limit uniform over directions or nuisance functions.',[15])
issue('S19','The asymptotic level definition (4) takes the supremum over null laws before limsup in n. Theorem 3 condition (35) says SP1/SP2 hold for all laws in R, without explicit uniform versions in its wording. This quantifier distinction is retained; pointwise stochastic rates are not silently promoted to uniform rates.',[5,7,15,16])
issue('S20','Equation (34) defines s squared; the power formula uses s. Its nonnegative-root interpretation is recorded in the ambient resolution, without replacing the source formula. There is no source natural-language name for this scalar, so its original definition is retained with the local-path context rather than assigned an invented API title.',[15,16])
issue('S21','The GPLM source writes L_{beta,eta} in (29), while local parameters are pairs (beta,g). The natural predictor eta depends on X and Z, so the displayed product is a marginal law combined with a conditional response kernel, not independence of the response from covariates.',[15])
issue('S22','The source does not specify detailed measurable-selection conventions for learned conditional laws, fitted functions or conditional quantiles. The resampling formulas require suitable versions, and the ordinary probabilistic little-o notation is interpreted under the sequence of true data laws.',[5,6,7,8])
issue('S23','The audited PDF is arXiv:2211.14698v2, with title date 10 February 2023 and margin stamp 8 February 2023, not the final journal version. References share page 34 with Appendix A. Only the area above the recorded boundary is retained as main-text evidence; all appendix results and proofs are excluded.',[1,33])
resolution={
 'shared':'D1 defines the iid triangular-array experiment and A1 fixes alpha in (0,1). Bold variables denote population quantities and plain letters sample arrays. Individual laws are calligraphic L, null/regularity classes are script L/R, conditional quantiles use blackboard Q, and Phi and z_{1-alpha} are the standard normal CDF and quantile. Expectations, variances, conditional kernels, empirical variance and stochastic little-o are ambient. Fitted means are data-dependent nuisance-function inputs; Algorithm 1 gives their learned-kernel realization for dCRT. No appendix results are used.',
 '1':'D1/D4 give true sampling and learned conditional laws; D3 gives the true response mean appearing in NDG2. D6 is the four-argument resampled statistic, D8 its conditional variance, D9 the conditional quantile and D11 the conditional convergence notion. D12 preserves NDG2, also reused by Theorem 2. NDG1 and Lyap-1 are fully bound inline in the original statement and need no synthesized definitions. The standard normal limit is for resampling conditional on the observed data, not for the observed statistic under arbitrary alternatives. No null-law requirement or GCM comparison is imported.',
 '2':'D2 supplies conditional-independence membership; D18 gives SP1-prime, with the additional error (24) archived in its application context. D14/D13 give the original error rates and error definitions; D15 is SP2. D12 is NDG2 and D16 is variance consistency (23). D3 and D4 resolve the two factors in the inline Lyap-2 condition. D8 and D7 resolve the resampling and GCM variance estimates; D10 is the infinite-resampling dCRT decision. The ratio and event of equal decisions are the full conclusions. NDG1 is not added as a new premise, and extensions to contiguous alternatives are Corollaries rather than additional Theorems.',
 '3':'D2 supplies the null class and D14/D15 are the referenced SP1/SP2 requirements in (35). D7 gives the GCM decision using arbitrary fitted nuisance means; no resampling kernel is needed. D20 gives the fixed-dimensional GPLM family, log-partition function and nuisance subspace. D21 gives local paths and the original definition of s squared in (34); s is interpreted as its nonnegative square root. D22 is Definition 2, whose level requirement uses D19. Conditions (36)-(38) bind the OR alternatives, exact nuisance-space membership and eventual inclusion of zero-coefficient local paths directly in the theorem. The source’s pointwise-versus-uniform rate distinction is preserved, not repaired.'
}
(ROOT/'ambient-conventions.json').write_text(json.dumps(dict(paper_id=PID,auxiliary_passages=aux,unresolved_source_conventions=issues,standard_ambient_resolution=resolution),indent=2,ensure_ascii=False)+'\n')
print('Saved',len(aux),'auxiliary passages and',len(issues),'source-convention notes.')
