"""Archive main-text conventions separately from the original theorem statements."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];PID=ROOT.name
aux=[]
def add(aid,text,pages,loc,meaning):
    aux.append(dict(auxiliary_id=aid,statement_original=text.strip(),evidence=[dict(page=p,location=loc) for p in pages],resolution=meaning))
add('A1',r'''For a vector $v=(v_1,\ldots,v_d)\in\mathbb R^d$ and $q>0$, we denote $|v|_q=(\sum_{i=1}^d|v_i|^q)^{1/q}$ and $|v|_\infty=\max_{1\leq i\leq d}|v_i|$. For $s>0$ and a random vector $X$, we say $X\in\mathcal L^s$ if $\|X\|_s=[\mathbb E(|X|_2^s)]^{1/s}<\infty$, and denote $\mathcal E_0(X)=X-\mathbb E(X)$. For two positive number sequences $(a_n)$ and $(b_n)$, we say $a_n=O(b_n)$ or $a_n\lesssim b_n$ (resp. $a_n\asymp b_n$) if there exists $C>0$ such that $a_n/b_n\leq C$ (resp. $1/C\leq a_n/b_n\leq C$) for all large $n$, and say $a_n=o(b_n)$ or $a_n\gg b_n$ if $a_n/b_n\to0$ as $n\to\infty$. Let $(X_n)$ and $(Y_n)$ to be two sequences of random variables. Write $X_n=O_{\mathbb P}(Y_n)$ if for $\forall\epsilon>0$, there exists $C>0$ such that $\mathbb P(|X_n/Y_n|\leq C)>1-\epsilon$ for all large $n$, and say $X_n=o_{\mathbb P}(Y_n)$ if $X_n/Y_n\to0$ in probability as $n\to\infty$.''',[4],'Notation paragraph','Distinguish finite-dimensional vector q-norms from random-variable Lq norms. The printed meaning of much-greater-than is inconsistent with the usual convention and the later threshold narrative; preserve it and record the conflict.')
add('A2',r'''The symbol $o(1)$ and $\to0$ in this theorem and the rest of the paper is in the asymptotic regime $n\wedge p\to\infty$.''',[11],'After Theorem 1','The asymptotic results concern sequences with both sample size and dimension diverging. S, neighborhood sizes, break counts and locations may also vary as specified. The Gaussian reference vector changes with n,p,b,S.')
add('A3',r'''Note that in Sections 2 and 3, we assume $p=\widetilde p$, and all $A_k$, $k\geq0$, are diagonal matrices, which indicates the independence between the component processes $(\epsilon_{t,j})_{t\in\mathbb Z}$. We relax this assumption to weak cross-sectional dependence for a general $\epsilon_t$ in Section 4, and also provide the results for the same linear $\epsilon_t$ in (4) as a special case in Appendix B.4.''',[7],'After equation (5)','The rectangular linear coefficient setup is specialized to square diagonal filters in Theorems 1-3. Theorem 4 uses its own nonlinear model and Assumptions 8-12; no appendix specialization is imported.')
add('A4',r'''\[
n^4p^{2-q}\log^{3q}(pn)\to0.\tag{15}
\]''',[11],'Theorem 1 — condition (15)','Theorem 2 explicitly imports this numbered rate condition only. The separate log(n)=o(sqrt(bn)) condition in Theorem 1 is not included in the reference to (15).')
add('A5',r'''Theorem 1 implies that, for any level $\alpha\in(0,1)$, we can choose the threshold value $\omega$ to be the quantile of the Gaussian limiting distribution indicated by Theorem 1:
\[
\omega=\inf_{r\geq0}\left\{r:\mathbb P\left(\max_{bn+1\leq i\leq n-bn}Z_i>r\right)\leq\alpha\right\}.\tag{19}
\]''',[12],'Optional Gaussian calibration','This is one proposed choice of threshold. Algorithm 1 takes omega as input and Theorem 2 states its own signal and threshold rate requirements. Gaussian calibration is not required just to state the consistency theorem.')
add('A6',r'''We denote the break location by $\tau_k=nu_k$, $1\leq k\leq K$, and introduce the following assumption for the identification of breaks.''',[12],'Before Definition 1','This translates rescaled times to observation-index locations. Theorem 2 binds the nearest true break k* inline. A tie rule and what is meant by estimated indices k up to K off the event K-hat=K are not supplied.')
add('A7',r'''For any time point $i$ satisfying $|i-\tau_k|\leq bn$, we define the weighted break vectors as
\[
d_i=\mathbb EV_i=\sum_{k=1}^K\left(1-\frac{|i-\tau_k|}{bn}\right)\Lambda^{-1}\gamma_k\mathbf1_{|i-\tau_k|\leq bn}.\tag{20}
\]''',[12],'Weighted signal formula','This positive-sign formula conflicts with the left-minus-right estimator (3),(6) for the positive jump convention (2). It is retained as source evidence for that issue, not used to repair the theorem or add a proof-only dependency.')
add('A8',r'''We denote each element in $\mathcal Z^\diamond$ by $Z_\varphi^\diamond$, where
\[
\varphi=(i,s)\in\mathcal N,\quad\text{for }\mathcal N=\{bn+1,\ldots,n-bn\}\times\{1,\ldots,S\}.\tag{33}
\]''',[20],'Time-neighborhood product index','The same finite product index is explicitly reused in Theorem 4. It is ambient indexing notation and does not make the general theorem depend on the earlier Gaussian covariance or linear model.')
add('A9',r'''$K\in\mathbb N$ is the number of structural breaks which is unknown and could go to infinity as $n$ increases; $u_1,\ldots,u_K$ are the time stamps of the breaks with $0=u_0<u_1<\ldots<u_K<u_{K+1}=1$''',[5],'Equation (2) — break-count and ordered-time conventions, excerpt','The general model (43) explicitly says K and the break times are defined similarly to (2). This imports their parameter convention, not the linear error representation or diagonal coefficient assumptions.')
add('A10',r'''$b$ is a bandwidth parameter satisfying $b\to0$ and $bn\to\infty$. Without loss of generality, we assume that $bn$ is an integer.''',[6],'After equation (3) — bandwidth convention, excerpt','The shared moving-window bandwidth has integer block size, tending to infinity while its fraction tends to zero. The statistics themselves specify the admissible interior time range.')
issues=[]
def issue(key,pages,loc,note):
    issues.append(dict(key=key,evidence=[dict(page=p,location=loc) for p in pages],note=note))
issue('asymptotic_inequality_direction',[4,15],'Notation and Theorem 2','The notation paragraph says a_n>>b_n means a_n/b_n tends to zero. This reverses the conventional reading used by the later signal and threshold discussion. Both the notation and original theorem inequalities are retained without choosing a correction.')
issue('jump_sign',[5,6,7,12,14,15],'Equations (2),(3),(6),(20), Algorithm 1 and Theorem 2','The trend adds gamma_k at a break, whereas the local contrast and jump estimate subtract the right mean from the left. At an isolated positive jump their expectation has the opposite sign. Equation (20) nevertheless prints a positive tent-weighted gamma_k, and Theorem 2(iii) compares gamma-hat_k minus gamma_(k*). The disagreement is preserved.')
issue('undefined_gamma_zero',[5,15],'Assumption 4','The minimum starts at k=0 but the model only defines gamma_1,...,gamma_K. No gamma_0 convention is supplied. The original index range is not changed to make the condition well formed.')
issue('algorithm_threshold_and_ties',[14,15],'Algorithm 1 and Theorem 2','At Q_n=omega the algorithm enters its else branch but its strict-exceedance candidate set is empty, leaving max{k:A_k nonempty} undefined. Argmax and nearest-break ties have no explicit selection rule. Estimated quantities indexed up to true K also need an extension off the high-probability event K-hat=K. These omissions are not filled into source statements.')
issue('algorithm_shifted_means',[6,14],'Equation (3) and Algorithm 1','The jump estimate evaluates the left mean at tau-hat_k-bn and right mean at tau-hat_k+bn-1. These shifted windows can fall outside the observed range for candidate locations allowed by Algorithm 1. No boundary extension rule is supplied. The original shifts and subtraction order are retained.')
issue('centering_at_selected_index',[7,14,15],'Equation (7), Remark 5 and discussion after Theorem 2','The exact centering in (7) uses coordinate variances at a fixed index. Remark 5 approximates it by 2p/(bn); the discussion after Theorem 2 instead writes an expectation at a selected random index. These expressions are not silently identified. The extracted centering and theorem use the original bar-c definition.')
issue('neighborhood_covariance_free_index',[9,20],'Equation (32)','The displayed covariance has an overlap indicator with a free j, and no sum over j. It also invokes Xi from (11), which already includes a factor p. This does not unambiguously define the full comparison covariance. The printed expression is retained without inferring an overlap-count correction.')
issue('neighborhood_adjacency_scope',[16,17,18],'Definition 2 and spatial-window discussion','The numbered definition specifies coordinate subsets, while surrounding prose describes adjacent series and uses contiguity in a window-count argument. The definition itself is retained; an arbitrary set is not silently rewritten as an interval. Assumptions 6-7 and the influenced-set construction belong to Proposition 1, not a stored Theorem.')
issue('continuous_locations_on_lattice',[25,26],'Assumption 8 and general spatial setup','The source simultaneously puts locations in Z^v and represents them as scaled iid vectors having a positive continuous density on [0,1]^v. No rounding or alternative ambient space is specified. The density assumption is preserved as written, rather than replaced by the separate mass-to-volume discussion. Independence of random locations from the noise is not explicitly stated.')
issue('mass_and_volume',[25,26],'Equations (40)-(41) and Definition 6','The source calls each interval an interval on Z and then assigns its rectangle Lebesgue volume. A literal finite lattice rectangle has zero Lebesgue measure; a continuous enclosing rectangle would be a different interpretation. The source does not state that change of interpretation. Its mass comparability condition is retained with the full definition.')
issue('general_scale_convention',[7,27,29,30],'Equations (5),(44),(45),(53),(56)','Equation (5) uses sigma_j squared for the long-run variance; equation (44) instead defines sigma(l)=sigma(l,l) as the variance, but later inverses and the correlation ratio use sigma(l) as if it were a standard deviation. The general formulas are preserved with no square-root correction. Unlike (5), the general setup does not explicitly repeat a uniform positive variance bound.')
issue('coupling_domains',[28],'Equations (49)-(50)','The nonlinear representation uses ell-prime in Z^v, but both displayed coupled versions use Z. The replacement rule is stated only for i>=0 although the process uses an entire negative-time history. The double-star rule replaces i=0 OR s=0, not only their intersection. These source domains and logical conditions are retained.')
issue('general_gaussian_zero_lag',[30],'Equation (56)','The piecewise covariance formula covers only zeta>0 and does not state its diagonal or other same-time entries. The overlap indicator requires both spatial indices in the intersection of the two rectangles, as printed. No zero-lag limit or different overlap weights are supplied by the census. The detailed evaluation is referred to appendix Lemma 15, which was not read.')
issue('constant_uniformity',[11,21,30],'Theorems 1,3,4','Theorems 1 and 3 explicitly exclude dependence of the implicit constant on n,p,b; Theorem 4 additionally excludes S. These exact clauses are retained, as are the different error rates. The Gaussian comparison laws are finite vectors depending on the asymptotic parameters, not a single fixed limiting distribution.')
issue('appendix_only_material',[7,30],'Variance-estimation and covariance proof references','The variance estimator is referred to Appendix A.1 and the detailed general covariance evaluation to Lemma 15 in Appendix C. No appendix body was inspected. The census preserves the known-scale main-text statistic and records the covariance specification omissions rather than importing those details.')
resolution={
 'shared':'Basic real vector spaces, finite sums, indicators, expectation, variance, Gaussian laws, suprema, minima, logarithms and convergence notation remain ambient. A1 gives source norm/rate conventions; A2 gives n∧p→∞; A10 gives the common moving-window bandwidth. Every paper-specific object is resolved by the local interfaces or auxiliary passages. Statements and conditions with unresolved source conventions remain original claims, not certified well-posed theorems.',
 '1':'Assumptions 1,2,3 resolve to D10,D11,D12 under the VMA convention A3. The null is D2, Q_n is D8 and Z_i is D9. Delta_0,Delta_1,Delta_2 and the real supremum variable are bound inline. The additional log-bandwidth and (15) rates are a separate convergence clause. The covariance is the explicit (11)-(12) law; no proof X_j construction or Gaussian critical quantile is needed.',
 '2':'Assumptions 1-4 resolve to D10,D11,D12,D16. The referenced rate (15) is A4. K and gamma_k come from D1, Lambda from D5, kappa_n and tau_k from D13/A6, delta_p from D14, and all estimated quantities from Algorithm 1 D15; bar-c is D7. Omega is the algorithm input satisfying the displayed rate and signal requirements, with no mandatory use of optional A5. Gamma_k and nearest-break k* are bound inline. All three conclusions and the stronger optional localization condition are preserved; the signal-index, sign and estimator-domain issues are recorded separately.',
 '3':'Assumptions 1-3 and 5 resolve to D10,D11,D12,D20. D19 supplies the localized no-break model, D22 the normalized Two-Way statistic, D23 its Gaussian comparison vector and D17 the minimum neighborhood size. A8 supplies the finite product index N without creating an extra interface. All Delta terms, the real threshold variable and the two additional convergence conditions are inline. Assumptions 4,6,7, Algorithm 1, Definition 5 and Proposition 1 are not imported.',
 '4':'Assumptions 8-12 resolve to D28,D29,D36,D37,D38 under the nonlinear spatial model D25,D26,D30. The null is no jumps in (43), as stated in the context of (46). Q-tilde is D35; Z-tilde is D40 with rho-tilde D39; B_min and its comparability convention are D27. N is A8, while v is the fixed spatial dimension D25 and xi is the exponent in Assumption 12. The q parameter comes from Assumptions 10/11. c_(p,n), the three Delta terms, the real supremum variable and both extra convergence rates are bound inline. A9 resolves the shared break-time parameter convention only. No VMA, diagonal independence, linear covariance, positive-signal or localization algorithm assumptions are inherited.'
}
(ROOT/'ambient-conventions.json').write_text(json.dumps(dict(paper_id=PID,auxiliary_passages=aux,unresolved_source_conventions=issues,standard_ambient_resolution=resolution),indent=2,ensure_ascii=False)+'\n')
print('Saved',len(aux),'auxiliary passages and',len(issues),'source notes.')
