"""Build elliptical-test dependencies with theorem-specific statistical scope."""
import copy,json,subprocess,sys
from pathlib import Path
from extract_interfaces import ROOT,PID,interfaces,members
SKILL=Path('skills/statistical-paper-census/scripts')
sys.path.insert(0,str(SKILL))
from canonical_dependencies import canonical_dependencies
from census_metrics import derive_metrics
from publication_contract import attach_inventory
DIRECT_NUMS={'1':[2,3,4,5],'2':[3,12,13,15,17,22,23,24],'3':[3,12,13,14,24],'4':[2,6,12,14,25],'5':[9,12,13,14,26,27,28,29,30,31,32],'6':[12,13,14,27,28,29,30,32]}
DIRECT={n:['D'+str(i) for i in v] for n,v in DIRECT_NUMS.items()}
EDGE_TEXT={
'D2':{'D1':'The radial and angular kernels are defined on Omega_U and Omega_Theta, the archived coordinate domains.'},
'D3':{'D2':'The Hilbert tensor product uses the two RKHSs generated by the radial and angular kernels.'},
'D4':{'D1':'The probability-measure domain is the Borel product of the radius and angular spaces.'},
'D5':{'D2':'Characteristicness is the injectivity property of the kernel mean embeddings in the corresponding RKHSs.'},
'D8':{'D1':'The source polar transformation maps the angular rectangle to the unit sphere and defines its inverse on regular coordinates.','D7':'The inverse chart uses the five-case Arctan function; its missing (0,0) value is not silently filled.'},
'D9':{'D6':'Population whitening uses mean mu and covariance Sigma, as given by the moment functionals at F0.','D8':'Theta(x) is g(V(x)), the source’s polar coordinate transformation of the standardized direction.'},
'D10':{'D1':'The fixed spherical angular density P0 is normalized on the exact domain Omega_Theta.'},
'D11':{'D2':'The centered angular feature is an element of the angular RKHS.','D10':'Its mean is subtracted under the fixed law P0, not the observed angular marginal.'},
'D12':{'D3':'The population discrepancy is a tensor-RKHS element represented as an operator between the base RKHSs.','D9':'Its U and Theta are the population-standardized radius and polar angle.','D11':'The simplified formula averages radial features tensored with angular features centered under P0.'},
'D13':{'D3':'The sample discrepancy is a tensor-RKHS operator.','D11':'Even after fitting transformations its angular centering remains the fixed P0 mean.','D32':'Its fitted radii and angles use the sample mean and n-denominator covariance from the same iid observations.'},
'D14':{'D3':'The Hilbert-Schmidt norm applies to the operator realization of the Hilbert tensor product.'},
'D16':{'D6':'The F-dependent transforms use the distribution-specific moment functionals mu(F) and Sigma(F).','D8':'The angular transform is the polar chart g applied after whitening and normalization.'},
'D17':{'D3':'The functional takes values in the tensor RKHS.','D11':'It holds the P0-centered feature fixed while varying F.','D16':'Both the whitening transforms U(x,F),Theta(x,F) and the outer integration depend on F.'},
'D19':{'D6':'The moment influence expressions differentiate mu(F),Sigma(F) and inverse covariance square root.','D18':'Their star notation denotes the source contamination derivative, not an adjoint.'},
'D20':{'D15':'Lemma4’s coefficient/influence formulas are stated conditionally on Frechet differentiability of the transformation functionals; this is part of the source formula context.','D16':'The differentiated objects are the distribution-dependent U,V,Theta transforms.','D19':'The displayed expansions multiply the mean and covariance influence functions by A,B,C coefficients.'},
'D21':{'D2':'The dotted kernel is the derivative of the RKHS feature in its second argument.'},
'D22':{'D3':'The influence element is a sum of tensors and acts between the two base RKHSs.','D9':'Its leading feature term and both expectation corrections are evaluated at population-standardized U and Theta.','D11':'The first two terms use the angular feature centered under fixed P0.','D12':'The full influence formula subtracts the population discrepancy Sigma_UTheta.','D15':'Lemma5 states its influence formula under Frechet differentiability, whose printed definition is preserved separately.','D17':'The functional differentiated in Lemma5 is Sigma_UTheta(F), varying both the outer law and the standardization.','D20':'The corrections use U-star and Theta-star from Lemma4, including the estimation effects of mean and covariance.','D21':'The two correction terms use derivatives of radial/angular features in their second arguments.'},
'D23':{'D2':'Condition(5.11) applies the source’s bounded-Hessian C² requirement to both kernels.'},
'D24':{'D3':'Gamma acts on the Hilbert tensor product, one operator level above the base feature tensors.','D22':'Gamma is the second moment of the full discrepancy influence element in (5.10); its conditional construction does not itself establish a local-alternative CLT.'},
'D25':{'D2':'The literal known-parameter formula uses radial and angular kernel features.','D3':'It is an operator-valued empirical feature average in the tensor RKHS.','D9':'Known mu and Sigma give the population U,Theta transforms without estimating moments.'},
'D27':{'D6':'Assumption1 bounds the extremal eigenvalues of the covariance Sigma.','D26':'The positive covariance bounds are absolute constants, independent of dimension and sample size.'},
'D28':{'D6':'The sub-Gaussian MGF is centered by the population mean mu.'},
'D29':{'D9':'Assumption3 concerns the density of W=Sigma^(-1/2)(X−mu).','D26':'The base c in the density bound c^d is an absolute constant.'},
'D30':{'D2':'Assumption4 controls the RKHS feature differences of both kernels as well as their scalar bounds.','D8':'The angular feature is composed with the polar chart g and compared in the original unit-direction coordinates.'},
'D31':{'D26':'The rate functions use positive constants independent of n and d.'},
'D32':{'D8':'The fitted angle is g of the fitted direction; sample moment definitions alone do not remove polar exceptional sets.'}}
def direct_reason(n,lid):
    label='Theorem '+n
    if lid=='D2':return label+' explicitly uses the radial and angular positive definite kernels and their RKHSs.'+(' Characteristicness is a further explicit requirement.' if n=='1' else ' Its concentration hypothesis is boundedness, not characteristicness or C² regularity.')
    if lid=='D3':return label+' explicitly uses the tensor RKHS H_U tensor H_Theta as the space of the embedding or asymptotic covariance and shift objects.'
    if lid=='D4':return 'Theorem1 defines an injective embedding on all probability measures on the radial-angular Borel product space, without a particular data-law assumption.'
    if lid=='D5':return 'Theorem1 explicitly assumes both kernels are characteristic and asserts injectivity of the tensor-product probability embedding.'
    if lid=='D6':return 'Theorem4 explicitly assumes known population mean mu and covariance Sigma, which parameterize the true whitening transformation.'
    if lid=='D9':return 'Theorem5 explicitly requires a density bound for W, the population-whitened vector Sigma^(-1/2)(X−mu).'
    if lid=='D12':return label+' uses the population discrepancy Sigma_UTheta from (3.1), whose angular reference is the fixed P0.'+(' Under its local alternative this operator equals n^(-1/2)Sigma1.' if n=='3' else ' The E-versus-E0 difference in its known-parameter estimator (7.1) is separately flagged.' if n=='4' else '')
    if lid=='D13':return label+' uses the fitted-parameter operator breve-Sigma_UTheta from (3.3), with the same sample used to estimate location/scatter and average the transformed features.'
    if lid=='D14':return label+' compares Hilbert-Schmidt norms of the relevant operators.'+(' The local-alternative statistic is n times the squared norm.' if n=='3' else ' Its displayed conclusion concerns the norm itself, not the squared norm.')
    if lid=='D15':return 'Theorem2 explicitly assumes Frechet differentiability of the discrepancy functional at F0 under the uniform distribution metric described in Section5.1.'
    if lid=='D17':return 'Theorem2 differentiates F↦Sigma_UTheta(F) from (5.2)–(5.3), including the distribution-dependence of whitening but holding P0 fixed.'
    if lid=='D22':return 'Theorem2 explicitly refers to the full influence expression (5.10), including the population subtraction and the U-star and Theta-star estimation corrections.'
    if lid=='D23':return 'Theorem2 explicitly invokes (5.11), where C² means twice differentiable with a bounded Hessian; it does not merely assume pointwise differentiability.'
    if lid=='D24':return label+(' defines Gamma as the influence-element second-moment operator.' if n=='2' else ' uses Gamma’s spectral decomposition. Its statement gives two spectral/shift conditions; it does not explicitly restate all Theorem2 hypotheses or resolve zero eigenvalues in shifted normals.')
    if lid=='D25':return 'Theorem4 explicitly specifies (7.1), the known-parameter empirical operator. Its last factor is printed as E[kappa_Theta], unlike E0 in the earlier discrepancy; both source formulas are retained.'
    if lid=='D26':return 'Theorem5 explicitly calls c1 through c10 absolute constants, referring to the Section7.2 convention of independence from n and d.'
    if lid=='D27':return label+(' explicitly assumes' if n=='5' else ' inherits from Theorem5')+' Assumption1, uniform positive upper and lower covariance eigenvalue bounds.'
    if lid=='D28':return label+(' explicitly assumes' if n=='5' else ' inherits from Theorem5')+' Assumption2, a dimension-uniform sub-Gaussian bound in unit directions, retaining the printed implicit lambda/sphere conventions.'
    if lid=='D29':return label+(' explicitly assumes' if n=='5' else ' inherits from Theorem5')+' Assumption3: the density of the whitened W is bounded by c^d, with c absolute.'
    if lid=='D30':return label+(' explicitly assumes' if n=='5' else ' inherits from Theorem5')+' Assumption4, bounded kernels and RKHS-feature Lipschitz bounds, including the d^(-1) factor for the polar-composed angular feature.'
    if lid=='D31':return 'Theorem5 explicitly uses the four rate functions in (7.6), with the product f3*f2, c5*f1 and f4 in its threshold. Theorem6 inherits assumptions and does not use these bound functions in its statement.'
    if lid=='D32':return label+(' explicitly states iid sampling and uses the fitted-parameter discrepancy based on the empirical mean and covariance.' if n=='5' else ' inherits iid sampling from Theorem5 and uses the same fitted transforms in its convergence statement.')
    raise ValueError((n,lid))
def main():
    import extract_interfaces,save_ambient
    extract_interfaces.ROOT=ROOT;extract_interfaces.main();save_ambient.ROOT=ROOT;save_ambient.main()
    inv=json.loads((ROOT/'theorem-inventory.json').read_text());data=copy.deepcopy(inv)
    data['schema_version']='statistical-ranked-interfaces-v4'
    data['scope'].update(semantic_ranking_policy='All six main-text Theorems retained with full statements.',build_order_policy='Keep abstract embedding, operator asymptotics, known-parameter and fitted-parameter concentration scopes distinct. Preserve conditional influence definitions and explicit source ambiguities.')
    data['interfaces']=copy.deepcopy(interfaces);claims={c['claim_id']:c for c in data['claims']}
    for lid,m in members.items():assert set(m['depends_on'])==set(EDGE_TEXT.get(lid,{})),lid
    for c in data['claims']:
        n=c['claim_id'].split('/T')[-1];c['depends_on']=DIRECT[n]
        for x in data['interfaces']:
            lid=x['members'][0]['local_id']
            if lid in DIRECT[n]:
                ev=copy.deepcopy(c['evidence'])+copy.deepcopy(members[lid]['evidence'])
                x['central_claim_uses'].append(dict(use_id=c['claim_id']+'-'+lid,paper_id=PID,claim_id=c['claim_id'],use_kind='statement_dependency',reason=direct_reason(n,lid),evidence=ev))
    edges=canonical_dependencies(data)
    for x in data['interfaces']:x['dependencies']=edges[x['interface_id']]
    derive_metrics(data)
    for x in data['interfaces']:
        for rel in x['related_theorems']:
            cid=rel['claim_id'];n=cid.split('/T')[-1];path=rel['via_local_ids']
            reason=' '.join([direct_reason(n,path[0])]+[EDGE_TEXT[a][b] for a,b in zip(path,path[1:])])
            ev=copy.deepcopy(claims[cid]['evidence'])
            for lid in path:ev.extend(e for e in members[lid]['evidence'] if e not in ev)
            x['theorem_explanations'][cid]=dict(paper_id=PID,via_local_ids=path,text=reason,evidence=ev)
        for m in x['members']:
            own=m['statement_original']+' '+m['local_label'];linked=own+' '+' '.join(claims[r['claim_id']]['statement_original'] for r in x['related_theorems'])
            selectors=m['highlight_symbols']+m['highlight_phrases']
            assert any(s in own for s in selectors) and all(s in linked for s in selectors),(m['local_id'],[s for s in selectors if s not in linked])
    attach_inventory(data,ROOT/'theorem-inventory.json',ROOT/'ranked-interfaces.json')
    (ROOT/'unfinalized-census.json').write_text(json.dumps(data,indent=2,ensure_ascii=False)+'\n')
    subprocess.run([sys.executable,str(SKILL/'finalize_census.py'),str(ROOT/'unfinalized-census.json'),str(ROOT/'ranked-interfaces.json'),'--inventory',str(ROOT/'theorem-inventory.json')],check=True)
    subprocess.run([sys.executable,str(SKILL/'validate_census.py'),str(ROOT/'ranked-interfaces.json')],check=True)
    print('Census structurally validated; independent source review remains pending.')
if __name__=='__main__':main()
