"""Preserve model scope, theorem binders and original auxiliary tensor passages."""
import json
from save_inventory import ROOT,PID

def main():
    aux=[]
    def add(n,s,pages,note,deps=()):aux.append(dict(local_id='A'+str(n),statement_original=s,evidence=[dict(page=p,location='Original main-text context A'+str(n)) for p in pages],scope_note=note,depends_on=list(deps)))
    add(1,r'''A critical feature of moment and cumulant tensors that we use to study identification in model (1) comes from multilinearity, i.e. for every $A\in\mathbb R^{d\times d}$ we have
\[
h_r(AX)=A\bullet h_r(X),
\]
(6)''',[5],'Original equivariance property underlying the identification proof. The algebraic action is D7; the property does not turn the purely algebraic Theorems5.3/5.10 into statements about random tensors or independent components.',['D1','D6','D7'])
    add(2,r'''We formalize zero restrictions by choosing a subset $\mathcal I$ of $r$-tuples $(i_1,\ldots,i_r)$ satisfying $1\le i_1\le\cdots\le i_r\le d$ and by defining the vector space $\mathcal V=\mathcal V(\mathcal I)$ of symmetric tensors $T\in S^r(\mathbb R^d)$ such that $T_{\mathbf i}=0$ for all $\mathbf i=(i_1,\ldots,i_r)\in\mathcal I$. In symbols:
\[
\mathcal V=\mathcal V(\mathcal I)=\{T\in S^r(\mathbb R^d):T_{\mathbf i}=0\text{ for }\mathbf i\in\mathcal I\}.
\]
Note that the codimension of $\mathcal V$ in $S^r(\mathbb R^d)$ is precisely $\operatorname{codim}(\mathcal V)=|\mathcal I|$.''',[7],'General zero-pattern parameterization. The inventoried theorems use the directly defined diagonal/reflectional spaces; no extra dependency on an arbitrary index-set model is needed to state them. G_T itself is defined for a general subset V, not only this linear zero-pattern space.',['D2'])
    add(3,r'''Proposition 4.1. Consider the model (1) with $\mathbb E\varepsilon=0$ and $\operatorname{var}(\varepsilon)=I_d$. Suppose we know, for a fixed $r\ge3$, that $T=h_r(\varepsilon)\in\mathcal V\subset S^r(\mathbb R^d)$. Then $A$ can be identified up to the set
\[
\Omega_0=\{QA:Q\in\mathcal G_T(\mathcal V)\}.
\]
(11)''',[7],'General identification proposition used to derive Theorems5.5/5.14, not an additional Theorem or an independent premise. It distinguishes the transformation set G_T from the parameter set of matrices QA, correcting interpretation without altering the source definition’s imprecise subset-of-Omega prose.',['D1','D2','D6','D8','D9'])
    add(4,r'''\[
T_{i\cdots i}\ne0\qquad\text{for at least }d-1\text{ different values of }i=1,\ldots,d.
\]
(13)
If $r=2$, the same conclusion holds under a stronger condition that $T_{jj}\ne T_{kk}$ for $j\ne k$.''',[9],'Genericity clauses excerpted from Theorem5.3. Its higher-order condition permits one zero diagonal entry; its r=2 branch requires pairwise distinct matrix diagonals. Theorem5.5 binds its own equivalent at-most-one-zero condition, rather than referencing an external assumption object.',['D2','D11'])
    add(5,r'''\[
f_T(x)=\sum_{i_1=1}^d\cdots\sum_{i_r=1}^dT_{i_1\cdots i_r}x_{i_1}\cdots x_{i_r}=\sum_{\mathbf i}T_{\mathbf i}(x^{\otimes r})_{\mathbf i}=\langle T,x^{\otimes r}\rangle,
\]
(12)
where $x^{\otimes r}\in S^r(\mathbb R^d)$ denotes the tensor with coordinates $(x^{\otimes r})_{i_1\cdots i_r}=x_{i_1}\cdots x_{i_r}$. If $r=2$ then $T$ is a symmetric matrix and $f_T(x)=x'Tx$ is the standard quadratic form associated with $T$.''',[8],'Homogeneous-polynomial representation used in proofs. It is not part of the inventoried theorem statements or of the entrywise definitions of diagonal/reflectionally invariant tensors, so no polynomial, Hessian or gradient API is added to their dependency graph.',['D2'])
    add(6,r'''Lemma 5.9. The tensor $T\in S^r(\mathbb R^d)$ is reflectionally invariant if and only if $f_T(x)=f_T(Dx)$ for every diagonal matrix $D$ with $\pm1$ on the diagonal.''',[10],'Alternative characterization used in the proof. Preserve it as a lemma, not a Theorem or a replacement for Definition5.8. Invariance under coordinate reflections is different from full rotational invariance.',['D2','D12'])
    add(7,r'''The multilinearity property (6) is not exclusive to moments and cumulant tensors, as central moments, free cumulants and boolean cumulants, for instance, also share this property; see Zwiernik (2012, Section 5.2) for a more complete characterization. Our main results rely only on the property (6) and so the definition of $h_r(X)$ can be extended beyond moments and cumulants if needed.''',[6],'Remark3.1 discusses possible extensions. The primary h_r notation remains a selected moment or classical cumulant tensor; broader cumulant notions are not automatically merged into its definition or treated as additional theorem assumptions.',['D6','D7'])
    add(8,r'''If $r=2$ then $\mathcal V^{\mathrm{refl}}=\mathcal V^{\mathrm{diag}}$ and it corresponds to the set of diagonal matrices. In this case, the genericity condition (14) and the genericity condition in Theorem 5.3 coincide: $T_{jj}\ne T_{kk}$ for $j\ne k$.''',[11],'Remark5.12 explicitly includes the second-order algebraic case. With normalized latent covariance, h_2(epsilon)=I_d under either moment/cumulant choice, so condition(14) cannot hold for d>1 at r=2. Do not silently rewrite Theorem5.14 to say r≥4, but retain this applicability limit.',['D11','D12','D13'])
    add(9,r'''Theorems 5.5 and 5.14 highlight key zero moment and cumulant patterns that can be used to identify $A$ up to sign and permutation for the general model (1). Such restrictions are equally sufficient for identification in the class of linear simultaneous equations models $AY=BX+\varepsilon$ when $X$ is exogenous, and various dynamic extensions of such models (e.g. Kilian and Lütkepohl, 2017).''',[13],'Section5.3 discusses extensions beyond model(1); Corollaries5.7/5.15 apply the tensor results to specific component models. These are not additional main-text Theorems, and the application models, mean independence and estimation procedures are not imposed on all four inventoried statements.',['D1','D6','D10','D11','D12'])
    issues=[]
    def issue(i,pages,note):issues.append(dict(issue_id=i,evidence=[dict(page=p,location='Source scope or notation issue') for p in pages],note=note))
    issue('registered-title-and-boundary',[1,21],'The registered source is arXiv:2206.13668v4, marked19 Mar2024. Its title says components (plural), whereas the corpus metadata says component. Main text and acknowledgements end on PDF page21 before references at y580.205; evidence is clipped at y572. No appendix or S-prefixed supplementary passage is imported.')
    issue('orthogonal-domain-and-parameter-side',[1,6,7,9,11],'The Q transformations in the algebraic conclusions range over O(d), as specified by the preceding setting and G_T definition. They are not arbitrary invertible matrices: diagonal rescalings would otherwise invalidate the conclusion. A maps Y to epsilon, and the surviving ambiguity is left multiplication by signed permutations, changing rows rather than columns.')
    issue('transformations-versus-parameter-set',[7],'Equation(10) defines G_T(V) as a subset of O(d), but the following source sentence calls it a subset of Omega, which contains QA. Proposition4.1 gives the actual parameter set Omega_0={QA:Q in G_T(V)}. Preserve the original sentence while keeping transformations Q separate from parameter matrices QA. G_T is not generally a group or the stabilizer of T.')
    issue('algebraic-versus-statistical-scope',[5,7,8,9,10,11,12],'Theorems5.3/5.10 concern arbitrary symmetric tensors, not necessarily realizable as moments/cumulants of a distribution. Theorems5.5/5.14 concern model(1) with centered unit-covariance hidden components and a chosen h_r. No observational-model premise or generating-function existence condition is imported into the algebraic theorems.')
    issue('moment-cumulant-choice',[5,6,9,12],'h_r denotes either the order-r raw moment tensor or the order-r classical cumulant tensor. Listing both definitions resolves a notation alternative, not a conjunction requiring both tensors to satisfy the restrictions. Their higher-order entries differ; zero mean makes only the third-order tensors coincide. Remark3.1’s extensions are not folded into the default definition.')
    issue('moment-and-generating-function-existence',[5],'The source defines moments by expectations and also derivatives of the MGF, and cumulants through log-MGF derivatives. It does not specify a neighborhood where the MGF is finite or analytic. Theorems require the indicated tensors to exist, but finite moments of one order alone do not establish that analytic representation. Preserve this unresolved regularity convention; do not silently assume all moments or replace the original cumulant definition.')
    issue('different-genericity-conditions',[9,11,12],'For r≥3, Theorem5.3 requires at least d−1 nonzero full diagonal entries, equivalently at most one zero. Its r=2 branch needs pairwise distinct matrix diagonals. For reflectional tensors, condition(14) compares repeated-pair contractions summed over all indices, not just full diagonal entries. These conditions are neither interchangeable nor part of the entrywise zero-pattern definitions.')
    issue('even-order-and-normalized-second-order',[5,10,11,12],'Definition5.8 permits only the zero tensor at odd order. Theorem5.10 takes even r and l=(r−2)/2, with the standard positive-order context; r=2 yields an empty contraction and distinct diagonal entries. Theorem5.14 does not explicitly exclude r=2, but h_2(epsilon)=I_d under its normalization, so genericity fails for d>1. No new lower bound on r is inserted into the source statement.')
    issue('reflection-pattern-versus-stabilizer',[10,11],'Reflectionally invariant means every potentially nonzero entry has even multiplicity of each coordinate label, including off-diagonal pair patterns. It does not mean invariant under every orthogonal transformation. Theorem5.10 describes all transformations into the entire reflectional space, yielding signed permutations; Lemma5.13 describes the smaller exact stabilizer of a fixed generic tensor. The two sets are not merged.')
    issue('identification-not-estimation-or-independence',[1,7,9,12,13],'The statistical conclusions determine A from the population distribution up to row sign/permutation, not exact recovery of a unique orientation, a finite-sample estimator or a convergence rate. Neither diagonal constraints at one selected order nor reflectional constraints imply independence. Corollaries for common-variance, elliptical or mean-independent models and later minimum-distance estimation results are not extra Theorems or premises of the general identification statements.')
    bindings={
      'T5.3':dict(domain='T is an arbitrary real symmetric order-r tensor; Q ranges over O(d) under the standing transformation convention.',objects=['D2','D7','D9','D10','D11'],branches={'higher_order':'r≥3, diagonal T with at least d−1 nonzero full diagonal entries.','second_order':'r=2 with pairwise distinct diagonal entries; preserve this separate branch.'},conclusion='All orthogonal Q taking T into the diagonal space are exactly signed permutations; G_T(Vdiag)=SP(d). No distributional realizability assumption.'),
      'T5.5':dict(model='AY=epsilon, invertible A, observed Y, hidden centered epsilon with covariance I_d.',objects=['D1','D6','D8','D10','D11'],choice='Some fixed r≥3 and either h_r=mu_r or h_r=kappa_r, diagonal with at most one zero full diagonal entry.',conclusion='Population identification of A up to left signed-permutation action, hence row permutations and row signs. Independence and non-Gaussian-component assumptions are not separately imposed.'),
      'T5.10':dict(domain='Arbitrary symmetric reflectionally invariant tensor at even positive order r; Q in O(d).',objects=['D2','D7','D9','D10','D12'],local_binders='l=(r−2)/2; each i_a sums over[d], and j,k range over[d] with j≠k. Condition(14) is bound inline and separately archived as D13 for reuse by Theorem5.14.',conclusion='G_T(Vrefl)=SP(d), not a claim that the exact stabilizer Q*T=T is all of SP(d).'),
      'T5.14':dict(model='Same observed normalized linear model as Theorem5.5.',objects=['D1','D6','D8','D10','D12','D13'],choice='For some even r, the chosen h_r(epsilon) is reflectionally invariant and satisfies the repeated-pair contraction condition(14). Moments and cumulants are alternatives.',conclusion='A is identifiable up to row signs and permutations. The statement does not invoke independence or require a specific generative component model.',order_note='The original statement says even r; the normalized second-order case cannot satisfy condition(14) for d>1.')}
    refs=[dict(claim_id=PID+'/T5.3',reference='Definition5.1 and G_T(Vdiag)',reference_kind='definition_reference',resolution='D11 preserves the diagonal space; D9 defines admissible orthogonal transformations, using the tensor action D7.'),dict(claim_id=PID+'/T5.3',reference='Lemma5.2 and homogeneous polynomial(12)',reference_kind='proof_only',resolution='A5 preserves the polynomial representation; gradient/Hessian identities do not become statement dependencies.'),dict(claim_id=PID+'/T5.5',reference='model(1) and h_r',reference_kind='definition_reference',resolution='D1 and D6 with the original moment/cumulant alternatives and normalized observational ambiguity D8.'),dict(claim_id=PID+'/T5.5',reference='Proposition4.1 and Theorem5.3',reference_kind='proof_only',resolution='The main text combines those results to prove identification. The theorem itself binds its diagonal and at-most-one-zero assumptions; no theorem-as-premise edge is added.'),dict(claim_id=PID+'/T5.10',reference='Definition5.8 and G_T(Vrefl)',reference_kind='definition_reference',resolution='D12 supplies the even-index-multiplicity pattern, and D9 supplies the orthogonal transformation-set meaning.'),dict(claim_id=PID+'/T5.10',reference='Lemmas5.9 and5.13',reference_kind='proof_only',resolution='Reflection polynomial invariance and exact stabilizer computations are proof tools, distinct from the target transformation set.'),dict(claim_id=PID+'/T5.14',reference='genericity condition(14)',reference_kind='assumption_reference',resolution='D13 reproduces only the repeated-pair contraction condition defined inside Theorem5.10, applied here to h_r(epsilon).'),dict(claim_id=PID+'/T5.14',reference='Proposition4.1 and Theorem5.10',reference_kind='proof_only',resolution='Derivation of the model-identification result; the source theorem retains its own moment/cumulant and reflectional assumptions without importing the proof’s polynomial machinery.')]
    data=dict(paper_id=PID,unranked_auxiliary_passages=aux,source_issues=issues,statement_local_bindings=bindings,source_claim_references=refs,ambient_conventions=['Positive integer dimension/order, real random vectors, covariance matrices, orthogonal matrices, permutations, sign matrices, tensor index tuples and empty contractions are ambient mathematical conventions; no mathlib availability is assessed.','The matrices Q in Theorems5.3/5.10 lie in O(d). The algebraic action itself is defined for any real d-by-d A. The statistical A is invertible and acts from observed Y to latent epsilon.','The distribution of Y is the observed object for population identification; no iid sample or estimator is needed to state these four theorems. Higher-order tensor existence is implicit and the MGF derivative regularity remains explicitly noted.','Both moment and cumulant definitions are connected through the source h_r notation as alternatives, never as simultaneous restrictions or a synthesized tensor. All definitions preserve original source labels and quantifiers.','No appendix or S-prefixed supplementary body is used. Source validation preserves statements and their meaning; it does not certify proofs, moment determinacy or the later estimation procedures.'])
    (ROOT/'ambient-prerequisites.json').write_text(json.dumps(data,indent=2,ensure_ascii=False)+'\n')
if __name__=='__main__':main()
