"""Transcribe statement prerequisites from the inspected pinned preprint, without supplements."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];PID=ROOT.name
interfaces=[];members={};edges={}
def add(lid,term,body,pages,heading,deps=None,*,kind='definition',symbols=(),phrases=(),context=None,note=None,shape):
    m=dict(paper_id=PID,local_id=lid,local_label=heading,source_heading=heading,source_kind=kind,
        statement_original=body.strip(),relation='exact',depends_on=list(deps or {}),
        evidence=[dict(page=p,location=heading) for p in pages],highlight_symbols=list(symbols),highlight_phrases=list(phrases))
    if note:m['variant_note']=note
    terms=term if isinstance(term,list) else [term];keywords=[]
    for t in terms:
        key=dict(paper_id=PID,local_id=lid,source_text=t,label=t[0].upper()+t[1:],kind='term')
        if t not in body:
            assert context and t in context,(lid,t)
            m['naming_context']=[dict(context_id=lid+'/name',text=context,evidence=m['evidence'])];key['context_id']=lid+'/name'
        keywords.append(key)
    interfaces.append(dict(interface_id=PID+'/'+lid,rank_group='all',name=' · '.join(k['label'] for k in keywords),
        lean_role='hypothesis' if kind in ('condition','assumption') else 'definition',type_shape=shape,semantic_boundary=shape,
        members=[m],source_keywords=keywords,central_claim_uses=[],dependencies=[],theorem_explanations={}))
    members[lid]=m;edges[lid]=deps or {}
add('D1',['Training GWAS','Testing GWAS','Genotype reference panel'],r'''
Consider two independent GWAS that are conducted for the same continuous complex trait with the same $p$ genetic variants:

Training GWAS: $(\boldsymbol X,\boldsymbol y)$, where $\boldsymbol X=(\boldsymbol x_1,\ldots,\boldsymbol x_p)\in\mathbb R^{n\times p}$ and $\boldsymbol y\in\mathbb R^{n\times1}$;

Testing GWAS: $(\boldsymbol Z,\boldsymbol y_z)$, where $\boldsymbol Z=(\boldsymbol z_1,\ldots,\boldsymbol z_p)\in\mathbb R^{n_z\times p}$ and $\boldsymbol y_z\in\mathbb R^{n_z\times1}$.

Here $\boldsymbol y$ and $\boldsymbol y_z$ are the complex traits measured in two independent cohorts with sample sizes $n$ and $n_z$, respectively.

In addition, we define an external genotype reference panel dataset for the same $p$ genetic variants as

Genotype reference panel: $\boldsymbol W=(\boldsymbol w_1,\ldots,\boldsymbol w_p)\in\mathbb R^{n_w\times p}$.
''',[4,5],'Section 2.1 — training, testing and reference data',kind='source_passage',phrases=['Training GWAS','Testing GWAS','Genotype reference panel'],shape='Three datasets with distinct sample sizes and common columns; the first two have responses, the external reference panel has no response. Source excerpts are separate dataset declarations, not a synthesized stochastic model.')
add('D2','linear additive polygenic models',r'''
Without loss of generality, it is assumed that there are $m\leq p$ causal variants with nonzero effects and $\boldsymbol X_{(1)}\in\mathbb R^{n\times m}$ and $\boldsymbol Z_{(1)}\in\mathbb R^{n_z\times m}$ denote the corresponding data matrices among the $p$ genetic variants in $\boldsymbol X$ and $\boldsymbol Z$, respectively. The linear additive polygenic models [Jiang et al., 2016] assume
\[
\boldsymbol y=\boldsymbol X\boldsymbol\beta+\boldsymbol\epsilon=\boldsymbol X_{(1)}\boldsymbol\beta_{(1)}+\boldsymbol\epsilon\qquad\text{and}\qquad\boldsymbol y_z=\boldsymbol Z\boldsymbol\beta+\boldsymbol\epsilon_z=\boldsymbol Z_{(1)}\boldsymbol\beta_{(1)}+\boldsymbol\epsilon_z,\tag{1}
\]
where $\boldsymbol\beta_{(1)}$ is a $m\times1$ vector of nonzero causal genetic effects, $\boldsymbol\beta$ is a $p\times1$ vector consisting of $\boldsymbol\beta_{(1)}$ and $p-m$ zeros, and $\boldsymbol\epsilon$ and $\boldsymbol\epsilon_z$ represent independent random error vectors.
''',[5],'Section 2.1 — model (1)',{'D1':'The model uses the training and testing designs and responses declared in Section 2.1.'},kind='source_passage',phrases=['linear additive polygenic models'],symbols=[r'\boldsymbol\beta_{(1)}',r'\boldsymbol y_z'],shape='Two response equations with a shared effect vector, m causal coordinates and separate errors. Random-effect distribution and proportional causal count are later conditions, not imposed by these equations alone.')
add('D3','uniformly bounded eigenvalues',r'''
(a). Let $\boldsymbol X=\boldsymbol X_0\boldsymbol\Sigma^{1/2}$, $\boldsymbol Z=\boldsymbol Z_0\boldsymbol\Sigma^{1/2}$, and $\boldsymbol W=\boldsymbol W_0\boldsymbol\Sigma^{1/2}$, where the entries of $\boldsymbol X_0$, $\boldsymbol Z_0$, and $\boldsymbol W_0$ are real-value i.i.d. random variables with mean zero, variance one, and a finite 4th order moment. The $\boldsymbol\Sigma$ is a $p\times p$ population level deterministic positive definite matrix of $p$ genetic variants. We have uniformly bounded eigenvalues in $\boldsymbol\Sigma$ in the sense that $0<c\leq\lambda_{\min}(\boldsymbol\Sigma)\leq\lambda_{\max}(\boldsymbol\Sigma)\leq C$ for all $p$ and some constants $c,C$, where $\lambda_{\min}(\boldsymbol A)$ and $\lambda_{\max}(\boldsymbol A)$ are the smallest and largest eigenvalues of a generic matrix $\boldsymbol A$, respectively. The $\boldsymbol\Sigma^{1/2}$ denotes any nonnegative square root of $\boldsymbol\Sigma$. For simplicity, we also assume $\boldsymbol\Sigma_{ii}=1$, $i=1,\ldots,p$, or equivalently, $\boldsymbol X$, $\boldsymbol Z$, and $\boldsymbol W$ have been column-standardized.
''',[5],'Condition 1(a)',{'D1':'The covariance-factor designs have the dimensions and sample roles specified by the dataset declarations.'},kind='condition',phrases=['Condition 1(a)','uniformly bounded eigenvalues'],symbols=[r'\boldsymbol\Sigma^{1/2}'],shape='Common deterministic covariance, standardized iid innovation entries with a fourth moment, and dimension-uniform spectral bounds. Preserve the source equation of population diagonal-one with column standardization without claiming their finite-sample equivalence.')
add('D4','block-diagonal structure',r'''
(b). The $\boldsymbol\Sigma$ has a block-diagonal structure with $K$ blocks, whose boundaries are known, denoted by $\boldsymbol\Sigma=\operatorname{Diag}(\boldsymbol\Sigma_1,\ldots,\boldsymbol\Sigma_l,\ldots,\boldsymbol\Sigma_K)$, where $\boldsymbol\Sigma_l$ is a $p_l\times p_l$ matrix for $l\in1,\ldots,K$ such that $\sum_{l=1}^Kp_l=p$. Let $\boldsymbol X_l=(\boldsymbol x_{\widetilde p_{l-1}+1},\ldots,\boldsymbol x_{\widetilde p_l})$, $\boldsymbol W_l=(\boldsymbol w_{\widetilde p_{l-1}+1},\ldots,\boldsymbol w_{\widetilde p_l})$, and $\boldsymbol Z_l=(\boldsymbol z_{\widetilde p_{l-1}+1},\ldots,\boldsymbol z_{\widetilde p_l})$ be the submatrices of $\boldsymbol X$, $\boldsymbol W$, and $\boldsymbol Z$ corresponding to $\boldsymbol\Sigma_l$, respectively, where $\widetilde p_l=p_1+\cdots+p_l$.
''',[5],'Condition 1(b)',{'D3':'The block structure is imposed on the common covariance from Condition 1(a), with corresponding design columns.'},kind='condition',phrases=['Condition 1(b)','block-diagonal structure'],symbols=[r'\boldsymbol\Sigma_l',r'\widetilde p_l'],shape='Known contiguous blocks of the population covariance and aligned columns in all three designs. The indexing needs the implicit empty prefix p-tilde_0=0. K is the number of blocks, not the bold matrix K_l in Theorem 3.')
add('D5',['empirical spectral distribution','limiting spectral distribution'],r'''
(c). For $l=1,\ldots,K$, we define the empirical spectral distribution (ESD) of $\boldsymbol\Sigma_l$ as $F_{p_l}^{\boldsymbol\Sigma_l}(x)=p_l^{-1}\cdot\sum_{i=1}^{p_l}\mathrm I(\lambda_i(\boldsymbol\Sigma_l)\leq x)$, $x\in\mathbb R$, where $\lambda_i(\boldsymbol A)$ is the $i$-th eigenvalue of a generic matrix $\boldsymbol A$. As $p_l\to\infty$, let $\{\boldsymbol\Sigma_l\}_{p_l>1}$ be a sequence of matrices, we assume that the sequence of corresponding ESDs $\{F_{p_l}^{\boldsymbol\Sigma_l}(x)\}_{p_l>1}$ converges weakly to a limit probability distribution $H_l(x)$ for $x\in\mathbb R$, called the limiting spectral distribution (LSD), for each $l$. Similarly, we assume the $p\times p$ population level correlation matrix $\boldsymbol\Sigma$ has a LSD, denoted as $H(x)$ for $x\in\mathbb R$.
''',[5],'Condition 1(c)',{'D4':'The population spectral measures and limits are for the blocks and their full covariance.'},kind='condition',phrases=['Condition 1(c)','empirical spectral distribution','limiting spectral distribution'],symbols=[r'H_l(x)',r'F_{p_l}^{\boldsymbol\Sigma_l}(x)'],shape='Population ESDs and assumed weak limits, distinct from the sample spectral laws M_l and M_w_l. Preserve the probability-distribution interpretation of H_l and H.')
add('D6',['sample size','number of genetic variants'],r'''
(d). As $\min(n,n_z,n_w,p)\to\infty$, we assume $\omega_n=p/n\to\omega\in(0,\infty)$, $\omega_{w_n}=p/n_w\to\omega_w\in(0,\infty)$, and $\omega_{z_n}=p/n_z\to\omega_z\in(0,\infty)$. In addition, for $l=1,\ldots,K$, we assume $\omega_{l_n}=p_l/n\to\omega_l\in(0,\infty)$, $\omega_{w_{ln}}=p_l/n_w\to\omega_{w_l}\in(0,\infty)$, and $\omega_{z_{ln}}=p_l/n_z\to\omega_{z_l}\in(0,\infty)$.
''',[5],'Condition 1(d)',{'D1':'The three denominators are the separate dataset sizes.','D4':'Each block has dimension p_l and the blocks sum to p.'},kind='condition',context='In Condition 1 (d), we assume that the sample size and the number of genetic variants are proportional to each other.',phrases=['Condition 1(d)'],symbols=[r'\omega_{w_l}',r'\omega_{z_l}',r'\omega_l'],shape='Global and block dimension-to-sample limits for training, external reference and testing data. Limits are finite positive constants. The nested finite-index notation follows the printed source.')
members['D6']['naming_context'][0]['evidence']=[dict(page=6,location='Discussion of Condition 1(d)')]
add('D7','number of causal variants',r'''As $p\to\infty$, we assume $\gamma_p=m/p\to\gamma\in(0,\infty)$.''',[6],'Condition 2',{'D2':'m counts the nonzero causal effects in the polygenic model.'},kind='condition',context='Condition 2 assumes that the number of causal variants $m$ is proportional to $p$ [Jiang et al., 2016].',phrases=['Condition 2'],symbols=[r'\gamma_p=m/p'],shape='Nonvanishing causal fraction; the printed interval for gamma is (0,infinity), while m<=p already restricts any valid limit to at most one. The source is not a sparse m/p->0 regime.')
add('D8',['nonzero genetic effects','random error vectors'],r'''
Let $F(0,V)$ represent a generic distribution with mean zero, (co)variance $V$, and finite fourth order moments. We assume that the distribution of $\boldsymbol\beta_{(1)}$ is independent of the genetic variant data $\boldsymbol X$, $\boldsymbol Z$, and $\boldsymbol W$ and satisfies $\boldsymbol\beta_{(1)}\sim F(\boldsymbol0,p^{-1}\cdot\boldsymbol\Sigma_\beta)$, where $\boldsymbol\Sigma_\beta=\sigma_\beta^2\cdot\boldsymbol I_m$. In addition, $\boldsymbol\epsilon$ and $\boldsymbol\epsilon_z$ are independent random variables satisfying
\[
\begin{pmatrix}\boldsymbol\epsilon\\\boldsymbol\epsilon_z\end{pmatrix}\sim F\left[\begin{pmatrix}\boldsymbol0\\\boldsymbol0\end{pmatrix},\begin{pmatrix}\boldsymbol\Sigma_{\epsilon\epsilon}&\boldsymbol0\\\boldsymbol0&\boldsymbol\Sigma_{\epsilon_z\epsilon_z}\end{pmatrix}\right],
\]
where $\boldsymbol\Sigma_{\epsilon\epsilon}=\sigma_\epsilon^2\cdot\boldsymbol I_n$ and $\boldsymbol\Sigma_{\epsilon_z\epsilon_z}=\sigma_{\epsilon_z}^2\cdot\boldsymbol I_{n_z}$.
''',[6],'Condition 3',{'D2':'The effects and noise vectors are those in model (1).'},kind='condition',context=r'Next, we introduce the condition on nonzero genetic effects $\boldsymbol\beta_{(1)}$ and random error vectors $\boldsymbol\epsilon$ and $\boldsymbol\epsilon_z$.',phrases=['Condition 3'],symbols=[r'\boldsymbol\beta_{(1)}\sim F(\boldsymbol0,p^{-1}\cdot\boldsymbol\Sigma_\beta)',r'\sigma_{\epsilon_z}^2'],shape='Centered finite-fourth-moment effect distribution with covariance scaled by p^{-1}, independent of the designs, and separate noise covariance matrices. The generic F notation is not a Gaussian assumption and does not itself enforce iid coordinates.')
members['D8']['application_context']=[dict(text=r'In Condition 3, we model $\boldsymbol\beta_{(1)}$ as i.i.d. random variables with finite moments [Dobriban and Wager, 2018, Jiang et al., 2016], reflecting the fact that most of genetic variants have a small contribution to complex traits in GWAS.',evidence=[dict(page=6,location='Discussion after Condition 3 — coordinate interpretation')])]
add('D9','genetic heritability',r'''The genetic heritability $h_\beta^2$ of $\boldsymbol y$ can be defined as $h_\beta^2=(\boldsymbol\beta^T\boldsymbol X^T\boldsymbol X\boldsymbol\beta)/(\boldsymbol\beta^T\boldsymbol X^T\boldsymbol X\boldsymbol\beta+\boldsymbol\epsilon^T\boldsymbol\epsilon)\in(0,1)$, which describes how much variation in a trait can be attributed to genetic factors.''',[6],'Section 2.1 — genetic heritability',{'D2':'The numerator and noise denominator use the realized training model.'},phrases=['genetic heritability'],symbols=[r'h_\beta^2'],shape='Realized training-sample signal-energy fraction, not a centered population variance ratio. Testing-noise variance can differ under the printed Condition 3; the consequences are retained as a source issue.')
add('D10','block-wise covariance matrix',r'''The $\boldsymbol\Sigma_l$s’ can be approximated by $\widehat{\boldsymbol\Sigma}_B=\operatorname{Diag}(\widehat{\boldsymbol\Sigma}_{B_1},\ldots,\widehat{\boldsymbol\Sigma}_{B_l},\ldots,\widehat{\boldsymbol\Sigma}_{B_K})$ based on the training data $\boldsymbol X$, where $\widehat{\boldsymbol\Sigma}_{B_l}=n^{-1}\boldsymbol X_l^T\boldsymbol X_l$ for $l=1,\ldots,K$.''',[7],'Section 2.2(i) — training block covariance',{'D4':'The training Gram blocks use the known column boundaries.'},context=r'Its major technical challenge is to obtain the limit of trace functions involving the population covariance matrix $\boldsymbol\Sigma$, the sample covariance matrix $\widehat{\boldsymbol\Sigma}$, and the block-wise covariance matrix $\widehat{\boldsymbol\Sigma}_B$',symbols=[r'\widehat{\boldsymbol\Sigma}_B',r'\widehat{\boldsymbol\Sigma}_{B_l}'],shape='Block diagonal assembly of uncentered training Gram matrices divided by n. It discards all off-block empirical entries; it does not compute a regression estimator.')
members['D10']['naming_context'][0]['evidence']=[dict(page=8,location='Section 3 — matrix terminology')]
add('D11','external reference panel',r'''The $\boldsymbol\Sigma_l$s’ can be approximated by $\widehat{\boldsymbol\Sigma}_{BW}=\operatorname{Diag}(\widehat{\boldsymbol\Sigma}_{BW_1},\ldots,\widehat{\boldsymbol\Sigma}_{BW_l},\ldots,\widehat{\boldsymbol\Sigma}_{BW_K})$ based on the external reference panel $\boldsymbol W$, where $\widehat{\boldsymbol\Sigma}_{BW_l}=n_w^{-1}\boldsymbol W_l^T\boldsymbol W_l$ for $l=1,\ldots,K$.''',[7],'Section 2.2(ii) — covariance from the external reference panel',{'D4':'The reference Gram blocks use the same population block boundaries and their reference-design columns.'},phrases=['external reference panel'],symbols=[r'\widehat{\boldsymbol\Sigma}_{BW_l}',r'\widehat{\boldsymbol\Sigma}_{BW}'],shape='Original source construction of a block covariance estimate from the external reference data, divided by n_w. The title is a source keyword; the unchanged mathematical definition is the covariance construction.')
add('D12','testing data',r'''The $\boldsymbol\Sigma_l$s’ can also be approximated by $\widehat{\boldsymbol\Sigma}_{BZ}=\operatorname{Diag}(\widehat{\boldsymbol\Sigma}_{BZ_1},\ldots,\widehat{\boldsymbol\Sigma}_{BZ_l},\ldots,\widehat{\boldsymbol\Sigma}_{BZ_K})$ based on the testing data $\boldsymbol Z$, where $\widehat{\boldsymbol\Sigma}_{BZ_l}=n_z^{-1}\boldsymbol Z_l^T\boldsymbol Z_l$ for $l=1,\ldots,K$.''',[7],'Section 2.2(iii) — covariance from the testing data',{'D4':'The testing Gram blocks use the same population boundaries and testing-design columns.'},phrases=['testing data'],symbols=[r'\widehat{\boldsymbol\Sigma}_{BZ_l}',r'\widehat{\boldsymbol\Sigma}_{BZ}'],shape='Block covariance estimated from the same testing design used in the prediction accuracy. This is distinct from an external independent reference matrix.')
add('D13','sample covariance matrix',r'''where $\widehat{\boldsymbol\Sigma}=n^{-1}\boldsymbol X^T\boldsymbol X$.''',[7],'Section 2.2 — full training covariance',{'D1':'The full Gram matrix is formed from the training design.'},context=r'the sample covariance matrix $\widehat{\boldsymbol\Sigma}$',symbols=[r'\widehat{\boldsymbol\Sigma}=n^{-1}\boldsymbol X^T\boldsymbol X'],shape='Full uncentered training Gram matrix divided by n; off-block entries remain. No ridge estimate or causal-response model is required for this matrix functional.')
members['D13']['naming_context'][0]['evidence']=[dict(page=8,location='Section 3 — full covariance terminology')]
add('D14','Block-wise ridge estimator',r'''
The corresponding black-wise ridge estimator is
\[
\widehat{\boldsymbol\beta}_B(\lambda)=\{\widehat{\boldsymbol\beta}_{B_1}(\lambda)^T,\ldots,\widehat{\boldsymbol\beta}_{B_l}(\lambda)^T,\ldots,\widehat{\boldsymbol\beta}_{B_K}(\lambda)^T\}^T,\qquad\lambda\in(0,\infty),
\]
where $\widehat{\boldsymbol\beta}_{B_l}(\lambda)=n^{-1}(\widehat{\boldsymbol\Sigma}_{B_l}+\lambda\boldsymbol I_{p_l})^{-1}\boldsymbol X_l^T\boldsymbol y$ for $l\in1,\ldots,K$.
''',[7],'Section 2.2(i) — ridge estimator using training covariance',{'D10':'The inverse uses the training block covariance estimate.'},context=r'i) Block-wise ridge estimator with $\boldsymbol X$',symbols=[r'\widehat{\boldsymbol\beta}_B(\lambda)',r'\widehat{\boldsymbol\beta}_{B_l}(\lambda)'],shape='Concatenated ridge estimates using each local training covariance and the training cross-product. The source typo black-wise is preserved in the body; the natural-language keyword comes from the printed subsection heading.')
add('D15','block-wise ridge estimator',r'''
The corresponding block-wise ridge estimator is
\[
\widehat{\boldsymbol\beta}_{BW}(\lambda)=\{\widehat{\boldsymbol\beta}_{BW_1}(\lambda)^T,\ldots,\widehat{\boldsymbol\beta}_{BW_l}(\lambda)^T,\ldots,\widehat{\boldsymbol\beta}_{BW_K}(\lambda)^T\}^T,\qquad\lambda\in(0,\infty),
\]
where $\widehat{\boldsymbol\beta}_{BW_l}(\lambda)=n_w^{-1}(\widehat{\boldsymbol\Sigma}_{BW_l}+\lambda\boldsymbol I_{p_l})^{-1}\boldsymbol X_l^T\boldsymbol y$ for $l=1,\ldots,K$.
''',[7],'Section 2.2(ii) — ridge estimator using external reference covariance',{'D11':'The inverse uses reference-panel Gram blocks; the response cross-product still uses training data.'},phrases=['block-wise ridge estimator'],symbols=[r'\widehat{\boldsymbol\beta}_{BW}(\lambda)',r'\widehat{\boldsymbol\beta}_{BW_l}(\lambda)'],shape='External-covariance ridge with the printed n_w^{-1} training cross-product factor, not n^{-1}. The covariance and response cross-product use different datasets.')
add('D16','block-wise ridge estimator',r'''
The corresponding block-wise ridge estimator is
\[
\widehat{\boldsymbol\beta}_{BZ}(\lambda)=\{\widehat{\boldsymbol\beta}_{BZ_1}(\lambda)^T,\ldots,\widehat{\boldsymbol\beta}_{BZ_l}(\lambda)^T,\ldots,\widehat{\boldsymbol\beta}_{BZ_K}(\lambda)^T\}^T,\qquad\lambda\in(0,\infty),
\]
where $\widehat{\boldsymbol\beta}_{BZ_l}(\lambda)=n_z^{-1}(\widehat{\boldsymbol\Sigma}_{BZ_l}+\lambda\boldsymbol I_{p_l})^{-1}\boldsymbol X_l^T\boldsymbol y$ for $l=1,\ldots,K$.
''',[7],'Section 2.2(iii) — ridge estimator using testing covariance',{'D12':'The inverse uses testing-design Gram blocks while the cross-product uses training responses.'},phrases=['block-wise ridge estimator'],symbols=[r'\widehat{\boldsymbol\beta}_{BZ}(\lambda)',r'\widehat{\boldsymbol\beta}_{BZ_l}(\lambda)'],shape='Testing-covariance ridge with the printed n_z^{-1} factor and training response cross-product. Its estimate depends on the testing design used in the accuracy functional.')
add('D17','out-of-sample predictor',r'''Let $\widehat{\boldsymbol\beta}$ be a generic $p\times1$ estimator of $\boldsymbol\beta$, the out-of-sample predictor is given by $\widehat{\boldsymbol S}_Z=\boldsymbol Z\widehat{\boldsymbol\beta}$. Then, the out-of-sample $R^2$ is given by $A^2=(\boldsymbol y_z^T\widehat{\boldsymbol S}_Z)^2/(\|\boldsymbol y_z\|\cdot\|\widehat{\boldsymbol S}_Z\|)^2$, where $\|\boldsymbol y_z\|^2=\boldsymbol y_z^T\boldsymbol y_z$ and $\|\widehat{\boldsymbol S}_Z\|^2=\widehat{\boldsymbol S}_Z^T\widehat{\boldsymbol S}_Z$.''',[8],'Section 2.2 — prediction and accuracy functional',{'D1':'Prediction is evaluated on the testing design and response.'},phrases=['out-of-sample predictor'],symbols=[r'\widehat{\boldsymbol S}_Z',r'A^2'],shape='Squared uncentered cosine between test response and prediction, called out-of-sample R^2 by the author. It is not a centered coefficient of determination; zero-norm cases are not defined in the source.')
add('D18','Stieltjes transform',r'''Specifically, for a given distribution $F(t)$ with support on $[0,\infty)$, the Stieltjes transform is defined as $m_F(z)=\int_0^\infty(t-z)^{-1}\,dF(t)$ [Dobriban and Wager, 2018].''',[8],'Section 3 — Stieltjes transform',phrases=['Stieltjes transform'],symbols=[r'm_F(z)'],shape='Resolvent transform with convention (t-z)^{-1}. Negative real z=-lambda is used in the theorems. The source does not explicitly state the full complex domain or branch selection conditions.')
add('D19','Stieltjes transform',r'''The ESD of $\widehat{\boldsymbol\Sigma}_{B_l}$ is denoted by $F_{p_l}^{\widehat{\boldsymbol\Sigma}_{B_l}}(x)=p_l^{-1}\cdot\sum_{i=1}^{p_l}\mathrm I(\lambda_i(\widehat{\boldsymbol\Sigma}_{B_l})\leq x)$ for $x\in\mathbb R$. As $p_l\to\infty$, it is well-known [Yao et al., 2015] that $F_{p_l}^{\widehat{\boldsymbol\Sigma}_{B_l}}(x)$ converges weakly to the LSD of $\widehat{\boldsymbol\Sigma}_{B_l}$, denoted as $M_l(x)$, with probability one. The Stieltjes transform of $M_l(x)$, denoted as $m_l(z)$, can be implicitly defined by the Marchenko-Pastur equation given in equation (4) below [Bai and Zhou, 2008, Marchenko and Pastur, 1967, Silverstein, 1995].''',[8],'Section 3 — training sample spectral law and transform',{'D10':'The sample ESD is for the training block covariance.','D18':'m_l is the Stieltjes transform, with the stated sign convention, of the sample LSD.'},kind='source_passage',phrases=['Stieltjes transform'],symbols=[r'M_l(x)',r'm_l(z)'],shape='Names for training-block sample ESD, its almost-sure limiting law and its transform. The convergence assertion is retained as source prose, not counted as a new theorem or substituted for population H_l.')
add('D20','Stieltjes transform',r'''Let $v_{w_l}(-\lambda)=\omega_{w_l}\{m_{w_l}(-\lambda)-\lambda^{-1}\}+\lambda^{-1}$, and $m_{w_l}(z)=\int[t\{1-\omega_{w_l}-\omega_{w_l}zm_{w_l}(z)\}-z]^{-1}\,dH_l(t)$ denotes the Stieltjes transform of the LSD of $\widehat{\boldsymbol\Sigma}_{BW_l}$, denoted as $M_{w_l}(x)$.''',[12],'Section 4 — reference-panel spectral transforms',{'D11':'The sample law is the LSD of the external reference Gram block.','D5':'The fixed-point equation uses the population block LSD H_l.','D6':'The transform uses the reference block aspect ratio omega_w_l.','D18':'m_w_l is a Stieltjes transform in the source convention.'},phrases=['Stieltjes transform'],symbols=[r'v_{w_l}(-\lambda)',r'm_{w_l}(z)',r'M_{w_l}(x)'],shape='Reference sample transform and its companion relation. They are distinct from m_l and M_l for the training data; K_l in Theorem 3 refers to this companion transform.')
add('D21','sub-matrix',r'''Let $\boldsymbol A$ be a generic $p\times p$ matrix and $\boldsymbol A_m$ be an $m\times m$ sub-matrix of $\boldsymbol A$ corresponding to the $m$ causal variants with nonzero effects.''',[9],'Condition 4 — notation for the causal submatrix',{'D2':'The subset is indexed by the causal coordinates of the polygenic model.'},kind='definition',phrases=['sub-matrix'],symbols=[r'\boldsymbol A_m'],shape='Restriction of a square matrix to causal-coordinate rows and columns. This notation is reused in Condition 5 without imposing the separate Condition 4 trace-ratio hypotheses.')
add('D22','homogeneity',r'''As $\min(n,p)\to\infty$, we assume $\operatorname{tr}(\boldsymbol A_m)/\operatorname{tr}(\boldsymbol A)=\gamma+o_p(1)$ for $\boldsymbol A=\boldsymbol\Sigma(\widehat{\boldsymbol\Sigma}_B+\lambda\boldsymbol I_p)^{-1}\widehat{\boldsymbol\Sigma}$ and $\widehat{\boldsymbol\Sigma}(\widehat{\boldsymbol\Sigma}_B+\lambda\boldsymbol I_p)^{-1}\boldsymbol\Sigma(\widehat{\boldsymbol\Sigma}_B+\lambda\boldsymbol I_p)^{-1}\widehat{\boldsymbol\Sigma}$.''',[9],'Condition 4 — trace-ratio assumptions',{'D21':'The numerator uses the causal-coordinate submatrix.','D7':'gamma is the limiting causal fraction from Condition 2.','D10':'Both specified matrices use the training block inverse.','D13':'Both specified matrices also use the full training covariance.'},kind='condition',context=r'Condition 4 describes some mild conditions on the homogeneity between the $m$ causal variants and the $p-m$ null variants',phrases=['Condition 4'],symbols=[r'\operatorname{tr}(\boldsymbol A_m)/\operatorname{tr}(\boldsymbol A)'],shape='Trace-ratio convergence for exactly the two listed matrices. Not a universal assumption over arbitrary matrices and not the reference/testing variants of Condition 5.')
add('D23','homogeneity',r'''As $\min(n,n_w,n_z,p)\to\infty$, we assume $\operatorname{tr}(\boldsymbol A_m)/\operatorname{tr}(\boldsymbol A)=\gamma+o_p(1)$ for $\boldsymbol A=\widehat{\boldsymbol\Sigma}(\widehat{\boldsymbol\Sigma}_{BZ}+\lambda\boldsymbol I_p)^{-1}\widehat{\boldsymbol\Sigma}_Z(\widehat{\boldsymbol\Sigma}_{BZ}+\lambda\boldsymbol I_p)^{-1}\widehat{\boldsymbol\Sigma}$, $\widehat{\boldsymbol\Sigma}(\widehat{\boldsymbol\Sigma}_{BZ}+\lambda\boldsymbol I_p)^{-1}\boldsymbol\Sigma$, $\widehat{\boldsymbol\Sigma}(\widehat{\boldsymbol\Sigma}_{BW}+\lambda\boldsymbol I_p)^{-1}\boldsymbol\Sigma(\widehat{\boldsymbol\Sigma}_{BW}+\lambda\boldsymbol I_p)^{-1}\widehat{\boldsymbol\Sigma}$, and $\boldsymbol\Sigma(\widehat{\boldsymbol\Sigma}_{BW}+\lambda\boldsymbol I_p)^{-1}\boldsymbol\Sigma$, where $\widehat{\boldsymbol\Sigma}_Z=n_z^{-1}\boldsymbol Z^T\boldsymbol Z$.''',[12],'Condition 5',{'D21':'The same causal-coordinate submatrix notation is reused, without importing Condition 4 assumptions.','D7':'gamma is the causal-fraction limit in Condition 2.','D11':'The last two specified matrices use the reference block covariance.','D12':'The first two specified matrices use the testing block covariance.','D13':'The listed products include the full training covariance.'},kind='condition',context=r'Similar to Condition 4, Condition 5 is a set of mild assumptions on the overall homogeneity between the $m$ causal variants and the $p-m$ null variants.',phrases=['Condition 5'],symbols=[r'\operatorname{tr}(\boldsymbol A_m)/\operatorname{tr}(\boldsymbol A)',r'\widehat{\boldsymbol\Sigma}_Z'],shape='Trace-ratio convergence for four explicitly listed matrices, including a full testing Gram matrix defined in the condition. The last matrix ends in population Sigma as printed, not the empirical training covariance.')
def main():
    (ROOT/'source-passages.json').write_text(json.dumps(dict(paper_id=PID,members=list(members.values()),local_dependency_reasons=edges),indent=2,ensure_ascii=False)+'\n')
    (ROOT/'interface-draft.json').write_text(json.dumps(interfaces,indent=2,ensure_ascii=False)+'\n')
    print('Saved 23 source interfaces; dependency finalization and source audit remain.')

if __name__ == "__main__":
    main()
