"""Preserve original segmented-model, assumption, estimator and bootstrap source passages."""
import json,hashlib
from save_inventory import ROOT,PID,STATEMENTS
REVIEW_ROOT=ROOT
interfaces=[];members={}
def add(n,term,s,pages,deps,symbols,boundary,heading,kind='definition',context=None,context_page=None,phrases=None):
    lid=f'D{n}'
    m=dict(paper_id=PID,local_id=lid,local_label=heading,source_heading=heading,source_kind=kind,statement_original=s,relation='exact',depends_on=[f'D{i}' for i in deps],evidence=[dict(page=p,location=heading) for p in pages],highlight_symbols=symbols,highlight_phrases=phrases or [])
    kw=dict(paper_id=PID,local_id=lid,source_text=term,label=term[0].upper()+term[1:],kind='term')
    if term not in s:
        assert context and term in context,(lid,term)
        m['naming_context']=[dict(context_id=lid+'/name',text=context,evidence=[dict(page=context_page or pages[0],location='Original naming context')])];kw['context_id']=lid+'/name'
    members[lid]=m
    interfaces.append(dict(interface_id=PID+'/'+lid,rank_group='all',name=kw['label'],lean_role='definition',type_shape=boundary,semantic_boundary=boundary,members=[m],source_keywords=[kw],central_claim_uses=[],dependencies=[],theorem_explanations={}))
add(1,'four-regime regression model',r'''Let $\{W_t=(Y_t,X_t,Z_{1,t},Z_{2,t})\}_{t=1}^T$ be a sequence of observations, where $Y_t$ is the response variable to covariates $X_t\in\mathbb R^p$ and two partitioning variables $Z_{i,t}\in\mathbb R^{d_i}$ for $i=1$ and $2$, which determine the boundaries of the segments or regimes. The variables $X_t$, $Z_{1,t}$ and $Z_{2,t}$ can share common variables. The four-regime regression model is
\[
Y_t=\sum_{k=1}^4X_t^\top\beta_{k0}\mathbf1\{Z_t\in R_k(\gamma_0)\}+\varepsilon_t,
\]
(2.1)
where $Z_t$ is the union of variables of $Z_{1,t}$ and $Z_{2,t}$, $\{\beta_{k0}\}_{k=1}^4$ are the regression coefficients, $\{\gamma_{i0}\}_{j=1}^2$ are the boundary coefficients, $\varepsilon_t$ is the residual satisfying $\mathbb E(\varepsilon_t\mid X_t,Z_t)=0$ with a finite second moment, and $R_k(\gamma_0)$ is the $k$-th region split by the hyperplanes $\{H_{i0}:z_i^\top\gamma_{i0}=0\}_{i=1}^2$ for $z_i\in\mathbb R^{d_i}$. The overall parameter of interest is $\theta=(\gamma^\top,\beta^\top)^\top$ where $\beta=(\beta_1^\top,\cdots,\beta_4^\top)^\top$ and $\gamma=(\gamma_1^\top,\gamma_2^\top)^\top$. We let $\theta_0$, $\beta_0$ and $\gamma_0$ denote the respective true parameters.''',[3],[2],[r'Y_t=\sum_{k=1}^4',r'\theta=(\gamma^\top,\beta^\top)^\top'],'Four-regime model with mean-zero conditional residual and finite second moment. Preserve the i/j index mismatch in the boundary-coefficient set and the permission to share variables. This stochastic premise is separate from purely algebraic LS/MIQP definitions.','Section 2 — Four-regime regression model (2.1)',kind='source_passage')
add(2,'regression region',r'''For any observation $W_t$, it is the signs of $Z_{1,t}^\top\gamma_{10}$ and $Z_{2,t}^\top\gamma_{20}$ that determine which regression region it is located at. Denote by $\mathbf1_1(U,V)=\mathbf1(U>0,V>0)$, $\mathbf1_2(U,V)=\mathbf1(U\le0,V>0)$, $\mathbf1_3(U,V)=\mathbf1(U\le0,V\le0)$ and $\mathbf1_4(U,V)=\mathbf1(U>0,V\le0)$.''',[3],[],[r'\mathbf1_1(U,V)',r'\mathbf1_2(U,V)',r'\mathbf1_3(U,V)',r'\mathbf1_4(U,V)'],'Original four-region sign convention, including assignment of zero values to nonpositive sides. It defines the source R_k for any candidate pair of hyperplanes.','Section 2 — Four-region indicators')
add(3,'parameter space',r'''and the parameter space is $\Theta=\Gamma_1\times\Gamma_2\times\mathcal B^4$, where $\Gamma_i$ is a compact set in $\mathbb R^{d_i}$ and the first element of any $\gamma\in\Gamma_i$ is normalized as $1$ for each $i=1,2$, and $\mathcal B$ is a compact set in $\mathbb R^p$.''',[4],[],[r'\Theta=\Gamma_1\times\Gamma_2\times\mathcal B^4'],'Compact normalized boundary spaces and compact coefficient space. No convex/polyhedral or box property is stated here; those properties are not inferred from compactness.','Section 3 — Parameter space')
add(4,'least squares criterion function',r'''\[
\mathbb M_T(\theta)=\frac1T\sum_{t=1}^T\left\{Y_t-\sum_{k=1}^4X_t^\top\beta_k\mathbf1_k(Z_{1,t}^\top\gamma_1,Z_{2,t}^\top\gamma_2)\right\}^2=:\frac1T\sum_{t=1}^Tm(W_t,\theta),
\]
(3.1)''',[4],[2],[r'\mathbb M_T(\theta)',r'm(W_t,\theta)'],'Empirical squared-error criterion on supplied data; its definition does not impose the true stochastic four-regime model.','Section 3 — Least squares criterion (3.1)',context='we define the following least squares criterion function')
add(5,'minimizers',r'''Since $\mathbb M_T(\theta)$ is strictly convex in $\beta$ and piece-wise constant in $\gamma$ with at most $T$ jumps, it has a unique minimizer $\widehat\beta=(\widehat\beta_1^\top,\cdots,\widehat\beta_4^\top)^\top$ for $\beta$, but a set of minimizers for $\gamma$, which is denoted as $\widehat{\mathcal G}$, such that a LSE $\widehat\theta=(\widehat\gamma^\top,\widehat\beta^\top)^\top$ satisfies
\[
\mathbb M_T(\widehat\theta)=\inf_{\theta\in\Theta}\mathbb M_T(\theta)\quad\text{for any }\widehat\gamma\in\widehat{\mathcal G}.
\]
(3.2)''',[4],[3,4],[r'\widehat{\mathcal G}',r'\mathbb M_T(\widehat\theta)'],'Original LSE and set-valued boundary-solution passage. Preserve its strict-convexity/uniqueness assertions as source assertions, with their missing finite-sample qualifications recorded separately. The later finite set of two boundary vectors reuses the same symbol and is stored separately.','Section 3 — Least squares minimizers (3.2)',kind='source_passage')
add(6,'temporal dependence',r'''(i) The time series $\{W_t\}_{t\ge1}$ is strictly stationary and $\rho$-mixing with the mixing coefficient $\rho(t)\le c\alpha^t$ for finite positive constants $c$ and $\alpha\in(0,1)$, where $\rho(t)=\sup_{s,t\ge1}\{\sup\operatorname{Corr}(f,g):f\in\Omega_1^s,g\in\Omega_{s+t}^\infty\}$, where $\Omega_i^j$ denotes the $\sigma$-filed generated by $\{W_t:i\le t\le j\}$. (ii) $\mathbb E(\varepsilon_t\mid\mathcal F_{t-1})=0$, where $\mathcal F_{t-1}$ is a filtration generated by $\{(X_i,Z_{1i},Z_{2i},\varepsilon_{i-1}):i\le t\}$.''',[4,5],[],[r'\rho(t)\le c\alpha^t',r'\mathbb E(\varepsilon_t\mid\mathcal F_{t-1})=0'],'Source assumption on data W and residuals, with geometric rho mixing and its original correlation/filtration notation. It applies to both original and degenerate models through their own residuals; no edge to the four-regime model is imposed by symbol reuse alone.','Assumption 1 — Temporal dependence',kind='assumption',context='Assumption 1 (temporal dependence).',phrases=['Assumption 1'])
add(7,'identification',r'''For $i\in\{1,2\}$ and $k,h\in\{1,\cdots,4\}$, (i) $Z_1$ and $Z_2$ are not identically distributed. (ii) There exists a $j\in\{1,\cdots,d_i\}$ such that $\mathbb P(|q_i|\le\epsilon\mid Z_{-j,i})>0$ almost surely for $Z_{-j,i}$ and for any $\epsilon>0$, where $Z_{-j,i}$ is the vector after excluding $Z_i$'s $j$th element; without loss of generality, assume $j=1$. (iii) For any $\gamma\in\Gamma_1\times\Gamma_2$ and $\mathbb P\{Z\in R_k(\gamma_0)\cap R_h(\gamma)\}>0$, the smallest eigenvalue of $\mathbb E\{XX^\top\mid Z\in R_k(\gamma_0)\cap R_h(\gamma)\}\ge\lambda_0$ for some constant $\lambda_0>0$. (iv) For $(k,h)\in S(i)$, $\|\beta_{k0}-\beta_{h0}\|>c_0$ for some constant $c_0>0$.''',[5],[2,3,11],[r'\mathbb P(|q_i|\le\epsilon\mid Z_{-j,i})',r'\|\beta_{k0}-\beta_{h0}\|>c_0'],'All four original identification clauses; strictly positive fixed boundary effects and uniform positive eigenvalue condition on nonempty true/candidate intersections. Do not import unchanged into the degenerate models that use supplementary replacements.','Assumption 2 — Identification',kind='assumption',context='Assumption 2 (identification).',phrases=['Assumption 2'])
add(8,'moment condition',r'''(i) $\mathbb E(Y^4)<\infty$, $\mathbb E(\|X\|^4)<\infty$ and $\max_{i=1,2}\mathbb E(\|Z_i\|)<\infty$. (ii) For each $i=1$ and $2$, $\mathbb P(Z_i^\top\gamma_1<0<Z_i^\top\gamma_2)\le c_1\|\gamma_1-\gamma_2\|$ if $\gamma_1,\gamma_2,\in\mathcal N(\gamma_{i0};\delta_0)$, for some constants $\delta_0,c_1>0$.''',[5],[],[r'\mathbb E(Y^4)',r'\mathbb P(Z_i^\top\gamma_1<0<Z_i^\top\gamma_2)'],'Original moments and local hyperplane-crossing probability bound. Preserve the source extra comma and the first-moment requirement for Z; do not change it to a fourth moment.','Assumption 3',kind='assumption',context='Assumption 3 (i) is a moment condition',phrases=['Assumption 3'])
add(9,'regression surface',r'''(i) For $i=1$ and $2$, there exist constants $\delta_1,c_2>0$ such that if $\epsilon\in(0,\delta_1)$ then $\mathbb P(|q_i|<\epsilon\mid Z_{-1,i})\ge c_2\epsilon$ almost surely. (ii) For $i=1$ and $2$, there exists a neighborhood $\mathcal N_i=\mathcal N(\gamma_{i0};\delta_2)$ of $\gamma_{i0}$ for some $\delta_2>0$, such that $\inf_{\gamma\in\mathcal N_i}\mathbb E(\|X^\top\delta_{kh,0}\|\mid Z_i^\top\gamma=0)>0$ almost surely for each $(k,h)\in S(i)$, where $\delta_{kh,0}=\beta_{k0}-\beta_{h0}$. (iii) $\mathbb P(Z_1^\top\gamma_1<0<Z_1^\top\gamma_2,Z_2^\top\gamma_3<0<Z_2^\top\gamma_4)\le c_3\|\gamma_1-\gamma_2\|\|\gamma_3-\gamma_4\|$ for some constant $c_3>0$ if $\gamma_1,\gamma_2\in\mathcal N_1$ and $\gamma_3,\gamma_4\in\mathcal N_2$. (iv) $\sup_{\gamma\in\mathcal N_i}\mathbb E(\|X\|^8\mid Z_i^\top\gamma=0)<\infty$ and $\sup_{\gamma\in\mathcal N_i}\mathbb E(\varepsilon^8\mid Z_i^\top\gamma=0)<\infty$ almost surely.''',[6],[11],[r'\mathbb P(|q_i|<\epsilon\mid Z_{-1,i})',r'\delta_{kh,0}',r'\|\gamma_1-\gamma_2\|\|\gamma_3-\gamma_4\|'],'All four clauses, including positive local boundary mass, nonvanishing regression jump, a product bound near intersecting hyperplanes, and conditional eighth moments. The main-text probability-zero conditioning requires a version convention not supplied here.','Assumption 4',kind='assumption',context='Assumption 4 (ii) ensures there is a jump of the regression surface at the splitting hyperplane',phrases=['Assumption 4'])
add(10,'conditional densities',r'''(i) For $i=1$ and $2$, there exist constants $\delta_3,c_4>0$ such that $\mathbb P(|q_{i,t}|\le\delta_3,|q_{i,t+j}|\le\delta_3)\le c_4\{\mathbb P(|q_{i,t}|\le\delta_3)\}^2$ uniformly for $t\ge1$ and $j\ge1$; (ii) For each $z_{-1,i}\in\mathcal Z_{-1,i}$, the conditional density $f_{q_i\mid Z_{-1,i}}(q\mid z_{-1,i})$ is continuous at $q=0$ and $c_4\le f_{q_i\mid Z_{-1,i}}(0\mid z_{-1,i})\le c_5$ for some constants $c_4,c_5>0$; (iii) For each $\xi\in\mathbb R$ and $z_{-1,i}\in\mathcal Z_{-1,i}$, the conditional density $f_{\xi^{(k,h)}\mid q_i,Z_{-1,i}}(\xi\mid q_i,z_{-1,i})$ is continuous at $q_i=0$ and $f_{\xi^{(k,h)}\mid q_i,Z_{-1,i}}(\xi\mid0,z_{-1,i})\le c_6$ for a constant $c_6>0$; (iv) $\mathcal Z_{-1,i}$ is a compact subset of $\mathbb R^{d_i-1}$.''',[7],[11,13],[r'\mathbb P(|q_{i,t}|\le\delta_3,|q_{i,t+j}|\le\delta_3)',r'f_{q_i\mid Z_{-1,i}}',r'f_{\xi^{(k,h)}\mid q_i,Z_{-1,i}}'],'Preserve the fixed-delta non-clustering inequality and pointwise conditional-density continuity/bounds. Do not replace the printed fixed delta3 by a threshold tending to zero or invent uniform continuity.','Assumption 5',kind='assumption',context='Assumption 5 (ii) and (iii) are on the conditional densities',phrases=['Assumption 5'])
add(11,'adjacent regions',r'''Let $W=(Y,X,Z_1,Z_2)$ follow the stationary distribution $\mathbb P_0$ of $W_t$, and $q_i=Z_i^\top\gamma_{i0}$ for $i=1$ and $2$ to indicate whether $Z=(Z_1,Z_2)$ is located on the true hyperplane $H_{i0}:Z_i^\top\gamma_{i0}=0$ or not. Let $S(i)$ be the set consisting of index pairs $(k,h)$ if $R_k(\gamma_0)$ and $R_h(\gamma_0)$ are two adjacent regions split by $H_{i0}$. Specifically, $S(1)=\{(1,2),(2,1)(3,4),(4,3)\}$ and $S(2)=\{(1,4),(4,1),(2,3),(3,2)\}$ according to the provision in the lines above (2.2). Furthermore, let $Z$ be the union vector of variables in $Z_1$ and $Z_2$''',[4],[2],[r'q_i=Z_i^\top\gamma_{i0}',r'S(1)',r'S(2)'],'Ordered adjacent-region pairs and signed true-boundary coordinates. Preserve the missing comma in S(1); the prose establishes the intended index-pair set. Stationary data law is a binding here, not an import of every mixing hypothesis.','Section 3.1 — Boundary coordinates and adjacency',kind='source_passage')
add(12,'asymptotic variance',r'''To present the asymptotic distributions of $\widehat\beta$ and $\widehat\gamma$, we define for each $k\in\{1,\cdots,4\}$,
\[
B_k=\mathbb E\{XX^\top\mathbf1(Z\in R_k(\gamma_0)\}\quad\text{and}\quad\Sigma_k=B_k^{-1}\mathbb E\{XX^\top\varepsilon^2\mathbf1(Z\in R_k(\gamma_0)\}B_k^{-1}.
\]''',[7],[2],[r'B_k',r'\Sigma_k'],'Original covariance formula and its design moment, preserving missing indicator closing parentheses. The residual belongs to the theorem’s stochastic model; no long-run covariance is substituted.','Section 3.2 — Asymptotic covariance',context='as far as the asymptotic variance of $\widehat\beta_k$ is concerned',context_page=9)
add(13,'conditional distributions',r'''Let $q_{i,t}=Z_{i,t}^\top\gamma_{i0}$ and $q_i=Z_i^\top\gamma_{i0}$ for $i=1$ and $2$. Denote by $s_i^{(k)}=(-1)^{\mathbf1(q_i\le0,\ \forall Z\in R_k(\gamma_0))}$ be the sign of $q_i$ for $Z=(Z_1^\top,Z_2^\top)\in R_k(\gamma_0)$. For instance, $s_1^{(1)}=s_2^{(1)}=1$ and $s_1^{(2)}=-1,s_2^{(2)}=1$. If $R_k(\gamma_0)$ and $R_h(\gamma_0)$ are adjacent such that $(k,h)\in S(i)$ for $i=1$ or $2$, let
\[
\xi_t^{(k,h)}=(\delta_{kh,0}^\top X_tX_t^\top\delta_{kh,0}+2X_t^\top\delta_{kh,0}\varepsilon_t)\mathbf1\{Z_t\in R_k(\gamma_0)\cup R_h(\gamma_0)\}
\]
(3.3)
where $\delta_{kh,0}=\beta_{k0}-\beta_{h0}$. Let $Z_{-1,i,t}$ be the random vector of $Z_{i,t}$ excluding its first element. Suppose $(q_i,Z_{-1,i},\xi^{(k,h)})$ follows the stationary distribution of $(q_{i,t},Z_{-1,i,t},\xi_t^{(k,h)})$. We denote $F_{q_i\mid Z_{-1,i}}(q\mid Z_{-1,i})$ and $F_{\xi^{(k,h)}\mid q_i,Z_{-1,i}}(\xi\mid q_i,Z_{-1,i})$ as the conditional distributions of $q_i$ on $Z_{-1,i}$ and $\xi^{(k,h)}$ on $(q_i,Z_{-1,i})$, respectively, and the corresponding conditional densities are $f_{q_i\mid Z_{-1,i}}(q\mid Z_{-1,i})$ and $f_{\xi^{(k,h)}\mid q_i,Z_{-1,i}}(\xi\mid q_i,Z_{-1,i})$, respectively. Let $\mathcal Z_{-1,i}$ be the support of the distribution of $Z_{-1,i}$.''',[7],[2,11],[r'\xi_t^{(k,h)}',r's_i^{(k)}',r'f_{\xi^{(k,h)}\mid q_i,Z_{-1,i}}'],'Original signed boundary coordinates, contrast jump marks and their conditional distributions/densities. The sign convention is region-specific; the law conditioned at q=0 later supplies the limiting marks.','Section 3.2 — Jump marks and conditional distributions (3.3)',kind='source_passage')
add(14,'stochastic process',r'''The asymptotic distribution of $\widehat\gamma$ needs the following stochastic process
\[
D(v)=\sum_{i=1,2}\sum_{k,h\in S(i)}\sum_{\ell=1}^\infty\xi_{i,\ell}^{(k,h)}\mathbf1\left\{J_{i,\ell}^{(k,h)}+(Z_{i,\ell}^{(k,h)})^\top v_{-1,i}\le0<J_{i,\ell}^{(k,h)}\right\},
\]
(3.4)
for $v=(v_1^\top,v_2^\top)^\top\in\mathbb R^{d_1+d_2}$, where $\{(\xi_{i,\ell}^{(k,h)},Z_{i,\ell}^{(k,h)})\}_{\ell=1}^\infty$ are independent copies of $(\bar\xi_i^{(k,h)},Z_{-1,i})$ with $\bar\xi_i^{(k,h)}\sim F_{\xi^{(k,h)}\mid q_i,Z_{-1,i}}(\xi\mid0,Z_{-1,i})$, and $J_{i,\ell}^{(k,h)}=\mathcal J_{i,\ell}^{(k,h)}/f_{q_i\mid Z_{-1,i}}(0\mid Z_{i,\ell}^{(k,h)})$ with $\mathcal J_{i,\ell}^{(k,h)}=s_i^{(k)}\sum_{n=1}^\ell\mathcal E_{i,n}^{(k,h)}$ and $\{\mathcal E_{i,n}^{(k,h)}\}_{n=1}^\infty$ are independent unit exponential variables which are independent of $\{(\xi_{i,\ell}^{(k,h)},Z_{i,\ell}^{(k,h)})\}_{\ell=1}^\infty$. Moreover, $\{(\xi_{i,\ell}^{(k,h)},Z_{i,\ell}^{(k,h)},J_{i,\ell}^{(k,h)})\}_{\ell=1}^\infty$ are mutually independent with respect to $i=1,2$ and $(k,h)\in S(i)$.''',[7],[11,13],[r'D(v)',r'0<J_{i,\ell}^{(k,h)}',r'\mathcal J_{i,\ell}^{(k,h)}'],'Full printed limiting marked process with signed exponential arrivals, density scaling and independent families. Preserve the one-sided indicator and the full-space v domain; their implications for negative signs and free fixed coordinates are recorded as unresolved source issues.','Section 3.2 — Limiting stochastic process (3.4)')
add(15,'centroid',r'''Let $\mathcal G_D=\{v_m:D(v_m)\le D(v)\text{ if }v\ne v_m\}$ be the set of minimizers for $D(v)$. Since $D(v)$ is a piece-wise constant random function, there are infinitely many elements in $\mathcal G_D$. Such a phenomenon also appears in the threshold regression, where the minimizers of the process, that is a special case of (3.4), are attained in an interval, whose left endpoint is commonly used as a representative, which is not applicable to our case since $\mathcal G_D$ is a polyhedron. As treated in [35], we use the centroid of $\mathcal G_D$ as the representative. For any set $\mathcal A$ of $d$-dimensional vectors, the centroid of $\mathcal A$ is $C(\mathcal A)=\int_{v\in\mathcal A}v\,dv/\int_{v\in\mathcal A}dv$, which can be geometrically interpreted as the center of mass of the set $\mathcal A$. Let $\gamma_D^c=C(\mathcal G_D)$ and $\widehat\gamma^c=C(\widehat{\mathcal G})$, where $\widehat{\mathcal G}$ is the set for LS estimators for $\gamma$.''',[7,8],[5,14],[r'C(\mathcal A)',r'\gamma_D^c',r'\widehat\gamma^c'],'Source minimizer-set and centroid convention for the limiting process and LSEs. Dimension/volume conventions and existence of a bounded measurable minimizer set require clarification; do not define the centroid of a zero- or infinite-volume set by fiat.','Section 3.2 — Minimizer centroids',kind='source_passage')
add(16,'MIQP problem',r'''Let $g=\{g_{j,t}:j=1,2,t=1,\cdots,T\}$, $I=\{I_{k,t}:k=1,\cdots,4,t=1,\cdots,T\}$ and $\ell=\{\ell_{k,i,t}:k=1,\cdots,4,i=1,\cdots,p,t=1,\cdots,T\}$. Solve the following problem:
\[
\min_{\beta,\gamma,g,I,\ell}\frac1T\sum_{t=1}^T\left(Y_t-\sum_{k=1}^4\sum_{i=1}^pX_{t,i}\ell_{k,i,t}\right)^2
\]
(4.6)
subject to
\[
\begin{cases}
\beta_k\in\mathcal B,\ \gamma_j\in\Gamma_j,\ g_{j,t}\in\{0,1\},\ I_{k,t}\in\{0,1\},\ L_i\le\beta_{k,i}\le U_i,\\
(g_{j,t}-1)(M_{j,t}+\epsilon)<Z_{j,t}^\top\gamma_j\le g_{j,t}M_{j,t},\ I_{k,t}L_i\le\ell_{k,i,t}\le I_{k,t}U_i,\\
L_i(1-I_{k,t})\le\beta_{k,i}-\ell_{k,i,t}\le U_i(1-I_{k,t}),\\
I_{k,t}\le s_j^{(k)}g_{j,t}+(1-s_j^{(k)})/2,\quad I_{k,t}\ge\sum_{j=1}^2\{s_j^{(k)}g_{j,t}+(1-s_j^{(k)})/2\}-1,
\end{cases}
\]
(4.7)
for $k=1,\cdots,4$, $j=1,2$, $i=1,\cdots,p$ and $t=1,\cdots,T$.''',[10],[3,17,32],[r'\min_{\beta,\gamma,g,I,\ell}',r'(g_{j,t}-1)(M_{j,t}+\epsilon)'],'Complete source optimization and every constraint. Preserve the strict lower inequality and non-strict upper inequality; source epsilon extends the negative bound, not a positive classification margin. The theorem states equality of minima, not a guarantee about practical solver tolerances.','Section 4 — MIQP (4.6)–(4.7)',kind='source_passage',context='we transform the original LS problem (2.2) to a MIQP problem formulated as following.')
add(17,'constants',r'''As $\beta_k$ belongs to a compact set, there exist constants $L_i$ and $U_i$ such that $L_i\le\beta_{k,i}\le U_i$.''',[9],[3],[r'L_i\le\beta_{k,i}\le U_i'],'Coordinate bounds valid over the coefficient parameter space. Compactness supplies finite bounds but does not make the full parameter space polyhedral.','Section 4 — Coefficient bounds')
add(18,'heteroscedastic error',r'''Suppose that $Y$ is generated according to the following segmented linear regression model with heteroscedastic error
\[
Y=\sum_{k=1}^4X^\top\beta_0\mathbf1\{Z\in R_k(\gamma_0)\}+\sigma_0(X,Z)e,
\]
(5.1)
where $e$ has a continuous distribution and is independent of $(X,Z)$ with $\mathbb E(e)=0$ and $\mathbb E(e^2)=1$, and $\sigma_0^2(X,Z)$ is a conditional variance function representing possible heteroskedasticity. Model (5.1) is a refinement of Model (2.1) with more detailed structure on the residuals.''',[11],[1,2],[r'\sigma_0(X,Z)e',r'\mathbb E(e^2)=1'],'Bootstrap-specific error model with independent standardized error and conditional scale. The source prints beta_0 rather than beta_k0 inside the summation; retain that dimension/index discrepancy. It is a stated refinement of the four-regime model, not a consequence of a martingale difference condition alone.','Section 5 — Heteroscedastic model (5.1)',kind='source_passage')
add(19,'kernel smoothing estimator',r'''Let $F_0(x,z)$ be the distribution function of $(X,Z)$, whose density function is $f_0(x,z)$. We estimate $F_0(x,z)$ and $\sigma_0(x,z)$ nonparametrically with the kernel smoothing. Specifically, let $K_1(\cdot)$ and $K_2(\cdot)$ be a $p$-dimensional and a $(d_1+d_2)$-dimensional kernel functions, respectively. Let $G_i(u)=\int_{-\infty}^uK_i(u)\,du$ for $i=1,2$. The kernel smoothing estimator for $F_0(x,z)$ is given by
\[
\widetilde F_0(x,z)=\frac1T\sum_{t=1}^TG_1\left(\frac{X_t-x}{h_1}\right)G_2\left(\frac{Z_t-z}{h_2}\right),
\]
where $h_1$ and $h_2$ are smoothing bandwidths.''',[12],[],[r'\widetilde F_0(x,z)',r'\frac{X_t-x}{h_1}',r'\frac{Z_t-z}{h_2}'],'Original kernel-integral and smoothed-distribution formula. Preserve data-minus-evaluation arguments; they give decreasing rather than ordinary lower-tail CDF orientation. The stated ambient dimensions also need care if variables are shared. No corrected CDF is substituted.','Section 5 — Smoothed covariate distribution')
add(20,'local linear estimator',r'''With the LS estimator $(\widehat\gamma,\widehat\beta)$, the estimated residuals are $\widehat\varepsilon_t=Y_t-\sum_{k=1}^4X^\top\widehat\beta\mathbf1\{Z_t\in R_k(\widehat\gamma)\}$. The conditional variance function $\sigma_0^2(x,z)$ can be estimated via the local linear approach proposed by [10]. For any given $(x,z)$, the local linear estimator $\widetilde\sigma^2(x,z)=\widehat\alpha$, which is defined by
\[
(\widehat\alpha,\widehat\eta)=\arg\min_{(\alpha,\eta)}\sum_{t=1}^T\left\{\widehat\varepsilon_t^2-\alpha-((X_t-x)^\top,(Z_t-z)^\top)\eta\right\}^2K_1\left(\frac{X_t-x}{b_1}\right)K_2\left(\frac{Z_t-z}{b_2}\right),
\]
where $\eta\in\mathbb R^{p+d_1+d_2}$, and $b_1$ and $b_2$ are smoothing bandwidths.''',[12],[2,5,18,19],[r'\widetilde\sigma^2(x,z)=\widehat\alpha',r'\widehat\varepsilon_t^2-\alpha'],'Source local-linear regression of squared fitted residuals. Preserve the residual formula’s missing t/k subscripts, and do not silently truncate potentially negative or zero variance estimates. Kernel definitions are those of the preceding smoothing passage.','Section 5 — Local linear variance estimator')
add(21,'empirical distribution',r'''Let $\widehat e_t=\widehat\varepsilon_t/\widetilde\sigma(X_t,Z_t)$ and $\widetilde e_t=\widehat e_t-\bar e_T$, where $\bar e_T=\sum_{t=1}^T\widehat e_t/T$. Denote $\widehat G(e)$ as the empirical distribution of $\{\widetilde e_t\}_{t=1}^T$.''',[12],[20],[r'\widehat G(e)',r'\widetilde e_t=\widehat e_t-\bar e_T'],'Centered standardized residual empirical law. No additional variance normalization is printed. The residual law G-hat is distinct from the calligraphic boundary-minimizer set.','Section 5 — Standardized residual empirical distribution')
add(22,'kernel functions',r'''(i) The stationary distribution $F_0$ of $(X_t,Z_t)$ has a compact support and is absolute continuous with density $f_0(x,z)$ which is bounded and $\inf_{x,z}f_0(x,z)>0$. (ii) The conditional variance function $\sigma_0^2(x,z)$ is bounded and $\inf_{x,z}\sigma_0^2(x,z)>0$. (iii) The kernels $K_1(\cdot)$ and $K_2(\cdot)$ are symmetric density functions which are Lipshitz continuous and have bounded supports. The smoothing bandwidths satisfy $h_i,b_i\to0$ for $i=1$ and $2$, and $T(\log T)^{-1}h_1^ph_2^{d_1+d_2}\to\infty$ and $T(\log T)^{-1}b_1^pb_2^{d_1+d_2}\to\infty$ as $T\to\infty$.''',[12],[18,19,20],[r'\inf_{x,z}f_0(x,z)>0',r'T(\log T)^{-1}h_1^ph_2^{d_1+d_2}',r'T(\log T)^{-1}b_1^pb_2^{d_1+d_2}'],'All original density, conditional-variance, kernel and bandwidth clauses. Global lower bounds with compact density support and the missing smoothness/positivity conventions are retained as source issues, not repaired by extra assumptions.','Assumption 6',kind='assumption',context='the kernel functions, and the smoothing bandwidths to facilitate the Bootstrap procedure.',phrases=['Assumption 6'])
add(23,'bootstrap procedure',r'''The bootstrap procedure to approximate the distributions of $\{T(\widehat\gamma^c-\gamma_0),\sqrt T(\widehat\beta-\beta_0)\}$ is as follows.

Step 1: First, generate $\{(X_t^*,Z_t^*)\}_{t=1}^T$ independently from $\widetilde F(x,z)$ and $\{e_t^*\}_{t=1}^T$ independently from $\widehat G(e)$, respectively. Then, generate $Y_t^*=\sum_{k=1}^4(X_t^*)^\top\widehat\beta_k\mathbf1\{Z_t^*\in R_k(\widehat\gamma^c)\}+\widetilde\sigma(X_t^*,Z_t^*)e_t^*$ to obtain bootstrap resample $\{(Y_t^*,X_t^*,Z_t^*)\}_{t=1}^T$.

Step 2: Compute the LSEs based on $\{(Y_t^*,X_t^*,Z_t^*)\}_{t=1}^T$, where $\widehat\beta^*$ is the LSE for $\beta_0$ and $\{\widehat\gamma_i^*\}_{i=1}^N$ are the LSEs for $\gamma_0$ for a sufficiently large $N$. Let $\widehat\gamma^{*c}=\sum_{i=1}^N\widehat\gamma_i^*/N$.

Step 3: Repeat the above two steps $B$ times for a large positive integer $B$ to obtain $\{\widehat\gamma_b^{*c}\}_{b=1}^B$ and $\{\widehat\beta_b^*\}_{b=1}^B$, and use the empirical distribution of $\{T(\widehat\gamma_b^{*c}-\widehat\gamma^c),\sqrt T(\widehat\beta_b^*-\widehat\beta)\}_{b=1}^B$ as an estimate of the distribution of $\{T(\widehat\gamma^c-\gamma_0),\sqrt T(\widehat\beta-\beta_0)\}$.''',[12,13],[2,5,15,19,20,21],[r'\widetilde F(x,z)',r'\widehat\gamma^{*c}=\sum_{i=1}^N\widehat\gamma_i^*/N',r'\widehat\gamma_b^{*c}'],'Full three-step source bootstrap with independent resampling, original empirical centering, and averaging N boundary minimizers. Preserve F-tilde versus F0-tilde notation. The source does not specify a sampling law for minimizers or an N asymptotic sufficient for centroid approximation.','Section 5 — Smoothed regression bootstrap steps',kind='source_passage')
add(24,'empirical distribution',r'''Denote the distribution of $\{T(\widehat\gamma^c-\gamma_0),\sqrt T(\widehat\beta-\beta_0)\}$ as $\mathcal L_T$ and the empirical distribution of $\{T(\widehat\gamma_b^{*c}-\widehat\gamma^c),\sqrt T(\widehat\beta_b^*-\widehat\beta)\}_{b=1}^B$ as $\mathcal L_{T,B}$.''',[13],[5,15,23],[r'\mathcal L_T',r'\mathcal L_{T,B}'],'Original joint target law and bootstrap empirical law. Boundary estimates scale by T, regression estimates by sqrt T; source order is boundary then regression.','Section 5 — Target and bootstrap distributions')
add(25,'segmented models',r'''Figure 1 illustrates the segmented models with no more than four regimes, which can be expressed in a unified form
\[
Y_t=\sum_{k=1}^{K_0}X_t^\top\beta_{k0}\mathbf1\{Z_t\in R_k(\gamma_0)\}+\varepsilon_t,
\]
(6.6)
where the number of regimes $1\le K_0<4$ and the number of splitting hyperplanes $L_0\le2$. In particular, $R_k(\gamma_0)=\mathcal Z_1\times\mathcal Z_2$ for the global linear model $(K_0=1)$, the splitting coefficient $\gamma_0=\gamma_{10}$ or $\gamma_{20}$ when $L_0=1$, and $\gamma_0=(\gamma_{10}^\top,\gamma_{20}^\top)^\top$ when $L_0=2$.''',[15],[26,27,28,29,30],[r'K_0',r'L_0',r'Y_t=\sum_{k=1}^{K_0}'],'Source unified expression for the five listed lower-regime families, not a new four-regime data-generating assumption. Original family passages define the possible R_k; figures and formula inconsistencies are recorded separately.','Section 6 — Unified degenerate models (6.6)',kind='source_passage')
add(26,'Three-regime model',r'''\[
Y_t=\sum_{k=1}^3X_t^\top\beta_{k0}\mathbf1\{Z_t\in R_k(\gamma_0)\}+\varepsilon_t,
\]
(6.1)
where the two hyperplanes $H_1$ and $H_2$ have no intersection on $\mathcal Z_1\times\mathcal Z_2$. Without loss of generality, we suppose that $z_1^\top\gamma_{10}\le z_2^\top\gamma_{20}$ for all $(z_1,z_2)\in(\mathcal Z_1\times\mathcal Z_2)$. Then, $R_1(\gamma_0)=\{z:z_1^\top\gamma_{10}>0\}$, $R_2(\gamma_0)=\{z:z_1^\top\gamma_{10}\le0,z_2^\top\gamma_{20}>0\}$ and $R_3(\gamma_0)=\{z:z_2^\top\gamma_{20}\le0\}$. The conventional multi-threshold models (e.g., [12] and [23]) correspond to this case.''',[13,14],[],[r'R_2(\gamma_0)',r'z_1^\top\gamma_{10}\le z_2^\top\gamma_{20}'],'Nonintersecting two-hyperplane three-region family, preserving global ordering on the covariate support.','Section 6 (a.1) — Three-regime model with non-intersected splitting hyperplanes',kind='source_passage',context='(a.1). Three-regime model with non-intersected splitting hyperplanes:',context_page=13)
add(27,'Three-regime regression model',r'''\[
Y_t=\sum_{k=1}^3X_t^\top\beta_{k0}\mathbf1(Z_t\in R_k(\gamma_0)+\varepsilon_t,
\]
(6.2)
where $R_1(\gamma_0)=\{z:z_i^\top\gamma_{j,0}>0,z_j^\top\gamma_{j,0}>0\}$, $R_2(\gamma_0)=\{z:z_i^\top\gamma_{j,0}>0,z_j^\top\gamma_{j,0}\le0\}$ and $R_3(\gamma_0)=\{z:z_j^\top\gamma_{j,0}\le0\}$ for $i\ne j\in\{1,2\}$. Geometrically, one side of the hyperplane $H_j:z_j^\top\gamma_{j,0}=0$ is split by $H_i:z_i^\top\gamma_{i,0}=0$ that does not extend to the other side of $H_j$.''',[14],[],[r'z_i^\top\gamma_{j,0}',r'R_3(\gamma_0)'],'Original intersecting family, including the printed missing indicator delimiter and region/index inconsistencies. R2 as printed overlaps R3; Figure1(C) and the prose suggest different intended geometry. Do not silently replace the formulas by the figure.','Section 6 (a.2) — Three-regime regression model with intersected splitting hyperplanes',kind='source_passage',context='(a.2). Three-regime regression model with intersected splitting hyperplanes:')
add(28,'Two-regime regression model',r'''\[
Y_t=\sum_{k=1}^2X_t^\top\beta_{k0}\mathbf1\{Z_t\in R_k(\gamma_0)\}+\varepsilon_t,
\]
(6.3)
where $(z,\gamma_0)$ is either $(z_1,\gamma_{10})$ or $(z_2,\gamma_{20})$ and $R_1(\gamma_0)=\{z:z^\top\gamma_0>0\}$ and $R_2(\gamma_0)=\{z:z^\top\gamma_0\le0\}$, which are the same as the two-regime models of [22] and [35].''',[14],[],[r'z^\top\gamma_0>0',r'z^\top\gamma_0\le0'],'One-hyperplane two-region specialization, with gamma0 taking the dimension of the selected boundary covariates.','Section 6 (b.1) — Two-regime regression model with one splitting hyperplane',kind='source_passage',context='(b.1). Two-regime regression model with one splitting hyperplane:')
add(29,'Two-regime regression model',r'''\[
Y_t=\sum_{k=1}^2X_t^\top\beta_{k0}\mathbf1\{Z_t\in R_k(\gamma_0)\}+\varepsilon_t,
\]
(6.4)
where $R_1(\gamma_0)=\{z:z_1^\top\gamma_{10}>0,z_2^\top\gamma_{20}>0\}$ and $R_2\{\gamma_0\}=\mathcal Z_1\times\mathcal Z_2\setminus R_1(\gamma_0)$.''',[14],[],[r'R_1(\gamma_0)',r'R_2\{\gamma_0\}'],'Two-hyperplane family with a positive-positive intersection and its complement. Preserve the brace notation in R2 as printed.','Section 6 (b.2) — Two-regime regression model with two splitting hyperplanes',kind='source_passage',context='(b.2). Two-regime regression model with two splitting hyperplanes:')
add(30,'Global linear model',r'''\[
Y_t=X_t^\top\beta_0+\varepsilon_t,
\]
(6.5)''',[14],[],[r'Y_t=X_t^\top\beta_0+\varepsilon_t'],'Global linear model, the K0=1 family with no splitting hyperplane.','Section 6 (c) — Global linear model',kind='source_passage',context='(c). Global linear model:')
add(31,'distance',r'''Let $\widehat{\mathcal B}=\{\widehat\beta_k\}_{k=1}^4$ and $\widehat{\mathcal G}=\{\widehat\gamma_j\}_{j=1}^2$ be the LS estimators for the regression and the boundary coefficients, respectively, obtained under the four-regime regression model (3.2). To measure the estimation accuracy of the four-regime algorithms for less than four regime models, we need a distance of the true parameters of possibly degenerated models to the set of the LS estimates under the four-regime model. To this end, we define a distance between a vector $v$ and a set of vectors $\widehat{\mathcal V}=\{\widehat v_j\}_{j=1}^J$ as $d(v,\widehat{\mathcal V})=\min_j\|v-\widehat v_j\|_2$.''',[15],[5],[r'\widehat{\mathcal B}',r'd(v,\widehat{\mathcal V})'],'Point-to-finite-set Euclidean distance, not squared distance. This passage reuses G-hat for the two fitted boundary vectors, distinct from the full boundary-minimizer set earlier. Comparing differently dimensioned boundary vectors needs a source convention not supplied here.','Section 6 — Distances to fitted parameter sets',kind='source_passage')
add(32,'indicators',r'''To make the notations compact, we define $I_{k,t}=\mathbf1\{Z_t\in R_k(\gamma)\}$ for any candidate $\gamma=(\gamma_1^\top,\gamma_2^\top)^\top$ and $k=1,\cdots,4$. Let $X_{t,i}$ be the $i$-th element of $X_t$ and $\beta_{k,i}$ be the $i$-th element of $\beta_k$. It can be noted that the irregularity of $\mathbb M_T(\theta)$ in (3.2) is brought by the indicators $\{I_{k,t}\}$. If we define $\ell_{k,i,t}=I_{k,t}\beta_{k,i}$ for $i=1,\cdots,p$, then $\mathbb M_T(\theta)$ can be expressed as
\[
V_T(\ell)=\frac1T\sum_{t=1}^T\left(Y_t-\sum_{k=1}^4\sum_{i=1}^pX_{t,i}\ell_{k,i,t}\right)^2
\]
(4.1)
which is quadratic with respect to $\ell=\{\ell_{k,i,t}:k=1,\cdots,4;i=1,\cdots,p;t=1,\cdots,T\}$.''',[9],[2,4],[r'I_{k,t}=\mathbf1\{Z_t\in R_k(\gamma)\}',r'\ell_{k,i,t}=I_{k,t}\beta_{k,i}'],'Algebraic candidate-regime indicators and lifted coefficient products, defined for fixed supplied data. Further source sign variables and M bounds are preserved separately.','Section 4 — Lifted regression indicators and products',kind='source_passage')
add(33,'number of segments',r'''For the initial model with four regimes, define
\[
S_T(4)=\sum_{t=1}^T[Y_t-\sum_{k=1}^KX_t^\top\widehat\beta_k^{(4)}\mathbf1\{Z_t\in\widehat R_k^{(4)}\}]^2
\]
to be the sum of square residual (SSR) of the estimated four-regime model. For $K=4,3,2$, recursively define
\[
D_T^{(K)}(i,h)=\min_{\beta\in\mathcal B}\sum_{t=1}^T[Y_t-X_t^\top\beta\mathbf1\{Z_t\in\widehat R_i^{(K)}\cup\widehat R_h^{(K)}\}]^2-\sum_{t=1}^T[Y_t-\sum_{k=i,h}X_t^\top\widehat\beta_k^{(K)}\mathbf1\{Z_t\in\widehat R_k^{(K)}\}]^2
\]
to be the increment in the SSR after merging $\widehat R_i^{(K)}$ and $\widehat R_h^{(K)}$. Let $\mathcal A_K$ be the pair of indices for the adjacent segments of $\{\widehat R_k^{(K)}\}$. We merge the segments $\widehat R_{\widehat i}^{(K)}$ and $\widehat R_{\widehat h}^{(K)}$ if
\[
(\widehat i,\widehat h)=\arg\min_{(i,h)\in\mathcal A_K}D_T^{(K)}(i,h),
\]
(6.7)
followed by labeling the merged region and the remaining regions as $\{\widehat R_k^{(K-1)}\}_{k=1}^{K-1}$, and we denote the estimated regression coefficients to these $K-1$ regimes by $\{\widehat\beta_k^{(K-1)}\}_{k=1}^{K-1}$. Then, define the SSR of the $(K-1)$-segment submodel as
\[
S_T(K-1)=S_T(K)+D_T^{(K)}(\widehat i,\widehat h).
\]
After obtaining the $S_T(K)$ for $K=2,3,4$, we select the number of segments $\widehat K$ as
\[
\widehat K=\arg\min_{1\le K\le4}\{\log(S_T(K)/T)+(\lambda_T/T)K\}
\]
(6.8)
and output the estimated regimes and regression coefficients accordingly.''',[16],[2,3,5],[r'\widehat K',r'D_T^{(K)}(i,h)',r'S_T(K-1)=S_T(K)+D_T^{(K)}(\widehat i,\widehat h)'],'Full greedy adjacent-regime merging and penalized selection algorithm, including K=1 in the final minimum. Preserve the initial formula’s free K, the prose enumeration2,3,4, and the relabeling without a specified matching rule. The global model uses the final recursive merge despite the prose list omitting1.','Section 6 — Backward merging and model selection (6.7)–(6.8)',kind='source_passage')
add(34,'linear constraints',r'''Let $g_{j,t}=\mathbf1(Z_{j,t}^\top\gamma_j>0)$. We first express $g_{j,t}$ by linear constraints in $\gamma_j$, so as to link $I_{k,t}$ with $g_{j,t}$ via linear inequalities. Let $M_{j,t}=\max_{\gamma\in\Gamma_j}|Z_{j,t}^\top\gamma|$ which can be readily computed via linear programming. Then,
\[
(g_{j,t}-1)(M_{j,t}+\epsilon)<Z_{j,t}^\top\gamma_j\le g_{j,t}M_{j,t}
\]
(4.3)
hold by the definition of $g_{j,t}$, where $\epsilon>0$ is a small predetermined constant.''',[9],[3,32],[r'g_{j,t}=\mathbf1(Z_{j,t}^\top\gamma_j>0)',r'M_{j,t}=\max_{\gamma\in\Gamma_j}|Z_{j,t}^\top\gamma|'],'Sign encoding and data-dependent M bound as printed. The compact Gamma assumption alone does not justify linear-program computation; strict feasibility has to remain distinct from numerical solver approximations.','Section 4 — Hyperplane sign constraints (4.3)',kind='source_passage')
# The complete MIQP uses the explicitly defined M bound and binary sign encoding.
members['D16']['depends_on'].append('D34')

# Distinguish the empirical centroid from the limiting-process centroid: the
# bootstrap target law does not depend on the limit process merely by notation.
original=members['D15']['statement_original']
pre,post=original.split('For any set ',1)
generic,end=post.split('Let $',1)
add(35,'centroid','For any set '+generic.strip(),[7,8],[],[r'C(\mathcal A)'],'Original Lebesgue centroid functional. Its denominator must be positive and finite in the chosen dimension; no such domain convention is silently supplied.','Section 3.2 — Centroid functional')
m=members['D15'];m['statement_original']=r'$\widehat\gamma^c=C(\widehat{\mathcal G})$, where $\widehat{\mathcal G}$ is the set for LS estimators for $\gamma$.'
m['depends_on']=['D5','D35'];m['highlight_symbols']=[r'\widehat\gamma^c']
m['source_heading']=m['local_label']='Section 3.2 — Centroid of the LSE solution set'
x=next(x for x in interfaces if x['members'][0]['local_id']=='D15')
m['naming_context']=[dict(context_id='D15/name',text='Numerically, $\widehat\gamma^c$ can be approximated by the average of $N$ elements of $\widehat{\mathcal G}$ for a sufficiently large $N$.',evidence=[dict(page=8,location='Centroid discussion')]),dict(context_id='D15/centroid',text='the centroid of $\mathcal A$ is',evidence=[dict(page=8,location='Centroid functional')])]
x['source_keywords'][0]['context_id']='D15/centroid'
x['type_shape']=x['semantic_boundary']='Empirical boundary minimizer centroid, using the common centroid functional and LSE solution set. It is distinct from the limiting-process centroid.'
add(36,'centroid',pre.strip()+'\n'+r'Let $\gamma_D^c=C(\mathcal G_D)$',[7,8],[14,35],[r'\gamma_D^c',r'\mathcal G_D'],'Original minimizer set of D and its centroid; the limiting process supplies this object, not the empirical LSE solution set. Preserve the printed full-space domain and its unresolved volume/existence issue.','Section 3.2 — Centroid of the limiting minimizer set',kind='source_passage')

# Source-inspected rendering amendment; see the explicit saved review plan.
members['D20']['highlight_symbols'] = ['\\widetilde\\sigma^2(x,z)=\\widehat\\alpha', '\\left\\{\\widehat\\varepsilon_t^2-\\alpha-((X_t-x)^\\top,(Z_t-z)^\\top)\\eta\\right\\}^2']

def main():
    review=json.loads((REVIEW_ROOT/'inventory-review.json').read_text())
    assert review['status']=='complete' and review['source_checked']
    assert hashlib.sha256((ROOT/'theorem-inventory.json').read_bytes()).hexdigest()==review['inventory_sha256']
    for m in members.values():
        assert all(x in members for x in m['depends_on'])
        for x in m['highlight_symbols']:assert x in m['statement_original'] or any(x in t for t in STATEMENTS),(m['local_id'],x)
    (ROOT/'source-passages.json').write_text(json.dumps(dict(paper_id=PID,members=list(members.values())),indent=2,ensure_ascii=False)+'\n')
    (ROOT/'interface-extraction.json').write_text(json.dumps(dict(paper_id=PID,interfaces=interfaces),indent=2,ensure_ascii=False)+'\n')
if __name__=='__main__':main()
