"""Preserve source conventions, excluded supplementary imports and formula discrepancies."""
import json
from save_inventory import ROOT,PID,STATEMENTS

def main():
    aux=[]
    def add(n,s,pages,note,deps=()):aux.append(dict(local_id='A'+str(n),statement_original=s,evidence=[dict(page=p,location='Original main-text context A'+str(n)) for p in pages],scope_note=note,depends_on=list(deps)))
    add(1,r'''We use $\mathbf1(A)$ for the indicator function of an event $A$, $\|v\|=(\sum_{i=1}^dv_i^2)^{1/2}$ for the $L_2$-norm of vector $v=(v_1,\cdots,v_d)^\top$ and $\mathcal N(v_0;\delta)=\{v:\|v-v_0\|\le\delta\}$ for the $\delta$-neighborhood of $v$. Define $v_{-1}$ as the sub-vector of $v$ excluding its first element, i.e., $v_{-1}=(v_2,\cdots,v_d)^\top$. We use $|E|$ to denote the cardinality of a set $E$. For any two sets $E_1$ and $E_2$, we denote $E_1\mathbin{\triangle}E_2=(E_1\setminus E_2)\cup(E_2\setminus E_1)$ as their symmetric difference.''',[3],'Original ambient Euclidean norm, closed neighborhood, omitted-first-coordinate, cardinality and symmetric-difference conventions. The distance in Section6 uses the Euclidean subscript2, not a squared norm.')
    add(2,r'''For any candidate $\gamma_i$ of $\gamma_{i0}$, we normalize it by its first element $\gamma_{i,1}$, resulting in $\gamma_i=:(1,\widetilde\gamma_i)$ where $\widetilde\gamma_i$ is assumed to take values in a compact set. As noted in [22], an alternative normalization is $\|\gamma_i\|_2=1$. In this study, we employ the former as it has one less parameter.''',[4],'First-coordinate normalization is the actual convention. Nonzero first coordinate and possible orientation/sign relabeling are not spelled out; the unit-norm alternative is not substituted.',['D3'])
    add(3,r'''It is noted that for any two $\widehat\gamma,\widehat\gamma'\in\widehat{\mathcal G}$, the segmented regimes under the corresponding hyperplanes must be the same, as otherwise the estimated regression coefficients will be distinct. In addition, the set $\widehat{\mathcal G}$ is convex since for each $i=1$ or $2$, $Z_{i,t}^\top\widehat\gamma_i>0$ and $Z_{i,t}^\top\widehat\gamma_i'>0$ imply that $Z_{i,t}^\top\widetilde\gamma_i>0$ for all $\widetilde\gamma_i=\alpha\widehat\gamma_i+(1-\alpha)\widehat\gamma_i'$ with $\alpha\in[0,1]$.''',[4],'Source claims about common optimal partitions and convexity. These are not used as independent proven facts: arbitrary compact parameter spaces, ties and rank-deficient cells need additional qualifications.',['D2','D3','D5'])
    add(4,r'''Numerically, $\widehat\gamma^c$ can be approximated by the average of $N$ elements of $\widehat{\mathcal G}$ for a sufficiently large $N$.''',[8],'Numerical approximation statement only. Arbitrary or solver-generated elements need not sample a centroid consistently; the source does not specify their law or a rate for N.',['D5','D15'])
    add(5,r'''where $s_j^{(k)}\in\{-1,1\}$ is the sign of $z_j^\top\gamma_j$ for the points belonging in $R_k(\gamma)$, we can write $I_{k,t}=\prod_{j=1}^2\mathbf1(s_j^{(k)}Z_{j,t}^\top\gamma_j>0)$, which can be linked to $\{g_{j,t}\}_{j=1}^2$ via
\[
I_{k,t}=\prod_{j=1}^2\mathbf1\left(s_j^{(k)}Z_{j,t}^\top\gamma_j>0\right)=\prod_{j=1}^2\{s_j^{(k)}g_{j,t}+(1-s_j^{(k)})/2\},
\]
(4.4)''',[10],'Candidate-region sign constants used by the MIQP. The strict signed-product representation excludes zero-boundary observations, unlike the source nonpositive region definitions. The binary Boolean expression handles g=0 as nonpositive; the equality at zero is a source discrepancy.',['D2','D32','D34'])
    add(6,r'''However, it requires further investigation to understand the detailed mechanism regarding how the multiple elements of $\widehat{\mathcal G}$ are produced by the MIQP solver.''',[10],'Explicit source limitation on solver-generated minimizer sampling; it matters to finite-N centroid approximations in the bootstrap.',['D5','D15','D16','D23'])
    add(7,r'''Assumptions S2-S4 in the SM ([33]), which adapt Assumptions 3–4 to the degenerate model settings''',[15],'Required supplementary assumption reference in T6.1, inherited by T6.2. The original main text does not state those bodies; they remain unresolved external prerequisites, not fabricated definitions or copies of Assumptions3–4.')
    add(8,r'''As in the original LS problem, the LSEs for $\gamma_0$ based on each bootstrap resample are attained on a convex set $\widehat{\mathcal G}^*$. Therefore, in Step 2 we approximate the centroid of $\widehat{\mathcal G}^*$ by the average of $N$ elements in $\widehat{\mathcal G}^*$.''',[13],'Source rationale for the starred boundary estimate. This is an approximation, with no stated sampling/limit regime for N; it is not silently equated to an exact centroid.',['D5','D15','D23'])
    add(9,r'''It is noted that such a decaying rate is only required in deriving the limiting distribution of $\widehat\gamma$, which can be relaxed to the polynomial decay for Theorem 3.1 and Theorem 3.2.''',[5],'The surrounding prose mentions a possible weaker mixing assumption, but the printed theorems still cite Assumption1. Preserve their original geometric rate instead of replacing it by an unspecified polynomial condition.',['D6'])
    add(10,r'''$R_1$ $(+,+)$; $R_2$ $(-,+)$; $R_3$ $(-,-)\cup(+,-)$.''',[14],'Figure1(C) labels for the three-region intersecting model, transcribed in spatial region order. They conflict with the printed R2 clause in(6.2); record both as evidence without treating the figure as a corrected original formula.',['D27'])
    issues=[]
    def issue(i,pages,note):issues.append(dict(issue_id=i,evidence=[dict(page=p,location='Source scope or notation issue') for p in pages],note=note))
    issue('registered-source-scope',[1,24],'Registered source is arXiv2410.04384v1 marked6Oct2024,25pages. Main text ends after acknowledgements on24, before the supplementary-material notice at y395.594; evidence clipped390. The notice points to a separate supplement, whose bodies are excluded. Exactly seven actual Theorems are retained.')
    issue('supplementary-assumptions',[15,16],'T6.1 requires Assumption1 and supplementary S2–S4, described only as adaptations of Assumptions3–4. T6.2 inherits those assumptions. The supplement remains out of scope, so their precise content and dependency closure are unresolved. Neither theorem is dropped or treated as assumption-free; the original references and limits are explicit.')
    issue('mixing-and-filtration-notation',[4,5],'Assumption1 writes rho(t) with an outer supremum over s,t>=1, reusing the lag variable, and writes f andg as members of sigma-fields rather than specifying measurable finite-variance random variables. It calls F_(t-1) the filtration generated by data through index t including current covariates. Preserve these source conventions without rewriting the definition. Theorems3.1/3.2 retain the printed geometric assumption despite prose suggesting a polynomial relaxation.')
    issue('normalized-boundary-coordinates',[4,7,8],'Boundary first coordinates are fixed to1, so their estimation differences have zero first coordinates. D(v) is nevertheless declared on R^(d1+d2) and uses only v_-1,i. The source does not restrict the two redundant coordinates or specify intrinsic measure for centroid integration. Taking the written full-space domain literally leaves free directions and prevents the stated ordinary full-volume centroid construction.')
    issue('finite-sample-lse-uniqueness',[4],'The paper asserts strict convexity in beta, a unique beta minimizer, identical optimal partitions and a convex boundary-minimizer set. These assertions are not assured for arbitrary finite samples with empty/rank-deficient cells or tied partitions, and compact Gamma/B need not be convex. Preserve them as source assertions, not certified general properties. Compactness with discontinuous indicators also does not alone guarantee an attained minimum.')
    issue('sign-and-zero-boundaries',[3,9,10],'Region definitions assign equality to nonpositive sides. The later expression product 1(s_j*z_j^T gamma_j>0) omits equality even when s_j=-1, whereas its claimed binary expression uses g_j=0 for nonpositive values. The mismatch occurs exactly on candidate boundaries. The source MIQP constraints themselves retain their original strict and non-strict sides.')
    issue('miqp-domain-and-solvers',[4,9,10],'Gamma_i andB are only specified as compact, while the source calls the constraints linear/polyhedral and M_jt computable by linear programming. Additional polyhedral assumptions are not printed. Strict inequalities are not standard closed MIQP constraints; solver epsilon/tolerance substitutions are not part of Theorem4.1. Epsilon in(4.3)/(4.7) expands a negative bound and does not impose a positive margin on g=1.')
    issue('source-punctuation-and-indices',[3,4,5,6,7,14],'Retain the boundary-coefficient set’s i/j mismatch, missing comma between(2,1) and(3,4) inS(1), extra commas in Assumption3 andT3.1, missing indicator parentheses in covariance definitions and(6.2), and brace notation R2{gamma0}. Formula delimiters remain as printed where they can be represented directly in LaTeX; no change in mathematical meaning is asserted.')
    issue('conditional-null-set-versions',[6,7],'Assumptions4/5 condition on hyperplanes or q_i=0, typically probability-zero events. The source asks continuity and bounds for some conditional densities but does not fully specify common versions for every conditional moment or support point. Preserve the original conditional clauses and their almost-sure/pointwise qualifiers.')
    issue('nonclustering-threshold',[7],'Assumption5(i) quantifies one fixed positive delta3 and a constant bound on paired-neighborhood probabilities. The surrounding prose describes a smaller-order rare-event effect, but the printed condition has no delta→0 uniformity. Do not replace it by a stronger shrinking-threshold condition.')
    issue('signed-limit-arrivals',[7],'In(3.4), the indicator requires0<J while J=s^(k)_i times a positive exponential sum divided by a positive density. Negative-sign families therefore have no contribution in the printed expression. The paper describes a multivariate compound Poisson process covering boundary directions; a missing complementary orientation may be intended, but no term is invented or read from a supplementary proof.')
    issue('centroid-volume-and-sampling',[4,7,8,10,13],'The centroid integral needs positive finite volume in a specified dimension. Normalized parameter spaces can have zero ambient volume, and the limiting process domain has unremoved free directions. Averaging N arbitrary minimizers or solver outputs is not automatically an unbiased/consistent centroid approximation. The source acknowledges the solver sampling mechanism is unknown and does not state an N→infinity rate alongside B,T→infinity inT5.1.')
    issue('bootstrap-error-model-index',[11,12],'Equation5.1 prints beta_0 rather than beta_k0 inside the regime sum, even though beta_0 earlier denotes the stacked coefficients. The fitted-residual line similarly omits the t index onX and the k index on fitted beta. Preserve these expressions and their apparent dimension/index gaps; the actual resampling Step1 separately prints beta-hat_k correctly.')
    issue('smoothed-cdf-orientation',[12],'G_i is defined by integrating a density from minus infinity up to u, but F0-tilde uses(X_t-x)/h1 and(Z_t-z)/h2. For positive bandwidths this is decreasing in evaluation coordinates, unlike a usual CDF. Preserve the source expression and record that resampling from it as an ordinary distribution needs clarification; do not reverse the arguments silently.')
    issue('shared-variables-and-density-domain',[3,12],'The model allows shared covariates and definesZ as the union of variables inZ1/Z2. Later kernels treatZ as dimensiond1+d2 and demand an absolutely continuous joint law of(X,Z), which fails in redundant ambient coordinates when variables coincide. Assumption6 also combines compact support with a positive infimum over unqualified all(x,z); the intended support-relative domain is not explicitly supplied.')
    issue('variance-smoothing-regularity',[12],'Assumption6 bounds the true variance above and away from0 but does not print continuity/smoothness assumptions for that function, despite claiming uniform consistency of its local-linear estimate. Local-linear fitted variances can be nonpositive; no truncation or denominator convention is stated before standardized residuals are formed. These are source limitations, not extra hypotheses imposed by the census.')
    issue('bootstrap-notation-and-resampling',[12,13],'Step1 calls the covariate law F-tilde while the preceding definition isF0-tilde. The standardized empirical residual law G-hat is different from calligraphicG-hat for boundary minimizers. Resampling is independent even though original data are dependent; this is the stated model-based construction, not a block bootstrap. LT,B uses finite-N boundary averages while LT is written using the original centroid.')
    issue('degenerate-region-discrepancy',[14],'In family(a.2), the source uses z_i^T gamma_j,0, which may have incompatible dimensions when di!=dj, and its printed R2 is a subset ofR3 rather than a disjoint region. Figure1(C) labels R2 as(-,+), while the printed inequalities differ. Preserve both source representations and leave the intended correction unresolved.')
    issue('finite-set-symbol-reuse',[4,15],'Earlier G-hat is the set of all stacked boundary minimizers; Section6 reuses it for the finite set of two fitted boundary vectors. Point-to-set distance is Euclidean and unsquared. If d1!=d2, the finite set contains differently sized vectors, and the source does not state how invalid comparisons are omitted. The original L0=1/L0=2 cases are retained separately.')
    issue('selection-and-label-matching',[15,16],'The recursive algorithm defines an initial ST(4) with a free K in the inner sum, later lists ST(K) only forK=2,3,4 though the final minimum includes1, and freely relabels merged regions. The recurrence does reachK=1, but no matching permutation with true region labels is specified forT6.2’s per-k conclusion. The theorem inheritsK0<4 fromT6.1, even though surrounding text discusses selecting up to four regimes.')
    issue('probability-rate-notation',[6,15,16],'Regime error bounds use ordinaryO(1/T) although estimated regions are random; the source does not explicitly specify conditional versus integrated probability over a newZ and fitted data. T6.2 writes P{estimated-region triangle true-region} without Z membership. Preserve this implicit set-probability notation and the original O versusOp distinction.')
    bindings={
'T3.1':'Original four-regime model, normalized compact parameter space, LSE beta and arbitrary boundary minimizer inG-hat; explicit Assumptions1–3. Full theta consistency, retaining the source punctuation. No centroid or limiting-process requirement is imposed on the choice of minimizer.',
'T3.2':'Same model and LSEs, explicit Assumptions1–4, sqrtT rate for regression coefficients andT rate for any boundary minimizer. No centroid, covariance law or Assumption5 is imported merely to prove convergence rates.',
'T3.3':'Original model, Assumptions1–5, LSE regression components, original covarianceSigma_k, empirical boundary centroid and the centroid of the printed D-process minimizer set. Both convergence and stated asymptotic independence clauses are preserved. Coordinate/centroid and signed-arrival issues remain unresolved source details.',
'T4.1':'Fixed supplied data, compact normalized parameter spaces, original least-squares criterion/minimizers and complete MIQP(4.6)–(4.7), with coefficient bounds, M_jt and candidate sign constants. This algebraic equality does not explicitly assume the stochastic Assumptions1–6; no such import is invented.',
'T5.1':'Assumptions1–6 plus the Section5 heteroscedastic standardized-error refinement and original smoothed bootstrap construction. LT is the jointT/sqrtT estimator law; LT,B is the empirical law of B resamples using finite-N boundary averages. Rho is any weak-convergence-metrizing metric, distinct from the mixing coefficientrho(t). External limit-process formulas are not needed merely to define the empirical centroid.',
'T6.1':'One of the five degenerate model families summarized in6.6, K0<4 andL0<=2, Assumption1 and unresolved supplementaryS2–S4. Four-regime fitted coefficient/boundary finite sets and point-to-set distance, with separateL0=1/2 cases, and unions of fitted four-region cells for each true region. Original Assumptions2–4 are not substituted for their supplementary adaptations.',
'T6.2':'InheritsT6.1’s degenerate-model setup and its Assumption1 plus unresolvedS2–S4; does not inheritT6.1’s conclusions as assumptions. Adds diverging sublinear penaltylambda_T and the complete greedy merging/selection algorithm. Fitted and true labels need the unresolved matching convention. No automatic extension toK0=4 is made.'}
    refs=[]
    def ref(claim,target,kind,note):refs.append(dict(claim_id=PID+'/'+claim,target=target,reference_kind=kind,note=note))
    ref('T6.1','Supplementary Assumptions S2–S4','unresolved_external_assumption','Bodies are not in the inspected main text. Preserve the mandatory reference and its source description; no appendix reading or synthesized substitute.')
    ref('T6.2','Theorem6.1 — assumptions only','assumption_reference','Inherit its degenerate model andAssumption1 plus the same unresolved supplementaryS2–S4, not the asserted convergence conclusions.')
    ref('T6.2','Supplementary Assumptions S2–S4 viaT6.1','unresolved_external_assumption','The inherited external prerequisites remain explicitly unresolved.')
    ref('T4.1','MIQP(4.6)–(4.7) andLSE(3.2)','definition_reference','Theorem equates original empirical criterion values under the two optimizations. No mixing or distributional hypotheses are needed to state that equality.')
    ref('T5.1','Section5 model(5.1) and bootstrap Steps1–3','definition_reference','The bootstrap statement uses the independent standardized-error refinement and the specific smoothing/resampling/centroid approximation construction.')
    for n in ['T3.1','T3.2','T3.3','T4.1','T5.1']:ref(n,'Supplementary proof sections','proof_only','Proofs are deferred to the separate SM. No proof-only lemmas, alternative algorithms or stronger assumptions are imported.')
    data=dict(paper_id=PID,unranked_auxiliary_passages=aux,statement_local_bindings=bindings,source_claim_references=refs,source_issues=issues,unresolved_external_prerequisites=[dict(reference='Assumptions S2–S4 in the SM ([33])',required_by=[PID+'/T6.1',PID+'/T6.2'],status='not_inspected_outside_main_text_scope',source_evidence=[dict(page=15,location='Theorem6.1 explicit reference'),dict(page=16,location='Theorem6.2 assumption inheritance')])],ambient_prerequisites=['Euclidean vector/matrix operations, indicators, finite set operations and symmetric differences, compactness, parameter products, infima/argmin, conditional expectations and density versions.','Stationary time series, sigma-fields, correlation/mixing, martingale differences, ordinary and stochastic order, weak convergence, Gaussian laws and asymptotic independence.','Independent exponential variables, marked point-process constructions, intrinsic versus ambient integration for centroids, regular conditional distributions and density values on hyperplanes.','Kernel integration/smoothing, empirical distributions, local linear least squares, standardized residuals, joint estimator laws, weak-convergence metrics, greedy adjacency merging and penalized model selection. No library availability claim.'],validation_limits='Main-text source census only. Explicit supplementary assumptions remain unresolved and are not fabricated. Source formula discrepancies are preserved rather than silently corrected. Source validation does not certify theorem truth, algorithm implementability or bootstrap validity.')
    (ROOT/'ambient-prerequisites.json').write_text(json.dumps(data,indent=2,ensure_ascii=False)+'\n')
if __name__=='__main__':main()
