"""Preserve theorem binders, non-theorem context and unresolved source notation."""
import json
from save_inventory import ROOT,PID

def main():
    aux=[]
    def add(n,s,pages,note,deps=()):aux.append(dict(local_id='A'+str(n),statement_original=s,evidence=[dict(page=p,location='Original main-text context A'+str(n)) for p in pages],scope_note=note,depends_on=list(deps)))
    add(1,r'''Consider the following assumptions for a sequence $\{S_n\}_{n\in\mathbb N}$ such that $S_n\in\mathcal H_K^*$, for each $n\ge1$. Let $\xrightarrow{d}$ denote convergence in distribution for sequences of random variables.''',[10],'Standing binder of the arbitrary dual-valued sequence in Theorem4.1. It is not automatically the statistical empirical process and does not carry the CMR sampling hypotheses.',['D3','D4'])
    add(2,r'''Then, a GP $A\sim GP(m,K)$ is a stochastic process such that for any $n\in\mathbb N$ and $x_1,\ldots,x_n$ in $\mathcal X$, the random vector $(A(x_1),A(x_2),\ldots,A(x_n))$ is distributed as a Gaussian vector with mean $(m(x_1),m(x_2),\ldots,m(x_n))$ and covariance matrix with $ij$-th element $K(x_i,x_j)$, $i,j=1,\ldots,n$.''',[6],'Original motivating GP definition. The three theorem statements consume explicit Hilbert-space processes and empirical quadratic forms, so GP integration is not a separate theorem dependency merely because it motivates the paper.',['D1'])
    add(3,r'''where $\widetilde Z$ and $\widetilde X$ are independent copies of $Z$ and $X$, respectively,
and let $\Pi$ denote the orthogonal projection operator onto the orthocomplement of $g$ in $L_2(X)$, where $L_2(X)$ is the Hilbert space of square integrable measurable functions of $X$.''',[3],'Two distinct source excerpts: the independent-copy convention in(8), and the L2(X) meaning later on the page. Independent copies mean an independent replication of the joint observation; the statement does not assert independence of Z and X within an observation. The projection uses P_X, not the residual-weighted measure mu.',['D7','D9','D10'])
    add(4,r'''We consider the Neyman-orthogonal (infeasible) function-parametric process
\[
R_n(\Pi a)=\frac1{\sqrt n}\sum_{i=1}^n\Pi a(X_i)\varepsilon(Z_i,\theta_0),\qquad a\in\mathcal H_K,
\]
(20)
where $\Pi a(X_i)$ is defined in (13). This process is infeasible because $\Pi$ and $\theta_0$ are unknown.''',[11],'Proof route for Theorem4.3 through the true-parameter projected process, not an additional printed theorem or premise. Theorem4.1 is applied to it in the proof; this does not import AssumptionA into the definition of the applied statistic.',['D2','D7','D10'])
    add(5,r'''Define $\dot G:=E[\dot g'(X,\theta_0)\varepsilon(Z,\theta_0)]$.
Proposition 4.2. Under Assumption B,
\[
\|\widehat R_n(\cdot)-R_n(\Pi\cdot)+G(\cdot,\theta_0)\Gamma^{-1}\dot G\sqrt n(\widehat\theta-\theta_0)\|=o_P(1).
\]
(21)
As a corollary, under $H_0$, $\dot G=0$ and hence, $\|\widehat R_n(\cdot)-R_n(\Pi\cdot)\|=o_P(1)$. This result shows the local robustness under the null and the lack of robustness under the alternative when $\dot G\ne0$.''',[12],'Main-text proposition and explanation clarify the role of the null, but neither is an extra Theorem or a dependency of the process definition. Proposition4.2 is proof machinery for Theorem4.3. The non-null correction is relevant to the unresolved scope of the later bootstrap statement.',['D3','D7','D8','D10','D14','D18','D19'])
    add(6,r'''For justification of the bootstrap we use the concept of a.s. consistency, denoted by $\xrightarrow{d}$ a.s., see [21] or Chapter 2.9 in [55].''',[13],'The source cites rather than defines the precise conditional-distribution convergence criterion. Preserve the almost-sure qualifier and record the external-definition limit; this is not an ordinary pathwise limit.',['D21'])
    add(7,r'''We consider the local (Pitman) alternatives
\[
H_n(\delta):E[\varepsilon(Z,\theta_0)\mid X]=\frac{\delta(X)}{\sqrt n}\text{ a.s.}
\]
where $\delta(X)$ is a non-zero square integrable measurable function of $X$.
We add some more moment conditions to Assumption B.
Assumption B: (v) $E[\delta^2(X)/\sigma_\varepsilon^2(X)]<\infty$ and $E[K^\perp(X,X)\delta^2(X)]<\infty$.''',[13],'The local-power addition appears after Theorem4.4 and applies to Proposition4.5, not to the preceding Theorems4.3 and4.4. Local alternatives and B(v) are not imported into their statement graphs.',['D7','D11','D16'])
    add(8,r'''Let $K$ be a kernel on $\mathcal X$ with RKHS $\mathcal H_K$. Then, for any $n\in\mathbb N$, $x_1,\ldots,x_n\in\mathcal X$ and $c=(c_1,\ldots,c_n)'\in\mathbb R^n$,
\[
\sup_{a\in\mathcal B_K}\frac1n\sum_{i=1}^nc_ia(x_i)=\left\|\frac1n\sum_{i=1}^nc_iK(\cdot,x_i)\right\|_K=\sqrt{c'\mathbb Kc}.
\]''',[9],'Lemma3.4 is not an inventoried Theorem. Its final equality has a normalization mismatch when mathbb K is taken with Algorithm1’s entries K(x_i,x_j)/n. Preserve the source formula and flag the mismatch without altering the correctly scaled statistic(14) or theorem statements.',['D1','D2','D13'])
    add(9,r'''This section discusses the case where the conditional score $g(X,\theta_0)=E[s(Z,\theta_0)\mid X]$ is nonparametric.''',[14],'Section5 separately develops the nonparametric-score extension and AssumptionC. It contains no additional Theorem environment and is not silently inserted into the parametric-score assumptions of Theorems4.3/4.4.',['D9'])
    issues=[]
    def issue(i,pages,note):issues.append(dict(issue_id=i,evidence=[dict(page=p,location='Source scope or notation issue') for p in pages],note=note))
    issue('registered-version-and-scope',[1,20],'The registered source is the IMS manuscript AOS2401-003R2A0.pdf, marked Submitted to the Annals of Statistics. The source has no publication date on the inspected cover. The main-text discussion ends on shared page20 before the mathematical appendix; only the clipped main text is used.')
    issue('two-hilbert-space-spectra',[10,11,12],'Theorem4.1 uses the covariance operator on H_K, H_K-orthonormal eigenvectors and sqrt(mu_j). Theorem4.3 uses the Kperp integral operator on L2(mu), eigenvectors orthonormal there, and lambda_j multiplying a Kperp-RKHS inner product. Different normalization means the lambda_j coefficient must not be silently changed to sqrt(lambda_j). RKHS representatives for zero eigenvalues and projection membership are implicit in the source.')
    issue('bootstrap-null-scope',[12,13],'Theorem4.3 explicitly assumes H0; Theorem4.4 prints only AssumptionB while referring to the same R_infinity. Proposition4.2 shows an additional parameter-estimation term under alternatives. Preserve the bootstrap statement exactly and flag its intended non-null scope as unresolved; do not add H0 to the original or infer unconditional validity under arbitrary alternatives.')
    issue('bootstrap-almost-sure-strength',[12,13],'B(iv) requires only a root-n O_P estimator rate, whereas Theorem4.4 asserts almost-sure bootstrap consistency and cites the formal convergence concept externally. The main text does not supply a detailed conditional metric definition or additional pathwise estimator assumptions. This census records the stated strength and does not certify its proof or silently weaken a.s. to in probability.')
    issue('gram-matrix-scaling',[8,11],'Algorithm1 defines the raw mathbb K entries as K(X_i,X_j)/n. B(ii) then prints lambda_max(mathbb K)=O_P(n^−1), not O_P(1) and not the projected Gram matrix. Retain the exact condition; for standard fixed nonzero kernels this is substantially restrictive and should be checked before assuming the theorem applies to an example.')
    issue('lemma34-normalization',[8,9],'For the Algorithm1 Gram scaling, the squared norm of n^−1 sum_i c_i K(.,x_i) equals c-prime mathbb K c/n. Lemma3.4 instead prints sqrt(c-prime mathbb K c) for that norm. This mismatch is confined to the auxiliary original lemma passage; the empirical process uses1/sqrt(n), so the statistic norm identity(14) has the compatible scaling.')
    issue('matrix-valued-score-measure',[11,12],'The source defines sigma_s² as E[s*s-prime|X], which is a p-by-p matrix for p>1, then calls sigma_s² dF_X a measure and writes kappa_s<infinity without an explicit trace, norm or componentwise convention. Preserve the matrix-valued expression and leave its scalarization unresolved.')
    issue('projection-domain-and-inverses',[8,9,11,12],'Population Gamma is assumed nonsingular and empirical Gamma_n is asserted nonsingular for sufficiently large n. The source gives no convention for singular finite samples. Pi is initially an L2(P_X) projection, the empirical process is indexed by H_K, and the spectral expansion uses L2(mu); these three domains are distinct. No generalized inverse or universal RKHS/L2 isometry is inserted.')
    issue('boundary-and-neighborhood',[11,12],'Theta is compact and theta0 may be on its boundary, while Theta0 is introduced as a small neighborhood in R^p and differentiability is stated in Theta. The extension/relative-domain convention for derivatives and suprema near a boundary is implicit. Preserve the printed domains without strengthening to an interior parameter or a globally extended function.')
    issue('later-assumptions-and-proof-only-results',[11,12,13,14],'B(v) is introduced after Theorem4.4 for local-power Proposition4.5. Section5 separately treats estimated nonparametric conditional scores under AssumptionC. Neither is retroactively added to Theorems4.3/4.4. Proposition4.2 and the application of Theorem4.1 are proof steps, not new assumptions of the applied process definitions.')
    issue('sampling-and-residual-second-moment',[1,3,9,12],'W_i are iid joint observations, without independence of Z_i and X_i. The weighted measure uses E[epsilon²|X], which equals conditional variance only under conditional mean zero. The multipliers are independent of all original observations, centered, unit variance and bounded; Gaussian multipliers do not satisfy that printed bounded-support assumption.')
    bindings={
      'T4.1':dict(sequence='Arbitrary random S_n in the separable bounded-functional space H_K*, not implicitly a CMR empirical process.',assumptions='AssumptionA(i)–(iii), preserving covariance-form positivity, basis summability and the order lim_J limsup_n.',limit='S_infinity from the covariance operator T_sigma, sqrt(mu_j), H_K-orthonormal basis and iid standard normals.',convergence='Hoffmann-Jorgensen weak convergence in H_K* with its operator norm and Borel sigma field.',objects=['D3','D4','D6']),
      'T4.3':dict(sampling='Standing iid scalar moment-function model; fitted theta and conditional scores.',assumptions='Explicit AssumptionB(i)–(iv) and H0. No B(v), AssumptionC or AssumptionA added as statement premises.',objects=['D3','D8','D10','D14','D15','D17','D19'],local_binders='R_infinity(a) is defined inline by the printed lambda_j<Kperp-inner-product> series; a ranges over H_K and U_j are iid standard normals under page11 convention. That formula is separately archived as D22 for its reuse by Theorem4.4.',conclusions='Dual weak convergence and the n*Qhat quadratic statistic limit sum_j lambda_j U_j². Preserve the factor n and L2(mu) eigenbasis.'),
      'T4.4':dict(assumptions='AssumptionB(i)–(iv) only in the printed statement; bounded iid centered unit-variance bootstrap multipliers independent of data are standing Section4.3 conditions.',objects=['D3','D19','D20','D21','D22'],limit='R_infinity is a definition reference to the inline formula in Theorem4.3, not an imported H0 premise or theorem-proof invocation.',convergence='Almost-sure conditional bootstrap distributional convergence of the scalar squared operator norm. Formal external convergence definition and non-null scope remain explicitly noted.',bootstrap='Hold fitted theta, residuals and score projection fixed; resample V_i only.')}
    refs=[dict(claim_id=PID+'/T4.1',reference='Assumption A',reference_kind='assumption_reference',resolution='D4 contains all three parts; S_n binder and weak convergence convention are A1 and D3.'),dict(claim_id=PID+'/T4.1',reference='S_infinity and T_sigma',reference_kind='definition_reference',resolution='D5,D6 preserve the H_K covariance spectrum and Gaussian series.'),dict(claim_id=PID+'/T4.3',reference='Assumption B and H0',reference_kind='assumption_reference',resolution='D19 and D8; B(i)–(iv) only, with all underlying quantities resolved locally.'),dict(claim_id=PID+'/T4.3',reference='Proposition4.2 and application of Theorem4.1',reference_kind='proof_only',resolution='A4,A5 preserve the infeasible comparison process and non-null correction. No edge to D4 or D6 is imported into the applied theorem.'),dict(claim_id=PID+'/T4.3',reference='Spectral expansion and Theorem3.1 in [34]',reference_kind='definition_reference',resolution='D17 preserves the stated L2(mu) spectral quantities. The external result is credited for the expansion; no appendix or external proof is read.'),dict(claim_id=PID+'/T4.4',reference='Assumption B',reference_kind='assumption_reference',resolution='D19 contains the four parts that precede the theorem. The later local-power part(v) is excluded.'),dict(claim_id=PID+'/T4.4',reference='R_infinity in Theorem4.3',reference_kind='definition_reference',resolution='D22 reuses only the explicitly defined limit functional. It does not inherit H0 by a theorem-to-theorem assumption edge.'),dict(claim_id=PID+'/T4.4',reference='[21] or Chapter2.9 in [55]',reference_kind='external_definition_reference',resolution='D21 preserves the source’s name and notation for a.s. bootstrap consistency; its precise external definition is not reproduced locally.')]
    data=dict(paper_id=PID,unranked_auxiliary_passages=aux,source_issues=issues,statement_local_bindings=bindings,source_claim_references=refs,ambient_conventions=['Real Euclidean spaces, conditional expectations, matrix transpose/inverse, Gaussian vectors, orthonormal bases, Hilbert norms and stochastic-order notation are ambient; no mathlib verdict is made.','U_j are iid standard normals under the page11 standing convention. Their appearance in Theorem4.3/4.4 does not require the abstract S_infinity construction or AssumptionA.','Theta-hat is a supplied estimator, with its rate imposed separately by B(iv). The base construction evaluates g(X_i,theta-hat); nonparametric g-hat is a later extension.','All source excerpts are main-text only; assumptions, definitions and proof-only propositions retain their distinct source identities. Source and schema checks do not certify mathematical proofs.'])
    (ROOT/'ambient-prerequisites.json').write_text(json.dumps(data,indent=2,ensure_ascii=False)+'\n')
if __name__=='__main__':main()
