"""Reproduce source-faithful definitions and conditions; preserve distinct design cases."""
import json
from save_inventory import ROOT,PID,STATEMENTS
interfaces=[];members={}
def add(n,term,s,pages,deps,symbols,boundary,heading,kind='definition',context=None,context_page=None,phrases=None):
    lid=f'D{n}'
    m=dict(paper_id=PID,local_id=lid,local_label=heading,source_heading=heading,source_kind=kind,statement_original=s,relation='exact',depends_on=[f'D{i}' for i in deps],evidence=[dict(page=p,location=heading) for p in pages],highlight_symbols=symbols,highlight_phrases=phrases or [])
    kw=dict(paper_id=PID,local_id=lid,source_text=term,label=term[0].upper()+term[1:],kind='term')
    if term not in s:
        assert context and term in context,(lid,term)
        m['naming_context']=[dict(context_id=lid+'/name',text=context,evidence=[dict(page=context_page or pages[0],location='Original naming context')])];kw['context_id']=lid+'/name'
    members[lid]=m
    interfaces.append(dict(interface_id=PID+'/'+lid,rank_group='all',name=kw['label'],lean_role='definition',type_shape=boundary,semantic_boundary=boundary,members=[m],source_keywords=[kw],central_claim_uses=[],dependencies=[],theorem_explanations={}))
add(1,'sampling design',r'''Suppose that $\mathcal P=\{1,\ldots,N\}$ is a finite population of size $N$, and a sample $s$ of size $n$ $(<N)$ is a subset of $\mathcal P$ having size $n$. Further, suppose that $\mathcal S$ is the collection of all subsets of $\mathcal P$ having size $n$. Then, a sampling design $P(s)$ is a probability distribution on $\mathcal S$ such that $0\le P(s)\le1$ for all $s\in\mathcal S$ and $\sum_{s\in\mathcal S}P(s)=1$.''',[5],[],[r'P(s)',r'\mathcal S'],'Fixed-size probability law on subsets. Inclusion probability pi_i is specified in the same section; SRSWOR is the named simple random sampling without replacement specialization.','Section 2 — Sampling design')
add(2,'finite population distribution function',r'''Let $F_{y,N}(t)=\sum_{i=1}^N1_{[Y_i\le t]}/N$ be the finite population distribution function of $y$ for $t\in\mathbb R$. Then, the finite population $p$th quantile of $y$ is defined as $Q_{y,N}(p)=\inf\{t\in\mathbb R:F_{y,N}(t)\ge p\}$ for $0<p<1$.''',[5],[1],[r'F_{y,N}(t)',r'Q_{y,N}(p)'],'Finite-population generalized inverse, not a superpopulation quantile. The x analogue uses the known auxiliary values.','Section 2 — Finite population quantile')
add(3,'sample quantile',r'''To eliminate these problems, we consider $\widehat F_y(t)=\sum_{i\in s}d(i,s)1_{[Y_i\le t]}/\sum_{i\in s}d(i,s)$ (see Conti and Marella (2015), Kuk (1988) and Wang and Opsomer (2011)) as an estimator of $F_{y,N}(t)$. Based on $\widehat F_y(t)$, the sample $p$th quantile of $y$ is defined as
\[
\widehat Q_y(p)=\inf\{t\in\mathbb R:\widehat F_y(t)\ge p\}.
\]
(1)''',[6],[2],[r'\widehat F_y(t)',r'\widehat Q_y(p)'],'Normalized weighted distribution and inverse. Weights are chosen per theorem: 1/(N pi_i) or A_i/(N X_i). No sampling design assumption is built into the generic definition.','Section 2 — Sample quantile (1)',context=r'''The weak convergence of the quantile process constructed based on the sample quantile for $d(i,s)=(N\pi_i)^{-1}$ was considered earlier in Conti and Marella (2015) under a high entropy sampling design.''',context_page=10)
EST_CONTEXT=r'''Suppose that $Q_{x,N}(p)$ and $\widehat Q_x(p)$ are the population and the sample $p$th quantiles of $x$, respectively. Then, the ratio, the difference and the regression estimators of $Q_{y,N}(p)$ are defined as'''
add(4,'ratio',r'''\[\widehat Q_{y,RA}(p)=(\widehat Q_y(p)/\widehat Q_x(p))Q_{x,N}(p).\]''',[6],[2,3],[r'\widehat Q_{y,RA}(p)'],'First row of (2), with the shared binder retained as naming context. Division is by the sample auxiliary quantile.','Section 2 — Ratio estimator (2)',context=EST_CONTEXT)
add(5,'difference',r'''\[\widehat Q_{y,DI}(p)=\widehat Q_y(p)+\left(\sum_{i\in s}d(i,s)Y_i\Big/\sum_{i\in s}d(i,s)X_i\right)(Q_{x,N}(p)-\widehat Q_x(p)).\]''',[6],[2,3],[r'\widehat Q_{y,DI}(p)'],'Second row of (2); coefficient is a ratio of weighted totals, not the regression coefficient.','Section 2 — Difference estimator (2)',context=EST_CONTEXT)
add(6,'regression estimators',r'''\[\widehat Q_{y,REG}(p)=\widehat Q_y(p)+\widehat\beta(Q_{x,N}(p)-\widehat Q_x(p)),\]
respectively, where $\widehat\beta=\sum_{i\in s}d(i,s)X_iY_i/\sum_{i\in s}d(i,s)X_i^2$.''',[6],[2,3],[r'\widehat Q_{y,REG}(p)',r'\widehat\beta'],'Third row of (2), including the uncentered weighted slope. Do not replace it by centered least squares or identify it with the separately cited GREG mean estimator.','Section 2 — Regression estimator (2)',context=EST_CONTEXT)
add(7,'probability measure',r'''In such cases, a sampling design can be expressed as a function $P(s,\omega)$ defined on $\mathcal S\times\Omega$ so that for each $s\in\mathcal S$, $P(s,\omega)$ is a random variable on $\Omega$, and for each $\omega\in\Omega$, $P(s,\omega)$ is a probability distribution on $\mathcal S$. If a sampling design is independent of $X_1,\ldots,X_N$ (eg., SRSWOR), then, for each $s\in\mathcal S$, the corresponding $P(s,\omega)$ is a degenerate random variable on $\Omega$. Suppose that $\mathcal A$ is the power set of $\mathcal S$. Then, we consider the probability measure $P^*(B\times E)=\int_E\sum_{s\in B}P(s,\omega)dP(\omega)$ (see Boistard et al. (2017a) and Han and Wellner (2021)) defined on the product space $(\mathcal S\times\Omega,\mathcal A\times\mathcal F)$, where $B\in\mathcal A$, $E\in\mathcal F$ and $B\times E$ is a cylinder subset of $\mathcal S\times\Omega$. We denote expectations of random quantities with respect to $P(s,\omega)$, $P$ and $P^*$ by $E$, $E_P$ and $E_{P^*}$, respectively.''',[7],[1],[r'P^*',r'P(s,\omega)'],'Joint design/superpopulation measure. The single-stage iid model is archived separately; the cluster model replaces global identical distribution by within-stratum iid and across-stratum independence.','Section 3 — Joint probability measure')
add(8,'left continuous functions',r'''Now, suppose that for any $0<\alpha<\beta<1$, $D[\alpha,\beta]$ is the space of all left continuous functions on $[\alpha,\beta]$ having right hand limits at each point, and $\mathcal D$ is the $\sigma$-field on $D[\alpha,\beta]$ generated by the open balls (ball $\sigma$-field) with respect to the sup norm metric. Note that $\mathcal D$ coincides with the Borel $\sigma$-field on $D[\alpha,\beta]$ with respect to the Skorohod metric (cf. Billingsley (2013) and Shorack and Wellner (2009)).''',[6,7],[],[r'D[\alpha,\beta]',r'\mathcal D'],'Left-continuous paths with right limits, ball sigma-field, supremum-norm weak convergence. Not the right-continuous empirical-process space tilde-D used in proofs.','Section 2 — Quantile-process path space')
add(9,'high entropy sampling design',r'''The sampling design $P(s,\omega)$ is called the high entropy sampling design (cf. Berger (1998), Boistard et al. (2017a), Cardot et al. (2014), Conti (2014), etc.) if
\[
D(P\|R)=\sum_{s\in\mathcal S}P(s,\omega)\log(P(s,\omega)/R(s,\omega))\to0\text{ as }\nu\to\infty\text{ a.s. }[P]
\]
(3)
for some rejective sampling design $R(s,\omega)$ (see Hájek (1964)).''',[8],[1,7],[r'D(P\|R)'],'Relative entropy tends to zero almost surely for some rejective design. The source does not give its construction here or explicitly require matching inclusion probabilities; leave that unresolved.','Section 3 — High entropy design (3)')
add(10,'population and sample sizes',r'''Assumption 1. $n/N\to\lambda$ as $\nu\to\infty$, where $0<\lambda<1$.''',[8],[],[r'n/N\to\lambda'],'Nonvanishing, nonunit limiting sampling fraction. T6.1 and T6.2 additionally restrict lambda; those restrictions remain theorem-local.','Assumption 1',kind='assumption',context=r'''We define our asymptotic framework as follows. Let $\{\mathcal P_\nu\}$ be a sequence of populations with $N_\nu,n_\nu\to\infty$ as $\nu\to\infty$ (see Boistard et al. (2017a), Conti and Marella (2015), Wang and Opsomer (2011), etc.), where $N_\nu$ and $n_\nu$ are, respectively, the population and sample sizes corresponding to the $\nu$th population.''',context_page=7)
add(11,'inclusion probabilities',r'''Suppose that $F_y$ and $F_x$ are superpopulation distribution functions of $y$ and $x$, respectively. Further, suppose that $Q_y(p)=\inf\{t\in\mathbb R:F_y(t)\ge p\}$ and $Q_x(p)=\inf\{t\in\mathbb R:F_x(t)\ge p\}$ are superpopulation $p$th quantiles of $y$ and $x$, respectively, and $\mathbf V_i=\mathbf G_i-\sum_{i=1}^N\mathbf G_i/N$ for $i=1,\ldots,N$, where
\[
\mathbf G_i=(1_{[Y_i\le Q_y(p_1)]},\ldots,1_{[Y_i\le Q_y(p_k)]},1_{[X_i\le Q_x(p_1)]}\ldots,1_{[X_i\le Q_x(p_k)]})
\]
for $p_1,\ldots,p_k\in(0,1)$ and $k\ge1$. Moreover, let $\mathbf T=\sum_{i=1}^N\mathbf V_i(1-\pi_i)/\sum_{i=1}^N\pi_i(1-\pi_i)$, where $\{\pi_i\}_{i=1}^N$ denote inclusion probabilities.

Assumption 2. The inclusion probabilities $\{\pi_i\}_{i=1}^N$ are such that the following hold.
(i) Given any $k\ge1$ and $p_1,\ldots,p_k\in(0,1)$, $(n/N^2)\sum_{i=1}^N(\mathbf V_i-\mathbf T\pi_i)^T(\mathbf V_i-\mathbf T\pi_i)(\pi_i^{-1}-1)\to\mathbf\Gamma$ as $\nu\to\infty$ a.s. $[P]$ for some positive definite (p.d.) matrix $\mathbf\Gamma$.
(ii) There exist constants $K_1,K_2>0$ such that for all $i=1,\ldots,N$ and $\nu\ge1$, $K_1\le N\pi_i/n\le K_2$ a.s. $[P]$.''',[8],[1],[r'\mathbf V_i',r'\mathbf\Gamma'], 'Covariance limit and inclusion-probability bounds, with their complete defining vector context. The unrestricted repeated quantile indices can make positive definiteness impossible; do not silently add distinctness.','Assumption 2 and its defining context',kind='assumption',phrases=['Assumption 2'])
add(12,'Superpopulation distribution functions',r'''Suppose that $\operatorname{supp}(F)=(a_1,a_2)$ is the support (see Conti and Marella (2015)) of any distribution function $F$, where $a_1=\sup\{t\in\mathbb R:F(t)=0\}$ and $a_2=\inf\{t\in\mathbb R:F(t)=1\}$. Note that $-\infty\le a_1<a_2\le\infty$.

Assumption 3. Superpopulation distribution functions $F_y$ of $y$ and $F_x$ of $x$ are continuous and are differentiable with positive continuous derivatives $f_y$ and $f_x$ on $\operatorname{supp}(F_y)\subseteq(-\infty,\infty)$ and $\operatorname{supp}(F_x)\subseteq(0,\infty)$, respectively.''',[8,9],[],[r'\operatorname{supp}(F)',r'f_y',r'f_x'],'Source open-interval support convention and positive continuous densities. Keep separate from finite empirical CDFs and from the stratified regularity conditions.','Assumption 3 and support convention',kind='assumption',phrases=['Assumption 3'])
add(13,'RHC sampling design',r'''In RHC sampling design (see Chaudhuri et al. (2006) and Rao et al. (1962)), $\mathcal P$ is first divided randomly into $n$ disjoint groups of sizes $N_1\cdots,N_n$, respectively, by taking a sample of $N_1$ units from $N$ units with SRSWOR, a sample of $N_2$ units from $N-N_1$ units with SRSWOR and so on. Then, one unit is selected in the sample from each of these groups independently with probability proportional to the size variable $x$.

Let us also assume that $\{N_r\}_{r=1}^n$ are as follows (see Rao et al. (1962)).
\[
N_r=\begin{cases}N/n,&\text{for }r=1,\cdots,n,\text{ when }N/n\text{ is an integer},\\
\lfloor N/n\rfloor,&\text{for }r=1,\cdots,k,\text{ and}\\
\lfloor N/n\rfloor+1,&\text{for }r=k+1,\cdots,n,\text{ when }N/n\text{ is not an integer},\end{cases}
\]
(6)
where $k$ is such that $\sum_{r=1}^nN_r=N$. Here, $\lfloor N/n\rfloor$ is the integer part of $N/n$.''',[11,12],[1],[r'N_r',r'\lfloor N/n\rfloor'],'Rao–Hartley–Cochran random grouping followed by within-group PPS. Group sizes (6) are an additional condition explicitly retained, not a universal property of every RHC design. A_i is the selected group auxiliary total.','Section 3 — RHC sampling and grouping (6)',kind='source_passage')
add(14,'size variable',r'''Assumption 4. There exists a constant $K$ such that $\max_{1\le i\le N}X_i/\min_{1\le i\le N}X_i\le K$ a.s. $[P]$.''',[11],[],[r'\max_{1\le i\le N}X_i/\min_{1\le i\le N}X_i'],'Uniform maximum/minimum ratio condition, not merely a finite second moment or an upper bound.','Assumption 4',kind='assumption',context=r'''Then, one unit is selected in the sample from each of these groups independently with probability proportional to the size variable $x$.''',phrases=['Assumption 4'])
add(15,'support of the joint distribution',r'''Assumption 5. The support of the joint distribution of $(Y_i,X_i)$ is not a subset of a straight line in $\mathbb R^2$.''',[11,12],[],[], 'Noncollinearity of the joint distribution support; no density or independence between X and Y is added.','Assumption 5',kind='assumption',phrases=['Assumption 5','straight line'])
add(16,'stratified multistage cluster sampling design with SRSWOR',r'''Suppose that the finite population $\mathcal P$ is divided into $H$ strata or subpopulations, where stratum $h$ consists of $M_h$ clusters for $h=1,\ldots,H$. Further, the $j$th cluster in stratum $h$ consists of $N_{hj}$ units for $j=1,\ldots,M_h$. For any given $h=1,\ldots,H$, $j=1,\ldots,M_h$ and $l=1,\ldots,N_{hj}$, we assume that the $l$th unit from cluster $j$ in stratum $h$ is the $i$th unit in the population $\mathcal P$, where $i=\sum_{h'=1}^h\sum_{j'=1}^{M_{h'}}N_{h'j'}-\sum_{j'=j}^{M_h}N_{hj'}+l$. In stratified multistage cluster sampling design with SRSWOR, first a sample $s_h$ of $m_h$ $(<M_h)$ clusters is selected from stratum $h$ under SRSWOR for each $h$. Then, a sample $s_{hj}$ of $r_h$ $(<N_{hj})$ units is selected from $j$th cluster in stratum $h$ if it is selected in the sample of clusters $s_h$ in the first stage for $h=1,\ldots,H$. Thus the resulting sample is $s=\cup_{1\le h\le H,j\in s_h}s_{hj}$. The samplings in two stages are done independently across the strata and the clusters. Under the above sampling design, the inclusion probability of the $i$th population unit is $\pi_i=m_hr_h/M_hN_{hj}$ if it belongs to the $j$th cluster of stratum $h$.''',[13],[1],[r'\pi_i=m_hr_h/M_hN_{hj}',r's_{hj}'],'Two-stage SRSWOR within strata, with independent draws across strata/clusters and design weights M_h N_hj/(N m_h r_h). The stratum-specific superpopulation model is archived in ambient prerequisites. Do not impose global iid.','Section 4 — Stratified multistage cluster sampling')
add(17,'number of clusters',r'''Assumption 6. $\sum_{\nu=1}^\infty\exp(-KM_h)<\infty$, $0<\underline{\lim}_{\nu\to\infty}m_h/M_h\le\overline{\lim}_{\nu\to\infty}m_h/M_h<1$, $\lim_{\nu\to\infty}n_h/n=\lambda_h>0$, $\lim_{\nu\to\infty}N_h/N=\Lambda_h>0$ and $0<\underline{\lim}_{\nu\to\infty}\min_{1\le j\le M_h}r_h/N_{hj}\le\overline{\lim}_{\nu\to\infty}\max_{1\le j\le M_h}r_h/N_{hj}<1$ for any $h=1,\ldots,H$ and $K>0$, and $\max_{1\le h\le H}\sum_{j=1}^{M_h}N_{hj}^4/M_h=O(1)$ and $\max_{1\le h\le H}\sum_{j=1}^{M_h}(N_{hj}-N_h/M_h)^2/M_h\to0$ as $\nu\to\infty$.''',[14],[16],[r'\lambda_h',r'\Lambda_h'],'Fixed-H design growth conditions, preserving liminf/limsup, fourth powers, stratum proportions and vanishing cluster-size variation. N_h=sum_j N_hj and n_h=m_h r_h.','Assumption 6',kind='assumption',context=r'''The condition $\sum_{\nu=1}^\infty\exp(-KM_h)<\infty$ for any $h=1,\ldots,H$ and $K>0$ in Assumption 6 holds, when the number of clusters in each stratum is a strictly increasing function of $\nu$.''')
add(18,'support of the joint distribution',r'''Assumption 7. For any $h=1,\ldots,H$, the support of the joint distribution of $(Y'_{hjl},X'_{hjl})$ is not a subset of a straight line in $\mathbb R^2$, and $E_P\|\mathbf W'_{hjl}\|^2<\infty$, where $\mathbf W'_{hjl}=(X'_{hjl},Y'_{hjl},X'_{hjl}Y'_{hjl},(X'_{hjl})^2)$.''',[14],[16],[r"\mathbf W'_{hjl}"],'Per-stratum noncollinearity and second moment of a four-coordinate vector. Not equivalent to Assumption 5 alone.','Assumption 7',kind='assumption',phrases=['Assumption 7'])
add(19,'positive continuous derivatives',r'''Assumption 8. $\operatorname{supp}(F_{y,h})=C_y$ and $\operatorname{supp}(F_{x,h})=C_x$ for any $h=1,\ldots,H$ and some open intervals $C_y\subseteq(-\infty,\infty)$ and $C_x\subseteq(0,\infty)$. Moreover, $F_{y,h}$ and $F_{x,h}$ are continuous on $\mathbb R$ and are differentiable with positive continuous derivatives $f_{y,h}$ and $f_{x,h}$ on $C_y$ and $C_x$, respectively, for any $h=1,\ldots,H$ and $\nu\ge1$.''',[14],[16],[r'f_{y,h}',r'f_{x,h}'],'Common open supports and stratum-specific smooth positive densities, for every h and nu. Does not require identical distributions across strata.','Assumption 8',kind='assumption',phrases=['Assumption 8'])
add(20,'cluster sizes',r'''Assumption 9. $\sum_{\nu=1}^\infty\exp(-KH)<\infty$ for any $K>0$, and $\max_{1\le h\le H,1\le j\le M_h}nM_hN_{hj}/m_hN=O(1)$, $\sum_{h=1}^HM_h^4/H=O(1)$ and $\max_{1\le h\le H}\sum_{j=1}^{M_h}(N_{hj}-N_h/M_h)^2/M_h\to0$ as $\nu\to\infty$.''',[15],[16],[r'\sum_{h=1}^HM_h^4/H'],'Growing-H replacement for Assumption 6; no fixed-H positive stratum-limit proportions imported.','Assumption 9',kind='assumption',context='This assumption and Assumption 1 imply that cluster sizes in any stratum cannot be arbitrarily large.',context_page=16,phrases=['Assumption 9'])
add(21,'quantile functions',r'''Next, suppose that $F_{y,H}(t)=\sum_{h=1}^H(N_h/N)F_{y,h}(t)$ and $F_{x,H}(t)=\sum_{h=1}^H(N_h/N)F_{x,h}(t)$, and $Q_{y,H}$ and $Q_{x,H}$ are quantile functions corresponding to $F_{y,H}$ and $F_{x,H}$, respectively. Let
\[
\mathbf G'_{hjl}=(1_{[Y'_{hjl}\le Q_{y,H}(p_1)]},\ldots,1_{[Y'_{hjl}\le Q_{y,H}(p_k)]},1_{[X'_{hjl}\le Q_{x,H}(p_1)]},\ldots,1_{[X'_{hjl}\le Q_{x,H}(p_k)]})
\]
for any $k\ge1$ and $p_1,\ldots,p_k\in(0,1)$, and $\mathbf\Gamma_h=E_P(\mathbf G'_{hjl}-E_P(\mathbf G'_{hjl}))^T(\mathbf G'_{hjl}-E_P(\mathbf G'_{hjl}))$.

Further, suppose that $f_{y,H}(t)=dF_{y,H}/dt$ and $f_{x,H}(t)=dF_{x,H}/dt$, and consider the following assumptions.''',[15],[16],[r'Q_{y,H}',r'\mathbf\Gamma_h',r'f_{y,H}'],'Population-size-weighted mixture CDFs, their inverses and densities, and covariance of centered stratum indicator vectors. These are not empirical CDFs.','Section 4 — Mixture quantiles and indicator covariance')
add(22,'positive definite matrices',r'''Assumption 10. Given any $k\ge1$ and $p_1,\ldots,p_k\in(0,1)$, $\sum_{h=1}^HN_h(N_h-n_h)\mathbf\Gamma_h/n_hN\to\mathbf\Gamma_1$ and $\sum_{h=1}^HN_h\mathbf\Gamma_h/N\to\mathbf\Gamma_2$ as $\nu\to\infty$ for some positive definite matrices $\mathbf\Gamma_1$ and $\mathbf\Gamma_2$. Moreover, $\sum_{h=1}^H\sum_{j=1}^{M_h}\sum_{l=1}^{N_{hj}}\mathbf W'_{hjl}/N\to\mathbf\Theta=(\Theta_1,\ldots,\Theta_4)$ and $\sum_{h=1}^H\sum_{j=1}^{M_h}\sum_{l=1}^{N_{hj}}\|\mathbf W'_{hjl}\|^2/N=O(1)$ a.s. $[P]$ as $\nu\to\infty$, where $\Theta_1>0$.''',[15],[16,21],[r'\mathbf\Gamma_1',r'\mathbf\Theta'],'Growing-H covariance limits and empirical moment-vector limits. W-prime is the vector defined in Assumption 7, but this does not import Assumption 7 noncollinearity/finite-expectation hypothesis.','Assumption 10',kind='assumption',phrases=['Assumption 10'])
add(23,'distribution function',r'''Assumption 11. $\operatorname{supp}(F_{y,h})=C_y$ and $\operatorname{supp}(F_{x,h})=C_x$ for any $h=1,\ldots,H$ and some open intervals $C_y\subseteq(-\infty,\infty)$ and $C_x\subseteq(0,\infty)$. Further, there exists a distribution function $\widetilde F_y$ with $\operatorname{supp}(\widetilde F_y)=C_y$ and positive continuous derivative $\widetilde f_y$ such that $F_{y,H}(t)\to\widetilde F_y(t)$ for any $t\in\mathbb R$ and $\sup_{C_y}|f_{y,H}(t)-\widetilde f_y(t)|\to0$ as $\nu\to\infty$. There also exists a distribution function $\widetilde F_x$ with $\operatorname{supp}(\widetilde F_x)=C_x$ and positive continuous derivative $\widetilde f_x$ such that $F_{x,H}(t)\to\widetilde F_x(t)$ for any $t\in\mathbb R$ and $\sup_{C_x}|f_{x,H}(t)-\widetilde f_x(t)|\to0$ as $\nu\to\infty$.''',[15,16],[21],[r'\widetilde F_y',r'\widetilde f_x'],'Growing-H limiting mixture CDFs with pointwise CDF convergence and uniform density convergence on common open supports. Distinct from within-stratum Assumption 8.','Assumption 11',kind='assumption',phrases=['Assumption 11'])
add(24,'Expressions',r'''Table 1: Expressions of $\zeta_i(p)$'s appearing in (5) and (7) for different $G(p)$'s in the cases of high entropy and RHC sampling designs
\[
\begin{array}{c|l}
G(p)&\zeta_i(p)\\
\widehat Q_y(p)&1_{[Y_i\le Q_y(p)]}/f_y(Q_y(p))\\
\widehat Q_{y,RA}(p)&1_{[Y_i\le Q_y(p)]}/f_y(Q_y(p))-(Q_y(p)/Q_x(p))1_{[X_i\le Q_x(p)]}/f_x(Q_x(p))\\
\widehat Q_{y,DI}(p)&1_{[Y_i\le Q_y(p)]}/f_y(Q_y(p))-(E_P(Y_i)/E_P(X_i))1_{[X_i\le Q_x(p)]}/f_x(Q_x(p))\\
\widehat Q_{y,REG}(p)&1_{[Y_i\le Q_y(p)]}/f_y(Q_y(p))-(E_P(X_iY_i)/E_P(X_i)^2)1_{[X_i\le Q_x(p)]}/f_x(Q_x(p))
\end{array}
\]''',[11],[3,4,5,6],[r'\zeta_i(p)'],'Complete four-row Table 1. Superpopulation inverse-CDF and derivative notation is archived as ambient context without importing all of Assumption 3 into downstream comparison statements. Preserve E_P(X_i)^2 typography; its placement is ambiguous between a second moment and square of the mean.','Table 1 — Quantile-process expressions')
add(25,'Expressions',r'''Table 3: Expressions of $\zeta'_{hjl}(p)$'s appearing in (8) for different $G(p)$'s in the case of stratified multistage cluster sampling design with SRSWOR

$H$ is fixed as $\nu\to\infty$
\[
\begin{array}{c|l}
G(p)&\zeta'_{hjl}(p)\\
\widehat Q_y(p)&1_{[Y'_{hjl}\le Q_{y,H}(p)]}/f_{y,H}(Q_{y,H}(p))\\
\widehat Q_{y,RA}(p)&1_{[Y'_{hjl}\le Q_{y,H}(p)]}/f_{y,H}(Q_{y,H}(p))-(Q_{y,H}(p)/Q_{x,H}(p))1_{[X'_{hjl}\le Q_{x,H}(p)]}/f_{x,H}(Q_{x,H}(p))\\
\widehat Q_{y,DI}(p)&1_{[Y'_{hjl}\le Q_{y,H}(p)]}/f_{y,H}(Q_{y,H}(p))-(\sum_{h=1}^H(N_h/N)E_P(Y'_{hjl})/\sum_{h=1}^H(N_h/N)E_P(X'_{hjl}))1_{[X'_{hjl}\le Q_{x,H}(p)]}/f_{x,H}(Q_{x,H}(p))\\
\widehat Q_{y,REG}(p)&1_{[Y'_{hjl}\le Q_{y,H}(p)]}/f_{y,H}(Q_{y,H}(p))-(\sum_{h=1}^H(N_h/N)E_P(X'_{hjl}Y'_{hjl})/\sum_{h=1}^H(N_h/N)E_P(X'_{hjl})^2)1_{[X'_{hjl}\le Q_{x,H}(p)]}/f_{x,H}(Q_{x,H}(p))
\end{array}
\]
$H\to\infty$ as $\nu\to\infty$
\[
\begin{array}{c|l}
G(p)&\zeta'_{hjl}(p)\\
\widehat Q_y(p)&1_{[Y'_{hjl}\le Q_{y,H}(p)]}/f_{y,H}(Q_{y,H}(p))\\
\widehat Q_{y,RA}(p)&1_{[Y'_{hjl}\le Q_{y,H}(p)]}/f_{y,H}(Q_{y,H}(p))-(Q_{y,H}(p)/Q_{x,H}(p))1_{[X'_{hjl}\le Q_{x,H}(p)]}/f_{x,H}(Q_{x,H}(p))\\
\widehat Q_{y,DI}(p)&1_{[Y'_{hjl}\le Q_{y,H}(p)]}/f_{y,H}(Q_{y,H}(p))-({}^{2}\Theta_2/{}^{2}\Theta_1)1_{[X'_{hjl}\le Q_{x,H}(p)]}/f_{x,H}(Q_{x,H}(p))\\
\widehat Q_{y,REG}(p)&1_{[Y'_{hjl}\le Q_{y,H}(p)]}/f_{y,H}(Q_{y,H}(p))-({}^{2}\Theta_3/{}^{2}\Theta_4)1_{[X'_{hjl}\le Q_{x,H}(p)]}/f_{x,H}(Q_{x,H}(p))
\end{array}
\]
${}^{2}$ The $\Theta_1$, $\Theta_2$, $\Theta_3$ and $\Theta_4$ are as in Assumption 10 in Section 4.''',[17],[3,4,5,6,21],[r"\zeta'_{hjl}(p)",r'\Theta_2'],'Both four-row regimes preserved. Superscript 2 preceding Theta is a footnote marker, not a power or multiplicative constant. Theta is the empirical moment-vector limit from Assumption 10 only in the growing-H rows; that reference does not impose Assumption 10 on fixed-H rows.','Table 3 — Stratified quantile-process expressions')
# Kernel passages are complete original excerpts of the corresponding theorem.
add(26,'covariance kernel',STATEMENTS[0][STATEMENTS[0].index(r'K(p_1,p_2)='):].replace('K(p_1,p_2)=',r'\['+'\n'+'K(p_1,p_2)=',1),[10],[1,24],[r'K(p_1,p_2)',r'S(p)'],'Equation (5), including centering and inclusion-probability correction; separate from the RHC and stratified kernels. This formula itself does not assume the entire high-entropy CLT.','Theorem 3.1 — Covariance kernel (5)',kind='theorem_excerpt',context=r'mean 0 Gaussian process in $D[\alpha,\beta]$ with almost sure continuous path and p.d. covariance kernel')
add(27,'covariance kernel',STATEMENTS[1][STATEMENTS[1].index('\\['):],[12],[13,24],[r'K(p_1,p_2)',r'\gamma',r'\bar X'],'Equation (7), gamma and its limiting factor c. Bar-X is used in the source without an explicit main-text equation defining it; inferred population mean interpretation is recorded separately.','Theorem 3.2 — RHC covariance kernel (7)',kind='theorem_excerpt',context=r'Then, the conclusion of Theorem 3.1 holds for $d(i,s)=A_i/NX_i$ and RHC sampling design with p.d. covariance kernel')
add(28,'covariance kernel',STATEMENTS[2][STATEMENTS[2].index('\\['):STATEMENTS[2].index('\n(ii)')],[16],[16,25],[r'K(p_1,p_2)',r"\zeta'_{hjl}(p)"],'Equation (8); preserve printed expectation-parenthesis placement. N_h, n_h and the stratum superpopulation model govern this kernel, with Table 3 using different H regimes.','Theorem 4.1 — Stratified covariance kernel (8)',kind='theorem_excerpt',context=r'Then, the conclusion of Theorem 3.1 holds for stratified multistage cluster sampling design with SRSWOR with p.d. covariance kernel')
add(29,'smooth function',r'''Let us fix $0<\alpha<\beta<1$ and consider the finite population parameter $\int_{[\alpha,\beta]}Q_{y,N}(p)J(p)dp$ for some known smooth function $J$ on $[0,1]$.

Next, suppose that $k\ge1$, $p_1,\ldots,p_k\in(0,1)$, $f:\mathbb R^k\to\mathbb R$ is a smooth function, and $f(Q_{y,N}(p_1),\ldots,Q_{y,N}(p_k))$ is a finite population parameter.''',[18,19],[2],[r'J',r'f:\mathbb R^k\to\mathbb R'],'Two classes of smooth finite-population quantile functionals; estimators substitute the selected G. Preserve the source smoothness wording rather than inventing a specific differentiability order.','Section 5 — Smooth functions of quantiles')
add(30,'asymptotic variances',r'''Here,
\[
\sigma_1^2=\int_\alpha^\beta\int_\alpha^\beta K(p_1,p_2)J(p_1)J(p_2)dp_1dp_2,\quad\sigma_2^2=\mathbf a\mathbf\Delta\mathbf a^T,
\]
(10)
$\mathbf\Delta$ is a $k\times k$ matrix such that
\[
((\mathbf\Delta))_{uv}=K(p_u,p_v)\text{ for }1\le u,v\le k,\text{ and }\mathbf a=\lim_{\nu\to\infty}\nabla f(Q_{y,N}(p_1),\ldots,Q_{y,N}(p_k))
\]
(11)
a.s. $[P]$.''',[19],[29],[r'\sigma_1^2',r'\mathbf\Delta',r'\mathbf a'],'Variance functionals for a supplied K; K is chosen per design, rather than importing all three kernels as dependencies. Gradient here is an almost-sure finite-population limit, distinct from the explicit superpopulation gradient in Section 6.','Theorem 5.1 — Asymptotic variances (10)–(11)',kind='theorem_excerpt',context=r'''In this section, we shall first compare different estimators of the finite population parameter $\int_{[\alpha,\beta]}Q_{y,N}(p)J(p)dp$ as well as $f(Q_{y,N}(p_1),\ldots,Q_{y,N}(p_k))$ (see Section 5) under each of SRSWOR, RHC and any HE$\pi$PS sampling designs in terms of their asymptotic variances given in Theorem 5.1.''',context_page=22)
add(31,'Estimation of asymptotic covariance kernels',r'''Following the approach of Cardot et al. (2014), $K(p_1,p_2)$, for $d(i,s)=(N\pi_i)^{-1}$, under any high entropy sampling design (see (5)) can be estimated by
\[
\widehat K(p_1,p_2)=(n/N^2)\sum_{i\in s}(\widehat\zeta_i(p_1)-\widehat{\bar\zeta}(p_1)-\widehat S(p_1)\pi_i)\times(\widehat\zeta_i(p_2)-\widehat{\bar\zeta}(p_2)-\widehat S(p_2)\pi_i)(\pi_i^{-1}-1)\pi_i^{-1},
\]
(12)
where $\widehat{\bar\zeta}(p)=\sum_{i\in s}(N\pi_i)^{-1}\widehat\zeta_i(p)$ and $\widehat S(p)=\sum_{i\in s}(\widehat\zeta_i(p)-\widehat{\bar\zeta}(p))(\pi_i^{-1}-1)/\sum_{i\in s}(1-\pi_i)$. Here, $\widehat\zeta_i(p)$ is obtained by replacing the superpopulation parameters involved in the expression of $\zeta_i(p)$ in Table 1 by their estimators under high entropy sampling designs (see Table 5 in Section 2 of the supplement (Dey and Chaudhuri (2024d))).''',[20,21],[1,24],[r'\widehat K(p_1,p_2)',r'\widehat S(p)'],'High-entropy plug-in kernel estimator; exact substitutions for zeta-hat are supplement-only and unresolved. Do not infer them from the coefficient names.','Section 5.1 — Kernel estimator (12)',context='Estimation of asymptotic covariance kernels and confidence intervals',context_page=20)
add(32,'Estimation of asymptotic covariance kernels',r'''Next, $K(p_1,p_2)$, for $d(i,s)=A_i/NX_i$ under RHC sampling design (see (7)), can be estimated as
\[
\widehat K(p_1,p_2)=n\gamma(\bar X/N)\sum_{i\in s}(\widehat\zeta_i(p_1)-\widehat{\bar\zeta}(p_1))(\widehat\zeta_i(p_2)-\widehat{\bar\zeta}(p_2))(A_i/X_i^2),
\]
(13)
where $\widehat{\bar\zeta}(p)=\sum_{i\in s}\widehat\zeta_i(p)(A_i/NX_i)$. Here, $\widehat\zeta_i(p)$ is obtained by replacing the superpopulation parameters involved in the expression of $\zeta_i(p)$ in Table 1 by their estimators under RHC sampling design (see Table 5 in Section 2 of the supplement (Dey and Chaudhuri (2024d))).''',[21],[13,27],[r'\widehat K(p_1,p_2)',r'A_i/X_i^2'],'RHC plug-in kernel with gamma from (7); zeta-hat substitutions are supplement-only. The A_i/X_i^2 factor differs from the centering A_i/(N X_i).','Section 5.1 — Kernel estimator (13)',context='Estimation of asymptotic covariance kernels and confidence intervals',context_page=20)
add(33,'Estimation of asymptotic covariance kernels',r'''Next, for the case of stratified multistage cluster sampling design with SRSWOR, $E_P(\zeta'_{hjl}(p_1)-E_P(\zeta'_{hjl}(p_1)))(\zeta'_{hjl}(p_2)-E_P(\zeta'_{hjl}(p_2)))$ in the expression of $K(p_1,p_2)$ in (8) can be estimated as
\[
\sum_{j\in s_h}\sum_{l\in s_{hj}}M_hN_{hj}(\widehat\zeta_{hjl}(p_1)-\widehat{\bar\zeta}_h(p_1))(\widehat\zeta_{hjl}(p_2)-\widehat{\bar\zeta}_h(p_2))/m_hr_hN_h,
\]
(15)
where $\widehat{\bar\zeta}_h(p)=\sum_{j\in s_h}\sum_{l\in s_{hj}}M_hN_{hj}\widehat\zeta_{hjl}(p)/m_hr_hN_h$, and $h=1,\ldots,H$. Here, $\widehat\zeta_{hjl}(p)$ is obtained replacing the superpopulation parameters involved in the expression of $\zeta'_{hjl}(p)$ in Table 3 by their estimators as mentioned in Table 6 in Section 2 of the supplement (Dey and Chaudhuri (2024d)). Thus an estimator of $K(p_1,p_2)$ in (8) under stratified multistage cluster sampling design with SRSWOR is obtained as
\[
\widehat K(p_1,p_2)=(n/N^2)\sum_{h=1}^H(N_h^2/n_h-N_h)\sum_{j\in s_h}\sum_{l\in s_{hj}}M_hN_{hj}(\widehat\zeta_{hjl}(p_1)-\widehat{\bar\zeta}_h(p_1))\times(\widehat\zeta_{hjl}(p_2)-\widehat{\bar\zeta}_h(p_2))/m_hr_hN_h.
\]
(16)''',[21,22],[16,25],[r'\widehat K(p_1,p_2)',r'\widehat{\bar\zeta}_h'],'Stratum-centered plug-in kernel; exact estimated Table-3 substitutions referred to supplement Table 6 are unresolved. No single-stage high-entropy assumptions are imported.','Section 5.1 — Stratified kernel estimator (15)–(16)',context='Estimation of asymptotic covariance kernels and confidence intervals',context_page=20)
add(34,'consistent estimators',r'''Given an estimator $\widehat K(p_1,p_2)$ of $K(p_1,p_2)$, an estimator of $\sigma_1^2$ can be constructed as $\widehat\sigma_1^2=\int_\alpha^\beta\int_\alpha^\beta\widehat K(p_1,p_2)J(p_1)J(p_2)dp_1dp_2$, whereas an estimator of $\sigma_2^2$ can be constructed as $\widehat\sigma_2^2=\widehat{\mathbf a}\widehat{\mathbf\Delta}\widehat{\mathbf a}^T$. Here, $\widehat{\mathbf a}=\nabla f(\widehat Q_y(p_1),\ldots,\widehat Q_y(p_k))$, $k\ge1$, $p_1,\ldots,p_k\in[\alpha,\beta]$, and $\widehat{\mathbf\Delta}$ is a $k\times k$ matrix such that $((\widehat{\mathbf\Delta}))_{uv}=\widehat K(p_u,p_v)$ for $1\le u,v\le k$. In the following theorem, we assert that the above estimators of $\sigma_1^2$ and $\sigma_2^2$ are consistent.''',[21],[3,29,30],[r'\widehat\sigma_1^2',r'\widehat{\mathbf a}'],'Plug-in variance functionals for a supplied kernel estimator. The gradient is evaluated at sample quantiles Qhat_y even when G is an adjusted estimator; preserve that choice.','Section 5.1 — Variance estimators',context=r'''We now discuss the estimation of the asymptotic covariance kernels mentioned in (5), (7) and (8) based on which consistent estimators of $\sigma_i^2$'s will be constructed.''',context_page=20)
add(35,'asymptotic covariance kernels',r'''Let us assume that $P(s,\omega)$ is one of SRSWOR, RHC and any HE$\pi$PS sampling designs. Let us also assume that $K_1(p_1,p_2)$, $K_2(p_1,p_2)$, $K_3(p_1,p_2)$ and $K_4(p_1,p_2)$ are the asymptotic covariance kernels of the quantile processes constructed based on $\widehat Q_y(p)$, $\widehat Q_{y,RA}(p)$, $\widehat Q_{y,DI}(p)$ and $\widehat Q_{y,REG}(p)$ under $P(s,\omega)$, respectively (see Table 2 and (7)), and $\{\mathbf\Delta_u:1\le u\le4\}$ is a $k\times k$ matrix such that
\[
((\mathbf\Delta_u))_{wv}=K_u(p_w,p_v)\text{ for }1\le w,v\le k\text{ and }1\le u\le4.
\]
(17)''',[22],[9,26,27],[r'K_1(p_1,p_2)',r'\mathbf\Delta_u'],'Estimator-indexed covariance family under one fixed design. Four estimator choices; index u does not enumerate designs. Table 2 is archived in ambient prerequisites with its exact typography.','Section 6.1 — Estimator comparison kernels (17)',kind='source_passage')
add(36,'asymptotic covariance kernels',r'''Let us assume that $G(p)$ is one of $\widehat Q_y(p)$, $\widehat Q_{y,RA}(p)$, $\widehat Q_{y,DI}(p)$ and $\widehat Q_{y,REG}(p)$, $K_1^*(p_1,p_2)$, $K_2^*(p_1,p_2)$ and $K_3^*(p_1,p_2)$ denote asymptotic covariance kernels of the quantile process based on $G(p)$ under SRSWOR, RHC and any HE$\pi$PS sampling designs (see Table 2 and (7)), respectively, and $\{\mathbf\Delta_u^*:1\le u\le3\}$ are $k\times k$ matrices such that
\[
((\mathbf\Delta_u^*))_{wv}=K_u^*(p_w,p_v)\text{ for }1\le w,v\le k\text{ and }1\le u\le3.
\]
(20)''',[23],[9,26,27],[r'K_1^*(p_1,p_2)',r'\mathbf\Delta_u^*'],'Design-indexed covariance family for one fixed estimator G; three design choices, not four estimator choices.','Section 6.1 — Design comparison kernels (20)',kind='source_passage')
add(37,'GREG estimator',r'''Here, we compare the GREG estimator, say $\widehat{\bar Y}_{GREG}$ (see Cochran (1977), Dey and Chaudhuri (2024b) and references therein), of the finite population mean $\bar Y=\sum_{i=1}^NY_i/N$, the sample mean $\bar y=\sum_{i\in s}Y_i/n$, and the sample median $\widehat Q_y(0.5)$ under SRSWOR in terms of asymptotic variances of $\sqrt n(\widehat{\bar Y}_{GREG}-E_P(Y_i))$, $\sqrt n(\bar y-E_P(Y_i))$ and $\sqrt n(\widehat Q_y(0.5)-Q_y(0.5))$, when the superpopulation median $Q_y(0.5)$ and the superpopulation mean $E_P(Y_i)$ are same.''',[25,26],[1,3],[r'\widehat{\bar Y}_{GREG}',r'\widehat Q_y(0.5)'],'Source names/cites GREG but does not define its estimator formula in the main text. Retain it as unresolved, not equated to the quantile regression slope. The comparison centers at superpopulation targets, unlike earlier finite-population CLTs.','Section 6.2 — GREG, sample mean and sample median',kind='source_passage')

for n in [24,25]:
    lid='D'+str(n);x=next(x for x in interfaces if x['members'][0]['local_id']==lid)
    term='high entropy and RHC sampling designs' if n==24 else 'stratified multistage cluster sampling design with SRSWOR'
    assert term in members[lid]['statement_original']
    label=term[0].upper()+term[1:]
    x['source_keywords'].append(dict(paper_id=PID,local_id=lid,source_text=term,label=label,kind='term'))
    x['name']='Expressions · '+label

def main():
    (ROOT/'source-passages.json').write_text(json.dumps(dict(paper_id=PID,members=list(members.values())),indent=2,ensure_ascii=False)+'\n')
    (ROOT/'interface-extraction.json').write_text(json.dumps(dict(paper_id=PID,interfaces=interfaces),indent=2,ensure_ascii=False)+'\n')
if __name__=='__main__':main()
