"""Archive supporting source passages, branch scope and unresolved main-text references."""
import json
from save_inventory import ROOT,PID
def main():
    aux=[]
    def add(n,s,pages,note,deps=()):aux.append(dict(local_id='A'+str(n),statement_original=s,evidence=[dict(page=p,location='Original main-text context A'+str(n)) for p in pages],scope_note=note,depends_on=list(deps)))
    add(1,r'''Let $(Y_i,X_i)$ be the value of $(y,x)$ for the $i$th population unit, $i=1,\ldots,N$, where $y$ is a real valued study variable and $x$ is a positive real valued size/auxiliary variable. In sample survey, the population values $\{X_i\}_{i=1}^N$ on $x$ are assumed to be known and utilized to implement sampling designs as well as to construct estimators.''',[5],'Observed study values and known positive auxiliary population values. No independence between study and auxiliary variables is assumed.')
    add(2,r'''Here, $\pi_i$ is the inclusion probability of the $i$th population unit under any sampling design $P(s)$, and $A_i$ is the $x$ total of that group of population units formed in the first step of the RHC sampling design from which the $i$th population unit is selected in the sample (see the 2nd paragraph following Theorem 3.1 in Section 3).''',[5],'Meaning of inverse-inclusion weights and RHC group-total weights. The fixed-size SRSWOR name is used throughout; a PMF formula is not printed in the main text.',['D1','D13'])
    add(3,r'''We consider a superpopulation model such that $\{(Y_i,X_i):1\le i\le N\}$ are i.i.d. random vectors on some probability space $(\Omega,\mathcal F,P)$ (see Boistard et al. (2017a), Conti (2014), Conti and Marella (2015) and references therein).''',[7],'Single-stage model only: iid across population units, not independence between X_i and Y_i and not identical distribution across strata in Section 4.')
    add(4,r'''We define our asymptotic framework as follows. Let $\{\mathcal P_\nu\}$ be a sequence of populations with $N_\nu,n_\nu\to\infty$ as $\nu\to\infty$ (see Boistard et al. (2017a), Conti and Marella (2015), Wang and Opsomer (2011), etc.), where $N_\nu$ and $n_\nu$ are, respectively, the population and sample sizes corresponding to the $\nu$th population. We suppress the limiting index $\nu$ for the sake of notational simplicity.''',[7],'Diverging sample and population sizes plus theorem-specific limiting sampling fractions.',['D10'])
    add(5,r'''Suppose that $F_y$ and $F_x$ are superpopulation distribution functions of $y$ and $x$, respectively. Further, suppose that $Q_y(p)=\inf\{t\in\mathbb R:F_y(t)\ge p\}$ and $Q_x(p)=\inf\{t\in\mathbb R:F_x(t)\ge p\}$ are superpopulation $p$th quantiles of $y$ and $x$, respectively.''',[8],'Generalized inverse convention for the superpopulation, distinct from finite-population Q_y,N. Density symbols f_y,f_x denote the derivatives named in Assumption 3; use of those symbols alone does not assert its complete hypothesis.')
    add(6,r'''All vectors in Euclidean spaces will be taken as row vectors and superscript $T$ will be used to denote their transpose.''',[8],'Quadratic forms and covariance matrices use row-vector convention.')
    add(7,r'''A sampling design is called HE$\pi$PS sampling design if it is a high entropy as well as a $\pi$PS sampling design (e.g., RS sampling design, rejective sampling design, etc.).''',[10],'Conjunction of high entropy and inclusion-probability-proportional-to-size design classes. Main text does not define a full piPS or rejective PMF; exact construction remains external. Do not conflate piPS inclusion probabilities with one-step PPS draws in RHC.',['D9'])
    add(8,r'''Table 2: $K(p_1,p_2)$ in (5) under different high entropy sampling designs

SRSWOR and LMS:
\[
(1-\lambda)E_P[\zeta_i(p_1)-E_P(\zeta_i(p_1))][\zeta_i(p_2)-E_P(\zeta_i(p_2))]
\]
HE$\pi$PS:
\[
{}^{1}E_P[\zeta_i(p_1)-E_P(\zeta_i(p_1))+\lambda\chi^{-1}\mu_x^{-1}X_iE_P((\zeta_i(p_1)-E_P(\zeta_i(p_1)))X_i)]\times
[\zeta_i(p_2)-E_P(\zeta_i(p_2))+\lambda\chi^{-1}\mu_x^{-1}X_iE_P((\zeta_i(p_2)-E_P(\zeta_i(p_2)))X_i)]\times[\mu_xX_i^{-1}-\lambda].
\]
${}^{1}$ $\mu_x=E_P(X_i)$ and $\chi=\mu_x-(\lambda E_P(X_i)^2/\mu_x)$.''',[11],'Exact displayed factors, expectation placement and footnote preserved. The superscript 1 is a footnote, not a power. Second-moment and outer-expectation grouping require interpretation; no silent repair. These kernels are explicitly referenced by both comparison theorems.',['D24','D26'])
    add(9,r'''We assume that for any given $h$, $\{(Y'_{hjl},X'_{hjl}):l=1,\ldots,N_{hj},j=1,\ldots,M_h\}$ are i.i.d. random vectors defined on $(\Omega,\mathcal F,P)$ with marginal distribution functions $F_{y,h}$ and $F_{x,h}$, where $F_{y,h}$'s and $F_{x,h}$'s are not necessarily identical for varying $h$. We also assume that the population observations on $(y,x)$ in any stratum are independent of the observations in other strata.''',[13,14],'Stratified superpopulation replaces the global iid model. Outcomes are iid even across clusters within a stratum as printed, independent across strata, and may have different stratum distributions.',['D16'])
    add(10,r'''Let $N_h=\sum_{j=1}^{M_h}N_{hj}$ and $n_h=m_hr_h$ be the number of population units in stratum $h$ and the number of population units sampled from stratum $h$, respectively, for any $h=1,\ldots,H$.''',[14],'Stratum counts in all kernel and regularity formulas.',['D16'])
    add(11,r'''$\mathbf W_i=(X_i,Y_i,X_iY_i,X_i^2)$''',[10,12],'Moment-vector definition from T3.1/T3.2. Their E_P||W_i||² hypothesis includes products and X fourth moments; keep complete printed assumption rather than reducing to separate X,Y second moments.')
    add(12,r'''$\mathbf W'_{hjl}=(X'_{hjl},Y'_{hjl},X'_{hjl}Y'_{hjl},(X'_{hjl})^2)$''',[14],'Vector definition in Assumption 7, also used by Assumption 10. Referencing the vector does not import Assumption 7 entire hypothesis. Growing-H Theta is the vector limit explicitly specified in Assumption 10, while fixed-H Table 3 uses stratum expectations.',['D16'])
    add(13,r'''Suppose that $X_i\le b$ a.s. $[P]$ for some $b>0$, $E_P(X_i)^{-1}<\infty$, Assumption 1 holds with $0<\lambda<E_P(X_i)/b$, Assumptions 4 and 5 hold, and (6) holds.''',[23],'Identical opening conditions of T6.1 and T6.2; upper bound b and the stricter lambda range are theorem-local. The literal inverse-moment typography is retained.',['D10','D13','D14','D15'])
    add(14,r'''Here, $\sigma_y^2$ and $f_y$ are the superpopulation variance and density function of $y$, respectively, and $\rho_{xy}$ is the superpopulation correlation coefficient between $x$ and $y$.''',[26],'T6.3 variance/density/correlation convention. The statement does not explicitly add finiteness and nonzero variance conditions required for the usual correlation definition; that issue is recorded.')
    issues=[]
    def issue(i,pages,note):issues.append(dict(issue_id=i,evidence=[dict(page=p,location='Source scope or notation issue') for p in pages],note=note))
    issue('conclusion-versus-assumptions',[12,16,19,20,21,22],'T3.2 and T4.1 import the conclusion of T3.1 with design/kernel replacements, not its high-entropy assumptions. T5.1(i) assumes the conclusion of T3.1; T5.1(ii) and T5.3 import T3.2 assumptions. T5.2 imports (9) only; T5.4 imports T4.1 assumptions and (14) only. Preserve these distinctions.')
    issue('fixed-versus-growing-strata',[14,15,16,17,20],'Fixed-H uses Assumptions 1,6–8; growing-H uses 1,8–11. The union in a theorem dependency inventory denotes use in different branches, not simultaneous hypotheses. Theta references in growing-H Table 3 do not impose Assumption 10 on fixed-H formulas.')
    issue('left-continuous-paths',[6,7,9],'Quantile paths D are left continuous with right limits and ball sigma-field. Right-continuous tilde-D is a proof empirical-process space, not the inventoried quantile-process state space.')
    issue('positive-definiteness-quantifiers',[8,15],'Assumptions 2 and 10 quantify over arbitrary p1,...,pk without saying distinct. Repeated indices duplicate coordinates and conflict with strict positive definiteness. Preserve the printed quantifiers; no inferred distinctness is inserted.')
    issue('expectation-parentheses',[11,15,16,21],'Equation (8), Gamma_h and Table 2 visually place expectation immediately on the first centered factor, without explicit outer parentheses enclosing the product. The intended covariance grouping is an inference. Original formulas retain the printed placement.')
    issue('moment-power-typography',[11,12,17,23],'E_P(X_i)^2 in Table 1, Table 2 and Table 3 can be misread as squared mean rather than second moment. The regression estimator slope suggests the latter interpretation. E_P(X_i)^(-1) similarly uses a trailing power in inverse-moment assumptions. Preserve typography rather than silently reparenthesize.')
    issue('undefined-bar-x',[12,21],'Bar-X occurs in (7) and (13), but no explicit main-text defining equation was found. Interpreting it as the known finite-population auxiliary mean is plausible, not a quoted definition.')
    issue('supplement-plug-in-definitions',[20,21,22],'Zeta-hat and stratified zeta-hat substitute estimators from supplement Tables 5 and 6. Exact density/moment substitutions are not supplied in the main text. The references remain unresolved; no supplement or appendix body was read.')
    issue('external-sampling-definitions',[8,10,11],'Rejective sampling and piPS are named with external references; main text provides the KL characterization of high entropy and the full RHC grouping procedure, but not full rejective/piPS construction formulas. Do not invent them.')
    issue('external-greg-definition',[25,26],'Section 6.2 names and cites the GREG mean estimator without specifying its formula. This is not automatically the uncentered quantile regression coefficient in (2). Main-text census keeps it unresolved.')
    issue('comparison-kernel-existence',[22,23,24],'T6.1 and T6.2 refer to asymptotic covariance kernels in preceding prose but omit Assumption 3 and the W second-moment hypothesis in their printed opening conditions. Record that existence/regularity gap without adding those hypotheses to the quotation or dependency graph.')
    issue('median-comparison-scope',[25,26],'T6.3 comparisons are separately paired by respectively. The surrounding paragraph centers at superpopulation mean/median, not finite-population targets. Variance/correlation existence is implicit rather than explicitly guaranteed by printed Assumptions 1 and 3.')
    issue('slash-division',[26],'Equations (23) and (24) print 1/4 f_y^2 and 1/4 sigma_y^2 f_y^2 in slash notation. Interpreting the full products as denominators is inferred from context; original statement preserves the slash form.')
    issue('table-footnotes',[11,17],'Table 2 superscript 1 and Table 3 superscript 2 are footnote marks; in Table 3 the repeated mark preceding Theta is neither exponent nor multiplication by 2.')
    issue('smoothness-and-gradient',[18,19,21],'J and f are described as smooth, without a numeric order. The variance estimator gradient is evaluated at Qhat_y, not an arbitrary adjusted G, as printed. Theorem 5.1 uses a limiting finite-population gradient; comparison theorems write the superpopulation gradient directly.')
    refs=[]
    def ref(n,label,kind,scope):refs.append(dict(from_claim_id=PID+'/T'+n,to_source_label=label,reference_kind=kind,scope=scope))
    for n in ['3.2','4.1']:ref(n,'Theorem 3.1','conclusion_reference','Quantile-process convergence conclusion only; substitute this theorem sampling design, weights and covariance kernel.')
    ref('5.1','Theorem 3.1','conclusion_as_hypothesis','Part (i) assumes the functional convergence conclusion; do not import Assumption 2 or other sufficient conditions from that theorem.')
    ref('5.1','Theorem 3.2','assumption_reference','Part (ii) imports its assumptions for the RHC branch only.')
    ref('5.2','Theorem 5.1, (9)','conclusion_reference','Import the two normal limits with cluster design, weights and K(8), not the high-entropy or RHC hypotheses.')
    for label in ['Theorem 3.1','Theorem 3.2']:ref('5.3',label,'assumption_reference','Branch-specific assumptions; high-entropy and RHC are alternatives.')
    ref('5.4','Theorem 4.1','assumption_reference','Retain the fixed-H and growing-H alternatives.')
    ref('5.4','Theorem 5.3, (14)','conclusion_reference','Variance consistency conclusion only, not the single-stage assumptions.')
    ref('5.3','Supplement Table 5, Section 2','appendix_reference_unresolved','Exact zeta-hat substitutions are not defined in the main text.')
    ref('5.4','Supplement Table 6, Section 2','appendix_reference_unresolved','Exact stratified zeta-hat substitutions are not defined in the main text.')
    ref('6.3','Cochran (1977), Dey and Chaudhuri (2024b)','external_definition_unresolved','GREG mean estimator named and cited; main text supplies no formula.')
    bindings={
'T3.1':'A1–A6 fix positive auxiliary values, known population x, single-stage iid model, joint P*, asymptotic sequence, superpopulation quantiles and row vectors. D2–D6 give the finite target and four estimators. D8 is the left-continuous path space. D9–D12 are high entropy and Assumptions 1–3, with W moment condition A11. Kernel (5) and Table 1 are D26,D24. The positive-definiteness quantifier issue remains explicit.',
'T3.2':'Inherit the process-convergence conclusion only, with RHC design, balanced grouping (6), weights A_i/(N X_i), Assumptions 1,3–5 and the printed two moment conditions. D27 and D24 replace the kernel; no high-entropy or Assumption 2 premise is imported. A2 defines group total, A11 the moment vector; bar-X remains unresolved.',
'T4.1':'The process conclusion uses D8 and estimators D3–D6 with D16 design and A9–A10 stratum model/counts. Part (i): fixed H and Assumptions 1,6–8. Part (ii): H grows and Assumptions 1,8–11. D28 and D25 give kernel (8) and both Table 3 cases; mixture quantities D21 follow. Definition of W-prime is A12; using it does not import Assumption 7 into growing-H.',
'T5.1':'Part (i) assumes the T3.1 process conclusion and continuous K(5), not all its sufficient hypotheses. Part (ii) assumes T3.2 hypotheses, uses RHC weights and K(7), and asserts (9). D29 supplies smooth J/f and the finite-population targets, D30 the variance functional with the chosen kernel. Branch-specific conditions are not conjoined.',
'T5.2':'Two finite-population-centered normal limits (9), with D29 smooth functionals and D30 variance functional supplied K(8). Fixed-H uses 1,6–8; growing-H uses 1,8–11 and explicit continuity K(8). D16 and A9–A10 fix stratum design/model/counts. No high-entropy or RHC premise inherited from the cited result.',
'T5.3':'High-entropy branch assumes T3.1 conditions and pairs K(5) with Khat(12); RHC branch assumes T3.2 conditions and pairs K(7) with Khat(13). D34 fixes the variance estimators, using gradient at Qhat_y. Exact zeta-hat substitutions remain unresolved supplement references.',
'T5.4':'Assumptions of T4.1 retain both H regimes. D28,D33 supply K(8), Khat(16); D30,D34 supply variance targets and estimators. Only consistency conclusion (14) is imported from T5.3; its high-entropy/RHC hypotheses are not. Supplement Table 6 is unresolved.',
'T6.1':'A13 gives the explicit X upper bound, inverse-moment typography and stricter lambda interval; 1,4,5 and balanced grouping (6) are printed. D35 indexes four estimators under one fixed design; D29 supplies the two functionals. K(5)/(7) and Table 2 determine its covariance family. The max over u=2..4 requires strict improvement over every adjusted estimator. Missing explicit covariance-existence assumptions are flagged, not added.',
'T6.2':'Same A13 hypotheses. D36 instead indexes SRSWOR,RHC,HEpiPS for one fixed estimator G. The maxima run u=2..3; D29 gives the two targets. Retain the superpopulation gradient in (22). Do not reinterpret the index as the four estimators or add Assumption 3 through kernel notation.',
'T6.3':'D37 retains the externally defined GREG, sample mean and sample median, centered at superpopulation targets. Assumptions 1,3 and Q_y(0.5)=E_P(Y_i) are the printed hypotheses. A14 defines variance/density/correlation; existence and slash-division ambiguities are flagged. Respectively pairs each inequality with its own comparison.'}
    out=dict(paper_id=PID,status='extracted',unranked_auxiliary_passages=aux,source_issues=issues,source_claim_references=refs,statement_local_bindings=bindings,ambient_prerequisites=['Finite populations, fixed-size subset laws, inclusion probabilities, row vectors and transpose, covariance matrices, positive definiteness, integration, Gaussian processes, convergence in law and probability.','Main-text inverse-CDF and open-support conventions are retained. Standard variance/correlation and derivative notation stays local; no library-availability claim is made.','Alternative designs and fixed/growing stratum regimes remain separately scoped even when one theorem has dependencies from both branches.'],extraction_policy='Main-text Theorems only; appendix bodies excluded. Named external constructions and supplement-only substitutions stay explicitly unresolved. Original statements and formulas are preserved separately from interpretive notes.')
    (ROOT/'ambient-prerequisites.json').write_text(json.dumps(out,indent=2,ensure_ascii=False)+'\n')
if __name__=='__main__':main()
