"""Preserve main-text tensor regression definitions, algorithms and referenced conditions."""
import json
from save_inventory import ROOT,PID,STATEMENTS
interfaces=[];members={}
def add(n,term,s,pages,deps,symbols,boundary,heading,kind='definition',context=None,context_page=None,phrases=None):
    lid=f'D{n}'
    m=dict(paper_id=PID,local_id=lid,local_label=heading,source_heading=heading,source_kind=kind,statement_original=s,relation='exact',depends_on=[f'D{i}' for i in deps],evidence=[dict(page=p,location=heading) for p in pages],highlight_symbols=symbols,highlight_phrases=phrases or [])
    kw=dict(paper_id=PID,local_id=lid,source_text=term,label=term[0].upper()+term[1:],kind='term')
    if term not in s:
        assert context and term in context,(lid,term)
        m['naming_context']=[dict(context_id=lid+'/name',text=context,evidence=[dict(page=context_page or pages[0],location='Original naming context')])];kw['context_id']=lid+'/name'
    members[lid]=m
    interfaces.append(dict(interface_id=PID+'/'+lid,rank_group='all',name=kw['label'],lean_role='definition',type_shape=boundary,semantic_boundary=boundary,members=[m],source_keywords=[kw],central_claim_uses=[],dependencies=[],theorem_explanations={}))
add(1,'tensor-on-tensor regression',r'''This paper studies a general class of problems termed tensor-on-tensor regression, which aims to characterize the relationships between covariates and responses in the form of scalars, vectors, matrices, or high-order tensors:
\[
\mathcal Y_i=\langle\mathcal A_i,\mathcal X^*\rangle_*+\mathcal E_i,\qquad i=1,\ldots,n.
\]
(1)
Here, $\mathcal A_i\in\mathbb R^{p_1\times\cdots\times p_d},i=1,\ldots,n$ are the known order-$d$ (or $d$-way) tensor covariates. $\mathcal Y_i,\mathcal E_i\in\mathbb R^{p_{d+1}\times\cdots\times p_{d+m}}$ are both order-$m$ tensors and are observations and unknown noise, respectively. $\mathcal X^*\in\mathbb R^{p_1\times\cdots\times p_d\times p_{d+1}\times\cdots\times p_{d+m}}$ is an order-$(d+m)$ tensor parameter of interest. $\langle\cdot,\cdot\rangle_*$ is the contracted tensor inner product defined as $\langle\mathcal A_i,\mathcal X^*\rangle_*\in\mathbb R^{p_{d+1}\times\cdots\times p_{d+m}}$,
\[
(\langle\mathcal A_i,\mathcal X^*\rangle_*)_{[j_1,\ldots,j_m]}=\sum_{\substack{k_l=1,\\l=1,\ldots,d}}^{p_l}\mathcal A_{i[k_1,\ldots,k_d]}\mathcal X^*_{[k_1,\ldots,k_d,j_1,\ldots,j_m]}.
\]
Throughout the paper, we consider $d$ and $m$ to be fixed constants. We also stack all responses and errors to $\mathcal Y,\mathcal E\in\mathbb R^{n\times p_{d+1}\times\cdots\times p_{d+m}}$, where $\mathcal Y_{[i,:,\ldots,:]}=\mathcal Y_i$ and $\mathcal E_{[i,:,\ldots,:]}=\mathcal E_i$. Then the tensor-on-tensor regression model can be written succinctly as $\mathcal Y=\mathscr A(\mathcal X^*)+\mathcal E$, where $\mathscr A:\mathbb R^{p_1\times\cdots\times p_{d+m}}\to\mathbb R^{n\times p_{d+1}\times\cdots\times p_{d+m}}$ is a linear map such that
\[
\mathscr A(\mathcal X^*)_{[i,:,\ldots,:]}=\langle\mathcal A_i,\mathcal X^*\rangle_*\quad\text{for }i=1,\ldots,n.
\]
(2)''',[1,2],[],[r'\langle\mathcal A_i,\mathcal X^*\rangle_*',r'\mathcal Y=\mathscr A(\mathcal X^*)+\mathcal E'],'General contraction regression model with fixed covariate order d and response order m. This passage does not assume Gaussian design; Definition2 is separate. The source summation notation over all k_l is preserved.','Introduction — Tensor-on-tensor regression (1)–(2)',kind='source_passage')
add(2,'Tucker rank',r'''The matricization operation $\mathcal M_k(\cdot)$ unfolds an order-$d$ tensor along mode $k$ to a matrix, say $\mathcal A\in\mathbb R^{p_1\times\cdots\times p_d}$ to $\mathcal M_k(\mathcal A)\in\mathbb R^{p_k\times p_{-k}}$, where $p_{-k}=\prod_{j\ne k}p_j$ and its detailed definition is provided in Supplement B. The Frobenius norm of tensor $\mathcal A$ is defined as $\|\mathcal A\|_{\mathrm F}=(\sum_{i_1,\ldots,i_d}\mathcal A_{[i_1,\ldots,i_d]}^2)^{1/2}$. The Tucker rank of an order-$d$ tensor $\mathcal A$, denoted by $\operatorname{Tucrank}(\mathcal A)$, is defined as a $d$-tuple $\mathbf r:=(r_1,\ldots,r_d)$, where $r_k=\operatorname{rank}(\mathcal M_k(\mathcal A))$.''',[7],[],[r'\operatorname{Tucrank}(\mathcal A)',r'\mathcal M_k(\mathcal A)'],'Multilinear rank defined by matrix ranks of mode unfoldings. Generic order d is instantiated as d+m in regression. Main-text mode unfolding is retained, but its detailed index convention is deferred to an excluded supplement. Frobenius norm is standard ambient context.','Section 1.5 — Matricization and Tucker rank')
add(3,'singular vectors',r'''For any matrix $\mathbf D\in\mathbb R^{p_1\times p_2}$, let $\sigma_k(\mathbf D)$ be the $k$th largest singular value of $\mathbf D$. We also denote $\operatorname{SVD}_r(\mathbf D)=[\mathbf u_1\ \cdots\ \mathbf u_r]$ and $\operatorname{QR}(\mathbf D)$ as the subspace composed of the leading $r$ left singular vectors and the Q part of the QR decomposition of $\mathbf D$, respectively.''',[7],[],[r'\sigma_k(\mathbf D)',r'\operatorname{SVD}_r(\mathbf D)'],'The paper’s SVD_r returns a basis matrix of leading LEFT singular vectors, not a truncated reconstructed matrix. QR(D) denotes its Q part. Singular values are ordered decreasingly. Bases at ties remain choices; P_r is a separate reconstruction operator.','Section 1.5 — Singular values, singular vectors and QR')
add(4,'Tucker decomposition',r'''Any Tucker rank-$(r_1,\ldots,r_d)$ tensor $\mathcal A$ admits the following Tucker decomposition (Tucker, 1966): $\mathcal A=\llbracket\mathcal S;\mathbf U_1,\ldots,\mathbf U_d\rrbracket:=\mathcal S\times_1\mathbf U_1\times\cdots\times_d\mathbf U_d$, where $\mathcal S\in\mathbb R^{r_1\times\cdots\times r_d}$ is the core tensor and $\mathbf U_k=\operatorname{SVD}_{r_k}(\mathcal M_k(\mathcal A))$ is the mode-$k$ top $r_k$ left singular vectors. Here, the mode-$k$ product of $\mathcal A\in\mathbb R^{p_1\times\cdots\times p_d}$ with a matrix $\mathbf B\in\mathbb R^{r_k\times p_k}$, denoted by $\mathcal A\times_k\mathbf B$, is a $p_1\times\cdots\times p_{k-1}\times r_k\times p_{k+1}\times\cdots\times p_d$-dimensional tensor, and its definition is provided in Supplement B. The following abbreviations are used to denote the tensor-matrix product along multiple modes: $\mathcal A\times_{k=1}^d\mathbf U_k:=\mathcal A\times_1\mathbf U_1\times\cdots\times_d\mathbf U_d$; $\mathcal A\times_{l\ne k}\mathbf U_l:=\mathcal A\times_1\mathbf U_1\times\cdots\times_{k-1}\mathbf U_{k-1}\times_{k+1}\mathbf U_{k+1}\times\cdots\times_d\mathbf U_d$.''',[7],[2,3],[r'\llbracket\mathcal S;\mathbf U_1,\ldots,\mathbf U_d\rrbracket',r'\mathcal A\times_k\mathbf B'],'Original Tucker core/factor reconstruction and mode-product notation. The detailed mode-product index definition is deferred to SupplementB and remains unresolved within this main-text scope.','Section 1.5 — Tucker decomposition and tensor-matrix products')
add(5,'approximation',r'''For any order-$d$ tensor $\mathcal Z\in\mathbb R^{p_1\times\cdots\times p_d}$ and a $d$-tuple $\mathbf r=(r_1,\ldots,r_d)$, let $\mathcal Z_{\max(\mathbf r)}:=\mathcal Z\times_{k=1}^d P_{\widehat{\mathbf U}_k}$ be the best Tucker rank $\mathbf r$ approximation of $\mathcal Z$ in terms of Frobenius norm, where $(\widehat{\mathbf U}_1,\ldots,\widehat{\mathbf U}_d)$ is the solution to $\operatorname{arg\,max}_{\mathbf U_k\in\mathbb O_{p_k,r_k},k=1,\ldots,d}\|\mathcal Z\times_{k=1}^d P_{\mathbf U_k}\|_{\mathrm F}$ (De Lathauwer et al., 2000b, Theorem 4.2).''',[7],[2,4],[r'\mathcal Z_{\max(\mathbf r)}',r'\mathbb O_{p_k,r_k}'],'Best Frobenius Tucker-rank approximation through a maximizing tuple of orthonormal mode subspaces. Stiefel/projection notation is retained as ambient A1. This is not the efficiently computed T-HOSVD retraction or the matrix P_r operator.','Section 1.5 — Best Tucker rank approximation')
# Original main-text naming context identifies the tensor low-rank projection.
members['D5']['naming_context']=[dict(context_id='D5/name',text=members['D5']['statement_original'],evidence=[dict(page=7,location='Best Tucker approximation definition')])]
add(6,'loss function',r'''\[
\widehat{\mathcal X}_{\mathrm{opt}}=\underset{\mathcal X\in\mathbb R^{p_1\times\cdots\times p_{d+m}}}{\operatorname{arg\,min}}\ f(\mathcal X):=\frac12\|\mathcal Y-\mathscr A(\mathcal X)\|_{\mathrm F}^2,\qquad\text{subject to }\operatorname{Tucrank}(\mathcal X)\le\mathbf r.
\]
(3)''',[3],[1,2],[r'f(\mathcal X):=\frac12\|\mathcal Y-\mathscr A(\mathcal X)\|_{\mathrm F}^2',r'\operatorname{Tucrank}(\mathcal X)\le\mathbf r'],'Bounded-Tucker-rank least-squares problem. Theorem3 explicitly compares residual loss and is not restricted to this global optimizer. RGD/RGN are algorithms, not identities asserting global minimization.','Section 1.1 — Rank-constrained least squares (3)',context='such as the global minimizer of the loss function (3)',context_page=12)
add(7,'tangent space',r'''Denote the collection of $(p_1,\ldots,p_d,p_{d+1},\ldots,p_{d+m})$-dimensional tensors of Tucker rank $\mathbf r:=(r_1,\ldots,r_d,r_{d+1},\ldots,r_{d+m})$ by $\mathbb M_{\mathbf r}=\{\mathcal X\in\mathbb R^{p_1\times\cdots\times p_{d+m}},\operatorname{Tucrank}(\mathcal X)=\mathbf r\}$. Then $\mathbb M_{\mathbf r}$ forms a $\{\prod_{j=1}^{d+m}r_j+\sum_{j=1}^{d+m}r_j(p_j-r_j)\}$-dimensional smooth submanifold embedded in $\mathbb R^{p_1\times\cdots\times p_{d+m}}$ (Uschmajew and Vandereycken, 2013). Recall in the general over-parameterized scenario, $\mathbf r$ may be different from $\mathbf r^*$, the actual rank of the tensor of interest. Suppose $\mathcal X\in\mathbb M_{\mathbf r}$ has Tucker decomposition $\llbracket\mathcal S;\mathbf U_1,\ldots,\mathbf U_d,\mathbf U_{d+1},\ldots,\mathbf U_{d+m}\rrbracket$. Define $\mathbf V_k=\operatorname{QR}(\mathcal M_k(\mathcal S)^\top)$, which corresponds to the row space of $\mathcal M_k(\mathcal S)$, and for $k=1,\ldots,d+m$, define
\[
\mathbf W_k:=(\mathbf U_{d+m}\otimes\cdots\otimes\mathbf U_{k+1}\otimes\mathbf U_{k-1}\otimes\cdots\otimes\mathbf U_1)\mathbf V_k\in\mathbb O_{p_{-k},r_k},
\]
(4)
where $p_{-k}=\prod_{j=1,j\ne k}^{d+m}p_j$. By the tensor matricization formula provided in Supplement B, $\mathbf U_k,\mathbf W_k$ correspond to the subspaces of the column and row spans of $\mathcal M_k(\mathcal X)$, respectively. Koch and Lubich (2010) provided the explicit formulas for the tangent space of $\mathbb M_{\mathbf r}$ at $\mathcal X$, denoted by $T_{\mathcal X}\mathbb M_{\mathbf r}$ (see Supplement B for the expression). We equip $\mathbb M_{\mathbf r}$ with the Riemannian metric induced by the natural Euclidean inner product $\langle\cdot,\cdot\rangle$. Under this metric, the following operator $P_{T_{\mathcal X}}$ projects any tensor $\mathcal Z\in\mathbb R^{p_1\times\cdots\times p_{d+m}}$ onto the tangent space $T_{\mathcal X}\mathbb M_{\mathbf r}$,
\[
P_{T_{\mathcal X}}(\mathcal Z):=\mathcal Z\times_{k=1}^{d+m}P_{\mathbf U_k}+\sum_{k=1}^{d+m}\mathcal T_k(P_{\mathbf U_{k\perp}}\mathcal M_k(\mathcal Z)P_{\mathbf W_k}),
\]
(5)
where $\mathcal T_k(\cdot)$ denotes the mode-$k$ tensorization, i.e., the reverse operator of $\mathcal M_k(\cdot)$.''',[8],[2,3,4],[r'\mathbb M_{\mathbf r}',r'P_{T_{\mathcal X}}(\mathcal Z)'],'Exact-rank smooth manifold and its Euclidean tangent projection. Main-text equation5 is retained; explicit tangent-space parameterization and mode-ordering details are deferred to SupplementB. The bounded-rank set is not silently called smooth. Orthogonal projectors/complements are ambient A1/A4.','Section 2.1 — Fixed-rank manifold and tangent projection (4)–(5)')
add(8,'adjoint map',r'''First, by the definition of the adjoint map, $\mathscr A^*:\mathbb R^{n\times p_{d+1}\times\cdots\times p_{d+m}}\to\mathbb R^{p_1\times\cdots\times p_{d+m}}$ satisfies $\langle\mathscr A(\mathcal Z_1),\mathcal Z_2\rangle=\langle\mathcal Z_1,\mathscr A^*(\mathcal Z_2)\rangle$ for any $\mathcal Z_1\in\mathbb R^{p_1\times\cdots\times p_{d+m}},\mathcal Z_2\in\mathbb R^{n\times p_{d+1}\times\cdots\times p_{d+m}}$. Simple manipulation yields:
\[
\mathscr A^*(\mathcal Z_2)_{[k_1,\ldots,k_d,j_1,\ldots,j_m]}=\sum_{i=1}^n\mathcal Z_{2[i,j_1,\ldots,j_m]}\mathcal A_{i[k_1,\ldots,k_d]}.
\]''',[20],[1],[r'\mathscr A^*(\mathcal Z_2)',r'\langle\mathscr A(\mathcal Z_1),\mathcal Z_2\rangle'],'Euclidean adjoint of the sample contraction operator, with complete coordinate formula from the main-text implementation section. It does not impose TRIP or a Gaussian model.','Section 7 — Adjoint map')
add(9,'stepsize',r'''where the stepsize $\alpha_t$ is chosen as the local steepest descent direction with a closed form as
\[
\alpha_t:=\underset{\alpha\in\mathbb R}{\operatorname{arg\,min}}\frac12\|\mathcal Y-\mathscr A(\mathcal X^t-\alpha P_{T_{\mathcal X^t}}\mathscr A^*(\mathscr A(\mathcal X^t)-\mathcal Y))\|_{\mathrm F}^2
=\frac{\|P_{T_{\mathcal X^t}}(\mathscr A^*(\mathscr A(\mathcal X^t)-\mathcal Y))\|_{\mathrm F}^2}{\|\mathscr A P_{T_{\mathcal X^t}}(\mathscr A^*(\mathscr A(\mathcal X^t)-\mathcal Y))\|_{\mathrm F}^2}.
\]
(6)''',[9],[1,7,8],[r'\alpha_t',r'\underset{\alpha\in\mathbb R}{\operatorname{arg\,min}}'],'RGD local exact-line-search ratio, not an arbitrary fixed step. The zero-gradient 0/0 case is not assigned a convention by this display; retain the source ambiguity.','Section 2.2 — RGD stepsize (6)')
add(10,'retractions',r'''We can apply two types of computationally efficient retractions to bring $\mathcal X^{t+0.5}$ back to $\mathbb M_{\mathbf r}$: truncated high-order singular value decomposition (T-HOSVD) (De Lathauwer et al., 2000a) or sequentially truncated high-order singular value decomposition (ST-HOSVD) (Vannieuwenhoven et al., 2012). The pseudocode of T-HOSVD and ST-HOSVD are given in Algorithms 6 and 7 in Supplement A, respectively.''',[9],[7],[r'\mathbb M_{\mathbf r}'],'Named tensor retractions from main-text prose. Algorithms6/7 are in the excluded supplement, so their full pseudocode and any tie/rank-deficient conventions are unresolved; do not substitute best Tucker approximation. Matrix P_r is separately defined in the main text.','Section 2.2 — Retractions and excluded algorithm references',kind='source_passage',phrases=['T-HOSVD','ST-HOSVD'])
add(11,'Riemannian Gradient Descent/Gauss-Newton',r'''1: Input: $\mathcal Y\in\mathbb R^{n\times p_{d+1}\times\cdots\times p_{d+m}}$, $\mathcal A_1,\ldots,\mathcal A_n\in\mathbb R^{p_1\times\cdots\times p_d}$, $t_{\max}$, input Tucker rank $\mathbf r$, and initialization $\mathcal X^0$ of Tucker rank $\mathbf r$.
2: for $t=0,1,\ldots,t_{\max}-1$ do
3: (RGD Update) Compute $\mathcal X^{t+0.5}=\mathcal X^t-\alpha_tP_{T_{\mathcal X^t}}\mathscr A^*(\mathscr A(\mathcal X^t)-\mathcal Y)$, where $\alpha_t$ is given in (6).
(RGN Update) Solve the least squares problem
\[
\mathcal X^{t+0.5}=\underset{\mathcal X\in T_{\mathcal X^t}\mathbb M_{\mathbf r}}{\operatorname{arg\,min}}\frac12\|\mathcal Y-\mathscr A P_{T_{\mathcal X^t}}(\mathcal X)\|_2^2.
\]
(8)
4: Update $\mathcal X^{t+1}=\mathcal H_{\mathbf r}(\mathcal X^{t+0.5})$. Here $\mathcal H_{\mathbf r}(\cdot)$ is the retraction map onto $\mathbb M_{\mathbf r}$, e.g., ST-HOSVD and T-HOSVD.
5: end for
6: Output: $\mathcal X^{t_{\max}}$.''',[10],[1,2,7,8,9,10],[r'\mathcal X^{t+0.5}',r'\mathcal H_{\mathbf r}'],'Both branches of Algorithm1, with exact input, iterations, tangent least-squares step and retraction. Theorem1 selects RGD and Theorem2 RGN; a shared algorithm entry does not assert that the RGN branch uses the RGD stepsize. Retain equation8’s printed 2-norm on tensor responses and the exact-rank/bounded-rank issue.','Algorithm 1 — Riemannian Gradient Descent/Gauss-Newton',context='Algorithm 1 Riemannian Gradient Descent/Gauss-Newton for (Over-parameterized) Tensor-on-Tensor Regression')
add(12,'Tensor Restricted Isometry Property',r'''Let $\mathscr A:\mathbb R^{p_1\times\cdots\times p_{d+m}}\to\mathbb R^{n\times p_{d+1}\times\cdots\times p_{d+m}}$ be a linear map. For a fixed $(d+m)$-tuple $\mathbf r=(r_1,\ldots,r_{d+m})$ with $1\le r_k\le p_k$, define the $\mathbf r$-tensor restricted isometry constant to be the smallest number $R_{\mathbf r}$ such that $(1-R_{\mathbf r})\|\mathcal Z\|_{\mathrm F}^2\le\|\mathscr A(\mathcal Z)\|_{\mathrm F}^2\le(1+R_{\mathbf r})\|\mathcal Z\|_{\mathrm F}^2$ holds for all $\mathcal Z$ of Tucker rank at most $\mathbf r$. If $0\le R_{\mathbf r}<1$, we say $\mathscr A$ satisfies $\mathbf r$-tensor restricted isometry property ($\mathbf r$-TRIP).''',[10],[2],[r'R_{\mathbf r}',r'0\le R_{\mathbf r}<1'],'Restricted isometry for every tensor of bounded Tucker rank. Definition uses an arbitrary linear map, not necessarily sampled Gaussian regression. Later ranks2r and2r+r* may exceed the printed r_k≤p_k range; extension convention remains explicit as a source issue.','Definition 1 — Tensor Restricted Isometry Property (TRIP)',context='Definition 1 (Tensor Restricted Isometry Property (TRIP))')
add(13,'least singular values',STATEMENTS[0].split('where ',1)[1].split(' In addition',1)[0],[10],[2,3],[r'\lambda:=\min_{k=1,\ldots,d+m}\sigma_{r_k^*}(\mathcal M_k(\mathcal X^*))'],'Signal strength is the minimum of the true-rank nonzero singular values over all unfoldings, not the r_kth singular value at the possibly oversized input rank. Referencing lambda does not import the additional hypotheses of Theorem1.','Theorem 1 — Signal strength definition',kind='theorem_excerpt')
add(14,'Gaussian ensemble design',r'''We say the tensor-on-tensor regression (1) is generated from the Gaussian ensemble design if $\{\mathcal A_i\}_{i=1}^n$ and $\{\mathcal E_i\}_{i=1}^n$ are generated independently, $\mathcal A_i$ has i.i.d. $N(0,1/n)$ entries, and $\mathcal E_i$ has i.i.d. $N(0,\sigma^2/n)$ entries.''',[12],[1],[r'N(0,1/n)',r'N(0,\sigma^2/n)'],'Independent Gaussian design/noise with sample-size normalization1/n andsigma²/n. It is distinct from the unit-variance low-degree testing model in Section5.','Definition 2 — Tensor-on-tensor Regression Under Gaussian Ensemble Design')
add(15,'scalar-on-tensor regression',r'''The scalar-on-tensor regression corresponds to the general tensor-on-tensor regression model (1) with $m=0$. It can be written as
\[
\mathbf y=\mathscr A(\mathcal X^*)+\boldsymbol\varepsilon,\quad\text{or }y_i=\langle\mathcal A_i,\mathcal X^*\rangle+\varepsilon_i,\ i\in[n].
\]
(10)
Here, $\mathbf y\in\mathbb R^n$ are observations, $\boldsymbol\varepsilon\in\mathbb R^n$ are unknown noise, and $\mathcal X^*\in\mathbb R^{p_1\times\cdots\times p_d}$ is an order-$d$ Tucker rank $\mathbf r^*$ tensor that links response $y_i$ to tensor covariates $\mathcal A_i$, which is the parameter of interest. $\mathscr A(\mathcal X^*)=(\langle\mathcal A_1,\mathcal X^*\rangle,\ldots,\langle\mathcal A_n,\mathcal X^*\rangle)^\top$.''',[13],[1,2],[r'm=0',r'\mathbf y=\mathscr A(\mathcal X^*)+\boldsymbol\varepsilon'],'Scalar responses, Tucker-rank tensor coefficient and full contraction operator. Theorem5 separately adds the Gaussian design. Theorem9 rebinds its complete testing distributions instead of inheriting Definition2.','Section 4.1 — Scalar-on-tensor regression (10)',kind='source_passage')
add(16,'Initialization',r'''1: Input: $y_i\in\mathbb R$, $\mathcal A_i\in\mathbb R^{p_1\times\cdots\times p_d}$ for $i=1,\ldots,n$ and input Tucker rank $\mathbf r=(r_1,\ldots,r_d)$.
2: Calculate $\widehat{\mathbf U}_k^0=\operatorname{SVD}_{r_k}(\mathcal M_k(\mathscr A^*(\mathbf y)))$, $k=1,\ldots,d$.
3: For $k=1$ to $d$, apply one-iteration HOOI, i.e., calculate
\[
\widehat{\mathbf U}_k^1=\operatorname{SVD}_{r_k}(\mathcal M_k(\mathscr A^*(\mathbf y)\times_{j<k}(\widehat{\mathbf U}_j^0)^\top\times_{j>k}(\widehat{\mathbf U}_j^0)^\top)).
\]
Recall $\operatorname{SVD}_r(\cdot)$ returns the matrix composed of the leading $r$ left singular vectors of matrix “$\cdot$”.
4: Output: $\mathcal X^0=\mathscr A^*(\mathbf y)\times_{k=1}^d\widehat{\mathbf U}_k^1(\widehat{\mathbf U}_k^1)^\top$.''',[13],[3,4,8,15],[r'\widehat{\mathbf U}_k^0',r'\widehat{\mathbf U}_k^1'],'Full scalar-on-tensor spectral initialization. Both j<k and j>k factors are printed with superscript0, so no sequential superscript1 substitution is made. The algorithm does not require its theorem guarantee to be defined.','Algorithm 2 — Initialization for (Over-parameterized) Scalar-on-tensor Regression',context='Algorithm 2 Initialization for (Over-parameterized) Scalar-on-tensor Regression')
add(17,'tensor-on-vector regression',r'''In this section, we consider the tensor-on-vector regression model:
\[
\mathcal Y_i=\mathcal X^*\times_1\mathbf a_i^\top+\mathcal E_i,\quad\text{for }i=1,\ldots,n,
\]
(11)
where $\mathcal Y_i,\mathcal E_i\in\mathbb R^{p_2\times\cdots\times p_{m+1}}$ are the observation and noise, $\mathcal X^*\in\mathbb R^{p_1\times\cdots\times p_{m+1}}$ is the parameter tensor of interest with Tucker rank $\mathbf r^*$ and $\mathbf a_i\in\mathbb R^{p_1}$ is the covariate vector. We can also write the model compactly as $\mathcal Y=\mathcal X^*\times_1\mathbf A+\mathcal E$ where $\mathcal Y,\mathcal E\in\mathbb R^{n\times\cdots\times p_{m+1}}$, $\mathcal Y_{[i,:,\ldots,:]}=\mathcal Y_i$, $\mathcal E_{[i,:,\ldots,:]}=\mathcal E_i$ and $\mathbf A=[\mathbf a_1,\ldots,\mathbf a_n]^\top\in\mathbb R^{n\times p_1}$ is the collection of covariate vectors.''',[14],[1,2,4],[r'\mathcal X^*\times_1\mathbf a_i^\top',r'\mathbf A=[\mathbf a_1,\ldots,\mathbf a_n]^\top'],'Vector covariates d=1 and m response modes. Preserve the source’s abbreviated stacked dimension n×...×p_{m+1}. Gaussian scaling remains a separate condition.','Section 4.2 — Tensor-on-vector regression (11)',kind='source_passage')
add(18,'Initialization',r'''1: Input: $\mathcal Y_i\in\mathbb R^{p_2\times\cdots\times p_{m+1}}$, $\mathbf a_i\in\mathbb R^{p_1}$ for $i=1,\ldots,n$ and input Tucker rank $\mathbf r=(r_1,\ldots,r_{m+1})$.
2: Compute the QR decomposition of $\mathbf A$ and denote it by $\mathbf Q_{\mathbf A}\mathbf R_{\mathbf A}$.
3: Calculate $\widehat{\mathbf U}_k^0=\operatorname{SVD}_{r_k}(\mathcal M_k(\mathcal Y\times_1\mathbf Q_{\mathbf A}^\top))$, $k=1,\ldots,m+1$.
4: For $k=1$ to $m+1$, apply one-iteration HOOI, i.e., calculate
\[
\widehat{\mathbf U}_k^1=\operatorname{SVD}_{r_k}(\mathcal M_k((\mathcal Y\times_1\mathbf Q_{\mathbf A}^\top)\times_{j<k}(\widehat{\mathbf U}_j^0)^\top\times_{j>k}(\widehat{\mathbf U}_j^0)^\top)).
\]
5: Compute $\widetilde{\mathcal X}^0=(\mathcal Y\times_1\mathbf Q_{\mathbf A}^\top)\times_{k=1}^{m+1}\widehat{\mathbf U}_k^1(\widehat{\mathbf U}_k^1)^\top$.
6: Return $\mathcal X^0=\widetilde{\mathcal X}^0\times_1\mathbf R_{\mathbf A}^{-1}$.
7: Output: $\mathcal X^0$.''',[14],[3,4,17],[r'\mathbf Q_{\mathbf A}^\top',r'\mathbf R_{\mathbf A}^{-1}'],'QR-whitened tensor-on-vector initialization and inverse-R transformation back to the coefficient space. Requires a suitable full-column-rank QR for the inverse to exist; Gaussian n≥p1 context is recorded, not added to the original pseudocode. Old0 factors are used on both sides of each HOOI update.','Algorithm 3 — Initialization for (Over-parameterized) Tensor-on-vector Regression',context='Algorithm 3 Initialization for (Over-parameterized) Tensor-on-vector Regression')
add(19,'Matrix Trace Regression',r'''In this model, we observe
\[
y_i=\langle\mathbf A_i,\mathbf X^*\rangle+\varepsilon_i,\quad i=1,\ldots,n;\quad\text{or }\mathbf y=\mathscr A(\mathbf X^*)+\boldsymbol\varepsilon,
\]
(12)
where $\mathbf y,\boldsymbol\varepsilon\in\mathbb R^n$ are observations and unknown noise and $\mathbf X^*\in\mathbb R^{p_1\times p_2}$ is a rank $r^*$ parameter matrix of interest.''',[14],[1],[r'\langle\mathbf A_i,\mathbf X^*\rangle',r'\mathbf X^*\in\mathbb R^{p_1\times p_2}'],'Matrix trace regression with scalar rank r,r*; not a positive-semidefinite-only model. Its retraction and sharper Corollary1 initialization thresholds are retained separately.','Section 4.3 — Matrix Trace Regression (12)',kind='source_passage',context='4.3. Matrix Trace Regression.')
add(20,'matrix projection operator',r'''In matrix trace regression, we can take the retraction map $\mathcal H_{\mathbf r}$ in RGD and RGN as the best rank $r$ matrix projection operator: $\mathcal P_r(\mathbf B)=\mathbf U_{[:,1:r]}\boldsymbol\Sigma_{[1:r,1:r]}\mathbf V_{[:,1:r]}^\top$, where $\mathbf B=\mathbf U\boldsymbol\Sigma\mathbf V^\top$ is the SVD. Different from the low-rank projection for tensor of order 3 or higher, $\mathcal P_r$ can be computed efficiently by truncated SVD.''',[14],[3],[r'\mathcal P_r(\mathbf B)',r'\mathbf U_{[:,1:r]}\boldsymbol\Sigma_{[1:r,1:r]}\mathbf V_{[:,1:r]}^\top'],'Truncated-SVD reconstructed matrix, distinct from SVD_r returning a basis and from the general best Tucker approximation. This is the chosen matrix retraction and initialization operator in Theorem7.','Section 4.3 — Best-rank matrix projection')
add(21,'Rank-1 Tensor-on-tensor Regression',r'''In this section, we introduce a modified initialization scheme with theoretical guarantees for general $d$ and $m$ when $\mathcal X^*$ is a rank-1 tensor and input rank is also 1. For simplicity, we assume $n$ is even. Suppose $\mathcal X^*=\lambda\mathbf u_1\circ\mathbf u_2\circ\cdots\circ\mathbf u_{d+m}\in\mathbb R^{p_1\times\cdots\times p_{d+m}}$, where “$\circ$” denotes the outer product of vectors. Then in this special setting, the model (1) can be rewritten as
\[
\mathcal Y_i=\lambda\langle\mathcal A_i,\mathbf u_1\circ\cdots\circ\mathbf u_d\rangle\mathbf u_{d+1}\circ\cdots\circ\mathbf u_{d+m}+\mathcal E_i.
\]
(13)
Let $\mathcal Y^1$ and $\mathcal Y^2$ collect $\mathcal Y_i$s in the first and second halves of the data: $\mathcal Y^1_{[i,:,\ldots,:]}=\mathcal Y_i$ and $\mathcal Y^2_{[i,:,\ldots,:]}=\mathcal Y_{n/2+i}$ for $i=1,\ldots,n/2$.''',[16],[1],[r'\mathcal X^*=\lambda\mathbf u_1\circ\mathbf u_2\circ\cdots\circ\mathbf u_{d+m}',r'\mathcal Y^1_{[i,:,\ldots,:]}'],'Rank-one coefficient and rank-one input with even sample size for splitting. Lambda is the factor amplitude in13; the earlier signal-strength convention implies unit-normalized factors are intended, but the local display does not explicitly state each norm. Preserve this gap rather than invent a source condition.','Section 4.4 — Rank-1 Tensor-on-tensor Regression (13)',kind='source_passage',context='4.4. Rank-1 Tensor-on-tensor Regression.')
add(22,'Initialization',r'''1: Input: $\mathcal Y_i\in\mathbb R^{p_{d+1}\times\cdots\times p_{d+m}}$, $\mathcal A_i\in\mathbb R^{p_1\times\cdots\times p_d}$ for $i=1,\ldots,n$.
2: Calculate $\widetilde{\mathbf u}_k^0=\operatorname{SVD}_1(\mathcal M_{k-d+1}(\mathcal Y^1))$, $k=d+1,\ldots,d+m$.
3: Compute $y'_i=\langle\mathcal Y_i,\widetilde{\mathbf u}_{d+1}^0\circ\cdots\circ\widetilde{\mathbf u}_{d+m}^0\rangle$ for $i=n/2+1,\ldots,n$.
4: Calculate $\widetilde{\mathbf u}_k^0=\operatorname{SVD}_1(\mathcal M_k(\sum_{i=n/2+1}^n y'_i\mathcal A_i))$, $k=1,\ldots,d$.
5: For $k=1$ to $d+m$, apply one-iteration HOOI, i.e., calculate
\[
\widetilde{\mathbf u}_k^1=\operatorname{SVD}_1(\mathcal M_k(\mathscr A^*(\mathcal Y)\times_{j<k}(\widetilde{\mathbf u}_j^0)^\top\times_{j>k}(\widetilde{\mathbf u}_j^0)^\top)).
\]
6: Output: $\mathcal X^0=\mathscr A^*(\mathcal Y)\times_{k=1}^{d+m}\widetilde{\mathbf u}_k^1(\widetilde{\mathbf u}_k^1)^\top$.''',[16],[3,4,8,21],[r'\mathcal M_{k-d+1}(\mathcal Y^1)',r'y\prime_i',r'\widetilde{\mathbf u}_k^1'],'Full rank-one sample-split initialization: response factors from first half; projected response/covariate factors from second half; final update using all data. The source updates both sides using old0 vectors.','Algorithm 4 — Initialization for Rank-1 Tensor-on-tensor Regression',context='Algorithm 4 Initialization for Rank-1 Tensor-on-tensor Regression')
members['D22']['highlight_symbols']=[r'\mathcal M_{k-d+1}(\mathcal Y^1)',r'\widetilde{\mathbf u}_k^1']
add(23,'hypothesis testing',r'''Without loss of generality, we assume $\varepsilon_i\overset{i.i.d.}{\sim}N(0,\sigma^2)$ with $0\le\sigma^2<1$, $\mathcal A_i\overset{i.i.d.}{\sim}N(0,1)$ and $\|\mathcal X^*\|_{\mathrm F}+\sigma^2=1$ in establishing the computational lower bound for scalar-on-tensor regression (10) (see Supplement G.1 for a proof). We also consider the setting $p_1=\cdots=p_d=p$ and $r_1^*=\cdots=r_d^*=r^*$ throughout this section.
We consider a canonical hypothesis testing formulation of scalar-on-tensor regression:
\[
H_0:\{(y_i,\operatorname{vec}(\mathcal A_i))\}_{i=1}^n\overset{i.i.d.}{\sim}N(0,\mathbf I_{1+p^d}),
\]
\[
H_1:\{(y_i,\operatorname{vec}(\mathcal A_i))\}_{i=1}^n:\mathcal X^*=\sqrt{1-\sigma^2}\mathbf x^{*\otimes d},
\]
\[
\mathbf x^*=(x_1^*,\ldots,x_p^*),\ x_j^*\overset{i.i.d.}{\sim}\operatorname{Uniform}(\{p^{-1/2},-p^{-1/2}\});
\]
\[
\text{for }i\in[n],\mathcal A_i\overset{i.i.d.}{\sim}N(0,1),y_i\text{ is i.i.d. generated}
\]
\[
\text{via }y_i=\langle\mathcal X^*,\mathcal A_i\rangle+\varepsilon_i,\ \varepsilon_i\overset{i.i.d.}{\sim}N(0,\sigma^2).
\]
(14)''',[17],[],[r'H_0',r'H_1',r'\sqrt{1-\sigma^2}\mathbf x^{*\otimes d}'],'Complete main-text null and planted symmetric rank-one alternative for low-degree testing. Covariate variance1 is distinct from Definition2 variance1/n. A common sampled signal couples observations under H1; iid is naturally conditional on this signal. Preserve the unsquared norm in the preceding normalization, which conflicts with the displayed square-root amplitude.','Section 5 — Hypothesis test (14)',kind='source_passage')
add(24,'initialization',r'''the initialization $\mathcal X^0$ satisfies $\|\mathcal X^0-\mathcal X^*\|_{\mathrm F}\le\frac{R_{2\mathbf r}}{(d+m)(1+R_{2\mathbf r+\mathbf r^*}-R_{2\mathbf r})}\lambda$''',[10],[12,13],[r'\frac{R_{2\mathbf r}}{(d+m)(1+R_{2\mathbf r+\mathbf r^*}-R_{2\mathbf r})}\lambda'],'Exact RGD initialization-distance condition from Theorem1. Theorems5,6,8 promise this condition; it is an output property, not an additional assumed initialization. RGD’s separate TRIP upper/signal lower conditions are archived as auxiliary context.','Theorem 1 — Initialization condition',kind='theorem_excerpt')
add(25,'initialization',r'''the initialization $\mathcal X^0$ satisfies $\|\mathcal X^0-\mathcal X^*\|_{\mathrm F}\le\frac{1-R_{2\mathbf r}}{4(d+m)(\sqrt{d+m}+1)(1+R_{2\mathbf r+\mathbf r^*}-R_{2\mathbf r})}\lambda$''',[11],[12,13],[r'\frac{1-R_{2\mathbf r}}{4(d+m)(\sqrt{d+m}+1)(1+R_{2\mathbf r+\mathbf r^*}-R_{2\mathbf r})}\lambda'],'Exact RGN initialization-distance condition from Theorem2, distinct from Theorem1’s threshold. Theorems5,6,8 guarantee it; do not transfer RGD-specific additional assumptions into Theorem2.','Theorem 2 — Initialization condition',kind='theorem_excerpt')
add(27,'initialization',r'''(RGD) Suppose the initialization $\mathbf X^0$ satisfies $\|\mathbf X^0-\mathbf X^*\|_{\mathrm F}\le\frac{R_{2r}}{(1+R_{2r+r^*}-R_{2r})}\sigma_{r^*}(\mathbf X^*)$.''',[15],[3,12],[r'\frac{R_{2r}}{(1+R_{2r+r^*}-R_{2r})}\sigma_{r^*}(\mathbf X^*)'],'Sharper matrix RGD initialization threshold explicitly referenced by Theorem7. Its guarantee does not assume an initializer is already close. Scalar rank notation specializes TRIP to matrix RIP; separate additional Corollary1 conditions are auxiliary context.','Corollary 1 — RGD initialization condition',kind='theorem_excerpt')
add(28,'initialization',r'''(RGN) If the initialization $\mathbf X^0$ satisfies $\|\mathbf X^0-\mathbf X^*\|_{\mathrm F}\le\frac{1-R_{2r}}{8(1+R_{2r+r^*}-R_{2r})}\sigma_{r^*}(\mathbf X^*)$.''',[15],[3,12],[r'\frac{1-R_{2r}}{8(1+R_{2r+r^*}-R_{2r})}\sigma_{r^*}(\mathbf X^*)'],'Sharper matrix RGN initialization threshold explicitly referenced by Theorem7. Preserve denominator8, not the general tensor theorem’s dimension-dependent factor.','Corollary 1 — RGN initialization condition',kind='theorem_excerpt')
add(29,'One-iteration Higher-Order Orthogonal Iteration',r'''1: Input: $\widetilde{\mathcal T}\in\mathbb R^{p_1\times\cdots\times p_d}$, initialization $\widetilde{\mathbf U}_k^0\in\mathbb O_{p_k,r_k}$, $k=1,\ldots,d$, input Tucker rank $\mathbf r=(r_1,\ldots,r_d)$.
2: For $k=1$ to $d$, update $\widetilde{\mathbf U}_k^1=\operatorname{SVD}_{r_k}(\mathcal M_k(\widetilde{\mathcal T}\times_{j<k}(\widetilde{\mathbf U}_j^0)^\top\times_{j>k}(\widetilde{\mathbf U}_j^0)^\top))$.
3: Output: $\widehat{\mathcal T}=\widetilde{\mathcal T}\times_{k=1}^d P_{\widetilde{\mathbf U}_k^1}$.''',[20],[2,3,4],[r'\widetilde{\mathbf U}_k^1',r'P_{\widetilde{\mathbf U}_k^1}'],'Original deterministic OHOOI algorithm. Both sides use old0 subspaces as printed. Its definition takes tensor data, ranks and initial orthonormal subspaces; no regression/Gaussian/TRIP premise enters Theorem10.','Algorithm 5 — One-iteration Higher-Order Orthogonal Iteration (OHOOI)',context='Algorithm 5 One-iteration Higher-Order Orthogonal Iteration (OHOOI)')
add(30,'Estimators with Small Loss',STATEMENTS[2].split(' Then ',1)[0],[12],[1,2,12],[r'\operatorname{Tucrank}(\widehat{\mathcal X})\le\mathbf r',r'\|\mathcal Y-\mathscr A(\widehat{\mathcal X})\|_{\mathrm F}^2'],'Theorem4’s phrase estimator in Theorem3 refers to bounded-rank estimators with loss no larger than true loss, under2rTRIP. This source excerpt preserves that qualification; it does not restrict the estimator to RGD/RGN or assume initialization. The minimax lower branch quantifies all estimators separately.','Theorem 3 — Estimator qualification referenced by Theorem 4',kind='theorem_excerpt',context='Theorem 3 (Upper Bound for Estimators with Small Loss and Global Minimizers)')
# Add source model qualifiers to algorithm names, without inventing umbrella names.
for n,term in [(16,'Scalar-on-tensor Regression'),(18,'Tensor-on-vector Regression'),(22,'Rank-1 Tensor-on-tensor Regression')]:
    m=members['D'+str(n)];x=next(x for x in interfaces if x['members'][0] is m);ctx=m['naming_context'][0]
    assert term in ctx['text']
    x['source_keywords'].append(dict(paper_id=PID,local_id=m['local_id'],source_text=term,label=term,kind='term',context_id=ctx['context_id']))
    x['name']=' · '.join(k['label'] for k in x['source_keywords'])
m=members['D5'];ctx='Different from the low-rank projection for tensor of order 3 or higher, $\\mathcal P_r$ can be computed efficiently by truncated SVD.'
m['naming_context']=[dict(context_id='D5/name',text=ctx,evidence=[dict(page=14,location='Comparison of tensor projection with matrix truncated SVD')])]
x=next(x for x in interfaces if x['members'][0]['local_id']=='D5')
x['source_keywords']=[dict(paper_id=PID,local_id='D5',source_text='low-rank projection',label='Low-rank projection',kind='term',context_id='D5/name')]
x['name']='Low-rank projection'
# Preserve the full algorithm separately, while indexing each actual branch.
ALGORITHM_ONE=members['D11']['statement_original']
prefix,branches=ALGORITHM_ONE.split('3: (RGD Update)',1)
rgd,rest=branches.split('(RGN Update)',1)
rgn,tail=rest.split('4: Update',1)
# The common retraction is a bound algorithm argument; named tensor choices are D10,
# and the explicitly chosen matrix reconstruction is D20.
tail=tail.replace(', e.g., ST-HOSVD and T-HOSVD.', '.')
members['D11']['statement_original']=prefix+'3: (RGD Update)'+rgd+'4: Update'+tail
members['D11']['depends_on']=['D1','D2','D7','D8','D9']
members['D11']['local_label']=members['D11']['source_heading']='Algorithm 1 — RGD branch and common input/output'
x=next(x for x in interfaces if x['members'][0]['local_id']=='D11')
x['source_keywords'][0].update(source_text='Riemannian Gradient Descent',label='Riemannian Gradient Descent')
x['name']='Riemannian Gradient Descent'
x['semantic_boundary']=x['type_shape']='Algorithm1 RGD branch with the common retraction parameter. The alternative RGN branch is omitted from this excerpt, and the full original algorithm is preserved in auxiliary context. Tensor retraction choices D10 and the matrix P_r choice D20 are resolved per theorem, not implicitly imposed on every specialization.'
add(31,'Gauss-Newton',prefix+'(RGN Update)'+rgn+'4: Update'+tail,[10],[1,2,7],[r"\mathcal X^{t+0.5}",r"\mathcal H_{\mathbf r}"],'Algorithm1 RGN branch with common input/output and a bound retraction. It solves the tangent least-squares problem and does not use the RGD line-search ratio. The complete two-branch original is auxiliary context; named tensor versus matrix retractions are resolved at each theorem.','Algorithm 1 — RGN branch and common input/output',context='Algorithm 1 Riemannian Gradient Descent/Gauss-Newton for (Over-parameterized) Tensor-on-Tensor Regression')
members['D30']['depends_on'].append('D6')
def main():
    (ROOT/'source-passages.json').write_text(json.dumps(dict(paper_id=PID,members=list(members.values())),indent=2,ensure_ascii=False)+'\n')
    (ROOT/'interface-extraction.json').write_text(json.dumps(dict(paper_id=PID,interfaces=interfaces),indent=2,ensure_ascii=False)+'\n')
if __name__=='__main__':main()
