"""Keep source conventions, guarantee references and unresolved main-text ambiguities."""
import json
from save_inventory import ROOT,PID,STATEMENTS
from extract_interfaces import ALGORITHM_ONE

def main():
    aux=[]
    def add(n,s,pages,note,deps=()):aux.append(dict(local_id='A'+str(n),statement_original=s,evidence=[dict(page=p,location='Original main-text context A'+str(n)) for p in pages],scope_note=note,depends_on=list(deps)))
    add(1,r'''$\mathbf I_r$ represents the $r$-by-$r$ identity matrix. Let $\mathbb O_{p,r}=\{\mathbf U\in\mathbb R^{p\times r}:\mathbf U^\top\mathbf U=\mathbf I_r\}$ and for any $\mathbf U\in\mathbb O_{p,r}$, denote $P_{\mathbf U}=\mathbf U\mathbf U^\top$.''',[7],'Original orthonormal-frame and orthogonal-projector definitions, retained as ambient notation without inventing a source natural-language Stiefel title. Used by best Tucker approximation, geometry and OHOOI. No availability claim is made.')
    add(2,r'''To this end, we adopt a rank over-parameterization scheme: we introduce a conservative guess of rank $\mathbf r:=(r_1,\ldots,r_d,r_{d+1},\ldots,r_{d+m})\ge(r_1^*,\ldots,r_d^*,r_{d+1}^*,\ldots,r_{d+m}^*)$ and solve the following tensor-on-tensor regression under the possibly over-parameterized regime:''',[3],'Standing componentwise input rank at least true rank, including the feasible-true-parameter convention for Theorem3. Theorem9 rebinds its rank-one testing distribution; Theorem10 states its own rank inequality.',['D2','D6'])
    add(3,ALGORITHM_ONE,[10],'Full original Algorithm1, including both alternatives and named retraction examples. D11 and D31 select the RGD and RGN branches, with common input/output; this full source remains intact and is not silently rewritten.',['D1','D2','D7','D8','D9','D10'])
    add(4,r'''Then the projection operator onto $\mathbf U_{k\perp}^t$, the orthogonal complement of $\mathbf U_k^t$, satisfies
\[
P_{\mathbf U_{k\perp}^t}=\mathbf I_{p_k}-P_{\mathbf U_k^t}=\mathbf I_{p_k}-P_{\overline{\mathbf U}_k^t}-P_{\check{\mathbf U}_k^t}=(\mathbf I_{p_k}-P_{\overline{\mathbf U}_k^t})(\mathbf I_{p_k}-P_{\check{\mathbf U}_k^t}).
\]
(17)''',[19],'Original orthogonal-complement convention. The barred/check decomposition is separately A5. Theorem10 applies a complement to the ESTIMATED initial subspace, not the true factor. This notation passage is not an import of the proof lemma that follows.')
    add(5,r'''for any $k\in[d+m]$, the mode-$k$ singular subspace of $\mathcal X^t$, denoted by $\mathbf U_k^t$, can be decomposed as $\mathbf U_k^t=[\overline{\mathbf U}_k^t\ \check{\mathbf U}_k^t]$ where $\overline{\mathbf U}_k^t$ is composed of the first $r_k^*$ columns of $\mathbf U_k^t$ and $\check{\mathbf U}_k^t$ is composed of the rest of the $(r_k-r_k^*)$ columns of $\mathbf U_k^t$.''',[19],'Only the source notation accompanying the orthogonal-complement identity A4. Its use in a proof does not add a dependency of every theorem on Lemma3.',['D2','D3'])
    add(6,STATEMENTS[0].split(' In addition, ',1)[1].split(' Then for all',1)[0],[10],'Theorem1’s separate RGD TRIP upper and signal-to-noise lower bounds. These are assumed in T1 and are not transferred into T2 merely because lambda is defined there. The initialization conditions promised in T5/T6/T8 are separately D24/D25.',['D5','D8','D12','D13'])
    add(7,r'''Consider the (over-parameterized) matrix trace regression model in (12) with $r\ge r^*$. Let $\mathcal H_r$ be the rank $r$ truncated SVD. Suppose $\mathscr A$ satisfies $2r$-RIP.''',[15],'Corollary1’s surrounding context for the matrix initialization conditions referenced in T7. These hypotheses are distinguished from the closeness property guaranteed for its output.',['D12','D19','D20'])
    add(8,r'''In addition, we assume $R_{2r}\le\frac1{17}$ and $\sigma_{r^*}(\mathbf X^*)\ge\frac{4(1+R_{2r+r^*}-R_{2r})}{R_{2r}(1-R_{2r})}\|(\mathscr A^*(\boldsymbol\varepsilon))_{\max(2r)}\|_{\mathrm F}$.''',[15],'Additional RGD-only Corollary1 conditions, separate from its initialization-distance inequality and RGN branch. Preserve sharper matrix constants.',['D3','D5','D8','D12'])
    add(9,r'''The classic RGD/RGN methods are designed to optimize on smooth manifolds. This corresponds to minimizing the objective function in (3) with the fixed Tucker rank constraint $\operatorname{Tucrank}(\mathcal X)=\mathbf r$ since $\mathbb M_{\mathbf r}$ is a smooth manifold. Note that $\{\mathcal X:\operatorname{Tucrank}(\mathcal X)\le\mathbf r\}$ is not a smooth manifold while such bounded rank constraint is essential to handle over-parameterization, the classic theory no longer applies. Regardless, we propose to continue using Algorithm 1 even with the bounded rank constraint.''',[9],'Remark1 explicitly distinguishes the smooth exact-rank manifold from the bounded-rank feasible set. Do not redefine the latter as smooth or quietly assume rank-deficient tangent/QR choices have been specified.',['D2','D6','D7','D11','D31'])
    add(10,r'''Throughout the paper, let $c(d)$ be a constant that depends on $d$ only, whose actual value varies from line to line; $c_1(m),c_2(d,m)$ are noted similarly. Finally, we denote $\mathscr A^*$ as the adjoint of the linear operator $\mathscr A$.''',[7,8],'Dimension-dependent constants have only the displayed mode-order dependence, not a new dependence on sample size or ambient dimensions. The adjoint is defined explicitly in D8.',['D8'])
    issues=[]
    def issue(i,pages,note):issues.append(dict(issue_id=i,evidence=[dict(page=p,location='Source scope or notation issue') for p in pages],note=note))
    issue('registered-version-and-boundary',[1,26],'Registered source is arXiv2206.08756v3 marked15Jan2024,65pages, submitted-to-AoS preprint. Main text ends with acknowledgements on page26 before REFERENCES y328.151; clip322. All supplementary bodies, starting32, are excluded. No assumption of identity with the published version is made.')
    issue('rgn-time-zero-factor',[11,15],'Theorem2 prints2^(-2^t) for all t≥0, even without noise. At t=0 it implies e0≤e0/2 unless e0=0. The corresponding Corollary1 RGN factor has the same issue. Preserve the original; do not repair the exponent or shift the time range.')
    issue('theorem-four-target',[12],'Theorem4’s upper expected error uses unstarred X although the surrounding true parameter is X*. Its lower bound deliberately ranges over X. Preserve the difference in the inventory; no silent star insertion.')
    issue('theorem-eight-dimension-index',[17],'Theorem8 prints bar-p=max_{k=1,...,d+m} p_i, with mismatched indices. Its df is sum p_i, not the exact rank-one manifold dimension; retain both source expressions.')
    issue('testing-normalization-and-coupling',[17],'Section5 preceding14 prints ||X*||F+sigma²=1, without a square on the norm. Equation14 instead sets X*=sqrt(1-sigma²) x* tensor-power d with unit-norm Rademacher x*, consistent with squared-norm normalization. Preserve both. A common random planted signal couples samples under H1, so the source iid wording is naturally conditional on that signal; explicit independence of the planted signal, designs and errors is not fully spelled out in14.')
    issue('testing-is-low-degree',[17,18],'Theorem9 bounds the alternative expectation of null-centered, null-unit-variance polynomials of total degree at mostD. It does not prove an unconditional lower bound for all polynomial-time algorithms. The surrounding runtime equivalence is conjectural and the testing-to-estimation reduction is in an excluded supplement. Preserve the bound n≤(p/(dD))^(d/2)delta/[2(1-sigma²)] and variance of f, not f squared.')
    issue('rank-and-unfolding-conventions',[7,8,9],'Detailed matricization/mode-product indexing and explicit tangent-space parameterization are deferred to SupplementB. Main-text formulas and dimensions are saved. Admissible nonempty Tucker ranks, singular-value ties and rank-deficient QR choices require conventions beyond the printed definitions; do not silently import an appendix.')
    issue('trip-rank-range',[7,10],'Definition1 states1≤r_k≤p_k, whereas later constants use2r and2r+r*. Best-approximation subspaces also use ranks2r. A capping/extension convention may be needed when these exceed ambient sizes; the source does not specify it in these passages.')
    issue('rgd-zero-step-and-rgn-norm',[9,10,21],'Stepsize6 is0/0 at zero projected gradient unless a stopping or zero-step convention is supplied. Algorithm1 Eq8 prints the2-norm for tensor responses, while the surrounding objective, Lemma2 and Section7 use Frobenius norm. Preserve the print; vectorization equivalence is an interpretation, not a source rewrite.')
    issue('retraction-scope-and-update-order',[9,13,14,16,20],'T-HOSVD/ST-HOSVD pseudocode lies in excluded Algorithms6/7. Main Algorithms2–5 consistently print old superscript0 factors both for j<k and j>k; do not change them to sequential updated factors. Matrix P_r is explicitly defined in the main text and does not need the excluded tensor-retraction pseudocode.')
    issue('rank-one-amplitude-and-qr',[14,16],'Section4.4 introduces rank-one factors and amplitude lambda without explicitly restating unit norms for each u_k; the earlier least-nonzero-singular-value lambda convention suggests normalization but does not state each factor norm here. Algorithm3 uses R_A inverse, requiring full column rank, and Algorithm4 uses even n and two sample halves. These requirements remain documented separately from original theorem wording.')
    issue('iteration-count-domain',[13,14,15,17],'Theorems5–8 print log and loglog iteration thresholds truncated with vee0, using division by sigma and positive signal strength. At sigma=0 or where the inner logarithm is nonpositive, an extended/domain convention is needed; the max with0 does not itself define an undefined log. No corrective convention is inserted.')
    issue('source-references-and-branches',[10,11,12,13,14,15,17,19,20],'T5/T6/T8 reference T1/T2 initialization conditions as guaranteed conclusions; T7 similarly references Corollary1. They do not assume the initializer is already good. T4 references the qualified estimator of T3 only in its upper branch; the minimax lower bound quantifies all estimators. T10 supplies a proof tool for T5/T6, but their theorem statements do not import its perturbation hypothesis.')
    bindings={
'T1':'True tensor X*, true rank r*, input r≥r*, initial X0, all t≥0, lambda and explicit RGD TRIP/signal assumptions are bound in the statement. Model1/2, rank, adjoint, best approximation, Algorithm1 RGD branch and tensor retraction choices are source-resolved. Exact initialization excerpt D24 is used as a property. No Gaussian model is assumed.',
'T2':'Same regression/rank conventions; Algorithm1 RGN branch, initialization D25 and lambda’s object definition fromT1. No RGD stepsize or additional T1 R2r upper/signal lower premise is inherited. Printed t=0 exponent issue retained.',
'T3':'Any estimator Xhat satisfying the printed rank and residual-loss inequality; model and standing r≥r* context A2. No initialization or algorithm requirement. Conclusion uses adjoint noise and best2r approximation.',
'T4':'Gaussian model, df, constants, min dimension and lower parameter space are bound inside the statement. The upper noise norm uses adjoint/best approximation. Only the upper estimator clause refers to T3; the lower minimax infimum remains over all estimators and uses expected unsquared norm.',
'T5':'Scalar-on-tensor specialization, Gaussian law, df, sample condition, high-probability event and log/loglog output thresholds. Algorithm2 returns X0 and guarantees both original initialization properties D24/D25; subsequent RGD and RGN use their distinct branches with tensor retractions.',
'T6':'Tensor-on-vector specialization, Gaussian law, df, sample condition containing+p1, high-probability event and log/loglog output thresholds. Algorithm3’s QR and inverse-R operations retained. Initialization guarantees are conclusions.',
'T7':'Matrix rank r,r*, df=(p1+p2-r)r, sigma_{r*}(X*) and sample condition. X0=P_r(A*(y)); matrix P_r also supplies the retraction. Corollary1’s two sharper closeness properties are output guarantees; no generic tensor T-HOSVD requirement is imported.',
'T8':'Rank-one model13 with even n and input rank1 fromSection4.4; Gaussian law, amplitude/signal convention, df=sum p_i, printed bar-p index mismatch, high-probability event and iteration bounds. Algorithm4 sample splitting preserved; T1/T2 initialization references are guarantees.',
'T9':'Testing distributions14 bind the planted signal and observations. Delta∈(0,1), degreeD, centered/unit-variance polynomial class, sample threshold and expectation supremum are statement-local. Polynomial degree, expectation, variance and vec are ambient. No Gaussian1/n, TRIP or algorithm-init dependency.',
'T10':'Deterministic tildeT,T,Z=tildeT-T, true Tucker decomposition and rankr*, input rankr≥r*, estimated orthonormal frames, operator-norm initial complement bound and final Frobenius error are statement-local. Orthogonal frames/projectors A1 and complement convention A4; OHOOI Algorithm5 and best-r approximation. No regression/Gaussian/TRIP or theorem-initialization premise.'}
    refs=[]
    def ref(claim,target,kind,note):refs.append(dict(claim_id=PID+'/'+claim,target=target,reference_kind=kind,note=note))
    for n in [5,6,8]:
        ref('T'+str(n),'Theorems 1 and 2 — initialization conditions','guarantee_reference','The output initializer is asserted to satisfy D24/D25. These are referenced properties of the conclusion, not extra input assumptions or imports of full theorem conclusions.')
    ref('T7','Corollary 1 — initialization conditions','guarantee_reference','Matrix-specific D27/D28 are the two promised output properties. Corollary1 remains outside the Theorem inventory.')
    ref('T4','Theorem 3 — qualified estimator','estimator_reference','Only the upper-bound estimator clause refers to the rank/loss/TRIP qualification D30. The lower minimax branch remains distinct.')
    for n in [2,5,6,8]:ref('T'+str(n),'Theorem 1 — lambda definition','object_reference','The least true-rank singular-value signal definition is used without importing the additional RGD assumptions.')
    for n in [5,6]:ref('T'+str(n),'Theorem 10','proof_only','Main-text discussion says the perturbation result is used in establishing the theorem. Its hypothesis is not a statement dependency of this statistical theorem.')
    ref('T9','Lemma 4 and Supplement G','proof_only','Hermite calculations, low-degree likelihood-ratio proof and testing-to-estimation reduction support proofs; no supplement body is read or imported.')
    data=dict(paper_id=PID,unranked_auxiliary_passages=aux,statement_local_bindings=bindings,source_claim_references=refs,source_issues=issues,ambient_prerequisites=['Finite real arrays and matrices, componentwise rank inequalities, Frobenius inner product/norm and matrix operator norm, singular values and QR, orthonormal frames and orthogonal complements as archived in A1/A4.','Mode products, contraction and matricization retain the available original definitions; unresolved detailed indexing is explicitly flagged rather than filled from excluded supplements.','Finite-dimensional Gaussian laws, iid/conditional sampling, expectations, probabilities, variances, polynomial total degree, Kronecker/outer products, empirical sample indexing and minimax quantifiers; no mathlib availability assertion.'],validation_limits='A source census preserves statements and dependencies. It does not prove the claims, repair the source, inspect excluded supplements, or perform mathlib search.')
    (ROOT/'ambient-prerequisites.json').write_text(json.dumps(data,indent=2,ensure_ascii=False)+'\n')
if __name__=='__main__':main()
