"""Keep imported hypotheses, denominator definitions, covariance context and source issues."""
import json
from save_inventory import ROOT,PID,STATEMENTS

def main():
    aux=[]
    def add(n,s,pages,note,deps=()):aux.append(dict(local_id='A'+str(n),statement_original=s,evidence=[dict(page=p,location='Original main-text context A'+str(n)) for p in pages],scope_note=note,depends_on=list(deps)))
    add(1,STATEMENTS[0].split('Then, for every')[0].strip(),[7,8],'Exact Theorem5 assumptions imported by Corollary6 and hence Theorem10. They include iid standardized X*, regular variation of index1, Eq3, spectral Theta and u_n→infinity,n/a*(u_n)→infinity. This excerpt excludes the theorem’s own conclusion and covariance.',['D1','D2','D3'])
    add(2,STATEMENTS[1].split('Then we have')[0].strip(),[10],'Exact Theorem8 assumptions imported by Theorem10. Preserve the printed unindexed alpha in X*, Eq3/30 and the intermediate sequence k_n with all-coordinate bias rates. The Gaussian H conclusion is a separate object reference, not another assumption.',['D2','D20','D27'])
    add(3,r'''\[
n^{-1}\sum_{l=1}^n\mathbf1\{\ell_I(X_l/X_{k:n})>1\}
\]''',[9],'Original denominator expression of the displayed Mtilde/Ptilde estimator. The ratio display assigns it the symbol Ptilde_{n,k,I}; for I={i} this is the denominator in Hill equation(33). Only order statistics and ell_I are needed to define it, so the Hill estimator does not depend on the angular moment numerator or on itself. The expression is excerpted without inventing a standalone equality absent from the source.',['D6','D16'])
    add(4,r'''Using the same techniques as in the proof of Cor. 6, one can easily show the joint weak convergence of $(G_n(v,s,\beta,p_1),\widetilde G_n(w,t,\gamma,p_2))_{n\in\mathbb N}$ ($v,s,\beta,p_1$), ($w,t,\gamma,p_2$) in $\partial B_1^+(0)\times A'_\delta\times K$ to $(G(v,s,\beta,p_1),\widetilde G(w,t,\gamma,p_2))$ which are jointly Gaussian. Then for $\beta=\gamma=\mathbf1$, the covariances express as
\[
\operatorname{Cov}(G(v,s,\mathbf1,p_1),\widetilde G(w,t,\mathbf1,p_2))
=\frac{\mathbb E\left[\left(v^\top\frac{s\circ\Theta}{\|s\circ\Theta\|}\right)^{p_1}\left(w^\top\frac{t\circ\Theta}{\|t\circ\Theta\|}\right)^{p_2}(\|s\circ\Theta\|\wedge\|t\circ\Theta\|)\right]}{\mathbb E[\|t\circ\Theta\|]}
\]
\[
-\frac{\mathbb E\left[\left(v^\top\frac{s\circ\Theta}{\|s\circ\Theta\|}\right)^{p_1}(\|s\circ\Theta\|\wedge\|t\circ\Theta\|)\right]\mathbb E\left[\left(w^\top\frac{t\circ\Theta}{\|t\circ\Theta\|}\right)^{p_2}\|t\circ\Theta\|\right]}{(\mathbb E[\|t\circ\Theta\|])^2}.
\]''',[9],'Remark7.2 supplies the G/Gtilde cross covariance required by Theorem10, including the p1=0 restriction G^0. The formula has no extra tau factor after cancellation. Preserve the source’s K domain; zeroth moments are defined in Theorem5 and G^0 immediately before Theorem10. This is original covariance context for D26, not a proof-only dependency or an assumption of independence.',['D3','D5','D10','D22','D23'])
    add(5,r'''\[
\frac{\widetilde M_{n,k,I}(v_I,p)}{\widetilde P_{n,k,I}}=\frac{\widehat M_{n,u_n}(v_I,u_n/X_{k:n}^*\circ\mathbf1_I,\alpha/\widehat\alpha,p)}{\widehat P_{n,u_n}(u_n/X_{k:n}^*\circ\mathbf1_I)}.
\]
(28)''',[9],'Original connection between random-threshold and perturbed deterministic-threshold estimators. It explains the arguments in Theorem10. The primary definition of the random-threshold estimator is already explicit in D17; this representation does not create an extra formula-equality premise. Ratios and powers are coordinatewise.',['D7','D11','D12','D16','D17','D19','D27'])
    add(6,r'''There is a one-to-one correspondence between the normalized exponent measure $\mu^*$ and the distribution of $\Theta$, the so-called (normalized) spectral measure (w.r.t. the norm $\|\cdot\|$) via
\[
\mu^*(\{x\in E:\|x\|>r,x/\|x\|\in B\})=\tau r^{-1}\mathbb P(\Theta\in B),\qquad r>0,\ B\subset S^+_{d-1}
\]
(6)
for some constant $1\le\tau\le d$ given by''',[3],'Original polar disintegration context distinguishes the probability law of Theta from the exponent measure and scale tau. The unit-Pareto law in D3 has survival1/y for y≥1. No exact Pareto law is imposed on the observed X* margins.',['D1','D3','D4'])
    add(7,r'''Then, for every finite set $K_0\subset\mathbb N_0$ and $\delta\ge0$''',[8],'Theorem5 explicitly allows zeroth powers, and has finite K0. Corollary6 uses finite K⊂N but requires bias control for p=0 as well. Theorem10 inherits finiteness of K through its Corollary6 assumption reference, while requiring delta>0.',['D10'])
    add(8,r'''Assume that all the partial derivatives
\[
c_{s_i}(v,s,\beta,p)=\frac\partial{\partial s_i}c(v,s,\beta,p),\qquad i\in\{1,\ldots,d\},p\in K,
\]
\[
c_{\beta_i}(v,s,\beta,p)=\frac\partial{\partial\beta_i}c(v,s,\beta,p),\qquad i\in\{1,\ldots,d\},p\in K,
\]
exist and are continuous on $\partial B_1^+(0)\times A'_\delta$.''',[11],'Exact differentiability clause bound inside Theorem10. No derivative formula from an appendix is imported. The domain is stratified with inactive zero coordinates, so ordinary partial derivatives require an extension or relative interpretation not specified by the printed statement.',['D5','D10','D13'])
    issues=[]
    def issue(i,pages,note):issues.append(dict(issue_id=i,evidence=[dict(page=p,location='Source scope or notation issue') for p in pages],note=note))
    issue('registered-version-and-boundary',[1,25],'Registered local source is arXiv:2010.03832v2 marked3Jul2024, with running preprint dateJuly4,2024. Main text and acknowledgements end on PDFpage25; clip at y520 before References y527.295. AppendixA begins26. Exactly Theorems5,8,10 are inventoried; Corollary6 is retained only for its explicit assumption import and Gaussian definition.')
    issue('regular-variation-domain-and-tail-scale',[3,9],'Section2 prints E=[0,infinity)^d while vague regular variation normally needs an origin-excluded cone or equivalent topology. Eq3 states a*(u)~1/P(X_i*>u); the Section3.2 prose instead prints a*(.)~P(X_i*>.), apparently missing the inverse. Use Eq3 as the defining normalization and preserve the discrepancy. The model has asymptotically normalized margins, not necessarily exact standard Pareto margins.')
    issue('standardization-alpha-indices',[3,9,10],'Section2 and Section3.2 standardize each coordinate using alpha_i, whereas Theorem8 prints X_i^alpha with an unindexed exponent. Theorem8’s Gaussian covariance still uses alpha_i alpha_j. Preserve the theorem verbatim and the original model separately; do not silently impose equal indices or repair the displayed theorem.')
    issue('positive-orthant-versus-masked-support',[7],'The printed A_delta,I lies in (0,infinity)^d but also requires zero coordinates off I. Literally proper-support strata are empty. The surrounding discussion intends masked nonnegative scaling vectors close to1_I. Keep the printed set and record the apparent orthant error, rather than redefining it. This affects the domain of the process and derivative statements.')
    issue('corollary-six-centering-and-domain',[7,8],'Corollary6 condition(27) prints tau E||s circle X*|| c and v in partial B1*(0), whereas Eq23/26 use the spectral Theta and the plus simplex. The starred B1 domain is not defined. The X* expectation differs from the bounded spectral normalization and can be infinite, for example with standard Pareto margins. Index1 regular variation alone does not force its mean to be infinite. Preserve both expressions; this is an unresolved source discrepancy in an assumption explicitly imported by Theorem10.')
    issue('expectation-centering-and-assumption-imports',[8,10,11],'Theorem5 centers at the exact finite-sample expectation and does not assume Eq27 or Eq30. Theorem8 imports Eq3/30 and the coordinatewise second-order bias rate, but not Corollary6’s angular bias assumption. Theorem10 explicitly imports both Corollary6 and Theorem8 assumptions. A reference to the Gaussian limit object alone does not import every assumption or conclusion of its originating result.')
    issue('masked-weights-and-derivative-extension',[4,6,7,11],'The simplex is nonnegative with l1 norm1, but v_I masks coordinates without renormalizing, so v_I need not lie in that simplex. Theorem10 evaluates c and Gaussian processes at v_I nonetheless. The formulas extend homogeneously, but the extension is not explicitly stated. Likewise all coordinate partial derivatives on stratified A_delta prime require an extension/relative convention at inactive zeros and boundary points. Record these issues rather than altering the domain.')
    issue('zero-divisions-and-strict-exceedances',[5,7,9,10],'The source specifies0^0=1 for Phat, but does not fully state zero-angle or zero-exceedance-denominator conventions. Theta/ell_I(Theta) under the tilted spectral law can be undefined on zero-weight angles; the integral needs a harmless convention there. Order-statistic ratios assume positive denominators. Strict exceedances above the kth upper order statistic can give k−1 observations in a continuous sample and fewer with ties; do not replace Ptilde by k/n or add an unstated no-tie hypothesis.')
    issue('tilted-spectral-law-and-pair-coefficients',[3,5,8,10],'Theta^I is an ell_I(Theta)-tilted angular law, not simple rescaling under the original probability. Theorem8’s tau_ij is the {i,j} subset coefficient, while tau is the full-set coefficient. Remark7.1 uses projected Theta_I^I. These probability laws and constants remain separate even though linked by Eq14–15.')
    issue('joint-gaussian-coupling-and-appendix-covariance',[8,9,10,11],'Theorem10’s Gtilde,G^0 and Htilde are jointly coupled limits. Preserve Remark7.2’s G/Gtilde cross covariance, Eq34’s H/G covariance and the i in J zero H/Gtilde covariance. G^0 is the p=0 restriction of G. The general Gtilde covariance Eq48 is in an excluded appendix, but Remark7.1 gives the needed s=1_I,beta=1 specialization in full; do not read the appendix or assume independence of all components.')
    issue('general-cross-covariance-notation',[11],'Equation35 prints Theta_i wedge Theta_J in a scalar covariance expression without a norm around the vector Theta_J. Its interpretation is ambiguous. Theorem10 only needs i in I, for which the following original sentence explicitly states zero H_i/Gtilde covariance. Retain that clean specialization and note the unresolved general expression, without silently correcting it.')
    issue('sequence-and-index-notation',[8,9,10,11],'Theorem10’s display uses k whereas its assumptions use k_n; preserve this notation and record k=k_n along the stated sequence. Finiteness of K is inherited from Corollary6. The Hill prose uses alpha_hat_{k,n,i} while(33) uses alpha_hat_{n,k,i}. Rem7.2 states K although its zeroth-moment specialization is used later; G at p=0 is explicitly defined in Theorem5 and before Theorem10. No source notation is silently rewritten.')
    bindings={
'T5':dict(sample='iid normalized nonnegative X* regularly varying with index1, Eq3 and spectralTheta.',sequences='u_n→infinity and n/a*(u_n)→infinity; finite K0⊂N0 and delta≥0.',bound_inline='G_n is defined by(24), centered at a*E Mhat, with sqrt(n/a*) scaling. G is defined by its full covariance(25).',objects=['D1','D2','D3','D4','D5','D10','D11'],excluded='No Corollary6 bias(27), second-order(30), unknown-margin model or Hill estimator is required.'),
'T8':dict(sample='iid non-standard X and printed X* standardization, Eq3 and second-order(30).',sequences='k_n→infinity, k_n/n→0 and sqrt(k_n) A_i*(n/k_n)→0 for everyi.',bound_inline='Joint centered Gaussian Htilde with full pairwise covariance; reciprocal estimators and alpha inverse are coordinatewise.',objects=['D2','D3','D4','D8','D19','D20','D27'],excluded='No Corollary6 angular bias(27), random angular-moment estimator or process differentiability is assumed.'),
'T10':dict(sample='iid non-standard X; full Corollary6 assumptions(A1,D14) and full Theorem8 assumptions(A2).',sequences='a*(u_n)~n/k_n,delta>0,finite K⊂N inherited fromCor6; display k follows k_n.',bound_inline='All c partials in s_i,beta_i exist continuously on the printed domain; nonemptyI. Preserve sqrt(k), signs, alpha_i factors, G^0 superscript and weak l-infinity topology.',objects=['D5','D7','D10','D13','D14','D17','D20','D22','D23','D24','D26','D27'],limit='Joint Gaussian combination: Gtilde minus the sum of c_si G^0 and c_betai alpha_i H_i. Required joint covariances are main-text D22,D23,D24,D26,A4.',unresolved='Printed Eq27 centering/domain, A_delta orthant, masked-simplex extensions and derivative interpretation are preserved as source issues.')}
    refs=[dict(claim_id=PID+'/T5',reference='Eq3 and spectral component',reference_kind='definition_reference',resolution='D1–D3 preserve index1 regular variation, unit marginal normalization and independent Pareto/spectral limit.'),dict(claim_id=PID+'/T8',reference='Eq3 and(30)',reference_kind='assumption_reference',resolution='D2,D20 preserve marginal normalization and positive-auxiliary second-order condition; intermediate sequence and all-coordinate bias rates are inline and saved in A2.'),dict(claim_id=PID+'/T10',reference='assumptions of Cor6',reference_kind='assumption_reference',resolution='D14 preserves condition27 verbatim and its finite K and uniformity. A1 preserves the imported Theorem5 assumptions, not its conclusion.'),dict(claim_id=PID+'/T10',reference='assumptions of Thm8',reference_kind='assumption_reference',resolution='A2 preserves full original assumptions, including Eq3/30 and k_n bias rate, without importing an assumption about Gaussian convergence.'),dict(claim_id=PID+'/T10',reference='Gtilde,Htilde andG^0',reference_kind='definition_reference',resolution='D22–D24,D26,A4 supply all needed marginal and cross covariances from main-text Theorem5,Cor6,Remark7.1/7.2,Theorem8,Remark9 and the p=0 definition.'),dict(claim_id=PID+'/T5',reference='AppendixA proof',reference_kind='proof_only',resolution='Excluded; no appendix body read.'),dict(claim_id=PID+'/T8',reference='AppendixC proof',reference_kind='proof_only',resolution='Excluded; no appendix body read.'),dict(claim_id=PID+'/T10',reference='AppendixD proof',reference_kind='proof_only',resolution='Excluded; no appendix body read.')]
    data=dict(paper_id=PID,unranked_auxiliary_passages=aux,source_issues=issues,statement_local_bindings=bindings,source_claim_references=refs,ambient_conventions=['Nonnegative real d-vectors; maximum norm unless norm1 is specified; coordinatewise powers, products and ratios; indicator vectors and masked coordinates; scalar minima and coordinate subset maxima.','Unit Pareto radial Y has survival1/y for y≥1 and is independent ofTheta. The normalized probability spectral law is distinct frommu* andtau. Vague and weak convergence, bounded-function l-infinity spaces, tightness and centered Gaussian laws retain standard ambient meanings.','All estimator definitions preserve finite-sample strict exceedances and original power/order indices. The denominator A3 is available independently of the Hill numerator, avoiding a circular graph. No mathlib availability is inferred.','I and J are nonempty coordinate subsets where their maxima are used. Tau_ij denotes tau_{i,j}; repeated indices reduce to a singleton. The source does not explicitly discuss every zero-division convention, extension domain or tie case.','Original multi-location excerpts in D10,D23,D26 and A4 preserve the cited pieces without presenting them as one contiguous source paragraph. Eq48 and all appendix bodies are excluded. This audit records statements and dependencies; it does not prove them or repair the source.'])
    (ROOT/'ambient-prerequisites.json').write_text(json.dumps(data,indent=2,ensure_ascii=False)+'\n')
if __name__=='__main__':main()
