"""Retain source conventions and unresolved meanings, separate from theorem originals."""
import json
from save_inventory import PID,ROOT
A=[];ISSUES=[]
def passage(n,s,pages,note):
    A.append(dict(local_id=f'A{n}',statement_original=s,evidence=[dict(page=p,location=f'Auxiliary source passage A{n}') for p in pages],scope_note=note))
def issue(key,text,pages):
    ISSUES.append(dict(issue_id=key,description=text,evidence=[dict(page=p,location='Source scope or notation') for p in pages]))
passage(1,r'''We denote $\rho_*:=P_*(A=0)\in(0,1)$, the true proportion of data from the target population.''',[8],'Observed-target proportion for Theorem 2 and dagger specializations. It is not a positivity assumption on an unobserved target in the general Section 3 setup.')
passage(2,r'''We suppose that $\operatorname{var}_{P_*}(\ell(X,Y)\mid A=0)<\infty$, a very mild condition, throughout this paper.''',[8],'Footnote 2, standing finite target-loss variance. Its X,Y and A=0 wording must be preserved alongside the later generalized Z,Q setting.')
passage(3,r'''In this paper, we define $0/0=0$.''',[8],'Footnote 3 supplies a stated zero-denominator convention; do not report every zero fold count as completely unspecified. It does not define a nonzero numerator divided by zero.')
passage(4,r'''For any non-negative integers $M$ and $N$, we use $[M:N]$ to denote the index set $\{M,M+1,\ldots,N\}$ if $M\leq N$ and the empty index set otherwise; we use $[M]$ as a shorthand for $[1:M]$. For any finite set $S$, we use $|S|$ to denote its cardinality.''',[9],'Finite fold and component ranges, including the empty sums arising when K=1.')
passage(5,r'''For a distribution $P$, we use $P_\sharp$ and $P_{\sharp\mid\natural}$ to denote the marginal distribution of the random variable $\sharp$ and the conditional distribution of $\sharp\mid\natural$, respectively, under $P$; we use $P_{*,\sharp}$ and $P_{*,\sharp\mid\natural}$ to denote these distributions under $P_*$. We use $P^n$ to denote the empirical distribution of a sample of size $n$ from $P$. When splitting the sample into $V>0$ folds, we use $P^{n,v}$ and $P_\sharp^{n,v}$ to denote empirical distributions in fold $v\in[V]$. All functions considered will be measurable with respect to appropriate sigma-algebras, which will be kept implicit. For any function $f$, any distribution $P$, we sometimes use $Pf$ to denote $\int f\,dP$. For any $p\in[1,\infty]$, we use $\|f\|_{L^p(P)}$ to denote the $L^p(P)$ norm of $f$, namely $(\int f(x)^pP(dx))^{1/p}$. We also use $L^p(P)$ to denote the space of all functions with a finite $L^p(P)$ norm, and use $L_0^p(P)$ to denote $\{f\in L^p(P):\int f\,dP=0\}$. All asymptotic results are with respect to the sample size $n$ tending to infinity.''',[9],'Original ambient notation. The printed Lp formula lacks absolute values and an infinity-endpoint definition. L2 and L2_0 are used by the two theorem statements; do not silently rewrite the general notation.')
passage(6,r'''When working under this stronger condition, we use $\mathcal S_k$ to denote $\mathcal S'_k\setminus\{0\}$ for short.''',[10],'Source-only sets exclude the observed target. The preceding stronger condition is DS.0-dagger; S_k can be empty, whereas S-prime_k is nonempty in DS.0.')
passage(7,r'''According to the well-known review by Moreno-Torres et al. [2012], the following four dataset shift conditions are among the most widely considered when one source population is available, so that $\mathcal A=\{0,1\}$. These conditions are all special cases of Condition $\mathrm{DS.0}^\dagger$.''',[10],'Binary one-source context for DS.1 and Section 4. DS.2–DS.4 are not hypotheses of Theorem 2.')
passage(8,r'''If $\theta^{k-1}(\bar z_{k-1})=\infty$, we set $1/(1+\theta^{k-1}(\bar z_{k-1}))$ to be zero. When $\theta^{k-1}$ equals the truth $\theta_*^{k-1}$, this can happen for $\bar z_{k-1}$ outside the support of $\bar Z_{k-1}\mid A=0$ but inside the support of $\bar Z_{k-1}\mid A\in\mathcal S_k$.''',[13],'Footnote 4 fixes the inverse-odds convention at infinity; preserve it for (7), (9), (13) and the dagger algorithm.')
passage(9,r'''We take as given a flexible regression method $\mathcal K$ estimating conditional means and a flexible classifier $\mathcal C$ estimating conditional odds—both taking outcome, covariates, and an index set for data points being used as inputs in order. For example, $\mathcal K$ and $\mathcal C$ may be random forests, neural networks, gradient boosting, or an ensemble learner. We also take as given a flexible density ratio estimator $\mathcal W$, taking an index set for data points being used as input, which may be transformed from a classifier $\mathcal C$ by Bayes’ Theorem or based on kernel density estimators.''',[14],'Given fitting procedures; no particular learner or sufficient smoothness condition is an extra theorem premise. The general algorithm body remains excluded.')
passage(10,r'''Splitting the sample into a fixed number $V$ of folds $I_v$ ($v\in[V]$) leads to the estimating equation $\sum_{i\in I_v}D_{\mathrm{SC}}(\widehat{\boldsymbol\ell}_v,\widehat{\boldsymbol\theta}_v,\widehat{\boldsymbol\pi}_v,r)(O_i)=0$ averaging over data in each every fold $v$, with preliminary estimators $(\widehat{\boldsymbol\ell}_v,\widehat{\boldsymbol\theta}_v,\widehat{\boldsymbol\pi}_v)$ using data outside of the fold. The solution is given in (11).''',[14],'Fixed V asymptotic convention. The source says every preliminary estimate uses out-of-fold data here, but Algorithm 1-dagger line 4 uses in-fold pi. Preserve the discrepancy and the actual algorithm.')
passage(11,r'''It is viable to replace the in-fold estimator $\widehat{\boldsymbol\pi}_v$ of $\boldsymbol\pi_*$ with an out-of-fold estimator in Algorithms 1 and $1^\dagger$. These two approaches have the same theoretical properties that we will show next, and similar empirical performance.''',[14],'Remark 2 records an allowed alternative in the general/dagger discussion. This does not erase the different qualification about inconsistent conditional-risk estimation in Section 4 Remark 6.')
passage(12,r'''In the following analyses without assuming Condition DS.0, we assume that nuisance estimators $\widehat{\boldsymbol\ell}_v$ can be evaluated at any point in the space $\mathcal Z$ containing the observation, even if that point is outside the support under $P_*$. For illustration, we assume that, for each $k\in[2:K]$, $\|\widehat\ell_v^k-\ell_\infty^k\|_{L^2(\nu_k)}\xrightarrow{p}0$ for some function $\ell_\infty^k$, where $\nu_k$ denotes the distribution of $\bar Z_k\mid A\in\mathcal S'_k$ under $P^0$.''',[14],'Off-support evaluability is a stated convention. The limiting regressions are illustrative only, as Remark 3 makes explicit. The source writes the otherwise unexplained P^0; do not replace it with P_*.')
passage(13,r'''In all expectations involving nuisance estimators such as $(\widehat{\boldsymbol\ell}_v,\widehat{\boldsymbol\theta}_v,\widehat{\boldsymbol\pi}_v)$, these estimators are treated as fixed and the expectation integrates over the randomness in a data point $O=(Z,A)$. For example, $\mathbb E_{P_*}[\widehat\ell_v^1(Z_1)\mid A=0]=\int\widehat\ell_v^1\,d\mu$ where $\mu$ is the distribution of $Z_1\mid A=0$ under $P_*$, and this expectation is itself random due to the randomness in $\widehat\ell_v^1$.''',[14],'Footnote 5: fitted nuisance functions remain random, but are frozen for integration over a fresh observation. This governs h, B, Delta and the remainder in Theorem 2.')
passage(14,r'''Further, given any scalar $r$, with $\theta^0:=\sum_{a\in\mathcal S_1}\pi^a/\pi^0$, define''',[13],'Generic theta^0 convention preceding (8), also used in (7) and (9). It does not make D_GSC a prerequisite of D_SC.')
issue('registered-version','All statements and passages refer to the registered arXiv v4, stamped 8 Jun 2024, not an assumed published-version transcription.',[1])
issue('general-algorithm-outside-scope','The general Algorithm 1 is explicitly placed in the supplement. Only the main-text reference and Theorem 1 input/output references are preserved. Its construction and omitted local dependencies remain unresolved.',[14,17,18])
issue('algorithm-number-collision','General supplement Algorithm 1, main-text Algorithm 1-dagger on page 15, and Section 4 Algorithm 1 on page 26 are distinct source references. The two latter bodies are retained in full.',[14,15,26])
issue('target-observation-scope','Section 2 assumes A contains 0 and fully observed target data. Section 3 expressly allows an unobserved target Q. Theorem 1 still writes conditional expectations given A=0 in Delta; that notation requires clarification in the general unobserved-target case.',[7,10,17])
issue('target-support-notation','The prefix setup names the support of history given A=0 even though Q may be unobserved. DS.0 subsequently says support under Q. Preserve both source formulations.',[10])
issue('density-ratio-existence','Theorem 1 discusses failure of DS.0 yet uses lambda_* defined for dominated target/source history laws. The main-text failure discussion emphasizes conditional mismatch and extensions; no unrestricted density-ratio construction under failure of domination is supplied.',[12,17,21])
issue('source-probability-positivity','DS.0 makes S-prime_k a known nonempty subset but does not separately write positive source probability for every such conditioning event. Conditional laws and denominators need their usual existence conventions.',[10,12,13])
issue('general-standing-variance','Footnote 2 states finite conditional variance of ell(X,Y) given A=0 throughout, while the generalized setup permits arbitrary Z and unobserved Q. Do not silently change that standing source statement.',[8,10])
issue('fold-conventions','Fixed V is stated in Section 3.2. Approximately equal fold sizes are specified by Algorithm 1-dagger; the specialized Algorithm 1 states random folds without repeating approximate equality. Empty-fold handling and minimum training class sizes are not fully specified.',[14,15,26])
issue('marginal-fit-prose-conflict','Page 14 says all preliminary nuisance estimators are out-of-fold. Algorithm 1-dagger explicitly estimates pi in-fold. Remark 2 permits an out-of-fold alternative; preserve the actual recipe and both qualifications.',[14,15])
issue('theorem1-unhatted-pi','The last denominator in expansion (19) uses pi_v^a without a hat. Its meaning is not separately defined; it is preserved rather than silently replaced by pi-hat_v^a.',[18])
issue('theorem1-threshold-rates','The threshold on t contains a*b+a+b+n^-1, whereas the normal-tail bound (20) contains a*b+n^-1/2*(a+b)+n^-1. Both are preserved as printed.',[17,18])
issue('bound-uniformity','The finite-sample branch quantifies over all n,k,v and refers to the bound on lambda-hat. It does not separately spell out whether one deterministic envelope is uniform in all indices and realizations; the constants are stated to depend only on epsilon, P_* and that bound.',[17,18])
issue('zero-variance','Theorem 1 divides by sigma_*,GSC in (20), without explicitly assuming it is positive. The source 0/0=0 convention does not specify nonzero/0.',[8,13,18])
issue('theorem1-drift-scope','ST.1 and ST.2 control r-hat minus Delta. DS.0 is added only in the final clause to make Delta=0. Drift correction must not be discarded or DS.0 added to every branch.',[17,18])
issue('nonunique-regressions','Section 3.4 says conditional means can be nonunique even on target supports when DS.0 fails; ST conditions and the influence function may depend on the selected version. No unique canonical regression is substituted.',[12,21])
issue('illustrative-limits','Remark 3 allows ST.1/ST.2 without existence of every nuisance limit. The illustrative L2(nu_k) convergence and limiting oracle regressions are not added as theorem assumptions.',[14,16,17])
issue('unintroduced-P0','The illustration defining nu_k on page 14 uses P^0 without a definition there. That symbol is preserved as an unresolved source convention.',[14])
issue('lp-notation','The stated general Lp norm lacks absolute values and the infinity-endpoint convention, although p ranges through infinity. The actual theorem uses L2. Preserve the printed general definition.',[9])
issue('regularity-external','Asymptotic linearity and efficient influence function are described in the main text, but regularity and full model/tangent-space definitions are not provided. Supplementary efficiency exposition remains excluded.',[9])
issue('efficient-identification-conditions','The paragraph identifying D_GSC and D_SC as efficient influence functions requires DS.0 plus two-sided ratio bounds or DS.0-dagger plus bounded odds. These conditions qualify that source identification; they must not be silently inserted into all of Theorem 1.',[13,17,18])
issue('binary-feature-shift','DS.1 is X independent of A under A={0,1}. Neither a multi-source interpretation of 1-a nor Y|X invariance is substituted for it.',[10,25,26])
issue('theorem2-rho-index','Theorem 2 remainder uses rho-hat^v in its first term but rho-hat^{-v} inside D_Xcon. Algorithm 1 estimates rho in-fold. Remark 6 says out-of-fold rho changes the influence function when conditional risk is inconsistently estimated; preserve the apparent inconsistency.',[26,27])
issue('theorem2-nuisance-limit','Theorem 2 assumes one common L2 limit across folds, which need not equal E_*. The extra leading influence-function term is retained. Only the final branch sets E_infinity=E_*.',[26,27])
issue('footnote6-preservation','Theorem 1 footnote 6 is retained as source_footnotes in the inventory and must survive the full census handoff unchanged. It is not inserted into statement_original.',[17])
RESOLUTION={
'shared':dict(local_objects='D1–D10 retain target risks, prefixes, shift conditions and true nuisance functions; D11–D15 retain pseudo-losses, influence functions and variance; D16 is the unresolved general algorithm; D17–D22 retain the dagger algorithm, oracle/product-bias terms and rate conditions; D23–D26 retain conditional risk, the feature-shift influence function and algorithm, and asymptotic linearity.',ambient_or_bound='A1–A17 preserve source proportions, standing variance, quotient conventions, indices, measurability, empirical laws, L2, source-only sets, binary populations, fitting procedures, fixed folds, frozen-nuisance integration and theta^0. Ordinary conditional expectation, RN derivatives, stochastic orders, standard normal probability, finite sums and convergence remain ambient.'),
'1':dict(local_objects='Theorem 1 explicitly consumes estimated and true nuisance functions, both pseudo-loss parameterizations through its algorithm references, h, B, sigma_GSC, ST.1/ST.2 and the final additional DS.0 clause. General r_*=E_Q ell and the dagger observed-target specialization must remain distinguishable.',ambient_or_bound='Delta_v and Delta, confidence sequences a,b,c,d, epsilon,t, constants C1/C2, and Phi are bound or defined inline. The nuisance integration convention freezes fitted functions. pi_v^a in (19), A=0 for an unobserved target, and missing general algorithm details remain unresolved.',branch_scope='Retain finite-sample expansion and confidence guarantee, two algorithm-specific efficiency expansions, weaker consistency, and final drift-zero conclusion as branches of one theorem.'),
'2':dict(local_objects='DS.1, risk (1), conditional target risk E_*, D_Xcon (23), Section 4 Algorithm 1 and the RAL convention resolve the statement. The general Algorithm 1 and ST.1/ST.2 are not theorem premises.',ambient_or_bound='E_infinity is a common L2 nuisance limit, and B is defined inline. rho_* and in-fold rho-hat^v are source-defined; the remainder also prints rho-hat^{-v}, retained unresolved. P_* and P^{n,v} act on functions as integration operators.',branch_scope='Common possibly inconsistent nuisance limit yields the full stated RAL expansion; E_infinity=E_* is an additional efficiency branch.')}
passage(15,r'''Conditions ST.1 and ST.2 can hold even if the limit $\ell_\infty^k$ of the nuisance function estimator $\widehat\ell_v^k$ does not exist. This case could happen if the support of $\bar Z_k\mid A\in\mathcal S_k$ is larger than $\mathcal Z_k$. Our results allow for such cases; we introduced the limit $\ell_\infty^k$ to illustrate Conditions ST.1 and ST.2.''',[17],'Remark 3 expressly limits the role of the illustrative nuisance limits; they are not extra hypotheses of Theorem 1.')
passage(16,r'''Nevertheless, without Condition DS.0, our results in Section 3.2 remain valid as long as Condition ST.1 or ST.2 holds for one version of the collection of true conditional mean loss functions $\boldsymbol\ell_*$. For example, part 2 of Condition ST.1 would require the consistency of $\widehat{\boldsymbol\ell}_v$ for some version of $\boldsymbol\ell_*$, and $D_{\mathrm{SC}}(\boldsymbol\ell_*,\boldsymbol\theta_*,\boldsymbol\pi_*,r_*)$ in (22) would depend on the particular adopted version of $\boldsymbol\ell_*$. The appropriate choice of $\boldsymbol\ell_*$ often depends on the asymptotic behavior of the nuisance estimator $\widehat{\boldsymbol\ell}_v$, which might heavily depend on the particular choice of the regression technique used in the sequential regression (Line 6, Alg. $1^\dagger$).''',[21],'Section 3.4 qualification: under failed DS.0, rate conditions and the influence function can depend on the adopted conditional-mean version. No unique global version is imposed.')
passage(17,r'''It is possible to replace the in-fold estimator $\widehat\rho^v$ of $\rho_*$ with an out-of-fold estimator in Alg. 1. Unlike Alg. $1^\dagger$, this would lead to a different influence function when the nuisance function $\mathcal E_*$ is estimated inconsistently in Theorem 2. In this case, the influence function of $\widehat r_{\mathrm{Xcon}}$ from Theorem 2 cannot be used to construct asymptotically valid confidence intervals if $\mathcal E_*$ is estimated inconsistently.''',[27],'Remark 6 qualifies the alternative rho estimate in the concept-shift algorithm and supports retaining the inconsistent fold superscripts in the printed Theorem 2 remainder.')

def main():
    data=dict(paper_id=PID,status='extracted',unranked_auxiliary_passages=A,source_issues=ISSUES,statement_resolution=RESOLUTION,unresolved_source_references=[dict(reference='General Algorithm 1 in Supplemental Material',status='excluded_by_scope',resolution='Main-text references retained, algorithm body and its missing dependencies unresolved.'),dict(reference='Supplement S9 and cited semiparametric regularity theory',status='excluded_by_scope',resolution='No supplementary proofs or definitions read; the main-text terminology is retained.')])
    (ROOT/'ambient-prerequisites.json').write_text(json.dumps(data,indent=2,ensure_ascii=False)+'\n')
    print(f'Saved {len(A)} auxiliary passages and {len(ISSUES)} source issues.')
if __name__=='__main__':main()
