"""Derive and validate this paper's census from its reviewed inventory and local graph."""
import copy
import json
import subprocess
import sys
from pathlib import Path
from extract_interfaces import ROOT,PID,interfaces,members,edges,main as save_passages

SKILL=Path('skills/statistical-paper-census/scripts')
sys.path.insert(0,str(SKILL))
from canonical_dependencies import canonical_dependencies
from census_metrics import derive_metrics
from publication_contract import attach_inventory

DIRECT={'2.4': {'D1': 'The probability and sigma-squared parameter refer to the iid Gaussian-error regression model (1.1).', 'D6': 'The statement fixes K=K0 and s=s0 in problem (2.1) and concerns its solution theta-hat-g, named immediately before the theorem.', 'D8': 'Both the probability bound and consistency statement compare against theta-hat-ol from Definition 2.3.', 'D5': 'The bound and sufficient threshold explicitly use c_min from Definition 2.2.', 'D9': 'The final conclusion is convergence to zero of the 0-1 grouping risk L_g defined immediately before the theorem.'}, '2.5': {'D1': 'The minimax grouping probabilities and noise variance sigma-squared use model (1.1).', 'D9': 'Both the lower bound and its consequence concern L_g for arbitrary estimators.', 'D10': 'The supremum ranges over the sensitivity-restricted class Theta_c(K0,s0,ell) introduced in Section 2.3.3.', 'D11': 'The theorem-defined ratio r minimizes over the separated and balanced class tilde-Theta(K0,s0).', 'D5': 'The denominator in the theorem-defined r is the minimum of grouping sensitivity c_min.'}, '3.2': {'D14': 'The statement explicitly quantifies over the sequence generated by Algorithm 2.', 'D12': 'The condition L>l and the limit of g(theta_m) use the convex, lower-bounded, Lipschitz-gradient objective introduced in Section 3.2.'}}

def main():
    save_passages()
    inv=json.loads((ROOT/'theorem-inventory.json').read_text())
    data=copy.deepcopy(inv)
    data['schema_version']='statistical-ranked-interfaces-v4'
    data['scope'].update(paper_count=1,
        source_policy='Pinned arXiv:2201.01036v1, 31 PDF pages. Three main-text Theorems and all extracted passages checked against pages 1-19; appended material beginning on page 20 excluded.',
        normalization_policy='Preserve printed wording, formulas, labels and source inconsistencies; transcribe mathematical expressions into LaTeX and normalize line wrapping and typographic emphasis only. The printed PDF supplies original wording, numbering and algorithm nesting.',
        semantic_ranking_policy='All three inventoried Theorems retained; direct demand counted once per theorem and interface, independently of proof use.',
        build_order_policy='Derive from the acyclic same-paper dependency graph; statistical grouping risks and general-objective algorithm convergence retain separate dependencies; screening and MIO implementations are not imported into the stated results.')
    data['interfaces']=copy.deepcopy(interfaces)
    claims={c['claim_id']:c for c in data['claims']}
    for c in data['claims']:
        number=c['claim_id'].split('/T')[-1]
        direct=DIRECT[number]
        c['depends_on']=list(direct)
        for x in data['interfaces']:
            used=[m['local_id'] for m in x['members'] if m['local_id'] in direct]
            if used:
                x['central_claim_uses'].append(dict(use_id=c['claim_id']+'-'+x['interface_id'].split('/')[-1],
                    paper_id=PID,claim_id=c['claim_id'],use_kind='statement_dependency',reason=' '.join(direct[lid] for lid in used),evidence=c['evidence']))
    derived=canonical_dependencies(data)
    for x in data['interfaces']:x['dependencies']=derived[x['interface_id']]
    derive_metrics(data)
    for x in data['interfaces']:
        for r in x['related_theorems']:
            cid=r['claim_id'];path=r['via_local_ids'];number=cid.split('/T')[-1]
            sentences=[DIRECT[number][path[0]]]
            evidence=list(claims[cid]['evidence'])
            for lid in path:
                evidence.extend(e for e in members[lid]['evidence'] if e not in evidence)
            for a,b in zip(path,path[1:]):sentences.append(edges[a][b])
            x['theorem_explanations'][cid]=dict(paper_id=PID,via_local_ids=path,text=' '.join(sentences),evidence=evidence)
        for m in x['members']:
            own=m['statement_original']+' '+m['local_label']
            linked=own+' '+' '.join(claims[r['claim_id']]['statement_original'] for r in x['related_theorems'])
            selectors=m['highlight_symbols']+m['highlight_phrases']
            assert any(s in own for s in selectors),(m['local_id'],'no source highlight')
            assert all(s in linked for s in selectors),(m['local_id'],'unmatched selectors',[s for s in selectors if s not in linked])
    attach_inventory(data,ROOT/'theorem-inventory.json',ROOT/'ranked-interfaces.json')
    (ROOT/'unfinalized-census.json').write_text(json.dumps(data,indent=2,ensure_ascii=False)+'\n')
    subprocess.run([sys.executable,str(SKILL/'finalize_census.py'),str(ROOT/'unfinalized-census.json'),str(ROOT/'ranked-interfaces.json'),'--inventory',str(ROOT/'theorem-inventory.json')],check=True)
    subprocess.run([sys.executable,str(SKILL/'validate_census.py'),str(ROOT/'ranked-interfaces.json')],check=True)
    print('All source highlight selectors matched. Census finalized and independently validated; final source-audit record remains.')

if __name__=='__main__':main()
