"""Preserve supporting main-text definitions, local binders and source ambiguities."""
import json
from save_inventory import ROOT,PID
def main():
    aux=[]
    def add(n,s,pages,note,deps=()):
        aux.append(dict(local_id='A'+str(n),statement_original=s,evidence=[dict(page=p,location='Original main-text context A'+str(n)) for p in pages],scope_note=note,depends_on=list(deps)))
    add(1,r'''Let $(\mathcal Z_1,\mathcal G_1),\ldots,(\mathcal Z_n,\mathcal G_n)$, $(\mathcal Z,\mathcal G)$, $(\mathcal Z',\mathcal G')$ and $(\mathcal X,\mathcal F)$ be measurable spaces and write $\mathcal Z^{(n)}:=\mathcal Z_1\times\cdots\times\mathcal Z_n$ and $\mathcal G^{(n)}:=\mathcal G_1\otimes\cdots\otimes\mathcal G_n$. Moreover, we use the conventions that $\mathcal Z^{(0)}=\varnothing=\mathcal G^{(0)}$ and $A\times\varnothing=A$ for any set $A$.''',[4],'Product sample spaces and the printed empty-product convention. The source uses the empty-set symbol as a formal zero-history convention; literal set multiplication would not satisfy its identity. No silent replacement by a singleton is made.')
    add(2,r'''Notice that strictly speaking $\mathcal Q_\alpha(\mathcal X)$ is set theoretically not well defined, as it is at least as large as the set of all sets. However, this is not an issue. We simply need to define expressions like $\sup_{Q\in\mathcal Q_\alpha(\mathcal X)}I_\theta(Q\mathcal P)$ by
\[
\sup\{a\in\mathbb R:\exists(\mathcal Z,\mathcal G)\text{ measurable}:\exists Q\in\mathcal Q_\alpha(\mathcal X\to\mathcal Z):a=I_\theta(Q\mathcal P)\}.
\]''',[5],'Footnote 1 supplies the real-valued interpretation of an unrestricted-output Fisher supremum. Used in the scalar Theorems 4.11 and 4.12; not a supremum over a fixed output alphabet.',['D2','D6'])
    add(3,r'''We say that a model is DQM or simply regular, if it is DQM at every point $\theta\in\Theta$. For convenience we sometimes write $dx$ instead of $\mu(dx)$.''',[9],'All-parameter DQM/regular convention. Theorem 3.3/3.5 impose DQM only at their specified parameter; Theorem 4.2 and C1 explicitly require every parameter.',['D5'])
    add(4,r'''For a given parameter space $\Theta\subseteq\mathbb R^p$, let $\mathcal E_n=(\Omega_n,\mathcal A_n,\{R_{n,\theta}:\theta\in\Theta\})$, $n\ge1$, be a sequence of statistical experiments, where $R_{n,\theta}$ is a probability measure on the measurable space $(\Omega_n,\mathcal A_n)$. For $\theta,\theta_0\in\Theta$, define the associated log-likelihood ratio $\Lambda_n(\theta,\theta_0):=\log\frac{dR_{n,\theta}}{dR_{n,\theta_0}}$, where $\frac{dR_{n,\theta}}{dR_{n,\theta_0}}$ is the Radon-Nikodym derivative of the absolutely continuous part of $R_{n,\theta}$ with respect to $R_{n,\theta_0}$ and set $\Lambda_n(\theta,\theta_0):=\Lambda_n(\theta_0,\theta_0)=0$ if $\theta\notin\Theta$.''',[10],'Complete main-text log-likelihood ratio convention required by Definition 2. No full mutual absolute-continuity requirement is inserted into the LAMN definition.')
    add(5,r'''Throughout, we write $J_p$ for the $p\times p$ identity matrix and $\|\cdot\|_r$ to denote the $\ell_r$ as well as the $L^r(\mu)$ norm whenever the meaning is clear from the context. We also use simply $\|\cdot\|$ to denote the Euclidean norm of vectors and the spectral norm for matrices and we write $\preceq$ to denote the partial Loewner ordering of matrices. If $\mathcal P=(P_\theta)_{\theta\in\Theta}$ is a parametric model with $\Theta\subseteq\mathbb R^p$ that is dominated by $\mu$, we write $p_\theta=\frac{dP_\theta}{d\mu}$ and $\mathbb E_\theta$ for a $\mu$-density and for the expectation operator with respect to $P_\theta$, respectively. If $V$ is a random $p$-vector we also write $\operatorname{Var}[V]$ to denote the corresponding $p\times p$ covariance matrix. Finally, $\overset{R_n}{\rightsquigarrow}$ denotes weak convergence with respect to the sequence of probability measures $(R_n)_{n\in\mathbb N}$.''',[4],'Ambient matrix, density and weak-convergence conventions; J_p is the identity, not the all-ones matrix. The author overloads norm notation and keeps the matrix 2-subscript in Lemma 4.10.')
    add(6,r'''\[
\Sigma_{n,\theta}(z_{1:n-1}):=\frac1n\sum_{i=1}^nI_\theta(Q_{z_{1:i-1}}\mathcal P),\qquad z_{1:n-1}=(z_1,\ldots,z_{n-1})\in\mathcal Z^{(n-1)}.
\]''',[11],'Definition excerpt from Theorem 3.3 explicitly imported by Theorem 3.5. Only this average conditional-information object is imported, not the weak-limit or LAMN conclusion of Theorem 3.3.',['D1','D3','D6'])
    add(7,r'''Throughout this subsection, we consider a parametric model $\mathcal P=(P_\theta)_{\theta\in\Theta}$, with parameter space $\Theta\subseteq\mathbb R^p$ and sample space $(\mathcal X,\mathcal F)$, that is dominated by $\mu$ with corresponding densities $p_\theta$.''',[14],'Section 4.1 ambient dominated model for Theorems 4.1–4.3. Theorem 4.1 concerns raw likelihood and has no privacy/DQM assumption.')
    add(8,r'''Consider first the case where the original data $X_1,\ldots,X_n$ are observed. If, for some measurable function $g:\mathcal X\to G$ (often a power function $g(x)=(x,x^2,\ldots,x^p)$) with range $G=\{g(x):x\in\mathcal X\}\subseteq\mathbb R^p$, the function $f:\Theta\to G$, $f(\theta):=\mathbb E_\theta[g]$ has a continuous inverse $f^{-1}:G\to\Theta\subseteq\mathbb R^p$, then the moment estimator $\widehat\theta_n:=f^{-1}(\frac1n\sum_{i=1}^ng(X_i))$ is consistent.''',[15],'Source context for the method of moments. Theorem 4.3 rebinds g,f and the noisy estimator explicitly. Neither this paragraph nor the theorem supplies an extension of the inverse to noisy averages outside G.')
    add(9,r'''If Conditions (C1) and (C2) hold with $p=1$ and $k:\Theta\to\mathbb N$ and $T:\mathcal X\times\Theta\to\mathbb N$ are measurable with $T_\theta(x):=T(x,\theta)\le k(\theta)$ for all $(x,\theta)\in\mathcal X\times\Theta$, then there exists a Markov kernel $Q\in\mathfrak P(\mathbb N\times\Theta\to\mathbb N)$, such that $Q_\theta(C\mid y):=Q(C\mid y,\theta)$ ($\theta\in\Theta$, $C\subseteq[k(\theta)]$, $y\in[k(\theta)]$) satisfies for all $\theta\in\Theta$, $Q_\theta\in\mathcal Q_\alpha([k(\theta)]\to[k(\theta)])$ and
\[
I_\theta(Q_\theta T_\theta\mathcal P)=\max_{Q\in\mathcal Q_\alpha([k(\theta)]\to[k(\theta)])}I_\theta(QT_\theta\mathcal P).
\]
(4.5)
Furthermore, for every $\theta_0\in\Theta$ the function $\theta\mapsto I_{\theta_0}(Q_\theta T_\theta\mathcal P):\Theta\to\mathbb R_+$ is measurable.''',[19],'Full main-text Lemma 4.6 supplies the sense of measurable maximizer referenced in Theorem 4.11 and construction D15. Existence proof is in the supplement and remains excluded. This auxiliary lemma is not a Theorem inventory record.',['D1','D2','D6','D10','D11'])
    add(10,r'''Consider a model $\mathcal P=(P_\theta)_{\theta\in\Theta}$, $\Theta\subseteq\mathbb R^p$, on sample space $\mathcal X$ that is DQM at the points $\theta,\theta'\in\Theta$ with scores $s_\theta$ and $s_{\theta'}$. Then
\[
\sup_{Q\in\mathcal Q_\alpha(\mathcal X)}\|I_\theta(Q\mathcal P)-I_{\theta'}(Q\mathcal P)\|_2
\le e^{2\alpha}(\operatorname{tr}[I_\theta(\mathcal P)]\vee\operatorname{tr}[I_{\theta'}(\mathcal P)]\vee1)\left[2\left\|\|\dot p_\theta-\dot p_{\theta'}\|_{\ell_2}\right\|_{L^1(\mu)}+3\|p_\theta-p_{\theta'}\|_{L^1(\mu)}\right]=:\varphi(\theta,\theta'),
\]
(4.7)
with $\dot p_\theta(x):=s_\theta(x)p_\theta(x)\in\mathbb R^p$. Moreover, if Conditions (C1) and (C3) hold, then $\theta'\mapsto\varphi(\theta,\theta')$ is continuous at $\theta$ for every $\theta\in\Theta$.''',[20],'Complete main-text Lemma 4.10 defines the error modulus used by Theorem 4.11. Preserve e^(2alpha), both trace terms, coefficients 2 and 3, and nested L1/l2 norm. No separate named reusable predicate is invented for this local bound.',['D2','D5','D6','D10','D12'])
    add(11,r'''Furthermore, consider a model $(\mathcal X,\mathcal F,\mathcal P)$ that is DQM at $\theta\in\Theta\subseteq\mathbb R^p$ with score $s_\theta$ and a measurable mapping $T:\mathcal X\to[k]$. Write $\mathbf p_\theta:=(P_\theta T^{-1}(\{j\}))_{j\in[k]}\in\mathbb R^k$ and $\dot{\mathbf p}_\theta:=(\int_{T^{-1}(\{j\})}s_\theta(x)p_\theta(x)\mu(dx))_{j\in[k]}\in\mathbb R^{p\times k}$.
i) The set $\mathcal Q_\alpha([k]\to[\ell])$ can be identified with $\mathcal M_\alpha(\ell,k)$ as follows: For $M\in\mathcal M_\alpha(\ell,k)$, define $Q(C\mid y):=\sum_{i\in C}M_{i,y}$, $C\subseteq[\ell]$, $y\in[k]$. For $Q\in\mathcal Q_\alpha([k]\to[\ell])$, define $M_{i,y}:=Q(\{i\}\mid y)$, $i\in[\ell]$, $y\in[k]$.
ii) $\mathcal M_\alpha(\ell,k)\subseteq\mathbb R^{\ell\times k}$ is a compact polytope. (Lemma 23 of Kairouz, Oh and Viswanath, 2016)
iii) Consider the convex cone $\mathcal C_\alpha(k):=\{v\in\mathbb R^k:0\le v_j\le1,v_j\le e^\alpha v_{j'},\forall j,j'\in[k]\}$ and for $\theta\in\Theta$ and $v\in\mathcal C_\alpha(k)$, define $g_\theta(v):=\frac{\dot{\mathbf p}_\theta vv^T\dot{\mathbf p}_\theta^T}{v^T\mathbf p_\theta}\in\mathbb R^{p\times p}$, $g_\theta(0):=0$. Then $I_\theta(QT\mathcal P)=\sum_{i=1}^{\ell}g_\theta(Q_{i\cdot}^T)$ for all $Q\in\mathcal M_\alpha(\ell,k)$, and $g_\theta:\mathcal C_\alpha(k)\to\mathbb R^{p\times p}$ is continuous. Here, $Q_{i\cdot}\in\mathbb R^k$ denotes the $i$-th row of the matrix $Q$.
iv) If $p=1$, then $g_\theta:\mathcal C_\alpha(k)\to\mathbb R$ is convex and sublinear.''',[18,19],'Remaining main-text Lemma 4.5 specifies the matrix/kernel identification and objective formula. Keep zero-vector extension and source description of the bounded domain as a cone; that domain is not literally a cone under unrestricted positive scaling. The bold p denotes finite probability/derivative vectors, distinct from the density.',['D1','D2','D5','D6','D14'])
    add(12,r'''Notice that steps 1-5 above define the $\alpha$-sequentially interactive mechanism $Q^{(n)}$ extensively discussed in Subsection 4.2. This mechanism releases a locally private view $Z_1,\ldots,Z_n$ of $X_1,\ldots,X_n$. Specifically, conditional on $Z_1,\ldots,Z_{n_1}$, the $Z_{n_1+1},\ldots,Z_n$ are iid with counting density (pmf) $\widehat q_\theta$ and $\widehat Q_{n_1}\widehat T_{n_1}\in\mathcal Q_\alpha(\mathcal X\to\{1,\ldots,\widehat k_{n_1}\})$ (cf. Figure 1).''',[22],'Conditional iid second-group interpretation of D15. The adaptive full sample is not iid unconditionally.',['D2','D3','D15'])
    add(13,r'''Consequently, the overall privacy protocol can be formally expressed as an $\alpha$-sequential mechanism
\[
Q^{(n)}(dz_{1:n}\mid x_{1:n}):=\left[\bigotimes_{i=n_1+1}^n[\widehat Q_{n_1}\widehat T_{n_1}](dz_i\mid x_i,z_{1:n_1})\right]\left[\bigotimes_{j=1}^{n_1}Q_0(dz_j\mid x_j)\right],
\]
(4.3)
provided we can also show that $[\widehat Q_{n_1}\widehat T_{n_1}]\in\mathfrak P(\mathcal X\times\mathcal Z_0^{n_1}\to\mathbb N)$, that is, provided we can show measurability of $(x_i,z_{1:n_1})\mapsto[\widehat Q_{n_1}\widehat T_{n_1}](C\mid x_i,z_{1:n_1})$, for all $C\subseteq\mathbb N$ (see Lemma 4.6 and the ensuing discussion below).''',[17],'Explicit full experiment kernel referred to by Theorem 4.12; first-stage data determine the common second-stage private channel.',['D1','D2','D3','D4','D15'])
    add(14,r"""For $x,x'\in\mathcal X^n$, define $d_0(x,x'):=|\{i:x_i\ne x_i'\}|$ to be the Hamming distance, i.e., the number of differing components in $x$ and $x'$. Recall that for $\alpha\in(0,\infty)$, a Markov kernel $Q\in\mathfrak P(\mathcal X^n\to\mathcal Z)$ is called $\alpha$-differentially private, if, for all $A\in\mathcal G$ and for all $x,x'\in\mathcal X^n$ with $d_0(x,x')=1$, we have
\[
Q(A\mid x)\le e^\alpha Q(A\mid x').
\]
(1.3)
We sometimes also refer to such a Markov kernel as a privacy mechanism or a channel.""",[4],'Eventwise central privacy referenced for comparison in (1.6)-(1.7). Local privacy in the theorem mechanisms still imposes its stronger marginal all-input conditions; no additional central-data access is allowed.',['D1'])
    issues=[]
    def issue(k,t,ps):issues.append(dict(issue_id=k,description=t,evidence=[dict(page=p,location='Original source scope or convention') for p in ps]))
    issue('empty-product','The author writes Z^(0)=emptyset=G^(0) and A times emptyset=A as a formal convention. This is not literal Cartesian-product set theory; preserve the printed convention and flag it for later formalization.',[4,5])
    issue('unrestricted-output-class','Q_alpha(X) is a union over all measurable output spaces. Footnote 1 explicitly replaces scalar Fisher supremum notation by a supremum over attainable real numbers; the census retains that explanation.',[5])
    issue('moment-inverse-domain','Theorem 4.3 applies f^{-1}:G->Theta to the noisy mean of Z_i, but no extension or fallback outside G is given. The noisy mean need not belong to G. Preserve the theorem as printed; its domain issue is not solved by the census.',[15])
    issue('cross-parameter-lower-bound','Theorem 4.11 prints 0 <= sup_Q I_theta(QP)-I_theta_n1(Qhat That P) for arbitrary theta and theta_n1. Comparing information at different parameters does not by itself justify nonnegativity. Preserve the printed bound and flag its scope; the census does not certify or correct the claim.',[21])
    issue('bounded-cone','Lemma 4.5 calls C_alpha(k) a convex cone while imposing 0<=v_j<=1. The upper bound prevents closure under arbitrary positive scaling. Preserve the set and original wording, without dropping its upper bound.',[19])
    issue('appendix-density-reference','The fixed-channel MLE definition invokes q(z|x) from Lemma D.2. Its main-text integrated density and bounds are retained; the appendix lemma is not inspected or imported.',[14])
    issue('compact-consistency','Theorems 4.1 and 4.2 retain the event estimator in compact K in their convergence statements. They do not by themselves assert unrestricted consistency without an additional tightness or compact-parameter argument.',[14,15])
    issue('conditional-efficiency','Theorem 4.12 explicitly assumes consistency of the second-stage MLE. The procedure allows an arbitrary value when no maximizer exists. Neither consistency nor universal attainment is inferred from the efficiency conclusion.',[22])
    refs=[dict(from_claim_id=PID+'/T3.5',to_claim_id=PID+'/T3.3',reference_kind='definition_reference',scope='Only the displayed Sigma_n,theta definition is imported, retained as A6; no full-sequence weak convergence or LAMN assumption is added.'),dict(from_claim_id=PID+'/T4.2',to_claim_id=PID+'/T4.1',reference_kind='proof_only',scope='The proof verifies classical likelihood conditions for private densities. Theorem 4.2 does not assume those conditions independently.'),dict(from_claim_id=PID+'/T4.11',to_source_label='Lemma 4.6; Lemma 4.10',reference_kind='definition_reference',scope='Main-text statements retained in A9 and A10 specify the measurable selection and error modulus actually named in the theorem.'),dict(from_claim_id=PID+'/T4.11',to_source_label='Projection (4.6); Lemmas 4.7 and 4.9',reference_kind='proof_only',scope='Approximation and finite-output reduction are proof machinery, not additional hypotheses/definitions of the theorem estimator.'),dict(from_claim_id=PID+'/T4.12',to_source_label='Section 4.3 six-step construction; protocol (4.3)',reference_kind='definition_reference',scope='D15 and A12-A13 retain the estimator and full sample distribution explicitly imported by the theorem.'),dict(from_claim_id=PID+'/T4.2',to_source_label='Lemma D.2',reference_kind='appendix_reference_unresolved',scope='Referenced via private MLE D8. Preserve the main-text density formula and reference; do not read the appendix.')]
    bindings={
'T3.3':'Q^(n), its conditional kernels and experiment law resolve through D1-D3; DQM and score/information through D5-D6. Sigma and Delta are locally defined, with Sigma retained in A6 for the next theorem. D7 and A4 define the LAMN conclusion. Countable generation, nonzero original information and weak convergence are explicit hypotheses. The limit need not be positive definite. A5 fixes identity J_p and weak convergence.',
'T3.5':'D1-D3 define the experiment. D5-D6 and A6 resolve averaged conditional information. All finite-n information matrices and every weak accumulation point are assumed positive definite. The regular estimator/local-alternative limit D_theta, Gaussian convolution kernel and mixture representation are locally bound. No full-sequence LAMN assumption or conclusion is imported from Theorem 3.3.',
'T4.1':'A7 supplies the dominated raw-data model, and A5 its density/expectation conventions. Every likelihood, supremum, compact set and maximizer is bound in the theorem. Thus its ranked direct-interface list is empty without omitting the theorem. No private channel, DQM, Section 4 scalar restriction or two-stage estimator is imposed on this classical multivariate statement.',
'T4.2':'D1-D2 resolve QP, D5 with A3 resolves DQM at every parameter, and D8 defines the non-interactive private MLE including the integrated density and maximization. Identifiability is the ambient injectivity of theta->QP_theta, explicitly assumed. Compact-intersection convergence is retained; the classical Theorem 4.1 is a proof reference.',
'T4.3':'D9 supplies the hard l1-ball truncation; D4 defines the non-interactive privacy conclusion. g, its range G, f=E_theta g, the inverse, independent iid-component Laplace noise, Z_i, the estimator and both growth conditions are all bound in the theorem under the dominated model A7. The inverse-outside-G issue is retained separately. No DQM is assumed and no preliminary root-n rate is inferred.',
'T4.11':'C1-C3 resolve independently to D10-D12; D13 retains the full Definition 3 including Delta and convergence along arbitrary convergent parameters. D14 is the finite channel matrix domain, D1-D2 the kernel/privacy convention and D6 Fisher information. A9 defines the cited measurable-maximizer sense; A10 supplies phi; A2 the unrestricted scalar supremum. Q0, n1, the preliminary estimator, its plugged-in quantizer/alphabet, theta_n1, C_alpha and the consistency condition are theorem-local. The cross-parameter 0<= statement remains a source issue.',
'T4.12':'C1-C3 are D10-D12. D15 preserves every step of the estimator/experiment, with D3 and A12-A13 giving the sequential protocol and conditional iid second group. D1-D2,D6 and A2 resolve I*_alpha,theta0. Three density derivatives and their L1 regularity are explicit local assumptions, with the scalar parameter, positive information, n1->infinity, n1/n->0, consistency at theta0 and local h all retained. The final rate is sqrt(n); a root-n first-stage rate is not required.'}
    out=dict(paper_id=PID,status='extracted',unranked_auxiliary_passages=aux,source_issues=issues,source_claim_references=refs,statement_local_bindings=bindings,ambient_prerequisites=['Measurable spaces and Markov kernels, product laws, conditional expectations, sigma-finite densities, finite-dimensional matrix positivity, weak convergence, Gaussian laws, convolution, Laplace noise, L1/L2 spaces, continuity, compactness and likelihood maximization.','Identifiability retains its standard injectivity meaning for the parameter-indexed distribution family. Existence of measurable maximizers is assumed or explicitly qualified as in the source, not invented.'],extraction_policy='Main-text statements and their definitions only. Appendix references remain unresolved beyond their main-text formulas. Locally bound error moduli and conditional information are retained as auxiliary passages, not synthesized named APIs.')
    (ROOT/'ambient-prerequisites.json').write_text(json.dumps(out,indent=2,ensure_ascii=False)+'\n')
if __name__=='__main__':main()
