"""Save auxiliary source passages and unresolved conventions without changing originals."""
import json
from save_inventory import PID,ROOT
A=[];ISSUES=[]
def passage(n,s,pages,note):A.append(dict(local_id=f'A{n}',statement_original=s,evidence=[dict(page=p,location=f'Auxiliary source passage A{n}') for p in pages],scope_note=note))
def issue(key,text,pages):ISSUES.append(dict(issue_id=key,description=text,evidence=[dict(page=p,location='Source scope or notation') for p in pages]))
passage(1,r'''Let $\Delta^{m-1}$ be the $m-1$ dimensional probability simplex.''',[3],'Weights in Theorems 3 and 5 range over the usual nonnegative simplex with total mass one; the boundary is not excluded. The source names this ambient finite-dimensional object without expanding its inequalities.')
passage(2,r'''For any $x\in\mathbb R^d$, we use $\delta_x$ to denote the Dirac mass at point $x$.''',[3],'The atomic measures in Theorems 3, 5 and 6 use this named primitive. It is distinct from the first-variation prefix delta ell_N.')
passage(3,r'''For two probability measures $\mu,\nu\in\mathcal P(\mathbb R^d)$, we use $\mu\ll\nu$ to denote that $\mu$ is absolutely continuous with respect to $\nu$.''',[3],'The update ratios d(rho-new)/d(rho-old) use Radon–Nikodym derivatives. That ordinary measure-theoretic operation is implicit in the source rather than separately defined.')
passage(4,r'''In practice, however, we can only initialize from a discrete distribution with $m$ particles
\[
\rho_0=\sum_{l=1}^m\omega_0^{(l)}\delta_{\mu^{(l)}},\text{ where }\mu^{(1)},\ldots,\mu^{(m)}\in\mathbb R^d\text{ and }\omega_0=(\omega_0^{(1)},\ldots,\omega_0^{(m)})\in\Delta^{m-1}.
\]
The following theorem characterizes the Fisher-Rao gradient flow when initialized from a discrete distribution $\rho_0$ with $m$ mass points.''',[8],'Standing fixed locations for Theorem 5. The theorem does not assume the randomly sampled locations used by the implementation Algorithm 2.')
passage(5,r'''When initialized from a discrete distribution
\[
\rho_0=\frac1m\sum_{l=1}^m\delta_{\mu_0^{(l)}},\text{ where }\mu_0^{(1)},\ldots,\mu_0^{(m)}\in\mathbb R^d,
\]
the following theorem gives a concise characterization of the Wasserstein gradient flow.''',[9],'Standing equal-weight initialization for Theorem 6. Its displayed ODE still contains an unexplained omega_t^(j); this passage is not used to silently replace that symbol in the original theorem.')
passage(6,r'''While this will not be useful for our problem, it is worth noting that
\[
d_{\mathrm{FR}}^2(\rho_0,\rho_1)=4\int\left|\sqrt{\frac{d\rho_0}{d\lambda}}-\sqrt{\frac{d\rho_1}{d\lambda}}\right|^2d\lambda,
\]
where $\lambda$ is any positive measure such that $\rho_0,\rho_1\ll\lambda$ (e.g., $\lambda=\rho_0+\rho_1$.). Hence, up to a constant factor, the Fisher-Rao distance is simply the Hellinger distance that is well-known to statisticians.''',[4,5],'This claimed closed form is preserved separately from the centered probability-preserving action (3.2). Their equivalence is not certified by the census.')
passage(7,r'''The proof techniques employed to establish Theorem 2 do not cover Algorithm 1 unfortunately since the initial measure is not supported on the whole space. Nevertheless, since the NPMLE is known to be supported on a small number of atoms (Polyanskiy and Wu, 2020) in certain cases, it is likely that taking $m$ large enough will be sufficient to establish convergence results. This conjecture is supported by our numerical experiments in Section 4.''',[7],'Explicit source limitation: Theorem 2 is not a convergence guarantee for the finite-particle algorithm. The conjecture is not a stored theorem.')
passage(8,r'''We show in Appendix B.1 that for any $\rho\in\mathcal P(\mathbb R^d)$, $\int\delta\ell_N(\rho)d\rho=-1$ always holds. As a result, the optimality condition (ii) in Theorem 1 is implied by (i), which means that $\delta\ell_N(\widehat\rho)(x)\geq-1$ for all $x\in\mathbb R$ alone is already the necessary and sufficient condition for $\widehat\rho$ to be the NPMLE. However, we keep both conditions in the theorem as each of them reveal important structural information of NPMLE.''',[3],'Remark 1 supplies the first-variation mean identity underlying the reaction normalization. Its R instead of R^d is retained as printed. The theorem itself retains both conditions and its R^d domain; the appendix proof is excluded.')
passage(9,r'''Theorem 1 asserts the existence of NPMLE, but its uniqueness when $d\geq2$ is still an open problem. Although the uniqueness is not settled, the convergence theory in this paper is still valid: in this case NPMLE refers to any minimizer of (1.1).''',[3],'This is the source-version interpretation of the definite article in Theorems 2 and 4. It is not a current claim about the literature.')
passage(10,r'''We can also show a similar result for the continuous-time Fisher-Rao gradient flow $(\rho_t)_{t\geq0}$ (i.e. a distributional solution to the PDE (3.11)): if $\rho_t\xrightarrow{\mathrm w}\widehat\rho$ as $t\to\infty$, then $\widehat\rho$ is an NPMLE.''',[8],'Unnumbered assertion after Theorem 4, retained as scope context only. It does not expand the six-theorem inventory or replace the discrete iteration named in Theorem 4.')
passage(11,r'''Recall that a geodesic distance between two points measures the shortest curve that links these two points.''',[4],'Endpoint constraints in the dynamic distance formulas are expressed in surrounding prose, not explicitly repeated in each displayed infimum. Curves join the indicated rho_0 and rho_1; admissible regularity remains unspecified.')
issue('source-version','The inspected arXiv v1 has a January 5, 2023 title-page date and a 4 Jan 2023 arXiv stamp. It is the registered PDF, not the published AoS text; both dates and the version-specific URL are preserved.',[1])
issue('conditional-convergence','Theorems 2 and 4 assume weak convergence of the full sequence before identifying its limit. They do not establish existence of a limit or a convergence rate.',[6,8])
issue('step-size-mismatch','Iteration (3.12) uses gamma>0. Theorem 4 instead bounds eta by eta0 without explicitly identifying eta with gamma, and omits eta0>0. The original symbols and quantifiers are preserved.',[7,8])
issue('printed-weight-index','Both denominators in Theorem 3 and the denominator in Theorem 6 use omega_t^(j) inside a sum indexed by l. Theorem 5 uses omega_t^(l). The printed j indices are not changed to the mathematically expected l indices.',[6,8,9])
issue('unbound-wasserstein-weight','Theorem 6 has no weight dynamics or explicit definition of omega_t^(j), although its ODE uses that symbol and its measure formula uses equal weights 1/m. The preceding equal-weight initialization is retained separately, without repairing the ODE.',[9])
issue('zero-weight-denominator','The simplex allows zero weights. The j-indexed denominator in Theorem 3 is then zero for a zero-weight particle, so the displayed ODE is not defined literally on the entire stated initial simplex.',[3,6])
issue('particle-pde-consistency','With the printed j-indexed denominators, mass preservation and agreement of Theorem 3 with PDE (3.6) require clarification. Source review records the claimed equality without proving it or changing the formula.',[5,6])
issue('empirical-uniform-law','Uniform sampling from the indexed sample can mean uniform over indices or over distinct values when observations coincide. The source does not clarify this distinction.',[6,9])
issue('time-quantifiers','The ODE claims state unique solutions on any interval [0,T] without separately specifying T>=0, solution regularity, or how the assertion is quantified over the random initial locations.',[6,8,9])
issue('finite-dimensions','Positive finite integers N, m and d are implicit in the sample averages, simplex, and equal-weight formulas. Their domains are not repeated in every theorem.',[1,3,6,8,9])
issue('probability-versus-p2','The optimization and convergence theorems use all probability measures. The WFR flow passage uses P2. A finite-second-moment restriction must not be imported into Theorems 1, 2 or 4 merely from the flow overview.',[2,3,5,6,8])
issue('pushforward-measurability','The source defines pushforward for any mapping but does not state Borel measurability. A measurable map is needed for the usual Borel image-measure construction.',[3])
issue('weak-pde-time','The distributional-solution definition uses spatial test functions and an ordinary derivative in time. It does not specify temporal absolute continuity, pointwise versus almost-everywhere time equality, or integrability of the fields.',[3])
issue('measure-gradient-limit','The overview writes a difference quotient of measures and a limit eta->0 without specifying a topology, a one-sided positive limit, or minimizer selection. It expressly leaves existence of the limiting curve untreated.',[4])
issue('metric-admissibility','Dynamic distance displays omit explicit endpoint restrictions and admissible regularity of curves and fields. The prose supplies the endpoints but not a complete analytic domain.',[4,5])
issue('fisher-rao-identity','The source defines a centered probability-preserving reaction action and then states a four-times-Hellinger-squared closed form. The compatibility of these two descriptions requires separate mathematical review; neither is silently substituted for the other.',[4,5])
issue('wasserstein-finiteness','The static quadratic coupling formula is stated for all probability measures. It can have infinite value without further moment assumptions; the source does not state an extended-metric convention there.',[5])
issue('first-variation-representative','The explicit first variation has a fixed additive constant and mean -1. A generic first variation modulo constants cannot replace it unchanged in reaction formulas containing 1+delta ell_N.',[3,5,7])
issue('update-nonnegativity','The measure update definitions allow a positive step size without an explicit condition ensuring a nonnegative density multiplier. Theorems 2 and 4 discuss small steps, with the separate gamma/eta mismatch in Theorem 4.',[6,7,8])
issue('particle-algorithm-order','Algorithm 1 updates locations before weights, while (3.7) updates weights then transports the intermediate measure. Its printed denominators also use j-indexed weights. The algorithm is not substituted for the iteration in Theorem 2.',[6,7])
issue('finite-particle-support','A finite atomic initialization does not have full support on R^d. The source explicitly excludes Algorithm 1 from Theorem 2 coverage; analogous finite-support issues prevent treating Theorem 4 as a guarantee for arbitrary fixed particles.',[6,7,8])
issue('theorem5-locations','Theorem 5 uses arbitrary fixed real locations introduced in preceding prose. It does not assume their randomized initialization from Algorithm 2.',[8,9])
issue('remark-domain','Remark 1 uses x in R where Theorem 1 uses R^d. The remark is retained as source context without changing the theorem domain or dropping its second condition.',[3])
issue('nonunique-estimator','The source uses NPMLE to mean any minimizer. No tie-breaking rule or uniqueness assumption is inserted into the conditional-limit statements.',[3,6,8])
issue('excluded-claims','References to appendix Theorems 7 and 8 and the unnumbered continuous-time statement after Theorem 4 are not main-text Theorem environments. Appendix bodies and proof derivations are excluded.',[6,8,9])
RESOLUTION={
'shared':{'local_objects':'D1 gives the Gaussian kernel/convolution and sample setup, D2 the likelihood, D3 the NPMLE, D4 probability classes, D5 support, D6 pushforward, D7 weak convergence, D8 the distributional PDE convention, D9 first variation, D10/D13 the two discrete iterations, D11/D12/D14 the three flow PDEs, and D15–D18 the named geometric constructions.', 'ambient_or_bound':'A1/A2 give the simplex and Dirac notation; A3 the absolute-continuity convention. RN densities, gradients, divergence, Euclidean norm, finite sums, scalar derivatives, ordinary probability laws and Borel integration remain ambient. Couplings are probability measures with the two named marginals, as specified in the source distance passage.', 'source_scope':'Main text only. Alternative mirror/proximal interpretations are explanatory identities rather than extra theorem hypotheses. Appendix bodies are excluded.'},
'1':{'local_objects':'D3 resolves (1.1), D9 the explicit first variation and D4 the probability-measure domain.', 'ambient_or_bound':'x and rho-hat are locally quantified. Almost-everywhere equality refers to rho-hat. Gaussian convolution and observed samples enter through the likelihood.', 'branch_scope':'Existence and both directions of the two-condition optimality characterization are retained.'},
'2':{'local_objects':'D4/D5 give the full-support initial distribution, D10 the ordered measure iteration, D7 weak convergence, D3 the NPMLE target.', 'ambient_or_bound':'eta0 depends on the observed sample; eta and its bound are local hypotheses. The iteration uses an RN density and a measurable transport pushforward.', 'branch_scope':'Only conditional limit optimality; no finite-particle algorithm or continuous-time flow is an assumption.'},
'3':{'local_objects':'D1 supplies phi and the observed samples; D11 is PDE (3.6) with its WFR geometry; D8 supplies the meaning of distributional solution.', 'ambient_or_bound':'The coupled ODE and atomic measure are defined inline. A1 gives the simplex and A2 Dirac masses. Uniform initial positions, T and m are local parameters with unresolved conventions recorded separately.', 'branch_scope':'Location and weight dynamics are joint. The printed j-indexed denominator and zero-weight problem remain unresolved source content.'},
'4':{'local_objects':'D4/D5 supply the initial probability and support, D13 iteration (3.12), D7 weak convergence, D3 the NPMLE target.', 'ambient_or_bound':'The source uses eta/eta0 in the theorem, gamma in the iteration. No identification is silently inserted.', 'branch_scope':'The discrete theorem is separate from the unnumbered continuous-time claim in A10.'},
'5':{'local_objects':'D1 supplies the Gaussian kernel; D12 identifies PDE (3.11) and its geometry; D8 supplies distributional solution.', 'ambient_or_bound':'The ODE and weighted atomic curve are inline. A4 preserves arbitrary fixed locations, A1 the simplex and A2 Dirac masses.', 'branch_scope':'Only weights evolve, with l-indexed denominator weights as printed. No random initialization or discrete convergence theorem is imported.'},
'6':{'local_objects':'D1 supplies the Gaussian kernel; D14 gives PDE (3.18) and its Wasserstein geometry; D8 gives distributional solution.', 'ambient_or_bound':'The position ODE and equal-weight atomic curve are inline. A5 records equal-weight initialization, A2 Dirac masses. omega_t^(j) in the ODE has unresolved meaning in this source statement.', 'branch_scope':'Preserve the claim about the printed ODE and equal-weight curve without correcting the unexplained weight or importing a convergence theorem.'}}
def main():
    data=dict(paper_id=PID,unranked_auxiliary_passages=A,source_issues=ISSUES,statement_resolution=RESOLUTION,unresolved_source_references=[dict(reference='Appendices A–F and cited technical derivations',status='excluded_by_scope',resolution='References preserved where relevant; appendix bodies not consulted.'),dict(reference='omega_t^(j) in Theorem 6',status='unresolved_source_notation',resolution='Standing equal-weight measure recorded, but the unexplained ODE weight is preserved without repair.')])
    (ROOT/'ambient-prerequisites.json').write_text(json.dumps(data,indent=2,ensure_ascii=False)+'\n')
    print(f'Saved {len(A)} auxiliary passages and {len(ISSUES)} source issues.')
if __name__=='__main__':main()
